// GENERATED by build/resolveTemplateVersions.ts from the workspace. Do not edit by hand.
// Bump the package versions / catalog and re-run `pnpm run build:versions`.

/**
 * Dependency versions baked into the scaffold, kept in sync with this repo.
 *
 * @evidence requirements/agent-authoring/project-ownership.md#agent-portable-authoring Pins the documented toolchain inputs a generated project needs in a new checkout.
 * @evidence specifications/authoring-and-authority/source-authority-and-derivation.md#spec-authoring-source-input Emits explicit dependency versions instead of reading undeclared host state.
 */
export const AUTOMOVIE_TEMPLATE_VERSIONS: Record<string, string> = {
  archetypes: "^0.1.0",
  cli: "^0.1.0",
  engine: "^0.1.0",
  evidence: "^0.1.0",
  human: "^0.1.0",
  ingest: "^0.1.0",
  interface: "^0.1.0",
  mcp: "^0.1.0",
  production: "^0.1.0",
  render: "^0.1.0",
  template: "^0.1.5",
  viewer: "^0.1.0",
  huggingFaceTransformers: "3.8.1",
  h264Mp4Encoder: "^1.0.12",
  kokoroJs: "1.2.1",
  libopusWasm: "^0.2.0",
  mp4box: "^2.4.1",
  onnxruntimeNode: "1.21.0",
  playwright: "^1.60.0",
  pngjs: "^7.0.0",
  pngjsTypes: "^6.0.5",
  three: "^0.186.0",
  threeTypes: "^0.186.0",
  vite: "^5.4.10",
  nodeTypes: "^22.19.17",
  ttsc: "^0.29.0",
  ttscLint: "^0.29.0",
  typescript: "^7.0.2",
};
