import type {
  AutoMovieContentDigest,
  IAutoMovieBuildProjectOutput,
  IAutoMovieDiagnostic,
} from "@automovie/interface";
import { createHash } from "node:crypto";
import path from "node:path";

import { loadSourceModule } from "../internal/loadSourceModule";

/** One document or owned file and the digest read for it. */
export interface ISourceStatusEntry {
  path: string;
  digest: AutoMovieContentDigest | null;
}

/** The snapshot the retained source status compares, field for field. */
export interface ISourceStatusSnapshot {
  revision: number;
  inputFingerprint: AutoMovieContentDigest;
  resident: AutoMovieContentDigest | null;
  screenplay: AutoMovieContentDigest | null;
  documents: ISourceStatusEntry[];
  generated: {
    inputFingerprint: AutoMovieContentDigest | null;
    manifest: AutoMovieContentDigest | null;
    files: ISourceStatusEntry[];
  };
}

/** What one read-only source gate run reports. */
export interface ISourceStatusEvaluation {
  output: IAutoMovieBuildProjectOutput;
  documents: ISourceStatusEntry[];
  undeclaredModules: string[];
  revisionBound: boolean;
}

/** Absolute path of one private production module. */
export const productionModule = (file: string): string =>
  path.resolve(
    __dirname,
    "../../../../packages/production/src/production",
    file,
  );

/** The retention entry point, loaded from its private module. */
export const { retainAutoMovieProductionSourceStatus } = loadSourceModule<{
  retainAutoMovieProductionSourceStatus(props: {
    acquire: (documents: readonly string[]) => ISourceStatusSnapshot | null;
    evaluate: () => ISourceStatusEvaluation;
  }): () => IAutoMovieBuildProjectOutput;
}>(productionModule("retainAutoMovieProductionSourceStatus.ts"));

/** Content digest of one UTF-8 text: `sha256:` and the lowercase hex hash. */
export const textDigest = (text: string): AutoMovieContentDigest =>
  `sha256:${createHash("sha256").update(text, "utf8").digest("hex")}`;

/** Input identity the in-memory builder derives from one source text. */
export const fingerprintOf = (source: string): AutoMovieContentDigest =>
  textDigest(`source\0${source}`);

/** Generated bytes the in-memory builder publishes for one source text. */
export const generatedBytesOf = (source: string): string =>
  `compiled shot for ${source}`;

/** The screenplay document the in-memory validation reads. */
export const SCREENPLAY_DOCUMENT = "docs/screenplays/001-harbor.md";

/** Refusal the in-memory gate reports for invalid source. */
export const SOURCE_FAILURE: IAutoMovieDiagnostic = {
  code: "source-execution-failed",
  category: "error",
  phase: "source",
  target: "shot:opening",
  path: "src/shots/opening.ts",
  message: "Source export opening threw while building its shot program.",
};

/** Refusal the in-memory gate reports for output compiled from other source. */
export const GENERATED_STALE: IAutoMovieDiagnostic = {
  code: "generated-stale",
  category: "error",
  phase: "compile",
  target: "generated-manifest",
  path: "automovie/productions/harbor/generated-manifest.json",
  message: "Generated input differs from current source.",
};

/** Refusal the in-memory gate reports for edited builder-owned bytes. */
export const GENERATED_TAMPERED: IAutoMovieDiagnostic = {
  code: "generated-tampered",
  category: "error",
  phase: "compile",
  target: "shots/opening.json",
  path: "generated/harbor/shots/opening.json",
  message: "Generated digest differs from the builder-derived digest.",
};

/** Mutable project facts one in-memory gate answers for. */
export interface ISourceStatusState {
  revision: number;
  source: string;
  compiled: string;
  generated: string;
  valid: boolean;
  resident: AutoMovieContentDigest | null;
  screenplay: string | null;
  documents: Map<string, string | null>;
  read: string[];
  undeclaredModules: string[];
  incomplete: boolean;
  revisionBound: boolean;
}

/** The answer the in-memory gate gives for one state and its findings. */
export const answerOf = (
  state: ISourceStatusState,
  diagnostics: readonly IAutoMovieDiagnostic[],
): IAutoMovieBuildProjectOutput => ({
  success: diagnostics.length === 0,
  revision: state.revision,
  builder: { version: "unit", inputFingerprint: fingerprintOf(state.source) },
  diagnostics: [...diagnostics],
  materialized: [],
});

/**
 * A project a source gate can read and a builder can compile, in memory.
 *
 * The input identity is the digest of the source text. A compile records the
 * source it compiled and the bytes it published and advances the revision. The
 * gate succeeds only when the source is valid, the output was compiled from the
 * current source, and its bytes are untouched, which are the validation and
 * ownership facts the real gate decides. Hooks place a concurrent edit at an
 * exact point inside a read or a run, and counters record every run and read.
 */
export const createSourceStatusWorld = () => {
  const initial = "export const opening = defineShot({ beats: 3 });\n";
  const state: ISourceStatusState = {
    revision: 7,
    source: initial,
    compiled: initial,
    generated: generatedBytesOf(initial),
    valid: true,
    resident: null,
    screenplay: "treatment and scene index v1",
    documents: new Map([[SCREENPLAY_DOCUMENT, "INT. HARBOR - NIGHT"]]),
    read: [SCREENPLAY_DOCUMENT],
    undeclaredModules: [],
    incomplete: false,
    revisionBound: false,
  };
  const counts = { evaluations: 0, acquisitions: 0 };
  const hooks = {
    acquire: (): void => undefined,
    snapshot: (_snapshot: ISourceStatusSnapshot): void => undefined,
    beforeRead: (): void => undefined,
    read: (_index: number): void => undefined,
    afterRead: (): void => undefined,
    output: (_output: IAutoMovieBuildProjectOutput): void => undefined,
    afterAnswer: (): void => undefined,
  };
  const documentDigest = (file: string): AutoMovieContentDigest | null => {
    const text = state.documents.get(file);
    return text === undefined || text === null ? null : textDigest(text);
  };
  const acquire = (
    documents: readonly string[],
  ): ISourceStatusSnapshot | null => {
    counts.acquisitions += 1;
    hooks.acquire();
    if (state.incomplete) return null;
    const snapshot: ISourceStatusSnapshot = {
      revision: state.revision,
      inputFingerprint: fingerprintOf(state.source),
      resident: state.resident,
      screenplay:
        state.screenplay === null ? null : textDigest(state.screenplay),
      documents: [...new Set(documents)]
        .sort((left, right) => (left < right ? -1 : left > right ? 1 : 0))
        .map((file) => ({ path: file, digest: documentDigest(file) })),
      generated: {
        inputFingerprint: fingerprintOf(state.compiled),
        manifest: textDigest(`manifest\0${state.compiled}`),
        files: [
          { path: "shots/opening.json", digest: textDigest(state.generated) },
        ],
      },
    };
    hooks.snapshot(snapshot);
    return snapshot;
  };
  const evaluate = (): ISourceStatusEvaluation => {
    counts.evaluations += 1;
    hooks.beforeRead();
    const documents = state.read.map((file, index) => {
      hooks.read(index);
      return { path: file, digest: documentDigest(file) };
    });
    hooks.afterRead();
    const output = answerOf(state, [
      ...(state.valid ? [] : [SOURCE_FAILURE]),
      ...(state.compiled === state.source ? [] : [GENERATED_STALE]),
      ...(state.generated === generatedBytesOf(state.compiled)
        ? []
        : [GENERATED_TAMPERED]),
    ]);
    hooks.output(output);
    hooks.afterAnswer();
    return {
      output,
      documents,
      undeclaredModules: [...state.undeclaredModules],
      revisionBound: state.revisionBound,
    };
  };
  return {
    state,
    counts,
    hooks,
    acquire,
    evaluate,
    status: () => retainAutoMovieProductionSourceStatus({ acquire, evaluate }),
    compile: (): void => {
      state.compiled = state.source;
      state.generated = generatedBytesOf(state.source);
      state.revision += 1;
    },
  };
};

/** Gate runs each successive status call caused. */
export const runsPerCall = (
  world: ReturnType<typeof createSourceStatusWorld>,
  status: () => IAutoMovieBuildProjectOutput,
  calls: number,
): { runs: number[]; answers: IAutoMovieBuildProjectOutput[] } => {
  const runs: number[] = [];
  const answers: IAutoMovieBuildProjectOutput[] = [];
  for (let call = 0; call < calls; ++call) {
    const before = world.counts.evaluations;
    answers.push(status());
    runs.push(world.counts.evaluations - before);
  }
  return { runs, answers };
};
