import type { IAutoMovieProductionEvidence } from "@automovie/evidence";
import {
  AutoMovieProductionCompiler,
  AutoMovieProductionProject,
  digestAutoMovieBytes,
  normalizeAutoMovieSource,
} from "@automovie/production";
import { TestValidator } from "@nestia/e2e";

import { namedFacts } from "../internal/predicates";
import {
  LIBRARY_SOURCE,
  libraryAuthoring,
  libraryFixture,
} from "./libraryFixtures";

const PRODUCTION_SOURCE = "src/production/delivery.ts";
const PRODUCTION_OWNER = "docs/settings/production.md#delivery";

const productionModule = (payload: "empty" | "environment" = "empty") =>
  `import type { IAutoMovieLibrarySourceOwner } from "@automovie/interface";

export const delivery = {
  design: ${JSON.stringify(PRODUCTION_OWNER)},
  build: () => ({
    environments: ${payload === "empty" ? "[]" : "[{ id: 'forbidden' }]"},
    models: [],
  }),
} satisfies IAutoMovieLibrarySourceOwner;
`;

const productionAuthoring = (props: {
  root: string;
  source: string;
  enforced?: boolean;
}): IAutoMovieProductionEvidence => {
  const base = libraryAuthoring({ root: props.root });
  return {
    ...base,
    sourceOwners: [
      ...base.sourceOwners,
      {
        branch: "productionSources",
        stage: "review",
        enforced: props.enforced ?? true,
        relationship: "lineage",
        sourcePath: PRODUCTION_SOURCE,
        exportName: "delivery",
        symbolKind: "property",
        sourceDigest: digestAutoMovieBytes(
          normalizeAutoMovieSource(Buffer.from(props.source)),
        ),
        targetPath: "docs/settings/production.md",
        targetAnchor: "delivery",
        reviewed: true,
      },
    ],
  };
};

/**
 * Library publication executes settings source and reopens all input identity.
 *
 * Scenarios:
 *
 * 1. A selected production source executes as an exact zero-payload delivery,
 *    and the index records its owner, source, export, digest and compile identity.
 * 2. Changing only that source changes the compiler fingerprint on recompile.
 * 3. Missing owner export and semantic payload are refused at the exact source.
 * 4. A current authoring graph change or absent current provider fails closed
 *    before any generated byte is published.
 * 5. Disabled production-source residue is neither executed nor fingerprinted.
 */
export const test_production_library_source_currentness = (): void => {
  const fixture = libraryFixture();
  const staleGraph = libraryFixture();
  const noProvider = libraryFixture();
  const disabled = libraryFixture();
  const missingExport = libraryFixture();
  const semanticPayload = libraryFixture();
  try {
    const source = productionModule();
    fixture.write(PRODUCTION_SOURCE, source);
    const current = () => productionAuthoring({ root: fixture.root, source });
    const first = new AutoMovieProductionCompiler(
      AutoMovieProductionProject.open(fixture.root),
      current(),
      current,
    ).compile({ scope: "source" });
    const firstIndex = JSON.parse(
      fixture.generated("library/index.json") ?? "null",
    ) as {
      inputFingerprint: string;
      owners: Array<{
        branch: string;
        owner: string;
        source: string;
        export: string;
        sourceDigest: string;
        environments: string[];
        models: string[];
        contexts: string[];
      }>;
    } | null;
    const delivery = firstIndex?.owners.find(
      (owner) => owner.branch === "productionSources",
    );

    const changedSource = `${source}// settings revision\n`;
    fixture.write(PRODUCTION_SOURCE, changedSource);
    const changedCurrent = () =>
      productionAuthoring({ root: fixture.root, source: changedSource });
    const changed = new AutoMovieProductionCompiler(
      AutoMovieProductionProject.open(fixture.root),
      changedCurrent(),
      changedCurrent,
    ).compile({ scope: "source" });

    TestValidator.equals(
      "reviewed production source is an executed, fingerprinted delivery",
      namedFacts([
        ["firstCompileSucceeded", () => first.success],
        [
          "deliveryCarriesExactAttribution",
          () =>
            delivery?.owner === PRODUCTION_OWNER &&
            delivery.source === PRODUCTION_SOURCE &&
            delivery.export === "delivery" &&
            delivery.sourceDigest.startsWith("sha256:"),
        ],
        [
          "deliveryIsIntentionallyZeroPayload",
          () =>
            delivery?.environments.length === 0 &&
            delivery.models.length === 0 &&
            delivery.contexts.length === 0,
        ],
        [
          "deliverySharesCompileIdentity",
          () =>
            firstIndex?.inputFingerprint === first.compiler.inputFingerprint,
        ],
        [
          "sourceOnlyChangeRecompilesAtNewIdentity",
          () =>
            changed.success &&
            changed.compiler.inputFingerprint !==
              first.compiler.inputFingerprint,
        ],
      ]),
      {
        firstCompileSucceeded: true,
        deliveryCarriesExactAttribution: true,
        deliveryIsIntentionallyZeroPayload: true,
        deliverySharesCompileIdentity: true,
        sourceOnlyChangeRecompilesAtNewIdentity: true,
      },
    );

    const initialEvidence = libraryAuthoring({ root: staleGraph.root });
    const changedEvidence = {
      ...initialEvidence,
      designOwners: initialEvidence.designOwners.map((owner) => ({
        ...owner,
        units: owner.units.map((unit) => ({
          ...unit,
          digest: "b".repeat(64),
        })),
      })),
    };
    let graphReads = 0;
    const raced = new AutoMovieProductionCompiler(
      AutoMovieProductionProject.open(staleGraph.root),
      initialEvidence,
      () => (++graphReads === 1 ? initialEvidence : changedEvidence),
    ).compile({ scope: "source" });
    const unguarded = new AutoMovieProductionCompiler(
      AutoMovieProductionProject.open(noProvider.root),
      libraryAuthoring({ root: noProvider.root }),
    ).compile({ scope: "source" });

    TestValidator.equals(
      "library publication fails closed unless the fresh graph still matches",
      namedFacts([
        [
          "graphChangeUsesStableRaceDiagnostic",
          () =>
            raced.success === false &&
            raced.diagnostics.some(
              (diagnostic) => diagnostic.code === "compile-input-changed",
            ),
        ],
        [
          "graphChangePublishesNothing",
          () => staleGraph.generated("library/index.json") === null,
        ],
        [
          "missingProviderAlsoFailsClosed",
          () =>
            unguarded.success === false &&
            unguarded.diagnostics.some(
              (diagnostic) => diagnostic.code === "compile-input-changed",
            ),
        ],
        [
          "missingProviderPublishesNothing",
          () => noProvider.generated("library/index.json") === null,
        ],
      ]),
      {
        graphChangeUsesStableRaceDiagnostic: true,
        graphChangePublishesNothing: true,
        missingProviderAlsoFailsClosed: true,
        missingProviderPublishesNothing: true,
      },
    );

    const disabledFirst = `${productionModule()}// disabled first\n`;
    disabled.write(PRODUCTION_SOURCE, disabledFirst);
    const disabledEvidence = productionAuthoring({
      root: disabled.root,
      source: disabledFirst,
      enforced: false,
    });
    const disabledInitial = new AutoMovieProductionCompiler(
      AutoMovieProductionProject.open(disabled.root),
      disabledEvidence,
      () => disabledEvidence,
    ).compile({ scope: "source" });
    const disabledSecond = `${productionModule()}// disabled second\n`;
    disabled.write(PRODUCTION_SOURCE, disabledSecond);
    const disabledChangedEvidence = productionAuthoring({
      root: disabled.root,
      source: disabledSecond,
      enforced: false,
    });
    const disabledChanged = new AutoMovieProductionCompiler(
      AutoMovieProductionProject.open(disabled.root),
      disabledChangedEvidence,
      () => disabledChangedEvidence,
    ).compile({ scope: "source" });

    const absentExportSource = "export const helper = 1;\n";
    missingExport.write(PRODUCTION_SOURCE, absentExportSource);
    const absentExportEvidence = () =>
      productionAuthoring({
        root: missingExport.root,
        source: absentExportSource,
      });
    const absent = new AutoMovieProductionCompiler(
      AutoMovieProductionProject.openReadOnly(missingExport.root),
      absentExportEvidence(),
      absentExportEvidence,
    ).lint({ scope: "review" });

    const payloadSource = productionModule("environment");
    semanticPayload.write(PRODUCTION_SOURCE, payloadSource);
    const payloadEvidence = () =>
      productionAuthoring({
        root: semanticPayload.root,
        source: payloadSource,
      });
    const payload = new AutoMovieProductionCompiler(
      AutoMovieProductionProject.openReadOnly(semanticPayload.root),
      payloadEvidence(),
      payloadEvidence,
    ).lint({ scope: "source" });

    TestValidator.equals(
      "production-source non-delivery and inactive residue stay outside output",
      namedFacts([
        [
          "disabledBytesDoNotChangeFingerprint",
          () =>
            disabledInitial.success &&
            disabledChanged.success &&
            disabledInitial.compiler.inputFingerprint ===
              disabledChanged.compiler.inputFingerprint,
        ],
        [
          "disabledOwnerIsNotPublished",
          () =>
            !JSON.parse(
              disabled.generated("library/index.json") ?? "null",
            )?.owners.some(
              (owner: { branch: string }) =>
                owner.branch === "productionSources",
            ),
        ],
        [
          "selectedSourceWithoutExportIsRefused",
          () =>
            absent.success === false &&
            absent.diagnostics.some(
              (diagnostic) =>
                diagnostic.code === "source-export-missing" &&
                diagnostic.target ===
                  `library:productionSources:${PRODUCTION_OWNER}`,
            ),
        ],
        [
          "productionSourceCannotPublishSemanticPayload",
          () =>
            payload.success === false &&
            payload.diagnostics.some(
              (diagnostic) =>
                diagnostic.code === "source-export-invalid" &&
                diagnostic.path === PRODUCTION_SOURCE,
            ),
        ],
      ]),
      {
        disabledBytesDoNotChangeFingerprint: true,
        disabledOwnerIsNotPublished: true,
        selectedSourceWithoutExportIsRefused: true,
        productionSourceCannotPublishSemanticPayload: true,
      },
    );
  } finally {
    fixture.dispose();
    staleGraph.dispose();
    noProvider.dispose();
    disabled.dispose();
    missingExport.dispose();
    semanticPayload.dispose();
  }
};
