import { TestValidator } from "@nestia/e2e";

import {
  GENERATED_STALE,
  GENERATED_TAMPERED,
  SCREENPLAY_DOCUMENT,
  answerOf,
  createSourceStatusWorld,
  runsPerCall,
  textDigest,
} from "./sourceStatusFixtures";

/**
 * An unchanged successful gate answer is reused only behind a fresh read.
 *
 * A capture reaches the read-only source gate at five boundaries: before it
 * draws, after the pixels return, before and after the files are applied inside
 * the commit lock, and when its receipt is reopened. The answer depends on the
 * source, the documents validation read, the screenplay index, the builder-owned
 * output and the resident guard, and on the revision only when the answer read
 * the revision number into what it judged. Every boundary must read those again,
 * a boundary that finds them unchanged must not execute authored source, and one
 * changed input must run the gate exactly once more.
 *
 * Scenarios:
 *
 * 1. Five boundaries over unchanged inputs run the gate once, read the project
 *    once at each later boundary, and give the same answer every time.
 * 2. Mutating a reused answer leaves the next answer intact.
 * 3. A document edit, a screenplay index edit and a resident guard change each
 *    run the gate once, and the next boundary reuses it.
 * 4. A project write that moves no gate input, such as a render commit, reuses the
 *    answer under the new revision without running the gate, while an answer
 *    that read the revision into what it judged runs once more and is then
 *    reused.
 * 5. Tampered generated bytes run the gate and fail with the tamper diagnostic
 *    at every boundary until a compile restores them, after which one run is
 *    reused.
 * 6. A source edit fails as stale output at every boundary until the compile,
 *    after which one run under the new input identity is reused.
 */
export const test_production_source_status_retention = (): void => {
  const world = createSourceStatusWorld();
  const status = world.status();
  const initial = answerOf(world.state, []);
  const reads: number[] = [];
  const boundaries = runsPerCall(
    world,
    () => {
      const before = world.counts.acquisitions;
      const answer = status();
      reads.push(world.counts.acquisitions - before);
      return answer;
    },
    5,
  );
  TestValidator.equals(
    "five unchanged capture boundaries run the gate once",
    {
      runs: boundaries.runs,
      laterReads: reads.slice(1),
      answers: boundaries.answers,
    },
    {
      runs: [1, 0, 0, 0, 0],
      laterReads: [1, 1, 1, 1],
      answers: [initial, initial, initial, initial, initial],
    },
  );

  const reused = status();
  reused.diagnostics.push(GENERATED_TAMPERED);
  reused.builder.inputFingerprint = textDigest("forged identity");
  TestValidator.equals(
    "a mutated reused answer leaves the next answer intact",
    status(),
    initial,
  );

  const changed = (
    target: ReturnType<typeof createSourceStatusWorld>,
    targetStatus: () => ReturnType<typeof status>,
    change: () => void,
  ) => {
    change();
    const observed = runsPerCall(target, targetStatus, 2);
    return {
      runs: observed.runs,
      answers: observed.answers,
      expected: answerOf(target.state, []),
    };
  };
  const inputs = [
    changed(world, status, () =>
      world.state.documents.set(SCREENPLAY_DOCUMENT, "EXT. HARBOR - DAWN"),
    ),
    changed(world, status, () => {
      world.state.screenplay = "treatment and scene index v2";
    }),
    changed(world, status, () => {
      world.state.resident = textDigest("another checkout root");
    }),
  ];
  TestValidator.equals(
    "each changed input runs the gate exactly once and is reused after",
    inputs.map((entry) => ({ runs: entry.runs, answers: entry.answers })),
    inputs.map((entry) => ({
      runs: [1, 0],
      answers: [entry.expected, entry.expected],
    })),
  );

  const unbound = changed(world, status, () => {
    world.state.revision += 1;
  });
  const boundWorld = createSourceStatusWorld();
  boundWorld.state.revisionBound = true;
  const boundStatus = boundWorld.status();
  boundStatus();
  const bound = changed(boundWorld, boundStatus, () => {
    boundWorld.state.revision += 1;
  });
  TestValidator.equals(
    "a revision alone moves only an answer that read the revision",
    {
      unbound: { runs: unbound.runs, answers: unbound.answers },
      bound: { runs: bound.runs, answers: bound.answers },
    },
    {
      unbound: { runs: [0, 0], answers: [unbound.expected, unbound.expected] },
      bound: { runs: [1, 0], answers: [bound.expected, bound.expected] },
    },
  );

  world.state.generated = "hand-edited compiled shot";
  const tampered = runsPerCall(world, status, 2);
  const tamperedAnswer = answerOf(world.state, [GENERATED_TAMPERED]);
  world.compile();
  const restored = runsPerCall(world, status, 2);
  TestValidator.equals(
    "tampered output fails until a compile restores it",
    { tampered, restored },
    {
      tampered: { runs: [1, 1], answers: [tamperedAnswer, tamperedAnswer] },
      restored: {
        runs: [1, 0],
        answers: [answerOf(world.state, []), answerOf(world.state, [])],
      },
    },
  );

  world.state.source = "export const opening = defineShot({ beats: 4 });\n";
  const stale = runsPerCall(world, status, 2);
  const staleAnswer = answerOf(world.state, [GENERATED_STALE]);
  world.compile();
  const recompiled = runsPerCall(world, status, 2);
  TestValidator.equals(
    "a source edit fails as stale until compiled, then one run is reused",
    { stale, recompiled },
    {
      stale: { runs: [1, 1], answers: [staleAnswer, staleAnswer] },
      recompiled: {
        runs: [1, 0],
        answers: [answerOf(world.state, []), answerOf(world.state, [])],
      },
    },
  );
};
