import {
  AutoMovieProductionCompiler,
  AutoMovieProductionInputRaceError,
  AutoMovieProductionProject,
} from "@automovie/production";
import { TestValidator } from "@nestia/e2e";
import assert from "node:assert/strict";

import { libraryAuthoring, libraryFixture } from "./libraryFixtures";
import { productionFixture } from "./productionFixtures";

type RacedMethod = "commitGenerated" | "confirmCurrentSnapshot";

/**
 * What a compile does when the project tells it the inputs moved.
 *
 * The compiler asks the project to commit what it produced, or, when it
 * produced no generated bytes, to confirm that nothing moved under the result.
 * Either call can report that the inputs changed mid-compile, and the compiler
 * answers by discarding the result and reporting `compile-input-changed`
 * against the fingerprint it read.
 *
 * No test had ever produced that answer. `compile-input-changed` appears
 * nowhere in the suite, so three separate handlers of it were written and never
 * taken, and a compile that silently kept a result assembled from inputs that
 * had already changed would have passed every check this repository has.
 *
 * The race is reported by the project rather than staged in the filesystem. A
 * real one needs a second writer landing inside one synchronous compile, and
 * scheduling that would test the scheduler; what these three lines specify is
 * the compiler's answer to being told, which is what a project reporting it
 * produces. The same doctrine names `spawnSync` as an input elsewhere.
 *
 * Scenarios:
 *
 * 1. A commit that reports a race fails the compile and carries
 *    `compile-input-changed` with the project's own message.
 * 2. A snapshot confirmation that reports one does the same at a scope that
 *    publishes no generated bytes, which is the only scope that reaches it.
 * 3. A film production commits through a different path with its own handler,
 *    which a library fixture cannot reach however it is compiled.
 * 4. An error that is not a race is rethrown rather than reported, so a real
 *    fault never arrives disguised as a concurrent writer.
 */
export const test_production_compile_input_race = (): void => {
  const fixture = libraryFixture();
  try {
    const compileWith = (props: {
      method: RacedMethod;
      scope: "design" | "final" | "review" | "source";
      thrown: () => unknown;
    }) => {
      const project = AutoMovieProductionProject.open(fixture.root);
      // A project that reports the race, rather than a filesystem staged to
      // produce one. The prototype keeps every other method real.
      const reporting = Object.create(project) as Record<string, unknown>;
      reporting[props.method] = (): never => {
        throw props.thrown();
      };
      return new AutoMovieProductionCompiler(
        reporting as unknown as AutoMovieProductionProject,
        libraryAuthoring({ root: fixture.root }),
      ).compile({ scope: props.scope });
    };

    const race = (): unknown =>
      new AutoMovieProductionInputRaceError(
        "Production inputs changed during the compile.",
      );

    const committed = compileWith({
      method: "commitGenerated",
      scope: "source",
      thrown: race,
    });
    const confirmed = compileWith({
      method: "confirmCurrentSnapshot",
      scope: "design",
      thrown: race,
    });
    // A film production takes a different path with its own handler, and a
    // library fixture can never reach it however it is compiled.
    const film = productionFixture();
    let published;
    try {
      const project = AutoMovieProductionProject.open(film.root);
      const reporting = Object.create(project) as Record<string, unknown>;
      reporting.commitGenerated = (): never => {
        throw race();
      };
      published = new AutoMovieProductionCompiler(
        reporting as unknown as AutoMovieProductionProject,
      ).compile({ scope: "source" });
    } finally {
      film.dispose();
    }

    const changed = (
      output: ReturnType<typeof compileWith>,
    ): { message: boolean; success: boolean } => ({
      message: output.diagnostics.some(
        (diagnostic) =>
          diagnostic.code === "compile-input-changed" &&
          diagnostic.message.includes(
            "Production inputs changed during the compile.",
          ) &&
          diagnostic.message.includes("Re-run the scaffold compile command"),
      ),
      success: output.success,
    });

    TestValidator.equals(
      "a project reporting a race turns the compile into compile-input-changed",
      {
        committed: changed(committed),
        confirmed: changed(confirmed),
        published: changed(published),
      },
      {
        committed: { message: true, success: false },
        confirmed: { message: true, success: false },
        published: { message: true, success: false },
      },
    );

    // The other side of the same guard. A fault that is not a race carries no
    // information about concurrency, and reporting it as one would send an
    // author to look for a second writer that never existed.
    for (const method of ["commitGenerated", "confirmCurrentSnapshot"] as const)
      assert.throws(
        () =>
          compileWith({
            method,
            scope: method === "commitGenerated" ? "source" : "design",
            thrown: () => new Error("the state root is gone"),
          }),
        /the state root is gone/u,
      );
  } finally {
    fixture.dispose();
  }
};
