import {
  ViolationCollector,
  compileCameraClearanceReports,
  stageScene,
} from "@automovie/engine";
import {
  IAutoMovieCameraClearanceEnvelope,
  IAutoMovieStage,
} from "@automovie/interface";
import { TestValidator } from "@nestia/e2e";

import { makeScriptWrite, makeStagingWrite } from "../internal/filmFixtures";
import { createModel } from "../internal/fixtures";
import { loadSourceModule } from "../internal/loadSourceModule";
import { productionModule } from "./sourceStatusFixtures";

interface ITrace {
  documents: Array<{ path: string; content: string | null }>;
  revisionBound: boolean;
}

interface IClearanceRuntime {
  revision: string;
  currentRevision: string;
  sampleRate: number;
}

const { recordAutoMovieProductionClearanceRevision } = loadSourceModule<{
  recordAutoMovieProductionClearanceRevision(props: {
    trace: ITrace | undefined;
    runtime: IClearanceRuntime;
  }): IClearanceRuntime;
}>(productionModule("recordAutoMovieProductionClearanceRevision.ts"));

/** One camera that either declares a physical envelope or carries none. */
const stageWithClearance = (): IAutoMovieStage => {
  const base = makeStagingWrite();
  const clearance: IAutoMovieCameraClearanceEnvelope = {
    body: { center: { x: 0, y: 0, z: 0 }, radius: 0.01 },
    parentRig: null,
  };
  return {
    ...base,
    cameras: [
      {
        ...base.cameras[0]!,
        near: 0.1,
        far: 100,
        depthPrecision: { minimumDepthBits: 24, maximumStepMeters: 1 },
        clearance,
      },
    ],
  };
};

/**
 * A clearance answer stays revision-bound while its artifact stops recording it.
 *
 * The builder hands the engine its revisions through a recording runtime, and
 * the retained source status may reuse an answer only when it knows whether the
 * revision number itself entered that answer. Removing the two revisions from
 * the compiled report is what keeps generated bytes independent of the revision
 * counter, and it must not quietly remove that freshness dependence with them:
 * the engine still reads both values to refuse a take measured against one
 * snapshot and gated against another, and reading them is exactly what marks
 * the answer bound.
 *
 * The binding is conditional, which is the half a regression would erase
 * silently. Only a camera declaring an envelope makes the engine read a
 * revision, so a take without one must leave the trace unbound and let an
 * unrelated project write keep a retained answer current.
 *
 * Scenarios:
 *
 * 1. A camera with an envelope and agreeing revisions compiles one clear
 *    report, leaves no violation, and binds the trace.
 * 2. That report carries neither `revision` nor `currentRevision`, so the
 *    dependence lives in the trace rather than in artifact bytes.
 * 3. A measured revision that is no longer current is refused at
 *    `$input.cameraClearance.currentRevision`, and the trace is still bound.
 * 4. A camera declaring no envelope compiles no report, raises no violation,
 *    and leaves the trace unbound.
 */
export const test_production_clearance_revision_binding = (): void => {
  const stagedResult = stageScene(makeScriptWrite(), stageWithClearance());
  if (stagedResult.success !== true)
    throw new Error("the clearance fixture must stage");
  const scene = stagedResult.scene;
  const heroCamera = scene.cameras[0]!;
  const models = [
    { ...createModel(), id: "stickman" },
    { ...createModel(), id: "knightB" },
  ];

  const inspect = (props: {
    revision: string;
    currentRevision: string;
    envelope: boolean;
  }) => {
    const trace: ITrace = { documents: [], revisionBound: false };
    const camera = props.envelope
      ? heroCamera
      : { ...heroCamera, clearance: undefined };
    const out = new ViolationCollector();
    const reports = compileCameraClearanceReports({
      scene: { ...scene, cameras: [camera] },
      hero: { camera, motion: null },
      coverage: [],
      duration: 2,
      motions: {},
      objectMotions: [],
      models,
      runtime: recordAutoMovieProductionClearanceRevision({
        trace,
        runtime: {
          revision: props.revision,
          currentRevision: props.currentRevision,
          sampleRate: 24,
        },
      }),
      out,
    });
    return { reports, out, trace };
  };

  const current = inspect({
    revision: "41",
    currentRevision: "41",
    envelope: true,
  });
  TestValidator.equals(
    "an envelope-bearing take compiles one clear report and binds the trace",
    [
      current.reports?.length,
      current.reports?.[0]?.status,
      current.out.items.length,
      current.trace.revisionBound,
    ],
    [1, "clear", 0, true],
  );

  TestValidator.equals(
    "the bound answer's report records no revision of its own",
    (current.reports ?? []).flatMap((report) =>
      ["revision", "currentRevision"].filter((key) =>
        Object.keys(report).includes(key),
      ),
    ),
    [],
  );

  const moved = inspect({
    revision: "41",
    currentRevision: "42",
    envelope: true,
  });
  TestValidator.equals(
    "a measured revision that is no longer current is refused while still bound",
    [
      moved.reports,
      moved.out.items.map((item) => item.path),
      moved.trace.revisionBound,
    ],
    [undefined, ["$input.cameraClearance.currentRevision"], true],
  );

  const plain = inspect({
    revision: "41",
    currentRevision: "41",
    envelope: false,
  });
  TestValidator.equals(
    "a take declaring no envelope reads no revision and leaves it unbound",
    [plain.reports, plain.out.items.length, plain.trace.revisionBound],
    [undefined, 0, false],
  );
};
