/**
 * Engine package boundaries for simulation, effects and sound.
 *
 * The package's lint.config.ts selects this declaration as an exclusion
 * carrier within its complete public-source population. It has no runtime
 * state and is not re-exported by the package barrel. Each declared
 * target/reason pair below owns one intentional negative relationship;
 * requirement and specification boundaries for this domain stay together.
 * Positive implementation citations remain on the actual public exports.
 * An exclusion neither implements a feature nor approves a rendered asset.
 * Add a boundary at its semantic owner and retain native graph validation.
 *
 * @evidenceExclude requirements/effects-and-simulation/README.md#effect와-simulation-요구사항 The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/budgets-and-bounded-work.md#effects-budget-admission The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/budgets-and-bounded-work.md#effects-budget-composition The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/budgets-and-bounded-work.md#effects-budget-identity The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/budgets-and-bounded-work.md#effects-external-cache-bound The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/clock-seek-and-determinism.md#effects-dependency-order The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/damage-and-destruction-boundary.md#effects-authored-destruction-state The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/damage-and-destruction-boundary.md#effects-damage-continuity The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/damage-and-destruction-boundary.md#effects-damage-trait-result The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/damage-and-destruction-boundary.md#effects-damage-transition-precedence The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/damage-and-destruction-boundary.md#effects-destruction-evidence The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/damage-and-destruction-boundary.md#effects-destruction-solver-ceiling The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/environment-coupling.md#effects-coupled-snapshot The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/environment-coupling.md#effects-coupling-dependency-invalidation The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/environment-coupling.md#effects-coupling-level The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/environment-coupling.md#effects-coupling-refusal The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/environment-coupling.md#effects-surface-consequence The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/environment-coupling.md#effects-wind-gravity-input The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/fire-smoke-and-atmosphere.md#effects-atmosphere-composition The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/fire-smoke-and-atmosphere.md#effects-fire-claim-boundary The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/fire-smoke-and-atmosphere.md#effects-fire-lifecycle-seek The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/fire-smoke-and-atmosphere.md#effects-fire-light-visibility The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/fire-smoke-and-atmosphere.md#effects-fire-source-state The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/fire-smoke-and-atmosphere.md#effects-smoke-wind-boundary The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/fluids-and-water.md#effects-fluid-object-interaction The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/particles-and-emission.md#effects-particle-contact-consequence The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/rigid-motion-ballistics-and-collision.md#effects-collision-refusal The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/rigid-motion-ballistics-and-collision.md#effects-rigid-contact-order-seek The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/rigid-motion-ballistics-and-collision.md#effects-rigid-linear-angular-state The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/scope-and-simulation-tiers.md#effects-external-provider-neutrality The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/scope-and-simulation-tiers.md#effects-prototype-fidelity-boundary The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/scope-and-simulation-tiers.md#effects-simulation-tier The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/soft-bodies-and-deformation.md#effects-soft-external-result The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/validation-and-evidence.md#effects-evidence-identity-freshness The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/validation-and-evidence.md#effects-evidence-status The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/validation-and-evidence.md#effects-external-result-evidence The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/validation-and-evidence.md#effects-hand-math-boundary The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/validation-and-evidence.md#effects-negative-twins The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/validation-and-evidence.md#effects-seek-equivalence-evidence The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/effects-and-simulation/validation-and-evidence.md#effects-visual-review The Engine owns the concrete bounded solvers and effect calculations cited by its source units; source acquisition, creative authoring, provider selection, fidelity approval, and rendered-effect delivery do not belong to this package.
 * @evidenceExclude requirements/sound/README.md#음향-요구사항 The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/ambience-and-sustained-sources.md#sound-ambience-bed-population The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/ambience-and-sustained-sources.md#sound-ambience-environment-revision The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/ambience-and-sustained-sources.md#sound-ambience-environment-state The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/ambience-and-sustained-sources.md#sound-ambience-loop-seam The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/ambience-and-sustained-sources.md#sound-ambience-refusal The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/ambience-and-sustained-sources.md#sound-ambience-seek-state The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/dialogue-voice-and-visemes.md#sound-dialogue-voice-consistency The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/dialogue-voice-and-visemes.md#sound-voice-source-adoption The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/editing-synchronization-and-continuity.md#sound-boundary-continuity The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/editing-synchronization-and-continuity.md#sound-conform-invalidation The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/editing-synchronization-and-continuity.md#sound-event-synchronization The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/editing-synchronization-and-continuity.md#sound-sync-refusal The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/event-cues-and-timing.md#sound-cue-identity-deduplication The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/event-cues-and-timing.md#sound-one-shot-sustained The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/foley-and-sound-effects.md#sound-effect-claim-boundary The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/foley-and-sound-effects.md#sound-foley-material-surface The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/foley-and-sound-effects.md#sound-foley-resolved-contact The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/foley-and-sound-effects.md#sound-foley-variation The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/foley-and-sound-effects.md#sound-layered-effects The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/foley-and-sound-effects.md#sound-procedural-foley-bound The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/interior-acoustics.md#sound-acoustic-provider-neutrality The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/mix-hierarchy-and-loudness.md#sound-bus-priority The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/mix-hierarchy-and-loudness.md#sound-deterministic-summation The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/mix-hierarchy-and-loudness.md#sound-mix-automation-clock The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/mix-hierarchy-and-loudness.md#sound-mix-refusal The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/mix-hierarchy-and-loudness.md#sound-processing-chain The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/mix-hierarchy-and-loudness.md#sound-stem-master-relation The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/music-and-silence.md#sound-music-conform The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/music-and-silence.md#sound-music-diegetic-distinction The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/music-and-silence.md#sound-music-provider-neutrality The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/music-and-silence.md#sound-music-rights-source The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/music-and-silence.md#sound-music-tempo-edit The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/music-and-silence.md#sound-silence-state The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/scope-and-identity.md#sound-authored-silence The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/scope-and-identity.md#sound-missing-refusal The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/scope-and-identity.md#sound-prototype-fidelity-boundary The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/scope-and-identity.md#sound-provider-neutrality The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/scope-and-identity.md#sound-story-world-binding The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/sources-and-external-assets.md#sound-decode-contract The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/sources-and-external-assets.md#sound-derived-source-closure The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/sources-and-external-assets.md#sound-source-choice The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/sources-and-external-assets.md#sound-source-immutable-adoption The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/sources-and-external-assets.md#sound-source-provider-adapter-boundary The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/sources-and-external-assets.md#sound-source-secret-remote-boundary The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/spatialization-and-propagation.md#sound-moving-path-sampling The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/spatialization-and-propagation.md#sound-occlusion-obstacle The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/validation-and-delivery.md#sound-audible-review The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/validation-and-delivery.md#sound-budget-evidence The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/validation-and-delivery.md#sound-delivery-inventory The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/validation-and-delivery.md#sound-evidence-identity-freshness The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/validation-and-delivery.md#sound-evidence-status The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/validation-and-delivery.md#sound-final-media-probe The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/validation-and-delivery.md#sound-picture-delivery-join The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude requirements/sound/validation-and-delivery.md#sound-seek-chunk-equivalence The Engine implements the cited propagation, acoustics, cue, and synchronization calculations; recording, voice or music sourcing, creative mix authority, provider adoption, loudness approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/README.md#simulation-effects-and-sound-specifications The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/ambience-music-spatial-and-acoustics.md#ambience-environment-revision-and-refusal The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/ambience-music-spatial-and-acoustics.md#ambience-loop-seam-and-seek The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/ambience-music-spatial-and-acoustics.md#music-source-rights-and-provider-neutrality The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/ambience-music-spatial-and-acoustics.md#music-tempo-edit-and-conform The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/budget-admission.md#audio-workload-budget-admission The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/budget-admission.md#effect-budget-preflight-admission The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/budget-admission.md#external-cache-and-retention-bound The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/clocks-ordering-seek-and-checkpoints.md#deterministic-dependency-and-contact-order The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/fluids-water-and-world-coupling.md#coupled-world-snapshot-contract The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/fluids-water-and-world-coupling.md#fluid-moving-object-interaction The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-conform-dependency-invalidation The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-delivery-stream-and-inventory The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-stem-master-relation-contract The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-sync-refusal-contract The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/particles-fire-and-atmosphere.md#atmosphere-composition-light-visibility-output The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/particles-fire-and-atmosphere.md#fire-source-fuel-and-lifecycle-state The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/particles-fire-and-atmosphere.md#smoke-wind-and-domain-boundary The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/rigid-collision-and-damage.md#damage-trait-result-state-boundary The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/rigid-collision-and-damage.md#damage-transition-precedence-and-continuity The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/rigid-collision-and-damage.md#destruction-solver-ceiling-and-evidence The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/rigid-collision-and-damage.md#rigid-collision-failure-contract The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/scope-tiers-and-identities.md#authored-silence-and-missing-state The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/scope-tiers-and-identities.md#external-result-provider-neutrality The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/soft-bodies-and-deformation.md#soft-external-deformation-adoption The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/sound-sources-events-dialogue-and-foley.md#foley-claim-and-failure-boundary The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/sound-sources-events-dialogue-and-foley.md#foley-variation-layering-and-bound The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/sound-sources-events-dialogue-and-foley.md#sound-decode-and-derived-source-closure The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/sound-sources-events-dialogue-and-foley.md#sound-source-choice-provider-and-secret-boundary The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/validation-evidence-and-compatibility.md#effect-evidence-status-and-external-result The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/validation-evidence-and-compatibility.md#effect-hand-math-and-negative-twins The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/validation-evidence-and-compatibility.md#effect-seek-equivalence-and-visual-review The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/validation-evidence-and-compatibility.md#simulation-sound-compatibility-and-recovery The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/validation-evidence-and-compatibility.md#sound-delivery-status-and-failure-propagation The Engine owns only the cited bounded simulation, effect, and sound calculations; provider integration, authored source selection, creative fidelity, renderer handoff, mix approval, and delivery remain outside it.
 * @evidenceExclude specifications/simulation-effects-and-sound/sound-sources-events-dialogue-and-foley.md#sound-decoder-input-contract The Engine receives decoded PCM and normalized sound facts; encoded-audio byte inspection, decoder admission limits, and decode-failure diagnostics belong to ingestion before Engine mixing.
 */
export type AutoMovieEngineSimulationEvidenceExclusions = never;
