/**
 * Engine package boundaries for product scope, execution and recovery.
 *
 * The package's lint.config.ts selects this declaration as an exclusion
 * carrier within its complete public-source population. It has no runtime
 * state and is not re-exported by the package barrel. Each declared
 * target/reason pair below owns one intentional negative relationship;
 * requirement and specification boundaries for this domain stay together.
 * Positive implementation citations remain on the actual public exports.
 * An exclusion neither implements a feature nor approves a rendered asset.
 * Add a boundary at its semantic owner and retain native graph validation.
 *
 * @evidenceExclude requirements/README.md#automovie-요구사항 The repository-wide requirements index spans every product layer; the Engine owns only the bounded deterministic computations cited by its public units.
 * @evidenceExclude requirements/operations-and-recovery/README.md#운영과-복구-요구사항 The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/audit-and-operator-authority.md#operations-action-specific-authority The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/audit-and-operator-authority.md#operations-audit-event-completeness The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/audit-and-operator-authority.md#operations-audit-history-preservation The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/audit-and-operator-authority.md#operations-high-risk-action-confirmation The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/audit-and-operator-authority.md#operations-override-emergency-access The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/audit-and-operator-authority.md#operations-secret-free-audit The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/cache-integrity-and-dependency-loss.md#operations-corrupt-cache-isolation The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/cache-integrity-and-dependency-loss.md#operations-dependency-identity-availability The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/cache-integrity-and-dependency-loss.md#operations-dependency-loss-options The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/cancellation-and-interruption.md#operations-cancelled-partial-results The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/cancellation-and-interruption.md#operations-forced-termination The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/cancellation-and-interruption.md#operations-pause-cancel-distinction The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/cancellation-and-interruption.md#operations-safe-interruption-point The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/cancellation-and-interruption.md#operations-timeout-interruption The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/checkpoints-resume-and-retry.md#operations-acknowledged-completion-boundary The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/checkpoints-resume-and-retry.md#operations-changed-input-restart The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/checkpoints-resume-and-retry.md#operations-checkpoint-completeness The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/checkpoints-resume-and-retry.md#operations-resume-eligibility The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/checkpoints-resume-and-retry.md#operations-resumed-result-validation The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/checkpoints-resume-and-retry.md#operations-retry-lineage-and-limits The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/concurrent-runs-and-locking.md#operations-concurrent-shared-result-reuse The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/concurrent-runs-and-locking.md#operations-deadlock-queue-stall The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/concurrent-runs-and-locking.md#operations-duplicate-job-concurrency The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/concurrent-runs-and-locking.md#operations-late-writer-fencing The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/concurrent-runs-and-locking.md#operations-lock-scope-owner The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/concurrent-runs-and-locking.md#operations-stale-lock-recovery The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/disaster-recovery.md#operations-backup-independence-integrity The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/disaster-recovery.md#operations-disaster-authoritative-state The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/disaster-recovery.md#operations-disaster-degraded-operation The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/disaster-recovery.md#operations-failover-split-brain The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/disaster-recovery.md#operations-recovery-exercise-gap The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/disaster-recovery.md#operations-restore-validation The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/failure-modes-and-recovery.md#operations-failure-isolation The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/failure-modes-and-recovery.md#operations-network-storage-failure The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/failure-modes-and-recovery.md#operations-process-crash-power-loss The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/failure-modes-and-recovery.md#operations-recovery-decision-basis The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/failure-modes-and-recovery.md#operations-repeated-failure-stop The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/failure-modes-and-recovery.md#operations-runtime-dependency-failure The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/idempotency-and-side-effects.md#operations-alias-visible-bytes The Engine computes and returns values and opens no pathname for writing, so it has no update that could change the bytes another directory entry observes.
 * @evidenceExclude requirements/operations-and-recovery/idempotency-and-side-effects.md#operations-compensation-reconciliation The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/idempotency-and-side-effects.md#operations-duplicate-submission The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/idempotency-and-side-effects.md#operations-exactly-once-claim-boundary The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/idempotency-and-side-effects.md#operations-external-side-effect-outcome The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/idempotency-and-side-effects.md#operations-idempotent-deterministic-results The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/migration-and-compatibility.md#operations-downgrade-rollback-compatibility The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/migration-and-compatibility.md#operations-migration-validation The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/migration-and-compatibility.md#operations-mixed-version-concurrency The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/migration-and-compatibility.md#operations-nondestructive-migration The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/migration-and-compatibility.md#operations-resume-compatibility-classification The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/migration-and-compatibility.md#operations-semantic-change-new-identity The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/observability-and-secret-protection.md#operations-event-correlation The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/observability-and-secret-protection.md#operations-failure-diagnostic The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/observability-and-secret-protection.md#operations-observability-access-control The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/observability-and-secret-protection.md#operations-observability-retention The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/observability-and-secret-protection.md#operations-progress-remaining-work The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/observability-and-secret-protection.md#operations-secret-redaction The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/partial-artifacts-and-publication.md#operations-artifact-state-ownership The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/partial-artifacts-and-publication.md#operations-atomic-current-transition The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/partial-artifacts-and-publication.md#operations-partial-artifact-isolation The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/partial-artifacts-and-publication.md#operations-publication-conflict-rollback The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/partial-artifacts-and-publication.md#operations-publication-preconditions The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/resource-budgets-and-backpressure.md#operations-backpressure The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/resource-budgets-and-backpressure.md#operations-budget-result-accounting The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/resource-budgets-and-backpressure.md#operations-preemption-resource-reclamation The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/resource-budgets-and-backpressure.md#operations-priority-fairness The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/resource-budgets-and-backpressure.md#operations-runtime-budget-enforcement The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/retention-and-cleanup.md#operations-cleanup-concurrency-safety The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/retention-and-cleanup.md#operations-cleanup-deletion-record The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/retention-and-cleanup.md#operations-cleanup-failure-visibility The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/retention-and-cleanup.md#operations-cleanup-target-preview The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/retention-and-cleanup.md#operations-reference-aware-retention The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/retention-and-cleanup.md#operations-sensitive-data-minimization The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/scope-job-identity-and-state.md#operations-deterministic-reexecution-identity The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/scope-job-identity-and-state.md#operations-job-attempt-separation The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/scope-job-identity-and-state.md#operations-job-identity-inputs The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/scope-job-identity-and-state.md#operations-job-state-transition-history The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/scope-job-identity-and-state.md#operations-job-state-vocabulary The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/scope-job-identity-and-state.md#operations-requested-effective-work The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/operations-and-recovery/scope-job-identity-and-state.md#operations-terminal-state-truth The Engine has no job queue, distributed lock, retry scheduler, artifact store, publication transaction, credential manager, or operational recovery workflow.
 * @evidenceExclude requirements/product/README.md#제품-계약-요구사항 This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/authorability.md#product-authoring-choice-space This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/authorability.md#product-discoverable-control This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/authorability.md#product-explicit-control This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/authorability.md#product-hidden-inference-refusal This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/capability-and-content.md#product-catalogue-refusal This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/capability-and-content.md#product-era-independent-composition This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/capability-and-content.md#product-example-role This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/capability-and-content.md#product-unplanted-subject-authoring This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/charter.md#product-author-owned-film This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/charter.md#product-reproducible-judgment This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/charter.md#product-structural-output This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/choice-and-external-services.md#product-delegation-not-proxy-decision This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/choice-and-external-services.md#product-deterministic-external-adoption This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/choice-and-external-services.md#product-external-substitution-choice This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/choice-and-external-services.md#product-provider-neutral-capability This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/extensibility-and-compatibility.md#product-capability-gap This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/extensibility-and-compatibility.md#product-explicit-protocol-change This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/extensibility-and-compatibility.md#product-independent-extension-axes This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/extensibility-and-compatibility.md#product-omission-compatibility This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/prototype-quality.md#product-prototype-geometry This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/prototype-quality.md#product-prototype-handoff This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/prototype-quality.md#product-prototype-motion-time This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/prototype-quality.md#product-prototype-readability This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/scope-and-exclusions.md#product-content-catalogue-exclusion This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/scope-and-exclusions.md#product-detailed-likeness-exclusion This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/scope-and-exclusions.md#product-editor-export-exclusion This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/scope-and-exclusions.md#product-exclusion-reopening This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude requirements/product/scope-and-exclusions.md#product-nondeterministic-completion-exclusion This repository-wide product contract spans authoring, ingestion, orchestration, rendering, review, and delivery; the Engine implements only its positively cited deterministic computation boundary.
 * @evidenceExclude specifications/README.md#automovie-시스템-명세 The repository-wide system specification index spans authoring through delivery; the Engine owns only its positively cited deterministic runtime slice.
 * @evidenceExclude specifications/execution-and-recovery/README.md#실행과-복구-시스템-계약 The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/artifacts-and-atomic-publication.md#execution-artifact-ownership-completeness The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/artifacts-and-atomic-publication.md#execution-atomic-current-commit The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/artifacts-and-atomic-publication.md#execution-partial-artifact-isolation The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/artifacts-and-atomic-publication.md#execution-publication-conflict-rollback The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/artifacts-and-atomic-publication.md#execution-publication-failure-outcome The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/artifacts-and-atomic-publication.md#execution-publication-preconditions The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/cancellation-timeout-and-preemption.md#execution-cancelled-partial-result The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/cancellation-timeout-and-preemption.md#execution-force-termination The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/cancellation-timeout-and-preemption.md#execution-pause-cancel-semantics The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/cancellation-timeout-and-preemption.md#execution-preemption-control-priority The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/cancellation-timeout-and-preemption.md#execution-safe-point-acknowledgement The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/cancellation-timeout-and-preemption.md#execution-timeout-classification The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/checkpoints-resume-cache-and-dependencies.md#execution-cache-authority-boundary The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/checkpoints-resume-cache-and-dependencies.md#execution-changed-input-restart The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/checkpoints-resume-cache-and-dependencies.md#execution-checkpoint-closure The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/checkpoints-resume-cache-and-dependencies.md#execution-corrupt-cache-quarantine The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/checkpoints-resume-cache-and-dependencies.md#execution-dependency-availability-loss The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/checkpoints-resume-cache-and-dependencies.md#execution-durable-completion-boundary The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/checkpoints-resume-cache-and-dependencies.md#execution-resume-eligibility The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/checkpoints-resume-cache-and-dependencies.md#execution-resumed-result-validation The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/concurrent-ownership-and-locking.md#execution-claim-scope-owner The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/concurrent-ownership-and-locking.md#execution-deadlock-starvation The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/concurrent-ownership-and-locking.md#execution-duplicate-job-coordination The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/concurrent-ownership-and-locking.md#execution-fencing-late-writer The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/concurrent-ownership-and-locking.md#execution-publication-ownership-conflict The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/concurrent-ownership-and-locking.md#execution-shared-immutable-result The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/concurrent-ownership-and-locking.md#execution-stale-claim-recovery The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/failure-reconciliation-and-disaster-recovery.md#execution-authoritative-recovery-set The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/failure-reconciliation-and-disaster-recovery.md#execution-backup-independence-integrity The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/failure-reconciliation-and-disaster-recovery.md#execution-disaster-degraded-operation The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/failure-reconciliation-and-disaster-recovery.md#execution-disaster-recovery-scope The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/failure-reconciliation-and-disaster-recovery.md#execution-failover-fencing The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/failure-reconciliation-and-disaster-recovery.md#execution-failure-isolation The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/failure-reconciliation-and-disaster-recovery.md#execution-network-storage-ambiguity The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/failure-reconciliation-and-disaster-recovery.md#execution-process-crash-power-loss The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/failure-reconciliation-and-disaster-recovery.md#execution-recovery-decision The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/failure-reconciliation-and-disaster-recovery.md#execution-recovery-exercise-evidence The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/failure-reconciliation-and-disaster-recovery.md#execution-repeated-failure-circuit The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/failure-reconciliation-and-disaster-recovery.md#execution-restore-validation The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/operational-evidence-and-authority.md#execution-action-specific-authority The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/operational-evidence-and-authority.md#execution-audit-event-envelope The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/operational-evidence-and-authority.md#execution-audit-history-preservation The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/operational-evidence-and-authority.md#execution-high-risk-confirmation The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/operational-evidence-and-authority.md#execution-operational-evidence-bundle The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/operational-evidence-and-authority.md#execution-operator-query-export The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/operational-evidence-and-authority.md#execution-override-emergency-access The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/operational-evidence-and-authority.md#execution-secret-free-audit The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/portability-migration-and-compatibility.md#execution-downgrade-rollback-compatibility The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/portability-migration-and-compatibility.md#execution-migration-validation The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/portability-migration-and-compatibility.md#execution-mixed-version-concurrency The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/portability-migration-and-compatibility.md#execution-nondestructive-migration The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/portability-migration-and-compatibility.md#execution-resume-compatibility The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/portability-migration-and-compatibility.md#execution-runtime-compatibility-evidence The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/portability-migration-and-compatibility.md#execution-semantic-change-identity The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/progress-heartbeats-and-observation.md#execution-event-ordering-correlation The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/progress-heartbeats-and-observation.md#execution-failure-observation The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/progress-heartbeats-and-observation.md#execution-heartbeat-liveness The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/progress-heartbeats-and-observation.md#execution-observation-access-control The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/progress-heartbeats-and-observation.md#execution-observation-retention The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/progress-heartbeats-and-observation.md#execution-progress-snapshot The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/progress-heartbeats-and-observation.md#execution-secret-safe-observation The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/resource-budgets-and-backpressure.md#execution-backpressure-signal The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/resource-budgets-and-backpressure.md#execution-budget-preemption The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/resource-budgets-and-backpressure.md#execution-priority-fairness The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/resource-budgets-and-backpressure.md#execution-resource-accounting The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/resource-budgets-and-backpressure.md#execution-runtime-budget-enforcement The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/retention-cleanup-and-quarantine.md#execution-cleanup-concurrency-safety The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/retention-cleanup-and-quarantine.md#execution-cleanup-failure-capacity The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/retention-cleanup-and-quarantine.md#execution-cleanup-plan-preview The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/retention-cleanup-and-quarantine.md#execution-cleanup-quarantine-boundary The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/retention-cleanup-and-quarantine.md#execution-deletion-outcome-tombstone The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/retention-cleanup-and-quarantine.md#execution-reference-aware-retention The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/retention-cleanup-and-quarantine.md#execution-retention-classes The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/retention-cleanup-and-quarantine.md#execution-sensitive-retention-minimization The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/retry-backoff-and-idempotency.md#execution-alias-visible-bytes The Engine writes no file, so neither in-place rewriting nor entry replacement is a method it can choose between; the packages that publish bytes own that choice.
 * @evidenceExclude specifications/execution-and-recovery/retry-backoff-and-idempotency.md#execution-compensation-adoption The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/retry-backoff-and-idempotency.md#execution-deterministic-result-reuse The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/retry-backoff-and-idempotency.md#execution-duplicate-submission The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/retry-backoff-and-idempotency.md#execution-exactly-once-boundary The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/retry-backoff-and-idempotency.md#execution-external-outcome-reconciliation The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/retry-backoff-and-idempotency.md#execution-retry-backoff-schedule The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/retry-backoff-and-idempotency.md#execution-retry-eligibility-limit The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/scope-and-execution-identities.md#execution-attempt-identity-lineage The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/scope-and-execution-identities.md#execution-deterministic-output-identity The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/scope-and-execution-identities.md#execution-domain-result-separation The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/scope-and-execution-identities.md#execution-logical-job-identity The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/scope-and-execution-identities.md#execution-record-input-output The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/state-machine-and-admission.md#execution-admission-decision The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/state-machine-and-admission.md#execution-admission-input The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/state-machine-and-admission.md#execution-allowed-state-transitions The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/state-machine-and-admission.md#execution-job-attempt-state The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/state-machine-and-admission.md#execution-terminal-outcome The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude specifications/execution-and-recovery/state-machine-and-admission.md#execution-transition-compare-set The Engine is a deterministic library, not the run coordinator; admission queues, concurrency ownership, retries, checkpoints, artifact publication, retention, and operational recovery are outside it.
 * @evidenceExclude requirements/operations-and-recovery/contract-baseline.md#operations-contract-baseline-identity The Engine evaluates already-authored typed inputs; the production language module, contract baseline and migration, contract discriminators and delivery index are generated-project authoring contracts owned by the evidence and template packages.
 * @evidenceExclude requirements/operations-and-recovery/contract-migration-plan.md#operations-contract-migration-plan The Engine evaluates already-authored typed inputs; the production language module, contract baseline and migration, contract discriminators and delivery index are generated-project authoring contracts owned by the evidence and template packages.
 * @evidenceExclude requirements/operations-and-recovery/contract-migration-publication.md#operations-contract-migration-publication The Engine evaluates already-authored typed inputs; the production language module, contract baseline and migration, contract discriminators and delivery index are generated-project authoring contracts owned by the evidence and template packages.
 * @evidenceExclude specifications/execution-and-recovery/contract-baseline.md#execution-contract-baseline-identity The Engine evaluates already-authored typed inputs; the production language module, contract baseline and migration, contract discriminators and delivery index are generated-project authoring contracts owned by the evidence and template packages.
 * @evidenceExclude specifications/execution-and-recovery/contract-migration-plan.md#execution-contract-migration-plan The Engine evaluates already-authored typed inputs; the production language module, contract baseline and migration, contract discriminators and delivery index are generated-project authoring contracts owned by the evidence and template packages.
 * @evidenceExclude specifications/execution-and-recovery/contract-migration-publication.md#execution-contract-migration-publication The Engine evaluates already-authored typed inputs; the production language module, contract baseline and migration, contract discriminators and delivery index are generated-project authoring contracts owned by the evidence and template packages.
 */
export type AutoMovieEngineOperationsEvidenceExclusions = never;
