/**
 * Engine package boundaries for world maps and site representation.
 *
 * The package's lint.config.ts selects this declaration as an exclusion
 * carrier within its complete public-source population. It has no runtime
 * state and is not re-exported by the package barrel. Each declared
 * target/reason pair below owns one intentional negative relationship;
 * requirement and specification boundaries for this domain stay together.
 * Positive implementation citations remain on the actual public exports.
 * An exclusion neither implements a feature nor approves a rendered asset.
 * Add a boundary at its semantic owner and retain native graph validation.
 *
 * @evidenceExclude requirements/map/README.md#맵과-세계-요구사항 The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/bridges-and-tunnels.md#map-bridge-span-support The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/bridges-and-tunnels.md#map-crossing-clearance The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/bridges-and-tunnels.md#map-crossing-identity-level The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/bridges-and-tunnels.md#map-crossing-state The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/bridges-and-tunnels.md#map-crossing-structural-bound The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/bridges-and-tunnels.md#map-tunnel-drainage-state The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/bridges-and-tunnels.md#map-tunnel-volume The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/coasts-and-oceans.md#map-bathymetry-seabed The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/coasts-and-oceans.md#map-coastal-hazard-change The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/coasts-and-oceans.md#map-land-water-transition The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/coasts-and-oceans.md#map-marine-navigation-exposure The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/coasts-and-oceans.md#map-ocean-bounds The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/coasts-and-oceans.md#map-sea-level-datum The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/coasts-and-oceans.md#map-tide-wave The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/deliverables-and-validation.md#map-cartographic-output The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/deliverables-and-validation.md#map-coordinate-boundary-validation The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/deliverables-and-validation.md#map-delivery-manifest The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/deliverables-and-validation.md#map-delivery-tiles-exchange The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/deliverables-and-validation.md#map-partial-delivery-refusal The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/deliverables-and-validation.md#map-quantities-statistics The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/deliverables-and-validation.md#map-source-resolved-output The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/deliverables-and-validation.md#map-state-detail-validation The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/deliverables-and-validation.md#map-unverified-scope The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/deliverables-and-validation.md#map-validation-reproduction The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/deliverables-and-validation.md#map-visual-review The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/external-assets-and-placement.md#map-external-adoption-identity The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/external-assets-and-placement.md#map-external-coordinate-units The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/external-assets-and-placement.md#map-external-gltf-semantics The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/external-assets-and-placement.md#map-external-population-groups The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/external-assets-and-placement.md#map-external-source-state The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/external-assets-and-placement.md#map-external-spatial-data The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/external-assets-and-placement.md#map-external-terrain-network-constraints The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/external-assets-and-placement.md#map-spatial-source-composition The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/external-assets-and-placement.md#map-spatial-source-provenance-quality The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/geology-and-ground-surfaces.md#map-geology-units-ground-zones The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/geology-and-ground-surfaces.md#map-ground-analysis-bound The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/geology-and-ground-surfaces.md#map-ground-cover The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/geology-and-ground-surfaces.md#map-ground-quantity The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/geology-and-ground-surfaces.md#map-ground-temporal-state The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/geology-and-ground-surfaces.md#map-soil-profile-properties The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/geology-and-ground-surfaces.md#map-strata-exposure The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/geology-and-ground-surfaces.md#map-surface-subsurface-relation The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/infrastructure-and-utilities.md#map-infrastructure-above-below The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/infrastructure-and-utilities.md#map-infrastructure-analysis-bound The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/infrastructure-and-utilities.md#map-infrastructure-capacity-flow The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/infrastructure-and-utilities.md#map-infrastructure-corridor-access The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/infrastructure-and-utilities.md#map-infrastructure-dependencies The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/infrastructure-and-utilities.md#map-infrastructure-era The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/infrastructure-and-utilities.md#map-infrastructure-failure-recovery The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/infrastructure-and-utilities.md#map-service-identity-kind The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/movement-and-visibility.md#map-navigation-validation-level The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/movement-and-visibility.md#map-route-connectivity The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/movement-and-visibility.md#map-route-visibility The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/movement-and-visibility.md#map-temporal-route-state The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/movement-and-visibility.md#map-traveler-cost-constraints The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/movement-and-visibility.md#map-viewshed-visibility-range The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/parcels-and-land-use.md#map-land-rights-overlays The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/parcels-and-land-use.md#map-land-use-capacity The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/parcels-and-land-use.md#map-land-use-physical-relation The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/parcels-and-land-use.md#map-land-use-state The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/parcels-and-land-use.md#map-parcel-boundary-provenance The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/parcels-and-land-use.md#map-parcel-boundary-topology The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/parcels-and-land-use.md#map-parcel-conflict The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/parks-and-public-space.md#map-park-nature-distinction The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/parks-and-public-space.md#map-public-space-circulation-access The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/parks-and-public-space.md#map-public-space-events The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/parks-and-public-space.md#map-public-space-facilities The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/parks-and-public-space.md#map-public-space-routine-event-state The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/parks-and-public-space.md#map-public-space-zones The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/rail-and-transport.md#map-station-terminal The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/rail-and-transport.md#map-track-composition The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/rail-and-transport.md#map-transport-bound The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/rail-and-transport.md#map-transport-interchange-crossing The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/rail-and-transport.md#map-transport-operating-state The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/rail-and-transport.md#map-transport-service-dependency The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/rail-and-transport.md#map-transport-vehicle-envelope The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/rivers-and-inland-water.md#map-hydrology-analysis-bound The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/rivers-and-inland-water.md#map-surface-groundwater-boundary The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/rivers-and-inland-water.md#map-water-season-event The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/rivers-and-inland-water.md#map-water-surroundings The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/rivers-and-inland-water.md#map-watershed-drainage The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/roads-and-paths.md#map-road-alignment-section The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/roads-and-paths.md#map-road-era-use The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/roads-and-paths.md#map-road-junction The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/roads-and-paths.md#map-road-route-reference The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/roads-and-paths.md#map-road-state The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/roads-and-paths.md#map-road-terrain-seams The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/roads-and-paths.md#map-road-users-rules The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/scale-and-populations.md#map-boundary-seams The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/scale-and-populations.md#map-deterministic-density The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/scale-and-populations.md#map-level-of-detail The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/scale-and-populations.md#map-scale-representation The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/scale-and-populations.md#map-spatial-partition The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/scale-and-populations.md#map-streaming-canonical-state The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/scale-and-populations.md#map-tile-streaming The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/scope-and-coordinates.md#map-coordinate-control-points The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/scope-and-coordinates.md#map-coordinate-reference-system The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/scope-and-coordinates.md#map-coordinate-unit The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/scope-and-coordinates.md#map-extent-boundary The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/scope-and-coordinates.md#map-horizontal-vertical-temporal-reference The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/scope-and-coordinates.md#map-scale-levels The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/scope-and-coordinates.md#map-spatial-feature-identity The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/settlements-and-urban-form.md#map-density-skyline The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/settlements-and-urban-form.md#map-settlement-content-boundary The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/settlements-and-urban-form.md#map-settlement-growth-decline The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/settlements-and-urban-form.md#map-settlement-hierarchy The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/settlements-and-urban-form.md#map-settlement-place-functions The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/settlements-and-urban-form.md#map-settlement-repetition The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/settlements-and-urban-form.md#map-settlement-terrain-service-relation The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/temporal-change.md#map-continuous-discrete-change The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/temporal-change.md#map-event-consequence The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/temporal-change.md#map-temporal-comparison The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/terrain-and-landforms.md#map-multilevel-terrain The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/terrain-and-landforms.md#map-terrain-modification The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/terrain-and-landforms.md#map-terrain-surface-volume The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/vegetation-and-ecology.md#map-ecology-gap The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/vegetation-and-ecology.md#map-habitat-ecological-relations The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/vegetation-and-ecology.md#map-vegetation-disturbance-recovery The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/vegetation-and-ecology.md#map-vegetation-terrain-water The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/weather-and-seasons.md#map-season-climate-context The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/weather-and-seasons.md#map-weather-film-continuity The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/weather-and-seasons.md#map-weather-forecast-refusal The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/weather-and-seasons.md#map-weather-source-uncertainty The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/weather-and-seasons.md#map-weather-spatial-variation The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/weather-and-seasons.md#map-weather-surface-consequence The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude requirements/map/weather-and-seasons.md#map-weather-temporal-sampling The Engine resolves only the cited world geometry, placement, terrain, and environmental facts; GIS acquisition, world authoring, infrastructure planning, authoritative survey decisions, and map publication remain outside it.
 * @evidenceExclude specifications/world-and-site/README.md#세계와-사이트-시스템-사양 The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/delivery-and-validation.md#world-site-cartographic-visual-output The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/delivery-and-validation.md#world-site-coordinate-boundary-validation The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/delivery-and-validation.md#world-site-delivery-manifest The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/delivery-and-validation.md#world-site-partial-delivery-refusal The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/delivery-and-validation.md#world-site-quantity-statistics-output The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/delivery-and-validation.md#world-site-source-resolved-output The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/delivery-and-validation.md#world-site-state-detail-validation The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/delivery-and-validation.md#world-site-tile-exchange-output The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/delivery-and-validation.md#world-site-unverified-scope-compatibility The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/delivery-and-validation.md#world-site-validation-reproduction The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/delivery-and-validation.md#world-site-visual-review The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/ecology-weather-and-calendar.md#world-site-ecology-gap-limit The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/ecology-weather-and-calendar.md#world-site-season-spatial-weather The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/ecology-weather-and-calendar.md#world-site-vegetation-habitat-relation The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/ecology-weather-and-calendar.md#world-site-weather-continuity-source-refusal The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/ecology-weather-and-calendar.md#world-site-weather-sampling-consequence The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/hydrology-coast-and-groundwater.md#world-site-marine-navigation-bound The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/hydrology-coast-and-groundwater.md#world-site-seabed-level-coast-seam The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/hydrology-coast-and-groundwater.md#world-site-surface-groundwater-relation The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/hydrology-coast-and-groundwater.md#world-site-tide-wave-coastal-hazard The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/land-settlements-and-public-space.md#world-site-density-skyline-repetition The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/land-settlements-and-public-space.md#world-site-land-right-capacity The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/land-settlements-and-public-space.md#world-site-land-use-physical-relation The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/land-settlements-and-public-space.md#world-site-parcel-boundary-topology The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/land-settlements-and-public-space.md#world-site-parcel-conflict-failure The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/land-settlements-and-public-space.md#world-site-park-nature-distinction The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/land-settlements-and-public-space.md#world-site-public-facility-event-state The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/land-settlements-and-public-space.md#world-site-public-space-zone-access The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/land-settlements-and-public-space.md#world-site-settlement-change-infrastructure-relation The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/land-settlements-and-public-space.md#world-site-settlement-content-boundary The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/land-settlements-and-public-space.md#world-site-settlement-function-hierarchy The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/partition-lod-streaming-and-seams.md#world-site-boundary-seam-invariant The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/partition-lod-streaming-and-seams.md#world-site-lod-selection-invariant The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/partition-lod-streaming-and-seams.md#world-site-spatial-partition-tile-identity The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/partition-lod-streaming-and-seams.md#world-site-streaming-canonical-compatibility The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/partition-lod-streaming-and-seams.md#world-site-tile-streaming-state The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/spatial-imports-and-placement.md#world-site-adoption-identity-coordinate The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/spatial-imports-and-placement.md#world-site-gltf-scene-semantics The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/spatial-imports-and-placement.md#world-site-import-terrain-network-population The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/spatial-imports-and-placement.md#world-site-spatial-data-input The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/spatial-imports-and-placement.md#world-site-spatial-source-provenance-composition The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/spatial-reference-and-identity.md#world-site-coordinate-axis-unit-input The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/spatial-reference-and-identity.md#world-site-crs-datum-epoch The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/spatial-reference-and-identity.md#world-site-extent-scale-control The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/temporal-state-and-staleness.md#world-site-continuous-discrete-change The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/temporal-state-and-staleness.md#world-site-event-consequence The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/temporal-state-and-staleness.md#world-site-temporal-comparison-output The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/terrain-ground-and-geology.md#world-site-geology-soil-profile The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/terrain-ground-and-geology.md#world-site-ground-cover-subsurface-relation The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/terrain-ground-and-geology.md#world-site-ground-state-quantity-limit The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/transport-crossings-and-utilities.md#world-site-bridge-support-tunnel-volume The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/transport-crossings-and-utilities.md#world-site-crossing-drainage-state-clearance The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/transport-crossings-and-utilities.md#world-site-crossing-identity-level The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/transport-crossings-and-utilities.md#world-site-crossing-structural-limit The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/transport-crossings-and-utilities.md#world-site-rail-envelope-track-input The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/transport-crossings-and-utilities.md#world-site-road-era-use-state The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/transport-crossings-and-utilities.md#world-site-road-junction-user-rule The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/transport-crossings-and-utilities.md#world-site-road-reference-alignment-input The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/transport-crossings-and-utilities.md#world-site-road-terrain-seam The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/transport-crossings-and-utilities.md#world-site-station-interchange-crossing The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/transport-crossings-and-utilities.md#world-site-transport-operation-bound The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/transport-crossings-and-utilities.md#world-site-utility-corridor-capacity The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/transport-crossings-and-utilities.md#world-site-utility-dependency-analysis-bound The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/transport-crossings-and-utilities.md#world-site-utility-era-failure-recovery The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/transport-crossings-and-utilities.md#world-site-utility-identity-location The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/traversal-and-visibility.md#world-site-navigation-validation-level The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/traversal-and-visibility.md#world-site-route-connectivity-time-state The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/traversal-and-visibility.md#world-site-route-visibility-composition The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/traversal-and-visibility.md#world-site-traveler-constraint-cost The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/traversal-and-visibility.md#world-site-viewshed-visibility-range The Engine resolves the cited terrain, placement, and environment calculations; spatial-data acquisition, authoritative site modeling, planning decisions, large-world lifecycle, and published map deliverables remain outside it.
 * @evidenceExclude specifications/world-and-site/spatial-reference-and-identity.md#world-site-coordinate-magnitude-admission The production-design builder performs coordinate-magnitude admission before Engine execution, so Engine transform validation does not duplicate the project-bound policy or its admission diagnostics.
 */
export type AutoMovieEngineWorldEvidenceExclusions = never;
