/**
 * Engine package boundaries for acceptance, review and diagnostics.
 *
 * The package's lint.config.ts selects this declaration as an exclusion
 * carrier within its complete public-source population. It has no runtime
 * state and is not re-exported by the package barrel. Each declared
 * target/reason pair below owns one intentional negative relationship;
 * requirement and specification boundaries for this domain stay together.
 * Positive implementation citations remain on the actual public exports.
 * An exclusion neither implements a feature nor approves a rendered asset.
 * Add a boundary at its semantic owner and retain native graph validation.
 *
 * @evidenceExclude requirements/acceptance/README.md#acceptance-요구사항 The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/approval-exceptions-and-publication.md#acceptance-approval-selection-separation The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/approval-exceptions-and-publication.md#acceptance-approval-status The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/approval-exceptions-and-publication.md#acceptance-conditional-use The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/approval-exceptions-and-publication.md#acceptance-deviation-expiry The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/approval-exceptions-and-publication.md#acceptance-nonwaivable-criteria The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/approval-exceptions-and-publication.md#acceptance-post-publication-status The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/approval-exceptions-and-publication.md#acceptance-publication-atomicity The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/case-matrix-and-counterexamples.md#acceptance-boundary-case The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/case-matrix-and-counterexamples.md#acceptance-interaction-counterexample The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/case-matrix-and-counterexamples.md#acceptance-invalid-versus-fail The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/case-matrix-and-counterexamples.md#acceptance-negative-case The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/case-matrix-and-counterexamples.md#acceptance-positive-case The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/case-matrix-and-counterexamples.md#acceptance-regression-counterexample The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/change-regression-and-revalidation.md#acceptance-criterion-change The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/change-regression-and-revalidation.md#acceptance-environment-profile-change The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/change-regression-and-revalidation.md#acceptance-improvement-correctness The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/change-regression-and-revalidation.md#acceptance-intentional-change The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/change-regression-and-revalidation.md#acceptance-narrow-revalidation-limit The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/change-regression-and-revalidation.md#acceptance-revalidation-completion The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/change-regression-and-revalidation.md#acceptance-target-change The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/criteria-and-observables.md#acceptance-falsifiable-statement The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/criteria-and-observables.md#acceptance-numeric-observable The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/criteria-and-observables.md#acceptance-perceptual-observable The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/criteria-and-observables.md#acceptance-preconditions-consumers The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/criteria-and-observables.md#acceptance-semantic-observable The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/criteria-and-observables.md#acceptance-single-responsibility The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/criteria-and-observables.md#acceptance-structural-observable The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/criteria-and-observables.md#acceptance-subjective-verdict-boundary The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/evidence-and-freshness.md#acceptance-current-historical-evidence The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/evidence-and-freshness.md#acceptance-evidence-conflict The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/evidence-and-freshness.md#acceptance-evidence-lineage-integrity The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/evidence-and-freshness.md#acceptance-numeric-evidence The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/evidence-and-freshness.md#acceptance-perceptual-evidence The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/evidence-and-freshness.md#acceptance-semantic-evidence The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/evidence-and-freshness.md#acceptance-structural-evidence The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/profiles-and-aggregation.md#acceptance-aggregate-fail The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/profiles-and-aggregation.md#acceptance-aggregate-incomplete The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/profiles-and-aggregation.md#acceptance-aggregate-pass The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/profiles-and-aggregation.md#acceptance-blocking-profile The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/profiles-and-aggregation.md#acceptance-delivery-profile The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/profiles-and-aggregation.md#acceptance-evidence-profile The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/profiles-and-aggregation.md#acceptance-profile-isolation The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/profiles-and-aggregation.md#acceptance-project-defined-profile The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/profiles-and-aggregation.md#acceptance-required-severity The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/profiles-and-aggregation.md#acceptance-weighted-score The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/review-surfaces-and-sampling.md#acceptance-asset-surface The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/review-surfaces-and-sampling.md#acceptance-delivery-surface The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/review-surfaces-and-sampling.md#acceptance-film-surface The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/review-surfaces-and-sampling.md#acceptance-missing-sample-verdict The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/review-surfaces-and-sampling.md#acceptance-presentation-conditions The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/review-surfaces-and-sampling.md#acceptance-sample-interval-claim The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/review-surfaces-and-sampling.md#acceptance-sequence-surface The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/review-surfaces-and-sampling.md#acceptance-shot-surface The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/review-surfaces-and-sampling.md#acceptance-spatial-view-sampling The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/review-surfaces-and-sampling.md#acceptance-subject-surface The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/scope-targets-and-authority.md#acceptance-authority-conflict The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/scope-targets-and-authority.md#acceptance-criterion-owner-authority The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/scope-targets-and-authority.md#acceptance-publication-authority The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/scope-targets-and-authority.md#acceptance-review-approval-authority The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/scope-targets-and-authority.md#acceptance-scope-inclusion-exclusion The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/tolerances-and-boundaries.md#acceptance-absolute-relative-tolerance The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/tolerances-and-boundaries.md#acceptance-asymmetric-directional-tolerance The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/tolerances-and-boundaries.md#acceptance-discrete-sample-boundary The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/tolerances-and-boundaries.md#acceptance-perceptual-tolerance The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/tolerances-and-boundaries.md#acceptance-profile-owned-thresholds The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/tolerances-and-boundaries.md#acceptance-rounding-quantization The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/tolerances-and-boundaries.md#acceptance-spatiotemporal-tolerance The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/uncertainty-and-partial-success.md#acceptance-criterion-verdicts The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/uncertainty-and-partial-success.md#acceptance-numeric-uncertainty The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/uncertainty-and-partial-success.md#acceptance-partial-artifact The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/uncertainty-and-partial-success.md#acceptance-partial-evidence The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/uncertainty-and-partial-success.md#acceptance-perceptual-uncertainty The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/acceptance/uncertainty-and-partial-success.md#acceptance-status-no-promotion The Engine emits bounded deterministic validation and simulation facts; it does not define acceptance criteria, sampling plans, approval decisions, exceptions, or publication state.
 * @evidenceExclude requirements/diagnostics/README.md#진단-요구사항 The Engine emits package-local deterministic findings for its validators; cross-package taxonomy, localization, retention, presentation, run aggregation, and diagnostic policy are not Engine implementations.
 * @evidenceExclude requirements/diagnostics/budgets-and-limits.md#diagnostics-budget-exceeded The Engine emits package-local deterministic findings for its validators; cross-package taxonomy, localization, retention, presentation, run aggregation, and diagnostic policy are not Engine implementations.
 * @evidenceExclude requirements/diagnostics/budgets-and-limits.md#diagnostics-budget-remediation The Engine emits package-local deterministic findings for its validators; cross-package taxonomy, localization, retention, presentation, run aggregation, and diagnostic policy are not Engine implementations.
 * @evidenceExclude requirements/diagnostics/collection-fail-fast-and-determinism.md#diagnostics-duplicates-and-occurrences The Engine emits package-local deterministic findings for its validators; cross-package taxonomy, localization, retention, presentation, run aggregation, and diagnostic policy are not Engine implementations.
 * @evidenceExclude requirements/diagnostics/collection-fail-fast-and-determinism.md#diagnostics-fail-fast-boundary The Engine emits package-local deterministic findings for its validators; cross-package taxonomy, localization, retention, presentation, run aggregation, and diagnostic policy are not Engine implementations.
 * @evidenceExclude requirements/diagnostics/external-input-and-security.md#diagnostics-external-failure-stage The Engine emits package-local deterministic findings for its validators; cross-package taxonomy, localization, retention, presentation, run aggregation, and diagnostic policy are not Engine implementations.
 * @evidenceExclude requirements/diagnostics/external-input-and-security.md#diagnostics-quarantine-and-adoption The Engine emits package-local deterministic findings for its validators; cross-package taxonomy, localization, retention, presentation, run aggregation, and diagnostic policy are not Engine implementations.
 * @evidenceExclude requirements/diagnostics/external-input-and-security.md#diagnostics-redaction The Engine emits package-local deterministic findings for its validators; cross-package taxonomy, localization, retention, presentation, run aggregation, and diagnostic policy are not Engine implementations.
 * @evidenceExclude requirements/diagnostics/external-input-and-security.md#diagnostics-security-refusal The Engine emits package-local deterministic findings for its validators; cross-package taxonomy, localization, retention, presentation, run aggregation, and diagnostic policy are not Engine implementations.
 * @evidenceExclude requirements/diagnostics/identity-path-and-context.md#diagnostics-code-catalog-reference The Engine emits package-local deterministic findings for its validators; cross-package taxonomy, localization, retention, presentation, run aggregation, and diagnostic policy are not Engine implementations.
 * @evidenceExclude requirements/diagnostics/identity-path-and-context.md#diagnostics-identity-stability The Engine emits package-local deterministic findings for its validators; cross-package taxonomy, localization, retention, presentation, run aggregation, and diagnostic policy are not Engine implementations.
 * @evidenceExclude requirements/diagnostics/input-and-result-classification.md#diagnostics-missing-state The Engine emits package-local deterministic findings for its validators; cross-package taxonomy, localization, retention, presentation, run aggregation, and diagnostic policy are not Engine implementations.
 * @evidenceExclude requirements/diagnostics/input-and-result-classification.md#diagnostics-unknown-state The Engine emits package-local deterministic findings for its validators; cross-package taxonomy, localization, retention, presentation, run aggregation, and diagnostic policy are not Engine implementations.
 * @evidenceExclude requirements/diagnostics/localization-and-machine-results.md#diagnostics-accessible-presentation The Engine emits package-local deterministic findings for its validators; cross-package taxonomy, localization, retention, presentation, run aggregation, and diagnostic policy are not Engine implementations.
 * @evidenceExclude requirements/diagnostics/localization-and-machine-results.md#diagnostics-locale-fallback The Engine emits package-local deterministic findings for its validators; cross-package taxonomy, localization, retention, presentation, run aggregation, and diagnostic policy are not Engine implementations.
 * @evidenceExclude requirements/diagnostics/localization-and-machine-results.md#diagnostics-safe-localized-export The Engine emits package-local deterministic findings for its validators; cross-package taxonomy, localization, retention, presentation, run aggregation, and diagnostic policy are not Engine implementations.
 * @evidenceExclude requirements/diagnostics/localization-and-machine-results.md#diagnostics-value-unit-time-format The Engine emits package-local deterministic findings for its validators; cross-package taxonomy, localization, retention, presentation, run aggregation, and diagnostic policy are not Engine implementations.
 * @evidenceExclude requirements/diagnostics/partial-artifacts-and-recovery.md#diagnostics-delivery-during-failure The Engine emits package-local deterministic findings for its validators; cross-package taxonomy, localization, retention, presentation, run aggregation, and diagnostic policy are not Engine implementations.
 * @evidenceExclude requirements/diagnostics/partial-artifacts-and-recovery.md#diagnostics-partial-retention The Engine emits package-local deterministic findings for its validators; cross-package taxonomy, localization, retention, presentation, run aggregation, and diagnostic policy are not Engine implementations.
 * @evidenceExclude requirements/diagnostics/partial-artifacts-and-recovery.md#diagnostics-partial-success-boundary The Engine emits package-local deterministic findings for its validators; cross-package taxonomy, localization, retention, presentation, run aggregation, and diagnostic policy are not Engine implementations.
 * @evidenceExclude requirements/diagnostics/partial-artifacts-and-recovery.md#diagnostics-preserve-prior-success The Engine emits package-local deterministic findings for its validators; cross-package taxonomy, localization, retention, presentation, run aggregation, and diagnostic policy are not Engine implementations.
 * @evidenceExclude requirements/diagnostics/partial-artifacts-and-recovery.md#diagnostics-resume-verified-reuse The Engine emits package-local deterministic findings for its validators; cross-package taxonomy, localization, retention, presentation, run aggregation, and diagnostic policy are not Engine implementations.
 * @evidenceExclude requirements/review/README.md#검토-요구사항 The Engine can normalize or emit cited validation facts, but it does not run human review, choose evidence samples, adjudicate subjective defects, approve exceptions, or close review state.
 * @evidenceExclude requirements/review/subject-inspection.md#review-subject-inspection-reach The Engine computes subject descriptions and coverage folds from compiled truth; the request surface a party without a screen uses to ask for an observation artifact belongs to the production package's inspection surface and its host instrument.
 * @evidenceExclude requirements/review/visual-change-reporting.md#review-visual-change-catalog-identity The Engine computes geometry, simulation, and validation facts from authored source; it holds no catalog of rendered-view image digests, so naming and keeping one stable across revisions belongs to the production package's visual change report.
 * @evidenceExclude requirements/review/visual-change-reporting.md#review-visual-change-four-states The Engine computes geometry, simulation, and validation facts from authored source; it holds no catalog of rendered-view image digests, so classifying views as changed, unchanged, new, or gone belongs to the production package's visual change report.
 * @evidenceExclude requirements/review/visual-change-reporting.md#review-visual-change-digest-reuse The Engine computes geometry, simulation, and validation facts from authored source; image bytes and their digests are produced downstream of it, so reusing and validating them belongs to the production package's visual change report.
 * @evidenceExclude requirements/review/visual-change-reporting.md#review-visual-change-evidence-boundary The Engine computes geometry, simulation, and validation facts from authored source; it neither issues review verdicts nor reports revision progress, so separating the two belongs to the production package's visual change report.
 * @evidenceExclude specifications/review-and-acceptance/README.md#review와-acceptance-시스템-명세 The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/alternatives-regression-and-revalidation.md#acceptance-system-criterion-change The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/alternatives-regression-and-revalidation.md#acceptance-system-improvement-correctness The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/alternatives-regression-and-revalidation.md#acceptance-system-intentional-change The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/alternatives-regression-and-revalidation.md#acceptance-system-revalidation-completion The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/alternatives-regression-and-revalidation.md#acceptance-system-target-environment-change The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/approval-waiver-and-publication.md#acceptance-system-approval The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/approval-waiver-and-publication.md#acceptance-system-conditional-approval The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/approval-waiver-and-publication.md#acceptance-system-nonwaivable-criterion The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/approval-waiver-and-publication.md#acceptance-system-post-publication-state The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/approval-waiver-and-publication.md#acceptance-system-publication-atomicity The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/approval-waiver-and-publication.md#acceptance-system-rejection The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/approval-waiver-and-publication.md#acceptance-system-waiver-expiry The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/case-matrix.md#acceptance-system-boundary-case The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/case-matrix.md#acceptance-system-interaction-case The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/case-matrix.md#acceptance-system-invalid-fail-separation The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/case-matrix.md#acceptance-system-negative-case The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/case-matrix.md#acceptance-system-positive-case The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/case-matrix.md#acceptance-system-regression-case The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/criteria-tolerance-and-comparison.md#acceptance-system-boundary-precision The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/criteria-tolerance-and-comparison.md#acceptance-system-deterministic-subjective-verdict The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/criteria-tolerance-and-comparison.md#acceptance-system-falsifiable-single-responsibility The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/criteria-tolerance-and-comparison.md#acceptance-system-numeric-observable The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/criteria-tolerance-and-comparison.md#acceptance-system-perceptual-observable The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/criteria-tolerance-and-comparison.md#acceptance-system-perceptual-profile-tolerance The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/criteria-tolerance-and-comparison.md#acceptance-system-semantic-observable The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/criteria-tolerance-and-comparison.md#acceptance-system-spatiotemporal-tolerance The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/criteria-tolerance-and-comparison.md#acceptance-system-structural-observable The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/criteria-tolerance-and-comparison.md#acceptance-system-tolerance-kinds The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/evidence-freshness-and-completeness.md#acceptance-system-current-historical-evidence The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/evidence-freshness-and-completeness.md#acceptance-system-evidence-conflict The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/evidence-freshness-and-completeness.md#acceptance-system-evidence-lineage-integrity The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/evidence-freshness-and-completeness.md#acceptance-system-numeric-evidence The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/evidence-freshness-and-completeness.md#acceptance-system-perceptual-evidence The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/evidence-freshness-and-completeness.md#acceptance-system-semantic-evidence The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/evidence-freshness-and-completeness.md#acceptance-system-structural-evidence The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/profiles-aggregation-and-partial-results.md#acceptance-system-aggregate-fail-incomplete The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/profiles-aggregation-and-partial-results.md#acceptance-system-aggregate-pass The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/profiles-aggregation-and-partial-results.md#acceptance-system-blocking-profile The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/profiles-aggregation-and-partial-results.md#acceptance-system-delivery-profile The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/profiles-aggregation-and-partial-results.md#acceptance-system-evidence-profile The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/profiles-aggregation-and-partial-results.md#acceptance-system-no-status-promotion The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/profiles-aggregation-and-partial-results.md#acceptance-system-numeric-uncertainty The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/profiles-aggregation-and-partial-results.md#acceptance-system-partial-artifact-evidence The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/profiles-aggregation-and-partial-results.md#acceptance-system-profile-isolation The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/profiles-aggregation-and-partial-results.md#acceptance-system-project-profile The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/profiles-aggregation-and-partial-results.md#acceptance-system-required-severity The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/profiles-aggregation-and-partial-results.md#acceptance-system-weighted-score The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/subject-surface-and-inspection.md#review-system-subject-inspection-reach The Engine emits the subject record and the coverage fold the surface returns; the request surface, its artifact separation, and its host-absence refusal belong to the production package's inspection surface.
 * @evidenceExclude specifications/review-and-acceptance/surfaces-and-sampling.md#review-system-asset-surface The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/surfaces-and-sampling.md#review-system-cross-scope-propagation The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/surfaces-and-sampling.md#review-system-delivery-surface The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/surfaces-and-sampling.md#review-system-film-surface The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/surfaces-and-sampling.md#review-system-missing-sample-state The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/surfaces-and-sampling.md#review-system-sample-interval-generalization The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/surfaces-and-sampling.md#review-system-sequence-surface The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/surfaces-and-sampling.md#review-system-shot-interval-surface The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/surfaces-and-sampling.md#review-system-spatial-view-sampling The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/target-scope-and-context.md#review-system-builder-artifact-read-refusal The Engine emits bounded facts and a few cited normalization results; it does not read builder-owned artifacts or decide how an unreadable one is refused.
 * @evidenceExclude specifications/review-and-acceptance/target-scope-and-context.md#review-system-context-invalidation The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/target-scope-and-context.md#review-system-context-unavailable The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/target-scope-and-context.md#review-system-presentation-context The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/verdict-authority-and-dissent.md#acceptance-system-criterion-owner The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/verdict-authority-and-dissent.md#acceptance-system-publication-authority The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/verdict-authority-and-dissent.md#acceptance-system-review-approval-roles The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/verdict-authority-and-dissent.md#review-system-automated-check-boundary The Engine emits bounded facts and a few cited normalization results; it does not choose review scope, collect presentation evidence, adjudicate findings, manage approval, or publish acceptance state.
 * @evidenceExclude specifications/review-and-acceptance/visual-change-reporting.md#review-system-visual-revision-snapshot The Engine emits compiled structural facts, not rendered-image identities; the revision snapshot of subject-view digests is assembled and validated by the production package's visual change report.
 * @evidenceExclude specifications/review-and-acceptance/visual-change-reporting.md#review-system-visual-change-states The Engine emits compiled structural facts, not rendered-image identities; the deterministic four-state join over two digest catalogs is performed by the production package's visual change report.
 * @evidenceExclude specifications/review-and-acceptance/visual-change-reporting.md#review-system-visual-change-digest-boundary The Engine emits compiled structural facts, not rendered-image identities; the pure fold that refuses to render, decode, or hash image bytes is owned by the production package's visual change report.
 * @evidenceExclude specifications/review-and-acceptance/visual-change-reporting.md#review-system-visual-change-evidence-separation The Engine emits compiled structural facts and owns the subject structural diff; keeping visual byte change separate from that diff and from review evidence is owned by the production package's visual change report.
 * @evidenceExclude specifications/validation-and-diagnostics/README.md#validation과-diagnostics-시스템-명세 The Engine implements cited package-local validators and findings; residual cross-package diagnostic schemas, orchestration, budgets, localization, retention, presentation, security redaction, and acceptance policy remain outside it.
 * @evidenceExclude specifications/validation-and-diagnostics/budget-and-truncation.md#validation-budget-exceeded-result The Engine implements cited package-local validators and findings; residual cross-package diagnostic schemas, orchestration, budgets, localization, retention, presentation, security redaction, and acceptance policy remain outside it.
 * @evidenceExclude specifications/validation-and-diagnostics/budget-and-truncation.md#validation-budget-retry-contract The Engine implements cited package-local validators and findings; residual cross-package diagnostic schemas, orchestration, budgets, localization, retention, presentation, security redaction, and acceptance policy remain outside it.
 * @evidenceExclude specifications/validation-and-diagnostics/classification-and-causality.md#validation-missing-state The Engine implements cited package-local validators and findings; residual cross-package diagnostic schemas, orchestration, budgets, localization, retention, presentation, security redaction, and acceptance policy remain outside it.
 * @evidenceExclude specifications/validation-and-diagnostics/classification-and-causality.md#validation-unknown-state The Engine implements cited package-local validators and findings; residual cross-package diagnostic schemas, orchestration, budgets, localization, retention, presentation, security redaction, and acceptance policy remain outside it.
 * @evidenceExclude specifications/validation-and-diagnostics/collection-order-and-termination.md#validation-diagnostic-deduplication The Engine implements cited package-local validators and findings; residual cross-package diagnostic schemas, orchestration, budgets, localization, retention, presentation, security redaction, and acceptance policy remain outside it.
 * @evidenceExclude specifications/validation-and-diagnostics/collection-order-and-termination.md#validation-fail-fast-execution The Engine implements cited package-local validators and findings; residual cross-package diagnostic schemas, orchestration, budgets, localization, retention, presentation, security redaction, and acceptance policy remain outside it.
 * @evidenceExclude specifications/validation-and-diagnostics/diagnostic-identity-location-and-severity.md#validation-diagnostic-code-catalog-reference The Engine implements cited package-local validators and findings; residual cross-package diagnostic schemas, orchestration, budgets, localization, retention, presentation, security redaction, and acceptance policy remain outside it.
 * @evidenceExclude specifications/validation-and-diagnostics/diagnostic-identity-location-and-severity.md#validation-diagnostic-identity-version The Engine implements cited package-local validators and findings; residual cross-package diagnostic schemas, orchestration, budgets, localization, retention, presentation, security redaction, and acceptance policy remain outside it.
 * @evidenceExclude specifications/validation-and-diagnostics/external-security-and-redaction.md#validation-external-failure-stages The Engine implements cited package-local validators and findings; residual cross-package diagnostic schemas, orchestration, budgets, localization, retention, presentation, security redaction, and acceptance policy remain outside it.
 * @evidenceExclude specifications/validation-and-diagnostics/external-security-and-redaction.md#validation-quarantine-adoption-state The Engine implements cited package-local validators and findings; residual cross-package diagnostic schemas, orchestration, budgets, localization, retention, presentation, security redaction, and acceptance policy remain outside it.
 * @evidenceExclude specifications/validation-and-diagnostics/external-security-and-redaction.md#validation-redaction-boundary The Engine implements cited package-local validators and findings; residual cross-package diagnostic schemas, orchestration, budgets, localization, retention, presentation, security redaction, and acceptance policy remain outside it.
 * @evidenceExclude specifications/validation-and-diagnostics/external-security-and-redaction.md#validation-security-refusal The Engine implements cited package-local validators and findings; residual cross-package diagnostic schemas, orchestration, budgets, localization, retention, presentation, security redaction, and acceptance policy remain outside it.
 * @evidenceExclude specifications/validation-and-diagnostics/localization-and-machine-results.md#validation-accessible-diagnostic-presentation The Engine implements cited package-local validators and findings; residual cross-package diagnostic schemas, orchestration, budgets, localization, retention, presentation, security redaction, and acceptance policy remain outside it.
 * @evidenceExclude specifications/validation-and-diagnostics/localization-and-machine-results.md#validation-canonical-value-format The Engine implements cited package-local validators and findings; residual cross-package diagnostic schemas, orchestration, budgets, localization, retention, presentation, security redaction, and acceptance policy remain outside it.
 * @evidenceExclude specifications/validation-and-diagnostics/localization-and-machine-results.md#validation-locale-fallback The Engine implements cited package-local validators and findings; residual cross-package diagnostic schemas, orchestration, budgets, localization, retention, presentation, security redaction, and acceptance policy remain outside it.
 * @evidenceExclude specifications/validation-and-diagnostics/localization-and-machine-results.md#validation-safe-localized-export The Engine implements cited package-local validators and findings; residual cross-package diagnostic schemas, orchestration, budgets, localization, retention, presentation, security redaction, and acceptance policy remain outside it.
 * @evidenceExclude specifications/validation-and-diagnostics/partial-artifacts-and-refusal.md#validation-artifact-refusal-boundary The Engine implements cited package-local validators and findings; residual cross-package diagnostic schemas, orchestration, budgets, localization, retention, presentation, security redaction, and acceptance policy remain outside it.
 * @evidenceExclude specifications/validation-and-diagnostics/partial-artifacts-and-refusal.md#validation-diagnostic-failure-channel The Engine implements cited package-local validators and findings; residual cross-package diagnostic schemas, orchestration, budgets, localization, retention, presentation, security redaction, and acceptance policy remain outside it.
 * @evidenceExclude specifications/validation-and-diagnostics/partial-artifacts-and-refusal.md#validation-partial-artifact-retention The Engine implements cited package-local validators and findings; residual cross-package diagnostic schemas, orchestration, budgets, localization, retention, presentation, security redaction, and acceptance policy remain outside it.
 * @evidenceExclude specifications/validation-and-diagnostics/partial-artifacts-and-refusal.md#validation-preserve-previous-complete The Engine implements cited package-local validators and findings; residual cross-package diagnostic schemas, orchestration, budgets, localization, retention, presentation, security redaction, and acceptance policy remain outside it.
 * @evidenceExclude specifications/validation-and-diagnostics/partial-artifacts-and-refusal.md#validation-resume-verified-artifacts The Engine implements cited package-local validators and findings; residual cross-package diagnostic schemas, orchestration, budgets, localization, retention, presentation, security redaction, and acceptance policy remain outside it.
 * @evidenceExclude specifications/review-and-acceptance/target-scope-and-context.md#review-system-criterion-dependency-scope Engine validators evaluate the selected facts supplied to them but neither expand review targets through criterion dependencies nor decide the resulting acceptance scope; the review-selection owner performs that orchestration before Engine validation.
 */
export type AutoMovieEngineAcceptanceEvidenceExclusions = never;
