/**
 * Engine package boundaries for formation, motion and staging.
 *
 * The package's lint.config.ts selects this declaration as an exclusion
 * carrier within its complete public-source population. It has no runtime
 * state and is not re-exported by the package barrel. Each declared
 * target/reason pair below owns one intentional negative relationship;
 * requirement and specification boundaries for this domain stay together.
 * Positive implementation citations remain on the actual public exports.
 * An exclusion neither implements a feature nor approves a rendered asset.
 * Add a boundary at its semantic owner and retain native graph validation.
 *
 * @evidenceExclude requirements/formations/README.md#formation-요구사항 The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/budgets-and-validation.md#formation-budget-policy-selection The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/budgets-and-validation.md#formation-complexity-worst-case The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/budgets-and-validation.md#formation-failure-status The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/budgets-and-validation.md#formation-resolution-validation The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/heroes-variation-and-state.md#formation-authored-variation-profile The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/heroes-variation-and-state.md#formation-continuity The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/hierarchies-and-units.md#formation-command-propagation The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/hierarchies-and-units.md#formation-hierarchy-refusal The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/hierarchies-and-units.md#formation-hierarchy-rule-provenance The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/hierarchies-and-units.md#formation-membership The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/hierarchies-and-units.md#formation-nested-frame-clock The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/hierarchies-and-units.md#formation-unit-local-variation The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/layouts-and-slots.md#formation-layout-capacity The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/layouts-and-slots.md#formation-layout-dressing The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/layouts-and-slots.md#formation-layout-selection-parameters The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/layouts-and-slots.md#formation-slot-assignment-policy The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/reform-and-group-motion.md#formation-command-response-events The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/reform-and-group-motion.md#formation-group-motion-model-selection The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/reform-and-group-motion.md#formation-reform-interior-state The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/reform-and-group-motion.md#formation-reform-refusal The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/resolution-culling-and-evidence.md#formation-resolution-culling-refusal The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/resolution-culling-and-evidence.md#formation-resolution-evidence-quantity The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/resolution-culling-and-evidence.md#formation-resolution-semantic-minimum The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/scope-and-identity.md#formation-all-repeated-subjects The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/scope-and-identity.md#formation-group-member-identity The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/scope-and-identity.md#formation-open-kinds The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/scope-and-identity.md#formation-scope-refusal The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/scope-and-identity.md#formation-story-binding The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/spacing-overlap-and-avoidance.md#formation-avoidance-integrity The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/spacing-overlap-and-avoidance.md#formation-avoidance-refusal The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/spacing-overlap-and-avoidance.md#formation-bounded-avoidance The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/spacing-overlap-and-avoidance.md#formation-static-spacing The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/spacing-overlap-and-avoidance.md#formation-temporal-overlap The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/terrain-and-routes.md#formation-group-path The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/terrain-and-routes.md#formation-relief-adaptation The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/terrain-and-routes.md#formation-route-interior The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/terrain-and-routes.md#formation-route-layout-envelope The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/terrain-and-routes.md#formation-terrain-refusal The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/formations/terrain-and-routes.md#formation-terrain-support-profile The Engine implements the cited deterministic formation layout, motion, terrain, and budget calculations; formation authorship, source-asset choice, command design, creative approval, and delivery review remain outside it.
 * @evidenceExclude requirements/motion/README.md#동작-요구사항 The Engine owns the cited deterministic sampling, retargeting, contact, and solver operations; motion capture acquisition, performance authorship, source licensing, creative selection, and visual acceptance remain outside it.
 * @evidenceExclude requirements/motion/channels-controls-and-drivers.md#motion-channel-contract The Engine owns the cited deterministic sampling, retargeting, contact, and solver operations; motion capture acquisition, performance authorship, source licensing, creative selection, and visual acceptance remain outside it.
 * @evidenceExclude requirements/motion/channels-controls-and-drivers.md#motion-channel-extensibility The Engine owns the cited deterministic sampling, retargeting, contact, and solver operations; motion capture acquisition, performance authorship, source licensing, creative selection, and visual acceptance remain outside it.
 * @evidenceExclude requirements/motion/contact-weight-and-support.md#motion-moving-support The Engine owns the cited deterministic sampling, retargeting, contact, and solver operations; motion capture acquisition, performance authorship, source licensing, creative selection, and visual acceptance remain outside it.
 * @evidenceExclude requirements/motion/layers-blends-and-transitions.md#motion-blend-refusal The Engine owns the cited deterministic sampling, retargeting, contact, and solver operations; motion capture acquisition, performance authorship, source licensing, creative selection, and visual acceptance remain outside it.
 * @evidenceExclude requirements/motion/layers-blends-and-transitions.md#motion-transition-window The Engine owns the cited deterministic sampling, retargeting, contact, and solver operations; motion capture acquisition, performance authorship, source licensing, creative selection, and visual acceptance remain outside it.
 * @evidenceExclude requirements/motion/object-motion-and-interaction.md#motion-multi-subject-interaction The Engine owns the cited deterministic sampling, retargeting, contact, and solver operations; motion capture acquisition, performance authorship, source licensing, creative selection, and visual acceptance remain outside it.
 * @evidenceExclude requirements/motion/object-motion-and-interaction.md#motion-object-handoff The Engine owns the cited deterministic sampling, retargeting, contact, and solver operations; motion capture acquisition, performance authorship, source licensing, creative selection, and visual acceptance remain outside it.
 * @evidenceExclude requirements/motion/object-motion-and-interaction.md#motion-object-state-transition The Engine owns the cited deterministic sampling, retargeting, contact, and solver operations; motion capture acquisition, performance authorship, source licensing, creative selection, and visual acceptance remain outside it.
 * @evidenceExclude requirements/motion/procedural-motion-and-gaits.md#motion-procedural-bound The Engine owns the cited deterministic sampling, retargeting, contact, and solver operations; motion capture acquisition, performance authorship, source licensing, creative selection, and visual acceptance remain outside it.
 * @evidenceExclude requirements/motion/procedural-motion-and-gaits.md#motion-procedural-variation The Engine owns the cited deterministic sampling, retargeting, contact, and solver operations; motion capture acquisition, performance authorship, source licensing, creative selection, and visual acceptance remain outside it.
 * @evidenceExclude requirements/motion/retargeting-and-scale.md#motion-retarget-non-humanoid The Engine owns the cited deterministic sampling, retargeting, contact, and solver operations; motion capture acquisition, performance authorship, source licensing, creative selection, and visual acceptance remain outside it.
 * @evidenceExclude requirements/motion/root-motion-and-trajectories.md#motion-path-fit-warp The Engine owns the cited deterministic sampling, retargeting, contact, and solver operations; motion capture acquisition, performance authorship, source licensing, creative selection, and visual acceptance remain outside it.
 * @evidenceExclude requirements/motion/root-motion-and-trajectories.md#motion-trajectory-refusal The Engine owns the cited deterministic sampling, retargeting, contact, and solver operations; motion capture acquisition, performance authorship, source licensing, creative selection, and visual acceptance remain outside it.
 * @evidenceExclude requirements/motion/scope-and-identity.md#motion-actor-object-scope The Engine owns the cited deterministic sampling, retargeting, contact, and solver operations; motion capture acquisition, performance authorship, source licensing, creative selection, and visual acceptance remain outside it.
 * @evidenceExclude requirements/motion/scope-and-identity.md#motion-all-objects-all-motion The Engine owns the cited deterministic sampling, retargeting, contact, and solver operations; motion capture acquisition, performance authorship, source licensing, creative selection, and visual acceptance remain outside it.
 * @evidenceExclude requirements/motion/scope-and-identity.md#motion-meaning-technique The Engine owns the cited deterministic sampling, retargeting, contact, and solver operations; motion capture acquisition, performance authorship, source licensing, creative selection, and visual acceptance remain outside it.
 * @evidenceExclude requirements/motion/scope-and-identity.md#motion-missing-refusal The Engine owns the cited deterministic sampling, retargeting, contact, and solver operations; motion capture acquisition, performance authorship, source licensing, creative selection, and visual acceptance remain outside it.
 * @evidenceExclude requirements/motion/scope-and-identity.md#motion-source-kinds The Engine owns the cited deterministic sampling, retargeting, contact, and solver operations; motion capture acquisition, performance authorship, source licensing, creative selection, and visual acceptance remain outside it.
 * @evidenceExclude requirements/motion/scope-and-identity.md#motion-variant-selection The Engine owns the cited deterministic sampling, retargeting, contact, and solver operations; motion capture acquisition, performance authorship, source licensing, creative selection, and visual acceptance remain outside it.
 * @evidenceExclude requirements/motion/timing-and-semantic-events.md#motion-event-markers The Engine owns the cited deterministic sampling, retargeting, contact, and solver operations; motion capture acquisition, performance authorship, source licensing, creative selection, and visual acceptance remain outside it.
 * @evidenceExclude requirements/motion/timing-and-semantic-events.md#motion-story-film-time The Engine owns the cited deterministic sampling, retargeting, contact, and solver operations; motion capture acquisition, performance authorship, source licensing, creative selection, and visual acceptance remain outside it.
 * @evidenceExclude requirements/motion/validation-and-determinism.md#motion-validation-status The Engine owns the cited deterministic sampling, retargeting, contact, and solver operations; motion capture acquisition, performance authorship, source licensing, creative selection, and visual acceptance remain outside it.
 * @evidenceExclude requirements/motion/validation-and-determinism.md#motion-visual-review The Engine owns the cited deterministic sampling, retargeting, contact, and solver operations; motion capture acquisition, performance authorship, source licensing, creative selection, and visual acceptance remain outside it.
 * @evidenceExclude requirements/staging/README.md#장면-연출-요구사항 The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/budgets-safety-and-validation.md#staging-authored-safety-state The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/budgets-safety-and-validation.md#staging-validation-context The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/budgets-safety-and-validation.md#staging-validation-twins The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/budgets-safety-and-validation.md#staging-viewer-review The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/coverage-and-alternative-takes.md#staging-coverage-kinds The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/coverage-and-alternative-takes.md#staging-coverage-matrix The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/coverage-and-alternative-takes.md#staging-coverage-overlap The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/coverage-and-alternative-takes.md#staging-take-comparability The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/coverage-and-alternative-takes.md#staging-take-identity The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/coverage-and-alternative-takes.md#staging-take-selection The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/events-and-timing.md#staging-event-frame-grid The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/events-and-timing.md#staging-event-order The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/events-and-timing.md#staging-event-timebase-interval The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/interactions-and-choreography.md#staging-choreography-alternatives The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/interactions-and-choreography.md#staging-interaction-contact-contract The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/interactions-and-choreography.md#staging-interaction-roles The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/marks-zones-and-blocking.md#staging-intentional-spatial-exceptions The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/marks-zones-and-blocking.md#staging-mark-reference-frame The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/marks-zones-and-blocking.md#staging-mark-refusal The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/marks-zones-and-blocking.md#staging-zones The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/scope-and-source-of-truth.md#staging-autofill-refusal The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/scope-and-source-of-truth.md#staging-open-style The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/scope-and-source-of-truth.md#staging-plan-alternatives The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/scope-and-source-of-truth.md#staging-story-distinction The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/shot-contracts-and-deliveries.md#staging-shot-contract-freshness The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/state-handoff-and-continuity.md#staging-authored-discontinuity The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/state-handoff-and-continuity.md#staging-continuity-finding The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/state-handoff-and-continuity.md#staging-cross-domain-continuity The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/state-handoff-and-continuity.md#staging-edit-boundary-state The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/state-handoff-and-continuity.md#staging-offscreen-change The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/state-handoff-and-continuity.md#staging-state-alternatives The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/state-handoff-and-continuity.md#staging-state-lineage The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/subjects-and-object-staging.md#staging-dressing-story-props The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/subjects-and-object-staging.md#staging-external-asset-use The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/subjects-and-object-staging.md#staging-placement-alternatives The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/subjects-and-object-staging.md#staging-placement-design-geometry-trace The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/visibility-and-readability.md#staging-intentional-unreadability The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/visibility-and-readability.md#staging-multi-subject-priority The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/visibility-and-readability.md#staging-readable-duration The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude requirements/staging/visibility-and-readability.md#staging-reveal-concealment The Engine realizes the cited marks, blocking, placement, interaction, and replay calculations; staging authorship, coverage choice, rehearsal judgment, exception approval, and production coordination remain outside it.
 * @evidenceExclude specifications/performance-motion-and-staging/README.md#퍼포먼스-모션과-스테이징-시스템-명세 The Engine implements the concrete performance, motion, formation, and staging units cited positively; residual authoring authority, source adoption, review, and delivery contracts remain outside the deterministic solver boundary.
 * @evidenceExclude specifications/performance-motion-and-staging/actor-identity-state-and-fidelity.md#performance-actor-representation-fidelity-boundary The Engine implements the concrete performance, motion, formation, and staging units cited positively; residual authoring authority, source adoption, review, and delivery contracts remain outside the deterministic solver boundary.
 * @evidenceExclude specifications/performance-motion-and-staging/actor-identity-state-and-fidelity.md#performance-actor-validation-output-compatibility The Engine implements the concrete performance, motion, formation, and staging units cited positively; residual authoring authority, source adoption, review, and delivery contracts remain outside the deterministic solver boundary.
 * @evidenceExclude specifications/performance-motion-and-staging/formation-identity-layout-and-terrain.md#performance-formation-hierarchy-membership-command The Engine implements the concrete performance, motion, formation, and staging units cited positively; residual authoring authority, source adoption, review, and delivery contracts remain outside the deterministic solver boundary.
 * @evidenceExclude specifications/performance-motion-and-staging/formation-identity-layout-and-terrain.md#performance-formation-sounding-membership-handoff The Engine implements the concrete performance, motion, formation, and staging units cited positively; residual authoring authority, source adoption, review, and delivery contracts remain outside the deterministic solver boundary.
 * @evidenceExclude specifications/performance-motion-and-staging/formation-identity-layout-and-terrain.md#performance-formation-spacing-overlap-avoidance The Engine implements the concrete performance, motion, formation, and staging units cited positively; residual authoring authority, source adoption, review, and delivery contracts remain outside the deterministic solver boundary.
 * @evidenceExclude specifications/performance-motion-and-staging/formation-motion-resolution-and-budgets.md#performance-formation-budget-worst-case-cost The Engine implements the concrete performance, motion, formation, and staging units cited positively; residual authoring authority, source adoption, review, and delivery contracts remain outside the deterministic solver boundary.
 * @evidenceExclude specifications/performance-motion-and-staging/rig-deformation-and-retargeting.md#performance-rig-compatibility-fidelity-ceiling The Engine implements the concrete performance, motion, formation, and staging units cited positively; residual authoring authority, source adoption, review, and delivery contracts remain outside the deterministic solver boundary.
 * @evidenceExclude specifications/performance-motion-and-staging/staging-events-coverage-and-validation.md#performance-staging-viewer-evidence-prototype-ceiling The Engine implements the concrete performance, motion, formation, and staging units cited positively; residual authoring authority, source adoption, review, and delivery contracts remain outside the deterministic solver boundary.
 * @evidenceExclude specifications/performance-motion-and-staging/staging-space-state-and-choreography.md#performance-staging-compatibility-stale-state The Engine implements the concrete performance, motion, formation, and staging units cited positively; residual authoring authority, source adoption, review, and delivery contracts remain outside the deterministic solver boundary.
 * @evidenceExclude specifications/performance-motion-and-staging/formation-identity-layout-and-terrain.md#performance-formation-static-clearance The builder validates model-derived body bounds against compiled formation columns and slots before runtime; Engine owns the admitted slot, ground, and motion calculations without repeating that compile-time clearance gate.
 * @evidenceExclude specifications/performance-motion-and-staging/formation-motion-resolution-and-budgets.md#performance-formation-motion-validation Engine formation samplers resolve already-valid cues; they do not validate cue identity, member count, intervals, or endpoint and interior coverage.
 */
export type AutoMovieEnginePerformanceEvidenceExclusions = never;
