/**
 * Engine package boundaries for authoring authority and provenance.
 *
 * The package's lint.config.ts selects this declaration as an exclusion
 * carrier within its complete public-source population. It has no runtime
 * state and is not re-exported by the package barrel. Each declared
 * target/reason pair below owns one intentional negative relationship;
 * requirement and specification boundaries for this domain stay together.
 * Positive implementation citations remain on the actual public exports.
 * An exclusion neither implements a feature nor approves a rendered asset.
 * Add a boundary at its semantic owner and retain native graph validation.
 *
 * @evidenceExclude requirements/evidence-and-provenance/completeness-freshness-and-refusal.md#evidence-honest-refusal The engine returns bounded computation and validation results; it does not grant current, verified, approved or publishable status from combined rights, custody, credential and review-authority obligations.
 * @evidenceExclude specifications/evidence-and-provenance/completeness-freshness-and-refusal.md#evp-fail-closed-decision-gate The engine does not own the publication decision gate that combines obligation matrices, integrity, rights, custody, privacy, execution conditions and authority. Its source exclusion declarations implement none of those runtime checks.
 * @evidenceExclude requirements/agent-authoring/README.md#에이전트-저작-요구사항 The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/capability-discovery.md#agent-capability-gap-discovery The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/capability-discovery.md#agent-choice-surface-discovery The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/capability-discovery.md#agent-diagnostic-discovery The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/capability-discovery.md#agent-technique-example The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/capability-discovery.md#agent-topic-document-discovery The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/deterministic-precomputation.md#agent-precomputed-closed-basis The Engine evaluates already-authored typed scene inputs; explicit source-derived generation, tracked artifact publication, compile-time freshness inspection, and provenance-ledger separation belong to the production project workflow.
 * @evidenceExclude requirements/agent-authoring/deterministic-precomputation.md#agent-precomputed-explicit-generation The Engine evaluates already-authored typed scene inputs; explicit source-derived generation, tracked artifact publication, compile-time freshness inspection, and provenance-ledger separation belong to the production project workflow.
 * @evidenceExclude requirements/agent-authoring/deterministic-precomputation.md#agent-precomputed-compile-refusal The Engine evaluates already-authored typed scene inputs; explicit source-derived generation, tracked artifact publication, compile-time freshness inspection, and provenance-ledger separation belong to the production project workflow.
 * @evidenceExclude requirements/agent-authoring/deterministic-precomputation.md#agent-precomputed-portable-publication The Engine evaluates already-authored typed scene inputs; explicit source-derived generation, tracked artifact publication, compile-time freshness inspection, and provenance-ledger separation belong to the production project workflow.
 * @evidenceExclude requirements/agent-authoring/deterministic-precomputation.md#agent-precomputed-provenance-separation The Engine evaluates already-authored typed scene inputs; explicit source-derived generation, tracked artifact publication, compile-time freshness inspection, and provenance-ledger separation belong to the production project workflow.
 * @evidenceExclude requirements/agent-authoring/knowledge-boundary.md#agent-authoring-api-refusal The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/knowledge-boundary.md#agent-content-supply-refusal The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/knowledge-boundary.md#agent-contract-guidance The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/knowledge-boundary.md#agent-host-evidence The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/knowledge-boundary.md#agent-no-surprise-external-effects The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/knowledge-boundary.md#agent-provider-neutrality The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/partial-work.md#agent-atomic-compilation The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/partial-work.md#agent-declared-omission The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/partial-work.md#agent-partial-result-control The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/partial-work.md#agent-partial-verification-scope The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/partial-work.md#agent-partial-work-gap-distinction The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/partial-work.md#agent-resumable-authoring The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/project-ownership.md#agent-ambiguous-ownership-refusal The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/project-ownership.md#agent-authoring-tool-replaceability The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/project-ownership.md#agent-editable-source-authority The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/project-ownership.md#agent-portable-authoring The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/project-ownership.md#agent-project-owned-bytes The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/project-ownership.md#agent-repository-project-boundary The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/roles-and-authorities.md#agent-author-authority The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/roles-and-authorities.md#agent-director-authority The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/roles-and-authorities.md#agent-evidence-producer-authority The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/roles-and-authorities.md#agent-runtime-authority The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/roles-and-authorities.md#agent-user-delegation-authority The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/source-owned-loop.md#agent-narrowest-valid-check The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/source-owned-loop.md#agent-reviewable-source-change The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/agent-authoring/source-owned-loop.md#agent-source-result-link The Engine has no LLM session, source-editing, prompt, tool-selection, or authoring-agent workflow; it only evaluates already-authored typed inputs.
 * @evidenceExclude requirements/evidence-and-provenance/README.md#증거와-출처-계보-요구사항 Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/canonical-digests-and-content-identity.md#integrity-algorithm-change-and-collision Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/canonical-digests-and-content-identity.md#integrity-byte-and-semantic-identity Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/canonical-digests-and-content-identity.md#integrity-mutable-reference-snapshot Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/chain-of-custody-and-tamper-detection.md#custody-distributed-copy-verification Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/chain-of-custody-and-tamper-detection.md#custody-gap-and-quarantine Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/chain-of-custody-and-tamper-detection.md#custody-signature-attestation-boundary Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/chain-of-custody-and-tamper-detection.md#custody-tamper-evident-history Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/completeness-freshness-and-refusal.md#evidence-reapproval-after-change Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/entities-activities-agents-and-lineage.md#provenance-activity-inputs-outputs Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/entities-activities-agents-and-lineage.md#provenance-agent-role-responsibility Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/entities-activities-agents-and-lineage.md#provenance-lineage-gaps Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/entities-activities-agents-and-lineage.md#provenance-primary-and-derived-source Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/observations-claims-and-human-judgments.md#evidence-human-judgment-history Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/privacy-credentials-and-disclosure.md#privacy-credential-omission Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/privacy-credentials-and-disclosure.md#privacy-erasure-and-lineage Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/privacy-credentials-and-disclosure.md#privacy-external-service-disclosure Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/privacy-credentials-and-disclosure.md#privacy-human-identity-and-pseudonym Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/privacy-credentials-and-disclosure.md#privacy-redaction-and-source-relation Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/privacy-credentials-and-disclosure.md#privacy-sensitive-metadata Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/retention-invalidation-and-disposal.md#retention-archive-retrieval-and-restoration Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/retention-invalidation-and-disposal.md#retention-hold-and-exception Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/retention-invalidation-and-disposal.md#retention-invalidation-versus-deletion Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/retention-invalidation-and-disposal.md#retention-verifiable-disposal Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/scope-identity-and-status.md#evidence-explicit-status Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/scope-identity-and-status.md#evidence-scope-and-exclusions Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/third-party-sources-rights-and-attribution.md#third-party-attribution-propagation Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/third-party-sources-rights-and-attribution.md#third-party-rights-and-terms Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/third-party-sources-rights-and-attribution.md#third-party-source-access-restriction Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/evidence-and-provenance/third-party-sources-rights-and-attribution.md#third-party-source-change-and-withdrawal Engine code participates in traceability and emits bounded facts, but it does not operate the repository-wide evidence registry, review ledger, retention policy, provenance publication, or approval gate.
 * @evidenceExclude requirements/production-evidence/README.md The Engine evaluates admitted production values; it does not configure the generated project's authoring evidence graph.
 * @evidenceExclude requirements/production-evidence/graph.md The Engine evaluates admitted production values; it does not configure the generated project's authoring evidence graph.
 * @evidenceExclude requirements/production-evidence/native-input.md#agent-production-evidence-native-boundary The engine receives admitted production values; native graph configuration belongs to the evidence adapter before engine evaluation.
 * @evidenceExclude requirements/production-evidence/input.md The Engine evaluates admitted production values; it does not configure the generated project's authoring evidence graph.
 * @evidenceExclude specifications/authoring-and-authority/README.md#저작과-권한-시스템-명세 The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/capability-and-content-boundary.md#spec-authoring-capability-extension-compatibility The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/capability-and-content-boundary.md#spec-authoring-capability-failure-gap The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/capability-and-content-boundary.md#spec-authoring-capability-not-content-invariant The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/capability-and-content-boundary.md#spec-authoring-capability-state The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/capability-and-content-boundary.md#spec-authoring-system-project-responsibility The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/deterministic-precomputed-artifacts.md#spec-authoring-precomputed-manifest The Engine consumes typed scene inputs after the project gate; the production project workflow owns the derived ledger, basis hashing, explicit publication, freshness refusal, portable filesystem policy, and unchanged source-execution budget.
 * @evidenceExclude specifications/authoring-and-authority/deterministic-precomputed-artifacts.md#spec-authoring-precomputed-basis The Engine consumes typed scene inputs after the project gate; the production project workflow owns the derived ledger, basis hashing, explicit publication, freshness refusal, portable filesystem policy, and unchanged source-execution budget.
 * @evidenceExclude specifications/authoring-and-authority/deterministic-precomputed-artifacts.md#spec-authoring-precomputed-generation The Engine consumes typed scene inputs after the project gate; the production project workflow owns the derived ledger, basis hashing, explicit publication, freshness refusal, portable filesystem policy, and unchanged source-execution budget.
 * @evidenceExclude specifications/authoring-and-authority/deterministic-precomputed-artifacts.md#spec-authoring-precomputed-freshness The Engine consumes typed scene inputs after the project gate; the production project workflow owns the derived ledger, basis hashing, explicit publication, freshness refusal, portable filesystem policy, and unchanged source-execution budget.
 * @evidenceExclude specifications/authoring-and-authority/deterministic-precomputed-artifacts.md#spec-authoring-precomputed-portability The Engine consumes typed scene inputs after the project gate; the production project workflow owns the derived ledger, basis hashing, explicit publication, freshness refusal, portable filesystem policy, and unchanged source-execution budget.
 * @evidenceExclude specifications/authoring-and-authority/delegation-and-decision-authority.md#spec-authoring-agent-input-output The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/delegation-and-decision-authority.md#spec-authoring-authority-compatibility The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/delegation-and-decision-authority.md#spec-authoring-authority-violation-failure The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/delegation-and-decision-authority.md#spec-authoring-decision-authority-state The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/delegation-and-decision-authority.md#spec-authoring-runtime-evidence-authority-invariant The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/delegation-and-decision-authority.md#spec-authoring-user-director-input The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/external-execution-and-provider-neutrality.md#spec-authoring-external-adoption-output The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/external-execution-and-provider-neutrality.md#spec-authoring-external-execution-state The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/external-execution-and-provider-neutrality.md#spec-authoring-external-failure-substitution The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/external-execution-and-provider-neutrality.md#spec-authoring-external-request-output The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/external-execution-and-provider-neutrality.md#spec-authoring-external-selection-input The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/external-execution-and-provider-neutrality.md#spec-authoring-provider-compatibility The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/external-execution-and-provider-neutrality.md#spec-authoring-provider-source-invariant The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/knowledge-evidence-and-tool-boundary.md#spec-authoring-host-evidence-output The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/knowledge-evidence-and-tool-boundary.md#spec-authoring-knowledge-request-output The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/knowledge-evidence-and-tool-boundary.md#spec-authoring-tool-authoring-invariant The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/knowledge-evidence-and-tool-boundary.md#spec-authoring-tool-boundary-compatibility The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/knowledge-evidence-and-tool-boundary.md#spec-authoring-tool-choice-discovery The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/knowledge-evidence-and-tool-boundary.md#spec-authoring-tool-content-side-effect-invariant The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/knowledge-evidence-and-tool-boundary.md#spec-authoring-tool-diagnostic-failure The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/partial-targets-and-atomic-results.md#spec-authoring-partial-atomic-invariant The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/partial-targets-and-atomic-results.md#spec-authoring-partial-omission-failure The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/partial-targets-and-atomic-results.md#spec-authoring-partial-result-checkpoint The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/partial-targets-and-atomic-results.md#spec-authoring-partial-resume-compatibility The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/partial-targets-and-atomic-results.md#spec-authoring-partial-target-input The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/partial-targets-and-atomic-results.md#spec-authoring-partial-verification-invariant The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/partial-targets-and-atomic-results.md#spec-authoring-partial-work-state The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/prototype-determinism-and-fidelity.md#spec-authoring-choice-determinism-invariant The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/prototype-determinism-and-fidelity.md#spec-authoring-downstream-fidelity-output The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/prototype-determinism-and-fidelity.md#spec-authoring-fidelity-failure-choice The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/prototype-determinism-and-fidelity.md#spec-authoring-prototype-exclusion-compatibility The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/prototype-determinism-and-fidelity.md#spec-authoring-structural-output-invariant The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/source-authority-and-derivation.md#spec-authoring-derivation-output-lineage The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/source-authority-and-derivation.md#spec-authoring-source-change-impact-invariant The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/source-authority-and-derivation.md#spec-authoring-source-derivation-state The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/source-authority-and-derivation.md#spec-authoring-source-ownership-failure The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/authoring-and-authority/source-authority-and-derivation.md#spec-authoring-source-resume-compatibility The Engine evaluates typed authored inputs but does not own source editing, agent authority, capability negotiation, change approval, or authoring-session state.
 * @evidenceExclude specifications/evidence-and-provenance/README.md#증거와-출처-계보-시스템-명세 The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/canonical-digests-and-content-identity.md#evp-algorithm-migration-collision The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/canonical-digests-and-content-identity.md#evp-byte-semantic-identity The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/canonical-digests-and-content-identity.md#evp-mutable-locator-snapshot The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/chain-of-custody-and-tamper-detection.md#evp-custody-quarantine-state The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/chain-of-custody-and-tamper-detection.md#evp-distributed-copy-verification The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/chain-of-custody-and-tamper-detection.md#evp-signature-verification-boundary The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/chain-of-custody-and-tamper-detection.md#evp-tamper-evident-correction-chain The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/completeness-freshness-and-refusal.md#evp-reapproval-after-change The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/entities-activities-agents-and-lineage.md#evp-activity-execution-record The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/entities-activities-agents-and-lineage.md#evp-actor-role-binding The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/entities-activities-agents-and-lineage.md#evp-lineage-gap-representation The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/entities-activities-agents-and-lineage.md#evp-primary-derived-source-relation The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/observations-claims-and-human-judgments.md#evp-human-judgment-activity The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/privacy-credentials-and-disclosure.md#evp-credential-exclusion-gate The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/privacy-credentials-and-disclosure.md#evp-erasure-tombstone The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/privacy-credentials-and-disclosure.md#evp-external-transfer-authorization The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/privacy-credentials-and-disclosure.md#evp-human-identity-pseudonymization The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/privacy-credentials-and-disclosure.md#evp-redaction-derivative The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/privacy-credentials-and-disclosure.md#evp-sensitive-metadata-filtering The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/retention-invalidation-and-disposal.md#evp-archive-retrieval-activity The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/retention-invalidation-and-disposal.md#evp-disposal-execution-receipt The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/retention-invalidation-and-disposal.md#evp-invalidation-deletion-state The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/retention-invalidation-and-disposal.md#evp-retention-hold The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/scope-identity-and-status.md#evp-record-scope-model The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/scope-identity-and-status.md#evp-record-status-transition The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/third-party-sources-rights-and-attribution.md#evp-attribution-propagation-closure The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/third-party-sources-rights-and-attribution.md#evp-restricted-source-verification The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/third-party-sources-rights-and-attribution.md#evp-source-terms-change-impact The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/evidence-and-provenance/third-party-sources-rights-and-attribution.md#evp-third-party-rights-evaluation The Engine participates through source citations and bounded findings; it does not implement evidence storage, provenance custody, retention, invalidation policy, publication, or cross-package decision gates.
 * @evidenceExclude specifications/production-evidence/README.md The Engine starts after authoring admission and does not implement evidence stages, graph construction, or source-tree validation.
 * @evidenceExclude specifications/production-evidence/graph.md The Engine starts after authoring admission and does not implement evidence stages, graph construction, or source-tree validation.
 * @evidenceExclude specifications/production-evidence/native-input.md#spec-authoring-production-evidence-native-boundary Graph declaration projection is performed by the evidence adapter, not by deterministic scene or geometry evaluation.
 * @evidenceExclude specifications/production-evidence/input.md The Engine starts after authoring admission and does not implement evidence stages, graph construction, or source-tree validation.
 * @evidenceExclude requirements/agent-authoring/production-language.md#agent-production-language-contract The Engine evaluates already-authored typed inputs; the production language module, contract baseline and migration, contract discriminators and delivery index are generated-project authoring contracts owned by the evidence and template packages.
 * @evidenceExclude requirements/production-evidence/authoring-contracts.md#agent-production-evidence-contract-discriminators The Engine evaluates already-authored typed inputs; the production language module, contract baseline and migration, contract discriminators and delivery index are generated-project authoring contracts owned by the evidence and template packages.
 * @evidenceExclude specifications/authoring-and-authority/production-language.md#spec-authoring-production-language-module The Engine evaluates already-authored typed inputs; the production language module, contract baseline and migration, contract discriminators and delivery index are generated-project authoring contracts owned by the evidence and template packages.
 * @evidenceExclude specifications/production-evidence/authoring-contracts.md#spec-authoring-production-evidence-contract-discriminators The Engine evaluates already-authored typed inputs; the production language module, contract baseline and migration, contract discriminators and delivery index are generated-project authoring contracts owned by the evidence and template packages.
 * @evidenceExclude requirements/agent-authoring/reference-navigation.md#agent-reference-selection The Engine evaluates typed scene inputs; authored-Markdown navigation and the repository sandbox launcher are separate authoring tools, not engine operations.
 * @evidenceExclude requirements/agent-authoring/reference-navigation.md#agent-reference-source The Engine evaluates typed scene inputs; authored-Markdown navigation and the repository sandbox launcher are separate authoring tools, not engine operations.
 * @evidenceExclude requirements/agent-authoring/reference-navigation.md#agent-reference-bounds The Engine evaluates typed scene inputs; authored-Markdown navigation and the repository sandbox launcher are separate authoring tools, not engine operations.
 * @evidenceExclude requirements/agent-authoring/reference-navigation.md#agent-reference-isolation The Engine evaluates typed scene inputs; authored-Markdown navigation and the repository sandbox launcher are separate authoring tools, not engine operations.
 * @evidenceExclude requirements/agent-authoring/reference-navigation.md#agent-reference-transports The Engine evaluates typed scene inputs; authored-Markdown navigation and the repository sandbox launcher are separate authoring tools, not engine operations.
 * @evidenceExclude requirements/agent-authoring/project-ownership.md#agent-sandbox-write-boundary The Engine evaluates typed scene inputs; authored-Markdown navigation and the repository sandbox launcher are separate authoring tools, not engine operations.
 * @evidenceExclude specifications/authoring-and-authority/reference-navigation.md#spec-reference-selection The Engine evaluates typed scene inputs; authored-Markdown navigation and the repository sandbox launcher are separate authoring tools, not engine operations.
 * @evidenceExclude specifications/authoring-and-authority/reference-navigation.md#spec-reference-source The Engine evaluates typed scene inputs; authored-Markdown navigation and the repository sandbox launcher are separate authoring tools, not engine operations.
 * @evidenceExclude specifications/authoring-and-authority/reference-navigation.md#spec-reference-bounds The Engine evaluates typed scene inputs; authored-Markdown navigation and the repository sandbox launcher are separate authoring tools, not engine operations.
 * @evidenceExclude specifications/authoring-and-authority/reference-navigation.md#spec-reference-isolation The Engine evaluates typed scene inputs; authored-Markdown navigation and the repository sandbox launcher are separate authoring tools, not engine operations.
 * @evidenceExclude specifications/authoring-and-authority/reference-navigation.md#spec-reference-transports The Engine evaluates typed scene inputs; authored-Markdown navigation and the repository sandbox launcher are separate authoring tools, not engine operations.
 * @evidenceExclude specifications/authoring-and-authority/source-authority-and-derivation.md#spec-authoring-sandbox-physical-ownership The Engine evaluates typed scene inputs; authored-Markdown navigation and the repository sandbox launcher are separate authoring tools, not engine operations.
 */
export type AutoMovieEngineAuthoringEvidenceExclusions = never;
