/**
 * Engine package boundaries for narrative intent and editorial decisions.
 *
 * The package's lint.config.ts selects this declaration as an exclusion
 * carrier within its complete public-source population. It has no runtime
 * state and is not re-exported by the package barrel. Each declared
 * target/reason pair below owns one intentional negative relationship;
 * requirement and specification boundaries for this domain stay together.
 * Positive implementation citations remain on the actual public exports.
 * An exclusion neither implements a feature nor approves a rendered asset.
 * Add a boundary at its semantic owner and retain native graph validation.
 *
 * @evidenceExclude requirements/editorial/README.md#편집-요구사항 The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/clips-source-ranges-and-handles.md#editorial-clip-handles The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/clips-source-ranges-and-handles.md#editorial-clip-replacement The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/clips-source-ranges-and-handles.md#editorial-clip-retime-direction The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/clips-source-ranges-and-handles.md#editorial-missing-generated-media The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/conform-and-media-references.md#editorial-conform-publication The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/conform-and-media-references.md#editorial-conform-refusal The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/conform-and-media-references.md#editorial-image-sequence-movie The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/conform-and-media-references.md#editorial-media-relink The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/conform-and-media-references.md#editorial-partial-conform-recovery The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/conform-and-media-references.md#editorial-proxy-final-conform The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/conform-and-media-references.md#editorial-reference-resolution The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/conform-and-media-references.md#editorial-time-channel-conform The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/continuity-and-film-grammar.md#editorial-continuity-incomplete The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/continuity-and-film-grammar.md#editorial-match-on-action The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/continuity-and-film-grammar.md#editorial-reaction-information The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/continuity-and-film-grammar.md#editorial-state-continuity The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/markers-effects-and-metadata.md#editorial-effect-ordering The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/markers-effects-and-metadata.md#editorial-effects The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/markers-effects-and-metadata.md#editorial-marker-event-distinction The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/markers-effects-and-metadata.md#editorial-marker-partial-result The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/markers-effects-and-metadata.md#editorial-marker-scope The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/markers-effects-and-metadata.md#editorial-metadata-provenance The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/markers-effects-and-metadata.md#editorial-metadata-refusal The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/pacing-and-rhythm.md#editorial-audiovisual-rhythm The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/pacing-and-rhythm.md#editorial-narrative-priority The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/pacing-and-rhythm.md#editorial-pacing-partial-analysis The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/pacing-and-rhythm.md#editorial-pacing-version-comparison The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/pacing-and-rhythm.md#editorial-readability-time The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/picture-and-sound-edits.md#editorial-audio-boundary-refusal The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/picture-and-sound-edits.md#editorial-channel-mix-relation The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/picture-and-sound-edits.md#editorial-dialogue-edits The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/picture-and-sound-edits.md#editorial-effects-music-edits The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/picture-and-sound-edits.md#editorial-room-tone-ambience The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/picture-and-sound-edits.md#editorial-silence-missing-audio The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/picture-and-sound-edits.md#editorial-sound-emission-presentation The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/rational-time-and-ranges.md#editorial-range-operations The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/scope-and-identity.md#editorial-identity-boundary The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/tracks-stacks-and-composition.md#editorial-enable-alternatives The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/tracks-stacks-and-composition.md#editorial-layered-stacks The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/tracks-stacks-and-composition.md#editorial-nested-composition The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/tracks-stacks-and-composition.md#editorial-picture-composition The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/tracks-stacks-and-composition.md#editorial-sound-composition The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/transitions-and-overlaps.md#editorial-picture-sound-transition The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/transitions-and-overlaps.md#editorial-transition-handles The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/transitions-and-overlaps.md#editorial-transition-partial-state The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/validation.md#editorial-film-review The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/validation.md#editorial-story-coverage The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/validation.md#editorial-validation-boundaries The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/validation.md#editorial-validation-recovery The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/validation.md#editorial-validation-refusal The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/validation.md#editorial-validation-status The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/versions-and-alternative-cuts.md#editorial-alternative-independence The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/versions-and-alternative-cuts.md#editorial-append-only-revision The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/versions-and-alternative-cuts.md#editorial-difference-report The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/versions-and-alternative-cuts.md#editorial-selection-state The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/versions-and-alternative-cuts.md#editorial-version-merge-conflict The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/versions-and-alternative-cuts.md#editorial-version-refusal The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/editorial/versions-and-alternative-cuts.md#editorial-version-stale-review The Engine implements only the cited deterministic timeline and cut operations; editorial authorship, alternative selection, conform authority, collaboration, publication, and final-delivery decisions remain outside it.
 * @evidenceExclude requirements/story/README.md#이야기-저작-요구사항 The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/beats-and-causality.md#story-action-reaction The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/beats-and-causality.md#story-beat-state-change The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/beats-and-causality.md#story-causal-link-types The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/beats-and-causality.md#story-causality-gap-reporting The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/beats-and-causality.md#story-choice-cost-reversal The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/beats-and-causality.md#story-setup-payoff The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/coverage-and-acceptance.md#story-acceptance-negative-twin The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/coverage-and-acceptance.md#story-acceptance-result-provenance The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/coverage-and-acceptance.md#story-coverage-roles-duplication The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/coverage-and-acceptance.md#story-film-level-review The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/coverage-and-acceptance.md#story-final-acceptance The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/coverage-and-acceptance.md#story-orphan-gap The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/coverage-and-acceptance.md#story-sequence-acceptance The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/dialogue-language-and-silence.md#story-dialogue-action-interaction The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/dialogue-language-and-silence.md#story-dialogue-continuity The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/dialogue-language-and-silence.md#story-dialogue-quotation-provenance The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/dialogue-language-and-silence.md#story-dialogue-text-intent The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/dialogue-language-and-silence.md#story-dialogue-timing-intent The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/dialogue-language-and-silence.md#story-dialogue-variants-approval The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/dialogue-language-and-silence.md#story-dialogue-voice-text-separation The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/dialogue-language-and-silence.md#story-multilingual-dialogue The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/dialogue-language-and-silence.md#story-silence-nonverbal The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/dramatic-characters-goals-and-relations.md#story-character-agency-viewpoint The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/dramatic-characters-goals-and-relations.md#story-character-arc-milestones The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/dramatic-characters-goals-and-relations.md#story-character-completeness The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/dramatic-characters-goals-and-relations.md#story-character-goals-obstacles The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/dramatic-characters-goals-and-relations.md#story-character-groups-members The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/dramatic-characters-goals-and-relations.md#story-character-information-provenance The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/dramatic-characters-goals-and-relations.md#story-character-presence-absence The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/dramatic-characters-goals-and-relations.md#story-character-relations The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/logline-and-premise.md#story-logline-alternatives The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/logline-and-premise.md#story-logline-opening-ending-relation The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/logline-and-premise.md#story-logline-overclaim-refusal The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/logline-and-premise.md#story-logline-promises-exclusions The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/logline-and-premise.md#story-logline-scope-bound The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/logline-and-premise.md#story-observable-core The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/logline-and-premise.md#story-premise-question The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/logline-and-premise.md#story-premise-review-status The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/revision-and-change-impact.md#story-deletion-invalidation The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/revision-and-change-impact.md#story-revision-alternatives The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/revision-and-change-impact.md#story-revision-approval-status The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/revision-and-change-impact.md#story-revision-conflict-authority The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/revision-and-change-impact.md#story-revision-freshness The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/revision-and-change-impact.md#story-revision-lineage The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/revision-and-change-impact.md#story-revision-reason The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/revision-and-change-impact.md#story-revision-rollback-reproduction The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/revision-and-change-impact.md#story-revision-soft-lock The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/revision-and-change-impact.md#story-revision-stable-identity The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/scenes-and-observable-action.md#story-scene-local-arc The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/scenes-and-observable-action.md#story-scene-number-soft-lock The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/scenes-and-observable-action.md#story-scene-participant-modes The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/scenes-and-observable-action.md#story-scene-place-time The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/scenes-and-observable-action.md#story-scene-shot-separation The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/scope-and-source-of-truth.md#story-capability-content-boundary The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/scope-and-source-of-truth.md#story-fact-fiction-provenance The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/scope-and-source-of-truth.md#story-open-form The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/scope-and-source-of-truth.md#story-production-distinction The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/scope-and-source-of-truth.md#story-source-authority The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/scope-and-source-of-truth.md#story-unknown-preservation The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/story-clock-and-state.md#story-duration-deadline-recurrence The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/story-clock-and-state.md#story-state-ledger The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/story-clock-and-state.md#story-state-transition-causes The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/story-clock-and-state.md#story-time-contradictions The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/story-clock-and-state.md#story-time-ellipsis-compression The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/themes-motifs-and-subtext.md#story-motif-absence-restraint The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/themes-motifs-and-subtext.md#story-motif-variation The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/themes-motifs-and-subtext.md#story-subtext-performance The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/themes-motifs-and-subtext.md#story-symbol-source-context The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/themes-motifs-and-subtext.md#story-theme-acceptance-boundary The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/themes-motifs-and-subtext.md#story-theme-change-impact The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/themes-motifs-and-subtext.md#story-theme-coverage The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/themes-motifs-and-subtext.md#story-theme-interpretation-boundary The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/themes-motifs-and-subtext.md#story-theme-progression-counterpoint The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/treatment-and-sequences.md#story-parallel-intercut-lines The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/treatment-and-sequences.md#story-sequence-alternatives-order The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/treatment-and-sequences.md#story-sequence-causality The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/treatment-and-sequences.md#story-sequence-identity The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/treatment-and-sequences.md#story-sequence-scale-weight The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/treatment-and-sequences.md#story-sequence-state-handoff The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/treatment-and-sequences.md#story-treatment-completeness The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude requirements/story/treatment-and-sequences.md#story-treatment-coverage The Engine does not author or adjudicate narrative structure, character goals, beats, theme, dialogue intent, continuity authority, or screenplay revisions; it consumes compiled production facts.
 * @evidenceExclude specifications/narrative-and-intent/README.md#narrative-intent-readme The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/alternatives-revisions-and-compatibility.md#narrative-intent-alternative-selection-approval The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/alternatives-revisions-and-compatibility.md#narrative-intent-canonical-comparison-revalidation The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/alternatives-revisions-and-compatibility.md#narrative-intent-compatibility-invariants The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/alternatives-revisions-and-compatibility.md#narrative-intent-revision-conflict-rollback The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/alternatives-revisions-and-compatibility.md#narrative-intent-revision-deletion-soft-lock The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/alternatives-revisions-and-compatibility.md#narrative-intent-revision-reason-status The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/budgets-continuity-and-deliverables.md#narrative-intent-budget-aggregate-variant The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/budgets-continuity-and-deliverables.md#narrative-intent-budget-story-representation The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/budgets-continuity-and-deliverables.md#narrative-intent-deliverable-authority-gaps The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/budgets-continuity-and-deliverables.md#narrative-intent-deliverable-provenance-handoff The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/characters-relations-and-state.md#narrative-intent-character-agency-viewpoint The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/characters-relations-and-state.md#narrative-intent-character-arc-milestones The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/characters-relations-and-state.md#narrative-intent-character-goal-state The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/characters-relations-and-state.md#narrative-intent-character-group-membership The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/characters-relations-and-state.md#narrative-intent-character-presence-state The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/characters-relations-and-state.md#narrative-intent-character-state-completeness The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/design-authority-and-visual-language.md#narrative-intent-design-authority-boundary The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/design-authority-and-visual-language.md#narrative-intent-design-capability-boundary The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/design-authority-and-visual-language.md#narrative-intent-design-reference-realization The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/design-authority-and-visual-language.md#narrative-intent-design-scope-completeness The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/design-authority-and-visual-language.md#narrative-intent-design-status-unknown The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/design-authority-and-visual-language.md#narrative-intent-graphics-style-exceptions The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/design-authority-and-visual-language.md#narrative-intent-story-design-ownership The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/design-authority-and-visual-language.md#narrative-intent-visual-hierarchy-viewing The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/design-authority-and-visual-language.md#narrative-intent-visual-language-acceptance The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/design-authority-and-visual-language.md#narrative-intent-visual-language-variation The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/dialogue-language-theme-and-meaning.md#narrative-intent-dialogue-continuity The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/dialogue-language-theme-and-meaning.md#narrative-intent-dialogue-quotation-rights The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/dialogue-language-theme-and-meaning.md#narrative-intent-dialogue-voice-text-boundary The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/dialogue-language-theme-and-meaning.md#narrative-intent-motif-variation-coverage The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/dialogue-language-theme-and-meaning.md#narrative-intent-silence-nonverbal-contract The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/dialogue-language-theme-and-meaning.md#narrative-intent-subtext-theme-progression The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/dialogue-language-theme-and-meaning.md#narrative-intent-theme-source-acceptance The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/dialogue-language-theme-and-meaning.md#narrative-intent-utterance-timing-action The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/events-causality-and-time.md#narrative-intent-action-reaction-knowledge The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/events-causality-and-time.md#narrative-intent-causal-failure The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/events-causality-and-time.md#narrative-intent-setup-payoff-roles The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/fidelity-references-and-provenance.md#narrative-intent-fidelity-freshness-acceptance The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/fidelity-references-and-provenance.md#narrative-intent-reference-authority-replacement The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/fidelity-references-and-provenance.md#narrative-intent-reference-lineage The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/fidelity-references-and-provenance.md#narrative-intent-reference-rights-boundary The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/fidelity-references-and-provenance.md#narrative-intent-repaint-structural-boundary The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/fidelity-references-and-provenance.md#narrative-intent-unsupported-fidelity-continuity The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/locations-subjects-and-assets.md#narrative-intent-asset-plan-lifecycle The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/locations-subjects-and-assets.md#narrative-intent-location-anchor-traversal The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/locations-subjects-and-assets.md#narrative-intent-location-review The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/locations-subjects-and-assets.md#narrative-intent-location-scope-context The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/locations-subjects-and-assets.md#narrative-intent-location-time-build-scope The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/locations-subjects-and-assets.md#narrative-intent-subject-capability-ledger The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/locations-subjects-and-assets.md#narrative-intent-subject-source-strategy The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/scale-palette-material-and-state.md#narrative-intent-material-color-lighting-boundary The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/scale-palette-material-and-state.md#narrative-intent-material-provenance-substitution The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/scale-palette-material-and-state.md#narrative-intent-material-state-continuity The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/scale-palette-material-and-state.md#narrative-intent-palette-role-distinction The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/scale-palette-material-and-state.md#narrative-intent-repeated-scale-proportion The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/scale-palette-material-and-state.md#narrative-intent-scale-clearance-conflict The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/scale-palette-material-and-state.md#narrative-intent-scale-tier-evidence The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/scale-palette-material-and-state.md#narrative-intent-silhouette-detail-contract The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/scene-coverage-and-acceptance.md#narrative-intent-final-story-acceptance The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/scene-coverage-and-acceptance.md#narrative-intent-story-verdict-provenance The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/story-authority-and-hierarchy.md#narrative-intent-logline-premise-input The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/story-authority-and-hierarchy.md#narrative-intent-logline-promise-closure The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/story-authority-and-hierarchy.md#narrative-intent-sequence-refinement The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/story-authority-and-hierarchy.md#narrative-intent-story-fact-authority The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude specifications/narrative-and-intent/story-authority-and-hierarchy.md#narrative-intent-story-unknown-review-state The Engine consumes compiled scene and performance facts; it does not author, revise, select, approve, or preserve authority over story intent, characters, beats, themes, or narrative alternatives.
 * @evidenceExclude requirements/story/delivery-index.md#story-delivery-index The Engine evaluates already-authored typed inputs; the production language module, contract baseline and migration, contract discriminators and delivery index are generated-project authoring contracts owned by the evidence and template packages.
 * @evidenceExclude specifications/narrative-and-intent/delivery-index.md#narrative-intent-delivery-index The Engine evaluates already-authored typed inputs; the production language module, contract baseline and migration, contract discriminators and delivery index are generated-project authoring contracts owned by the evidence and template packages.
 */
export type AutoMovieEngineNarrativeEvidenceExclusions = never;
