import type { IAutoMovieHumanFaceOpticalSupportAnterior } from "./IAutoMovieHumanFaceOpticalSupportAnterior";
import type { IAutoMovieHumanFaceOpticalSupportRigid } from "./IAutoMovieHumanFaceOpticalSupportRigid";
import type { IAutoMovieHumanFaceOpticalSupportTarget } from "./IAutoMovieHumanFaceOpticalSupportTarget";

/**
 * Producer-qualified authoring support for one native connected-basis eye.
 *
 * The source producer supplies the actual native surface correspondence,
 * attachment and oriented anterior chart. Neutral rows are exact witnesses of
 * the resident domain, not raw MakeHuman control IDs. An asset hash identifies
 * provenance; it does not alone certify anatomy or contact. Target witnesses
 * enroll only source movements actually regenerated by that producer. Other
 * targets whose eye coordinates and rigid pivot do not change need no inferred
 * movement; a relevant nonzero target without a witness is refused.
 *
 * The anterior chart is the chosen source-axis/native-triangle intersection,
 * not a maximum-projection vertex, a measured corneal apex or a lid margin.
 * Axis and reference fix a geometric convention in the source head frame;
 * the articulation's existing centre landmark remains the rotation pivot.
 *
 * @author Samchon
 */
export interface IAutoMovieHumanFaceOpticalSupport {
  /** Explicit anatomical attachment owner, never inferred from an X coordinate. */
  owner: "leftEye" | "rightEye";

  /** Existing native source surface that contains this eye. */
  surface: string;

  /** Producer/source generation identity, independent of skin normal domains. */
  generation: string;

  /** SHA-256 identities of the licensed source inputs and qualification receipt. */
  sourceSha256: string[];

  /** Exact witness of the existing rigid owner configuration, not a second motion law. */
  rigid: IAutoMovieHumanFaceOpticalSupportRigid;

  /** Native vertex IDs of this whole eye component, in witness row order. */
  vertices: number[];

  /** Exact neutral XYZ triples aligned with vertices, in head-frame metres. */
  neutralPositions: number[];

  /**
   * Exact resident UV pairs per triangle corner, aligned with `triangles`
   * (two numbers per corner, six per triangle). Per corner because a UV seam
   * gives one native vertex several UV pairs, so a per-vertex row cannot be exact.
   */
  neutralUvs: number[];

  /** Actual oriented native source triangles of this component, before collider caps. */
  triangles: number[];

  /** Source-axis hit chart; triangle corners use native IDs and weights are (1-u-v,u,v). */
  anterior: IAutoMovieHumanFaceOpticalSupportAnterior;

  /** Chosen neutral geometric anterior axis, not a clinical optical axis. */
  axis: [number, number, number];

  /** Point on the chosen neutral source axis, in metres; neither pivot nor fitted globe centre. */
  axisOrigin: [number, number, number];

  /** Source reference direction projected perpendicular to axis to fix roll. */
  reference: [number, number, number];

  /** Regenerated nonzero source endpoint witnesses; zero-effect endpoints are checked directly. */
  targets: IAutoMovieHumanFaceOpticalSupportTarget[];
}
