import type { IAutoMovieHumanFaceOpticalSupportAnterior } from "./IAutoMovieHumanFaceOpticalSupportAnterior";
import type { IAutoMovieHumanFaceOpticalSupportRigid } from "./IAutoMovieHumanFaceOpticalSupportRigid";
import type { IAutoMovieHumanFaceOpticalSupportTarget } from "./IAutoMovieHumanFaceOpticalSupportTarget";

/**
 * Producer-qualified authoring support for one native connected-basis eye.
 *
 * The source producer supplies the actual native surface correspondence,
 * attachment and oriented anterior chart. Neutral rows are exact witnesses of
 * the resident domain, not raw MakeHuman control IDs. An asset hash identifies
 * provenance; it does not alone certify anatomy or contact. Target witnesses
 * enroll only source movements actually regenerated by that producer. Other
 * targets whose eye coordinates and rigid pivot do not change need no inferred
 * movement; a relevant nonzero target without a witness is refused.
 *
 * The anterior chart is the chosen source-axis/native-triangle intersection,
 * not a maximum-projection vertex, a measured corneal apex or a lid margin.
 * Axis and reference fix a geometric convention in the source head frame;
 * the articulation's existing centre landmark remains the rotation pivot.
 *
 * @evidence contracts/common.md#principled-implementation Records exact native coordinate, UV, incidence and target witnesses beside the producer identity so the consumer can reject stale or incompatible source data.
 * @evidence contracts/common.md#clear-and-simple-design One record binds one named side to one source surface and one chart.
 * @evidence contracts/common.md#prohibited-implementation-shortcuts No coordinate-sign side inference, raw-to-native ID copying or clinical label substitutes for correspondence.
 * @evidence contracts/common.md#meaningful-documentation Separates native witnesses, producer provenance, geometric registration and clinical claims.
 * @evidence contracts/modeling.md#spatial-conventions Neutral coordinates and endpoint displacements use the basis head-metre frame; UVs are the actual resident chart and barycentric coordinates are dimensionless.
 * @evidenceExclude contracts/modeling.md#part-identity-and-grouping The registered attachment owner names a source eye and defines no new part.
 * @evidenceExclude contracts/modeling.md#parameter-channels Source target names witness existing endpoints rather than defining controls.
 * @evidenceExclude contracts/modeling.md#emitted-geometry The optical builder owns generated geometry.
 * @evidenceExclude contracts/modeling.md#shared-boundaries The profile and contact owner define the generated outer interface.
 * @evidenceExclude contracts/modeling.md#rendered-observation The connected builder owns observation.
 * @evidenceExclude contracts/anatomy.md#anatomical-source Qualifies source authoring correspondence and carries no clinical measurement.
 * @evidenceExclude contracts/anatomy.md#permitted-range Introduces no physiological bound.
 * @evidenceExclude contracts/anatomy.md#parametric-authority The caller's seven dimensions own independent geometry; this record owns placement only.
 */
export interface IAutoMovieHumanFaceOpticalSupport {
  /** Explicit anatomical attachment owner, never inferred from an X coordinate. */
  owner: "leftEye" | "rightEye";

  /** Existing native source surface that contains this eye. */
  surface: string;

  /** Producer/source generation identity, independent of skin normal domains. */
  generation: string;

  /** SHA-256 identities of the licensed source inputs and qualification receipt. */
  sourceSha256: string[];

  /** Exact witness of the existing rigid owner configuration, not a second motion law. */
  rigid: IAutoMovieHumanFaceOpticalSupportRigid;

  /** Native vertex IDs of this whole eye component, in witness row order. */
  vertices: number[];

  /** Exact neutral XYZ triples aligned with vertices, in head-frame metres. */
  neutralPositions: number[];

  /** Exact resident UV pairs aligned with vertices. */
  neutralUvs: number[];

  /** Actual oriented native source triangles of this component, before collider caps. */
  triangles: number[];

  /** Source-axis hit chart; triangle corners use native IDs and weights are (1-u-v,u,v). */
  anterior: IAutoMovieHumanFaceOpticalSupportAnterior;

  /** Chosen neutral geometric anterior axis, not a clinical optical axis. */
  axis: [number, number, number];

  /** Point on the chosen neutral source axis, in metres; neither pivot nor fitted globe centre. */
  axisOrigin: [number, number, number];

  /** Source reference direction projected perpendicular to axis to fix roll. */
  reference: [number, number, number];

  /** Regenerated nonzero source endpoint witnesses; zero-effect endpoints are checked directly. */
  targets: IAutoMovieHumanFaceOpticalSupportTarget[];
}
