/**
 * Interface package boundaries for actors and asset representation.
 *
 * The package's lint.config.ts selects this declaration as an exclusion
 * carrier within its complete public-source population. It has no runtime
 * state and is not re-exported by the package barrel. Each declared
 * target/reason pair below owns one intentional negative relationship;
 * requirement and specification boundaries for this domain stay together.
 * Positive implementation citations remain on the actual public exports.
 * @evidenceExclude requirements/actors/facial-authoring/contract.md#actor-face-connected-basis Production schemas carry evaluated meshes; the reusable facial basis and compact control document are human-authoring inputs, not production AST types.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-connected-basis The pure production AST does not validate or evaluate sparse facial endpoints; the human builder supplies its resulting model.
 * An exclusion neither implements a feature nor approves a rendered asset.
 * Add a boundary at its semantic owner and retain native graph validation.
 *
 * @evidenceExclude requirements/actors/facial-authoring/README.md#face-requirements Portable production schemas represent already-generated meshes and rig facts; they do not define detailed facial authoring across document, editor and study review.
 * @evidenceExclude requirements/actors/facial-authoring/contract.md#actor-face-document Portable production schemas represent already-generated meshes and rig facts; they do not define the standalone human-face recipe, basis and version interpreter.
 * @evidenceExclude requirements/actors/facial-authoring/contract.md#actor-face-anatomical-components Portable production schemas represent already-generated meshes and rig facts; they do not define named craniofacial components, cavities and attached tissues.
 * @evidenceExclude requirements/actors/facial-authoring/contract.md#actor-face-skin-condition Production schemas carry resolved mesh and generic morph facts; the separate human authoring document defines rest-state facial skin and expression-driven wrinkle controls.
 * @evidenceExclude requirements/actors/facial-authoring/contract.md#actor-face-skin-colour Production schemas carry generic vertex colours but not the separate anatomical pigmentation document or paired reference-skin assembly.
 * @evidenceExclude requirements/actors/facial-authoring/contract.md#actor-face-controls-replacement Portable production schemas represent already-generated meshes and rig facts; they do not define anatomical detail overrides and side-specific part replacement.
 * @evidenceExclude requirements/actors/facial-authoring/contract.md#actor-face-expression Portable production schemas represent already-generated meshes and rig facts; they do not define observed-relative eyelid, oral, dental and gaze performance.
 * @evidenceExclude requirements/actors/facial-authoring/contract.md#actor-face-editor Portable production schemas represent already-generated meshes and rig facts; they do not define the interactive face editor, camera and file controls.
 * @evidenceExclude requirements/actors/facial-authoring/contract.md#actor-face-editor-state Portable production schemas represent already-generated meshes and rig facts; they do not define transactional face-document history and asynchronous last-valid publication.
 * @evidenceExclude requirements/actors/facial-authoring/contract.md#actor-face-export Portable production schemas represent already-generated meshes and rig facts; they do not define validated anatomical face GLTF/GLB serialization.
 * @evidenceExclude requirements/actors/facial-authoring/contract.md#actor-face-provenance Portable production schemas represent already-generated meshes and rig facts; they do not define non-executable selected-portrait facts in the face document.
 * @evidenceExclude requirements/actors/facial-authoring/contract.md#actor-face-review Portable production schemas represent already-generated meshes and rig facts; they do not define per-person source inventories, direct render inspection and likeness decisions.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/README.md#face-specifications Portable production schemas represent already-generated meshes and rig facts; they do not define the complete face construction, application and review boundary.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-document Portable production schemas represent already-generated meshes and rig facts; they do not define human-face version admission and photo-independent basis interpretation.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-components Portable production schemas represent already-generated meshes and rig facts; they do not define cranial, cervical, ocular, nasal, oral and auricular surface assembly.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-parametric-hair Production mesh types carry the generated strips; numerical scalp domains, styling fields and their document admission belong to the separate human authoring schema.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-skin-condition Pure production types do not construct facial attachment fields or perform portrait-local curved subdivision; those operations produce their resident mesh inputs.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-skin-colour Production schemas carry generic vertex colours but not the separate anatomical pigmentation document or paired reference-skin assembly.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-controls Portable production schemas represent already-generated meshes and rig facts; they do not define ordered face defaults, trait offsets, array replacement and asymmetric detail.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-attachments Portable production schemas represent already-generated meshes and rig facts; they do not define face-part cut ownership and final-surface attachment correspondence.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-expression Portable production schemas represent already-generated meshes and rig facts; they do not define the neutral/observed/current face solve and fixed optical identity.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-editor Portable production schemas represent already-generated meshes and rig facts; they do not define request-generation isolation and committed face history.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-editor-view Portable production schemas represent already-generated meshes and rig facts; they do not define DOM face controls, camera/clay state and last-valid downloads.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-export Portable production schemas represent already-generated meshes and rig facts; they do not define face-specific Float32, optical-material and GLTF serialization admission.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-provenance Portable production schemas represent already-generated meshes and rig facts; they do not define nullable portrait provenance that does not execute during face replay.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-review Portable production schemas represent already-generated meshes and rig facts; they do not define input/output review receipts, required portrait views and subjective acceptance.
 * @evidenceExclude requirements/actors/appearance-costume-and-attachments.md#actor-costume-intersection-refusal The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/appearance-costume-and-attachments.md#actor-costume-layers-variants The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/appearance-costume-and-attachments.md#actor-external-appearance-assets The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/appearance-costume-and-attachments.md#actor-rigid-soft-binding The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/body-scale-and-landmarks.md#actor-bounds-shot-scale The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/body-scale-and-landmarks.md#actor-proportion-neutral The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/body-scale-and-landmarks.md#actor-scale-validation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/inputs-selection-and-replacement.md#actor-external-rig-adoption The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/inputs-selection-and-replacement.md#actor-independent-binding-selection The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/inputs-selection-and-replacement.md#actor-input-compatibility-preview The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/inputs-selection-and-replacement.md#actor-selection-replacement-receipt The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/performance-and-story-binding.md#actor-performance-events-contacts The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/performance-and-story-binding.md#actor-performance-gap The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/performance-and-story-binding.md#actor-performance-local-clock The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/performance-and-story-binding.md#actor-performance-precedence The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/populations-and-doubles.md#actor-doubles-replacement The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/populations-and-doubles.md#actor-population-budget The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/populations-and-doubles.md#actor-population-refusal The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/populations-and-doubles.md#actor-prototype-variation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/pose-expression-and-gaze.md#actor-pose-space-authority The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/pose-expression-and-gaze.md#actor-pose-validation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/README.md#actor-요구사항 The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/representation-tiers-and-fidelity-boundary.md#actor-external-representation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/representation-tiers-and-fidelity-boundary.md#actor-fidelity-capability-separation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/representation-tiers-and-fidelity-boundary.md#actor-quality-claim-boundary The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/representation-tiers-and-fidelity-boundary.md#actor-shot-tier-selection The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/representation-tiers-and-fidelity-boundary.md#actor-tier-compatibility The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/scope-and-identity.md#actor-authored-facts The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/scope-and-identity.md#actor-character-distinction The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/scope-and-identity.md#actor-identity-representation-lifetime The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/scope-and-identity.md#actor-missing-binding The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/scope-and-identity.md#actor-open-control-vocabulary The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/scope-and-identity.md#actor-open-performer-kind The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/skeleton-rig-and-retargeting.md#actor-motion-retargeting The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/skeleton-rig-and-retargeting.md#actor-rig-refusal The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/state-and-continuity.md#actor-scene-state-handoff The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/state-and-continuity.md#actor-shot-continuity The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/state-and-continuity.md#actor-state-alternatives The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/state-and-continuity.md#actor-state-authority-provenance The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/state-and-continuity.md#actor-state-reset-refusal The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/state-and-continuity.md#actor-state-unknown-not-applicable The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/validation.md#actor-current-evidence The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/validation.md#actor-input-binding-validation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/validation.md#actor-multi-angle-review The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/validation.md#actor-numeric-geometry-validation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/validation.md#actor-purpose-validation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/validation.md#actor-validation-ceiling The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/voice-and-utterance-identity.md#actor-utterance-performance The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/voice-and-utterance-identity.md#actor-voice-casting-selection The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/voice-and-utterance-identity.md#actor-voice-continuity The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/voice-and-utterance-identity.md#actor-voice-refusal The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/actors/voice-and-utterance-identity.md#actor-voice-source-choice The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/era-and-style.md#asset-style-as-input The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/era-and-style.md#asset-style-catalogue-refusal The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/era-and-style.md#asset-style-mixing The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/era-and-style.md#asset-style-reference-role The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/external-assets.md#asset-bounded-decoder The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/external-assets.md#asset-external-conversion-receipt The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/external-assets.md#asset-external-group-composition The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/external-assets.md#asset-external-scene-graph-preservation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/external-assets.md#asset-external-secret-boundary The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/generated-assets.md#asset-generation-attempt-lineage The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/generated-assets.md#asset-generation-fixed-output The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/generated-assets.md#asset-generation-input-rights The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/generated-assets.md#asset-generation-refusal The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/generated-assets.md#asset-generation-reproducibility-boundary The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/generated-assets.md#asset-procedural-generation-distinction The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/geometry.md#asset-composable-geometry-operations The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/geometry.md#asset-degenerate-geometry-refusal The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/geometry.md#asset-geometry-dimensions The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/geometry.md#asset-geometry-topology The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/identity-and-instances.md#asset-instance-override-provenance The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/identity-and-instances.md#asset-variant-inheritance The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/materials-and-textures.md#asset-material-image-independence The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/materials-and-textures.md#asset-material-state The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/materials-and-textures.md#asset-texture-provenance The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/materials-and-textures.md#asset-user-authored-texture The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/patterns-and-procedural-composition.md#asset-deterministic-variation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/patterns-and-procedural-composition.md#asset-pattern-boundary-exception The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/patterns-and-procedural-composition.md#asset-pattern-local-stability The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/patterns-and-procedural-composition.md#asset-physical-module The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/patterns-and-procedural-composition.md#asset-procedural-rule The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/README.md#자산-저작-요구사항 The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/representations-bounds-and-lod.md#asset-bounds-state-motion The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/representations-bounds-and-lod.md#asset-lod-proxy-lineage The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/representations-bounds-and-lod.md#asset-lod-transition-stability The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/representations-bounds-and-lod.md#asset-representation-selection The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/representations-bounds-and-lod.md#asset-representation-semantic-preservation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/representations-bounds-and-lod.md#asset-representation-stale-refusal The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/rig-and-state.md#asset-deformable-surface The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/rig-and-state.md#asset-general-joint-relations The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/rig-and-state.md#asset-invalid-rig-refusal The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/rig-and-state.md#asset-motion-retargeting The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/validation.md#asset-external-generated-validation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/validation.md#asset-geometry-validation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/validation.md#asset-purpose-validation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/validation.md#asset-representation-bounds-validation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/validation.md#asset-rig-validation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/validation.md#asset-surface-validation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/asset-authoring/validation.md#asset-validation-gap The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/adoption-modes-and-composition.md#external-adoption-direct-placement The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/adoption-modes-and-composition.md#external-adoption-group-composition The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/adoption-modes-and-composition.md#external-adoption-intent-persistence The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/adoption-modes-and-composition.md#external-adoption-native-reinterpretation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/adoption-modes-and-composition.md#external-adoption-selection-overrides The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/conversion-receipts-and-determinism.md#external-conversion-receipt-freshness The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/conversion-receipts-and-determinism.md#external-generation-reproducibility-boundary The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/credentials-rights-and-provenance.md#external-credential-separation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/credentials-rights-and-provenance.md#external-provenance-acquisition-activity The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/credentials-rights-and-provenance.md#external-provenance-derivation-consumers The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/credentials-rights-and-provenance.md#external-provenance-sensitive-data The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/credentials-rights-and-provenance.md#external-provenance-source-record The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/identity-coordinates-and-units.md#external-identity-collision-ambiguity The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/identity-coordinates-and-units.md#external-identity-content-provenance The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/identity-coordinates-and-units.md#external-identity-elements-dependencies The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/identity-coordinates-and-units.md#external-identity-source-revision The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/identity-coordinates-and-units.md#external-identity-time-units The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/identity-coordinates-and-units.md#external-identity-value-interpretation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/media-families-and-declared-facts.md#external-media-audio The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/media-families-and-declared-facts.md#external-media-extensible-families The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/media-families-and-declared-facts.md#external-media-gltf-glb The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/media-families-and-declared-facts.md#external-media-image-video The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/media-families-and-declared-facts.md#external-media-motion The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/media-families-and-declared-facts.md#external-media-spatial-data The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/media-families-and-declared-facts.md#external-media-text-metadata The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/README.md#외부-입력-요구사항 The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/refresh-version-pinning-and-offline.md#external-cache-identity-trust The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/refresh-version-pinning-and-offline.md#external-cache-miss-unavailable-source The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/refresh-version-pinning-and-offline.md#external-explicit-refresh The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/refresh-version-pinning-and-offline.md#external-offline-ready-inputs The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/refresh-version-pinning-and-offline.md#external-provider-tool-version-pinning The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/refresh-version-pinning-and-offline.md#external-refresh-impact-staleness The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/resource-closure-and-acquisition.md#external-resource-archive-bounds The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/resource-closure-and-acquisition.md#external-resource-location-boundary The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/resource-closure-and-acquisition.md#external-resource-media-dependencies The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/resource-closure-and-acquisition.md#external-resource-network-dependency The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/resource-closure-and-acquisition.md#external-resource-original-bytes The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/source-selection-and-provider-neutrality.md#external-source-authority-boundary The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/source-selection-and-provider-neutrality.md#external-source-channel-parity The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/source-selection-and-provider-neutrality.md#external-source-provider-neutrality The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/source-selection-and-provider-neutrality.md#external-source-transfer-authority The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/unsupported-and-degradation.md#external-fidelity-semantic-boundary The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/unsupported-and-degradation.md#external-partial-adoption-boundary The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/unsupported-and-degradation.md#external-placeholder-final-boundary The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/unsupported-and-degradation.md#external-support-regression-compatibility The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/unsupported-and-degradation.md#external-unsupported-format-feature The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/unsupported-and-degradation.md#external-unsupported-hard-failure The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/unsupported-and-degradation.md#external-user-chosen-degradation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/validation-and-quarantine.md#external-validation-active-content The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/validation-and-quarantine.md#external-validation-adoption-gate The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/validation-and-quarantine.md#external-validation-content-facts The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/validation-and-quarantine.md#external-validation-quarantine-handling The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/validation-and-quarantine.md#external-validation-result-states The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/external-inputs/validation-and-quarantine.md#external-validation-structure-semantics The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/alternatives-instances-and-groups.md#asset-spec-alternative-failure-compatibility The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/alternatives-instances-and-groups.md#asset-spec-alternative-selection-output The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/alternatives-instances-and-groups.md#asset-spec-deterministic-instance-generation The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/alternatives-instances-and-groups.md#asset-spec-instance-override-resolution The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/alternatives-instances-and-groups.md#asset-spec-variant-inheritance The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/bounds-proxies-and-lod.md#asset-spec-bounds-lod-failures The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/bounds-proxies-and-lod.md#asset-spec-dynamic-bounds-invariants The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/bounds-proxies-and-lod.md#asset-spec-lod-output-costs The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/bounds-proxies-and-lod.md#asset-spec-lod-selection-policy The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/bounds-proxies-and-lod.md#asset-spec-lod-transition-invariants The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/bounds-proxies-and-lod.md#asset-spec-proxy-purpose-lineage The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/fidelity-and-validation.md#asset-spec-validation-compatibility-ceiling The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/fidelity-and-validation.md#asset-spec-validation-current-evidence The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/fidelity-and-validation.md#asset-spec-validation-motion-transitions The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/fidelity-and-validation.md#asset-spec-validation-numeric-structure The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/fidelity-and-validation.md#asset-spec-validation-purpose-inputs The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/fidelity-and-validation.md#asset-spec-validation-status-failures The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/fidelity-and-validation.md#asset-spec-validation-surface-visual The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-generation-adoption-failures The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-generation-attempt-identity The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-generation-credential-boundary The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-generation-reproducibility The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-repaint-derivation-validation The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-repaint-manual-routing The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/identity-resources-and-lifecycle.md#asset-spec-identity-inputs The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/identity-resources-and-lifecycle.md#asset-spec-lifecycle-states The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/identity-resources-and-lifecycle.md#asset-spec-model-resource-separation The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/identity-resources-and-lifecycle.md#asset-spec-source-revision-content The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/model-geometry-and-surface-facts.md#asset-spec-era-style-inputs The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/model-geometry-and-surface-facts.md#asset-spec-geometry-operations-topology The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/model-geometry-and-surface-facts.md#asset-spec-model-output-failures The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/model-geometry-and-surface-facts.md#asset-spec-procedural-pattern-inputs The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/model-geometry-and-surface-facts.md#asset-spec-surface-states-substitution The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/README.md#자산과-표현-시스템-사양 The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/rig-deformation-and-state.md#asset-spec-joint-control-invariants The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/rig-deformation-and-state.md#asset-spec-retarget-compatibility The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/rig-deformation-and-state.md#asset-spec-rig-output-failures The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/asset-and-representation/rig-deformation-and-state.md#asset-spec-skin-morph-facts The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/adoption-decisions-and-composition.md#interchange-adoption-intent-replay The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/adoption-decisions-and-composition.md#interchange-direct-placement-boundary The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/adoption-decisions-and-composition.md#interchange-group-composition-boundary The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/adoption-decisions-and-composition.md#interchange-native-reinterpretation-boundary The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/conversion-receipts-and-determinism.md#interchange-nondeterministic-generation-boundary The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/conversion-receipts-and-determinism.md#interchange-receipt-freshness-diff The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/identity-coordinates-and-units.md#interchange-content-provenance-identity The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/identity-coordinates-and-units.md#interchange-element-dependency-identity The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/identity-coordinates-and-units.md#interchange-identity-ambiguity-refusal The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/identity-coordinates-and-units.md#interchange-source-revision-identity The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/identity-coordinates-and-units.md#interchange-time-sample-mapping The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/identity-coordinates-and-units.md#interchange-value-interpretation-layer The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/intake-authority-and-routing.md#interchange-channel-independent-revision The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/intake-authority-and-routing.md#interchange-outbound-transfer-authorization The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/intake-authority-and-routing.md#interchange-provider-neutral-dispatch The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/intake-authority-and-routing.md#interchange-source-authority-separation The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/media-inspection-boundaries.md#interchange-audio-inspection The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/media-inspection-boundaries.md#interchange-design-drawing-inspection The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/media-inspection-boundaries.md#interchange-extensible-media-profile The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/media-inspection-boundaries.md#interchange-image-video-inspection The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/media-inspection-boundaries.md#interchange-spatial-data-inspection The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/media-inspection-boundaries.md#interchange-text-metadata-inspection The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/provenance-rights-and-secrets.md#interchange-derivation-consumer-reachability The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/provenance-rights-and-secrets.md#interchange-generated-acquisition-snapshot The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/provenance-rights-and-secrets.md#interchange-secret-reference-boundary The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/provenance-rights-and-secrets.md#interchange-sensitive-metadata-projection The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/provenance-rights-and-secrets.md#interchange-source-provenance-snapshot The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/README.md#interchange와-adoption-시스템-계약 The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/resource-closure-and-acquisition.md#interchange-expanded-resource-budget The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/resource-closure-and-acquisition.md#interchange-live-network-dependency-state The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/resource-closure-and-acquisition.md#interchange-locator-redirect-fence The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/resource-closure-and-acquisition.md#interchange-media-dependency-extraction The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/resource-closure-and-acquisition.md#interchange-original-byte-preservation The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/revision-refresh-and-offline-cache.md#interchange-cache-entry-identity The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/revision-refresh-and-offline-cache.md#interchange-external-version-snapshot The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/revision-refresh-and-offline-cache.md#interchange-offline-miss-state The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/revision-refresh-and-offline-cache.md#interchange-offline-ready-closure The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/revision-refresh-and-offline-cache.md#interchange-refresh-staleness-propagation The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/revision-refresh-and-offline-cache.md#interchange-refresh-transaction The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/support-degradation-and-refusal.md#interchange-appearance-semantics-fence The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/support-degradation-and-refusal.md#interchange-compatibility-migration-gate The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/support-degradation-and-refusal.md#interchange-explicit-degradation-policy The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/support-degradation-and-refusal.md#interchange-external-hard-refusal The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/support-degradation-and-refusal.md#interchange-format-feature-support-matrix The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/support-degradation-and-refusal.md#interchange-hard-refusal-predicate The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/support-degradation-and-refusal.md#interchange-partial-adoption-closure The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/support-degradation-and-refusal.md#interchange-placeholder-status-fence The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/validation-and-quarantine.md#interchange-active-content-isolation The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/validation-and-quarantine.md#interchange-atomic-adoption-gate The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/validation-and-quarantine.md#interchange-declared-observed-comparison The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/validation-and-quarantine.md#interchange-layered-validation The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/validation-and-quarantine.md#interchange-quarantine-exposure-removal The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/interchange-and-adoption/validation-and-quarantine.md#interchange-validation-result-envelope The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 */
export type AutoMovieInterfaceEvidenceExclusions = never;
