/** One owned Node session, retired when its event transport closes. @author Samchon */
export interface IHumanViewerNumericalOpened {
  type: "opened";

  /** Opaque correlation token generated by this loopback host. */
  session: string;
}
