import {
  closestPointsBetweenSegments,
  segmentSegmentDistance,
} from "@automovie/engine";
import { TestValidator } from "@nestia/e2e";

import { nclose, throwsError, vclose } from "../internal/predicates";

/**
 * Bounded segment minima retain their metric meaning across scale and parallel
 * limits. Symmetric constructions supply independent midpoint/gap oracles.
 *
 * Scenarios:
 * 1. Orthogonal and nearly parallel skew pairs retain interior minima at
 *    microscopic, ordinary and large scales; winding and pair swaps agree.
 * 2. Parallel overlap, endpoint contact and separated intervals are total,
 *    including a stationary line with zero residual variation or no domain.
 * 3. Float32-represented endpoints retain their own known separation.
 * 4. Exact points and owned witnesses preserve inputs; invalid coordinates,
 *    overflowing differences and underflowed nonzero ranks refuse and recover.
 * 5. Finite component differences whose norm overflows refuse explicitly.
 * 6. Eberly's independent near-parallel examples retain the published zero
 *    gap and endpoint minimum rather than cancelling a determinant division.
 * 7. A rigid axis permutation and translation preserve a known skew minimum.
 */
export const test_math_segment_conditioning = (): void => {
  for (const scale of [1e-200, 1e-100, 1e-6, 1e-3, 1, 1e100, 1e200]) {
    const a = { x: -scale, y: 0, z: 0 };
    const b = { x: scale, y: 0, z: 0 };
    for (const slope of [1, 1e-2, 1e-8, 1e-12, 1e-100]) {
      const gap = scale / 4;
      const c = { x: -scale, y: -scale * slope, z: gap };
      const d = { x: scale, y: scale * slope, z: gap };
      for (const [p, q, r, s] of [
        [a, b, c, d],
        [b, a, c, d],
        [c, d, a, b],
      ]) {
        const one = closestPointsBetweenSegments(p, q, r, s);
        TestValidator.predicate(
          `symmetric interior gap at ${scale}/${slope}`,
          nclose(one.distance, gap, gap * 1e-10) &&
            nclose(segmentSegmentDistance(p, q, r, s), gap, gap * 1e-10),
        );
      }
    }
  }
  const v = (x: number, y = 0, z = 0) => ({ x, y, z });
  const rigid = (point: ReturnType<typeof v>) =>
    v(point.z + 8, point.x - 4, point.y + 2);
  const transformed = closestPointsBetweenSegments(
    rigid(v(-1)),
    rigid(v(1)),
    rigid(v(-1, -1e-8, 0.25)),
    rigid(v(1, 1e-8, 0.25)),
  );
  TestValidator.predicate(
    "rigid-frame skew midpoint oracle",
    nclose(transformed.distance, 0.25, 1e-12) &&
      vclose(transformed.pointA, rigid(v(0)), 1e-7) &&
      vclose(transformed.pointB, rigid(v(0, 0, 0.25)), 1e-7),
  );
  // Eberly, Robust Computation of Distance Between Line Segments, section 3.3.
  // These expected distances are the paper's independent rational-arithmetic
  // results, not results generated by the production kernel.
  TestValidator.predicate(
    "primary near-parallel interior crossing",
    nclose(
      closestPointsBetweenSegments(
        v(-1.0264718499965966, 9.6163341007195407e-7),
        v(0.91950808032415809, -1.0094441192690283e-6),
        v(-1.062944738380611, 9.2709540082141753e-7),
        v(1.0811583868227901, -1.0670017179567367e-6),
      ).distance,
      0,
      1e-12,
    ),
  );
  TestValidator.predicate(
    "primary near-parallel endpoint minimum",
    nclose(
      closestPointsBetweenSegments(
        v(-1.0896217473782599, 9.7236145595088601e-7),
        v(0.91220578597858548, -9.4369829432107506e-7),
        v(-0.90010447502136237, 9.0671446351334441e-7),
        v(1.073087717872113, -9.818578763399274e-7),
      ).distance,
      1.1575046138574105e-7,
      1e-12,
    ),
  );
  for (const [a, b, c, d, expected] of [
    [v(0), v(2), v(1, 1), v(3, 1), 1],
    [v(0), v(1), v(1), v(2), 0],
    [v(0), v(1), v(2), v(3), 1],
    [v(0), v(0), v(0), v(0), 0],
    [v(0), v(0), v(0, 2), v(0, 2), 2],
    [v(0), v(2), v(1, 1), v(1, 1), 1],
    [v(1, 1), v(1, 1), v(0), v(2), 1],
  ] as const) {
    TestValidator.predicate(
      "independent parallel/endpoint/point gap",
      nclose(
        closestPointsBetweenSegments(a, b, c, d).distance,
        expected,
        1e-12,
      ),
    );
  }
  const represented = (point: ReturnType<typeof v>) => {
    const xyz = new Float32Array([point.x, point.y, point.z]);
    return v(xyz[0], xyz[1], xyz[2]);
  };
  const gap = new Float32Array([1e-6])[0];
  const one = closestPointsBetweenSegments(
    represented(v(-5e-6)),
    represented(v(5e-6)),
    represented(v(0, -5e-6, 1e-6)),
    represented(v(0, 5e-6, 1e-6)),
  );
  TestValidator.predicate(
    "represented Float32 interior witnesses",
    nclose(one.distance, gap, 1e-15) &&
      vclose(one.pointA, v(0), 1e-15) &&
      vclose(one.pointB, v(0, 0, gap), 1e-15),
  );
  const origin = Object.freeze(v(0));
  const result = closestPointsBetweenSegments(origin, origin, origin, origin);
  result.pointA.x = 7;
  result.pointB.y = 8;
  TestValidator.predicate(
    "collapsed witnesses are independently owned",
    origin.x === 0 &&
      origin.y === 0 &&
      closestPointsBetweenSegments(origin, origin, origin, origin).distance ===
        0,
  );
  for (const invalid of [NaN, Infinity])
    TestValidator.predicate(
      "nonfinite coordinates refuse",
      throwsError(
        () => closestPointsBetweenSegments(v(invalid), v(0), v(0), v(1)),
        "finite",
      ),
    );
  TestValidator.predicate(
    "overflowing differences refuse",
    throwsError(
      () => closestPointsBetweenSegments(v(-1e308), v(1e308), v(0), v(0)),
      "finite",
    ),
  );
  TestValidator.predicate(
    "nonzero first scaled span cannot collapse",
    throwsError(
      () => closestPointsBetweenSegments(v(0), v(1e-200), v(1), v(2)),
      "nonzero scaled span",
    ),
  );
  TestValidator.predicate(
    "nonzero second scaled span cannot collapse",
    throwsError(
      () => closestPointsBetweenSegments(v(1), v(2), v(0), v(1e-200)),
      "nonzero scaled span",
    ),
  );
  TestValidator.predicate(
    "finite components with unrepresentable norm refuse",
    throwsError(
      () =>
        closestPointsBetweenSegments(
          v(8e307, 8e307, 8e307),
          v(8e307, 8e307, 8e307),
          v(-8e307, -8e307, -8e307),
          v(-8e307, -8e307, -8e307),
        ),
      "witness distance",
    ),
  );
  TestValidator.predicate(
    "adjacent representable finite norm remains admitted",
    nclose(
      closestPointsBetweenSegments(
        v(5e307, 5e307, 5e307),
        v(5e307, 5e307, 5e307),
        v(-5e307, -5e307, -5e307),
        v(-5e307, -5e307, -5e307),
      ).distance,
      Math.sqrt(3) * 1e308,
      1e294,
    ),
  );
  TestValidator.predicate(
    "tiny positive first squared rank remains admitted",
    closestPointsBetweenSegments(v(0), v(1e-160), v(1), v(2)).distance === 1,
  );
  TestValidator.predicate(
    "tiny positive second squared rank remains admitted",
    closestPointsBetweenSegments(v(1), v(2), v(0), v(1e-160)).distance === 1,
  );
  TestValidator.predicate(
    "valid pair recovers after refusals",
    closestPointsBetweenSegments(v(0), v(1), v(0, 1), v(1, 1)).distance === 1,
  );
};
