/**
 * Package-local ledger for contract units the production library does not
 * implement.
 *
 * The production library compiles authored source into a film, keeps the
 * tracked project store, plans and verifies renders, probes delivered media and
 * inspects design references. It does not solve simulations, mix sound, drive
 * capture surfaces, inspect external model formats, build the generated
 * project's evidence graph, or make the human, rights and destination-profile
 * decisions the contracts reserve for people. Each exclusion below names the
 * narrower boundary that leaves a unit with another package, the generated
 * project's own commands, or a person, while the concrete production units keep
 * their positive citations.
 *
 * @evidence requirements/evidence-and-provenance/completeness-freshness-and-refusal.md#evidence-honest-refusal Keeps the units this package does not implement explicit instead of presenting them as production implementations.
 * @evidence specifications/evidence-and-provenance/completeness-freshness-and-refusal.md#evp-fail-closed-decision-gate Makes the package evidence graph refuse a positive verdict for a unit no production export truthfully answers.
 * @evidenceExclude requirements/agent-authoring/partial-work.md#agent-partial-result-control Adopting, revising or discarding a partial result is the author's decision in the generated project's tracked source; production returns typed results and never adopts a checkpoint on the user's behalf.
 * @evidenceExclude requirements/agent-authoring/source-owned-loop.md#agent-reviewable-source-change A change stays reviewable as the generated project's source diff and version history; production consumes reviewed source revisions through the compiler's input fingerprint and authors no change itself.
 * @evidenceExclude requirements/delivery-and-accessibility/audio-streams-and-channels.md#delivery-audio-mix-versions The blocking prototype delivers one display-referred master, one guide stem set and one caption sidecar; this unit names a delivery product the prototype does not produce.
 * @evidenceExclude requirements/delivery-and-accessibility/audio-streams-and-channels.md#delivery-loudness-profile This unit describes a human decision, an operator policy or a destination profile the blocking prototype does not model; production records the typed facts a person decides from and never decides for them.
 * @evidenceExclude requirements/delivery-and-accessibility/captions-subtitles-and-cues.md#delivery-caption-coverage Classifying required dialogue and sound events as covered, omitted or unresolved against the cue set is a review judgment the prototype does not compute.
 * @evidenceExclude requirements/delivery-and-accessibility/captions-subtitles-and-cues.md#delivery-caption-style-region Caption styling, safe region and vertical writing are not authored or rendered by the prototype's WebVTT sidecar.
 * @evidenceExclude requirements/delivery-and-accessibility/captions-subtitles-and-cues.md#delivery-caption-subtitle-distinction The prototype's caption cues carry one role each with a language and an optional speaker; translation subtitles, non-speech descriptions, song and chapter cues as separate tracks are not products of this compiler.
 * @evidenceExclude requirements/effects-and-simulation/clock-seek-and-determinism.md#effects-dependency-order The production package materializes and samples authored effects on the film clock; the solver's tier, order, fidelity ceiling and external-result adoption are the engine effect implementation.
 * @evidenceExclude requirements/effects-and-simulation/scope-and-simulation-tiers.md#effects-external-provider-neutrality The production package materializes and samples authored effects on the film clock; the solver's tier, order, fidelity ceiling and external-result adoption are the engine effect implementation.
 * @evidenceExclude requirements/effects-and-simulation/scope-and-simulation-tiers.md#effects-prototype-fidelity-boundary The production package materializes and samples authored effects on the film clock; the solver's tier, order, fidelity ceiling and external-result adoption are the engine effect implementation.
 * @evidenceExclude requirements/effects-and-simulation/scope-and-simulation-tiers.md#effects-simulation-tier The production package materializes and samples authored effects on the film clock; the solver's tier, order, fidelity ceiling and external-result adoption are the engine effect implementation.
 * @evidenceExclude requirements/evidence-and-provenance/completeness-freshness-and-refusal.md#evidence-partial-results-and-aggregation Aggregating outcomes, partial scopes and approvals across activities is the evidence layer's contract; production returns each check's own typed state and never folds them.
 * @evidenceExclude requirements/evidence-and-provenance/privacy-credentials-and-disclosure.md#privacy-erasure-and-lineage The project store's erase audit is a revision-guarded removal record for concurrency, not a privacy-basis tombstone with disposal scope and backup coverage.
 * @evidenceExclude requirements/evidence-and-provenance/privacy-credentials-and-disclosure.md#privacy-external-service-disclosure Disclosure and consent before a provider transfer belong to the generated project's repaint configuration; production executes only a request the project already selected.
 * @evidenceExclude requirements/evidence-and-provenance/privacy-credentials-and-disclosure.md#privacy-human-identity-and-pseudonym This unit describes a human decision, an operator policy or a destination profile the blocking prototype does not model; production records the typed facts a person decides from and never decides for them.
 * @evidenceExclude requirements/evidence-and-provenance/privacy-credentials-and-disclosure.md#privacy-redaction-and-source-relation This unit describes a human decision, an operator policy or a destination profile the blocking prototype does not model; production records the typed facts a person decides from and never decides for them.
 * @evidenceExclude requirements/evidence-and-provenance/privacy-credentials-and-disclosure.md#privacy-sensitive-metadata Production writes host and process identity only into private coordination locks under the user's home and publishes no public view; metadata redaction for publication is not a product of this package.
 * @evidenceExclude requirements/external-inputs/credentials-rights-and-provenance.md#external-provenance-sensitive-data This unit describes a human decision, an operator policy or a destination profile the blocking prototype does not model; production records the typed facts a person decides from and never decides for them.
 * @evidenceExclude requirements/external-inputs/credentials-rights-and-provenance.md#external-rights-license-conditions This unit describes a human decision, an operator policy or a destination profile the blocking prototype does not model; production records the typed facts a person decides from and never decides for them.
 * @evidenceExclude requirements/external-inputs/media-families-and-declared-facts.md#external-media-extensible-families External model, motion, spatial and profile inspection is the ingest package's inspector; production adopts its result and inspects only design-reference containers and text records itself.
 * @evidenceExclude requirements/external-inputs/media-families-and-declared-facts.md#external-media-gltf-glb External model, motion, spatial and profile inspection is the ingest package's inspector; production adopts its result and inspects only design-reference containers and text records itself.
 * @evidenceExclude requirements/external-inputs/media-families-and-declared-facts.md#external-media-motion External model, motion, spatial and profile inspection is the ingest package's inspector; production adopts its result and inspects only design-reference containers and text records itself.
 * @evidenceExclude requirements/external-inputs/media-families-and-declared-facts.md#external-media-spatial-data External model, motion, spatial and profile inspection is the ingest package's inspector; production adopts its result and inspects only design-reference containers and text records itself.
 * @evidenceExclude requirements/external-inputs/validation-and-quarantine.md#external-validation-quarantine-handling Exposure and removal of quarantined external inputs are the generated project's import lane; production's render cleanup quarantine is an artifact-retention mechanism cited under retention.
 * @evidenceExclude requirements/operations-and-recovery/retention-and-cleanup.md#operations-sensitive-data-minimization Production stores no secret material; a separate retention policy for secrets is not a render artifact class this planner classifies.
 * @evidenceExclude requirements/production-evidence/graph.md#agent-production-evidence-additive-extension The generated production graph's shared inventory, discovery, integrity, additive extension and determinism are built by the evidence package factory; production consumes only its shape-stage result.
 * @evidenceExclude requirements/production-evidence/graph.md#agent-production-evidence-deterministic-result The generated production graph's shared inventory, discovery, integrity, additive extension and determinism are built by the evidence package factory; production consumes only its shape-stage result.
 * @evidenceExclude requirements/production-evidence/graph.md#agent-production-evidence-discovery The generated production graph's shared inventory, discovery, integrity, additive extension and determinism are built by the evidence package factory; production consumes only its shape-stage result.
 * @evidenceExclude requirements/production-evidence/graph.md#agent-production-evidence-physical-integrity The generated production graph's shared inventory, discovery, integrity, additive extension and determinism are built by the evidence package factory; production consumes only its shape-stage result.
 * @evidenceExclude requirements/production-evidence/graph.md#agent-production-evidence-shared-contract The generated production graph's shared inventory, discovery, integrity, additive extension and determinism are built by the evidence package factory; production consumes only its shape-stage result.
 * @evidenceExclude requirements/rendering/frame-schedules-and-sampling.md#rendering-shutter-samples The prototype samples one instant per frame and claims no motion blur, so no shutter schedule exists to declare.
 * @evidenceExclude requirements/rendering/headless-and-platform-determinism.md#rendering-hardware-variation The generated project's render commands own worker processes, capture surfaces, GC apply results and their operator-facing recovery; production plans, verifies and adjudicates the artifacts those commands produce.
 * @evidenceExclude requirements/rendering/headless-and-platform-determinism.md#rendering-headless-refusal The generated project's render commands own worker processes, capture surfaces, GC apply results and their operator-facing recovery; production plans, verifies and adjudicates the artifacts those commands produce.
 * @evidenceExclude requirements/rendering/headless-and-platform-determinism.md#rendering-process-isolation The generated project's render commands own worker processes, capture surfaces, GC apply results and their operator-facing recovery; production plans, verifies and adjudicates the artifacts those commands produce.
 * @evidenceExclude requirements/sound/sources-and-external-assets.md#sound-source-choice This unit describes a human decision, an operator policy or a destination profile the blocking prototype does not model; production records the typed facts a person decides from and never decides for them.
 * @evidenceExclude requirements/sound/validation-and-delivery.md#sound-audible-review This unit describes a human decision, an operator policy or a destination profile the blocking prototype does not model; production records the typed facts a person decides from and never decides for them.
 * @evidenceExclude requirements/sound/validation-and-delivery.md#sound-budget-evidence Per-tier audio budget accounting is not computed by the prototype; the render plan records sample facts without a cost bound.
 * @evidenceExclude requirements/sound/validation-and-delivery.md#sound-numeric-verification Hand-computed fixture verification and negative twins are the repository test corpus and review procedure, not a runtime export of this package.
 * @evidenceExclude requirements/sound/validation-and-delivery.md#sound-seek-chunk-equivalence The production package plans cue sample ranges and delivers the mixed master; the mixer, stems, automation, loudness and lip-sync contracts are the engine sound implementation.
 * @evidenceExclude specifications/authoring-and-authority/partial-targets-and-atomic-results.md#spec-authoring-partial-result-checkpoint Adopting, revising or discarding a checkpoint is the author's decision in the generated project's tracked source; production returns typed results and never adopts one on the user's behalf.
 * @evidenceExclude specifications/authoring-and-authority/partial-targets-and-atomic-results.md#spec-authoring-partial-work-state The compiler records omissions and diagnostics; the six-state partial-target ledger is the generated project's authoring state.
 * @evidenceExclude specifications/authoring-and-authority/prototype-determinism-and-fidelity.md#spec-authoring-prototype-exclusion-compatibility Reopening a product exclusion is a contract-version decision recorded in the interface package's contract JSDoc, not a runtime behavior of the production library.
 * @evidenceExclude specifications/editorial-render-and-delivery/delivery-audio-text-and-localization.md#spec-delivery-description-alternatives The blocking prototype delivers one display-referred master, one guide stem set and one caption sidecar; this unit names a delivery product the prototype does not produce.
 * @evidenceExclude specifications/editorial-render-and-delivery/delivery-audio-text-and-localization.md#spec-delivery-localization Language-version closure, translation lineage and approval are not products of the prototype; production implements only the RFC 5646 cue identity cited under the caption units.
 * @evidenceExclude specifications/editorial-render-and-delivery/delivery-profiles-time-and-picture.md#spec-delivery-profile-matrix The prototype has fixed final and proxy tiers; a destination constraint matrix with required, optional and intentionally absent items is not modeled.
 * @evidenceExclude specifications/editorial-render-and-delivery/render-schedule-state-and-headless.md#spec-render-state-isolation The generated project's render commands own worker processes, capture surfaces, GC apply results and their operator-facing recovery; production plans, verifies and adjudicates the artifacts those commands produce.
 * @evidenceExclude specifications/evidence-and-provenance/completeness-freshness-and-refusal.md#evp-outcome-classification-lattice Aggregating outcomes, partial scopes and approvals across activities is the evidence layer's contract; production returns each check's own typed state and never folds them.
 * @evidenceExclude specifications/evidence-and-provenance/completeness-freshness-and-refusal.md#evp-partial-aggregation Aggregating outcomes, partial scopes and approvals across activities is the evidence layer's contract; production returns each check's own typed state and never folds them.
 * @evidenceExclude specifications/evidence-and-provenance/privacy-credentials-and-disclosure.md#evp-erasure-tombstone The project store's erase audit is a revision-guarded removal record for concurrency, not a privacy-basis tombstone with disposal scope and backup coverage.
 * @evidenceExclude specifications/evidence-and-provenance/privacy-credentials-and-disclosure.md#evp-external-transfer-authorization Transfer authorization and consent belong to the generated project's repaint configuration; production executes only a request the project already selected.
 * @evidenceExclude specifications/evidence-and-provenance/privacy-credentials-and-disclosure.md#evp-human-identity-pseudonymization This unit describes a human decision, an operator policy or a destination profile the blocking prototype does not model; production records the typed facts a person decides from and never decides for them.
 * @evidenceExclude specifications/evidence-and-provenance/privacy-credentials-and-disclosure.md#evp-redaction-derivative This unit describes a human decision, an operator policy or a destination profile the blocking prototype does not model; production records the typed facts a person decides from and never decides for them.
 * @evidenceExclude specifications/evidence-and-provenance/privacy-credentials-and-disclosure.md#evp-sensitive-metadata-filtering This unit describes a human decision, an operator policy or a destination profile the blocking prototype does not model; production records the typed facts a person decides from and never decides for them.
 * @evidenceExclude specifications/execution-and-recovery/artifacts-and-atomic-publication.md#execution-artifact-ownership-completeness The five-axis artifact snapshot is the validation session's record; production reports chunk states and publication identity through its own typed statuses.
 * @evidenceExclude specifications/execution-and-recovery/artifacts-and-atomic-publication.md#execution-publication-failure-outcome Separating payload write, durable flush, readback and acknowledgement outcomes is not modeled beyond the revision-guarded write; a failed cycle writes nothing and reports its refusal.
 * @evidenceExclude specifications/execution-and-recovery/retention-cleanup-and-quarantine.md#execution-cleanup-failure-capacity The apply result with reclaimed bytes, failure set and post-cleanup capacity is produced by the generated project's render cleanup command; production plans dispositions only.
 * @evidenceExclude specifications/execution-and-recovery/retention-cleanup-and-quarantine.md#execution-retention-classes Production classifies render artifacts by their plan and publication references, not by a retention policy class ledger with durations and recoverability.
 * @evidenceExclude specifications/execution-and-recovery/retention-cleanup-and-quarantine.md#execution-sensitive-retention-minimization Production stores no secret material; a separate retention policy for secrets is not a render artifact class this planner classifies.
 * @evidenceExclude specifications/interchange-and-adoption/media-inspection-boundaries.md#interchange-extensible-media-profile External model, motion, spatial and profile inspection is the ingest package's inspector; production adopts its result and inspects only design-reference containers and text records itself.
 * @evidenceExclude specifications/interchange-and-adoption/media-inspection-boundaries.md#interchange-gltf-glb-inspection External model, motion, spatial and profile inspection is the ingest package's inspector; production adopts its result and inspects only design-reference containers and text records itself.
 * @evidenceExclude specifications/interchange-and-adoption/media-inspection-boundaries.md#interchange-motion-inspection External model, motion, spatial and profile inspection is the ingest package's inspector; production adopts its result and inspects only design-reference containers and text records itself.
 * @evidenceExclude specifications/interchange-and-adoption/media-inspection-boundaries.md#interchange-spatial-data-inspection External model, motion, spatial and profile inspection is the ingest package's inspector; production adopts its result and inspects only design-reference containers and text records itself.
 * @evidenceExclude specifications/interchange-and-adoption/provenance-rights-and-secrets.md#interchange-rights-publication-gate This unit describes a human decision, an operator policy or a destination profile the blocking prototype does not model; production records the typed facts a person decides from and never decides for them.
 * @evidenceExclude specifications/interchange-and-adoption/provenance-rights-and-secrets.md#interchange-sensitive-metadata-projection This unit describes a human decision, an operator policy or a destination profile the blocking prototype does not model; production records the typed facts a person decides from and never decides for them.
 * @evidenceExclude specifications/production-evidence/graph.md#spec-authoring-production-evidence-additive-extension The generated production graph's shared inventory, discovery, integrity, additive extension and determinism are built by the evidence package factory; production consumes only its shape-stage result.
 * @evidenceExclude specifications/production-evidence/graph.md#spec-authoring-production-evidence-deterministic-result The generated production graph's shared inventory, discovery, integrity, additive extension and determinism are built by the evidence package factory; production consumes only its shape-stage result.
 * @evidenceExclude specifications/production-evidence/graph.md#spec-authoring-production-evidence-discovery The generated production graph's shared inventory, discovery, integrity, additive extension and determinism are built by the evidence package factory; production consumes only its shape-stage result.
 * @evidenceExclude specifications/production-evidence/graph.md#spec-authoring-production-evidence-physical-integrity The generated production graph's shared inventory, discovery, integrity, additive extension and determinism are built by the evidence package factory; production consumes only its shape-stage result.
 * @evidenceExclude specifications/production-evidence/graph.md#spec-authoring-production-evidence-shared-contract The generated production graph's shared inventory, discovery, integrity, additive extension and determinism are built by the evidence package factory; production consumes only its shape-stage result.
 * @evidenceExclude specifications/simulation-effects-and-sound/clocks-ordering-seek-and-checkpoints.md#deterministic-dependency-and-contact-order The production package materializes and samples authored effects on the film clock; the solver's tier, order, fidelity ceiling and external-result adoption are the engine effect implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/clocks-ordering-seek-and-checkpoints.md#numeric-platform-repeatability-class The production package materializes and samples authored effects on the film clock; the solver's tier, order, fidelity ceiling and external-result adoption are the engine effect implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-conform-dependency-invalidation Sound is planned anew from the compiled timeline on every render plan; production keeps no incremental sound timeline to conform or invalidate.
 * @evidenceExclude specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-event-sync-and-boundary-continuity The production package plans cue sample ranges and delivers the mixed master; the mixer, stems, automation, loudness and lip-sync contracts are the engine sound implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-loudness-peak-and-mix-failure The production package plans cue sample ranges and delivers the mixed master; the mixer, stems, automation, loudness and lip-sync contracts are the engine sound implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-mix-automation-sample-clock The production package plans cue sample ranges and delivers the mixed master; the mixer, stems, automation, loudness and lip-sync contracts are the engine sound implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-processing-chain-and-stable-summation The production package plans cue sample ranges and delivers the mixed master; the mixer, stems, automation, loudness and lip-sync contracts are the engine sound implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-stem-master-relation-contract The production package plans cue sample ranges and delivers the mixed master; the mixer, stems, automation, loudness and lip-sync contracts are the engine sound implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/scope-tiers-and-identities.md#authored-silence-and-missing-state The production package plans cue sample ranges and delivers the mixed master; the mixer, stems, automation, loudness and lip-sync contracts are the engine sound implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/scope-tiers-and-identities.md#external-result-provider-neutrality The production package materializes and samples authored effects on the film clock; the solver's tier, order, fidelity ceiling and external-result adoption are the engine effect implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/scope-tiers-and-identities.md#simulation-effects-sound-common-invariants The production package materializes and samples authored effects on the film clock; the solver's tier, order, fidelity ceiling and external-result adoption are the engine effect implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/scope-tiers-and-identities.md#simulation-effects-sound-prototype-fidelity-ceiling The production package materializes and samples authored effects on the film clock; the solver's tier, order, fidelity ceiling and external-result adoption are the engine effect implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/sound-sources-events-dialogue-and-foley.md#dialogue-failure-contract The production package plans cue sample ranges and delivers the mixed master; the mixer, stems, automation, loudness and lip-sync contracts are the engine sound implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/sound-sources-events-dialogue-and-foley.md#dialogue-lipsync-join-and-seek The production package plans cue sample ranges and delivers the mixed master; the mixer, stems, automation, loudness and lip-sync contracts are the engine sound implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/sound-sources-events-dialogue-and-foley.md#dialogue-voice-consistency-and-phoneme-state Dialogue synthesis, phoneme marks and viseme derivation are the generated project's dialogue runtime and the engine's viseme join; production plans dialogue ranges.
 * @evidenceExclude specifications/simulation-effects-and-sound/sound-sources-events-dialogue-and-foley.md#foley-claim-and-failure-boundary The production package plans cue sample ranges and delivers the mixed master; the mixer, stems, automation, loudness and lip-sync contracts are the engine sound implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/sound-sources-events-dialogue-and-foley.md#foley-variation-layering-and-bound The production package plans cue sample ranges and delivers the mixed master; the mixer, stems, automation, loudness and lip-sync contracts are the engine sound implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/sound-sources-events-dialogue-and-foley.md#sound-cue-kind-and-event-timing The production package plans cue sample ranges and delivers the mixed master; the mixer, stems, automation, loudness and lip-sync contracts are the engine sound implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/validation-evidence-and-compatibility.md#effect-evidence-status-and-external-result The production package materializes and samples authored effects on the film clock; the solver's tier, order, fidelity ceiling and external-result adoption are the engine effect implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/validation-evidence-and-compatibility.md#effect-hand-math-and-negative-twins Hand-computed fixture verification and negative twins are the repository test corpus and review procedure, not a runtime export of this package.
 * @evidenceExclude specifications/simulation-effects-and-sound/validation-evidence-and-compatibility.md#effect-seek-equivalence-and-visual-review The production package materializes and samples authored effects on the film clock; the solver's tier, order, fidelity ceiling and external-result adoption are the engine effect implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/validation-evidence-and-compatibility.md#simulation-sound-compatibility-and-recovery The production package materializes and samples authored effects on the film clock; the solver's tier, order, fidelity ceiling and external-result adoption are the engine effect implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/validation-evidence-and-compatibility.md#sound-budget-and-audible-review Per-tier audio budget accounting and audible review are not computed by the prototype; the render plan records sample facts without a cost bound.
 * @evidenceExclude specifications/validation-and-diagnostics/partial-artifacts-and-refusal.md#validation-artifact-refusal-boundary The validation session's five-axis result is the generated project's verify command; production supplies the typed chunk, publication and probe facts it consumes.
 * @evidenceExclude specifications/narrative-and-intent/budgets-continuity-and-deliverables.md#narrative-intent-budget-aggregate-variant The binder preserves the selected authored inventory and does not aggregate runtime budget variants.
 * @evidenceExclude specifications/narrative-and-intent/budgets-continuity-and-deliverables.md#narrative-intent-budget-feasibility-verdict Deliverable formatting cannot decide whether a production is feasible.
 * @evidenceExclude specifications/narrative-and-intent/budgets-continuity-and-deliverables.md#narrative-intent-budget-measurement-worst-case Binding tracked Markdown performs no resource measurement or worst-case analysis.
 * @evidenceExclude specifications/narrative-and-intent/budgets-continuity-and-deliverables.md#narrative-intent-budget-story-representation A reader-edition binder does not choose story representation or budget scope.
 * @evidenceExclude specifications/review-and-acceptance/README.md#review-acceptance-document-map The documentation index organizes the contract corpus and is not a runtime obligation of this library population reader.
 */
export const AUTOMOVIE_PRODUCTION_EVIDENCE_EXCLUSIONS =
  "production-evidence-exclusions" as const;
