/**
 * @evidenceExclude requirements/agent-authoring/partial-work.md#agent-declared-omission Authored omission declarations are evaluated by the native evidence graph.
 * @evidenceExclude requirements/agent-authoring/partial-work.md#agent-partial-work-gap-distinction The native evidence graph and authoring procedure classify declared unrealized work.
 * @evidenceExclude specifications/authoring-and-authority/partial-targets-and-atomic-results.md#spec-authoring-partial-omission-failure Native evidence lint evaluates authored omission declarations.
 * @evidenceExclude requirements/effects-and-simulation/scope-and-simulation-tiers.md#effects-story-binding The engine effect validator now implements this binding.
 * @evidenceExclude specifications/review-and-acceptance/README.md#review-acceptance-system-boundary This section routes review responsibilities across the system.
 * Package-local ledger for contract units the production library does not
 * implement.
 *
 * @evidenceExclude specifications/authoring-and-authority/source-authority-and-derivation.md#spec-authoring-sandbox-physical-ownership Repository sandbox creation, package packing and installer admission belong to the build launcher, not production compilation or its artifact store.
 *
 * The production library compiles authored source into a film, keeps the
 * tracked project store, plans and verifies renders, probes delivered media and
 * inspects design references. It does not solve simulations, mix sound, drive
 * capture surfaces, inspect external model formats, build the generated
 * project's evidence graph, or make the human, rights and destination-profile
 * decisions the contracts reserve for people. Each exclusion below names the
 * narrower boundary that leaves a unit with another package, the generated
 * project's own commands, or a person, while the concrete production units keep
 * their positive citations.
 *
 * @evidenceExclude requirements/agent-authoring/partial-work.md#agent-partial-result-control Adopting, revising or discarding a partial result is the author's decision in the generated project's tracked source; production returns typed results and never adopts a checkpoint on the user's behalf.
 * @evidenceExclude requirements/agent-authoring/source-owned-loop.md#agent-reviewable-source-change A change stays reviewable as the generated project's source diff and version history; production consumes reviewed source revisions through the builder's input fingerprint and authors no change itself.
 * @evidenceExclude requirements/delivery-and-accessibility/audio-streams-and-channels.md#delivery-audio-sample-boundary The render plan fixes each cue's source sample boundary and render's Opus profile assertion verifies the delivered priming, tail and presentation boundary against the encoded bytes; production stores the plan and compares the receipt rows against it.
 * @evidenceExclude requirements/delivery-and-accessibility/audio-streams-and-channels.md#delivery-channel-layout The ordered speaker layout of a planned asset is carried by the render plan's audio asset identity, which ingest's decoder observed; production records which deliverable consumed it.
 * @evidenceExclude requirements/delivery-and-accessibility/audio-streams-and-channels.md#delivery-audio-downmix Channel reduction and rate conversion of a source asset are the ingest audio decoder's recorded processing; production carries the decoded samples and the deliverable record without remapping channels.
 * @evidenceExclude requirements/delivery-and-accessibility/audio-streams-and-channels.md#delivery-audio-mix-versions The blocking prototype delivers one display-referred master, one guide stem set and one caption sidecar; this unit names a delivery product the prototype does not produce.
 * @evidenceExclude requirements/delivery-and-accessibility/audio-streams-and-channels.md#delivery-loudness-profile This unit describes a human decision, an operator policy or a destination profile the blocking prototype does not model; production records the typed facts a person decides from and never decides for them.
 * @evidenceExclude requirements/delivery-and-accessibility/captions-subtitles-and-cues.md#delivery-caption-presentation-form The selectable WebVTT sidecar is serialized by render's caption surface from compiled placements; production verifies the delivered bytes match the plan it stored.
 * @evidenceExclude requirements/delivery-and-accessibility/captions-subtitles-and-cues.md#delivery-caption-reading-overlap Reading rate, line, duration and same-language gap measurement against a declared profile is the render caption evaluator; production binds the installed segmenter and reopens the compiled timeline it measures.
 * @evidenceExclude requirements/delivery-and-accessibility/captions-subtitles-and-cues.md#delivery-cue-text-language Caption text canonicalization, tab preservation and prohibited-control sanitization are the render caption surface; this package only refuses a cue whose canonical text is blank or whose language tag is malformed, claimed under cue refusal.
 * @evidenceExclude requirements/delivery-and-accessibility/containers-codecs-and-media-facts.md#delivery-encoding-tool-identity The encoder package, version, closure digest and argument set are fenced into the render plan's runtime identity; production persists that identity and refuses a receipt that contradicts it.
 * @evidenceExclude requirements/delivery-and-accessibility/containers-codecs-and-media-facts.md#delivery-partial-container Parsing delivered container bytes and refusing one that opens without its required stream is the render Node entry's rendered-media probe; this package routes its two JSON sidecar records and compares the probe's facts with the manifest row.
 * @evidenceExclude requirements/delivery-and-accessibility/containers-codecs-and-media-facts.md#delivery-stream-identity Identifying each track by parsed codec and role belongs to the render video probe; production consumes the probe record and never reads a track itself.
 * @evidenceExclude requirements/delivery-and-accessibility/containers-codecs-and-media-facts.md#delivery-supported-combinations The supported container, codec, raster and colour combination is the render delivery profile; production compares a manifest row with whatever that profile admitted.
 * @evidenceExclude requirements/delivery-and-accessibility/picture-color-and-image-sequences.md#delivery-multipart-channels Planning beauty and each structural pass as separate chunk products with their own identity is the render plan's partition; production tracks each product's receipt separately.
 * @evidenceExclude requirements/delivery-and-accessibility/picture-color-and-image-sequences.md#delivery-picture-derivatives Binding a proxy tier to the master frame identity and range it derives from is the render plan's tier contract; production records which tier a publication used.
 * @evidenceExclude requirements/delivery-and-accessibility/picture-color-and-image-sequences.md#delivery-picture-alpha-channels The PNG role profile that fixes channel population and alpha relation is the render delivery surface; production stores and reopens the pictures it admitted.
 * @evidenceExclude requirements/delivery-and-accessibility/picture-color-and-image-sequences.md#delivery-picture-dimensions-window Stored dimensions, pixel aspect and orientation per PNG role are declared by the render delivery profile, not by this package's publication join.
 * @evidenceExclude requirements/delivery-and-accessibility/picture-color-and-image-sequences.md#delivery-picture-refusal Refusing transformed, stretched, ambiguously timed or colour-unidentified picture bytes is the render delivery assertion; production reports the refusal it raised against the deliverable that carried those bytes.
 * @evidenceExclude requirements/delivery-and-accessibility/picture-color-and-image-sequences.md#delivery-scene-display-picture Scene-linear to display-referred conversion happens in the renderer that draws the frame; this package neither converts nor grades pixels, and it lost this acknowledgement only because the picture profile it used to host moved to render.
 * @evidenceExclude requirements/delivery-and-accessibility/captions-subtitles-and-cues.md#delivery-caption-coverage Classifying required dialogue and sound events as covered, omitted or unresolved against the cue set is a review judgment the prototype does not compute.
 * @evidenceExclude requirements/delivery-and-accessibility/captions-subtitles-and-cues.md#delivery-caption-style-region Caption styling, safe region and vertical writing are not authored or rendered by the prototype's WebVTT sidecar.
 * @evidenceExclude requirements/delivery-and-accessibility/captions-subtitles-and-cues.md#delivery-caption-subtitle-distinction The prototype's caption cues carry one role each with a language and an optional speaker; translation subtitles, non-speech descriptions, song and chapter cues as separate tracks are not products of this builder.
 * @evidenceExclude requirements/effects-and-simulation/clock-seek-and-determinism.md#effects-dependency-order The engine film effect runtime materializes and samples authored effects on the film clock together with the solver's tier, order, fidelity ceiling and external-result adoption; production persists that runtime and plans renders against it.
 * @evidenceExclude requirements/effects-and-simulation/scope-and-simulation-tiers.md#effects-external-provider-neutrality The engine film effect runtime materializes and samples authored effects on the film clock together with the solver's tier, order, fidelity ceiling and external-result adoption; production persists that runtime and plans renders against it.
 * @evidenceExclude requirements/effects-and-simulation/scope-and-simulation-tiers.md#effects-prototype-fidelity-boundary The engine film effect runtime materializes and samples authored effects on the film clock together with the solver's tier, order, fidelity ceiling and external-result adoption; production persists that runtime and plans renders against it.
 * @evidenceExclude requirements/effects-and-simulation/scope-and-simulation-tiers.md#effects-simulation-tier The engine film effect runtime materializes and samples authored effects on the film clock together with the solver's tier, order, fidelity ceiling and external-result adoption; production persists that runtime and plans renders against it.
 * @evidenceExclude requirements/effects-and-simulation/clock-seek-and-determinism.md#effects-arbitrary-seek The engine film effect runtime samples a persisted film effect at any timeline frame from its immutable stream; production persists that runtime and plans renders against it without sampling state of its own.
 * @evidenceExclude requirements/effects-and-simulation/clock-seek-and-determinism.md#effects-seek-reconstruction The engine film effect runtime reconstructs every sampled state from the stream identity and absolute frame; production stores and reopens the runtime but reconstructs no effect state.
 * @evidenceExclude requirements/effects-and-simulation/clock-seek-and-determinism.md#effects-step-boundary The engine film effect runtime samples all effects at one exact film frame boundary; production passes timeline frames to it and evaluates no emitter, anchor or environment step.
 * @evidenceExclude requirements/effects-and-simulation/clock-seek-and-determinism.md#effects-platform-determinism The engine film effect runtime fixes cue order and the canonical serialization of each stream; production writes the bytes the engine produced and owns no effect iteration order.
 * @evidenceExclude requirements/effects-and-simulation/scope-and-simulation-tiers.md#effects-authored-solved The engine film effect runtime pairs each derived sample with the authored cue stream it came from; production carries the persisted runtime without deriving effect state.
 * @evidenceExclude requirements/effects-and-simulation/scope-and-simulation-tiers.md#effects-scope-refusal The engine film effect runtime refuses a missing zone, recipe, owner or bound by named code; production surfaces those refusals from the builder and render planner without a second effect validator.
 * @evidenceExclude specifications/simulation-effects-and-sound/clocks-ordering-seek-and-checkpoints.md#effect-film-time-step-boundary The engine film effect runtime performs the exact rational frame-to-effect-clock conversion; production hands it builder timeline frames and converts no effect clock.
 * @evidenceExclude specifications/simulation-effects-and-sound/clocks-ordering-seek-and-checkpoints.md#arbitrary-seek-reconstruction-contract The engine film effect runtime reconstructs the same state for repeated and reordered seeks; production performs no effect seek.
 * @evidenceExclude specifications/simulation-effects-and-sound/clocks-ordering-seek-and-checkpoints.md#checkpoint-cache-identity-and-validity The engine film effect runtime recomputes stream and runtime digests and refuses a population whose identity differs from the current edit; production keeps no effect checkpoint or cache key of its own.
 * @evidenceExclude specifications/simulation-effects-and-sound/clocks-ordering-seek-and-checkpoints.md#clock-seek-failure-and-recovery The engine film effect runtime returns named refusals for an invalid clock, frame or stale identity; production propagates them and adds no clock recovery path.
 * @evidenceExclude specifications/simulation-effects-and-sound/scope-tiers-and-identities.md#effect-sound-story-lifecycle-identity The engine film effect runtime folds production, film, cue and edit identity into each stream; production supplies those identities from its manifest without deriving effect identity.
 * @evidenceExclude requirements/effects-and-simulation/clock-seek-and-determinism.md#effects-cache-identity The engine film effect runtime keys every stream and runtime by content digest and refuses a stale population; production folds those engine digests into render chunk identity, claimed under chunk partition, and keeps no effect cache key of its own.
 * @evidenceExclude requirements/effects-and-simulation/clock-seek-and-determinism.md#effects-film-time-mapping The engine film effect runtime maps film frames onto the effect clock; production records the full-rate timeline frame in the render schedule, claimed under the frame schedule, and converts no effect time.
 * @evidenceExclude requirements/evidence-and-provenance/completeness-freshness-and-refusal.md#evidence-partial-results-and-aggregation Aggregating outcomes, partial scopes and approvals across activities is the evidence layer's contract; production returns each check's own typed state and never folds them.
 * @evidenceExclude requirements/evidence-and-provenance/generation-transformation-and-derivation.md#provenance-transformation-record The input digest, ordered recipe and output facts of a source transformation are recorded by the ingest audio decoder; production records which plan and receipt consumed the result.
 * @evidenceExclude requirements/evidence-and-provenance/privacy-credentials-and-disclosure.md#privacy-erasure-and-lineage The project store's erase audit is a revision-guarded removal record for concurrency, not a privacy-basis tombstone with disposal scope and backup coverage.
 * @evidenceExclude requirements/evidence-and-provenance/privacy-credentials-and-disclosure.md#privacy-external-service-disclosure Disclosure and consent before a provider transfer belong to the generated project's repaint configuration; production executes only a request the project already selected.
 * @evidenceExclude requirements/evidence-and-provenance/privacy-credentials-and-disclosure.md#privacy-human-identity-and-pseudonym This unit describes a human decision, an operator policy or a destination profile the blocking prototype does not model; production records the typed facts a person decides from and never decides for them.
 * @evidenceExclude requirements/evidence-and-provenance/privacy-credentials-and-disclosure.md#privacy-redaction-and-source-relation This unit describes a human decision, an operator policy or a destination profile the blocking prototype does not model; production records the typed facts a person decides from and never decides for them.
 * @evidenceExclude requirements/evidence-and-provenance/privacy-credentials-and-disclosure.md#privacy-sensitive-metadata Production writes host and process identity only into private coordination locks under the user's home and publishes no public view; metadata redaction for publication is not a product of this package.
 * @evidenceExclude requirements/external-inputs/credentials-rights-and-provenance.md#external-provenance-sensitive-data This unit describes a human decision, an operator policy or a destination profile the blocking prototype does not model; production records the typed facts a person decides from and never decides for them.
 * @evidenceExclude requirements/external-inputs/media-families-and-declared-facts.md#external-media-audio Audio container, codec, channel layout and rate facts are read by the ingest audio decoder; production consumes its typed result and inspects no audio bytes.
 * @evidenceExclude requirements/external-inputs/media-families-and-declared-facts.md#external-media-extensible-families External model, motion, spatial and profile inspection is the ingest package's inspector; production adopts its result and inspects only design-reference containers and text records itself.
 * @evidenceExclude requirements/external-inputs/media-families-and-declared-facts.md#external-media-gltf-glb External model, motion, spatial and profile inspection is the ingest package's inspector; production adopts its result and inspects only design-reference containers and text records itself.
 * @evidenceExclude requirements/external-inputs/media-families-and-declared-facts.md#external-media-motion External model, motion, spatial and profile inspection is the ingest package's inspector; production adopts its result and inspects only design-reference containers and text records itself.
 * @evidenceExclude requirements/external-inputs/media-families-and-declared-facts.md#external-media-spatial-data External model, motion, spatial and profile inspection is the ingest package's inspector; production adopts its result and inspects only design-reference containers and text records itself.
 * @evidenceExclude requirements/external-inputs/validation-and-quarantine.md#external-validation-quarantine-handling Exposure and removal of quarantined external inputs are the generated project's import lane; production's render cleanup quarantine is an artifact-retention mechanism cited under retention.
 * @evidenceExclude requirements/external-inputs/validation-and-quarantine.md#external-validation-structure-semantics Structural and semantic validation of external media bytes is the ingest inspectors' and its audio decoder's; production validates authored records and its own project store instead.
 * @evidenceExclude requirements/operations-and-recovery/retention-and-cleanup.md#operations-sensitive-data-minimization Production stores no secret material; a separate retention policy for secrets is not a render artifact class this planner classifies.
 * @evidenceExclude requirements/production-evidence/graph.md#agent-production-evidence-additive-extension The generated production graph's shared inventory, discovery, integrity, additive extension and determinism are built by the evidence package factory; production consumes only its shape-stage result.
 * @evidenceExclude requirements/production-evidence/graph.md#agent-production-evidence-deterministic-result The generated production graph's shared inventory, discovery, integrity, additive extension and determinism are built by the evidence package factory; production consumes only its shape-stage result.
 * @evidenceExclude requirements/production-evidence/graph.md#agent-production-evidence-discovery The generated production graph's shared inventory, discovery, integrity, additive extension and determinism are built by the evidence package factory; production consumes only its shape-stage result.
 * @evidenceExclude requirements/production-evidence/graph.md#agent-production-evidence-physical-integrity The generated production graph's shared inventory, discovery, integrity, additive extension and determinism are built by the evidence package factory; production consumes only its shape-stage result.
 * @evidenceExclude requirements/production-evidence/graph.md#agent-production-evidence-shared-contract The generated production graph's shared inventory, discovery, integrity, additive extension and determinism are built by the evidence package factory; production consumes only its shape-stage result.
 * @evidenceExclude requirements/rendering/frame-schedules-and-sampling.md#rendering-frame-boundary-convention Reading start-inclusive, end-exclusive frame ranges with exact integer arithmetic is the render planner's schedule; production consumes the ranges it publishes.
 * @evidenceExclude requirements/rendering/frame-schedules-and-sampling.md#rendering-frame-number-time Mapping every tier output frame to exactly one full-rate timeline frame and one exact time is the render planner's; production never renumbers a planned frame.
 * @evidenceExclude requirements/rendering/frame-schedules-and-sampling.md#rendering-schedule-audio-cues Deriving caption and cue times from the same rational film clock the frame schedule uses is render's caption and plan surface; production stores the result.
 * @evidenceExclude requirements/rendering/frame-schedules-and-sampling.md#rendering-schedule-refusal Refusing an invalid rate, an empty range or an unrepresentable frame count before scheduling is the render planner's; production refuses a stale plan, not an unschedulable one.
 * @evidenceExclude requirements/rendering/frame-schedules-and-sampling.md#rendering-state-sampling Declaring the one timeline frame per output frame at which capture resolves every shot layer and effect is the render planner's; production hands the plan to the capture host.
 * @evidenceExclude requirements/rendering/frame-schedules-and-sampling.md#rendering-subrange-stability Slicing every chunk from one global frame schedule so a retry carries exactly the frames a full render would is the render planner's; production re-runs the chunk the plan names.
 * @evidenceExclude requirements/rendering/scope-and-artifact-identity.md#rendering-product-scope Enumerating every product's expected outputs separately is the render plan's scope; production reports which of those outputs exist, are current or are missing.
 * @evidenceExclude requirements/rendering/frame-schedules-and-sampling.md#rendering-shutter-samples The prototype samples one instant per frame and claims no motion blur, so no shutter schedule exists to declare.
 * @evidenceExclude requirements/rendering/chunks-resume-and-recovery.md#rendering-chunk-partition Partitioning the frame schedule into content-addressed chunks whose identity is independent of chunk size or worker count is the render planner's; production locks, resumes and verifies the chunks it is given.
 * @evidenceExclude requirements/rendering/chunks-resume-and-recovery.md#rendering-chunk-assembly Assembling the feature from a contiguous set of current chunk encodes is the render Node entry's lossless splice; production plans the chunks and verifies their receipts.
 * @evidenceExclude requirements/rendering/headless-and-platform-determinism.md#rendering-hardware-variation The generated project's render commands own worker processes, capture surfaces, GC apply results and their operator-facing recovery; production plans, verifies and adjudicates the artifacts those commands produce.
 * @evidenceExclude requirements/rendering/headless-and-platform-determinism.md#rendering-headless-refusal The generated project's render commands own worker processes, capture surfaces, GC apply results and their operator-facing recovery; production plans, verifies and adjudicates the artifacts those commands produce.
 * @evidenceExclude requirements/rendering/headless-and-platform-determinism.md#rendering-process-isolation The generated project's render commands own worker processes, capture surfaces, GC apply results and their operator-facing recovery; production plans, verifies and adjudicates the artifacts those commands produce.
 * @evidenceExclude requirements/sound/sources-and-external-assets.md#sound-source-immutable-adoption Binding a planned cue to the digest of the adopted bytes is the render plan's audio asset identity; production stores the adoption receipt beside it.
 * @evidenceExclude requirements/sound/sources-and-external-assets.md#sound-derived-source-closure The input digest, ordered recipe and output facts of a source transformation are recorded by ingest's audio decoder; the render plan carries them and production stores the plan.
 * @evidenceExclude requirements/sound/sources-and-external-assets.md#sound-decode-contract The supported container, sample encoding, channel and rate envelope, and the refusal of anything outside it, are the ingest audio decoder's; production hands it adopted bytes and a target rate.
 * @evidenceExclude requirements/sound/sources-and-external-assets.md#sound-source-choice This unit describes a human decision, an operator policy or a destination profile the blocking prototype does not model; production records the typed facts a person decides from and never decides for them.
 * @evidenceExclude requirements/sound/sources-and-external-assets.md#sound-source-provider-adapter-boundary Keeping cue and mix consumption on provider-neutral bytes and technical facts is the ingest audio decoder's boundary; production stores the adoption receipt beside them.
 * @evidenceExclude requirements/sound/validation-and-delivery.md#sound-audible-review This unit describes a human decision, an operator policy or a destination profile the blocking prototype does not model; production records the typed facts a person decides from and never decides for them.
 * @evidenceExclude requirements/sound/validation-and-delivery.md#sound-budget-evidence Per-tier audio budget accounting is not computed by the prototype; the render plan records sample facts without a cost bound.
 * @evidenceExclude requirements/sound/validation-and-delivery.md#sound-final-media-probe Reopening final encoded bytes and comparing the complete Opus sample entry is the render delivery profile assertion; production joins that verdict to the sound plan and its evidence record.
 * @evidenceExclude requirements/sound/validation-and-delivery.md#sound-numeric-verification Hand-computed fixture verification and negative twins are the repository test corpus and review procedure, not a runtime export of this package.
 * @evidenceExclude requirements/sound/validation-and-delivery.md#sound-seek-chunk-equivalence The production package plans cue sample ranges and delivers the mixed master; the mixer, stems, automation, loudness and lip-sync contracts are the engine sound implementation.
 * @evidenceExclude specifications/authoring-and-authority/partial-targets-and-atomic-results.md#spec-authoring-partial-result-checkpoint Adopting, revising or discarding a checkpoint is the author's decision in the generated project's tracked source; production returns typed results and never adopts one on the user's behalf.
 * @evidenceExclude specifications/authoring-and-authority/partial-targets-and-atomic-results.md#spec-authoring-partial-work-state The builder records omissions and diagnostics; the six-state partial-target ledger is the generated project's authoring state.
 * @evidenceExclude specifications/authoring-and-authority/prototype-determinism-and-fidelity.md#spec-authoring-prototype-exclusion-compatibility Reopening a product exclusion is a contract-version decision recorded in the interface package's contract JSDoc, not a runtime behavior of the production library.
 * @evidenceExclude specifications/editorial-render-and-delivery/delivery-audio-text-and-localization.md#spec-delivery-description-alternatives The blocking prototype delivers one display-referred master, one guide stem set and one caption sidecar; this unit names a delivery product the prototype does not produce.
 * @evidenceExclude specifications/editorial-render-and-delivery/delivery-audio-text-and-localization.md#spec-delivery-localization Language-version closure, translation lineage and approval are not products of the prototype; production implements only the RFC 5646 cue identity cited under the caption units.
 * @evidenceExclude specifications/editorial-render-and-delivery/delivery-profiles-time-and-picture.md#spec-delivery-timecode-sync Carrying the exact rational picture rate and the stream timebases as separate plan fields is the render plan's; production compares a delivered stream against those fields.
 * @evidenceExclude specifications/editorial-render-and-delivery/delivery-profiles-time-and-picture.md#spec-delivery-profile-matrix The prototype has fixed final and proxy tiers; a destination constraint matrix with required, optional and intentionally absent items is not modeled.
 * @evidenceExclude specifications/editorial-render-and-delivery/render-schedule-state-and-headless.md#spec-render-artifact-lifecycle Fixing the revision, edit, range, products, dimensions and runtime profile of one render request is the render plan's lifecycle; production decides whether a stored plan is still current.
 * @evidenceExclude specifications/editorial-render-and-delivery/render-schedule-state-and-headless.md#spec-render-frame-schedule Generating the ordered frame set from the exact rational clock and slicing chunks from it is the render planner's; production executes and records the slices.
 * @evidenceExclude specifications/editorial-render-and-delivery/render-schedule-state-and-headless.md#spec-render-state-isolation The generated project's render commands own worker processes, capture surfaces, GC apply results and their operator-facing recovery; production plans, verifies and adjudicates the artifacts those commands produce.
 * @evidenceExclude specifications/evidence-and-provenance/completeness-freshness-and-refusal.md#evp-outcome-classification-lattice Aggregating outcomes, partial scopes and approvals across activities is the evidence layer's contract; production returns each check's own typed state and never folds them.
 * @evidenceExclude specifications/evidence-and-provenance/completeness-freshness-and-refusal.md#evp-partial-aggregation Aggregating outcomes, partial scopes and approvals across activities is the evidence layer's contract; production returns each check's own typed state and never folds them.
 * @evidenceExclude specifications/evidence-and-provenance/privacy-credentials-and-disclosure.md#evp-erasure-tombstone The project store's erase audit is a revision-guarded removal record for concurrency, not a privacy-basis tombstone with disposal scope and backup coverage.
 * @evidenceExclude specifications/evidence-and-provenance/privacy-credentials-and-disclosure.md#evp-external-transfer-authorization Transfer authorization and consent belong to the generated project's repaint configuration; production executes only a request the project already selected.
 * @evidenceExclude specifications/evidence-and-provenance/privacy-credentials-and-disclosure.md#evp-human-identity-pseudonymization This unit describes a human decision, an operator policy or a destination profile the blocking prototype does not model; production records the typed facts a person decides from and never decides for them.
 * @evidenceExclude specifications/evidence-and-provenance/privacy-credentials-and-disclosure.md#evp-redaction-derivative This unit describes a human decision, an operator policy or a destination profile the blocking prototype does not model; production records the typed facts a person decides from and never decides for them.
 * @evidenceExclude specifications/evidence-and-provenance/privacy-credentials-and-disclosure.md#evp-sensitive-metadata-filtering This unit describes a human decision, an operator policy or a destination profile the blocking prototype does not model; production records the typed facts a person decides from and never decides for them.
 * @evidenceExclude specifications/execution-and-recovery/artifacts-and-atomic-publication.md#execution-artifact-ownership-completeness The five-axis artifact snapshot is the validation session's record; production reports chunk states and publication identity through its own typed statuses.
 * @evidenceExclude specifications/execution-and-recovery/artifacts-and-atomic-publication.md#execution-publication-failure-outcome Separating payload write, durable flush, readback and acknowledgement outcomes is not modeled beyond the revision-guarded write; a failed cycle writes nothing and reports its refusal.
 * @evidenceExclude specifications/execution-and-recovery/retention-cleanup-and-quarantine.md#execution-cleanup-failure-capacity The apply result with reclaimed bytes, failure set and post-cleanup capacity is produced by the generated project's render cleanup command; production plans dispositions only.
 * @evidenceExclude specifications/execution-and-recovery/retention-cleanup-and-quarantine.md#execution-retention-classes Production classifies render artifacts by their plan and publication references, not by a retention policy class ledger with durations and recoverability.
 * @evidenceExclude specifications/execution-and-recovery/retention-cleanup-and-quarantine.md#execution-sensitive-retention-minimization Production stores no secret material; a separate retention policy for secrets is not a render artifact class this planner classifies.
 * @evidenceExclude specifications/interchange-and-adoption/media-inspection-boundaries.md#interchange-audio-inspection Separating observed audio source facts from processing results is ingest's audio decoder; production consumes the plan those facts travel in and inspects no audio bytes.
 * @evidenceExclude specifications/interchange-and-adoption/media-inspection-boundaries.md#interchange-extensible-media-profile External model, motion, spatial and profile inspection is the ingest package's inspector; production adopts its result and inspects only design-reference containers and text records itself.
 * @evidenceExclude specifications/interchange-and-adoption/media-inspection-boundaries.md#interchange-gltf-glb-inspection External model, motion, spatial and profile inspection is the ingest package's inspector; production adopts its result and inspects only design-reference containers and text records itself.
 * @evidenceExclude specifications/interchange-and-adoption/media-inspection-boundaries.md#interchange-motion-inspection External model, motion, spatial and profile inspection is the ingest package's inspector; production adopts its result and inspects only design-reference containers and text records itself.
 * @evidenceExclude specifications/interchange-and-adoption/media-inspection-boundaries.md#interchange-spatial-data-inspection External model, motion, spatial and profile inspection is the ingest package's inspector; production adopts its result and inspects only design-reference containers and text records itself.
 * @evidenceExclude specifications/interchange-and-adoption/provenance-rights-and-secrets.md#interchange-sensitive-metadata-projection This unit describes a human decision, an operator policy or a destination profile the blocking prototype does not model; production records the typed facts a person decides from and never decides for them.
 * @evidenceExclude specifications/production-evidence/graph.md#spec-authoring-production-evidence-additive-extension The generated production graph's shared inventory, discovery, integrity, additive extension and determinism are built by the evidence package factory; production consumes only its shape-stage result.
 * @evidenceExclude specifications/production-evidence/graph.md#spec-authoring-production-evidence-deterministic-result The generated production graph's shared inventory, discovery, integrity, additive extension and determinism are built by the evidence package factory; production consumes only its shape-stage result.
 * @evidenceExclude specifications/production-evidence/graph.md#spec-authoring-production-evidence-discovery The generated production graph's shared inventory, discovery, integrity, additive extension and determinism are built by the evidence package factory; production consumes only its shape-stage result.
 * @evidenceExclude specifications/production-evidence/graph.md#spec-authoring-production-evidence-physical-integrity The generated production graph's shared inventory, discovery, integrity, additive extension and determinism are built by the evidence package factory; production consumes only its shape-stage result.
 * @evidenceExclude specifications/production-evidence/graph.md#spec-authoring-production-evidence-shared-contract The generated production graph's shared inventory, discovery, integrity, additive extension and determinism are built by the evidence package factory; production consumes only its shape-stage result.
 * @evidenceExclude specifications/simulation-effects-and-sound/clocks-ordering-seek-and-checkpoints.md#deterministic-dependency-and-contact-order The production package materializes and samples authored effects on the film clock; the solver's tier, order, fidelity ceiling and external-result adoption are the engine effect implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/clocks-ordering-seek-and-checkpoints.md#numeric-platform-repeatability-class The production package materializes and samples authored effects on the film clock; the solver's tier, order, fidelity ceiling and external-result adoption are the engine effect implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-conform-dependency-invalidation Sound is planned anew from the compiled timeline on every render plan; production keeps no incremental sound timeline to conform or invalidate.
 * @evidenceExclude specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-event-sync-and-boundary-continuity The production package plans cue sample ranges and delivers the mixed master; the mixer, stems, automation, loudness and lip-sync contracts are the engine sound implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-loudness-peak-and-mix-failure The production package plans cue sample ranges and delivers the mixed master; the mixer, stems, automation, loudness and lip-sync contracts are the engine sound implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-mix-automation-sample-clock The production package plans cue sample ranges and delivers the mixed master; the mixer, stems, automation, loudness and lip-sync contracts are the engine sound implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-processing-chain-and-stable-summation The production package plans cue sample ranges and delivers the mixed master; the mixer, stems, automation, loudness and lip-sync contracts are the engine sound implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-stem-master-relation-contract The production package plans cue sample ranges and delivers the mixed master; the mixer, stems, automation, loudness and lip-sync contracts are the engine sound implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/scope-tiers-and-identities.md#authored-silence-and-missing-state The production package plans cue sample ranges and delivers the mixed master; the mixer, stems, automation, loudness and lip-sync contracts are the engine sound implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/scope-tiers-and-identities.md#external-result-provider-neutrality The production package materializes and samples authored effects on the film clock; the solver's tier, order, fidelity ceiling and external-result adoption are the engine effect implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/scope-tiers-and-identities.md#simulation-effects-sound-common-invariants The production package materializes and samples authored effects on the film clock; the solver's tier, order, fidelity ceiling and external-result adoption are the engine effect implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/scope-tiers-and-identities.md#simulation-effects-sound-prototype-fidelity-ceiling The production package materializes and samples authored effects on the film clock; the solver's tier, order, fidelity ceiling and external-result adoption are the engine effect implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/sound-sources-events-dialogue-and-foley.md#sound-decode-and-derived-source-closure Decode and derived-source closure belong to ingest's audio decoder, which mints the source revision; production records which plan and receipt consumed it.
 * @evidenceExclude specifications/simulation-effects-and-sound/sound-sources-events-dialogue-and-foley.md#dialogue-failure-contract The production package plans cue sample ranges and delivers the mixed master; the mixer, stems, automation, loudness and lip-sync contracts are the engine sound implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/sound-sources-events-dialogue-and-foley.md#dialogue-lipsync-join-and-seek The production package plans cue sample ranges and delivers the mixed master; the mixer, stems, automation, loudness and lip-sync contracts are the engine sound implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/sound-sources-events-dialogue-and-foley.md#dialogue-voice-consistency-and-phoneme-state Dialogue synthesis, phoneme marks and viseme derivation are the generated project's dialogue runtime and the engine's viseme join; production plans dialogue ranges.
 * @evidenceExclude specifications/simulation-effects-and-sound/sound-sources-events-dialogue-and-foley.md#foley-claim-and-failure-boundary The production package plans cue sample ranges and delivers the mixed master; the mixer, stems, automation, loudness and lip-sync contracts are the engine sound implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/sound-sources-events-dialogue-and-foley.md#foley-variation-layering-and-bound The production package plans cue sample ranges and delivers the mixed master; the mixer, stems, automation, loudness and lip-sync contracts are the engine sound implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/sound-sources-events-dialogue-and-foley.md#sound-cue-kind-and-event-timing The production package plans cue sample ranges and delivers the mixed master; the mixer, stems, automation, loudness and lip-sync contracts are the engine sound implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/sound-sources-events-dialogue-and-foley.md#sound-cue-sample-boundary-and-arrival The engine mixer converts each cue's emission and presentation time to integer sample indices and derives propagation arrival; production plans neither conversion.
 * @evidenceExclude specifications/simulation-effects-and-sound/sound-sources-events-dialogue-and-foley.md#sound-decoder-input-contract Separating observed source facts from a bounded decoded buffer, and refusing unsupported or damaged input rather than substituting silence, is the ingest audio decoder's contract.
 * @evidenceExclude specifications/simulation-effects-and-sound/sound-sources-events-dialogue-and-foley.md#sound-cue-failure-contract The engine mixer and its propagation refuse an invalid cue, emitter, span or arrival; production propagates that refusal and invents no cue outcome.
 * @evidenceExclude specifications/simulation-effects-and-sound/validation-evidence-and-compatibility.md#effect-evidence-status-and-external-result The production package materializes and samples authored effects on the film clock; the solver's tier, order, fidelity ceiling and external-result adoption are the engine effect implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/validation-evidence-and-compatibility.md#effect-hand-math-and-negative-twins Hand-computed fixture verification and negative twins are the repository test corpus and review procedure, not a runtime export of this package.
 * @evidenceExclude specifications/simulation-effects-and-sound/validation-evidence-and-compatibility.md#effect-seek-equivalence-and-visual-review The production package materializes and samples authored effects on the film clock; the solver's tier, order, fidelity ceiling and external-result adoption are the engine effect implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/validation-evidence-and-compatibility.md#simulation-sound-compatibility-and-recovery The production package materializes and samples authored effects on the film clock; the solver's tier, order, fidelity ceiling and external-result adoption are the engine effect implementation.
 * @evidenceExclude specifications/simulation-effects-and-sound/validation-evidence-and-compatibility.md#sound-budget-and-audible-review Per-tier audio budget accounting and audible review are not computed by the prototype; the render plan records sample facts without a cost bound.
 * @evidenceExclude specifications/validation-and-diagnostics/partial-artifacts-and-refusal.md#validation-artifact-refusal-boundary The validation session's five-axis result is the generated project's verify command; production supplies the typed chunk, publication and probe facts it consumes.
 * @evidenceExclude specifications/narrative-and-intent/budgets-continuity-and-deliverables.md#narrative-intent-budget-aggregate-variant The binder preserves the selected authored inventory and does not aggregate runtime budget variants.
 * @evidenceExclude specifications/narrative-and-intent/budgets-continuity-and-deliverables.md#narrative-intent-budget-feasibility-verdict Deliverable formatting cannot decide whether a production is feasible.
 * @evidenceExclude specifications/narrative-and-intent/budgets-continuity-and-deliverables.md#narrative-intent-budget-measurement-worst-case Binding tracked Markdown performs no resource measurement or worst-case analysis.
 * @evidenceExclude specifications/narrative-and-intent/budgets-continuity-and-deliverables.md#narrative-intent-budget-story-representation A reader-edition binder does not choose story representation or budget scope.
 * @evidenceExclude specifications/editorial-render-and-delivery/delivery-profiles-time-and-picture.md#spec-delivery-picture-products The versioned picture profile compared with decoded bytes is the render delivery surface; production records which deliverable carried those bytes and whether the publication is current.
 * @evidenceExclude specifications/editorial-render-and-delivery/delivery-audio-text-and-localization.md#spec-delivery-caption-readability-measurement The measure-always, verdict-only-on-exact-identity evaluator and its same-language gap lookup are the render caption implementation; production supplies the installed identity-bearing runtime and the compiled cue set.
 * @evidenceExclude specifications/review-and-acceptance/README.md#review-acceptance-document-map The documentation index organizes the contract corpus and is not a runtime obligation of this library population reader.
 */
export const AUTOMOVIE_PRODUCTION_EVIDENCE_EXCLUSIONS =
  "production-evidence-exclusions" as const;
