/**
 * Engine package boundaries for actors and asset representation.
 *
 * The package's lint.config.ts selects this declaration as an exclusion
 * carrier within its complete public-source population. It has no runtime
 * state and is not re-exported by the package barrel. Each declared
 * target/reason pair below owns one intentional negative relationship;
 * requirement and specification boundaries for this domain stay together.
 * Positive implementation citations remain on the actual public exports.
 * @evidenceExclude requirements/actors/facial-authoring/contract.md#actor-face-connected-basis Generic playback consumes the model already evaluated by the human authoring builder; it does not own reusable facial identity and expression documents.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-connected-basis Engine mesh validation checks the evaluated result; facial basis admission, ordered endpoint evaluation and pre-seam normals belong to the human builder.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-parametric-hair Generic signed mesh queries provide a geometric primitive; scalp sampling, numerical styling documents, curve integration and strip assembly are human authoring responsibilities.
 * An exclusion neither implements a feature nor approves a rendered asset.
 * Add a boundary at its semantic owner and retain native graph validation.
 *
 * @evidenceExclude requirements/actors/body-authoring/README.md#body-requirements The engine supplies forward kinematics, range validation and mesh checks the human body builder calls; it does not own the connected body basis, its documents or its measurements.
 * @evidenceExclude requirements/actors/body-authoring/contract.md#actor-body-connected-basis The engine validates the evaluated resident model and topology; compiling sparse body endpoints, correctives and identity belongs to the human package.
 * @evidenceExclude requirements/actors/body-authoring/contract.md#actor-body-joints The engine resolves clinical poses and range violations on any skeleton; deriving joints from shape-following landmarks and skinning a basis surface belongs to the human body builder.
 * @evidenceExclude requirements/actors/body-authoring/contract.md#actor-body-measurements Girth, distance and height rules over a body basis belong to the human package; the engine offers no anthropometric measurement.
 * @evidenceExclude requirements/actors/body-authoring/contract.md#actor-body-document The engine reads models and poses, not compact body edit documents.
 * @evidenceExclude specifications/asset-and-representation/body-authoring/README.md#body-specifications The engine implements the generic pose and validation contracts the body specification builds on, not the body basis, measurement or document boundaries themselves.
 * @evidenceExclude specifications/asset-and-representation/body-authoring/contract.md#body-spec-basis The engine validates the evaluated resident model and topology; compiling sparse body endpoints, correctives and identity belongs to the human package.
 * @evidenceExclude specifications/asset-and-representation/body-authoring/contract.md#body-spec-joints The engine resolves clinical poses and range violations on any skeleton; deriving joints from shape-following landmarks and skinning a basis surface belongs to the human body builder.
 * @evidenceExclude specifications/asset-and-representation/body-authoring/contract.md#body-spec-measurements Girth, distance and height rules over a body basis belong to the human package; the engine offers no anthropometric measurement.
 * @evidenceExclude specifications/asset-and-representation/body-authoring/contract.md#body-spec-document The engine reads models and poses, not compact body edit documents.
 * @evidenceExclude requirements/actors/body-authoring/contract.md#actor-body-editor The engine hosts no body editing screen; the playground page does.
 * @evidenceExclude requirements/actors/body-authoring/contract.md#actor-body-export The engine does not serialize a built body; the human package's exporter does.
 * @evidenceExclude specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor-view The engine owns no body editor inputs or display state.
 * @evidenceExclude specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor The engine owns no body editor transaction or worker boundary.
 * @evidenceExclude specifications/asset-and-representation/body-authoring/contract.md#body-spec-export The engine does not write a built body to glTF through the human package.
 * @evidenceExclude requirements/actors/body-authoring/contract.md#actor-body-simple-shape The engine does not expand simple body parameters; the human package's expansion does.
 * @evidenceExclude specifications/asset-and-representation/body-authoring/contract.md#body-spec-simple-shape The engine evaluates no simple-tier table or measured inversion.
 * @evidenceExclude requirements/actors/facial-authoring/README.md#face-requirements The engine consumes authored meshes and generic face rigs; its deterministic playback boundary does not implement detailed facial authoring across document, editor and study review.
 * @evidenceExclude requirements/actors/facial-authoring/contract.md#actor-face-document The engine consumes authored meshes and generic face rigs; its deterministic playback boundary does not implement the standalone human-face recipe, basis and version interpreter.
 * @evidenceExclude requirements/actors/facial-authoring/contract.md#actor-face-anatomical-components The engine consumes authored meshes and generic face rigs; its deterministic playback boundary does not implement named craniofacial components, cavities and attached tissues.
 * @evidenceExclude requirements/actors/facial-authoring/contract.md#actor-face-skin-condition The engine deforms already-authored meshes through generic fields; it does not define anatomical rest-state skin or expression-dependent facial crease populations.
 * @evidenceExclude requirements/actors/facial-authoring/contract.md#actor-face-skin-colour Generic mesh processing preserves supplied RGB; anatomical region binding and expression-relative colour construction belong to human.
 * @evidenceExclude requirements/actors/facial-authoring/contract.md#actor-face-controls-replacement The engine consumes authored meshes and generic face rigs; its deterministic playback boundary does not implement anatomical detail overrides and side-specific part replacement.
 * @evidenceExclude requirements/actors/facial-authoring/contract.md#actor-face-expression The engine consumes authored meshes and generic face rigs; its deterministic playback boundary does not implement observed-relative eyelid, oral, dental and gaze performance.
 * @evidenceExclude requirements/actors/facial-authoring/contract.md#actor-face-editor The engine consumes authored meshes and generic face rigs; its deterministic playback boundary does not implement the interactive face editor, camera and file controls.
 * @evidenceExclude requirements/actors/facial-authoring/contract.md#actor-face-editor-state The engine consumes authored meshes and generic face rigs; its deterministic playback boundary does not implement transactional face-document history and asynchronous last-valid publication.
 * @evidenceExclude requirements/actors/facial-authoring/contract.md#actor-face-export The engine consumes authored meshes and generic face rigs; its deterministic playback boundary does not implement validated anatomical face GLTF/GLB serialization.
 * @evidenceExclude requirements/actors/facial-authoring/contract.md#actor-face-provenance The engine consumes authored meshes and generic face rigs; its deterministic playback boundary does not implement non-executable selected-portrait facts in the face document.
 * @evidenceExclude requirements/actors/facial-authoring/contract.md#actor-face-review The engine consumes authored meshes and generic face rigs; its deterministic playback boundary does not implement per-person source inventories, direct render inspection and likeness decisions.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/README.md#face-specifications The engine consumes authored meshes and generic face rigs; its deterministic playback boundary does not implement the complete face construction, application and review boundary.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-document The engine consumes authored meshes and generic face rigs; its deterministic playback boundary does not implement human-face version admission and photo-independent basis interpretation.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-components The engine consumes authored meshes and generic face rigs; its deterministic playback boundary does not implement cranial, cervical, ocular, nasal, oral and auricular surface assembly.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-skin-condition Generic engine deformation consumes caller-owned fields; the human assembly owns facial attachment-driven fields and the local sampling of its portrait surface.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-skin-colour Generic mesh processing preserves supplied RGB; anatomical region binding and expression-relative colour construction belong to human.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-controls The engine consumes authored meshes and generic face rigs; its deterministic playback boundary does not implement ordered face defaults, trait offsets, array replacement and asymmetric detail.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-attachments The engine consumes authored meshes and generic face rigs; its deterministic playback boundary does not implement face-part cut ownership and final-surface attachment correspondence.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-expression The engine consumes authored meshes and generic face rigs; its deterministic playback boundary does not implement the neutral/observed/current face solve and fixed optical identity.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-editor The engine consumes authored meshes and generic face rigs; its deterministic playback boundary does not implement request-generation isolation and committed face history.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-editor-view The engine consumes authored meshes and generic face rigs; its deterministic playback boundary does not implement DOM face controls, camera/clay state and last-valid downloads.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-export The engine consumes authored meshes and generic face rigs; its deterministic playback boundary does not implement face-specific Float32, optical-material and GLTF serialization admission.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-provenance The engine consumes authored meshes and generic face rigs; its deterministic playback boundary does not implement nullable portrait provenance that does not execute during face replay.
 * @evidenceExclude specifications/asset-and-representation/facial-authoring/contract.md#face-spec-review The engine consumes authored meshes and generic face rigs; its deterministic playback boundary does not implement input/output review receipts, required portrait views and subjective acceptance.
 * @evidenceExclude requirements/actors/README.md#actor-요구사항 The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/appearance-costume-and-attachments.md#actor-costume-intersection-refusal The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/appearance-costume-and-attachments.md#actor-costume-layers-variants The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/appearance-costume-and-attachments.md#actor-external-appearance-assets The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/appearance-costume-and-attachments.md#actor-rigid-soft-binding The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/body-scale-and-landmarks.md#actor-bounds-shot-scale The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/body-scale-and-landmarks.md#actor-left-right-asymmetry The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/body-scale-and-landmarks.md#actor-proportion-neutral The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/body-scale-and-landmarks.md#actor-scale-validation The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/inputs-selection-and-replacement.md#actor-external-rig-adoption The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/inputs-selection-and-replacement.md#actor-independent-binding-selection The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/inputs-selection-and-replacement.md#actor-input-compatibility-preview The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/inputs-selection-and-replacement.md#actor-selection-replacement-receipt The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/performance-and-story-binding.md#actor-performance-gap The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/performance-and-story-binding.md#actor-performance-precedence The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/populations-and-doubles.md#actor-doubles-replacement The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/populations-and-doubles.md#actor-population-budget The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/populations-and-doubles.md#actor-population-refusal The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/pose-expression-and-gaze.md#actor-pose-motion-distinction The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/representation-tiers-and-fidelity-boundary.md#actor-direct-authoring-ceiling The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/representation-tiers-and-fidelity-boundary.md#actor-external-representation The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/representation-tiers-and-fidelity-boundary.md#actor-fidelity-capability-separation The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/representation-tiers-and-fidelity-boundary.md#actor-quality-claim-boundary The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/representation-tiers-and-fidelity-boundary.md#actor-shot-tier-selection The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/representation-tiers-and-fidelity-boundary.md#actor-tier-compatibility The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/scope-and-identity.md#actor-authored-facts The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/scope-and-identity.md#actor-character-distinction The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/scope-and-identity.md#actor-missing-binding The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/scope-and-identity.md#actor-open-control-vocabulary The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/scope-and-identity.md#actor-open-performer-kind The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/state-and-continuity.md#actor-state-alternatives The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/state-and-continuity.md#actor-state-authority-provenance The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/state-and-continuity.md#actor-state-reset-refusal The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/state-and-continuity.md#actor-state-unknown-not-applicable The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/validation.md#actor-current-evidence The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/validation.md#actor-multi-angle-review The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/validation.md#actor-numeric-geometry-validation The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/validation.md#actor-purpose-validation The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/validation.md#actor-validation-ceiling The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/voice-and-utterance-identity.md#actor-voice-casting-selection The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/voice-and-utterance-identity.md#actor-voice-continuity The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/voice-and-utterance-identity.md#actor-voice-refusal The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/actors/voice-and-utterance-identity.md#actor-voice-source-choice The Engine realizes the actor rigs, poses, motion, and bindings cited by its concrete units; residual casting, identity authority, source selection, fidelity judgment, and replacement policy belong to project authoring and compilation.
 * @evidenceExclude requirements/asset-authoring/README.md#자산-저작-요구사항 The Engine consumes declared asset geometry and rig facts in the concrete operations cited by its units; acquisition, modeling decisions, provenance, cataloging, and authoring approval remain outside this runtime package.
 * @evidenceExclude requirements/asset-authoring/era-and-style.md#asset-style-as-input The Engine consumes declared asset geometry and rig facts in the concrete operations cited by its units; acquisition, modeling decisions, provenance, cataloging, and authoring approval remain outside this runtime package.
 * @evidenceExclude requirements/asset-authoring/era-and-style.md#asset-style-catalogue-refusal The Engine consumes declared asset geometry and rig facts in the concrete operations cited by its units; acquisition, modeling decisions, provenance, cataloging, and authoring approval remain outside this runtime package.
 * @evidenceExclude requirements/asset-authoring/era-and-style.md#asset-style-mixing The Engine consumes declared asset geometry and rig facts in the concrete operations cited by its units; acquisition, modeling decisions, provenance, cataloging, and authoring approval remain outside this runtime package.
 * @evidenceExclude requirements/asset-authoring/external-assets.md#asset-external-adoption-mode The Engine consumes declared asset geometry and rig facts in the concrete operations cited by its units; acquisition, modeling decisions, provenance, cataloging, and authoring approval remain outside this runtime package.
 * @evidenceExclude requirements/asset-authoring/external-assets.md#asset-external-conversion-receipt The Engine consumes declared asset geometry and rig facts in the concrete operations cited by its units; acquisition, modeling decisions, provenance, cataloging, and authoring approval remain outside this runtime package.
 * @evidenceExclude requirements/asset-authoring/external-assets.md#asset-external-scene-graph-preservation The Engine consumes declared asset geometry and rig facts in the concrete operations cited by its units; acquisition, modeling decisions, provenance, cataloging, and authoring approval remain outside this runtime package.
 * @evidenceExclude requirements/asset-authoring/external-assets.md#asset-external-secret-boundary The Engine consumes declared asset geometry and rig facts in the concrete operations cited by its units; acquisition, modeling decisions, provenance, cataloging, and authoring approval remain outside this runtime package.
 * @evidenceExclude requirements/asset-authoring/generated-assets.md#asset-generated-adoption-modes The Engine consumes declared asset geometry and rig facts in the concrete operations cited by its units; acquisition, modeling decisions, provenance, cataloging, and authoring approval remain outside this runtime package.
 * @evidenceExclude requirements/asset-authoring/generated-assets.md#asset-generation-attempt-lineage The Engine consumes declared asset geometry and rig facts in the concrete operations cited by its units; acquisition, modeling decisions, provenance, cataloging, and authoring approval remain outside this runtime package.
 * @evidenceExclude requirements/asset-authoring/generated-assets.md#asset-generation-input-rights The Engine consumes declared asset geometry and rig facts in the concrete operations cited by its units; acquisition, modeling decisions, provenance, cataloging, and authoring approval remain outside this runtime package.
 * @evidenceExclude requirements/asset-authoring/generated-assets.md#asset-generation-provider-independence The Engine consumes declared asset geometry and rig facts in the concrete operations cited by its units; acquisition, modeling decisions, provenance, cataloging, and authoring approval remain outside this runtime package.
 * @evidenceExclude requirements/asset-authoring/generated-assets.md#asset-generation-refusal The Engine consumes declared asset geometry and rig facts in the concrete operations cited by its units; acquisition, modeling decisions, provenance, cataloging, and authoring approval remain outside this runtime package.
 * @evidenceExclude requirements/asset-authoring/generated-assets.md#asset-procedural-generation-distinction The Engine consumes declared asset geometry and rig facts in the concrete operations cited by its units; acquisition, modeling decisions, provenance, cataloging, and authoring approval remain outside this runtime package.
 * @evidenceExclude requirements/asset-authoring/identity-and-instances.md#asset-instance-override-provenance The Engine consumes declared asset geometry and rig facts in the concrete operations cited by its units; acquisition, modeling decisions, provenance, cataloging, and authoring approval remain outside this runtime package.
 * @evidenceExclude requirements/asset-authoring/identity-and-instances.md#asset-variant-inheritance The Engine consumes declared asset geometry and rig facts in the concrete operations cited by its units; acquisition, modeling decisions, provenance, cataloging, and authoring approval remain outside this runtime package.
 * @evidenceExclude requirements/asset-authoring/materials-and-textures.md#asset-material-state The Engine consumes declared asset geometry and rig facts in the concrete operations cited by its units; acquisition, modeling decisions, provenance, cataloging, and authoring approval remain outside this runtime package.
 * @evidenceExclude requirements/asset-authoring/representations-bounds-and-lod.md#asset-lod-proxy-lineage The Engine consumes declared asset geometry and rig facts in the concrete operations cited by its units; acquisition, modeling decisions, provenance, cataloging, and authoring approval remain outside this runtime package.
 * @evidenceExclude requirements/asset-authoring/representations-bounds-and-lod.md#asset-representation-semantic-preservation The Engine consumes declared asset geometry and rig facts in the concrete operations cited by its units; acquisition, modeling decisions, provenance, cataloging, and authoring approval remain outside this runtime package.
 * @evidenceExclude requirements/asset-authoring/representations-bounds-and-lod.md#asset-representation-stale-refusal The Engine consumes declared asset geometry and rig facts in the concrete operations cited by its units; acquisition, modeling decisions, provenance, cataloging, and authoring approval remain outside this runtime package.
 * @evidenceExclude requirements/asset-authoring/rig-and-state.md#asset-derived-deformation-basis The Engine consumes declared asset geometry and rig facts in the concrete operations cited by its units; acquisition, modeling decisions, provenance, cataloging, and authoring approval remain outside this runtime package.
 * @evidenceExclude requirements/asset-authoring/validation.md#asset-representation-bounds-validation The Engine consumes declared asset geometry and rig facts in the concrete operations cited by its units; acquisition, modeling decisions, provenance, cataloging, and authoring approval remain outside this runtime package.
 * @evidenceExclude requirements/external-inputs/README.md#외부-입력-요구사항 The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/adoption-modes-and-composition.md#external-adoption-intent-persistence The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/adoption-modes-and-composition.md#external-adoption-selection-overrides The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/conversion-receipts-and-determinism.md#external-conversion-receipt-canonical-result The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/conversion-receipts-and-determinism.md#external-conversion-receipt-freshness The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/conversion-receipts-and-determinism.md#external-conversion-receipt-inputs The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/conversion-receipts-and-determinism.md#external-conversion-receipt-loss The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/conversion-receipts-and-determinism.md#external-conversion-receipt-mapping The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/credentials-rights-and-provenance.md#external-credential-separation The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/credentials-rights-and-provenance.md#external-provenance-sensitive-data The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/credentials-rights-and-provenance.md#external-provenance-source-record The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/identity-coordinates-and-units.md#external-identity-content-provenance The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/identity-coordinates-and-units.md#external-identity-source-revision The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/media-families-and-declared-facts.md#external-media-audio The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/media-families-and-declared-facts.md#external-media-extensible-families The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/media-families-and-declared-facts.md#external-media-gltf-glb The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/media-families-and-declared-facts.md#external-media-motion The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/media-families-and-declared-facts.md#external-media-spatial-data The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/media-families-and-declared-facts.md#external-media-text-metadata The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/refresh-version-pinning-and-offline.md#external-cache-identity-trust The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/refresh-version-pinning-and-offline.md#external-cache-miss-unavailable-source The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/refresh-version-pinning-and-offline.md#external-explicit-refresh The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/refresh-version-pinning-and-offline.md#external-offline-ready-inputs The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/resource-closure-and-acquisition.md#external-resource-archive-bounds The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/resource-closure-and-acquisition.md#external-resource-location-boundary The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/resource-closure-and-acquisition.md#external-resource-network-dependency The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/resource-closure-and-acquisition.md#external-resource-original-bytes The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/source-selection-and-provider-neutrality.md#external-source-acquisition-failure The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/source-selection-and-provider-neutrality.md#external-source-authority-boundary The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/source-selection-and-provider-neutrality.md#external-source-channel-parity The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/source-selection-and-provider-neutrality.md#external-source-provider-neutrality The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/source-selection-and-provider-neutrality.md#external-source-transfer-authority The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/unsupported-and-degradation.md#external-partial-adoption-boundary The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/unsupported-and-degradation.md#external-placeholder-final-boundary The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/unsupported-and-degradation.md#external-support-regression-compatibility The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/unsupported-and-degradation.md#external-user-chosen-degradation The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/validation-and-quarantine.md#external-validation-active-content The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/validation-and-quarantine.md#external-validation-adoption-gate The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/validation-and-quarantine.md#external-validation-quarantine-handling The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude requirements/external-inputs/validation-and-quarantine.md#external-validation-result-states The Engine consumes explicitly normalized external facts where cited; byte acquisition, decoding policy, quarantine, rights, credentials, conversion receipts, and adoption authority belong to ingestion and orchestration.
 * @evidenceExclude specifications/asset-and-representation/README.md#자산과-표현-시스템-사양 The Engine implements only the cited geometry, rig, proxy, and validation algorithms; residual asset declaration, acquisition, lifecycle, representation authority, and adoption contracts belong to interface, ingest, and authoring layers.
 * @evidenceExclude specifications/asset-and-representation/alternatives-instances-and-groups.md#asset-spec-alternative-failure-compatibility The Engine implements only the cited geometry, rig, proxy, and validation algorithms; residual asset declaration, acquisition, lifecycle, representation authority, and adoption contracts belong to interface, ingest, and authoring layers.
 * @evidenceExclude specifications/asset-and-representation/alternatives-instances-and-groups.md#asset-spec-instance-override-resolution The Engine implements only the cited geometry, rig, proxy, and validation algorithms; residual asset declaration, acquisition, lifecycle, representation authority, and adoption contracts belong to interface, ingest, and authoring layers.
 * @evidenceExclude specifications/asset-and-representation/alternatives-instances-and-groups.md#asset-spec-variant-inheritance The Engine implements only the cited geometry, rig, proxy, and validation algorithms; residual asset declaration, acquisition, lifecycle, representation authority, and adoption contracts belong to interface, ingest, and authoring layers.
 * @evidenceExclude specifications/asset-and-representation/bounds-proxies-and-lod.md#asset-spec-bounds-lod-failures The Engine implements only the cited geometry, rig, proxy, and validation algorithms; residual asset declaration, acquisition, lifecycle, representation authority, and adoption contracts belong to interface, ingest, and authoring layers.
 * @evidenceExclude specifications/asset-and-representation/bounds-proxies-and-lod.md#asset-spec-lod-output-costs The Engine implements only the cited geometry, rig, proxy, and validation algorithms; residual asset declaration, acquisition, lifecycle, representation authority, and adoption contracts belong to interface, ingest, and authoring layers.
 * @evidenceExclude specifications/asset-and-representation/bounds-proxies-and-lod.md#asset-spec-proxy-purpose-lineage The Engine implements only the cited geometry, rig, proxy, and validation algorithms; residual asset declaration, acquisition, lifecycle, representation authority, and adoption contracts belong to interface, ingest, and authoring layers.
 * @evidenceExclude specifications/asset-and-representation/fidelity-and-validation.md#asset-spec-validation-compatibility-ceiling The Engine implements only the cited geometry, rig, proxy, and validation algorithms; residual asset declaration, acquisition, lifecycle, representation authority, and adoption contracts belong to interface, ingest, and authoring layers.
 * @evidenceExclude specifications/asset-and-representation/fidelity-and-validation.md#asset-spec-validation-current-evidence The Engine implements only the cited geometry, rig, proxy, and validation algorithms; residual asset declaration, acquisition, lifecycle, representation authority, and adoption contracts belong to interface, ingest, and authoring layers.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-generation-adoption-failures The Engine implements only the cited geometry, rig, proxy, and validation algorithms; residual asset declaration, acquisition, lifecycle, representation authority, and adoption contracts belong to interface, ingest, and authoring layers.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-generation-attempt-identity The Engine implements only the cited geometry, rig, proxy, and validation algorithms; residual asset declaration, acquisition, lifecycle, representation authority, and adoption contracts belong to interface, ingest, and authoring layers.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-generation-credential-boundary The Engine implements only the cited geometry, rig, proxy, and validation algorithms; residual asset declaration, acquisition, lifecycle, representation authority, and adoption contracts belong to interface, ingest, and authoring layers.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-generation-provider-choice The Engine implements only the cited geometry, rig, proxy, and validation algorithms; residual asset declaration, acquisition, lifecycle, representation authority, and adoption contracts belong to interface, ingest, and authoring layers.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-repaint-attempt-selection The Engine implements only the cited geometry, rig, proxy, and validation algorithms; residual asset declaration, acquisition, lifecycle, representation authority, and adoption contracts belong to interface, ingest, and authoring layers.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-repaint-controls-references The Engine implements only the cited geometry, rig, proxy, and validation algorithms; residual asset declaration, acquisition, lifecycle, representation authority, and adoption contracts belong to interface, ingest, and authoring layers.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-repaint-derivation-validation Engine has no repaint rendition, request, control, reference, or output identity validator; repaint compilation and orchestration own canonical derivation validation before an admitted asset reaches Engine execution.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-repaint-eligibility-source-lock The Engine implements only the cited geometry, rig, proxy, and validation algorithms; residual asset declaration, acquisition, lifecycle, representation authority, and adoption contracts belong to interface, ingest, and authoring layers.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-repaint-execution-eligibility Engine does not assemble or admit repaint requests against current source compilation, structural review, frame and control alignment, reference digests, and delivery authorization; repaint orchestration owns that gate.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-repaint-failure-publication The Engine implements only the cited geometry, rig, proxy, and validation algorithms; residual asset declaration, acquisition, lifecycle, representation authority, and adoption contracts belong to interface, ingest, and authoring layers.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-repaint-manual-routing Engine neither selects a delivery repaint lane nor invokes a repaint guide or provider adapter; the caller and repaint orchestrator own explicit manual routing.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-repaint-output-provenance The Engine implements only the cited geometry, rig, proxy, and validation algorithms; residual asset declaration, acquisition, lifecycle, representation authority, and adoption contracts belong to interface, ingest, and authoring layers.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-repaint-structure-continuity The Engine implements only the cited geometry, rig, proxy, and validation algorithms; residual asset declaration, acquisition, lifecycle, representation authority, and adoption contracts belong to interface, ingest, and authoring layers.
 * @evidenceExclude specifications/asset-and-representation/identity-resources-and-lifecycle.md#asset-spec-identity-inputs The Engine implements only the cited geometry, rig, proxy, and validation algorithms; residual asset declaration, acquisition, lifecycle, representation authority, and adoption contracts belong to interface, ingest, and authoring layers.
 * @evidenceExclude specifications/asset-and-representation/identity-resources-and-lifecycle.md#asset-spec-lifecycle-states The Engine implements only the cited geometry, rig, proxy, and validation algorithms; residual asset declaration, acquisition, lifecycle, representation authority, and adoption contracts belong to interface, ingest, and authoring layers.
 * @evidenceExclude specifications/asset-and-representation/identity-resources-and-lifecycle.md#asset-spec-source-revision-content The Engine implements only the cited geometry, rig, proxy, and validation algorithms; residual asset declaration, acquisition, lifecycle, representation authority, and adoption contracts belong to interface, ingest, and authoring layers.
 * @evidenceExclude specifications/asset-and-representation/model-geometry-and-surface-facts.md#asset-spec-surface-states-substitution The Engine implements only the cited geometry, rig, proxy, and validation algorithms; residual asset declaration, acquisition, lifecycle, representation authority, and adoption contracts belong to interface, ingest, and authoring layers.
 * @evidenceExclude specifications/asset-and-representation/rig-deformation-and-state.md#asset-spec-derived-deformation-staleness The Engine implements only the cited geometry, rig, proxy, and validation algorithms; residual asset declaration, acquisition, lifecycle, representation authority, and adoption contracts belong to interface, ingest, and authoring layers.
 * @evidenceExclude specifications/interchange-and-adoption/README.md#interchange와-adoption-시스템-계약 The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/adoption-decisions-and-composition.md#interchange-adoption-intent-replay The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/adoption-decisions-and-composition.md#interchange-selection-override-resolution The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/conversion-receipts-and-determinism.md#interchange-canonical-receipt-result The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/conversion-receipts-and-determinism.md#interchange-receipt-element-mapping The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/conversion-receipts-and-determinism.md#interchange-receipt-freshness-diff The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/conversion-receipts-and-determinism.md#interchange-receipt-input-basis The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/conversion-receipts-and-determinism.md#interchange-receipt-loss-ledger The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/identity-coordinates-and-units.md#interchange-content-provenance-identity The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/identity-coordinates-and-units.md#interchange-source-revision-identity The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/intake-authority-and-routing.md#interchange-acquisition-failure-envelope The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/intake-authority-and-routing.md#interchange-channel-independent-revision The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/intake-authority-and-routing.md#interchange-outbound-transfer-authorization The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/intake-authority-and-routing.md#interchange-provider-neutral-dispatch The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/intake-authority-and-routing.md#interchange-source-authority-separation The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/media-inspection-boundaries.md#interchange-audio-inspection The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/media-inspection-boundaries.md#interchange-extensible-media-profile The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/media-inspection-boundaries.md#interchange-gltf-glb-inspection The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/media-inspection-boundaries.md#interchange-motion-inspection The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/media-inspection-boundaries.md#interchange-spatial-data-inspection The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/media-inspection-boundaries.md#interchange-text-metadata-inspection The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/provenance-rights-and-secrets.md#interchange-secret-reference-boundary The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/provenance-rights-and-secrets.md#interchange-sensitive-metadata-projection The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/provenance-rights-and-secrets.md#interchange-source-provenance-snapshot The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/resource-closure-and-acquisition.md#interchange-expanded-resource-budget The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/resource-closure-and-acquisition.md#interchange-live-network-dependency-state The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/resource-closure-and-acquisition.md#interchange-locator-redirect-fence The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/resource-closure-and-acquisition.md#interchange-original-byte-preservation The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/revision-refresh-and-offline-cache.md#interchange-cache-entry-identity The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/revision-refresh-and-offline-cache.md#interchange-offline-miss-state The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/revision-refresh-and-offline-cache.md#interchange-offline-ready-closure The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/revision-refresh-and-offline-cache.md#interchange-refresh-transaction The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/support-degradation-and-refusal.md#interchange-compatibility-migration-gate The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/support-degradation-and-refusal.md#interchange-explicit-degradation-policy The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/support-degradation-and-refusal.md#interchange-partial-adoption-closure The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/support-degradation-and-refusal.md#interchange-placeholder-status-fence The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/validation-and-quarantine.md#interchange-active-content-isolation The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/validation-and-quarantine.md#interchange-atomic-adoption-gate The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/validation-and-quarantine.md#interchange-quarantine-exposure-removal The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/validation-and-quarantine.md#interchange-validation-result-envelope The Engine consumes normalized inputs where explicitly cited but does not acquire resources, parse interchange containers, manage rights or secrets, quarantine inputs, issue conversion receipts, or decide adoption.
 * @evidenceExclude specifications/interchange-and-adoption/media-inspection-boundaries.md#interchange-design-drawing-inspection The Engine derives drawings from normalized scene geometry but does not inspect or decode externally supplied design-drawing media; ingestion owns that inspection boundary.
 */
export type AutoMovieEngineEvidenceExclusions = never;
