/**
 * Authoring ranges for independent performance channels. These are supported
 * kinematic controls, not medical population limits or detector probabilities.
 *
 * @evidence requirements/actors/facial-authoring/contract.md#actor-face-expression Gives the editor explicit neutral, side and unit semantics for performance.
 * @evidence specifications/asset-and-representation/facial-authoring/contract.md#face-spec-expression Separates closure, gaze, perioral movement and mandibular angle.
 */
export const humanFaceExpressionDefinitions = [
  {
    id: "blink",
    label: "Eyelid closure",
    unit: "fraction",
    minimum: 0,
    maximum: 1,
    step: 0.01,
    neutral: 0,
    paired: true,
  },
  {
    id: "browRaise",
    label: "Brow elevation",
    unit: "mm",
    minimum: -6,
    maximum: 8,
    step: 0.1,
    neutral: 0,
    paired: true,
  },
  {
    id: "smile",
    label: "Mouth-corner elevation",
    unit: "mm",
    minimum: -5,
    maximum: 8,
    step: 0.1,
    neutral: 0,
    paired: true,
  },
  {
    id: "jawOpen",
    label: "Mandibular opening",
    unit: "degrees",
    minimum: 0,
    maximum: 25,
    step: 0.5,
    neutral: 0,
    paired: false,
  },
  {
    id: "lipPart",
    label: "Lip separation",
    unit: "mm",
    minimum: 0,
    maximum: 30,
    step: 0.1,
    neutral: 0,
    paired: false,
  },
  {
    id: "pucker",
    label: "Lip protrusion",
    unit: "mm",
    minimum: 0,
    maximum: 4,
    step: 0.1,
    neutral: 0,
    paired: false,
  },
  {
    id: "tongueRaise",
    label: "Tongue dorsum elevation",
    unit: "mm",
    minimum: -8,
    maximum: 8,
    step: 0.1,
    neutral: 0,
    paired: false,
  },
  {
    id: "tongueAdvance",
    label: "Tongue anterior displacement",
    unit: "mm",
    minimum: -8,
    maximum: 8,
    step: 0.1,
    neutral: 0,
    paired: false,
  },
  {
    id: "gazePitch",
    label: "Upward gaze",
    unit: "degrees",
    minimum: -20,
    maximum: 20,
    step: 0.5,
    neutral: 0,
    paired: true,
  },
  {
    id: "gazeYaw",
    label: "Leftward gaze",
    unit: "degrees",
    minimum: -25,
    maximum: 25,
    step: 0.5,
    neutral: 0,
    paired: true,
  },
] as const;
