import { createAutoMovieSignedMeshQuery } from "@automovie/engine";
import { HUMAN_FACE_LID_SEAT } from "@automovie/human/face/anatomy/eye/HUMAN_FACE_LID_SEAT";
import type { IAutoMovieHumanFaceBasis } from "@automovie/human/face/structures/IAutoMovieHumanFaceBasis";

import { HUMAN_SOURCE_PERIOCULAR_CAGE_SELECTION } from "./HUMAN_SOURCE_PERIOCULAR_CAGE_SELECTION.ts";
import { isHumanSourceProjectedLoopInterior } from "./isHumanSourceProjectedLoopInterior.ts";
import type { IHumanSourceAuthoredSkin } from "./structures/IHumanSourceAuthoredSkin.ts";
import type { IHumanSourceCompactedTopology } from "./structures/IHumanSourceCompactedTopology.ts";
import type { IHumanSourceMirror } from "./structures/IHumanSourceMirror.ts";
import type { IHumanSourceOrbitalSkinReceipt } from "./structures/IHumanSourceOrbitalSkinReceipt.ts";
import type { IHumanSourceOrbitalSkinSide } from "./structures/IHumanSourceOrbitalSkinSide.ts";

/**
 * Seat hidden orbital skin inside the posterior lid loop outside the source globe.
 *
 * The authored posterior loop is a closed cycle in the canonical head's XY
 * projection. Odd-even crossing selects its interior; cage stations are held.
 * Only selected root vertices below the shared posterior clearance move. The
 * engine's oriented-open query on the source eye and registered closure supplies
 * local nearest-feature normal and signed distance. Unsupported feature sides
 * refuse; no global closed-volume interior is certified by this query mode.
 * No vertex addresses are authored per person.
 *
 * The target height blends from the nearest projected margin segment's seated
 * height to the posterior clearance with smoothstep over the shared medial-bed
 * length. Segment heights interpolate its endpoints' measured heights. Their
 * lower bound is the clearance, so the blend cannot leave a selected vertex
 * inside the globe. XY is the source's frontal projection, not a fitted eye
 * frame; this rule supports this frontal, neutral source loop only.
 *
 * Invoke after cage seating. Both root and skin coordinates change together,
 * and both partition views are regenerated without changing topology, ordinals
 * or endpoint deltas. Bindings and field derivatives must be regenerated by
 * the generation compiler. This authored hidden-skin clearance establishes no
 * clinical tissue thickness, motion validity or rendered acceptance.
 */
export function regenerateHumanSourceOrbitalSkin(
  face: IAutoMovieHumanFaceBasis,
  root: IHumanSourceCompactedTopology,
  skin: IHumanSourceAuthoredSkin,
  mirror: IHumanSourceMirror,
): IHumanSourceOrbitalSkinReceipt {
  const globe = face.surfaces.find((surface) => surface.id === "Human.low-poly");
  const collider = face.contact?.colliders.find((entry) => entry.surface === "Human.low-poly");
  if (globe === undefined || collider === undefined)
    throw new Error("Orbital skin authoring needs the source globe and its collider closure.");
  const query = createAutoMovieSignedMeshQuery(
    { positions: globe.positions, indices: [...globe.indices, ...collider.closure], normals: null, uvs: null, skin: null },
    { boundary: "open" },
  );
  const clearance = HUMAN_FACE_LID_SEAT.posteriorClearanceMetres;
  const reach = HUMAN_FACE_LID_SEAT.medialBedMetres;
  if (!(clearance > 0) || !(reach > 0))
    throw new Error("Orbital skin authoring needs positive clearance and blend reach.");
  const before = Float64Array.from(skin.positions);
  const point = (vertex: number): number[] => Array.from(before.subarray(3 * vertex, 3 * vertex + 3));
  const smoothstep = (value: number): number => {
    const t = Math.min(1, Math.max(0, value));
    return t * t * (3 - 2 * t);
  };
  const sides: IHumanSourceOrbitalSkinSide[] = [];
  for (const side of ["left", "right"] as const) {
    const rows = HUMAN_SOURCE_PERIOCULAR_CAGE_SELECTION.stations.map((station) =>
      station.nativeVertices.map((native) => {
        const vertex = root.nativeToSource[side === "left" ? native : mirror.twin[native]];
        if (!Number.isSafeInteger(vertex) || vertex < 0)
          throw new Error(`Orbital skin authoring: ${side} cage names a retired vertex.`);
        return vertex;
      }),
    );
    const held = new Set(rows.flat());
    const loop = rows[0].map(point);
    const heights = loop.map((position) => {
      const hit = query(position);
      if (hit.boundary) throw new Error("Orbital skin margin reads an open globe rim.");
      return Math.max(clearance, hit.signedDistance);
    });
    const moved: number[] = [];
    let minimumBefore: number | null = null, minimumAfter: number | null = null, maximum = 0;
    for (let vertex = 0; vertex < root.topology.vertexCount; vertex++) {
      if (held.has(vertex)) continue;
      if (!isHumanSourceProjectedLoopInterior(before, rows[0], vertex)) continue;
      const position = point(vertex);
      let nearest = Infinity, boundaryHeight = clearance;
      for (let at = 0; at < loop.length; at++) {
        const a = loop[at], b = loop[(at + 1) % loop.length];
        const dx = b[0] - a[0], dy = b[1] - a[1];
        const rank = dx * dx + dy * dy;
        if (!(rank > 0)) throw new Error(`Orbital skin ${side} margin has a degenerate projected segment.`);
        const t = Math.min(1, Math.max(0, ((position[0] - a[0]) * dx + (position[1] - a[1]) * dy) / rank));
        const distance = Math.hypot(position[0] - a[0] - t * dx, position[1] - a[1] - t * dy);
        if (distance < nearest) {
          nearest = distance;
          boundaryHeight = (1 - t) * heights[at] + t * heights[(at + 1) % loop.length];
        }
      }
      const hit = query(position);
      if (hit.boundary) throw new Error(`Orbital skin ${side} interior reads an open globe rim.`);
      if (hit.signedDistance >= clearance) continue;
      const wanted = clearance + (boundaryHeight - clearance) * (1 - smoothstep(nearest / reach));
      const target = hit.point.map((value, axis) => value + wanted * hit.normal[axis]);
      if (target.some((value) => !Number.isFinite(value)))
        throw new Error("Orbital skin authoring produced a nonfinite coordinate.");
      const after = query(target);
      if (after.boundary) throw new Error("Authored orbital skin reads an open globe rim.");
      minimumBefore = Math.min(minimumBefore ?? Infinity, hit.signedDistance);
      minimumAfter = Math.min(minimumAfter ?? Infinity, after.signedDistance);
      maximum = Math.max(maximum, Math.hypot(...target.map((value, axis) => value - position[axis])));
      moved.push(vertex);
      for (let axis = 0; axis < 3; axis++) {
        root.topology.positions[3 * vertex + axis] = target[axis];
        skin.positions[3 * vertex + axis] = target[axis];
      }
    }
    sides.push({ side, movedSourceVertices: moved, minimumBeforeMetres: minimumBefore,
      minimumAfterMetres: minimumAfter, maximumDisplacementMetres: maximum });
  }
  const pick = (samples: Int32Array): Float64Array => Float64Array.from(Array.from(samples)
    .flatMap((vertex) => Array.from(skin.positions.subarray(3 * vertex, 3 * vertex + 3))));
  skin.headPositions = pick(skin.partition.cut.faceToG1);
  skin.bodyPositions = pick(skin.partition.cut.p1BodyToG1);
  return { revision: "source-orbital-skin-seat-1", posteriorClearanceMetres: clearance,
    blendReachMetres: reach, frame: "canonical source metres,+Xleft,+Yup,+Zanterior; frontal XY projection", sides,
    qualification: "Authored hidden neutral skin clearance on the source globe; no clinical tissue, motion or rendered acceptance." };
}
