import { createHumanSourceFieldContext } from "./createHumanSourceFieldContext.ts";
import { fillHumanSourceNippleRegion } from "./fillHumanSourceNippleRegion.ts";
import { produceHumanSourceDefinition } from "./produceHumanSourceDefinition.ts";
import { produceHumanSourceEnvelope } from "./produceHumanSourceEnvelope.ts";
import { roundHalfEven } from "./roundHalfEven.ts";
import type { IHumanSourceFieldInput } from "./structures/IHumanSourceFieldInput.ts";
import type { IHumanSourceFieldRegeneration } from "./structures/IHumanSourceFieldRegeneration.ts";
import type { IHumanSourceFieldResult } from "./structures/IHumanSourceFieldResult.ts";

/** Storage decimals of the regenerated rows (10 micrometres, as the published rows). */
const DECIMALS = 5;

/**
 * Regenerate the body's post-extraction fields whose producers are rebuilt
 * (definition-g1, envelope-g1) over the whole body view, one run per field, so
 * no field joins published values to new ones. Each dense field is carried to
 * the generation's samples, its nipple region refilled like every endpoint,
 * stored at 10 µm, and written as the view rows (P1 vertices) and the
 * generation rows (their samples). The endpoints leave the unavailable list,
 * their reproduction records say which producer revision made them, and the
 * stale stamp gains a regenerated stamp naming them.
 */
export function regenerateHumanSourceBodyFields(input: IHumanSourceFieldInput): IHumanSourceFieldRegeneration {
  const { body, generation, cut, sample } = input;
  const context = createHumanSourceFieldContext(body, generation, cut, input.bodyRows);
  const results: IHumanSourceFieldResult[] = [produceHumanSourceDefinition(context), produceHumanSourceEnvelope(context, body.channels)];
  const total = generation.skin.positions.length / 3;
  const p1Targets = { ...input.bodyRows.p1Targets };
  const g1Targets = { ...input.bodyRows.g1Targets };
  const unavailable = { ...input.bodyRows.unavailable };
  const revisionOf = new Map<string, string>();
  for (const result of results)
    for (const [name, dense] of Object.entries(result.rows)) {
      const onSamples = new Float64Array(3 * total);
      cut.p1BodyToG1.forEach((g, j) => {
        for (let c = 0; c < 3; c++) onSamples[3 * g + c] = dense[3 * j + c];
      });
      fillHumanSourceNippleRegion(sample, onSamples);
      const p1: number[] = [];
      const g1: [number, number, number, number][] = [];
      cut.p1BodyToG1.forEach((g, j) => {
        const value = [0, 1, 2].map((c) => roundHalfEven(onSamples[3 * g + c], DECIMALS));
        if (value.some((x) => x !== 0)) {
          p1.push(j, ...value);
          g1.push([g, value[0], value[1], value[2]]);
        }
      });
      g1.sort((a, b) => a[0] - b[0]);
      p1Targets[name] = p1;
      g1Targets[name] = g1.flat();
      delete unavailable[name];
      revisionOf.set(name, String(result.receipt.revision));
    }
  const bodyRows = {
    ...input.bodyRows,
    p1Targets,
    g1Targets,
    unavailable,
    losses: input.bodyRows.losses.filter((loss) => !revisionOf.has(loss.row)),
    rows: input.bodyRows.rows.map((row) =>
      revisionOf.has(row.row)
        ? { ...row, provenance: "regenerated-producer" as const, newSupport: "regenerated" as const, note: `whole field regenerated by producer ${revisionOf.get(row.row)} over the body view` }
        : row,
    ),
  };
  const targets = { ...generation.targets };
  for (const name of revisionOf.keys()) targets[name] = g1Targets[name];
  return {
    generation: {
      ...generation,
      targets,
      unavailable,
      stamps: [
        ...generation.stamps,
        {
          derivative: `body post-extraction fields regenerated by rebuilt producers (${[...new Set(revisionOf.values())].join(", ")})`,
          authoredOn: generation.id,
          status: "regenerated",
          note: `${[...revisionOf.keys()].join(", ")}: whole fields over the body view; new revisions, not the published values`,
        },
      ],
    },
    bodyRows,
    receipts: results.map((r) => r.receipt),
  };
}
