/**
 * Viewer package boundaries for formation, motion and staging.
 *
 * The package's lint.config.ts selects this declaration as an exclusion
 * carrier within its complete public-source population. It has no runtime
 * state and is not re-exported by the package barrel. Each declared
 * target/reason pair below owns one intentional negative relationship;
 * requirement and specification boundaries for this domain stay together.
 * Positive implementation citations remain on the actual public exports.
 * An exclusion neither implements a feature nor approves a rendered asset.
 * Add a boundary at its semantic owner and retain native graph validation.
 *
 * @evidenceExclude requirements/formations/budgets-and-validation.md The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/heroes-variation-and-state.md#formation-authored-variation-profile The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/heroes-variation-and-state.md#formation-continuity The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/heroes-variation-and-state.md#formation-group-state The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/heroes-variation-and-state.md#formation-hero-overrides The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/heroes-variation-and-state.md#formation-stable-background-identity The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/hierarchies-and-units.md The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/layouts-and-slots.md#formation-layout-capacity The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/layouts-and-slots.md#formation-layout-dressing The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/layouts-and-slots.md#formation-local-frame The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/layouts-and-slots.md#formation-slot-assignment-policy The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/layouts-and-slots.md#formation-slot-identity The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/README.md The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/reform-and-group-motion.md#formation-command-response-events The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/reform-and-group-motion.md#formation-reform-interior-state The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/reform-and-group-motion.md#formation-reform-local-blend The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/reform-and-group-motion.md#formation-reform-refusal The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/reform-and-group-motion.md#formation-reform-slot-assignment The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/resolution-culling-and-evidence.md#formation-resolution-culling-refusal The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/resolution-culling-and-evidence.md#formation-resolution-semantic-minimum The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/scope-and-identity.md#formation-all-repeated-subjects The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/scope-and-identity.md#formation-authoring-mode-selection The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/scope-and-identity.md#formation-open-kinds The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/scope-and-identity.md#formation-scope-refusal The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/scope-and-identity.md#formation-story-binding The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/spacing-overlap-and-avoidance.md The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/terrain-and-routes.md#formation-relief-adaptation The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/terrain-and-routes.md#formation-route-interior The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/terrain-and-routes.md#formation-route-layout-envelope The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/terrain-and-routes.md#formation-terrain-refusal The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/formations/terrain-and-routes.md#formation-terrain-support-profile The viewer displays resolved formations; formation authoring, solving, budget decisions, and validation remain upstream.
 * @evidenceExclude requirements/motion/channels-controls-and-drivers.md The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/clips-keyframes-and-interpolation.md The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/constraints-and-inverse-kinematics.md The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/contact-weight-and-support.md The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/external-motion-inputs.md The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/layers-blends-and-transitions.md#motion-blend-refusal The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/layers-blends-and-transitions.md#motion-layer-event-composition The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/layers-blends-and-transitions.md#motion-layer-mask-weight The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/layers-blends-and-transitions.md#motion-phase-alignment The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/layers-blends-and-transitions.md#motion-transition-window The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/object-motion-and-interaction.md#motion-coupled-objects The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/object-motion-and-interaction.md#motion-interaction-refusal The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/object-motion-and-interaction.md#motion-multi-subject-interaction The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/object-motion-and-interaction.md#motion-object-handoff The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/procedural-motion-and-gaits.md The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/README.md The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/retargeting-and-scale.md#motion-retarget-contact-preservation The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/retargeting-and-scale.md#motion-retarget-non-humanoid The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/retargeting-and-scale.md#motion-retarget-proportion The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/retargeting-and-scale.md#motion-retarget-refusal The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/retargeting-and-scale.md#motion-retarget-source-provenance The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/root-motion-and-trajectories.md#motion-facing-travel The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/root-motion-and-trajectories.md#motion-path-fit-warp The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/root-motion-and-trajectories.md#motion-path-timing The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/root-motion-and-trajectories.md#motion-root-ground-clearance The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/root-motion-and-trajectories.md#motion-trajectory-refusal The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/scope-and-identity.md The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/secondary-motion.md#motion-secondary-adoption-choice The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/secondary-motion.md#motion-secondary-claim-boundary The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/secondary-motion.md#motion-secondary-moving-boundary The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/secondary-motion.md#motion-secondary-static-compatibility The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/timing-and-semantic-events.md#motion-event-identity-payload The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/timing-and-semantic-events.md#motion-event-markers The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/timing-and-semantic-events.md#motion-retime-event-preservation The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/timing-and-semantic-events.md#motion-story-film-time The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/timing-and-semantic-events.md#motion-timing-refusal The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/motion/validation-and-determinism.md The viewer samples and applies resolved clips; motion authoring, retargeting policy, solving, and validation remain upstream.
 * @evidenceExclude requirements/staging/budgets-safety-and-validation.md The viewer materializes resolved staging; blocking authorship, spatial solving, alternatives, and validation remain upstream.
 * @evidenceExclude requirements/staging/coverage-and-alternative-takes.md The viewer materializes resolved staging; blocking authorship, spatial solving, alternatives, and validation remain upstream.
 * @evidenceExclude requirements/staging/events-and-timing.md The viewer materializes resolved staging; blocking authorship, spatial solving, alternatives, and validation remain upstream.
 * @evidenceExclude requirements/staging/interactions-and-choreography.md The viewer materializes resolved staging; blocking authorship, spatial solving, alternatives, and validation remain upstream.
 * @evidenceExclude requirements/staging/marks-zones-and-blocking.md The viewer materializes resolved staging; blocking authorship, spatial solving, alternatives, and validation remain upstream.
 * @evidenceExclude requirements/staging/README.md The viewer materializes resolved staging; blocking authorship, spatial solving, alternatives, and validation remain upstream.
 * @evidenceExclude requirements/staging/scope-and-source-of-truth.md#staging-authored-blocking The viewer materializes resolved staging; blocking authorship, spatial solving, alternatives, and validation remain upstream.
 * @evidenceExclude requirements/staging/scope-and-source-of-truth.md#staging-autofill-refusal The viewer materializes resolved staging; blocking authorship, spatial solving, alternatives, and validation remain upstream.
 * @evidenceExclude requirements/staging/scope-and-source-of-truth.md#staging-open-style The viewer materializes resolved staging; blocking authorship, spatial solving, alternatives, and validation remain upstream.
 * @evidenceExclude requirements/staging/scope-and-source-of-truth.md#staging-plan-alternatives The viewer materializes resolved staging; blocking authorship, spatial solving, alternatives, and validation remain upstream.
 * @evidenceExclude requirements/staging/scope-and-source-of-truth.md#staging-story-distinction The viewer materializes resolved staging; blocking authorship, spatial solving, alternatives, and validation remain upstream.
 * @evidenceExclude requirements/staging/scope-and-source-of-truth.md#staging-upstream-source-trace The viewer materializes resolved staging; blocking authorship, spatial solving, alternatives, and validation remain upstream.
 * @evidenceExclude requirements/staging/shot-contracts-and-deliveries.md The viewer materializes resolved staging; blocking authorship, spatial solving, alternatives, and validation remain upstream.
 * @evidenceExclude requirements/staging/state-handoff-and-continuity.md The viewer materializes resolved staging; blocking authorship, spatial solving, alternatives, and validation remain upstream.
 * @evidenceExclude requirements/staging/subjects-and-object-staging.md The viewer materializes resolved staging; blocking authorship, spatial solving, alternatives, and validation remain upstream.
 * @evidenceExclude requirements/staging/visibility-and-readability.md The viewer materializes resolved staging; blocking authorship, spatial solving, alternatives, and validation remain upstream.
 * @evidenceExclude specifications/performance-motion-and-staging/actor-identity-state-and-fidelity.md The viewer applies resolved performance state; authoring, solving, retargeting policy, budgets, and validation remain upstream.
 * @evidenceExclude specifications/performance-motion-and-staging/formation-identity-layout-and-terrain.md#performance-formation-sounding-membership-handoff The viewer applies resolved performance state; authoring, solving, retargeting policy, budgets, and validation remain upstream.
 * @evidenceExclude specifications/performance-motion-and-staging/formation-identity-layout-and-terrain.md#performance-formation-spacing-overlap-avoidance The viewer applies resolved performance state; authoring, solving, retargeting policy, budgets, and validation remain upstream.
 * @evidenceExclude specifications/performance-motion-and-staging/formation-identity-layout-and-terrain.md#performance-formation-static-clearance The viewer instances already-resolved slots and does not derive body bounds or validate static member clearance.
 * @evidenceExclude specifications/performance-motion-and-staging/formation-motion-resolution-and-budgets.md#performance-formation-bounds-framing-culling-failures The viewer applies resolved performance state; authoring, solving, retargeting policy, budgets, and validation remain upstream.
 * @evidenceExclude specifications/performance-motion-and-staging/formation-motion-resolution-and-budgets.md#performance-formation-budget-worst-case-cost The viewer applies already-admitted formations; worst-case formation budget calculation and admission remain upstream.
 * @evidenceExclude specifications/performance-motion-and-staging/formation-motion-resolution-and-budgets.md#performance-formation-geometry-layout-motion-validation The viewer applies resolved performance state; authoring, solving, retargeting policy, budgets, and validation remain upstream.
 * @evidenceExclude specifications/performance-motion-and-staging/formation-motion-resolution-and-budgets.md#performance-formation-layout-ground-validation The viewer instances compiled placements and does not validate resolved slot uniqueness, body clearance, or support-surface contact.
 * @evidenceExclude specifications/performance-motion-and-staging/formation-motion-resolution-and-budgets.md#performance-formation-member-exception-command-event The viewer applies resolved performance state; authoring, solving, retargeting policy, budgets, and validation remain upstream.
 * @evidenceExclude specifications/performance-motion-and-staging/formation-motion-resolution-and-budgets.md#performance-formation-motion-validation The viewer samples compiled formation cues and exceptions but does not validate their identities, bounds, or shot-local intervals.
 * @evidenceExclude specifications/performance-motion-and-staging/kinematics-contact-and-interaction.md#performance-contact-phase-weight-support The viewer applies resolved performance state; authoring, solving, retargeting policy, budgets, and validation remain upstream.
 * @evidenceExclude specifications/performance-motion-and-staging/kinematics-contact-and-interaction.md#performance-interaction-determinism-compatibility The viewer applies resolved performance state; authoring, solving, retargeting policy, budgets, and validation remain upstream.
 * @evidenceExclude specifications/performance-motion-and-staging/kinematics-contact-and-interaction.md#performance-kinematics-procedural-gait-rule The viewer applies resolved performance state; authoring, solving, retargeting policy, budgets, and validation remain upstream.
 * @evidenceExclude specifications/performance-motion-and-staging/motion-sampling-and-composition.md#performance-motion-clip-keytime-interpolation The viewer applies resolved performance state; authoring, solving, retargeting policy, budgets, and validation remain upstream.
 * @evidenceExclude specifications/performance-motion-and-staging/motion-sampling-and-composition.md#performance-motion-deterministic-sampling-validation The viewer applies resolved performance state; authoring, solving, retargeting policy, budgets, and validation remain upstream.
 * @evidenceExclude specifications/performance-motion-and-staging/motion-sampling-and-composition.md#performance-motion-external-adoption-receipt The viewer applies resolved performance state; authoring, solving, retargeting policy, budgets, and validation remain upstream.
 * @evidenceExclude specifications/performance-motion-and-staging/motion-sampling-and-composition.md#performance-motion-layer-mask-transition-composition The viewer applies resolved performance state; authoring, solving, retargeting policy, budgets, and validation remain upstream.
 * @evidenceExclude specifications/performance-motion-and-staging/README.md The viewer applies resolved performance state; authoring, solving, retargeting policy, budgets, and validation remain upstream.
 * @evidenceExclude specifications/performance-motion-and-staging/rig-deformation-and-retargeting.md#performance-rig-compatibility-fidelity-ceiling The viewer applies resolved performance state; authoring, solving, retargeting policy, budgets, and validation remain upstream.
 * @evidenceExclude specifications/performance-motion-and-staging/rig-deformation-and-retargeting.md#performance-rig-retarget-preservation-failure The viewer applies resolved performance state; authoring, solving, retargeting policy, budgets, and validation remain upstream.
 * @evidenceExclude specifications/performance-motion-and-staging/rig-deformation-and-retargeting.md#performance-rig-rom-control-driver-graph The viewer applies resolved performance state; authoring, solving, retargeting policy, budgets, and validation remain upstream.
 * @evidenceExclude specifications/performance-motion-and-staging/rig-deformation-and-retargeting.md#performance-rig-semantic-joint-mapping The viewer applies resolved performance state; authoring, solving, retargeting policy, budgets, and validation remain upstream.
 * @evidenceExclude specifications/performance-motion-and-staging/staging-events-coverage-and-validation.md The viewer applies resolved performance state; authoring, solving, retargeting policy, budgets, and validation remain upstream.
 * @evidenceExclude specifications/performance-motion-and-staging/staging-space-state-and-choreography.md The viewer applies resolved performance state; authoring, solving, retargeting policy, budgets, and validation remain upstream.
 */
export type AutoMovieViewerPerformanceEvidenceExclusions = never;
