/**
 * Viewer package boundaries for authoring authority and provenance.
 *
 * The package's lint.config.ts selects this declaration as an exclusion
 * carrier within its complete public-source population. It has no runtime
 * state and is not re-exported by the package barrel. Each declared
 * target/reason pair below owns one intentional negative relationship;
 * requirement and specification boundaries for this domain stay together.
 * Positive implementation citations remain on the actual public exports.
 * An exclusion neither implements a feature nor approves a rendered asset.
 * Add a boundary at its semantic owner and retain native graph validation.
 *
 * @evidenceExclude requirements/agent-authoring/capability-discovery.md The viewer consumes compiled artifacts; agent instructions, authoring workflow, and source ownership remain outside this runtime.
 * @evidenceExclude requirements/agent-authoring/deterministic-precomputation.md#agent-precomputed-closed-basis The viewer mounts already-compiled scene data for playback; it runs no generator, seals no basis, refuses no stale artifact, publishes no derived bytes, and holds no provenance ledger.
 * @evidenceExclude requirements/agent-authoring/deterministic-precomputation.md#agent-precomputed-compile-refusal The viewer mounts already-compiled scene data for playback; it runs no generator, seals no basis, refuses no stale artifact, publishes no derived bytes, and holds no provenance ledger.
 * @evidenceExclude requirements/agent-authoring/deterministic-precomputation.md#agent-precomputed-explicit-generation The viewer mounts already-compiled scene data for playback; it runs no generator, seals no basis, refuses no stale artifact, publishes no derived bytes, and holds no provenance ledger.
 * @evidenceExclude requirements/agent-authoring/deterministic-precomputation.md#agent-precomputed-portable-publication The viewer mounts already-compiled scene data for playback; it runs no generator, seals no basis, refuses no stale artifact, publishes no derived bytes, and holds no provenance ledger.
 * @evidenceExclude requirements/agent-authoring/deterministic-precomputation.md#agent-precomputed-provenance-separation The viewer mounts already-compiled scene data for playback; it runs no generator, seals no basis, refuses no stale artifact, publishes no derived bytes, and holds no provenance ledger.
 * @evidenceExclude requirements/agent-authoring/knowledge-boundary.md The viewer consumes compiled artifacts; agent instructions, authoring workflow, and source ownership remain outside this runtime.
 * @evidenceExclude requirements/agent-authoring/partial-work.md The viewer consumes compiled artifacts; agent instructions, authoring workflow, and source ownership remain outside this runtime.
 * @evidenceExclude requirements/agent-authoring/project-ownership.md The viewer consumes compiled artifacts; agent instructions, authoring workflow, and source ownership remain outside this runtime.
 * @evidenceExclude requirements/agent-authoring/README.md The viewer consumes compiled artifacts; agent instructions, authoring workflow, and source ownership remain outside this runtime.
 * @evidenceExclude requirements/agent-authoring/roles-and-authorities.md The viewer consumes compiled artifacts; agent instructions, authoring workflow, and source ownership remain outside this runtime.
 * @evidenceExclude requirements/agent-authoring/source-owned-loop.md The viewer consumes compiled artifacts; agent instructions, authoring workflow, and source ownership remain outside this runtime.
 * @evidenceExclude requirements/evidence-and-provenance/canonical-digests-and-content-identity.md The viewer renders compiled state; provenance capture, evidence retention, and audit authority remain outside this projection layer.
 * @evidenceExclude requirements/evidence-and-provenance/chain-of-custody-and-tamper-detection.md The viewer renders compiled state; provenance capture, evidence retention, and audit authority remain outside this projection layer.
 * @evidenceExclude requirements/evidence-and-provenance/completeness-freshness-and-refusal.md The viewer renders compiled state; provenance capture, evidence retention, and audit authority remain outside this projection layer.
 * @evidenceExclude requirements/evidence-and-provenance/entities-activities-agents-and-lineage.md The viewer renders compiled state; provenance capture, evidence retention, and audit authority remain outside this projection layer.
 * @evidenceExclude requirements/evidence-and-provenance/generation-transformation-and-derivation.md The viewer renders compiled state; provenance capture, evidence retention, and audit authority remain outside this projection layer.
 * @evidenceExclude requirements/evidence-and-provenance/observations-claims-and-human-judgments.md The viewer renders compiled state; provenance capture, evidence retention, and audit authority remain outside this projection layer.
 * @evidenceExclude requirements/evidence-and-provenance/privacy-credentials-and-disclosure.md The viewer renders compiled state; provenance capture, evidence retention, and audit authority remain outside this projection layer.
 * @evidenceExclude requirements/evidence-and-provenance/README.md The viewer renders compiled state; provenance capture, evidence retention, and audit authority remain outside this projection layer.
 * @evidenceExclude requirements/evidence-and-provenance/retention-invalidation-and-disposal.md The viewer renders compiled state; provenance capture, evidence retention, and audit authority remain outside this projection layer.
 * @evidenceExclude requirements/evidence-and-provenance/scope-identity-and-status.md The viewer renders compiled state; provenance capture, evidence retention, and audit authority remain outside this projection layer.
 * @evidenceExclude requirements/evidence-and-provenance/third-party-sources-rights-and-attribution.md The viewer renders compiled state; provenance capture, evidence retention, and audit authority remain outside this projection layer.
 * @evidenceExclude requirements/production-evidence/README.md The viewer projects admitted production state and does not configure or validate the generated project's authoring evidence graph.
 * @evidenceExclude requirements/production-evidence/graph.md The viewer projects admitted production state and does not configure or validate the generated project's authoring evidence graph.
 * @evidenceExclude requirements/production-evidence/native-input.md#agent-production-evidence-native-boundary Native graph configuration belongs to the evidence adapter; the viewer consumes compiled production state without transforming graph declarations.
 * @evidenceExclude requirements/production-evidence/input.md The viewer projects admitted production state and does not configure or validate the generated project's authoring evidence graph.
 * @evidenceExclude specifications/authoring-and-authority/capability-and-content-boundary.md The viewer consumes compiled state; authoring authority, source lineage, reconciliation, and refusal remain outside this runtime.
 * @evidenceExclude specifications/authoring-and-authority/delegation-and-decision-authority.md The viewer consumes compiled state; authoring authority, source lineage, reconciliation, and refusal remain outside this runtime.
 * @evidenceExclude specifications/authoring-and-authority/deterministic-precomputed-artifacts.md#spec-authoring-precomputed-basis The viewer renders compiled results and implements no derived ledger, basis closure, generation attempt, compile freshness matrix, publication path invariant, or execution-budget boundary.
 * @evidenceExclude specifications/authoring-and-authority/deterministic-precomputed-artifacts.md#spec-authoring-precomputed-freshness The viewer renders compiled results and implements no derived ledger, basis closure, generation attempt, compile freshness matrix, publication path invariant, or execution-budget boundary.
 * @evidenceExclude specifications/authoring-and-authority/deterministic-precomputed-artifacts.md#spec-authoring-precomputed-generation The viewer renders compiled results and implements no derived ledger, basis closure, generation attempt, compile freshness matrix, publication path invariant, or execution-budget boundary.
 * @evidenceExclude specifications/authoring-and-authority/deterministic-precomputed-artifacts.md#spec-authoring-precomputed-manifest The viewer renders compiled results and implements no derived ledger, basis closure, generation attempt, compile freshness matrix, publication path invariant, or execution-budget boundary.
 * @evidenceExclude specifications/authoring-and-authority/deterministic-precomputed-artifacts.md#spec-authoring-precomputed-portability The viewer renders compiled results and implements no derived ledger, basis closure, generation attempt, compile freshness matrix, publication path invariant, or execution-budget boundary.
 * @evidenceExclude specifications/authoring-and-authority/external-execution-and-provider-neutrality.md The viewer consumes compiled state; authoring authority, source lineage, reconciliation, and refusal remain outside this runtime.
 * @evidenceExclude specifications/authoring-and-authority/knowledge-evidence-and-tool-boundary.md The viewer consumes compiled state; authoring authority, source lineage, reconciliation, and refusal remain outside this runtime.
 * @evidenceExclude specifications/authoring-and-authority/partial-targets-and-atomic-results.md The viewer consumes compiled state; authoring authority, source lineage, reconciliation, and refusal remain outside this runtime.
 * @evidenceExclude specifications/authoring-and-authority/prototype-determinism-and-fidelity.md The viewer consumes compiled state; authoring authority, source lineage, reconciliation, and refusal remain outside this runtime.
 * @evidenceExclude specifications/authoring-and-authority/README.md The viewer consumes compiled state; authoring authority, source lineage, reconciliation, and refusal remain outside this runtime.
 * @evidenceExclude specifications/authoring-and-authority/source-authority-and-derivation.md The viewer consumes compiled state; authoring authority, source lineage, reconciliation, and refusal remain outside this runtime.
 * @evidenceExclude specifications/evidence-and-provenance/canonical-digests-and-content-identity.md The viewer renders compiled state; evidence policy, provenance lineage, audit retention, and adjudication remain outside this projection layer.
 * @evidenceExclude specifications/evidence-and-provenance/chain-of-custody-and-tamper-detection.md The viewer renders compiled state; evidence policy, provenance lineage, audit retention, and adjudication remain outside this projection layer.
 * @evidenceExclude specifications/evidence-and-provenance/completeness-freshness-and-refusal.md The viewer renders compiled state; evidence policy, provenance lineage, audit retention, and adjudication remain outside this projection layer.
 * @evidenceExclude specifications/evidence-and-provenance/entities-activities-agents-and-lineage.md The viewer renders compiled state; evidence policy, provenance lineage, audit retention, and adjudication remain outside this projection layer.
 * @evidenceExclude specifications/evidence-and-provenance/generation-transformation-and-derivation.md The viewer renders compiled state; evidence policy, provenance lineage, audit retention, and adjudication remain outside this projection layer.
 * @evidenceExclude specifications/evidence-and-provenance/observations-claims-and-human-judgments.md The viewer renders compiled state; evidence policy, provenance lineage, audit retention, and adjudication remain outside this projection layer.
 * @evidenceExclude specifications/evidence-and-provenance/privacy-credentials-and-disclosure.md The viewer renders compiled state; evidence policy, provenance lineage, audit retention, and adjudication remain outside this projection layer.
 * @evidenceExclude specifications/evidence-and-provenance/README.md The viewer renders compiled state; evidence policy, provenance lineage, audit retention, and adjudication remain outside this projection layer.
 * @evidenceExclude specifications/evidence-and-provenance/retention-invalidation-and-disposal.md The viewer renders compiled state; evidence policy, provenance lineage, audit retention, and adjudication remain outside this projection layer.
 * @evidenceExclude specifications/evidence-and-provenance/scope-identity-and-status.md The viewer renders compiled state; evidence policy, provenance lineage, audit retention, and adjudication remain outside this projection layer.
 * @evidenceExclude specifications/evidence-and-provenance/third-party-sources-rights-and-attribution.md The viewer renders compiled state; evidence policy, provenance lineage, audit retention, and adjudication remain outside this projection layer.
 * @evidenceExclude specifications/production-evidence/README.md The viewer starts after authoring admission and does not implement evidence stages, graph construction, or project-tree validation.
 * @evidenceExclude specifications/production-evidence/graph.md The viewer starts after authoring admission and does not implement evidence stages, graph construction, or project-tree validation.
 * @evidenceExclude specifications/production-evidence/native-input.md#spec-authoring-production-evidence-native-boundary The evidence adapter projects evaluator inputs before visualization; viewer mounting preserves no graph declaration or local ownership metadata.
 * @evidenceExclude specifications/production-evidence/input.md The viewer starts after authoring admission and does not implement evidence stages, graph construction, or project-tree validation.
 * @evidenceExclude requirements/agent-authoring/production-language.md#agent-production-language-contract The viewer mounts already-compiled scene data for playback; the production language module, contract baseline and migration, contract discriminators and delivery index are generated-project authoring contracts owned by the evidence and template packages.
 * @evidenceExclude requirements/production-evidence/authoring-contracts.md#agent-production-evidence-contract-discriminators The viewer mounts already-compiled scene data for playback; the production language module, contract baseline and migration, contract discriminators and delivery index are generated-project authoring contracts owned by the evidence and template packages.
 * @evidenceExclude specifications/authoring-and-authority/production-language.md#spec-authoring-production-language-module The viewer mounts already-compiled scene data for playback; the production language module, contract baseline and migration, contract discriminators and delivery index are generated-project authoring contracts owned by the evidence and template packages.
 * @evidenceExclude specifications/production-evidence/authoring-contracts.md#spec-authoring-production-evidence-contract-discriminators The viewer mounts already-compiled scene data for playback; the production language module, contract baseline and migration, contract discriminators and delivery index are generated-project authoring contracts owned by the evidence and template packages.
 * @evidenceExclude requirements/agent-authoring/reference-navigation.md#agent-reference-selection The viewer displays compiled scene inputs; it neither serves authored-Markdown reference requests nor launches repository sandboxes.
 * @evidenceExclude requirements/agent-authoring/reference-navigation.md#agent-reference-source The viewer displays compiled scene inputs; it neither serves authored-Markdown reference requests nor launches repository sandboxes.
 * @evidenceExclude requirements/agent-authoring/reference-navigation.md#agent-reference-bounds The viewer displays compiled scene inputs; it neither serves authored-Markdown reference requests nor launches repository sandboxes.
 * @evidenceExclude requirements/agent-authoring/reference-navigation.md#agent-reference-isolation The viewer displays compiled scene inputs; it neither serves authored-Markdown reference requests nor launches repository sandboxes.
 * @evidenceExclude requirements/agent-authoring/reference-navigation.md#agent-reference-transports The viewer displays compiled scene inputs; it neither serves authored-Markdown reference requests nor launches repository sandboxes.
 * @evidenceExclude specifications/authoring-and-authority/reference-navigation.md#spec-reference-selection The viewer displays compiled scene inputs; it neither serves authored-Markdown reference requests nor launches repository sandboxes.
 * @evidenceExclude specifications/authoring-and-authority/reference-navigation.md#spec-reference-source The viewer displays compiled scene inputs; it neither serves authored-Markdown reference requests nor launches repository sandboxes.
 * @evidenceExclude specifications/authoring-and-authority/reference-navigation.md#spec-reference-bounds The viewer displays compiled scene inputs; it neither serves authored-Markdown reference requests nor launches repository sandboxes.
 * @evidenceExclude specifications/authoring-and-authority/reference-navigation.md#spec-reference-isolation The viewer displays compiled scene inputs; it neither serves authored-Markdown reference requests nor launches repository sandboxes.
 * @evidenceExclude specifications/authoring-and-authority/reference-navigation.md#spec-reference-transports The viewer displays compiled scene inputs; it neither serves authored-Markdown reference requests nor launches repository sandboxes.
 */
export type AutoMovieViewerAuthoringEvidenceExclusions = never;
