/**
 * Viewer package boundaries for camera, lighting, rendering and delivery.
 *
 * The package's lint.config.ts selects this declaration as an exclusion
 * carrier within its complete public-source population. It has no runtime
 * state and is not re-exported by the package barrel. Each declared
 * target/reason pair below owns one intentional negative relationship;
 * requirement and specification boundaries for this domain stay together.
 * Positive implementation citations remain on the actual public exports.
 * An exclusion neither implements a feature nor approves a rendered asset.
 * Add a boundary at its semantic owner and retain native graph validation.
 *
 * @evidenceExclude requirements/camera/axis-eyeline-and-screen-direction.md The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/clipping-occlusion-and-spatial-constraints.md#camera-clearance The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/clipping-occlusion-and-spatial-constraints.md#camera-dynamic-spatial-sampling The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/clipping-occlusion-and-spatial-constraints.md#camera-intended-obstruction The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/clipping-occlusion-and-spatial-constraints.md#camera-obstruction-contract The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/clipping-occlusion-and-spatial-constraints.md#camera-occlusion-metric The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/clipping-occlusion-and-spatial-constraints.md#camera-spatial-alternatives The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/clipping-occlusion-and-spatial-constraints.md#camera-spatial-geometry-revision The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/continuity-and-intentional-violations.md The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/framing-and-shot-size.md#camera-framing-source-trace The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/framing-and-shot-size.md#camera-landmark-framing The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/framing-and-shot-size.md#camera-headroom-lead-room The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/framing-and-shot-size.md#camera-multi-subject-composition The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/framing-and-shot-size.md#camera-framing-range The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/framing-and-shot-size.md#camera-intentional-crop The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/position-and-movement.md The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/projection-lens-and-sensor.md#camera-aperture-distinction The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/projection-lens-and-sensor.md#camera-gate-offset The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/projection-lens-and-sensor.md#camera-lens-character The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/projection-lens-and-sensor.md#camera-optical-conventions The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/projection-lens-and-sensor.md#camera-optical-refusal The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/projection-lens-and-sensor.md#camera-orthographic-scale The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/projection-lens-and-sensor.md#camera-projection-time-sampling The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/projection-lens-and-sensor.md#camera-sensor-gate-fit The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/README.md The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/scope-and-identity.md The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/shutter-exposure-and-sampling.md The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/targets-focus-and-depth-boundary.md The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/camera/validation.md The viewer applies resolved camera state; camera authorship, analysis, and constraint refusal remain upstream.
 * @evidenceExclude requirements/delivery-and-accessibility/audio-description-and-alternatives.md The viewer projects frames; encoding, packaging, accessibility policy, and delivery acceptance remain in the render and publication lanes.
 * @evidenceExclude requirements/delivery-and-accessibility/audio-streams-and-channels.md The viewer projects frames; encoding, packaging, accessibility policy, and delivery acceptance remain in the render and publication lanes.
 * @evidenceExclude requirements/delivery-and-accessibility/captions-subtitles-and-cues.md The viewer projects frames; encoding, packaging, accessibility policy, and delivery acceptance remain in the render and publication lanes.
 * @evidenceExclude requirements/delivery-and-accessibility/containers-codecs-and-media-facts.md The viewer projects frames; encoding, packaging, accessibility policy, and delivery acceptance remain in the render and publication lanes.
 * @evidenceExclude requirements/delivery-and-accessibility/frame-rate-timebase-and-timecode.md The viewer projects frames; encoding, packaging, accessibility policy, and delivery acceptance remain in the render and publication lanes.
 * @evidenceExclude requirements/delivery-and-accessibility/integrity-provenance-and-authenticity.md The viewer projects frames; encoding, packaging, accessibility policy, and delivery acceptance remain in the render and publication lanes.
 * @evidenceExclude requirements/delivery-and-accessibility/localization-and-language-versions.md The viewer projects frames; encoding, packaging, accessibility policy, and delivery acceptance remain in the render and publication lanes.
 * @evidenceExclude requirements/delivery-and-accessibility/packages-manifests-and-dependencies.md The viewer projects frames; encoding, packaging, accessibility policy, and delivery acceptance remain in the render and publication lanes.
 * @evidenceExclude requirements/delivery-and-accessibility/picture-color-and-image-sequences.md The viewer projects frames; encoding, packaging, accessibility policy, and delivery acceptance remain in the render and publication lanes.
 * @evidenceExclude requirements/delivery-and-accessibility/publication-and-retention.md The viewer projects frames; encoding, packaging, accessibility policy, and delivery acceptance remain in the render and publication lanes.
 * @evidenceExclude requirements/delivery-and-accessibility/README.md The viewer projects frames; encoding, packaging, accessibility policy, and delivery acceptance remain in the render and publication lanes.
 * @evidenceExclude requirements/delivery-and-accessibility/scope-and-profiles.md The viewer projects frames; encoding, packaging, accessibility policy, and delivery acceptance remain in the render and publication lanes.
 * @evidenceExclude requirements/delivery-and-accessibility/validation.md The viewer projects frames; encoding, packaging, accessibility policy, and delivery acceptance remain in the render and publication lanes.
 * @evidenceExclude requirements/lighting/alternatives-and-intentional-deviations.md The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/analysis-and-visual-validation.md The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/budgets-and-representation.md The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/color-exposure-and-display-boundary.md#lighting-camera-exposure The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/color-exposure-and-display-boundary.md#lighting-color-comparison-boundary The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/color-exposure-and-display-boundary.md#lighting-color-provenance The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/color-exposure-and-display-boundary.md#lighting-color-refusal The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/color-exposure-and-display-boundary.md#lighting-single-effective-transform The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/color-exposure-and-display-boundary.md#lighting-white-balance-adaptation The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/practicals-and-local-lights.md The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/README.md The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/scope-and-identity.md The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/shadows-reflections-and-transmission.md#lighting-intentional-optical-break The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/shadows-reflections-and-transmission.md#lighting-optical-approximation The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/shadows-reflections-and-transmission.md#lighting-reflection-identity The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/shadows-reflections-and-transmission.md#lighting-result-findings The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/shadows-reflections-and-transmission.md#lighting-shadow-time-sampling The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/shadows-reflections-and-transmission.md#lighting-structural-passes The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/shadows-reflections-and-transmission.md#lighting-transparent-boundary The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/shape-filters-and-linking.md The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/sources-and-photometry.md#lighting-distance-falloff The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/sources-and-photometry.md#lighting-emitting-geometry The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/sources-and-photometry.md#lighting-intensity-basis The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/sources-and-photometry.md#lighting-photometric-quantity-semantics The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/sources-and-photometry.md#lighting-profile-provenance The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/sources-and-photometry.md#lighting-source-color-temperature The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/sources-and-photometry.md#lighting-source-refusal The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/sun-sky-and-environment.md#lighting-declared-sun The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/sun-sky-and-environment.md#lighting-environment-alternatives The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/sun-sky-and-environment.md#lighting-environment-background-illumination The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/sun-sky-and-environment.md#lighting-environment-claim-boundary The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/sun-sky-and-environment.md#lighting-environment-geometry-trace The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/sun-sky-and-environment.md#lighting-environment-spatial-variation The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/lighting/temporal-state-and-continuity.md The viewer applies resolved lights; lighting authorship, analysis, safety policy, and validation remain upstream.
 * @evidenceExclude requirements/rendering/budgets.md#rendering-budget-decision The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/budgets.md#rendering-budget-refusal The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/budgets.md#rendering-budget-tiers The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/budgets.md#rendering-expansion-bounds The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/budgets.md#rendering-geometry-memory-budget The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/budgets.md#rendering-runtime-budget-enforcement The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/chunks-resume-and-recovery.md The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/encoding-and-multiplexing.md The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/frame-identity-and-content-addressing.md The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/frame-schedules-and-sampling.md#rendering-frame-boundary-convention The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/frame-schedules-and-sampling.md#rendering-frame-number-time The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/frame-schedules-and-sampling.md#rendering-schedule-audio-cues The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/frame-schedules-and-sampling.md#rendering-schedule-refusal The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/frame-schedules-and-sampling.md#rendering-shutter-samples The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/frame-schedules-and-sampling.md#rendering-subrange-stability The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/geometry-visibility-and-culling.md#rendering-culling-diagnostics The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/geometry-visibility-and-culling.md#rendering-culling-refusal The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/geometry-visibility-and-culling.md#rendering-deformed-bounds The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/geometry-visibility-and-culling.md#rendering-frustum-boundaries The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/geometry-visibility-and-culling.md#rendering-room-region-culling The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/geometry-visibility-and-culling.md#rendering-visibility-state The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/headless-and-platform-determinism.md The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/materials-lighting-and-color.md#rendering-color-recovery The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/materials-lighting-and-color.md#rendering-external-materials The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/materials-lighting-and-color.md#rendering-lighting-evaluation The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/materials-lighting-and-color.md#rendering-material-refusal The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/materials-lighting-and-color.md#rendering-texture-decode The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/materials-lighting-and-color.md#rendering-transparency-alpha The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/passes-channels-and-products.md#rendering-partial-product-set The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/passes-channels-and-products.md#rendering-pass-dependencies The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/passes-channels-and-products.md#rendering-pass-refusal The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/README.md The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/scene-lowering-and-runtime-state.md#rendering-lowering-partial-retry The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/scene-lowering-and-runtime-state.md#rendering-lowering-refusal The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/scene-lowering-and-runtime-state.md#rendering-runtime-build-order The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/scene-lowering-and-runtime-state.md#rendering-runtime-time-update The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/scope-and-artifact-identity.md The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/rendering/validation.md The viewer owns interactive projection only; render scheduling, headless capture policy, encoding, packaging, and publication remain in the render lane.
 * @evidenceExclude requirements/repaint/eligibility-and-prerequisites.md The viewer produces deterministic structural frames; repaint providers, generation policy, retries, selection, and publication remain outside this package.
 * @evidenceExclude requirements/repaint/identity-and-provenance.md The viewer produces deterministic structural frames; repaint providers, generation policy, retries, selection, and publication remain outside this package.
 * @evidenceExclude requirements/repaint/prompts-controls-and-constraints.md The viewer produces deterministic structural frames; repaint providers, generation policy, retries, selection, and publication remain outside this package.
 * @evidenceExclude requirements/repaint/providers-models-and-credentials.md The viewer produces deterministic structural frames; repaint providers, generation policy, retries, selection, and publication remain outside this package.
 * @evidenceExclude requirements/repaint/README.md The viewer produces deterministic structural frames; repaint providers, generation policy, retries, selection, and publication remain outside this package.
 * @evidenceExclude requirements/repaint/retries-seeds-and-variation.md The viewer produces deterministic structural frames; repaint providers, generation policy, retries, selection, and publication remain outside this package.
 * @evidenceExclude requirements/repaint/scope-and-user-choice.md The viewer produces deterministic structural frames; repaint providers, generation policy, retries, selection, and publication remain outside this package.
 * @evidenceExclude requirements/repaint/sequence-continuity-and-publication.md The viewer produces deterministic structural frames; repaint providers, generation policy, retries, selection, and publication remain outside this package.
 * @evidenceExclude requirements/repaint/source-frames-and-reference-locking.md The viewer produces deterministic structural frames; repaint providers, generation policy, retries, selection, and publication remain outside this package.
 * @evidenceExclude requirements/repaint/structural-comparison-and-review.md The viewer produces deterministic structural frames; repaint providers, generation policy, retries, selection, and publication remain outside this package.
 * @evidenceExclude specifications/camera-light-and-visibility/alternatives-deviations-and-evidence.md The viewer applies resolved camera, light, and visibility state; authoring, analysis, and constraint refusal remain upstream.
 * @evidenceExclude specifications/camera-light-and-visibility/camera-state-projection-and-gate.md#clv-camera-authority-spatial-binding The viewer applies resolved camera, light, and visibility state; authoring, analysis, and constraint refusal remain upstream.
 * @evidenceExclude specifications/camera-light-and-visibility/camera-state-projection-and-gate.md#clv-projection-sampling-refusal The viewer applies resolved camera, light, and visibility state; authoring, analysis, and constraint refusal remain upstream.
 * @evidenceExclude specifications/camera-light-and-visibility/camera-state-projection-and-gate.md#clv-sensor-gate-delivery-mapping The viewer applies resolved camera, light, and visibility state; authoring, analysis, and constraint refusal remain upstream.
 * @evidenceExclude specifications/camera-light-and-visibility/framing-axis-and-camera-path.md The viewer applies resolved camera, light, and visibility state; authoring, analysis, and constraint refusal remain upstream.
 * @evidenceExclude specifications/camera-light-and-visibility/light-source-photometry-and-environment.md#clv-light-authority-branches The viewer applies resolved camera, light, and visibility state; authoring, analysis, and constraint refusal remain upstream.
 * @evidenceExclude specifications/camera-light-and-visibility/light-transport-color-and-budget.md#clv-color-comparison-refusal The viewer applies resolved camera, light, and visibility state; authoring, analysis, and constraint refusal remain upstream.
 * @evidenceExclude specifications/camera-light-and-visibility/light-transport-color-and-budget.md#clv-light-budget-report-refusal The viewer applies resolved camera, light, and visibility state; authoring, analysis, and constraint refusal remain upstream.
 * @evidenceExclude specifications/camera-light-and-visibility/light-transport-color-and-budget.md#clv-light-budget-selection The viewer applies resolved camera, light, and visibility state; authoring, analysis, and constraint refusal remain upstream.
 * @evidenceExclude specifications/camera-light-and-visibility/light-transport-color-and-budget.md#clv-light-result-passes-findings The viewer applies resolved camera, light, and visibility state; authoring, analysis, and constraint refusal remain upstream.
 * @evidenceExclude specifications/camera-light-and-visibility/light-transport-color-and-budget.md#clv-reflection-transmission-approximation The viewer applies resolved camera, light, and visibility state; authoring, analysis, and constraint refusal remain upstream.
 * @evidenceExclude specifications/camera-light-and-visibility/practical-shaping-and-linking.md The viewer applies resolved camera, light, and visibility state; authoring, analysis, and constraint refusal remain upstream.
 * @evidenceExclude specifications/camera-light-and-visibility/README.md The viewer applies resolved camera, light, and visibility state; authoring, analysis, and constraint refusal remain upstream.
 * @evidenceExclude specifications/camera-light-and-visibility/target-focus-exposure-and-sampling.md The viewer applies resolved camera, light, and visibility state; authoring, analysis, and constraint refusal remain upstream.
 * @evidenceExclude specifications/camera-light-and-visibility/temporal-state-and-continuity.md The viewer applies resolved camera, light, and visibility state; authoring, analysis, and constraint refusal remain upstream.
 * @evidenceExclude specifications/camera-light-and-visibility/visibility-and-image-space-observation.md#clv-computable-geometry-results The viewer applies resolved camera, light, and visibility state; authoring, analysis, and constraint refusal remain upstream.
 * @evidenceExclude specifications/camera-light-and-visibility/visibility-and-image-space-observation.md#clv-intended-obstruction-unreadability The viewer applies resolved camera, light, and visibility state; authoring, analysis, and constraint refusal remain upstream.
 * @evidenceExclude specifications/camera-light-and-visibility/visibility-and-image-space-observation.md#clv-observation-validation-cases The viewer applies resolved camera, light, and visibility state; authoring, analysis, and constraint refusal remain upstream.
 * @evidenceExclude specifications/camera-light-and-visibility/visibility-and-image-space-observation.md#clv-occlusion-image-metrics The viewer applies resolved camera, light, and visibility state; authoring, analysis, and constraint refusal remain upstream.
 * @evidenceExclude specifications/camera-light-and-visibility/visibility-and-image-space-observation.md#clv-rational-visibility-sampling The viewer applies resolved camera, light, and visibility state; authoring, analysis, and constraint refusal remain upstream.
 * @evidenceExclude specifications/editorial-render-and-delivery/delivery-audio-text-and-localization.md The viewer projects resolved frames; editorial planning, render scheduling, encoding, packaging, and delivery authority remain outside it.
 * @evidenceExclude specifications/editorial-render-and-delivery/delivery-package-provenance-and-publication.md The viewer projects resolved frames; editorial planning, render scheduling, encoding, packaging, and delivery authority remain outside it.
 * @evidenceExclude specifications/editorial-render-and-delivery/delivery-profiles-time-and-picture.md The viewer projects resolved frames; editorial planning, render scheduling, encoding, packaging, and delivery authority remain outside it.
 * @evidenceExclude specifications/editorial-render-and-delivery/delivery-validation-and-release-status.md The viewer projects resolved frames; editorial planning, render scheduling, encoding, packaging, and delivery authority remain outside it.
 * @evidenceExclude specifications/editorial-render-and-delivery/editorial-audiovisual-continuity.md The viewer projects resolved frames; editorial planning, render scheduling, encoding, packaging, and delivery authority remain outside it.
 * @evidenceExclude specifications/editorial-render-and-delivery/editorial-version-conform-and-validation.md The viewer projects resolved frames; editorial planning, render scheduling, encoding, packaging, and delivery authority remain outside it.
 * @evidenceExclude specifications/editorial-render-and-delivery/rational-timeline-and-composition.md The viewer projects resolved frames; editorial planning, render scheduling, encoding, packaging, and delivery authority remain outside it.
 * @evidenceExclude specifications/editorial-render-and-delivery/README.md The viewer projects resolved frames; editorial planning, render scheduling, encoding, packaging, and delivery authority remain outside it.
 * @evidenceExclude specifications/editorial-render-and-delivery/render-budget-identity-and-recovery.md#spec-render-chunk-recovery The viewer projects resolved frames; editorial planning, render scheduling, encoding, packaging, and delivery authority remain outside it.
 * @evidenceExclude specifications/editorial-render-and-delivery/render-budget-identity-and-recovery.md#spec-render-frame-identity The viewer projects resolved frames; editorial planning, render scheduling, encoding, packaging, and delivery authority remain outside it.
 * @evidenceExclude specifications/editorial-render-and-delivery/render-budget-identity-and-recovery.md#spec-render-raster-admission-bound The viewer applies an admitted canvas size but does not compute or enforce the production raster pixel limit.
 * @evidenceExclude specifications/editorial-render-and-delivery/render-budget-identity-and-recovery.md#spec-render-target-dependency-fingerprint The viewer draws supplied runtime state and does not construct the target dependency closure used for render identity.
 * @evidenceExclude specifications/editorial-render-and-delivery/render-budget-identity-and-recovery.md#spec-render-target-fingerprint-protocol The viewer draws supplied runtime state and does not define or encode the versioned target fingerprint protocol.
 * @evidenceExclude specifications/editorial-render-and-delivery/render-encoding-and-validation.md The viewer projects resolved frames; editorial planning, render scheduling, encoding, packaging, and delivery authority remain outside it.
 * @evidenceExclude specifications/editorial-render-and-delivery/render-schedule-state-and-headless.md#spec-render-artifact-lifecycle The viewer projects resolved frames; editorial planning, render scheduling, encoding, packaging, and delivery authority remain outside it.
 * @evidenceExclude specifications/editorial-render-and-delivery/render-schedule-state-and-headless.md#spec-render-capture-runtime-identity The viewer owns a renderer lifecycle but does not canonicalize or record the browser, executable, platform, graphics, and capture-mode identity.
 * @evidenceExclude specifications/editorial-render-and-delivery/render-schedule-state-and-headless.md#spec-render-headless-platform The viewer projects resolved frames; editorial planning, render scheduling, encoding, packaging, and delivery authority remain outside it.
 */
export type AutoMovieViewerRenderingEvidenceExclusions = never;
