import { measureAutoMovieModelCrossings } from "@automovie/engine";
import {
  type IAutoMovieHumanFaceBasis,
  createHumanFaceBasisBuilder,
  exportHumanFace,
  parseHumanFaceBasisDocument,
  summarizeHumanFaceArticulation,
} from "@automovie/human";

/**
 * Prepare reusable numerical resources for one connected face worker.
 * Both preview and export evaluate the same compact document. Preview returns
 * the resident model directly; only an explicit export constructs a GLB.
 * Pigmentation and scalp hair are generated by the numerical document builder.
 * Both operations consume the same fields and shared basis correspondence. A
 * preview also states the joint motion the document asked for, read through
 * the same articulation the builder posed, so the editor prints degrees and
 * millimetres beside the optional crossing census.
 *
 * @evidence requirements/actors/facial-authoring/contract.md#actor-face-editor-state Preserves one admitted document's geometry across preview and export.
 * @evidence specifications/asset-and-representation/facial-authoring/contract.md#face-spec-editor Separates numerical evaluation from file encoding in a resident worker.
 */
export function createConnectedFaceRuntime(props: {
  basis: IAutoMovieHumanFaceBasis;
}) {
  const evaluate = createHumanFaceBasisBuilder(props.basis);
  return async (request: {
    document: string;
    operation: "preview" | "export";
    measure?: boolean;
  }) => {
    const document = parseHumanFaceBasisDocument(request.document);
    const model = evaluate(document);
    if (request.operation === "export") {
      const { glb } = await exportHumanFace(model);
      return { operation: "export" as const, glb };
    }
    return {
      operation: "preview" as const,
      model,
      articulation: summarizeHumanFaceArticulation(props.basis, document),
      crossings:
        request.measure === true ? measureAutoMovieModelCrossings(model) : null,
    };
  };
}

/** Numerical requests admitted by the connected runtime. */
export type ConnectedFaceRequest = Parameters<
  ReturnType<typeof createConnectedFaceRuntime>
>[0];

/** File bytes and resident previews are distinct reply alternatives. */
export type ConnectedFaceResult = Awaited<
  ReturnType<ReturnType<typeof createConnectedFaceRuntime>>
>;
