/**
 * The body editor's worker transports Float32 preview buffers independently of
 * GLB export. The worker owns the compiled basis and source model; transferred
 * arrays belong to one reply and the page may retain only the displayed frame.
 */
import type { IAutoMovieModelCrossing } from "@automovie/engine";
import type { IAutoMovieHumanBodyShoulderPose } from "@automovie/human";
import type {
  IAutoMovieJointPose,
  IAutoMovieModel,
  IAutoMovieModelPart,
} from "@automovie/interface";

/**
 * Mesh attributes at the preview and GLB Float32 precision boundary.
 * @evidence requirements/actors/body-authoring/contract.md#actor-body-editor Carries the numerical surface shown by the connected body editor.
 * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor-view Supplies directly drawable Float32 body geometry to the preview.
 */
export type ConnectedBodyMesh = {
  /** Metre positions, three scalars per vertex.
   * @evidence requirements/actors/body-authoring/contract.md#actor-body-editor Displays the admitted body shape.
   * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor-view Transfers the body positions at display precision.
   */
  positions: Float32Array<ArrayBuffer>;
  /** Unit directions or null if generated by the viewer.
   * @evidence requirements/actors/body-authoring/contract.md#actor-body-editor Shows the body's surface under the chosen material and light.
   * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor-view Carries preview normals alongside positions.
   */
  normals: Float32Array<ArrayBuffer> | null;
  /** glTF UV0 coordinates.
   * @evidence requirements/actors/body-authoring/contract.md#actor-body-editor Displays the body's resident material map.
   * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor-view Keeps UV0 aligned with the preview surface.
   */
  uvs: Float32Array<ArrayBuffer> | null;
  /** Linear RGB multipliers.
   * @evidence requirements/actors/body-authoring/contract.md#actor-body-editor Displays authored vertex color where the body has it.
   * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor-view Carries the optional resident color attribute.
   */
  colors?: Float32Array<ArrayBuffer>;
  /** Triangle vertex references.
   * @evidence requirements/actors/body-authoring/contract.md#actor-body-editor Displays the connected skin triangles.
   * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor-view Carries indexed preview topology.
   */
  indices: Uint32Array<ArrayBuffer>;
  /** Already posed, so the viewer must not attempt skin binding.
   * @evidence requirements/actors/body-authoring/contract.md#actor-body-editor Shows the committed posed body as static geometry.
   * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor-view Prevents the display layer from skinning an already posed surface.
   */
  skin: null;
};
/** Static model part whose geometry travels in transferable buffers.
 * @evidence requirements/actors/body-authoring/contract.md#actor-body-editor Shows the committed body regions together.
 * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor-view Keeps each resident region's geometry paired with its material binding.
 */
export type ConnectedBodyPart = Omit<IAutoMovieModelPart, "geometry"> & {
  /** Prepared static mesh. */
  geometry: { type: "mesh"; mesh: ConnectedBodyMesh };
};
/** Portable model metadata paired with transferable part geometry.
 * @evidence requirements/actors/body-authoring/contract.md#actor-body-editor Keeps the full body visible as one committed preview.
 * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor-view Carries all region buffers and finishes in one preview transaction.
 */
export type ConnectedBodyModel = Omit<IAutoMovieModel, "parts"> & {
  /** Draw-order parts, each with its own transfer ownership. */
  parts: ConnectedBodyPart[];
};
/** A preview computes buffers; an export computes a file.
 * @evidence requirements/actors/body-authoring/contract.md#actor-body-editor Requests the body's numerical preview independently of file encoding.
 * @evidence requirements/actors/body-authoring/contract.md#actor-body-export Requests a static file only on explicit export.
 * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor Separates preview transactions from file requests.
 * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-export Sends the committed document to the static exporter.
 */
export type ConnectedBodyRequest =
  | { operation: "preview"; document: string; measure: boolean }
  | { operation: "export"; document: string }
  | { operation: "armsDown"; document: string };
/** The matching result for one worker request.
 * @evidence requirements/actors/body-authoring/contract.md#actor-body-editor Returns numerical preview buffers for publication.
 * @evidence requirements/actors/body-authoring/contract.md#actor-body-export Returns portable GLB bytes when requested.
 * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor Correlates preview output with the worker request.
 * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-export Carries encoded output separately from display geometry.
 */
export type ConnectedBodyResult =
  | {
      operation: "preview";
      model: ConnectedBodyModel;
      crossings: IAutoMovieModelCrossing[] | null;
      extras: Record<string, unknown>;
    }
  | { operation: "export"; glb: Uint8Array<ArrayBuffer> }
  | {
      operation: "armsDown";
      pose: IAutoMovieJointPose[];
      shoulders: IAutoMovieHumanBodyShoulderPose[];
    };

/** Transfer exactly the buffers owned by this reply, never basis memory.
 * @evidence requirements/actors/body-authoring/contract.md#actor-body-editor Delivers preview geometry without copying the compiled basis.
 * @evidence requirements/actors/body-authoring/contract.md#actor-body-export Delivers requested GLB bytes without encoding during preview.
 * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor Transfers each preview's numerical buffers to its transaction.
 * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-export Transfers only the explicit export's binary file.
 */
export function connectedBodyTransfers(
  result: ConnectedBodyResult,
): ArrayBuffer[] {
  if (result.operation === "export") return [result.glb.buffer];
  if (result.operation === "armsDown") return [];
  const buffers: ArrayBuffer[] = [];
  for (const part of result.model.parts) {
    const mesh = part.geometry.mesh;
    buffers.push(mesh.positions.buffer, mesh.indices.buffer);
    if (mesh.normals !== null) buffers.push(mesh.normals.buffer);
    if (mesh.uvs !== null) buffers.push(mesh.uvs.buffer);
    if (mesh.colors !== undefined) buffers.push(mesh.colors.buffer);
  }
  return buffers;
}
