/**
 * The body editor's worker transports Float32 preview buffers independently of
 * GLB export. The worker owns the compiled basis and source model; transferred
 * arrays belong to one reply and the page may retain only the displayed frame.
 */
import type { IAutoMovieModelCrossing } from "@automovie/engine";
import type {
  IAutoMovieModel,
  IAutoMovieModelPart,
} from "@automovie/interface";

/** Mesh attributes at the preview and GLB Float32 precision boundary. */
export type ConnectedBodyMesh = {
  /** Metre positions, three scalars per vertex. */
  positions: Float32Array<ArrayBuffer>;
  /** Unit directions or null if generated by the viewer. */
  normals: Float32Array<ArrayBuffer> | null;
  /** glTF UV0 coordinates. */
  uvs: Float32Array<ArrayBuffer> | null;
  /** Linear RGB multipliers. */
  colors?: Float32Array<ArrayBuffer>;
  /** Triangle vertex references. */
  indices: Uint32Array<ArrayBuffer>;
  /** Already posed, so the viewer must not attempt skin binding. */
  skin: null;
};
/** Static model part whose geometry travels in transferable buffers. */
export type ConnectedBodyPart = Omit<IAutoMovieModelPart, "geometry"> & {
  /** Prepared static mesh. */
  geometry: { type: "mesh"; mesh: ConnectedBodyMesh };
};
/** Portable model metadata paired with transferable part geometry. */
export type ConnectedBodyModel = Omit<IAutoMovieModel, "parts"> & {
  /** Draw-order parts, each with its own transfer ownership. */
  parts: ConnectedBodyPart[];
};
/** A preview computes buffers; an export computes a file. */
export type ConnectedBodyRequest =
  | { operation: "preview"; document: string; measure: boolean }
  | { operation: "export"; document: string };
/** The matching result for one worker request. */
export type ConnectedBodyResult =
  | {
      operation: "preview";
      model: ConnectedBodyModel;
      crossings: IAutoMovieModelCrossing[] | null;
      extras: Record<string, unknown>;
    }
  | { operation: "export"; glb: Uint8Array<ArrayBuffer> };

/** Transfer exactly the buffers owned by this reply, never basis memory. */
export function connectedBodyTransfers(
  result: ConnectedBodyResult,
): ArrayBuffer[] {
  if (result.operation === "export") return [result.glb.buffer];
  const buffers: ArrayBuffer[] = [];
  for (const part of result.model.parts) {
    const mesh = part.geometry.mesh;
    buffers.push(mesh.positions.buffer, mesh.indices.buffer);
    if (mesh.normals !== null) buffers.push(mesh.normals.buffer);
    if (mesh.uvs !== null) buffers.push(mesh.uvs.buffer);
    if (mesh.colors !== undefined) buffers.push(mesh.colors.buffer);
  }
  return buffers;
}
