import { AutoMovieContentDigest } from "./AutoMovieContentDigest";
import { IAutoMovieProductionLipSyncJoin } from "./IAutoMovieProductionLipSyncJoin";
import { IAutoMovieProductionPhonemeChunk } from "./IAutoMovieProductionPhonemeChunk";
import { IAutoMovieProductionViseme } from "./IAutoMovieProductionViseme";

/**
 * Content-addressed receipt for one locally synthesized Kokoro line.
 *
 * @evidence requirements/sound/editing-synchronization-and-continuity.md#sound-event-synchronization Exposes `IAutoMovieProductionTtsReceipt` as the portable data boundary for the sound event synchronization requirement.
 * @evidence specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-event-sync-and-boundary-continuity Types `IAutoMovieProductionTtsReceipt` for the sound event sync and boundary continuity system contract.
 */
export interface IAutoMovieProductionTtsReceipt {
  /**
   * Receipt schema.
   *
   * @evidence requirements/sound/editing-synchronization-and-continuity.md#sound-event-synchronization Exposes `version` as the portable data boundary for the sound event synchronization requirement.
   * @evidence specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-event-sync-and-boundary-continuity Types `version` for the sound event sync and boundary continuity system contract.
   */
  version: 6;
  /**
   * Exact dialogue line id.
   *
   * @evidence requirements/sound/editing-synchronization-and-continuity.md#sound-event-synchronization Exposes `line` as the portable data boundary for the sound event synchronization requirement.
   * @evidence specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-event-sync-and-boundary-continuity Types `line` for the sound event sync and boundary continuity system contract.
   */
  line: string;
  /**
   * Content address over text, voice, model, and inference arguments.
   *
   * @evidence requirements/sound/editing-synchronization-and-continuity.md#sound-event-synchronization Exposes `cacheKey` as the portable data boundary for the sound event synchronization requirement.
   * @evidence specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-event-sync-and-boundary-continuity Types `cacheKey` for the sound event sync and boundary continuity system contract.
   */
  cacheKey: AutoMovieContentDigest;
  /**
   * Local Kokoro model identity.
   *
   * @evidence requirements/sound/editing-synchronization-and-continuity.md#sound-event-synchronization Exposes `model` as the portable data boundary for the sound event synchronization requirement.
   * @evidence specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-event-sync-and-boundary-continuity Types `model` for the sound event sync and boundary continuity system contract.
   */
  model: "onnx-community/Kokoro-82M-v1.0-ONNX";
  /**
   * Immutable Hugging Face model revision.
   *
   * @evidence requirements/sound/editing-synchronization-and-continuity.md#sound-event-synchronization Exposes `modelRevision` as the portable data boundary for the sound event synchronization requirement.
   * @evidence specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-event-sync-and-boundary-continuity Types `modelRevision` for the sound event sync and boundary continuity system contract.
   */
  modelRevision: "1939ad2a8e416c0acfeecc08a694d14ef25f2231";
  /**
   * Kokoro voice identity.
   *
   * @evidence requirements/sound/editing-synchronization-and-continuity.md#sound-event-synchronization Exposes `voice` as the portable data boundary for the sound event synchronization requirement.
   * @evidence specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-event-sync-and-boundary-continuity Types `voice` for the sound event sync and boundary continuity system contract.
   */
  voice: string;
  /**
   * Generator cost basis and consumer retained with the generated bytes.
   *
   * The record accompanies the exact runtime and synthesized line.
   *
   * @evidence requirements/sound/editing-synchronization-and-continuity.md#sound-event-synchronization Carries the generator adoption facts with the exact synthesized line rather than leaving them outside the synchronized receipt.
   * @evidence specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-event-sync-and-boundary-continuity Keeps the adopted generator context on the portable line receipt consumed across the sound-picture join.
   */
  generatorProvenance: {
    /** Optional descriptive source location. */
    source?: string;
    /** Optional descriptive license metadata. */
    license?: string;
    /** Optional descriptive date metadata. */
    termsCheckedAt?: string;
    /** Authored cost basis, including an explicit local-compute basis. */
    cost: string;
    /** Typed production consumer and authored reason for this adoption. */
    consumer: {
      /** Exact generated-content lane. */
      kind: "dialogue-synthesis";
      /** Why this production needs synthesized dialogue from this generator. */
      reason: string;
    };
  };
  /**
   * UTC instant captured immediately before the generator call that produced
   * this receipt's immutable PCM.
   *
   * @evidence specifications/simulation-effects-and-sound/scope-tiers-and-identities.md#external-result-provider-neutrality Retains the immutable generation instant with the adopted audio result.
   */
  generatedAt: string;
  /**
   * Model-native PCM clock before deterministic resampling.
   *
   * @evidence requirements/sound/editing-synchronization-and-continuity.md#sound-event-synchronization Exposes `sourceSampleRate` as the portable data boundary for the sound event synchronization requirement.
   * @evidence specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-event-sync-and-boundary-continuity Types `sourceSampleRate` for the sound event sync and boundary continuity system contract.
   */
  sourceSampleRate: number;
  /**
   * Exact cached mono source sample count.
   *
   * @evidence requirements/sound/editing-synchronization-and-continuity.md#sound-event-synchronization Exposes `sourceSamples` as the portable data boundary for the sound event synchronization requirement.
   * @evidence specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-event-sync-and-boundary-continuity Types `sourceSamples` for the sound event sync and boundary continuity system contract.
   */
  sourceSamples: number;
  /**
   * Digest of cached little-endian Float32 PCM bytes.
   *
   * @evidence requirements/sound/editing-synchronization-and-continuity.md#sound-event-synchronization Exposes `pcmDigest` as the portable data boundary for the sound event synchronization requirement.
   * @evidence specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-event-sync-and-boundary-continuity Types `pcmDigest` for the sound event sync and boundary continuity system contract.
   */
  pcmDigest: AutoMovieContentDigest;
  /**
   * Kokoro phoneme stream joined in synthesis order.
   *
   * @evidence requirements/sound/editing-synchronization-and-continuity.md#sound-event-synchronization Exposes `phonemes` as the portable data boundary for the sound event synchronization requirement.
   * @evidence specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-event-sync-and-boundary-continuity Types `phonemes` for the sound event sync and boundary continuity system contract.
   */
  phonemes: string;
  /**
   * Phoneme chunks on the exact model-native PCM clock.
   *
   * @evidence requirements/sound/editing-synchronization-and-continuity.md#sound-event-synchronization Exposes `phonemeChunks` as the portable data boundary for the sound event synchronization requirement.
   * @evidence specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-event-sync-and-boundary-continuity Types `phonemeChunks` for the sound event sync and boundary continuity system contract.
   */
  phonemeChunks: IAutoMovieProductionPhonemeChunk[];
  /**
   * Adapter, native backend, model-cache, and bundled-voice byte identity.
   *
   * @evidence requirements/sound/editing-synchronization-and-continuity.md#sound-event-synchronization Exposes `runtimeAssets` as the portable data boundary for the sound event synchronization requirement.
   * @evidence specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-event-sync-and-boundary-continuity Types `runtimeAssets` for the sound event sync and boundary continuity system contract.
   */
  runtimeAssets: Array<{
    /** Stable package or revision-cache-relative asset name. */
    path: string;
    /** Digest of the exact bytes consumed by synthesis. */
    digest: AutoMovieContentDigest;
  }>;
  /**
   * Mouth targets derived from the same chunk sample clock.
   *
   * @evidence requirements/sound/editing-synchronization-and-continuity.md#sound-event-synchronization Exposes `visemes` as the portable data boundary for the sound event synchronization requirement.
   * @evidence specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-event-sync-and-boundary-continuity Types `visemes` for the sound event sync and boundary continuity system contract.
   */
  visemes: IAutoMovieProductionViseme[];
  /**
   * Join from final-byte viseme timing to the authored speaking actor.
   *
   * Optional only for legacy receipts. New receipts record an available or
   * not-run outcome rather than silently dropping mouth motion.
   *
   * @evidence requirements/sound/dialogue-voice-and-visemes.md#sound-dialogue-final-bytes-authority Binds mouth timing to the same final bytes as audible dialogue.
   * @evidence specifications/simulation-effects-and-sound/sound-sources-events-dialogue-and-foley.md#dialogue-lipsync-join-and-seek Carries the deterministic actor join consumed before frame capture.
   *
   * @evidence requirements/sound/editing-synchronization-and-continuity.md#sound-event-synchronization Exposes `lipSync` as the portable data boundary for the sound event synchronization requirement.
   * @evidence specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-event-sync-and-boundary-continuity Types `lipSync` for the sound event sync and boundary continuity system contract.
   */
  lipSync?: IAutoMovieProductionLipSyncJoin;
}
