import type { IAutoMovieProductionEvidence } from "@automovie/evidence";
import type {
  IAutoMovieDiagnostic,
  IAutoMovieLibraryBuildContext,
  IAutoMovieModel,
} from "@automovie/interface";

import { admitAutoMovieLibraryContribution } from "./admitAutoMovieLibraryContribution";
import { admitAutoMovieLibrarySettingsContribution } from "./admitAutoMovieLibrarySettingsContribution";
import {
  digestAutoMovieBytes,
  normalizeAutoMovieSource,
} from "./contentIdentity";
import type { IAutoMovieMaterializedLibraryResult } from "./materializeProduction";
import { errorMessage } from "./productionBuildDiagnostics";
import type { buildLibrarySource } from "./productionSourceBuild";
import { resolveAutoMovieSourceOwnerBinding } from "./sourceOwnerBinding";

/**
 * Evaluate the acquired library source population and admit its contributions.
 *
 * The builder supplies the project reader, ordinary Node evaluator and engine
 * validators. This stage owns one attempt's registration and artifact identity
 * maps. It reads and normalizes each selected module before execution, binds
 * admission to those exact bytes and owner contexts, then preserves the first
 * registration at each address. A refused contribution still owns its claimed
 * identities so a later module cannot erase the failure by replacing it.
 *
 * Unreadable source becomes an attributed diagnostic and processing continues.
 * The evaluator has already shape-checked and admitted each returned owner;
 * therefore every registration resolves in the supplied context population.
 * Accepted results retain the source digest and contribution used by the later
 * publication stage. No generated bytes or persistent project state are written.
 *
 * @evidence requirements/agent-authoring/source-owned-loop.md#agent-source-result-link Binds each accepted library contribution to its acquired source bytes and exact authored owner without allowing a second registration to replace it.
 * @evidence specifications/authoring-and-authority/source-authority-and-derivation.md#spec-authoring-derivation-output-lineage Authenticates source owner edges before retaining their contribution and source digest for materialization.
 */
export const evaluateAutoMovieLibraryOwners = (props: {
  /** Project root whose ordinary evaluator loads the selected modules. */
  root: string;

  /** Canonically ordered source paths from the acquired authoring snapshot. */
  sources: readonly string[];

  /** Exact source-owner edges from that same snapshot. */
  bindings: IAutoMovieProductionEvidence["sourceOwners"];

  /** Validated owner addresses available during evaluation. */
  contexts: ReadonlyMap<string, IAutoMovieLibraryBuildContext>;

  /** Source binding branch selected for each context address. */
  sourceBranches: ReadonlyMap<string, string>;

  /** Completion gate choice used for source-edge admission. */
  requireReviewed: boolean;

  /** Reader from the same project handle that guards publication. */
  readSource: (source: string) => Uint8Array;

  /** Host evaluator that returns only shape-checked, admitted registrations. */
  evaluate: typeof buildLibrarySource;

  /** Domain validators shared with the builder's native compilation path. */
  validators: Parameters<
    typeof admitAutoMovieLibraryContribution
  >[0]["validators"];
}): {
  results: IAutoMovieMaterializedLibraryResult[];
  registeredBy: ReadonlyMap<string, string>;
  diagnostics: IAutoMovieDiagnostic[];
} => {
  const results: IAutoMovieMaterializedLibraryResult[] = [];
  const registeredBy = new Map<string, string>();
  const diagnostics: IAutoMovieDiagnostic[] = [];
  const environmentOwner = new Map<string, string>();
  const contextOwner = new Map<string, string>();
  const models = new Map<string, IAutoMovieModel>();
  const modelOwner = new Map<string, string>();
  for (const source of props.sources) {
    let text: string;
    try {
      text = Buffer.from(
        normalizeAutoMovieSource(props.readSource(source)),
      ).toString("utf8");
    } catch (error) {
      diagnostics.push({
        code: "source-path-missing",
        category: "error",
        phase: "source",
        target: `library-source:${source}`,
        path: source,
        message: `Library source "${source}" is selected by a reviewed source binding but cannot be read (${errorMessage(error)}). Restore the exact tracked file or correct the binding before compiling.`,
      });
      continue;
    }
    const sourceDigest = digestAutoMovieBytes(Buffer.from(text, "utf8"));
    const compiled = props.evaluate({
      path: source,
      source: text,
      sourceRoot: props.root,
      context: (design) => props.contexts.get(design) ?? null,
      admit: (exportName, design) =>
        resolveAutoMovieSourceOwnerBinding({
          bindings: props.bindings,
          branch: props.sourceBranches.get(design)!,
          sourcePath: source,
          exportName,
          owner: design,
          sourceDigest,
          requireReviewed: props.requireReviewed,
        }),
    });
    diagnostics.push(...compiled.diagnostics);
    for (const registration of compiled.registrations) {
      const context = props.contexts.get(registration.design)!;
      const target = `library:${context.branch}:${registration.design}`;
      const previous = registeredBy.get(registration.design);
      if (previous !== undefined) {
        diagnostics.push({
          code: "source-registration-mismatch",
          category: "error",
          phase: "source",
          target,
          path: source,
          message: `Library design owner "${registration.design}" is registered by both "${previous}" and "${source}#${registration.export}". Keep one source export per reviewed H2; two registrations make the published artifact depend on file order.`,
        });
        continue;
      }
      registeredBy.set(registration.design, `${source}#${registration.export}`);
      const accepted =
        context.branch === "productionSources"
          ? admitAutoMovieLibrarySettingsContribution({
              diagnostics,
              registration,
              source,
              target,
            })
          : admitAutoMovieLibraryContribution({
              diagnostics,
              contextOwner,
              environmentOwner,
              modelOwner,
              models,
              registration,
              source,
              target,
              validators: props.validators,
            });
      if (accepted === false) continue;
      results.push({
        branch: context.branch,
        owner: registration.design,
        source,
        export: registration.export,
        sourceDigest,
        contribution: registration.contribution,
      });
    }
  }
  return { results, registeredBy, diagnostics };
};
