import type { AutoMovieContentDigest, IAutoMovieDiagnostic, IAutoMovieGeneratedManifest } from "@automovie/interface";
import path from "node:path";

import type { AutoMovieProductionProject } from "./AutoMovieProductionProject";
import { canonicalAutoMovieJsonBytes, digestAutoMovieBytes } from "./contentIdentity";
import { generatedOwnershipDiagnosticMessage } from "./generatedOwnershipDiagnosticMessage";
import { normalizeSlash } from "./productionBuildDiagnostics";

/**
 * Compare resident generated ownership with the exact result derived now.
 *
 * Both timed and library builders use this policy before publication. The
 * project reader owns physical fencing and returns exact bytes; the host lists
 * the generated root, while this module owns stale, unowned, unsafe and changed
 * output diagnostics. It never writes. Only a matching prior owned output may
 * be retired automatically, and repair mode downgrades repairable differences
 * without admitting unsafe paths or unowned files.
 *
 * File observations precede whole-manifest comparison so each unsafe or
 * mismatched member retains its own address. A missing owned file is reported
 * through the reader's existing missing-file refusal; other read failures stay
 * unsafe. Publication must still confirm the input snapshot after this check,
 * since these observations alone do not establish a transaction snapshot.
 *
 * @evidence requirements/agent-authoring/source-owned-loop.md#agent-source-result-link Compares each resident output digest and manifest input identity with the result derived from current inputs, attributing differences to their owned paths.
 * @evidence specifications/authoring-and-authority/source-authority-and-derivation.md#spec-authoring-source-derivation-state Refuses changed generated bytes and input identities in read-only validation and distinguishes prior-owned output from unowned bytes before regeneration.
 */
export const inspectAutoMovieGeneratedOwnership = (props: {
  /** Fenced reader for resident generated records and bytes. */
  project: Pick<AutoMovieProductionProject,
    "root" | "generatedManifest" | "generatedRoot" | "trackedStatePath" | "readGeneratedFile"
  >;

  /** Exact manifest derived from the current design, source and protocol. */
  expected: IAutoMovieGeneratedManifest;

  /** Whether the caller will atomically replace repairable owned output. */
  repairDeclaredFiles: boolean;

  /** Host-owned physical listing, including links so they cannot disappear. */
  listFiles: (root: string) => string[];
}): IAutoMovieDiagnostic[] => {
  const { expected, repairDeclaredFiles } = props;
  const manifest = props.project.generatedManifest();
  const generatedManifestPath = normalizeSlash(
    path.relative(
      props.project.root,
      props.project.trackedStatePath("generated-manifest.json"),
    ),
  );
  const diagnostics: IAutoMovieDiagnostic[] = [];
  const expectedByPath = new Map(
    expected.files.map((file) => [normalizeSlash(file.path), file]),
  );
  const declaredByPath = new Map(
    (manifest?.files ?? []).map((file) => [normalizeSlash(file.path), file]),
  );
  if (manifest === null)
    diagnostics.push({
      code: "generated-manifest-missing",
      category: repairDeclaredFiles ? "warning" : "error",
      phase: "compile",
      target: "generated-manifest",
      path: generatedManifestPath,
      message: repairDeclaredFiles
        ? "Compiler-owned output has no generated manifest. The builder will publish the exact current ownership manifest with the derived files."
        : "Compiler-owned output has no generated manifest. Run the scaffold compile command before trusting generated bytes.",
    });
  for (const file of props.listFiles(props.project.generatedRoot())) {
    const relative = normalizeSlash(
      path.relative(props.project.generatedRoot(), file),
    );
    if (expectedByPath.has(relative) === false) {
      const declared = declaredByPath.get(relative);
      let matchesDeclared = false;
      try {
        matchesDeclared =
          declared !== undefined &&
          digestAutoMovieBytes(props.project.readGeneratedFile(relative)) ===
            declared.digest;
      } catch {
        matchesDeclared = false;
      }
      diagnostics.push({
        code: matchesDeclared
          ? "generated-stale-output"
          : "generated-unowned",
        category:
          matchesDeclared && repairDeclaredFiles ? "warning" : "error",
        phase: "compile",
        target: relative,
        path: normalizeSlash(path.relative(props.project.root, file)),
        message: matchesDeclared
          ? repairDeclaredFiles
            ? `Generated file "${relative}" belonged to the prior builder result but is absent from the current result. The builder will remove it.`
            : `Generated file "${relative}" is stale output from a different compile. Run the scaffold compile command to remove it.`
          : `Generated file "${relative}" is not the canonical output derived from current source and design. Remove it before running the builder.`,
      });
    }
  }
  for (const entry of expected.files) {
    const file = path.resolve(props.project.generatedRoot(), entry.path);
    let actual: AutoMovieContentDigest | null = null;
    try {
      actual = digestAutoMovieBytes(
        props.project.readGeneratedFile(entry.path),
      );
    } catch (error) {
      if (error instanceof Error && error.message.includes("does not exist"))
        actual = null;
      else {
        diagnostics.push({
          code: "generated-path-outside",
          category: "error",
          phase: "compile",
          target: entry.path,
          path: normalizeSlash(path.relative(props.project.root, file)),
          message:
            error instanceof Error
              ? error.message
              : `Generated file "${entry.path}" is unsafe. Remove the link before running the builder.`,
        });
        continue;
      }
    }
    if (actual !== entry.digest)
      diagnostics.push({
        code: "generated-tampered",
        category: repairDeclaredFiles ? "warning" : "error",
        phase: "compile",
        target: entry.path,
        path: normalizeSlash(path.relative(props.project.root, file)),
        message: generatedOwnershipDiagnosticMessage({
          actual,
          expected: entry.digest,
          repair: repairDeclaredFiles,
        }),
      });
  }
  if (
    manifest !== null &&
    manifest.inputFingerprint !== expected.inputFingerprint
  )
    diagnostics.push({
      code: "generated-stale",
      category: repairDeclaredFiles ? "warning" : "error",
      phase: "compile",
      target: "generated-manifest",
      path: generatedManifestPath,
      message: repairDeclaredFiles
        ? `Generated input ${manifest.inputFingerprint} differs from current ${expected.inputFingerprint}. The builder will refresh all builder-owned output.`
        : `Generated input ${manifest.inputFingerprint} differs from current ${expected.inputFingerprint}. Run the scaffold compile command before trusting generated output.`,
    });
  if (
    manifest !== null &&
    Buffer.from(canonicalAutoMovieJsonBytes(manifest)).equals(
      Buffer.from(canonicalAutoMovieJsonBytes(expected)),
    ) === false
  )
    diagnostics.push({
      code: "generated-manifest-stale",
      category: repairDeclaredFiles ? "warning" : "error",
      phase: "compile",
      target: "generated-manifest",
      path: generatedManifestPath,
      message: repairDeclaredFiles
        ? "The generated manifest does not exactly match builder-derived inventory, digests, identity, and provenance. The builder will replace it."
        : "The generated manifest does not exactly match builder-derived inventory, digests, identity, and provenance. Run the scaffold compile command before trusting generated output.",
    });
  return diagnostics;
};
