import { HUMAN_FACE_CRANIOFACIAL_MEASUREMENTS } from "./HUMAN_FACE_CRANIOFACIAL_MEASUREMENTS";
import { HUMAN_FACE_DENTAL_MEASUREMENTS } from "./HUMAN_FACE_DENTAL_MEASUREMENTS";
import { HUMAN_FACE_EAR_MEASUREMENTS } from "./HUMAN_FACE_EAR_MEASUREMENTS";
import { HUMAN_FACE_EYE_MEASUREMENTS } from "./HUMAN_FACE_EYE_MEASUREMENTS";
import { HUMAN_FACE_JAW_MEASUREMENTS } from "./HUMAN_FACE_JAW_MEASUREMENTS";
import { HUMAN_FACE_MOUTH_MEASUREMENTS } from "./HUMAN_FACE_MOUTH_MEASUREMENTS";
import { HUMAN_FACE_NOSE_MEASUREMENTS } from "./HUMAN_FACE_NOSE_MEASUREMENTS";
import { HUMAN_FACE_ORAL_CAVITY_MEASUREMENTS } from "./HUMAN_FACE_ORAL_CAVITY_MEASUREMENTS";
import { HUMAN_FACE_TONGUE_MEASUREMENTS } from "./HUMAN_FACE_TONGUE_MEASUREMENTS";
import type { IHumanFaceMeasurement } from "./IHumanFaceMeasurement";

/**
 * Every measurement the face resolver reads and a document target may name.
 *
 * Each face part owner registers its subtree in its own file and spreads it
 * here; identities are unique across the registry.
 *
 * @author Samchon
 */
export const HUMAN_FACE_MEASUREMENTS: readonly IHumanFaceMeasurement[] = [
  ...HUMAN_FACE_MOUTH_MEASUREMENTS,
  ...HUMAN_FACE_DENTAL_MEASUREMENTS,
  ...HUMAN_FACE_JAW_MEASUREMENTS,
  ...HUMAN_FACE_TONGUE_MEASUREMENTS,
  ...HUMAN_FACE_ORAL_CAVITY_MEASUREMENTS,
  ...HUMAN_FACE_CRANIOFACIAL_MEASUREMENTS,
  ...HUMAN_FACE_NOSE_MEASUREMENTS,
  ...HUMAN_FACE_EAR_MEASUREMENTS,
  ...HUMAN_FACE_EYE_MEASUREMENTS,
];
