/**
 * Interface package boundaries for authoring authority and provenance.
 *
 * The package's lint.config.ts selects this declaration as an exclusion
 * carrier within its complete public-source population. It has no runtime
 * state and is not re-exported by the package barrel. Each declared
 * target/reason pair below owns one intentional negative relationship;
 * requirement and specification boundaries for this domain stay together.
 * Positive implementation citations remain on the actual public exports.
 * An exclusion neither implements a feature nor approves a rendered asset.
 * Add a boundary at its semantic owner and retain native graph validation.
 *
 * @evidenceExclude requirements/agent-authoring/project-ownership.md#agent-sandbox-write-boundary Sandbox filesystem ownership belongs to the build launcher and template publication capabilities, not portable production data.
 * @evidenceExclude requirements/agent-authoring/reference-navigation.md#agent-reference-selection The MCP package owns authored Markdown navigation requests and responses independently of portable production schemas.
 * @evidenceExclude requirements/agent-authoring/reference-navigation.md#agent-reference-source The MCP reader owns source projection and byte revisions; this package neither reads nor projects documents.
 * @evidenceExclude requirements/agent-authoring/reference-navigation.md#agent-reference-bounds The MCP provider owns response budgets, pagination and reference failures.
 * @evidenceExclude requirements/agent-authoring/reference-navigation.md#agent-reference-isolation Physical read confinement belongs to the MCP adapter, not portable production data.
 * @evidenceExclude requirements/agent-authoring/reference-navigation.md#agent-reference-transports MCP and local JSON transports belong to the MCP package and installed client registration.
 * @evidenceExclude specifications/authoring-and-authority/reference-navigation.md#spec-reference-selection The MCP package declares the exact navigation address and heading response contracts.
 * @evidenceExclude specifications/authoring-and-authority/reference-navigation.md#spec-reference-source Lossless Markdown projection and digest computation are MCP reader responsibilities.
 * @evidenceExclude specifications/authoring-and-authority/reference-navigation.md#spec-reference-bounds Serialized byte ceilings and continuation admission belong to the MCP provider.
 * @evidenceExclude specifications/authoring-and-authority/reference-navigation.md#spec-reference-isolation Root binding and read-handle identity checks belong to the MCP filesystem adapter.
 * @evidenceExclude specifications/authoring-and-authority/reference-navigation.md#spec-reference-transports The MCP server and reference command implement shared transport behavior outside this portable schema package.
 * @evidenceExclude specifications/authoring-and-authority/source-authority-and-derivation.md#spec-authoring-sandbox-physical-ownership The build launcher and template native publication API retain sandbox generation authority; no portable production schema owns these OS capabilities.
 * @evidenceExclude requirements/agent-authoring/capability-discovery.md#agent-choice-surface-discovery The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/agent-authoring/capability-discovery.md#agent-diagnostic-discovery The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/agent-authoring/capability-discovery.md#agent-technique-example The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/agent-authoring/capability-discovery.md#agent-topic-document-discovery The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/agent-authoring/knowledge-boundary.md#agent-authoring-api-refusal The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/agent-authoring/knowledge-boundary.md#agent-no-surprise-external-effects The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/agent-authoring/knowledge-boundary.md#agent-provider-neutrality The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/agent-authoring/partial-work.md#agent-atomic-compilation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/agent-authoring/partial-work.md#agent-partial-verification-scope The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/agent-authoring/partial-work.md#agent-partial-work-gap-distinction The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/agent-authoring/partial-work.md#agent-resumable-authoring The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/agent-authoring/production-language.md#agent-production-language-contract The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/agent-authoring/project-ownership.md#agent-ambiguous-ownership-refusal The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/agent-authoring/project-ownership.md#agent-editable-source-authority The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/agent-authoring/project-ownership.md#agent-portable-authoring The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/agent-authoring/project-ownership.md#agent-project-owned-bytes The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/agent-authoring/README.md#에이전트-저작-요구사항 The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/agent-authoring/roles-and-authorities.md#agent-director-authority The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/agent-authoring/roles-and-authorities.md#agent-user-delegation-authority The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/agent-authoring/source-owned-loop.md#agent-change-impact-visibility The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/agent-authoring/source-owned-loop.md#agent-reviewable-source-change The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/canonical-digests-and-content-identity.md#integrity-algorithm-change-and-collision The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/canonical-digests-and-content-identity.md#integrity-binary-dependency-closure The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/canonical-digests-and-content-identity.md#integrity-byte-and-semantic-identity The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/canonical-digests-and-content-identity.md#integrity-mutable-reference-snapshot The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/canonical-digests-and-content-identity.md#integrity-structured-canonicalization The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/chain-of-custody-and-tamper-detection.md#custody-boundary-integrity-check The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/chain-of-custody-and-tamper-detection.md#custody-distributed-copy-verification The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/chain-of-custody-and-tamper-detection.md#custody-gap-and-quarantine The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/chain-of-custody-and-tamper-detection.md#custody-signature-attestation-boundary The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/chain-of-custody-and-tamper-detection.md#custody-tamper-evident-history The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/completeness-freshness-and-refusal.md#evidence-dependency-based-current-status The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/completeness-freshness-and-refusal.md#evidence-honest-refusal The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/completeness-freshness-and-refusal.md#evidence-partial-results-and-aggregation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/completeness-freshness-and-refusal.md#evidence-reapproval-after-change The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/completeness-freshness-and-refusal.md#evidence-reproduction-boundary The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/completeness-freshness-and-refusal.md#evidence-unsupported-and-not-run The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/entities-activities-agents-and-lineage.md#provenance-activity-inputs-outputs The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/entities-activities-agents-and-lineage.md#provenance-agent-role-responsibility The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/entities-activities-agents-and-lineage.md#provenance-entity-and-revision The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/entities-activities-agents-and-lineage.md#provenance-primary-and-derived-source The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/generation-transformation-and-derivation.md#provenance-derivation-impact The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/generation-transformation-and-derivation.md#provenance-generated-output-record The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/generation-transformation-and-derivation.md#provenance-nondeterministic-generation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/generation-transformation-and-derivation.md#provenance-selection-and-composition The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/generation-transformation-and-derivation.md#provenance-transformation-record The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/observations-claims-and-human-judgments.md#evidence-automated-finding-boundary The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/observations-claims-and-human-judgments.md#evidence-claim-basis The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/observations-claims-and-human-judgments.md#evidence-disagreement-and-resolution The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/observations-claims-and-human-judgments.md#evidence-human-judgment-history The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/privacy-credentials-and-disclosure.md#privacy-credential-omission The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/privacy-credentials-and-disclosure.md#privacy-erasure-and-lineage The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/privacy-credentials-and-disclosure.md#privacy-external-service-disclosure The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/privacy-credentials-and-disclosure.md#privacy-human-identity-and-pseudonym The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/privacy-credentials-and-disclosure.md#privacy-redaction-and-source-relation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/privacy-credentials-and-disclosure.md#privacy-sensitive-metadata The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/README.md#증거와-출처-계보-요구사항 The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/retention-invalidation-and-disposal.md#retention-archive-retrieval-and-restoration The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/retention-invalidation-and-disposal.md#retention-freshness-expiry-and-review The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/retention-invalidation-and-disposal.md#retention-hold-and-exception The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/retention-invalidation-and-disposal.md#retention-invalidation-versus-deletion The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/retention-invalidation-and-disposal.md#retention-verifiable-disposal The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/scope-identity-and-status.md#evidence-explicit-status The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/scope-identity-and-status.md#evidence-portable-inspection The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/scope-identity-and-status.md#evidence-scope-and-exclusions The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/scope-identity-and-status.md#evidence-subject-record-separation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/third-party-sources-rights-and-attribution.md#third-party-attribution-propagation The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/third-party-sources-rights-and-attribution.md#third-party-rights-and-terms The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/third-party-sources-rights-and-attribution.md#third-party-source-access-restriction The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/evidence-and-provenance/third-party-sources-rights-and-attribution.md#third-party-source-change-and-withdrawal The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/production-evidence/authoring-contracts.md#agent-production-evidence-contract-discriminators The portable interface package does not own this requirement beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude requirements/production-evidence/README.md The portable interface defines production data shapes; it does not configure or construct the project-owned authoring evidence graph.
 * @evidenceExclude requirements/production-evidence/graph.md The portable interface defines production data shapes; it does not configure or construct the project-owned authoring evidence graph.
 * @evidenceExclude requirements/production-evidence/native-input.md#agent-production-evidence-native-boundary Native evidence configuration belongs to the evidence adapter; portable production data does not transform graph declarations.
 * @evidenceExclude requirements/production-evidence/input.md The portable interface defines production data shapes; it does not configure or construct the project-owned authoring evidence graph.
 * @evidenceExclude specifications/authoring-and-authority/capability-and-content-boundary.md#spec-authoring-capability-extension-compatibility The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/capability-and-content-boundary.md#spec-authoring-capability-failure-gap The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/capability-and-content-boundary.md#spec-authoring-capability-input-output The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/capability-and-content-boundary.md#spec-authoring-capability-not-content-invariant The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/delegation-and-decision-authority.md#spec-authoring-authority-violation-failure The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/delegation-and-decision-authority.md#spec-authoring-decision-authority-state The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/delegation-and-decision-authority.md#spec-authoring-user-director-input The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/external-execution-and-provider-neutrality.md#spec-authoring-external-adoption-output The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/external-execution-and-provider-neutrality.md#spec-authoring-external-execution-state The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/external-execution-and-provider-neutrality.md#spec-authoring-external-failure-substitution The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/external-execution-and-provider-neutrality.md#spec-authoring-external-request-output The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/external-execution-and-provider-neutrality.md#spec-authoring-external-selection-input The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/external-execution-and-provider-neutrality.md#spec-authoring-provider-compatibility The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/external-execution-and-provider-neutrality.md#spec-authoring-provider-source-invariant The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/knowledge-evidence-and-tool-boundary.md#spec-authoring-tool-authoring-invariant The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/knowledge-evidence-and-tool-boundary.md#spec-authoring-tool-boundary-compatibility The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/knowledge-evidence-and-tool-boundary.md#spec-authoring-tool-choice-discovery The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/knowledge-evidence-and-tool-boundary.md#spec-authoring-tool-diagnostic-failure The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/partial-targets-and-atomic-results.md#spec-authoring-partial-atomic-invariant The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/partial-targets-and-atomic-results.md#spec-authoring-partial-resume-compatibility The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/partial-targets-and-atomic-results.md#spec-authoring-partial-work-state The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/production-language.md#spec-authoring-production-language-module The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/prototype-determinism-and-fidelity.md#spec-authoring-choice-determinism-invariant The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/prototype-determinism-and-fidelity.md#spec-authoring-deterministic-input-identity The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/prototype-determinism-and-fidelity.md#spec-authoring-downstream-fidelity-output The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/prototype-determinism-and-fidelity.md#spec-authoring-fidelity-failure-choice The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/prototype-determinism-and-fidelity.md#spec-authoring-prototype-exclusion-compatibility The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/prototype-determinism-and-fidelity.md#spec-authoring-structural-output-invariant The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/README.md#저작과-권한-시스템-명세 The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/source-authority-and-derivation.md#spec-authoring-change-impact-report The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/source-authority-and-derivation.md#spec-authoring-source-change-impact-invariant The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/source-authority-and-derivation.md#spec-authoring-source-ownership-failure The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/authoring-and-authority/source-authority-and-derivation.md#spec-authoring-source-resume-compatibility The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/canonical-digests-and-content-identity.md#evp-algorithm-migration-collision The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/canonical-digests-and-content-identity.md#evp-binary-closure-digest The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/canonical-digests-and-content-identity.md#evp-byte-semantic-identity The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/canonical-digests-and-content-identity.md#evp-mutable-locator-snapshot The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/canonical-digests-and-content-identity.md#evp-structured-canonicalization The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/chain-of-custody-and-tamper-detection.md#evp-custody-boundary-receipt The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/chain-of-custody-and-tamper-detection.md#evp-custody-quarantine-state The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/chain-of-custody-and-tamper-detection.md#evp-distributed-copy-verification The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/chain-of-custody-and-tamper-detection.md#evp-signature-verification-boundary The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/chain-of-custody-and-tamper-detection.md#evp-tamper-evident-correction-chain The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/completeness-freshness-and-refusal.md#evp-dependency-based-freshness The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/completeness-freshness-and-refusal.md#evp-fail-closed-decision-gate The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/completeness-freshness-and-refusal.md#evp-outcome-classification-lattice The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/completeness-freshness-and-refusal.md#evp-partial-aggregation The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/completeness-freshness-and-refusal.md#evp-reapproval-after-change The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/completeness-freshness-and-refusal.md#evp-reproduction-verification-boundary The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/entities-activities-agents-and-lineage.md#evp-activity-execution-record The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/entities-activities-agents-and-lineage.md#evp-actor-role-binding The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/entities-activities-agents-and-lineage.md#evp-entity-revision-model The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/entities-activities-agents-and-lineage.md#evp-primary-derived-source-relation The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/generation-transformation-and-derivation.md#evp-derivation-reverse-impact-index The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/generation-transformation-and-derivation.md#evp-generated-output-receipt The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/generation-transformation-and-derivation.md#evp-nondeterministic-attempt-model The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/generation-transformation-and-derivation.md#evp-selection-composition-record The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/generation-transformation-and-derivation.md#evp-transformation-mapping-and-loss The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/observations-claims-and-human-judgments.md#evp-automated-finding-result The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/observations-claims-and-human-judgments.md#evp-claim-evaluation-contract The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/observations-claims-and-human-judgments.md#evp-disagreement-resolution The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/observations-claims-and-human-judgments.md#evp-human-judgment-activity The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/privacy-credentials-and-disclosure.md#evp-credential-exclusion-gate The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/privacy-credentials-and-disclosure.md#evp-erasure-tombstone The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/privacy-credentials-and-disclosure.md#evp-external-transfer-authorization The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/privacy-credentials-and-disclosure.md#evp-human-identity-pseudonymization The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/privacy-credentials-and-disclosure.md#evp-redaction-derivative The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/privacy-credentials-and-disclosure.md#evp-sensitive-metadata-filtering The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/README.md#증거와-출처-계보-시스템-명세 The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/retention-invalidation-and-disposal.md#evp-archive-retrieval-activity The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/retention-invalidation-and-disposal.md#evp-disposal-execution-receipt The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/retention-invalidation-and-disposal.md#evp-freshness-expiry-evaluation The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/retention-invalidation-and-disposal.md#evp-invalidation-deletion-state The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/retention-invalidation-and-disposal.md#evp-retention-hold The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/scope-identity-and-status.md#evp-portable-inspection-view The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/scope-identity-and-status.md#evp-record-scope-model The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/scope-identity-and-status.md#evp-record-status-transition The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/scope-identity-and-status.md#evp-subject-record-identity-separation The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/third-party-sources-rights-and-attribution.md#evp-attribution-propagation-closure The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/third-party-sources-rights-and-attribution.md#evp-restricted-source-verification The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/third-party-sources-rights-and-attribution.md#evp-source-terms-change-impact The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/evidence-and-provenance/third-party-sources-rights-and-attribution.md#evp-third-party-rights-evaluation The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/production-evidence/authoring-contracts.md#spec-authoring-production-evidence-contract-discriminators The portable interface package does not own this specification beyond its declared data boundaries; the owning runtime or workflow package retains implementation and verification responsibility.
 * @evidenceExclude specifications/production-evidence/README.md The portable interface carries authored production values but does not implement the evidence configuration state machine or filesystem validation.
 * @evidenceExclude specifications/production-evidence/graph.md The portable interface carries authored production values but does not implement the evidence configuration state machine or filesystem validation.
 * @evidenceExclude specifications/production-evidence/native-input.md#spec-authoring-production-evidence-native-boundary The evidence adapter projects its own ownership metadata; no portable interface export constructs evaluator input.
 * @evidenceExclude specifications/production-evidence/input.md The portable interface carries authored production values but does not implement the evidence configuration state machine or filesystem validation.
 */
export type AutoMovieInterfaceAuthoringEvidenceExclusions = never;
