import type { IAutoMovieMesh } from "@automovie/interface";

/**
 * Mesh attributes at the preview and GLB Float32 precision boundary.
 * @evidence requirements/actors/body-authoring/contract.md#actor-body-editor Carries the numerical surface shown by the connected body editor.
 * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor-view Supplies directly drawable Float32 body geometry to the preview.
 * @author Samchon
 */
export interface ConnectedBodyMesh {
  /** Metre positions, three scalars per vertex.
   * @evidence requirements/actors/body-authoring/contract.md#actor-body-editor Displays the admitted body shape.
   * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor-view Transfers the body positions at display precision.
   */
  positions: Float32Array<ArrayBuffer>;
  /** Unit directions or null if generated by the viewer.
   * @evidence requirements/actors/body-authoring/contract.md#actor-body-editor Shows the body's surface under the chosen material and light.
   * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor-view Carries preview normals alongside positions.
   */
  normals: Float32Array<ArrayBuffer> | null;
  /** glTF UV0 coordinates.
   * @evidence requirements/actors/body-authoring/contract.md#actor-body-editor Displays the body's resident material map.
   * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor-view Keeps UV0 aligned with the preview surface.
   */
  uvs: Float32Array<ArrayBuffer> | null;
  /** Linear RGB multipliers.
   * @evidence requirements/actors/body-authoring/contract.md#actor-body-editor Displays authored vertex color where the body has it.
   * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor-view Carries the optional resident color attribute.
   */
  colors?: Float32Array<ArrayBuffer>;
  /** Triangle vertex references.
   * @evidence requirements/actors/body-authoring/contract.md#actor-body-editor Displays the connected skin triangles.
   * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor-view Carries indexed preview topology.
   */
  indices: Uint32Array<ArrayBuffer>;
  /** Owned source-pair/null incidence, cloned without narrowing opaque IDs.
   * @evidence requirements/actors/body-authoring/contract.md#actor-body-editor Preserves declared source incidence beside the committed numerical frame.
   * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor-view Carries independently owned source correspondence with the existing Float32 display buffers.
   */
  physicalVertices?: IAutoMovieMesh["physicalVertices"];
  /** Already posed, so the viewer must not attempt skin binding.
   * @evidence requirements/actors/body-authoring/contract.md#actor-body-editor Shows the committed posed body as static geometry.
   * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor-view Prevents the display layer from skinning an already posed surface.
   */
  skin: null;
}
