import { performShot, stageScene } from "@automovie/engine";
import {
  IAutoMovieCameraClearanceEnvelope,
  IAutoMovieShot,
  IAutoMovieStage,
} from "@automovie/interface";
import {
  canonicalAutoMovieJsonBytes,
  digestAutoMovieBytes,
} from "@automovie/production";
import { TestValidator } from "@nestia/e2e";

import {
  makePerformanceWrite,
  makeScriptWrite,
  makeStagingWrite,
  validSynthesizer,
} from "../internal/filmFixtures";
import { createModel, createSkeleton } from "../internal/fixtures";

/** One camera whose declared body envelope stays clear of every obstacle. */
const stageWithClearance = (): IAutoMovieStage => {
  const base = makeStagingWrite();
  const clearance: IAutoMovieCameraClearanceEnvelope = {
    body: { center: { x: 0, y: 0, z: 0 }, radius: 0.01 },
    parentRig: null,
  };
  return {
    ...base,
    cameras: [
      {
        ...base.cameras[0]!,
        near: 0.1,
        far: 100,
        depthPrecision: { minimumDepthBits: 24, maximumStepMeters: 1 },
        clearance,
      },
    ],
  };
};

/** Perform the same authored take under one clearance runtime. */
const compileTake = (revision: string, sampleRate: number) => {
  const staged = stageScene(makeScriptWrite(), stageWithClearance());
  if (staged.success !== true)
    throw new Error("the clearance fixture must stage");
  const performed = performShot({
    script: makeScriptWrite(),
    staged,
    performance: makePerformanceWrite(),
    synthesize: validSynthesizer,
    skeleton: () => createSkeleton(),
    models: [
      { ...createModel(), id: "stickman" },
      { ...createModel(), id: "knightB" },
    ],
    cameraClearance: { revision, currentRevision: revision, sampleRate },
  });
  if (performed.success !== true)
    throw new Error("the clearance fixture must perform");
  return performed;
};

/** Digest of the exact canonical bytes this shot would be materialized as. */
const artifactDigest = (shot: IAutoMovieShot): string =>
  digestAutoMovieBytes(canonicalAutoMovieJsonBytes(shot));

/**
 * A compiled take's bytes follow its inputs, never the project revision.
 *
 * Generated bytes are a function of design, source, evidence and protocol. The
 * project revision is not one of those, and it cannot be: the write that
 * publishes a take moves the revision, so a take that recorded the revision
 * would derive different bytes on the next run, report its own fresh output as
 * tampered, and never converge however many times it was repaired. The two
 * revisions an evaluation compares therefore stay on the runtime the builder
 * supplies while the report keeps only its verdict and sample plan.
 *
 * The inspection clock arrives on that same runtime, which is what makes this
 * pair worth pinning together: one field of one object must move the bytes and
 * the other must not, so an implementation cannot satisfy this case by dropping
 * the runtime's influence altogether.
 *
 * Scenarios:
 *
 * 1. Three takes are arranged and each one publishes exactly one clear report
 *    whose carried sample plan matches its interval count, so a later equality
 *    cannot be satisfied by an absent or empty report.
 * 2. Two takes differing only in project revision materialize to identical
 *    canonical bytes.
 * 3. A take differing only in its inspection clock materializes to different
 *    bytes, proving the equality above is not indifference to the runtime.
 * 4. No published report carries a `revision` or `currentRevision` member.
 */
export const test_film_camera_clearance_revision_independence = (): void => {
  const first = compileTake("41", 24);
  const second = compileTake("42", 24);
  const finer = compileTake("41", 48);

  TestValidator.equals(
    "every arranged take publishes one clear report over a real sample plan",
    [first, second, finer].map((performed) => [
      performed.shot.cameraClearance?.length,
      performed.shot.cameraClearance?.[0]?.status,
      performed.shot.cameraClearance?.[0]?.sampleTimes.length ===
        (performed.shot.cameraClearance?.[0]?.intervals ?? -1) + 1,
    ]),
    [
      [1, "clear", true],
      [1, "clear", true],
      [1, "clear", true],
    ],
  );

  TestValidator.equals(
    "a moved project revision alone leaves the generated bytes identical",
    artifactDigest(first.shot),
    artifactDigest(second.shot),
  );

  TestValidator.predicate(
    "those same bytes still follow the inspection clock the runtime carries",
    artifactDigest(first.shot) !== artifactDigest(finer.shot),
  );

  TestValidator.equals(
    "no published report carries a revision of its own",
    [first, second, finer].flatMap((performed) =>
      (performed.shot.cameraClearance ?? []).flatMap((report) =>
        ["revision", "currentRevision"].filter((key) =>
          Object.keys(report).includes(key),
        ),
      ),
    ),
    [],
  );
};
