import type * as Human from "@automovie/human";

/**
 * Optical identity, lids, lashes, brows and orbital support.
 * The frozen study root retains this domain through the native evidence graph.
 * Existing source inspections and historical capture limitations are preserved
 * verbatim. This carrier neither changes geometry nor accepts current likeness;
 * artifact observations and identities remain in review.md and the root record.
 *
 * @evidence {@link Human.createPortraitOpticalFrame} Inspects the centred spherical support and engine shortest-arc placement consumed by iris and cornea construction. It is opt-in and does not change this frozen study's default basis.
 * @evidenceReview {@link Human.createPortraitOpticalFrame} #952ce58 Read all finite/radius/noncentral refusals, owned local sphere and translation, normalized axial direction and the shared engine rotation. The ten-mm quarter-turn cornea test checks pole sag and axial shell thickness against hand arithmetic; the old off-axis height field refuses beside the radial construction. Parallel, antiparallel and extreme finite witnesses are exercised. The helper neither fits the globe nor guarantees cranial containment.
 * @evidence {@link Human.IPortraitEyePerformance} Separates observed closure, current blink and gaze differences from eye identity.
 * @evidenceReview {@link Human.IPortraitEyePerformance} #1322e5a Read closure bounds, the invertible observed maximum and gaze-difference units against admission and component construction. The fields change actual tissue/optical geometry rather than scaling a whole eye to simulate a blink.
 * @evidence {@link Human.assertPortraitEyePerformance} Rejects nonfinite or unsupported eye-performance inputs before posing geometry.
 * @evidenceReview {@link Human.assertPortraitEyePerformance} #c200f11 Read all four finite checks and inclusive closure/gaze bounds, including the 0.95 observed-blink maximum. This standalone guard is also called by the public optical and lid helpers rather than relying only on UI input validation.
 * @evidence {@link Human.buildPortraitPerformanceGlobe} Keeps a complete globe underneath the changing aperture.
 * @evidenceReview {@link Human.buildPortraitPerformanceGlobe} #b9f6a59 Read bounded integer tessellation, single north/south poles, wrapped rings, outward triangle winding, radius/centre placement and overflow refusal. Visibility belongs to surrounding opaque tissue, not a changing sphere radius.
 * @evidence {@link Human.posePortraitLidCurves} Moves paired eyelid margins to a common seam while preserving the fixed optical sphere.
 * @evidenceReview {@link Human.posePortraitLidCurves} #ba4f505 Read finite paired-sample admission, exact copied identity at unchanged closure, observed-relative opening ratio and the three-to-one upper/lower travel. Complete closure gives coincident corresponding points; overflow refuses. Actual wink and clay-oblique frames show closure, but regular lid shape remains a likeness limitation.
 * @evidence {@link Human.posePortraitOpticalMesh} Rotates resident optics and normals around one fixed globe centre.
 * @evidenceReview {@link Human.posePortraitOpticalMesh} #de0614f Read aligned finite position/normal admission, copied zero-gaze identity, yaw then negative-pitch quaternion composition, translated positions and rotation-only normals. Post-transform nonfinite values refuse; mesh dimensions and unrelated UV/index data are retained.
 * @evidence {@link Human.createPortraitEyeComponent} Fits one owned eye configuration into shared skin and supplies its optical and tissue finishers.
 * @evidenceReview {@link Human.createPortraitEyeComponent} #a785772 Read the complete factory and fitting/attachment/finishing closures with eyeComponentInputs, eyeSupport, eyeLidRows, eyeMargins, eyeOpticalSurface and eyeSurfaceContact. Copied input admission precedes the identity fit. Tangent mode retains observed canthal guides and uses its fixed hull for performed intersections, initial contact, final contact and drawing; gaze cannot choose the fitted centre. Omitted mode keeps the old sphere and unshifted guide arithmetic. Static, observed, half-closed/gazing and closed independent-host cases check fixed outer targets and optical identity while actual rim positions move. Geometric feasibility does not settle the observed tissue shape.
 * @evidence {@link Human.appendPortraitEyeMargins} Attaches the section rings to retained outer skin identities and returns the new inner boundary mapping.
 * @evidenceReview {@link Human.appendPortraitEyeMargins} #db275b5 Read the extracted eyeMargins and eyeLidRows owners. The outer ring reuses fitted host IDs; seven appended rings retain one group per triangle and return the inner IDs consumed after common subdivision. Both fitting and attachment use the same row calculation and supplied profile samplers. The independent four-point test pins XYZ, guide transport and caller preservation. This source inspection does not accept the final eyelid shape or contact residual.
 * @evidence {@link Human.IPortraitEyeShape.irisPigment} Selects an instance-owned pigment palette without changing the aperture or optical shell.
 * @evidenceReview {@link Human.IPortraitEyeShape.irisPigment} #53e8e02 Followed immediate createPortraitIrisMaterials evaluation and the later side-qualified material bindings. The pigment scenario mutates the caller's colour array after eye creation and retains the captured colour; its complete geometry buffers equal the omitted-pigment twin. The retained shape reference determines palette naming, while returned materials own the numerical colours.
 * @evidence {@link Human.IPortraitIrisPigment} Defines two linear-RGB endpoints for the eight-band iris palette.
 * @evidenceReview {@link Human.IPortraitIrisPigment} #0f525ea Read base and signed variation together with exact-three-element, finite and unit-range endpoint admission. Every intermediate band is a convex combination of the admitted endpoints. This data describes authored reflectance controls and contains no sampled photograph or geometry.
 * @evidence {@link Human.IPortraitIrisPigment.base} Supplies the first palette endpoint and limbal/dark-band colour.
 * @evidenceReview {@link Human.IPortraitIrisPigment.base} #9d87262 Located the original component in value+variation*(i/7) and the independent base [0.2,0.4,0.6] colour oracle. Modifying the caller's array afterward cannot change returned materials because each band stores a fresh colour object.
 * @evidence {@link Human.IPortraitIrisPigment.variation} Supplies signed displacement from the base to the opposite palette endpoint.
 * @evidenceReview {@link Human.IPortraitIrisPigment.variation} #b6f2672 Compared negative, zero and positive increments against the endpoint checks. The hand oracle advances red by 0.1 and reduces green by 0.05 per band, while zero variation preserves uniform colour. The interval applies to base+variation rather than forbidding all negative increments.
 * @evidence {@link Human.createPortraitIrisMaterials} Produces independently named, owned opaque pigment finishes from those admitted endpoints.
 * @evidenceReview {@link Human.createPortraitIrisMaterials} #0a2093f Read prefix admission, all array/domain failures and eight linear interpolations into fresh material records. Roughness is 0.65 and no texture is attached; the eye owns radial membership and chooses these IDs without moving a vertex. Palette names and scalar finishes do not establish optical or subject likeness.
 * @evidence {@link Human.IPortraitEyebrowFlowDirection} Defines a tip on the supporting brow and one signed anatomical sweep, independently of fibre radius or density.
 * @evidence {@link Human.IPortraitEyebrowFlowDirection.tip} Places a strand endpoint between the lower zero and upper one boundaries so upper roots can descend.
 * @evidence {@link Human.IPortraitEyebrowFlowDirection.outwardBend} Carries millimetre lateral displacement whose sign is applied by the existing anatomical-side owner.
 * @evidence {@link Human.IPortraitEyebrowFlowProfile} Supplies complete medial-to-lateral and lower-to-upper root-band flow instead of one global rise.
 * @evidence {@link Human.IPortraitEyebrowFlowProfile.sections} Replaces the whole ordered witness population with two through 32 stations spanning zero to one.
 * @evidence {@link Human.createPortraitEyebrowFlow} Provides the actual brow builder with owned convex longitudinal and root-band direction samples.
 * @evidenceReview {@link Human.IPortraitEyebrowFlowDirection} #aaa6ebc Read the bounded tip and signed millimetre sweep against interpolation and both strand builders. The planar geometry scenario checks actual root and tip vertices without changing fibre count.
 * @evidenceReview {@link Human.IPortraitEyebrowFlowDirection.tip} #54e856b Read zero as the lower and one as the upper supporting boundary. Independent endpoint and out-of-range tests pass; actual upper and lower roots converge to the same authored tip in ribbon and tube geometry.
 * @evidenceReview {@link Human.IPortraitEyebrowFlowDirection.outwardBend} #fc0ca68 Read the signed millimetre displacement through anatomical-side application. The planar consumer test verifies mirrored lateral endpoint offsets and the profile test retains negative sweeps.
 * @evidenceReview {@link Human.IPortraitEyebrowFlowProfile} #9445f66 Read complete lower and upper root-band directions rather than whole-brow root coordinates. Tests cover cloned ownership, a collapsed band sampled at one half and independent side document replacement.
 * @evidenceReview {@link Human.IPortraitEyebrowFlowProfile.sections} #8df5b6a Read ordered complete witnesses at both endpoints. Tests admit two and 32, reject missing endpoints, duplicate or invalid stations and 33 witnesses, and replace the whole document population.
 * @evidenceReview {@link Human.createPortraitEyebrowFlow} #0651332 Read the copied witnesses, bounded query admission and convex cubic then linear interpolation. Independent arithmetic and actual tube/ribbon endpoint tests pass; temporarily disconnecting the builder made the endpoint test fail before restoration.
 * @evidence {@link Human.IPortraitEyebrowProfile} Separates strand dimensions and local support clearance from the brow's boundary binding.
 * @evidenceReview {@link Human.IPortraitEyebrowProfile} #d3ee760 Read optional flow and uint32 densitySeed beside the inherited dimensions. Flow replaces direction; a supplied seed selects independent thinning, while omission preserves the original population for replay. Tests cover side-specific seed inheritance and complete direction arrays without changing the host boundary.
 * @evidence {@link Human.IPortraitEyebrowProfile.radius} Sets base strand radius and the scale of the local normal estimate.
 * @evidenceReview {@link Human.IPortraitEyebrowProfile.radius} #ca26526 Traced the positive dimension into the tapered tube radius and max(0.001,radius) finite-difference step. The centreline offset includes radius(t), so the added clearance is measured outside the strand rather than from its centre.
 * @evidence {@link Human.IPortraitEyebrowProfile.radiusStep} Adds deterministic radius variation across each group of three strands.
 * @evidenceReview {@link Human.IPortraitEyebrowProfile.radiusStep} #294c7cd Located (i%3)*radiusStep before the taper factor. The admission sum includes twice this nonnegative value, which catches an unrepresentable largest strand/offset combination; zero retains one base radius across the population.
 * @evidence {@link Human.IPortraitEyebrowProfile.taper} Controls loss of strand radius toward the free end.
 * @evidenceReview {@link Human.IPortraitEyebrowProfile.taper} #9035ba0 Read multiplication by 1-taper*t and the [0,1) admission interval. Zero retains constant radius; rejecting one keeps the tip from collapsing to zero cross-section through this control.
 * @evidence {@link Human.IPortraitEyebrowProfile.clearance} Adds separation beyond the strand radius along the estimated skin normal.
 * @evidenceReview {@link Human.IPortraitEyebrowProfile.clearance} #cf9c267 Compared the centreline offset radius(t)+clearance+arch*sin(pi*t) with the sloped-plane oracle's signed perpendicular distance. That test checks every emitted strand vertex. It verifies the planar contact mechanism, while arbitrary curved-surface clearance still needs its own measurement and render.
 * @evidence {@link Human.IPortraitEyebrowProfile.arch} Raises the strand midpoint from the local supporting surface.
 * @evidenceReview {@link Human.IPortraitEyebrowProfile.arch} #308f248 Followed its sine contribution into the normal offset. It vanishes at strand endpoints and is independent of the tangent-plane bend; a nonnegative arch cannot represent a negative supraorbital skin groove.
 * @evidence {@link Human.IPortraitEyebrowProfile.outwardBend} Bends strand XY paths toward the anatomical outer side.
 * @evidenceReview {@link Human.IPortraitEyebrowProfile.outwardBend} #f7351f8 Read the side-signed t² displacement in X and its participation in the nonzero-path check. A negative value bends oppositely; a path leaving the sampled skin refuses rather than retaining a guessed endpoint depth.
 * @evidence {@link Human.IPortraitEyebrowProfile.segments} Sets bounded longitudinal sampling of each tube.
 * @evidenceReview {@link Human.IPortraitEyebrowProfile.segments} #54a49df Traced the integral 1..32 range into portraitTube. The boundary scenarios admit both endpoints and reject zero, 33 and a fractional count. This resolution control does not alter the separately authored fibre count or brow region.
 * @evidence {@link Human.portraitEyebrowProfile} Supplies the authored basic strand dimensions when a caller omits detail.
 * @evidenceReview {@link Human.portraitEyebrowProfile} #099d6ad Read the default radius 0.05, step 0.0075, taper 0.58, clearance 0.03, arch 0.1, outward bend 1.2 and five segments against both consumers. Optional distribution fields remain omitted. The values are provisional fibre dimensions, not measured hair or accepted grooming.
 * @evidence {@link Human.assertPortraitEyebrowProfile} Admits bounded strand populations and finite profile arithmetic before allocation.
 * @evidenceReview {@link Human.assertPortraitEyebrowProfile} #045012e Read optional seed admission before allocation beside flow, root/span and dimension checks. Zero and uint32 maximum seeds are exercised, with negative, fractional, excessive and nonfinite values rejected. JSON shape admission remains separate; the actual eye component calls this numeric guard.
 * @evidence {@link Human.buildPortraitEyebrow} Samples the final skin beneath each independently named strand.
 * @evidenceReview {@link Human.buildPortraitEyebrow} #f2a65c8 Read the optional seeded independent sequence and the omitted-seed legacy path through actual fibre emission. Seeded planar coverage preserves every root-height band and each retained mesh; no fades preserve all meshes regardless of seed. The frozen legacy GLB and model digests replay exactly. Flow endpoint and side tests also pass; these checks do not accept a likeness.
 * @evidence {@link Human.IPortraitOcularTissueShape} Separates the medial conjunctival profile from the narrow lower ocular margin.
 * @evidenceReview {@link Human.IPortraitOcularTissueShape} #e9c3846 Read the five scalar dimensions and the factory's owned copy. All are finite and nonnegative; zero corner length or margin width disables its corresponding surface, while zero relief retains that surface's underlying support. This type does not describe the external lower-lid body.
 * @evidence {@link Human.IPortraitOcularTissueShape.cornerLength} Sets medial tissue extent along the live aperture's X span.
 * @evidenceReview {@link Human.IPortraitOcularTissueShape.cornerLength} #9c218b8 Followed the dimension into the side-dependent X interpolation and the half-aperture admission bound. The exact-half-width case is admitted, a larger medial extent refuses, and zero returns a null corner without removing the lower margin.
 * @evidence {@link Human.IPortraitOcularTissueShape.caruncleProjection} Scales the medial mound's additional anterior relief.
 * @evidenceReview {@link Human.IPortraitOcularTissueShape.caruncleProjection} #d1db376 Located its Gaussian centred at normalized medial distance 0.42 with width 0.26, multiplied by both sinusoidal boundary fades. Setting the amplitude to zero removes that mound term but leaves the support interpolation and fixed 0.02 mm tissue contribution.
 * @evidence {@link Human.IPortraitOcularTissueShape.plicaProjection} Scales a separate ridge lateral to the caruncular mound.
 * @evidenceReview {@link Human.IPortraitOcularTissueShape.plicaProjection} #387c9dc Read the narrower Gaussian at distance 0.82 and width 0.08. The isolated-amplitude test places its peak lateral to the caruncle, while both terms retain the same actual upper/lower boundaries; neither coefficient is a recovered subject measurement.
 * @evidence {@link Human.IPortraitOcularTissueShape.lowerMarginWidth} Limits how far the wet strip enters the visible eye opening.
 * @evidenceReview {@link Human.IPortraitOcularTissueShape.lowerMarginWidth} #b8670b3 Read the minimum of the canthus-faded width and half the local upper/lower Y separation. The parabolic-lid oracle places a 0.4 mm strip at Y=-1.6 mm in the centre and clips an oversized request to Y=0. Width zero disables this mesh independently.
 * @evidence {@link Human.IPortraitOcularTissueShape.lowerMarginLift} Rounds the wet strip above its boundary-to-support interpolation.
 * @evidenceReview {@link Human.IPortraitOcularTissueShape.lowerMarginLift} #dae1967 Traced the product of this amplitude, the longitudinal sine fade and sin(pi*v). Its contribution vanishes at both transverse boundaries and both canthi; the later eye-owned mesh contact may still advance the strip when zero lift would penetrate optical support.
 * @evidence {@link Human.IPortraitOcularTissueBoundary} Supplies the live eye frame consumed by both tissue surfaces.
 * @evidenceReview {@link Human.IPortraitOcularTissueBoundary} #1eb1b53 Read side, ordered X endpoints, upper/lower callbacks and support height together with the consuming section and globe closures. The current eye supplies refined lids and an engine-sampled support including cornea. No independent aperture or frozen tissue origin is created here.
 * @evidence {@link Human.IPortraitOcularTissueBoundary.side} Chooses which end of the increasing-X aperture is medial.
 * @evidenceReview {@link Human.IPortraitOcularTissueBoundary.side} #82bd582 Compared left's minimum-X origin with right's maximum-X origin and reversed normalized distance. The mirror oracle reverses column order while retaining outward winding; side changes anatomical placement rather than triangle orientation.
 * @evidence {@link Human.IPortraitOcularTissueBoundary.minimumX} Establishes the shared lower endpoint of the tissue sampling interval.
 * @evidenceReview {@link Human.IPortraitOcularTissueBoundary.minimumX} #3b143ed Read its participation in finite positive span admission and both strip/corner X formulas. Reversing or collapsing the interval refuses; translating both endpoints and the callbacks moves the constructed tissues in the same head frame.
 * @evidence {@link Human.IPortraitOcularTissueBoundary.maximumX} Establishes the opposite endpoint and the right eye's medial origin.
 * @evidenceReview {@link Human.IPortraitOcularTissueBoundary.maximumX} #f7ce724 Followed maximumX-minimumX into the medial half-width bound and maximumX-cornerLength*(1-u) into right-side construction. This is a supplied aperture boundary, not a maximum inferred separately from the generated strip.
 * @evidence {@link Human.IPortraitOcularTissueBoundary.upper} Supplies the upper surface of each local tissue section.
 * @evidenceReview {@link Human.IPortraitOcularTissueBoundary.upper} #4a96399 Read finite XYZ admission and upper.y>=lower.y before vertical interpolation and half-opening clipping. Returned Y/Z shape the patch; the lattice keeps the requested X coordinate. A nonfinite upper depth refuses during actual sampling.
 * @evidence {@link Human.IPortraitOcularTissueBoundary.lower} Anchors the wet margin and the lower side of the medial patch.
 * @evidenceReview {@link Human.IPortraitOcularTissueBoundary.lower} #8abda28 Traced lower.y into the strip origin and lower.z into both support bridges. The lower callback remains live, so translated lid functions move the tissue; a crossed lower height or nonfinite returned coordinate refuses instead of silently inverting the section.
 * @evidence {@link Human.IPortraitOcularTissueBoundary.globe} Supplies ocular support height in the same millimetre construction frame.
 * @evidenceReview {@link Human.IPortraitOcularTissueBoundary.globe} #f78bd9b Read the finite-height gate and both interpolation consumers. Despite the retained field name, the documented support may include cornea, as the current eye's engine depth query does. This callback shapes sampled positions; complete emitted-triangle clearance is enforced separately by the eye finisher.
 * @evidence {@link Human.IPortraitOrbitalSupportStation} Owns one forehead/brow/sulcus section on a subject-bound upper orbit.
 * @evidenceReview {@link Human.IPortraitOrbitalSupportStation} #adfbb28 Read every station member with the actual skin query and coupled field consumer. Signed projection changes section form, while positive height/descent locates its neighbours; these do not represent measured bone or fat thickness.
 * @evidence {@link Human.IPortraitOrbitalSupportStation.name} Preserves station identity in the three coupled anatomical targets.
 * @evidenceReview {@link Human.IPortraitOrbitalSupportStation.name} #342adfe Traced nonempty/unique admission and distinct forehead/brow/sulcus target names. Deterministic ordering belongs to the shared solver rather than the station array's incidental order.
 * @evidence {@link Human.IPortraitOrbitalSupportStation.anchor} Binds the section to a live retained brow-skin datum.
 * @evidenceReview {@link Human.IPortraitOrbitalSupportStation.anchor} #2db02e2 Checked nonnegative integral input and resident finite XYZ admission before building the skin sampler. The subject supplies different anchors for each orbit; the generic group contains no subject landmark identities.
 * @evidence {@link Human.IPortraitOrbitalSupportStation.forehead} Locates and constrains the surface above the brow pad.
 * @evidenceReview {@link Human.IPortraitOrbitalSupportStation.forehead} #9019c9e Read positive height and signed projection into the actual z query and combined solve. The independent inclined-plane case keeps this target stationary while the adjacent brow moves forward.
 * @evidence {@link Human.IPortraitOrbitalSupportStation.browProjection} Sets the target anterior movement at the brow's own resident skin section.
 * @evidenceReview {@link Human.IPortraitOrbitalSupportStation.browProjection} #8cab894 Traced the zero-height target and independent +0.2 mm oracle. This value affects skin consumed by the later eyebrow builder; it is not a hair offset or an independently added kernel amplitude.
 * @evidence {@link Human.IPortraitOrbitalSupportStation.sulcus} Defines the lower side of the upper-orbit support relationship.
 * @evidenceReview {@link Human.IPortraitOrbitalSupportStation.sulcus} #056dfad Read positive descent, negative local Y placement and signed projection with the -0.1 mm inclined-plane oracle. Its depth is queried on real skin rather than guessed from the brow point's Z.
 * @evidence {@link Human.IPortraitOrbitalSupportShape} Groups bounded upper-orbit sections under one interpolation support.
 * @evidenceReview {@link Human.IPortraitOrbitalSupportShape} #ebef7b1 Read copied nested inputs, one-to-32 station admission and the three-target-per-station mapping into the solver's 96-control domain. The section group remains optional in assembly and is not a complete anatomical reconstruction.
 * @evidence {@link Human.IPortraitOrbitalSupportShape.radius} Sets the common millimetre support used by the existing coupled solver.
 * @evidenceReview {@link Human.IPortraitOrbitalSupportShape.radius} #88d01c6 Compared finite positive metric admission with the resulting field radii. It governs interpolation reach rather than the brow-pad's literal tissue thickness; open-lid masking remains in the surface assembler.
 * @evidence {@link Human.IPortraitOrbitalSupportShape.stations} Supplies all section targets including stationary neighbouring witnesses.
 * @evidenceReview {@link Human.IPortraitOrbitalSupportShape.stations} #cb5c0b9 Checked empty/oversized/duplicate refusal, the exact 32-section limit, all-zero identity and ownership under later mutation. A provided empty population refuses rather than silently deleting one side of the support.
 * @evidence {@link Human.createPortraitOrbitalSupport} Builds the actual skin-based upper-orbit field consumed by portraitAssembly.
 * @evidenceReview {@link Human.createPortraitOrbitalSupport} #604ab53 Read side/profile admission, resident skin-depth queries, three roles per station and the coupled control-layer solver. Signed forehead, brow and sulcus requests share one skin surface and neighbouring attachments; they do not place an independent brow shell or assert measured bone depth.
 * @evidence {@link Human.IPortraitLowerLidPoint} Gives a named lower-tissue sample its planar offset and anterior section projection.
 * @evidenceReview {@link Human.IPortraitLowerLidPoint} #2e8e170 Read both millimetre fields through the eye's local outward-normal construction and support-depth bridge. Projection is not muscle thickness or a contact clearance; the two coordinates have separate geometric effects.
 * @evidence {@link Human.IPortraitLowerLidPoint.offset} Places tissue in order from the aperture towards surrounding skin.
 * @evidenceReview {@link Human.IPortraitLowerLidPoint.offset} #d1b5d96 Traced finite positive and strictly increasing admission for all six internal roles. Convex interpolation uses the same weights for each offset; the eye retains its inner aperture and derives the outer skin query from attachment distance.
 * @evidence {@link Human.IPortraitLowerLidPoint.projection} Shapes each tissue sample relative to its common support bridge.
 * @evidenceReview {@link Human.IPortraitLowerLidPoint.projection} #1d544dc Checked signed finite values, independent quarter-interval arithmetic and their replacement blend with basic row depths. A negative subtarsal projection is admitted; it does not move a separately guessed tissue mesh.
 * @evidence {@link Human.IPortraitLowerLidSection} Separates margin, pretarsal body, subtarsal boundary and preseptal transition in one shared section.
 * @evidenceReview {@link Human.IPortraitLowerLidSection} #1234883 Read all six points and outer attachment beside the explicit eye-row mapping. The ordering validator refuses crossed rows; all points still feed the same shared topology. This defines numerical shape freedom, not an accepted anatomical fit.
 * @evidence {@link Human.IPortraitLowerLidSection.margin} Owns the narrow outer skin margin before pretarsal fullness.
 * @evidenceReview {@link Human.IPortraitLowerLidSection.margin} #18946fc Followed this point to the ridge row while the inner aperture remains its own invariant. Its optional detailed offset/projection does not substitute for the separately drawn wet margin.
 * @evidence {@link Human.IPortraitLowerLidSection.pretarsalCrest} Places the roll's crest independently of its lower shoulder and crease.
 * @evidenceReview {@link Human.IPortraitLowerLidSection.pretarsalCrest} #d3dd668 Traced its mapping to the tarsal sampling row. The asymmetric-profile test changes this projection alone and verifies that higher lateral relief switches head-X side between anatomical eyes.
 * @evidence {@link Human.IPortraitLowerLidSection.pretarsalLower} Determines the roll's lower shoulder before the subtarsal boundary.
 * @evidenceReview {@link Human.IPortraitLowerLidSection.pretarsalLower} #b3f03e4 Read strict placement beyond the crest and before subtarsalInner, then its independent target in the shared skin row. It is not forced to equal the crest projection as in the basic envelope.
 * @evidence {@link Human.IPortraitLowerLidSection.subtarsalInner} Defines the roll-facing side of its lower boundary.
 * @evidenceReview {@link Human.IPortraitLowerLidSection.subtarsalInner} #27f3224 Checked the ordered offset and independent signed depth between pretarsalLower and subtarsalOuter. This local boundary is separate from the medial tear-trough field in orbital support.
 * @evidence {@link Human.IPortraitLowerLidSection.subtarsalOuter} Defines the preseptal-facing side of the subtarsal boundary.
 * @evidenceReview {@link Human.IPortraitLowerLidSection.subtarsalOuter} #697a736 Read its separate interpolation and mapping beyond subtarsalInner. Both sides can describe a recessed transition without turning the whole lower lid into a single inflated band.
 * @evidence {@link Human.IPortraitLowerLidSection.preseptal} Supplies a broader transition outside the pretarsal body and its lower boundary.
 * @evidenceReview {@link Human.IPortraitLowerLidSection.preseptal} #375fa45 Followed its position between subtarsalOuter and the live attachment. It controls the uppermost inserted outer row, while actual host depth supplies the final attachment rather than a copied absolute Z.
 * @evidence {@link Human.IPortraitLowerLidSection.attachment} Selects the section's outer reach on resident supporting skin.
 * @evidenceReview {@link Human.IPortraitLowerLidSection.attachment} #c1aeca2 Traced positive ordering beyond every tissue point, canthal width blending, the fit-stage depth query and the same append-stage section width. A missing host hit refuses; increasing reach is not itself a likeness correction.
 * @evidence {@link Human.IPortraitLowerLidProfile} Carries the complete optional medial-to-lateral section population for one eye.
 * @evidenceReview {@link Human.IPortraitLowerLidProfile} #fad1313 Read the two-to-32 section population, required zero/one endpoints and strict finite progress against the copied resolver. Eye construction chooses the basic path when the optional profile is absent and uses the owned resolver when present; a supplied empty list refuses rather than meaning omission.
 * @evidence {@link Human.IPortraitLowerLidProfile.sections} Specifies longitudinal variation without coupling the two eyes' handedness.
 * @evidenceReview {@link Human.IPortraitLowerLidProfile.sections} #b9bed27 Checked copied nested section data and uniform convex weights over each station interval. Returned samples are independently owned; mutation tests preserve the existing component and mirrored tests fail when right-side progress reversal is removed.
 * @evidence {@link Human.IPortraitUpperLidPoint} Names positive outward offsets and signed anterior relief over the actual ocular-to-skin bridge.
 * @evidenceReview {@link Human.IPortraitUpperLidPoint} #6a7002f Read the outward-offset/signed-relief pair against the upper row mapper. They use construction mm over a contact-to-host support bridge, not measured internal tissue thickness.
 * @evidence {@link Human.IPortraitUpperLidPoint.offset} Places each dry upper-tissue witness outward from the wet aperture in millimetres.
 * @evidenceReview {@link Human.IPortraitUpperLidPoint.offset} #a6724b2 Traced the positive offset through strict ordering and the planar rim normal. The central tarsal witness reaches y=3 from aperture y=2 with authored offset 1.
 * @evidence {@link Human.IPortraitUpperLidPoint.projection} Supplies signed upper-tissue relief independently of transverse placement.
 * @evidenceReview {@link Human.IPortraitUpperLidPoint.projection} #399d2a6 Read signed projection validation and replacement of the basic depth term. Negative crease values survive JSON; the independent quarter oracle retains each role's sign.
 * @evidence {@link Human.IPortraitUpperLidSection} Separates the six ordered upper tissue roles and farther host-skin attachment.
 * @evidenceReview {@link Human.IPortraitUpperLidSection} #5f0f4d7 Read all six named rows in order and their correspondence to shared lid rings. Tests retain separate upper/lower geometry and reject crossing crease offsets.
 * @evidence {@link Human.IPortraitUpperLidSection.margin} Owns the dry tissue row outside the unchanged wet contact rim.
 * @evidenceReview {@link Human.IPortraitUpperLidSection.margin} #bfb68f8 Traced margin to the ridge ring rather than the wet rim. The row test retains every wet point while detailed tissue changes outside it.
 * @evidence {@link Human.IPortraitUpperLidSection.tarsal} Controls the exposed body below the upper crease without adding basic tarsal volume twice.
 * @evidenceReview {@link Human.IPortraitUpperLidSection.tarsal} #f48fa03 Read the dedicated body point below the crease. The hand-known central point is (0,3,2); changing basic fold/volume controls leaves that fully selected detailed point unchanged.
 * @evidence {@link Human.IPortraitUpperLidSection.creaseInner} Sets the lower crease bank independently of its tarsal neighbour.
 * @evidenceReview {@link Human.IPortraitUpperLidSection.creaseInner} #0ee2eca Followed the lower crease bank into creaseInner, independently of tarsal and upper-bank depths. Crossing its predecessor or giving it NaN relief refuses in the profile test.
 * @evidence {@link Human.IPortraitUpperLidSection.creaseOuter} Sets the distinct upper crease bank before the overlying hood.
 * @evidenceReview {@link Human.IPortraitUpperLidSection.creaseOuter} #4d19ef9 Read the separate upper crease bank and strict successor order. Removing this required point from a serialized eye profile refuses at document admission.
 * @evidence {@link Human.IPortraitUpperLidSection.hood} Controls the hood edge independently of the two recessed crease banks.
 * @evidenceReview {@link Human.IPortraitUpperLidSection.hood} #3b88642 Traced the hood point to hoodEdge rather than to a second volume overlay. Input/result mutation of its relief and offset leaves the sampler's owned section unchanged.
 * @evidence {@link Human.IPortraitUpperLidSection.preseptal} Connects the upper fold into a broader outer tissue transition.
 * @evidenceReview {@link Human.IPortraitUpperLidSection.preseptal} #38de0d4 Read the last internal tissue point before the live attachment. Its depth participates in the same convex sampler, while the outer rim remains the host query's result.
 * @evidence {@link Human.IPortraitUpperLidSection.attachment} Places the live host-skin query beyond every internal tissue offset.
 * @evidenceReview {@link Human.IPortraitUpperLidSection.attachment} #a35f9a0 Read strict placement beyond all six points and its consumption by both fitting and rows. Real-socket edits move upper targets without moving lower targets; attachment at the last offset refuses.
 * @evidence {@link Human.IPortraitUpperLidProfile} Owns complete medial-to-lateral upper section witnesses independently on each eye.
 * @evidenceReview {@link Human.IPortraitUpperLidProfile} #5109c82 Read both complete populations: optional closedSections preserves witness coordinates and attachment distances while admitting an observed hood return. Without it all six offsets retain the prior strict order. The observed and closed arrays remain ordinary region data; no named-person or frozen first-face document is changed by this type extension.
 * @evidence {@link Human.IPortraitUpperLidProfile.sections} Replaces two through 32 ordered complete sections spanning zero to one.
 * @evidenceReview {@link Human.IPortraitUpperLidProfile.sections} #8012510 Read the complete two-to-32 population, required endpoints and whole-array replacement. Tests include a later interval, exact upper population bound, empty/duplicate/end omissions and a left three-to-two replacement.
 * @evidence {@link Human.createPortraitUpperLidProfile} Copies and admits upper role witnesses through the shared order-preserving sampler.
 * @evidence {@link Human.createPortraitLidSectionSampler} Owns the interpolation shared by upper and lower section profiles.
 * @evidenceReview {@link Human.createPortraitLidSectionSampler} #84d8c89 Read the full sampler and both anatomical callers. Finite positive tissue dimensions and attachment beyond every row are mandatory; the default enforces strict order, while an explicit anatomical callback checks authored and interpolated sections. All fields use the existing copied smoothstep witnesses. The folded upper consumer exercises the callback and interior crossing refusal; ordinary upper and lower callers retain their numerical path.
 * @evidenceReview {@link Human.createPortraitUpperLidProfile} #c973603 Read the ordered fallback, copied folded and closed samplers, matched witness/attachment check and observed-relative closure. The same stations reach the real eye rows. Hand arithmetic gives hood offset 2.25 and relief 0.6 halfway from observed 0.2 to current 0.6; crossing interior interpolation is refused despite valid ends. This is transverse-section admission, not final-surface collision or likeness approval.
 * @evidence {@link Human.createPortraitLowerLidProfile} Resolves ordered anatomical section witnesses for the actual eye consumer.
 * @evidenceReview {@link Human.createPortraitLowerLidProfile} #c8f314a Read delegation of the six existing lower roles into the common lid sampler. Copied admission, endpoint/order checks and convex operation order are retained. Quarter-oracle, population boundary, refusal and paired component tests pass. This adds no lower tissue or likeness verdict.
 * @evidence {@link Human.IPortraitEyeShape.lowerLidProfile} Selects detailed lower-tissue sections while preserving the basic omission path.
 * @evidenceReview {@link Human.IPortraitEyeShape.lowerLidProfile} #c06c53a Followed optional admission, copied resolution, anatomical progress reversal and replacement blending in the actual fit/append paths. The lower-lid component scenario retains the inner aperture and upper fitting controls while detailed lower rows change. The outer skin support and later optical contact remain separate responsibilities that can affect the resulting section.
 * @evidence {@link Human.IPortraitAegyoSalShape} Groups the optional pretarsal roll's crest, shoulder and longitudinal weights under one eye-owned surface responsibility.
 * @evidenceReview {@link Human.IPortraitAegyoSalShape} #73d926b Read the copied optional object and its finite dimensions beside the lower-row replacement branch; omission retains the eyelid-only path and supplied values are not a detached overlay.
 * @evidence {@link Human.IPortraitAegyoSalShape.offset} Places the single pretarsal crest immediately below the lower-lid margin.
 * @evidenceReview {@link Human.IPortraitAegyoSalShape.offset} #3104b22 Read positive admission and the lower-row offset blend at both canthal fades.
 * @evidence {@link Human.IPortraitAegyoSalShape.projection} Sets the crest's anterior relief independently of its shoulder.
 * @evidenceReview {@link Human.IPortraitAegyoSalShape.projection} #5edb036 Read nonnegative admission and the crest-to-shoulder projection falloff in the eye rows.
 * @evidence {@link Human.IPortraitAegyoSalShape.width} Declares the authored transverse support width of the pretarsal body.
 * @evidenceReview {@link Human.IPortraitAegyoSalShape.width} #bffc50c Read positive admission beside the continuous lower section's horizontal extent.
 * @evidence {@link Human.IPortraitAegyoSalShape.height} Declares the crest-to-shoulder distance of the rounded roll.
 * @evidenceReview {@link Human.IPortraitAegyoSalShape.height} #b1f248b Read positive admission beside the rapidly fading shoulder offsets.
 * @evidence {@link Human.IPortraitAegyoSalShape.reach} Bounds the optional roll's authored support reach.
 * @evidenceReview {@link Human.IPortraitAegyoSalShape.reach} #a020b28 Read finite positive admission; it remains a section control and does not create a second skin surface.
 * @evidence {@link Human.IPortraitAegyoSalShape.weights} Carries optional medial-to-lateral prominence across the seven lower-lid witnesses.
 * @evidenceReview {@link Human.IPortraitAegyoSalShape.weights} #c6051bf Read the seven-value bounded copy and the canthal fade in the actual lower-row mapping.
 * @evidence {@link Human.IPortraitEyeShape.cornealBoundary} Selects the closed shell's visible-aperture or full limbal boundary.
 * @evidenceReview {@link Human.IPortraitEyeShape.cornealBoundary} #63556d5 Read the shared eyeCornea extent selection: limbus supplies full iris-radius extents, while omission/aperture uses the clipped angular samples. The two-opening scenario preserves full limbal diameter and omitted/aperture equivalence. This choice supplies optical boundary geometry; the separate contact mode makes skin conform to it.
 * @evidence {@link Human.IPortraitEyeShape.lidContact} Selects inner optical support and final shared-eyelid contact with the full resident cornea.
 * @evidenceReview {@link Human.IPortraitEyeShape.lidContact} #682d58d Traced cornea/limbus admission, preconstruction inner support, retained sphere-projected outer guide and final complete-triangle contact. The engine supplies shared targets before common normals; the same optical builder supplies the rendered shell. Current directional separation is positive, but the wide lower pad remains an unaccepted anatomical shape.
 * @evidence {@link Human.IPortraitEyeShape.lidContactReach} Governs geodesic tissue adaptation around exact optical contact constraints.
 * @evidenceReview {@link Human.IPortraitEyeShape.lidContactReach} #842a388 Read the optional 3 mm default and nonnegative finite admission beside the shared skin adapter. Zero retains the complete face-contact targets with no surrounding spread; it no longer means that only original vertices were checked. The contact scenario distinguishes neighbouring adaptation and an empty contact population without treating either result as likeness acceptance.
 * @evidence {@link Human.IPortraitEyeSocket} Assigns caller-owned anatomical boundary identities to one replaceable eye.
 * @evidenceReview {@link Human.IPortraitEyeSocket} #042d18d Read the six members beside loopOf, fitting and brow construction. Both aperture paths share canthi and run in head-X order; the instance's anatomical side is separate from that order.
 * @evidence {@link Human.IPortraitEyeSocket.name} Selects anatomical handedness and side-qualified output identities.
 * @evidenceReview {@link Human.IPortraitEyeSocket.name} #7d1f6a8 Traced the left/right branches for outer-corner progress, medial tissues, lashes and brow bending. Positive head X is anatomical left; image-left is not substituted for that convention.
 * @evidence {@link Human.IPortraitEyeSocket.top} Supplies the upper aperture path and identifies which support rows receive a crease.
 * @evidenceReview {@link Human.IPortraitEyeSocket.top} #22819c6 Read top.includes in lidRows and the upper curve used by iris clipping and lashes. Its endpoint identities also participate in the lower loop, so corner membership does not create a second seam.
 * @evidence {@link Human.IPortraitEyeSocket.bottom} Supplies the lower aperture path in the same X direction as the upper path.
 * @evidenceReview {@link Human.IPortraitEyeSocket.bottom} #fb0a69b Followed the lower-first closed loop and the lower clipping lookup. Reversing this path would change winding and interpolation rather than simply rename an eye.
 * @evidence {@link Human.IPortraitEyeSocket.iris} Locates the independent gaze marker projected onto the fitted globe.
 * @evidenceReview {@link Human.IPortraitEyeSocket.iris} #76d587d Read the marker's exact zero-reach constraint and later sphere-ray intersection. It does not choose the lid-plane normal or a second spherical curvature.
 * @evidence {@link Human.IPortraitEyeSocket.browTop} Supplies the upper boundary of this eye's brow distribution.
 * @evidenceReview {@link Human.IPortraitEyeSocket.browTop} #2a35c47 Followed its retained IDs into buildPortraitEyebrow, where interpolated XY chooses fibre locations and actual final skin supplies contact depth. The boundary's sparse Z values are not used as the contact surface.
 * @evidence {@link Human.IPortraitEyeSocket.browBottom} Supplies the lower boundary from which brow fibre spans begin.
 * @evidenceReview {@link Human.IPortraitEyeSocket.browBottom} #2fbdd4d Compared its lower spline with the upper spline and the deterministic start/end fractions between them. Identical boundaries remove that cross-brow span, although outwardBend can still create a nonzero strand path. The eye copies this boundary array independently before final-skin sampling.
 * @evidence {@link Human.IPortraitEyeShape} Groups aperture, surrounding tissue, optical and sampling inputs for one eye instance.
 * @evidenceReview {@link Human.IPortraitEyeShape} #d664de1 Read the complete aperture, upper/lower tissue, optical, lash and sampling contract with input admission. Tangent support couples observation-ray fitting and radial optics, fixes the canthal midpoint, and shares one sampled support through expression. The optical radius no longer has to span exterior canthi in that mode; omission retains the all-rim fit. Tissue sections and contact remain separate owners, and no field infers clinical anatomy or accepts likeness.
 * @evidence {@link Human.IPortraitEyeShape.widthScale} Multiplies the aperture span about its measured horizontal midpoint.
 * @evidenceReview {@link Human.IPortraitEyeShape.widthScale} #3969d18 Read middleX+(x-middleX)*widthScale on both rim paths. The gaze marker is handled separately, so this dimension does not automatically scale the pupil or iris radius.
 * @evidence {@link Human.IPortraitEyeShape.openingScale} Multiplies aperture height about the extrema-derived vertical midpoint.
 * @evidenceReview {@link Human.IPortraitEyeShape.openingScale} #fc8118d Traced the same Y multiplier about middleY on both aperture paths before corner lift and sphere intersection. Zero and negative multipliers refuse at admission. The subsequent sphere and contact stages still determine the final boundary, and this multiplier does not supply lower-tissue thickness.
 * @evidence {@link Human.IPortraitEyeShape.outerCornerLift} Adds a signed millimetre lift that increases toward the anatomical outer canthus.
 * @evidenceReview {@link Human.IPortraitEyeShape.outerCornerLift} #4f12d9d Compared u for the left eye with 1-u for the right eye. Both paths use the same outer progress, retaining one corner position instead of lifting only the upper boundary.
 * @evidence {@link Human.IPortraitEyeShape.socketLift} Translates aperture and gaze together along the recorded view direction.
 * @evidenceReview {@link Human.IPortraitEyeShape.socketLift} #fffc0e7 Read the per-axis host.viewRay displacement and outer support's corresponding depth offset. This is a signed construction-distance control, not an increase in eye radius.
 * @evidence {@link Human.IPortraitEyeShape.blendReach} Limits the geodesic influence of the fitted outer eyelid on surrounding skin.
 * @evidenceReview {@link Human.IPortraitEyeShape.blendReach} #449affd Followed this nonnegative value into each outer-row constraint, beside the gaze marker's separate zero reach. It controls neighbouring adaptation rather than the width of the lid section.
 * @evidence {@link Human.IPortraitEyeShape.foldWidth} Sets the upper crease's planar separation from the aperture.
 * @evidenceReview {@link Human.IPortraitEyeShape.foldWidth} #3fa513b Read the sinusoid-weighted fold offsets across hood, crease and tarsal rows. The top-membership weight fades at both canthi and supplies no fold on the lower path.
 * @evidence {@link Human.IPortraitEyeShape.foldDepth} Recesses the upper crease relative to its ridge and hood.
 * @evidenceReview {@link Human.IPortraitEyeShape.foldDepth} #06bc857 Compared the negative depth at both crease rows with the positive fractions used by hood/tarsal rows. Increasing it changes a section relationship, not the aperture's XY contour.
 * @evidence {@link Human.IPortraitEyeShape.upperLidVolume} Adds tarsal support above the upper aperture.
 * @evidenceReview {@link Human.IPortraitEyeShape.upperLidVolume} #078db24 Located its sole contribution in the tarsal row multiplied by the upper weight. It cannot thicken the lower roll, whose separate lowerVolume term owns that side.
 * @evidence {@link Human.IPortraitEyeShape.lowerLidWidth} Controls the lower tissue transition's outward planar extent.
 * @evidenceReview {@link Human.IPortraitEyeShape.lowerLidWidth} #dfed770 Read its lower-only sine weight and fractional contributions to basic row offsets. Optional detailed sections blend toward their own offsets and attachment width, so this is not an independent override of a fully selected detailed section. Upper rows keep their fold-width path.
 * @evidence {@link Human.IPortraitEyeShape.lowerLidVolume} Raises the lower roll independently of its transition width.
 * @evidenceReview {@link Human.IPortraitEyeShape.lowerLidVolume} #d2324ed Traced the basic roll's lower-only amplitude through the tarsal and shoulder fractions. Detailed role projections replace these depths under the same canthal blend rather than adding a second roll. The current broad pad demonstrates why this scalar and its regular fractions do not by themselves define the desired pretarsal form.
 * @evidence {@link Human.IPortraitEyeShape.lidThickness} Supplies the forward depth of the aperture margin and neighbouring lid rows.
 * @evidenceReview {@link Human.IPortraitEyeShape.lidThickness} #0ddec62 Compared the inner point's Z increment and basic ridge's additional 0.08 mm with its separate use as final optical clearance in metres. Detailed role depths can replace basic row projections, but the complete contact pass still enforces this separation along the recorded ray. It is not a measured closed eyelid volume.
 * @evidence {@link Human.IPortraitEyeShape.surfaceRadius} Defines optical radius independently of gaze and, with tangent support, exterior canthal width.
 * @evidenceReview {@link Human.IPortraitEyeShape.surfaceRadius} #5951ffe Read both fitPortraitEyeSphere and fitPortraitCanthalSphere with the shared sclera and radial optics consumers. This authored millimetre radius remains at least the admitted corneal curvature. The legacy sphere must span the full rim; tangent mode fits supported rays and attaches exterior canthi separately without increasing optical radius. The diagnostic radius is not a recovered clinical measurement.
 * @evidence {@link Human.IPortraitEyeShape.cornealRadius} Sets the anterior optical cap curvature above the fitted globe.
 * @evidenceReview {@link Human.IPortraitEyeShape.cornealRadius} #c43aa0b Compared curvature against iris radius and globe radius, then read its sag contribution in buildPortraitCornea. The prescribed 7.8mm is a schematic assumption, not a recovered subject dimension.
 * @evidence {@link Human.IPortraitEyeShape.cornealThickness} Separates the optical shell's front and back and sets its material volume thickness.
 * @evidenceReview {@link Human.IPortraitEyeShape.cornealThickness} #6bd8e14 Followed the millimetre axial back-surface offset and the side-owned material's division by 1000. Geometry and optical metadata use one input; neither models the cornea's internal layers.
 * @evidence {@link Human.IPortraitEyeShape.cornealRimLift} Holds the optical shell above the underlying iris at its unclipped limbus.
 * @evidenceReview {@link Human.IPortraitEyeShape.cornealRimLift} #71c6947 Read the strict thickness+0.055 clearance admission and the constant rim offset in the cap surface. Angular clipping does not refit that lift or curvature for each column.
 * @evidence {@link Human.IPortraitEyeShape.irisRadius} Defines the pigment and corneal disk before the eyelid clips their visible reach.
 * @evidenceReview {@link Human.IPortraitEyeShape.irisRadius} #5a1cb99 Followed it into the pigment disk's angular clipping and the cornea's declared unclipped radius. Aperture mode forwards clipped extents; limbus mode restores full-radius columns. The pupil keeps its own smaller radius, and this input does not independently widen the fitted lid opening.
 * @evidence {@link Human.IPortraitEyeShape.pupilRadius} Defines the inner dark disk independently of the iris extent.
 * @evidenceReview {@link Human.IPortraitEyeShape.pupilRadius} #f5a2bf6 Read the positive radius and pupil<iris refusal, then its separately clipped disk with the 0.09mm surface offset. This opaque approximation does not model an internal eye cavity.
 * @evidence {@link Human.IPortraitEyeShape.tissues} Optionally supplies medial conjunctiva and the narrow lower ocular margin.
 * @evidenceReview {@link Human.IPortraitEyeShape.tissues} #ae7fd66 Checked the copied scalar profile and omission/independent-disable branches, then the live lid curves and resident sclera/cornea support in the finisher. Complete emitted-triangle contact now keeps the wet margin outside that support. These narrow conjunctival surfaces do not construct the external lower-lid body selected by lowerLidProfile.
 * @evidence {@link Human.IPortraitEyeShape.browFibres} Selects the number of explicit brow strands generated on the final forehead.
 * @evidenceReview {@link Human.IPortraitEyeShape.browFibres} #ec1b81a Read the zero-fibre return and the 4096 upper bound in the brow owner. This integer controls a mesh population, not the brow boundary or anatomical eye opening.
 * @evidence {@link Human.IPortraitEyeShape.browProfile} Supplies strand dimensions while retaining subject-owned brow boundaries.
 * @evidenceReview {@link Human.IPortraitEyeShape.browProfile} #6cf577e Traced the copied supplied/default profile through assertPortraitEyebrowProfile and final-skin contact. Changing fibre clearance or bending cannot substitute for moving the brow's upper/lower sockets.
 * @evidence {@link Human.IPortraitEyeShape.upperLashes} Sets the positive integer population of short lashes along the upper rim.
 * @evidenceReview {@link Human.IPortraitEyeShape.upperLashes} #1073d9d Read the evenly distributed u values and side-dependent outward curl. The separately built lash-line tube remains present independently of this count.
 * @evidence {@link Human.IPortraitEyeShape.sampling} Separates ocular mesh resolution from the eye's anatomical dimensions.
 * @evidenceReview {@link Human.IPortraitEyeShape.sampling} #5a9fed3 Followed eyeColumns/eyeRows into sclera sampling and irisColumns/irisRows into pigment and corneal sampling. Integer minima protect their lattices; a denser lattice does not certify likeness.
 * @evidence {@link Human.IPortraitEyeSphere} States the common centre and radius of the fitted optical surface in millimetres.
 * @evidenceReview {@link Human.IPortraitEyeSphere} #ef3af5e Read centre and radius against fitting, intersection and height consumers. Radius is a positive authored optical curvature control and centre lies behind the fitted aperture; neither is inferred from an emotion or asserted as a physiological measurement.
 * @evidence {@link Human.fitPortraitEyeSphere} Fits the globe from the lid plane independently of the gaze marker.
 * @evidenceReview {@link Human.fitPortraitEyeSphere} #205917a Read both fitting directions and their shared mean-rim residual. The default canthal-plane arithmetic is retained; observation-ray mode fixes the reference rim mean projection, rejects degenerate or undersized inputs and does not read current gaze. The tilted unit-circle oracle and rigid-frame test distinguish the modes. This is an authored surface basis, not recovered globe anatomy.
 * @evidence {@link Human.portraitEyeSphereIntersection} Places gaze/lid samples on the fitted globe along the supplied viewing ray.
 * @evidenceReview {@link Human.portraitEyeSphereIntersection} #6e879fb Read the normalized-ray quadratic and camera-facing root. The slanted radius-two oracle retains collinearity, while a missed sphere or zero ray refuses. This preserves projection only for the declared viewing direction.
 * @evidence {@link Human.portraitEyeSphereHeight} Supplies the anterior spherical height shared by sclera and pigment surfaces.
 * @evidenceReview {@link Human.portraitEyeSphereHeight} #e553bae Compared radius squared minus transverse squared distance with the positive square root. Tangency is finite, samples outside the disk refuse, and the same radius gives equal horizontal/vertical curvature.
 * @evidence {@link Human.IPortraitCornea} Defines the closed optical shell's aperture, curvature, axial thickness and live globe support.
 * @evidenceReview {@link Human.IPortraitCornea} #c5a8df5 Read every field in the millimetre frame: unclipped radius bounds the angular extents, curvature exceeds that radius, globeRadius bounds curvature, and rimLift clears thickness. The surface callback supplies fitted depth; these controls are a rendering model, not measured physiology.
 * @evidence {@link Human.buildPortraitCornea} Constructs the joined anterior/posterior shell delivered with optical volume materials.
 * @evidenceReview {@link Human.buildPortraitCornea} #ae6b51a Traced corneal sag minus globe sag, one axial vertex per pole, reversed back winding and shared outer-ring closure. Clipping changes radial reach without refitting curvature per column. The actual export's volume topology gate checks closure; opaque clay display does not judge refraction.
 * @evidence {@link Human.createPortraitOcularTissues} Builds owned medial conjunctiva and wet lower-margin profiles against supplied live ocular support.
 * @evidenceReview {@link Human.createPortraitOcularTissues} #4f9129f Read the complete factory, interval/sample admission, mirrored medial section, separate mound/ridge terms and clipped lower strip. Shape ownership, mirrored and translated frames, independent disabling and invalid dimensions/samples are covered by the tissue scenarios. The assembled eye additionally fits these meshes against its resident optical shell; the factory alone neither solves full triangle contact nor accepts the still-synthetic lower-lid form.
 * @evidence {@link Human.buildPortraitEye} Builds resident ocular surfaces, pigment, lashes and brows from the final shared lid boundary.
 * @evidenceReview {@link Human.buildPortraitEye} #91c8a85 Read the complete final-rim, optical, tissue, lash and brow finisher with eyeOpticalSurface, geometry scaling and the canthal hull. Exposed sphere faces and connective faces partition one boundary, with shared normals and the same triangles for contact. Exact lid interpolation endpoints prevent an endpoint X from being paired with an interior Y/Z outside a canthal apex; interior samples retain bisection. Wet support queries use the same millimetre-to-metre multiplication as portraitPart. Static, half-closed/gazing and closed analytic components exercise actual finishers. Remaining eyelid protrusion requires rendered anatomy review; this source inspection is not likeness acceptance.
 * @evidence {@link Human.IPortraitEyelashProfile} Defines the optional seven-field upper-lash shape separately from lid aperture and optical size.
 * @evidenceReview {@link Human.IPortraitEyelashProfile} #8079554 Read the seven required values and observed head-frame angle convention. The eye's omitted-profile branch retains the old geometry; selecting this profile supports rigid lid-relative radial transport, but adds neither lower lashes nor hair dynamics.
 * @evidence {@link Human.IPortraitEyelashProfile.length} Sets a maximum centreline arc length, not a projected height.
 * @evidenceReview {@link Human.IPortraitEyelashProfile.length} #9a2cb40 Read the two shortening factors at construction: the canthal envelope and deterministic growth weight both stay at or below one. Curl uses the arc integral and does not rescale this length.
 * @evidence {@link Human.IPortraitEyelashProfile.elevation} Sets the root tangent relative to anterior head Z.
 * @evidenceReview {@link Human.IPortraitEyelashProfile.elevation} #c9a8685 Read the degree-to-radian conversion and the later root-centred transport separately. This launch angle describes the observed head frame; a change in lid closure carries it with the globe-relative direction, while gaze alone adds no turn.
 * @evidence {@link Human.IPortraitEyelashProfile.curl} Controls signed root-to-tip tangent rotation.
 * @evidenceReview {@link Human.IPortraitEyelashProfile.curl} #2868d4e Read the stable sinc integral and the straight zero-turn branch. Radius times absolute turn must remain below the effective arc length to avoid an inner sweep singularity.
 * @evidence {@link Human.IPortraitEyelashProfile.fan} Mirrors the medial-to-lateral strand fan between eyes.
 * @evidenceReview {@link Human.IPortraitEyelashProfile.fan} #56a0c9f Read anatomical progress from the eye caller and the side sign in the builder. The constant horizontal frame stays orthogonal to the turning tangent, including a straight anterior strand.
 * @evidence {@link Human.IPortraitEyelashProfile.radius} Defines the root cross-section radius.
 * @evidenceReview {@link Human.IPortraitEyelashProfile.radius} #4fa5f7f Read its shared scalar bounds and its separate use in the ring offsets. It changes thickness, not the centreline or aperture.
 * @evidence {@link Human.IPortraitEyelashProfile.taper} Reduces the radius along the strand without collapsing its tip.
 * @evidenceReview {@link Human.IPortraitEyelashProfile.taper} #2a079b1 Read radius times one minus taper times progress. The inclusive 0.98 maximum retains a positive end ring rather than a repeated pole.
 * @evidence {@link Human.IPortraitEyelashProfile.variation} Selects deterministic per-strand shortening.
 * @evidenceReview {@link Human.IPortraitEyelashProfile.variation} #28e0ab8 Read the cosine-squared index sequence and the half-scale maximum. There is no random state, scene time or person name in this variation.
 * @evidence {@link Human.portraitEyelashParameters} Shares seven scalar envelopes between lash admission and eye detail sliders.
 * @evidenceReview {@link Human.portraitEyelashParameters} #a48d39b Read every bound, unit, step and effect against the profile and construction. These are authoring envelopes, not population-derived anatomical limits or proof that all combinations clear skin.
 * @evidence {@link Human.assertPortraitEyelashProfile} Rejects incomplete and out-of-envelope profiles before eye fitting.
 * @evidenceReview {@link Human.assertPortraitEyelashProfile} #e2fdc10 Read the finite and inclusive-bound checks over every required field. The coupled curvature-radius refusal belongs to the strand builder after its per-strand length is known.
 * @evidence {@link Human.buildPortraitEyelash} Builds the optional curved strand rooted on the current upper margin.
 * @evidenceReview {@link Human.buildPortraitEyelash} #fe7dd98 Read the full sweep and optional radial motion admission. Normalized observed/current directions define the shortest rigid turn about the current root; parallel inputs keep the unrotated arithmetic and antipodes refuse. Circle, normal and downward-turn unit tests pass. Length, radius and the eye's metre conversion remain independent of this turn; torsion and collisions are not modeled.
 * @evidence {@link Human.IPortraitEyeShape.upperLashProfile} Opts into the new shape while omission retains the original upper-lash formula.
 * @evidenceReview {@link Human.IPortraitEyeShape.upperLashProfile} #455a4b8 Read the optional admission and the finisher's two branches. Existing documents without this field keep their original tube formula; selecting it does not change the eye's aperture or its skin fitting inputs.
 */
export const portraitOcularReview = { scope: "ocular construction inspection" };
