import type * as Human from "@automovie/human";

/**
 * Lips, oral enclosure, tongue, teeth and mandibular performance.
 * The frozen study root retains this domain through the native evidence graph.
 * Existing source inspections and historical capture limitations are preserved
 * verbatim. This carrier neither changes geometry nor accepts current likeness;
 * artifact observations and identities remain in review.md and the root record.
 *
 * @evidence {@link Human.IPortraitOralChamber} Inspects complete internal-room dimensions separately from the aperture and tooth placement.
 * @evidenceReview {@link Human.IPortraitOralChamber} #34f99a3 Read the three millimetre fields and their actual lining and mouth consumers; they are authored enclosure dimensions, not measured hidden tissue.
 * @evidence {@link Human.IPortraitOralChamber.horizontalExpansion} Inspects the independent transverse half-extent increment.
 * @evidenceReview {@link Human.IPortraitOralChamber.horizontalExpansion} #3b48034 Read finite nonnegative admission and its normalized head-X contribution behind the unchanged lip rim.
 * @evidence {@link Human.IPortraitOralChamber.verticalExpansion} Inspects the independent vertical half-extent increment.
 * @evidenceReview {@link Human.IPortraitOralChamber.verticalExpansion} #2a0bda8 Read finite nonnegative admission and its normalized head-Y contribution, with no lip opening or tooth translation.
 * @evidence {@link Human.IPortraitOralChamber.transitionDepth} Inspects the vestibular depth controlling smooth expansion.
 * @evidenceReview {@link Human.IPortraitOralChamber.transitionDepth} #835bfe2 Read positive finite admission and the clamped depth ratio used by cubic smoothstep, independent of the posterior taper and cavity depth.
 * @evidence {@link Human.assertPortraitOralLining} Admits the selected enclosure dimensions.
 * @evidenceReview {@link Human.assertPortraitOralLining} #9856d65 Read positive representable depth and the inclusive wall fraction, now followed by three finite chamber dimensions. Expansions admit zero and reject negatives; transition depth must be positive. Both mouth entry points validate a selected chamber even when closed, and a missing wall fails admission.
 * @evidence {@link Human.tracePortraitOralBoundary} Inspects the seeded actual skin attachment consumed by the lining.
 * @evidenceReview {@link Human.tracePortraitOralBoundary} #ba44c3c Read complete resident triangles, distinct vertices, opposed manifold edges, unique outgoing boundary edges, seeded cycle traversal and finite noncollapsed rim admission. The cancellation invariant justifies traversal without a proximity heuristic. The returned indices are owned; input coordinates are untouched. Independent inner/outer annuli and the prior refusal cases exercise the consumer. This establishes attachment topology, not oral containment.
 * @evidence {@link Human.buildPortraitOralLining} Joins a cavity to the final lip boundary.
 * @evidenceReview {@link Human.buildPortraitOralLining} #2c8004d Read the entire compatibility call and native owner. It preserves all dimension/topology refusal, exact copied rim, chamber expansion, posterior cap and normal behavior. Only native callers additionally retain the already traced skin IDs; this remains an aperture-relative enclosure without a measured palate, floor or clearance guarantee.
 * @evidence {@link Human.IPortraitOralAttachment} Defines one shared interior attachment.
 * @evidenceReview {@link Human.IPortraitOralAttachment} #d232196 Read the chord, independent up guide, origin and signed millimetre offsets. The frame orients complete interiors and never scales their local dimensions.
 * @evidence {@link Human.IPortraitOralAttachment.rightCorner} Supplies the anatomical right endpoint.
 * @evidenceReview {@link Human.IPortraitOralAttachment.rightCorner} #a170bb2 Read its role as the origin of the right-to-left transverse chord. It is not a tooth or tongue vertex placement.
 * @evidence {@link Human.IPortraitOralAttachment.leftCorner} Supplies the anatomical left endpoint.
 * @evidenceReview {@link Human.IPortraitOralAttachment.leftCorner} #c8d2fcd Read the subtraction from rightCorner and the zero-length refusal. Positive X remains anatomical left.
 * @evidence {@link Human.IPortraitOralAttachment.origin} Supplies the independent oral anchor.
 * @evidenceReview {@link Human.IPortraitOralAttachment.origin} #a16ea94 Read the single lift/recess translation. Dental callers supply the upper lip; the tongue supplies the observed lower midpoint.
 * @evidence {@link Human.IPortraitOralAttachment.up} Defines superior orientation independently.
 * @evidenceReview {@link Human.IPortraitOralAttachment.up} #5a0eae3 Read removal of its chord projection and the degenerate independent-axis refusal before the shared transform.
 * @evidence {@link Human.IPortraitOralAttachment.lift} Places the interior along superior Y.
 * @evidenceReview {@link Human.IPortraitOralAttachment.lift} #0001cae Read signed translation after orthogonalization. The tongue uses negative drop, while the dental adapter retains its original signed lift.
 * @evidence {@link Human.IPortraitOralAttachment.recess} Places the interior posteriorly.
 * @evidenceReview {@link Human.IPortraitOralAttachment.recess} #e830871 Read subtraction along X cross Y. This is rigid placement and does not change the cavity wall or guarantee tissue clearance.
 * @evidence {@link Human.attachPortraitOralMesh} Shares dental and lingual placement arithmetic.
 * @evidenceReview {@link Human.attachPortraitOralMesh} #5d7e75e Read the extracted complete transform, copied buffers, degenerate frame, normal alignment and representable-output guards. The dental adapter delegates its former arithmetic; this reading is separate from execution and likeness.
 * @evidence {@link Human.IPortraitTongueShape} Owns optional lingual dimensions and finish.
 * @evidenceReview {@link Human.IPortraitTongueShape} #a4272a4 Read every required dimension and the independent observed oral placement. Omission does not invent a body; the complete selected profile requires a hinge in document resolution.
 * @evidence {@link Human.IPortraitTongueShape.halfWidth} Controls transverse body extent.
 * @evidenceReview {@link Human.IPortraitTongueShape.halfWidth} #1aa4e73 Read the sine envelope multiplying the transverse cosine. Endpoints remain fixed and it does not resize teeth.
 * @evidence {@link Human.IPortraitTongueShape.length} Controls posterior body extent.
 * @evidenceReview {@link Human.IPortraitTongueShape.length} #76cc93a Read negative longitudinal progress and the separate retraction-monotonicity guard. This length is an authoring value, not a recovered anatomical measurement.
 * @evidence {@link Human.IPortraitTongueShape.halfThickness} Controls both vertical half-sections.
 * @evidenceReview {@link Human.IPortraitTongueShape.halfThickness} #810b921 Read the radial sine term before centreline elevation and the strict groove-depth comparison.
 * @evidence {@link Human.IPortraitTongueShape.dorsumRise} Stores the observed centreline rise.
 * @evidenceReview {@link Human.IPortraitTongueShape.dorsumRise} #516ed31 Read its sine-squared envelope and observed-relative performance addition. It changes neither endpoint.
 * @evidence {@link Human.IPortraitTongueShape.grooveDepth} Controls upper median depression.
 * @evidenceReview {@link Human.IPortraitTongueShape.grooveDepth} #0930e33 Read the Gaussian transverse field multiplied by nonnegative radial sine. The inferior surface receives no groove depression.
 * @evidence {@link Human.IPortraitTongueShape.grooveWidth} Sets the Gaussian transverse scale.
 * @evidenceReview {@link Human.IPortraitTongueShape.grooveWidth} #664f265 Read division of X by this strictly positive scale before squaring; increasing spreads depression without changing its central amplitude.
 * @evidence {@link Human.IPortraitTongueShape.drop} Sets inferior observed placement.
 * @evidenceReview {@link Human.IPortraitTongueShape.drop} #b44d5ab Read negative lift in the shared oral frame. Jaw motion acts afterward, and lip performance cannot translate this captured body.
 * @evidence {@link Human.IPortraitTongueShape.recess} Sets posterior observed placement.
 * @evidenceReview {@link Human.IPortraitTongueShape.recess} #4b1b661 Read its use in the shared frame before weighted mandibular motion. The cavity wall remains an independently authored surface.
 * @evidence {@link Human.IPortraitTongueShape.material} Selects an existing lingual finish.
 * @evidenceReview {@link Human.IPortraitTongueShape.material} #efa56e4 Read the nonempty identity check and unchanged propagation to the resident part. It adds no implicit palette entry; complete model validation still requires that finish.
 * @evidence {@link Human.portraitTongueParameters} Shares tongue shape editing envelopes.
 * @evidenceReview {@link Human.portraitTongueParameters} #8b4d955 Read all eight dimensions against their type, validator and detail-channel consumer. They are editing bounds rather than biological ranges.
 * @evidence {@link Human.assertPortraitTongueShape} Admits the complete lingual profile.
 * @evidenceReview {@link Human.assertPortraitTongueShape} #0b843a1 Read all scalar bounds, strict groove versus half-thickness and nonblank finish checks. It does not certify interaction with surrounding tissues.
 * @evidence {@link Human.buildPortraitTongue} Builds the closed local lingual surface.
 * @evidenceReview {@link Human.buildPortraitTongue} #d0eff0f Read shared endpoint poles, indexed ring winding, upper-only groove, observed-relative rise/advance and the longitudinal reversal refusal. Normals come from the resulting geometry; this is not a muscle or volume-conservation model.
 * @evidence {@link Human.createPortraitTongueComponent} Connects lingual shape to the real face component protocol.
 * @evidenceReview {@link Human.createPortraitTongueComponent} #c54bc1b Read cloned inputs, expression resolution, socket/hinge admission, local tongue shape, observed lower attachment and anterior-to-posterior weighted jaw motion. Normals are regenerated after deformation. Native preparation clones the performed millimetre mesh, and direct finish packs the same producer. The fixed posterior point remains a kinematic approximation, not tissue simulation or clearance.
 * @evidence {@link Human.portraitJawSkinWeight} Shares the observed oral-band attachment field.
 * @evidenceReview {@link Human.portraitJawSkinWeight} #252d0c7 Read finite heights and derived differences, the four-mm minimum, bounded cubic weight and both consumers. This is a kinematic transition, not a measured muscle distribution.
 * @evidence {@link Human.createPortraitJawContinuation} Connects mandibular motion to reference-formed head and neck.
 * @evidenceReview {@link Human.createPortraitJawContinuation} #771a24c Read matching-angle omission and the changed angular continuation. The frozen study keeps its observed angle and therefore bypasses this field without changing its basis or reference fit. For performed derivatives, full mandibular attachments delimit a monotone cervical transition, while actual face constraints and inverse restoration retain their existing ownership. Angular-clearance and hinge-height refusals are active only when constructing this continuation; this does not certify likeness or complete-head nonintersection.
 * @evidence {@link Human.IPortraitMouthPerformance} Records observed/current separation, mandibular angles and optional commissure/protrusion changes.
 * @evidenceReview {@link Human.IPortraitMouthPerformance} #d246a56 Read each channel's physical units and limits, explicit hinge ownership, signed smile differences and pucker narrowing. The observed seam is an input calibration; these fields do not replace identity vermilion sections or dental dimensions.
 * @evidence {@link Human.createPortraitMandibularDentition} Attaches independently authored lower crowns to the observed jaw and moves the intact row.
 * @evidenceReview {@link Human.createPortraitMandibularDentition} #1f406f7 Read row preparation, inferior reflection of positions/normals, triangle reversal, attachment and one observed-relative jaw rotation. Native cervical cycles reverse with the reflected faces and are freshly copied alongside the posed mesh. The analytic ten-degree case checks their direction independently. Lip performance and occlusion retain their separate owners.
 * @evidence {@link Human.createPortraitMouthPerformance} Poses the actual paired oral margins while retaining the surrounding vermilion volume.
 * @evidenceReview {@link Human.createPortraitMouthPerformance} #4743922 Read ordered finite equal-length margins and shared corners, inverse observed jaw, zero-observation seam admission, three-dimensional closure, current jaw reapplication, smile and pucker decoration, exact unchanged path and piecewise displacement sampler. Outputs must remain finite and ordered. Neutral GPU frames hide the upper row behind closed lips; this is not an interarch collision certificate.
 * @evidence {@link Human.posePortraitJawPoint} Applies one bounded weighted mandibular rotation about the authored transverse hinge.
 * @evidenceReview {@link Human.posePortraitJawPoint} #2e7e156 Read finite point/hinge/angle/weight admission, copied zero-motion identity, X-axis quaternion rotation using angle times weight and result overflow refusal. Opposite angles use the same attachment weight, so inverse observation does not switch to linear positional blending.
 * @evidence {@link Human.IPortraitDentalSideContour} Supplies optional mesial/distal detail within one crown's basic profile.
 * @evidenceReview {@link Human.IPortraitDentalSideContour} #9395cb4 Read the three independently optional overrides and their nullish defaults in admission and loft construction. Empty side objects reproduce the basic mesh exactly. Mesial direction comes from the row, so a side profile does not carry an independently guessed world orientation.
 * @evidence {@link Human.IPortraitDentalSideContour.contactHeight} Locates the proximal breadth crest along the normalized loft height.
 * @evidenceReview {@link Human.IPortraitDentalSideContour.contactHeight} #8725c13 Followed the default 0.3 and strict (0,1) range into the breadth branches and the union of sampling levels. Off-grid 0.23 and 0.37 crests are explicitly sampled. Actual Y additionally includes the decaying incisal-rise term, so this parameter is not the final Y coordinate divided by crown height.
 * @evidence {@link Human.IPortraitDentalSideContour.cervicalWidth} Overrides one side's cervical-to-maximum half-width ratio.
 * @evidenceReview {@link Human.IPortraitDentalSideContour.cervicalWidth} #94ab7d1 Compared the per-side fallback with the post-crest narrowing formula and its (0,1] admission. The asymmetric eight-millimetre crown ends at cervical X=-2.8 and +3.6 mm while retaining maximum X=-4 and +4 mm elsewhere. Swapping the row's mesial direction exchanges those sides.
 * @evidence {@link Human.IPortraitDentalSideContour.incisalRise} Overrides one proximal cutting-edge corner's rise from the central edge.
 * @evidenceReview {@link Human.IPortraitDentalSideContour.incisalRise} #2cf9d34 Read the signed-X side selection, nonnegative half-height bound and rise*x²*(1-v)^4 contribution to Y. Explicit zero is retained instead of falling back to the crown's base rise; the asymmetric scenario gives the two independently calculated edge heights without rotating the tooth.
 * @evidence {@link Human.applyPortraitOralContact} Resolves one optional named lip/enamel/cavity relationship on assembled head parts.
 * @evidenceReview {@link Human.applyPortraitOralContact} #72dd87c Read omission identity, distinct requested names, exactly one resident match, mesh/transform/bone-frame admission and replacement of only enamel and lining. The binding scenario rejects missing, ambiguous, duplicate-role and foreign-frame inputs while retaining the actual lip and unrelated part objects. It does not infer contact ownership from every mesh whose bounds happen to overlap.
 * @evidence {@link Human.fitPortraitOralContact} Places the rigid enamel group behind its lip and then fits the cavity behind that placed group.
 * @evidenceReview {@link Human.fitPortraitOralContact} #a9cafe0 Read the maximum directional lip/enamel deficit into one posterior translation of the intact crown group, followed by lining targets against the moved teeth and refreshed lining normals. Independent-plane tests distinguish rigid retreat from per-tooth reshaping; this optional relation is not an occlusion solver.
 * @evidence {@link Human.IPortraitMouthSocket} Binds the oral opening and surrounding vermilion to subject-owned vertex identities.
 * @evidenceReview {@link Human.IPortraitMouthSocket} #fd28022 Read the closed outer loop, two equally directed inner paths and interior seed beside band flooding and coordinate construction. The mouth copies all three arrays; their anatomical ownership is supplied by the subject rather than inferred from arbitrary point height.
 * @evidence {@link Human.IPortraitMouthSocket.outer} Defines the cutaneous-vermilion boundary shared with surrounding skin.
 * @evidenceReview {@link Human.IPortraitMouthSocket.outer} #a90f5c6 Traced this loop into flood barriers, lip-band coordinates and the optional shared curve returned at attachment. It bounds the colour/tissue band and is not the inner oral opening that the host removes.
 * @evidence {@link Human.IPortraitMouthSocket.upper} Supplies the upper inner lip in increasing head-X order.
 * @evidenceReview {@link Human.IPortraitMouthSocket.upper} #7924c92 Read its reversed interior contribution to the closed oral loop, its role in local band classification and its later use by cavity and legacy dental-arch construction. Its endpoints are shared with the lower path rather than duplicated corners.
 * @evidence {@link Human.IPortraitMouthSocket.lower} Supplies the lower inner lip in the same longitudinal direction.
 * @evidenceReview {@link Human.IPortraitMouthSocket.lower} #c75c417 Followed its direct contribution to innerLoop and the lower surface of the interpolated cavity. The local lip sampler distinguishes this curved boundary from the upper one even near raised smile corners.
 * @evidence {@link Human.IPortraitMouthSocket.lipSeed} Identifies the connected vermilion region for material assignment.
 * @evidenceReview {@link Human.IPortraitMouthSocket.lipSeed} #003eb28 Read selection of an incident seed triangle before flooding between the two barrier loops. A missing seed refuses; the subject must place the seed inside the intended band because merely appearing in a triangle does not infer the correct anatomy.
 * @evidence {@link Human.IPortraitMouthShape} Declares lip fitting and the separate legacy cavity/crown settings.
 * @evidenceReview {@link Human.IPortraitMouthShape} #644ef4f Read the complete oral shape and the new optional cavityChamber profile beside cavityWall. The selected complete profile separates internal transverse/vertical room and transition depth from lip aperture and dental placement. Omission retains the former path; the frozen study document is not changed.
 * @evidence {@link Human.IPortraitMouthShape.widthScale} Scales band and opening X positions about the measured oral midpoint.
 * @evidenceReview {@link Human.IPortraitMouthShape.widthScale} #f261a81 Located centerX+(pointX-centerX)*widthScale in each selected lip target. It has positive finite admission and changes the mouth's geometry, while legacy tooth widths remain independently supplied enamel dimensions.
 * @evidence {@link Human.IPortraitMouthShape.openingScale} Scales fitted Y positions about the measured inner opening centre.
 * @evidenceReview {@link Human.IPortraitMouthShape.openingScale} #3837797 Read its application after optional local band-thickness scaling and before corner lift. The positive multiplier affects opening and band placement around centerY; it is not the same operation as upper/lower band ratios anchored to their local inner curves.
 * @evidence {@link Human.IPortraitMouthShape.cornerLift} Applies a signed smile-corner Y adjustment with a quadratic lateral weight.
 * @evidenceReview {@link Human.IPortraitMouthShape.cornerLift} #81d2c75 Traced the clamped absolute lateral fraction and cornerLift*corner². The term vanishes at the midpoint and reaches its configured value at the sides, while the independent Z projection uses the complementary weight.
 * @evidence {@link Human.IPortraitMouthShape.upperLipProjection} Adds the basic upper-band Z projection.
 * @evidenceReview {@link Human.IPortraitMouthShape.upperLipProjection} #2ce6f29 Read selection by the local curved band side and multiplication by 1-corner². Zero removes this term, but optional section relief and later skin fields remain separate contributors; the scalar does not independently locate a vermilion crest.
 * @evidence {@link Human.IPortraitMouthShape.lowerLipProjection} Adds basic lower-band projection independently of the upper value.
 * @evidenceReview {@link Human.IPortraitMouthShape.lowerLipProjection} #38a77c2 Compared the lower branch of the same local-side choice with upperLipProjection. It keeps the same corner fade and Z direction without using global Y to decide which band a raised corner belongs to.
 * @evidence {@link Human.IPortraitMouthShape.section} Supplies optional body, tubercle and pad relief inside the retained lip bands.
 * @evidenceReview {@link Human.IPortraitMouthShape.section} #d3f1a79 Followed the owned createPortraitLipSection closure into the additional Z term of each lip target. Omission contributes zero; the section's edge/corner fade is distinct from the basic upper/lower projection terms and does not move a second lip mesh.
 * @evidence {@link Human.IPortraitMouthShape.band} Selects independent scalar or knot-array thickness ratios for the two curved bands.
 * @evidenceReview {@link Human.IPortraitMouthShape.band} #7eea962 Read upper/lower scale resolvers and height=innerY+(pointY-innerY)*ratio, with an exact identity branch. The local inner curve anchors each change before overall openingScale and cornerLift; neighbouring outer skin follows the resulting fitting constraints.
 * @evidence {@link Human.IPortraitMouthShape.blendReach} Limits original-skin adaptation around the fitted lip targets.
 * @evidenceReview {@link Human.IPortraitMouthShape.blendReach} #a42ef98 Traced nonnegative finite admission and the same reach on every selected-band constraint. It controls the geodesic fitting stage, while the later shared subdivision and surface fields have their own effects on neighbouring samples.
 * @evidence {@link Human.IPortraitMouthShape.cavityDepth} Recesses the cavity behind the actual refined oral opening.
 * @evidenceReview {@link Human.IPortraitMouthShape.cavityDepth} #13976a2 Read the positive value multiplying 1+0.8*sin(pi*v) in cavity Z. The cavity lies one configured depth behind its boundary interpolation and 1.8 depths behind the transverse centre; this dark backdrop is not modeled tongue or gum tissue.
 * @evidence {@link Human.IPortraitMouthShape.dentalOffset} Shifts the legacy crown row along the sampled dental arch.
 * @evidenceReview {@link Human.IPortraitMouthShape.dentalOffset} #382855a Located the signed offset in arch.center+dentalOffset-rowLength/2 before walking individual crown widths. It changes longitudinal placement rather than width or recession, and is unused when this mouth's crowns list is empty.
 * @evidence {@link Human.IPortraitMouthShape.dentalRecess} Moves legacy crown placement posterior to the sampled upper-lip guide.
 * @evidenceReview {@link Human.IPortraitMouthShape.dentalRecess} #fdf128f Checked nonnegative admission and subtraction from at.z before the rotated local crown contribution. The active grouped dentition has its own placement owner; this value applies only to buildPortraitMouth's nonempty legacy row.
 * @evidence {@link Human.IPortraitMouthShape.dentalDrop} Places legacy crowns below their sampled arch Y coordinate.
 * @evidenceReview {@link Human.IPortraitMouthShape.dentalDrop} #d3837ce Read at.y-dentalDrop+localY after crown construction. This nonnegative millimetre offset is not crown height and does not influence the cavity when the early empty-row return is taken.
 * @evidence {@link Human.IPortraitMouthShape.dentalDepth} Supplies the common local half-depth of legacy crowns.
 * @evidenceReview {@link Human.IPortraitMouthShape.dentalDepth} #f319326 Followed the positive finite dimension into both crown validation and construction. It changes enamel geometry before arch rotation, unlike dentalRecess, which changes placement; it is not the depth control of the active separate dental group.
 * @evidence {@link Human.IPortraitMouthShape.toothGap} Adds longitudinal clearance between legacy crown widths.
 * @evidenceReview {@link Human.IPortraitMouthShape.toothGap} #73cf006 Read its nonnegative contribution to total rowLength and each cursor advance. It does not shrink the authored widths to force a fit; actual crown and curved-arch appearance remain subject to inspection.
 * @evidence {@link Human.IPortraitMouthShape.crowns} Supplies owned individual enamel profiles for the optional legacy row.
 * @evidenceReview {@link Human.IPortraitMouthShape.crowns} #3311561 Read deep copying, per-crown admission, optional cervical/edge defaults and proximal contour forwarding. Empty returns after the cavity, which is how the active assembly gives the separate grouped dental component sole ownership of teeth.
 * @evidence {@link Human.buildPortraitMouth} Builds the recessed cavity and, when requested, the legacy upper crowns from final lip curves.
 * @evidenceReview {@link Human.buildPortraitMouth} #f205e43 Read the complete compatibility entry and its single preparePortraitMouth call. It forwards source, socket, shape, performance and optional actual lip indices without changing admission or omission, then converts each native mesh once in its existing part order. The native owner retains backdrop, connected lining and legacy crown formulas.
 * @evidence {@link Human.IPortraitMouthShape.borderRefinement} Selects the outer vermilion's surface or independent closed-curve refinement rule.
 * @evidenceReview {@link Human.IPortraitMouthShape.borderRefinement} #d3b0f0f Read the allowed surface/curve values and the attach.curves handoff using the existing outer loop. The lip-border scenarios compare omitted/surface behaviour and shared curve refinement. This changes an outer boundary rule; it does not promise unchanged final inner-rim coordinates after all later refinement rounds or a complete vermilion section.
 * @evidence {@link Human.createPortraitMouthComponent} Fits the curved lip bands and declares their shared skin border, oral opening and interior finisher.
 * @evidenceReview {@link Human.createPortraitMouthComponent} #7209338 Read the entire copied-input admission, curved-band fit, performance, cuts, group labels, closures and optional boundary refinement. The shared adapter now calls preparePortraitMouth with final positions and selected lip-group triangles. Existing direct finish uses that same producer; wall/chamber checks still precede closed omission and separate dentition remains mandatory during performance.
 * @evidence {@link Human.portraitLipTriangles} Selects the connected lip band bounded by the two authored anatomical loops.
 * @evidenceReview {@link Human.portraitLipTriangles} #a0ce5d3 Read both anatomical barrier loops, edge incidence, seed selection and connectivity flood. The cutout and lip-border scenarios preserve full band triangles rather than selecting their centroids. A missing seed refuses, while choosing a seed in the intended band remains the subject binding responsibility.
 * @evidence {@link Human.IPortraitLipBandKnot} Defines one thickness-ratio witness along the curved oral span.
 * @evidenceReview {@link Human.IPortraitLipBandKnot} #a4f2ada Read at and scale with the scalar/array resolver. Witness order belongs to the supplied profile, and fixed endpoint ratios preserve corner positions rather than introducing a separate mouth frame.
 * @evidence {@link Human.IPortraitLipBandKnot.at} Locates a thickness witness from anatomical right to left.
 * @evidenceReview {@link Human.IPortraitLipBandKnot.at} #28ade80 Traced finite strictly increasing progress with endpoint values -1 and +1. Duplicate or reversed positions refuse, while asymmetric interior positions retain their specified intervals.
 * @evidence {@link Human.IPortraitLipBandKnot.scale} Sets a positive local ratio of vertical vermilion thickness.
 * @evidenceReview {@link Human.IPortraitLipBandKnot.scale} #d00eda8 Compared positive finite admission with identity endpoints and convex-hull interpolation. Zero cannot be interpreted as omission because it collapses thickness; explicit one is the neutral ratio.
 * @evidence {@link Human.createPortraitLipBandSampler} Supplies normalized lip coordinates and their authoritative inner/outer heights together.
 * @evidenceReview {@link Human.createPortraitLipBandSampler} #4e5ff66 Read the entire curved-boundary binder after extracting the legacy coordinate wrapper. The mouth uses this same innerY to scale thickness; a raised lower-band point is classified locally rather than by global head height. All bound curve data is copied.
 * @evidence {@link Human.createPortraitLipBandScale} Resolves omitted, scalar or ordered optional band profiles for mouth fitting.
 * @evidenceReview {@link Human.createPortraitLipBandScale} #2830997 Read two-to-64 knot admission, fixed corners, cubic interval blending and query refusal. Independent scalar and asymmetric-array arithmetic pins interpolation; the annulus consumer test fails when thickness application is disabled and confirms unchanged inner rim and upper band under lower-only detail.
 * @evidence {@link Human.IPortraitDentalCrown} Separates enamel width, height, half-depth, cervical narrowing and cutting-edge rise from arch placement.
 * @evidenceReview {@link Human.IPortraitDentalCrown} #8e72229 Read the local gingival +Y/anterior +Z frame, five numeric dimensions and optional paired side contours. Cervical width is a ratio and edge rise a millimetre length; neither places the crown on the arch. Side detail inherits omitted values independently, while row contact now measures the rotated result rather than trusting nominal width alone.
 * @evidence {@link Human.assertPortraitDentalCrown} Admits usable enamel profiles before their width influences arch clearance.
 * @evidenceReview {@link Human.assertPortraitDentalCrown} #ae0633f Compared finite positive dimensions, base cervical ratio and half-height rise bounds with the separate admission of both resolved side contours. The tests place each invalid contact fraction, ratio and rise on either anatomical side and retain explicit zero rise. This profile gate does not measure clearance after a row rotates the crown.
 * @evidence {@link Human.buildPortraitDentalCrown} Builds each closed local crown before the row arranges it along one arch.
 * @evidenceReview {@link Human.buildPortraitDentalCrown} #fde382c Read the complete compatibility wrapper and its native constructor. It forwards the profile and default or explicit mesial direction exactly once, returning the same owned enamel mesh while the native producer retains cervical identity.
 * @evidence {@link Human.IPortraitDentalArc} Exposes physical horizontal arc distance and tangent to the dental-row arrangement.
 * @evidenceReview {@link Human.IPortraitDentalArc} #bf977bd Read length, central distance and the sample result in the same millimetre frame. Position and horizontal unit tangent are returned together; the guide's inferred posterior continuation is not a source-image measurement.
 * @evidence {@link Human.createPortraitDentalArc} Samples the supplied dental guide by cumulative XZ distance rather than projected width or spline progress.
 * @evidenceReview {@link Human.createPortraitDentalArc} #aac4d50 Read 257 core samples, cubic posterior continuations, cumulative horizontal distance and binary lookup. Out-of-range travel and zero horizontal advance refuse. The grouped row supplies a planar elliptical guide and does not derive independent tooth heights from an animated lip.
 * @evidence {@link Human.IPortraitDentalRow} Supplies one local arch and its ordered crown profiles to the grouped dentition builder.
 * @evidenceReview {@link Human.IPortraitDentalRow} #bfb2647 Compared halfWidth/depth with the nominal ellipse, gap with arc-distance centre placement and optional contactGap with actual rotated-mesh separation. Crown profiles remain independently shaped data in right-to-left order. Contact can shift centres away from the guide without changing crown Y/Z or orientation; omission preserves nominal placement.
 * @evidence {@link Human.IPortraitDentalAttachment} Defines the complete row's oral datum, orientation guides and metric offsets.
 * @evidenceReview {@link Human.IPortraitDentalAttachment} #1c94f92 Read both corner points, upper-lip centre, up guide, lift and recess against rigid attachment. The corner chord supplies X, orthogonalized up supplies Y, and their cross supplies anterior Z; lengths remain millimetres and no per-tooth transform is introduced.
 * @evidence {@link Human.attachPortraitDentalRow} Places every crown vertex and normal through one orthonormal oral frame.
 * @evidenceReview {@link Human.attachPortraitDentalRow} #02ecd14 Read the adapter after extracting its complete transform to attachPortraitOralMesh. It maps upperLipMiddle to the shared origin and retains all other values; the shared helper now owns frame refusal messages and copied position/normal arithmetic.
 * @evidence {@link Human.IPortraitLipSection} Gives upper body/tubercle and lower body/pads independent signed relief controls.
 * @evidenceReview {@link Human.IPortraitLipSection} #ec42600 Read millimetre projections separately from half-width fractions for tubercle width, pad width and offset. Zero projections retain the prior band, so a small measured final effect does not make these controls inactive.
 * @evidence {@link Human.IPortraitLipCoordinate} Locates a sample inside one curved vermilion band without subject-specific vertex identities.
 * @evidenceReview {@link Human.IPortraitLipCoordinate} #0f58804 Compared upper/lower classification, signed lateral progress and cutaneous-to-aperture across progress with the coordinate binder. These are normalized band coordinates, not head-Y labels or a new dental frame.
 * @evidence {@link Human.createPortraitLipSection} Evaluates owned vermilion relief with exactly zero contribution at both band edges and corners.
 * @evidenceReview {@link Human.createPortraitLipSection} #aa7c7e8 Read the quartic lateral fade, sine-squared transverse envelope and distinct upper-central/lower-paired Gaussian terms. The independent unit envelope gives 0.28125 at lateral 0.5/across 0.25; boundaries return literal zero and overflow refuses. This scalar function supplies no vertex pinning after the caller's later refinement, and the final lip form remains unaccepted.
 * @evidence {@link Human.createPortraitLipCoordinates} Binds outer and inner lip curves to the section's normalized coordinates.
 * @evidenceReview {@link Human.createPortraitLipCoordinates} #52d5c3a Traced the two extreme-X outer paths, strict forward ordering, shared inner corners and local upper/lower midpoint classification. Normalized interpolation prevents large-coordinate subtraction overflow; the raised lower-lip test guards against replacing this curved frame with a global Y threshold.
 * @evidence {@link Human.buildPortraitDentalRow} Composes the owned crowns on a nominal arch and resolves optional proximal contact before merging the group.
 * @evidenceReview {@link Human.buildPortraitDentalRow} #fe88fe6 Re-read the formatted complete wrapper, native row producer and engine merge contract. The mesh-only API still receives the full placed enamel group; native cycle retention changes neither optional clearance arithmetic nor output normals and units.
 * @evidence {@link Human.createPortraitDentalComponent} Attaches the complete dental row to live refined oral anchors without cutting or deforming skin.
 * @evidenceReview {@link Human.createPortraitDentalComponent} #3da0014 Read native row preparation and both attachment policies. The component copies each crown cycle into the placed upper interior without changing vertex order. Observed-maxilla still captures pre-performance coordinates, while refined-oral reads final anchors. The shared adapter retains direct metric output; the loops imply no invented gingiva.
 * @evidence {@link Human.IPortraitInterior} Inspects the owned pre-packing anatomical descriptor.
 * @evidenceReview {@link Human.IPortraitInterior} #d8b116f Read the complete owned descriptor and the head admission call. Directed named cycles retain native indices; explicit attachments address skin by null or a prepared part by ID. Coincident positions do not discover a join. The descriptor still does not declare fixed/free mechanics or closed-skin aliases.
 * @evidence {@link Human.IPortraitInterior.id} Carries the existing part identity through preparation.
 * @evidenceReview {@link Human.IPortraitInterior.id} #83f67a3 Read direct propagation into portraitPart.id and name without remapping or coordinate lookup.
 * @evidence {@link Human.IPortraitInterior.material} Carries the resident palette identity.
 * @evidenceReview {@link Human.IPortraitInterior.material} #57e2d0a Read the unchanged material assignment at packing. This field neither creates a finish nor determines mechanical tissue properties.
 * @evidence {@link Human.IPortraitInterior.mesh} Retains native geometry before the metric boundary.
 * @evidenceReview {@link Human.IPortraitInterior.mesh} #6905c24 Read fresh placed buffers, native connectivity and current normals in upper/lower/tongue/mouth production. Position edits invalidate normals; this descriptor does not itself regenerate them.
 * @evidence {@link Human.createPortraitInteriorFinisher} Shares one producer between native and direct compatibility consumers.
 * @evidenceReview {@link Human.createPortraitInteriorFinisher} #f13a1a3 Read the complete adapter: prepare is exposed unchanged, while finish invokes it once and maps owned meshes through portraitPart in order. There is no cache, inverse scaling, repeated pose or independent geometry formula.
 * @evidence {@link Human.preparePortraitMouth} Inspects the native cavity and legacy crown producer used by the actual mouth component.
 * @evidenceReview {@link Human.preparePortraitMouth} #c280f62 Read the complete producer after native identity propagation. Connected lining maps its already traced boundary into explicit skin attachments; the detached backdrop has no fabricated join. Legacy crowns retain constructor-owned cervical cycles through the same rigid placement. Closed omission, dimensions, units and part order remain unchanged; no tissue clearance is certified.
 * @evidence {@link Human.assertPortraitInteriorBindings} Admits the declared native identities in the actual head path.
 * @evidenceReview {@link Human.assertPortraitInteriorBindings} #b21bb15 Re-read the formatted implementation and every branch: unique part identity, indexed/sequential directed edges, nonblank unique cycle names, simple resident cycles, finite referenced XYZ and exact declared attachment agreement. All parts are indexed before joins are read; no input is mutated, position lookup infers a relationship, face is removed or collision pair is excluded. Independent triangle refusals and the real head consumer pin this boundary.
 * @evidence {@link Human.preparePortraitDentalCrown} Owns enamel construction and its cervical attachment cycle together.
 * @evidenceReview {@link Human.preparePortraitDentalCrown} #720b2cf Read all inherited profile admission and loft/cap arithmetic. The actual final sampled row supplies the directed cervical cycle; independent off-grid proximal crests can change its vertex ordinals. The planar-cap edge-cancellation oracle checks this without assuming row counts. Fresh geometry and cycle arrays feed native rows and legacy mouth crowns.
 * @evidence {@link Human.preparePortraitDentalRow} Carries crown-owned identities through the actual row merge.
 * @evidenceReview {@link Human.preparePortraitDentalRow} #5508208 Read cloned admission, ellipse arc sampling, mesial direction, rigid positions/normals, optional complete-surface X shifts and engine concatenation. Each cervical index receives the preceding actual vertex count, and crown order is retained. Unequal off-grid profiles and optional separation exercise merged cap correspondence without coordinate recovery.
 * @evidence {@link Human.preparePortraitOralLining} Retains the traced skin IDs beside the native oral mesh.
 * @evidenceReview {@link Human.preparePortraitOralLining} #c487c7b Read all dimension admission, boundary tracing, exact rim copying, depth rings, chamber expansion, pole and normal construction. The same owned boundary array returned by the trace names each initial native vertex. Analytic annuli before and after subdivision pin skin identity, source ownership and the actual mouth consumer. Hidden anatomy and collision validity are not established.
 * @evidence {@link Human.IPortraitInterior.loops} Declares named directed anatomical cycles in native vertex space.
 * @evidenceReview {@link Human.IPortraitInterior.loops} #5f2044d Read the optional readonly cycle population beside upper, lower and legacy enamel producers and head admission. Names are unique within a part; cycles omit a repeated closing vertex and may border capped faces on both sides. The validator checks resident directed edges, not that every cycle is a free boundary or an anatomical reconstruction.
 * @evidence {@link Human.IPortraitInterior.attachments} Declares explicit skin or interior correspondences.
 * @evidenceReview {@link Human.IPortraitInterior.attachments} #3ff2591 Read native vertex pairs and target namespace against the lining producer and whole-population validator. Null denotes skin; a named interior may occur later. Exact coordinate equality validates a declared pair but never discovers one. Mechanical ownership and closed-skin seam aliases remain outside this field.
 */
export const portraitOralReview = { scope: "oral construction inspection" };
