import type * as ReferenceAnatomy from "../reference-anatomy/model";
import type * as Anatomy from "./anatomy";
import type * as Configuration from "./configuration";
import type * as ControlNet from "./controlNet";
import type * as ControlPositions from "./controlPositions";
import type * as Fitted from "./fittedModel";
import type * as Hair from "./hairProxy";
import type * as Model from "./model";
import type * as NasalReference from "./nasalReference";

/**
 * Frozen measurements, recipes, fitted construction and attributed alternatives.
 * The frozen study root retains this domain through the native evidence graph.
 * Existing source inspections and historical capture limitations are preserved
 * verbatim. This carrier neither changes geometry nor accepts current likeness;
 * artifact observations and identities remain in review.md and the root record.
 *
 * @evidence {@link Fitted.attachFittedPortraitContext} Attaches the target's dental, brow and coarse hair context to an already admitted fitted anatomical skin.
 * @evidenceReview {@link Fitted.attachFittedPortraitContext} #8112c3d Read the anatomical-part mesh guard, merged skin in millimetres, appended fitted landmarks, two skin-sampled brows, grouped upper arch and coarse hair. The function intentionally appends context and changes identity on the supplied model; the pure fixture exercises this real mutation boundary without rebuilding the expensive prior. Full-prior versus extracted-context replay was identical.
 * @evidence {@link NasalReference.admitPortraitNasalPatch} Checks exact fitted skin and target bytes before copying the selected numerical nasal patch.
 * @evidenceReview {@link NasalReference.admitPortraitNasalPatch} #0f8f391 Read source-skin and target byte admission before any boundary IDs are used, followed by owned metre-to-millimetre positions, copied triangle indices, fresh groups and copied boundary. The focused fixture checks byte mismatch refusal and input ownership; the full provider remains responsible for producing that fitted skin.
 * @evidence {@link Anatomy.portraitOrbitalRelief} Supplies the subject's named orbital support regions consumed by the shared surface layer.
 * @evidenceReview {@link Anatomy.portraitOrbitalRelief} #a1b1558 Read the medial upper-orbit region additions, resident anchors, XYZ offsets, radii and signed displacement beside the layer consumer. These authored envelopes adjust shared skin support and do not claim measured orbital anatomy.
 * @evidence {@link Anatomy.portraitPerioralRelief} Supplies the subject's named perioral transition regions consumed by the shared surface layer.
 * @evidenceReview {@link Anatomy.portraitPerioralRelief} #7f2a730 Read the updated philtral and lip-to-chin support radii and displacement beside the live-skin layer consumer. They remain surface envelopes with authored values, separate from the mouth component and dental placement.
 * @evidence {@link Anatomy.portraitPhiltralCurves} Supplies paired continuous controls from subnasale to the Cupid peaks for the upper cutaneous lip surface.
 * @evidenceReview {@link Anatomy.portraitPhiltralCurves} #b414518 Read both ordered crest groups, live landmark attachments, narrow support radii and bounded forward relief beside the curve-layer consumer; the curves stop at the retained vermilion boundary.
 * @evidence {@link Configuration.portraitEyeShape} Selects the active eye's optional skin attachment, lower-lid profile and optical/material controls.
 * @evidenceReview {@link Configuration.portraitEyeShape} #82419bb Read all frozen eye fields and their complete component consumers: reserve attachment, 1.06 width/1.04 opening, lower-section/pretarsal shape, fixed corneal/globe dimensions, pigment, wet tissue, 800-fibre rootBand/span/endFade and tessellation. Corrected lower-lid handedness and density thinning are implementation changes within the capped fit, not later retuning.
 * @evidence {@link Configuration.portraitHairShape} Selects the subject's continuous frontal hair-cap boundary fit.
 * @evidenceReview {@link Configuration.portraitHairShape} #6e08b93 Read the signed fringe bias beside both hair-proxy consumers and its focused boundary test. The value shifts one connected cap boundary within its transition band; it does not add a strand overlay or claim detailed grooming.
 * @evidence {@link Configuration.portraitNoseShape} Selects the active nose's fitted aperture dimensions and restrained alar projection.
 * @evidenceReview {@link Configuration.portraitNoseShape} #f7ab8e1 Read the coupled tip and alar relief beside the aperture and rim consumers. The two amplitudes soften the bridge-to-tip and paired wing transition while nostril topology and cavity attachment remain owned by the nose component.
 * @evidence {@link Configuration.portraitMouthShape} Selects the active mouth's corner, section, and grouped crown controls.
 * @evidenceReview {@link Configuration.portraitMouthShape} #f52cc95 Read the frozen 1.03 width, 0.9 opening, corner lift, upper/lower band ratios, vermilion section and ten individual crown profiles. The active grouped assembly copies this mouth with an empty crown array while deriving its separately placed row from the same authored crown data. None of the later export/editor repairs changes these dimensions.
 * @evidence {@link Configuration.portraitCheekShape} Selects paired medial and buccal cheek support radii and transition controls.
 * @evidenceReview {@link Configuration.portraitCheekShape} #4df9f58 Read the malar cushion's coupled projection/lift and the medial transition beside portraitCheekLayersFor. The offset follows the shared live anchor and does not create an independent detached cheek mesh.
 * @evidence {@link Configuration.portraitOrbitalSupportShapes} Selects the station-wise brow and sulcus support values for the active orbital layer.
 * @evidenceReview {@link Configuration.portraitOrbitalSupportShapes} #16623d4 Read the changed medial station brow/sulcus projections beside the orbital support factory. Station order and resident anchors remain the authority; these values do not alter the eye's optical shell.
 * @evidence {@link Configuration.portraitEyeSockets} Binds the active eye aperture, iris and brow boundary identities.
 * @evidenceReview {@link Configuration.portraitEyeSockets} #fc103a2 Read both handed socket loops and their shared canthus/iris/brow anchors beside eye construction. These identities select resident host vertices and do not encode a second eye shape.
 * @evidence {@link Configuration.alternatePortraitEye} Supplies an independently replaceable eye profile for component-assembly scenarios.
 * @evidenceReview {@link Configuration.alternatePortraitEye} #fec19f3 Read the copied alternate profile beside portraitComponentsFor and the replacement tests. Its replacement path is independent of the active eye and does not mutate the active configuration.
 * @evidence {@link Configuration.portraitNoseSocket} Binds the active nose's cut, aperture and lining anchors.
 * @evidenceReview {@link Configuration.portraitNoseSocket} #817b474 Read the resident socket IDs and their use by the nose component. These are attachment identities, separate from nasal dimensions and fitted aperture shape.
 * @evidence {@link Configuration.portraitNasalSection} Selects the optional cubic nasal-section evaluator input.
 * @evidenceReview {@link Configuration.portraitNasalSection} #0b359ee Read the retained section stations, transverse basis and join width beside the nasal evaluator. The active assembly keeps this optional path distinct from the recovered basic nose.
 * @evidence {@link Configuration.alternatePortraitNose} Supplies an independently replaceable nose profile for component-assembly scenarios.
 * @evidenceReview {@link Configuration.alternatePortraitNose} #48a088f Read the alternate nose's copied dimensions beside portraitComponentsFor and the replacement tests. It is an assembly alternative, not a second active nasal authority.
 * @evidence {@link Configuration.portraitMouthSocket} Binds the active mouth opening, lip and dental attachment identities.
 * @evidenceReview {@link Configuration.portraitMouthSocket} #ec358d3 Read the resident mouth loop and oral anchors beside mouth and dental attachment. These identities do not determine optional lip relief or crown profiles.
 * @evidence {@link Configuration.portraitDentalRow} Selects the ordered upper dental profiles, arch dimensions and contact policy.
 * @evidenceReview {@link Configuration.portraitDentalRow} #b361e70 Read halfWidth 23 mm, depth 16 mm, nominal gap 0.08 mm and actual proximal contactGap 0.02 mm. Crown profiles inherit the authored mouth array with width multiplied by 0.94 and explicit depth/cervical/edge defaults. The row builds one group independent of the mouth's disabled legacy crown output.
 * @evidence {@link Configuration.portraitDentalSocket} Binds the dental row to the refined oral anchors.
 * @evidenceReview {@link Configuration.portraitDentalSocket} #4507b8c Read the three resident attachment identities beside createPortraitDentalComponent; the socket owns placement data and does not reshape crowns.
 * @evidence {@link Configuration.portraitDentalPlacement} Selects grouped dental lift and recess in millimetres.
 * @evidenceReview {@link Configuration.portraitDentalPlacement} #837e99c Read lift 1.7 mm and recess 6 mm beside the actual grouped attachment and oral-contact consumer. Positive lift hides cervical ends and positive recess moves the intact upper arch posteriorly; these frozen offsets do not reshape crowns or certify profile likeness.
 * @evidence {@link Configuration.portraitCheekSockets} Binds paired cheek support regions to resident refined-surface anchors.
 * @evidenceReview {@link Configuration.portraitCheekSockets} #6a3f08e Read anatomical-side ordering and live anchors beside cheek-layer construction; sockets provide locations while paired shapes own radii and offsets.
 * @evidence {@link Configuration.portraitCheekLayersFor} Builds paired cheek surface layers from independently supplied shape controls.
 * @evidenceReview {@link Configuration.portraitCheekLayersFor} #88d021b Read copied right/left shapes, side mirroring and named malar/buccal fields beside the layer factory; it emits shared-skin fields rather than detached cheek parts.
 * @evidence {@link Configuration.portraitComponentsFor} Composes replaceable eye, nose and mouth owners with shared sockets.
 * @evidenceReview {@link Configuration.portraitComponentsFor} #08bcb1e Read copied component settings, defaults and optional mouth replacement beside assembly tests; each part retains independent attachment/detail parameters.
 * @evidence {@link Configuration.portraitNasalSupportDetail} Holds the optional nasal-control replacement selected by an assembly.
 * @evidenceReview {@link Configuration.portraitNasalSupportDetail} #cfdf698 Read its explicit undefined/default branch beside portraitNasalLayerFor and assembly construction; it remains separate from basic support.
 * @evidence {@link Configuration.measuredPortraitAssembly} Supplies the active component and surface-layer assembly.
 * @evidenceReview {@link Configuration.measuredPortraitAssembly} #f5b622f Read the complete frozen measured-cage assembly: owned skin/lip/teeth palette, coarse hair flag, original component inputs, three refinement rounds and all cheek/nasal/orbital/perioral/philtral layers. This remains the first-hour numerical state; creating the portable package did not resume identity fitting.
 * @evidence {@link Configuration.portraitAssembly} Supplies the complete default assembly input.
 * @evidenceReview {@link Configuration.portraitAssembly} #532a6ea Read default component/layer composition and stable references; replacement helpers retain independent owners.
 * @evidence {@link Anatomy.portraitNasalRelief} Supplies the retained basic nasal surface envelopes when no optional replacement detail is selected.
 * @evidenceReview {@link Anatomy.portraitNasalRelief} #d38d104 Read named nasal support regions, live anchors, radii and signed displacements beside portraitNasalLayerFor. They are visible-surface controls and remain separate from the nasal body and aperture groups.
 * @evidence {@link ControlNet.referenceControlNet} Supplies the frozen measured control positions, camera basis and triangle topology for this subject.
 * @evidenceReview {@link ControlNet.referenceControlNet} #4d29c79 Re-read the complete provenance, projection frame and topology after separating its unchanged position array into controlPositions. The assembly retains one shared data instance with the same vertex order and values. Image-plane observations are measured inputs; depth remains an authored estimate and is not a likeness certificate.
 * @evidence {@link ControlPositions.referenceControlPositions} Retains the exact frozen observation coordinates used by the study's control net after responsibility-based separation.
 * @evidenceReview {@link ControlPositions.referenceControlPositions} #ac132e9 Compared all 478 ordered coordinates with the pre-extraction control net and retained its original provenance and capture frame in controlNet. Only the data owner moved; coordinates and shared-array assembly semantics remain unchanged. These are frozen study inputs, not an anatomical ground-truth oracle.
 * @evidence {@link Hair.buildPortraitHairProxy} Builds the coarse scalp cap and side curtain used for face silhouette inspection.
 * @evidenceReview {@link Hair.buildPortraitHairProxy} #37d9aad Read finite scalp/side-attachment admission, uniform scalp enclosure, lateral-only ear clearance, finite metric radii and optional foreground depth sampling. The bounded fringe bias changes the cap's continuous boundary; the curtain shares cap vertices and normals are rebuilt. The returned single coarse hair mass is legacy context, not a human-package hair editor.
 * @evidence {@link Hair.IPortraitHairShape} Describes the optional subject-owned angular bias for the connected frontal cap boundary.
 * @evidenceReview {@link Hair.IPortraitHairShape} #95a551e Read the finite bounded bias admission and its signed use in the one cap boundary beside the focused fringe test. The neutral omission remains symmetric and the optional fit does not create a second mesh.
 * @evidence {@link Model.buildReferencePortrait} Assembles the selected foundation, components, shared skin layers, ears, hair and oral contacts into the inspectable portrait model.
 * @evidenceReview {@link Model.buildReferencePortrait} #a26d02e Read the explicit anatomical/procedural dispatch, common head assembly, optional named oral contact, final-skin pinnae, millimetre ear envelope and optional coarse hair. Palette and optical materials are owned independently. The empty-component and hair/context tests exercise this real entry point; final frozen full-GLB replay is recorded separately rather than inferred from source inspection.
 * @evidence {@link ReferenceAnatomy.IAnatomicalStudyShape} Declares the endpoint, expression, optical and refinement inputs of the optional anatomical study.
 * @evidenceReview {@link ReferenceAnatomy.IAnatomicalStudyShape} #a395fa1 Read all ten fields and their consumers in buildAnatomicalStudy. Weight controls act on the resident sparse targets, eye placement normalizes the common skin/anchor frame, and optical radii remain separate from skin refinement. The basic, translated-optics and buffer scenarios exercise this prior; it is not the active restored procedural face.
 * @evidence {@link ReferenceAnatomy.IAnatomicalStudyShape.youth} Selects the child contribution and complementary young contribution of the recorded prior.
 * @evidenceReview {@link ReferenceAnatomy.IAnatomicalStudyShape.youth} #9a0d7f3 Followed youth and 1-youth into the child/young target loop for both skin vertices and eye anchors. The basis scenario exercises zero and one and refuses -0.1 and 1.1. No calendar-age conversion is implemented or inferred from this blend.
 * @evidence {@link ReferenceAnatomy.IAnatomicalStudyShape.smile} Weights the recorded mouth-corner-puller target in the same source frame.
 * @evidenceReview {@link ReferenceAnatomy.IAnatomicalStudyShape.smile} #635e580 Located the smile target beside its eye-anchor deltas and checked the shared finite [0,1] admission. The basis scenario runs both endpoint values and rejects NaN; changing this value blends the stored deformation rather than invoking a coordinated facial muscle system.
 * @evidence {@link ReferenceAnatomy.IAnatomicalStudyShape.jawOpen} Weights the stored opening deformation before normalization and neck attachment.
 * @evidenceReview {@link ReferenceAnatomy.IAnatomicalStudyShape.jawOpen} #60b8754 Read the jawOpen sparse target application and the zero/one basis cases with an out-of-range 1.1 twin. The returned model has skeleton null, so this is a static target contribution rather than a jaw joint angle.
 * @evidence {@link ReferenceAnatomy.IAnatomicalStudyShape.eyeDistance} Sets the physical eye separation used to normalize the entire prior.
 * @evidenceReview {@link ReferenceAnatomy.IAnatomicalStudyShape.eyeDistance} #6a786d5 Traced division by the morphed anchors' X separation into the transform of every skin point and both eye centres; neck dimensions also use eyeDistance/64. The 64mm oracle places centres at +/-32mm. Zero separation and a scale exceeding Float32 representation refuse; this control is not an eyes-only translation.
 * @evidence {@link ReferenceAnatomy.IAnatomicalStudyShape.eyeHeight} Positions the common normalized eye midpoint along head Y.
 * @evidenceReview {@link ReferenceAnatomy.IAnatomicalStudyShape.eyeHeight} #e77e77a Read target[1] in the shared transform and the corresponding offset in all neck section heights. The basis oracle reads 0.025m at both globe centres, the optical twin changes it to 29mm, and NaN/Float32-overflow placements refuse. The surrounding head moves with this datum.
 * @evidence {@link ReferenceAnatomy.IAnatomicalStudyShape.eyeDepth} Positions the common normalized eye midpoint along head Z.
 * @evidenceReview {@link ReferenceAnatomy.IAnatomicalStudyShape.eyeDepth} #0b62bcb Followed target[2] through skin and anchor normalization and the neck centre formula. The independent centre oracle reads 0.037m, the translated optical case uses 34mm, and Infinity refuses. This is global anterior placement of the prior, not globe protrusion relative to its skin.
 * @evidence {@link ReferenceAnatomy.IAnatomicalStudyShape.eyeRadius} Defines each rigid optical sphere independently of the prior's skin coordinates.
 * @evidenceReview {@link ReferenceAnatomy.IAnatomicalStudyShape.eyeRadius} #f1736d2 Checked positive radius, 2*radius<eyeDistance and irisRadius<radius before reading spherical vertex construction and radial normals. The radius-sixteen and translated radius-fifteen scenarios retain the analytic directions; equality at radius32 with separation64 refuses. Fitted optical centres move, but the sphere itself is not warped by the skin residual.
 * @evidence {@link ReferenceAnatomy.IAnatomicalStudyShape.irisRadius} Determines the sampled pigment-cap disk on the study globe.
 * @evidenceReview {@link ReferenceAnatomy.IAnatomicalStudyShape.irisRadius} #ab83836 Read its positive domain and strict upper bound against eyeRadius, then the radius*v angular samples for the iris-1 cap. Its 0.04mm lift changes axial placement separately from radius. The buffer and optics scenarios inspect this cap; the simplified construction does not establish captured-eye refraction.
 * @evidence {@link ReferenceAnatomy.IAnatomicalStudyShape.pupilRadius} Controls the separate pupil-cap extent inside the iris.
 * @evidenceReview {@link ReferenceAnatomy.IAnatomicalStudyShape.pupilRadius} #dba3e1c Compared its strict pupil<iris admission with the separate pupil samples and 0.07mm lift. Zero and equality with the default6.4mm iris refuse. This is an opaque spherical cap, not a modeled internal pupil opening.
 * @evidence {@link ReferenceAnatomy.IAnatomicalStudyShape.subdivisionRounds} Selects common skin and neck tessellation after their shared attachment.
 * @evidenceReview {@link ReferenceAnatomy.IAnatomicalStudyShape.subdivisionRounds} #0e850c6 Traced omission to one round and explicit zero through the joinedFaces Catmull-Clark call. The subdivision owner admits only integers zero through three. This value does not change the separate 48-column optical sampling or authorize a different fitted-source basis.
 * @evidence {@link ReferenceAnatomy.anatomicalStudyShape} Supplies the explicitly unaccepted starting preset for the anatomical-prior path.
 * @evidenceReview {@link ReferenceAnatomy.anatomicalStudyShape} #a2b5fb5 Read youth0.6, smile0.55, jawOpen0.35, the64mm separation, midpoint[0,25,37]mm and radii16/6.4/2.55mm against the source interface and basis/optics scenarios. The preset contains no supplied refinement override; these authored values neither reproduce the current procedural construction nor establish the photographed adolescent's measurements.
 * @evidence {@link ReferenceAnatomy.buildAnatomicalStudy} Builds the resident attributed prior, shared skin/neck surface and separate optical parts.
 * @evidenceReview {@link ReferenceAnatomy.buildAnatomicalStudy} #be8ee8d Read the complete target accumulation, shared normalization, open-crop extraction, face-centre neck support, joined-quad refinement, optional residual and material separation. Basis tests verify finite geometry, midpoint placement and admission failures; optical/buffer tests check the actual delivered directions. The optional fitted alternative remains unaccepted, and source provenance is retained in the prior's README/assets rather than claimed as original sculpting.
 * @evidence {@link NasalReference.buildPortraitNasalReference} Reconstructs and admits the exact existing CC0 fitted nasal source before its boundary is consumed.
 * @evidenceReview {@link NasalReference.buildPortraitNasalReference} #8c202bc Read exact current prior/target admission, selected fitted sampling, resident anatomical-skin retrieval and delegation to admitPortraitNasalPatch before interpreting boundary IDs. The helper extraction preserves the source/target and full fitted-skin byte guards; it does not make an old residual or rejected nasal patch current.
 * @evidence {@link Fitted.buildFittedReferencePortrait} Applies the recorded anatomical fit only after checking its captured source and current target dependencies.
 * @evidenceReview {@link Fitted.buildFittedReferencePortrait} #3b59d73 Read current-prior and target-byte admission before the fitted anatomical build, recorded-landmark fallback and delegation to attachFittedPortraitContext. The independent full-prior versus extracted admission/context replay produced the same model at the checked sampling. This alternative fitted foundation is not the active procedural face or an accepted likeness.
 * @evidence {@link Anatomy.IPortraitNasalDetail} Groups a complete optional nasal control field in place of basic support amplitudes.
 * @evidenceReview {@link Anatomy.IPortraitNasalDetail} #d1d7074 Read its radius and control population beside portraitNasalLayerFor. Omission selects the original relief, while a supplied empty population explicitly removes that layer; detail is not silently added on top of the old nasal amplitudes.
 * @evidence {@link Anatomy.IPortraitNasalDetail.radius} Establishes one millimetre support extent for the coupled nasal group.
 * @evidenceReview {@link Anatomy.IPortraitNasalDetail.radius} #2c558c3 Traced the value into both normalized matrix distances and every final field radius. The same extent governs exterior and recessed lining; it is an authored influence range rather than a recovered tissue thickness.
 * @evidence {@link Anatomy.IPortraitNasalDetail.controls} Supplies the complete named nasal target population, including stationary anchors.
 * @evidenceReview {@link Anatomy.IPortraitNasalDetail.controls} #05d8c8c Compared active dorsal, tip, columellar and alar-facial handles with the solver's zero constraints. No control is discarded before solving merely because its displacement is zero; only solved zero coefficients produce no field.
 * @evidence {@link Anatomy.portraitNasalLayerFor} Selects exactly one basic or coupled nasal surface authority.
 * @evidenceReview {@link Anatomy.portraitNasalLayerFor} #b95b101 Re-read both branches with portraitNasalSupportDetail and the frozen measuredPortraitAssembly. The active procedural nose passes undefined and retains the original relief fields. An explicit empty control population disables those fields for the rejected native-patch alternative; that alternative is not selected. This corrects the earlier active-patch description without changing the frozen fit. Other anatomical layers still act on the assembled surface and require separate sensitivity checks.
 * @evidence {@link Anatomy.portraitNasalDetail} Records the rejected coupled nasal fitting hypothesis for explicit replacement experiments.
 * @evidenceReview {@link Anatomy.portraitNasalDetail} #970d91f Read each named datum, zero offset and signed three-axis movement with its frozen 0af74958 configuration. Eleven controls share a 22 mm support. Both image reviewers found a broad flat tip, so the preset is absent from the active assembly and is not an accepted anatomical fit.
 */
export const portraitStudyReview = { scope: "study construction inspection" };
