import type * as Human from "@automovie/human";

/**
 * Shared topology, skin, cranium, materials and model export.
 * The frozen study root retains this domain through the native evidence graph.
 * Existing source inspections and historical capture limitations are preserved
 * verbatim. This carrier neither changes geometry nor accepts current likeness;
 * artifact observations and identities remain in review.md and the root record.
 *
 * @evidence {@link Human.IPortraitSkinColourRegion} Inspects all six fields against reference binding, finite admission and the document consumer.
 * @evidenceReview {@link Human.IPortraitSkinColourRegion} #08e7c87 Read the six fields and their constructor admission: a unique nonblank name, resident anchor, finite millimetre offset, positive support radii, bounded linear RGB attenuation and strength. It is numerical authoring data, not a biological pigment estimate or a photograph texture.
 * @evidence {@link Human.createPortraitSkinColour} Inspects owned name-ordered compact colour multiplication after reference refinement.
 * @evidenceReview {@link Human.createPortraitSkinColour} #c25a3ee Read input/anchor ownership, name sorting, all numeric refusals, compact quartic support and multiplicative linear RGB. The kernel is bounded at floating-point zero distance. Independent centre, half-radius, outside and narrow-field probes pass; evaluation reads reference coordinates, never scene light or current pose.
 * @evidence {@link Human.IPortraitHeadPerformance} Separates reference continuation from resident performed components.
 * @evidenceReview {@link Human.IPortraitHeadPerformance} #70fcd9a Read both callbacks and their assembler consumer. Only appended cranium and neck vertices receive the pose; shared facial IDs remain current. This protocol alone promises no anatomical realism.
 * @evidence {@link Human.IPortraitHeadPerformance.reference} Provides reference coordinates for continuation formation.
 * @evidenceReview {@link Human.IPortraitHeadPerformance.reference} #3052bea Read the copied-point and vertex-ID invocation before cranial construction. Finite XYZ is checked and resident performed coordinates are not replaced by the returned reference.
 * @evidence {@link Human.IPortraitHeadPerformance.pose} Moves newly appended reference tissue before common refinement.
 * @evidenceReview {@link Human.IPortraitHeadPerformance.pose} #ff6d472 Read the appended-vertex loop and finite result copying before topology, subdivision and normals. Existing oral and facial vertices are not passed through this callback.
 * @evidence {@link Human.IPortraitSkinShape} Describes optional skin condition without changing the frozen subject's omitted profile.
 * @evidenceReview {@link Human.IPortraitSkinShape} #5ac437c Read the optional scalar record, zero-condition default and explicit bilateral ownership. The time-capped subject does not select age morphology, so this type adds an authoring capability without reinterpreting its stored appearance.
 * @evidence {@link Human.portraitSkinParameters} Supplies authoring defaults whose zero condition leaves the historical face unchanged.
 * @evidenceReview {@link Human.portraitSkinParameters} #3556b66 Read every unit, inclusive envelope, initial value and signed effect. Laxity and expression creasing default to zero, separately from regional fold multipliers and tissue amounts. These are visible-shape settings, not measured ages or tissue moduli.
 * @evidence {@link Human.resolvePortraitSkinShape} Resolves omission to taut skin with no transient crease driver.
 * @evidenceReview {@link Human.resolvePortraitSkinShape} #76b30c6 Read undefined-only defaults, finite/range refusal and allocation of a fresh complete output. The raw identity assembly unit replayed omitted and explicit zero settings exactly. The historical fit remains separately frozen and its images do not acquire a new likeness verdict.
 * @evidence {@link Human.createPortraitSkinLayer} Separates live surface detail from the frozen historical mesh and its time-capped fit.
 * @evidenceReview {@link Human.createPortraitSkinLayer} #808eed3 Read copied bindings/settings, actual anterior-depth queries, spline paths, regional drivers and conditional local sampling. Hand-plane tests verify centre depth and millimetre pad/descent vectors; unilateral blink fields stay lateral to the selected eye. Zero condition bypasses attachments. Four older candidates show resting folds, but their simplified placement and likeness remain unaccepted.
 * @evidence {@link Human.refinePortraitSurfaceSampling} Refines only requested field neighbourhoods, leaving an omitted skin condition without additional sampling.
 * @evidenceReview {@link Human.refinePortraitSurfaceSampling} #a329489 Read the complete conforming midpoint loop, contact protection and split masks. Reference XYZ and RGB are copied and linearly interpolated on the exact inserted edges while geometry retains tangent-guided midpoints. Original samples and contact handling remain unchanged. This transports material coordinates, not recovered anatomy.
 * @evidence {@link Human.IPortraitCranialStation} Describes one sagittal section of the superior, inferior and transverse cranial envelopes.
 * @evidenceReview {@link Human.IPortraitCranialStation} #ed1b920 Read posterior z ordering, separate crownZ, positive width, superior crown and either absolute or explicitly chin-relative floor. The resolver converts chin-relative values once and the cranial appender shares the resulting ring with neighbouring sections.
 * @evidence {@link Human.IPortraitCraniumShape} Carries whole-station replacement, posterior cap depth and independent transition correspondence.
 * @evidenceReview {@link Human.IPortraitCraniumShape} #53276c4 Read the optional five-to-sixty-four station array, cap and transition bounds and separate angular frame. These parameters define a provisional continuation behind the observed facial oval; no hidden skull measurement is inferred.
 * @evidence {@link Human.IPortraitFacialFrameShape} Names the common-host facial proportions and anatomical support displacements.
 * @evidenceReview {@link Human.IPortraitFacialFrameShape} #cd960ac Read the complete nasion scale and signed support fields, including bilateral browProjection in [-8,8] mm. Its zero default leaves the source foundation unchanged; nonzero depth belongs to identity before eyelid fitting, not expression brow elevation or a finished-eye transform. The first time-capped document does not opt into this added control.
 * @evidence {@link Human.createPortraitFacePerformanceComponent} Binds brow motion and lower facial skin to the same host used by the anatomical parts.
 * @evidenceReview {@link Human.createPortraitFacePerformanceComponent} #21972e7 Read complete jaw/brow constraint construction and the shared oral-band weight consumer. Lips remain excluded, lower-face targets keep their ownership and brow residuals compose with existing targets. Extracting the cubic field adds no second lower-face pose.
 * @evidence {@link Human.createPortraitFacialFrame} Transforms one shared host and its metric hinge attachment through compact anatomical supports.
 * @evidenceReview {@link Human.createPortraitFacialFrame} #28bc3e6 Read the complete copied-host transform and its brow-envelope helper. Nonzero brow depth requires two named resident eye guides, shares their highest aperture floor, and takes the maximum of compact bilateral weights before changing Z; invalid bands refuse. Zero bypasses the added binding requirement. The same retained transform still maps the jaw hinge, while source observations, indices and viewing ray retain their own ownership. New parameter renders are verified separately from this source inspection.
 * @evidence {@link Human.portraitCranialChinHeight} Derives the cranial continuation's chin datum from the retained facial oval.
 * @evidenceReview {@link Human.portraitCranialChinHeight} #1829f78 Read the fixed facial-oval identities, finite resident Y admission and minimum-height selection. The datum uses the complete lower oval rather than a singled-out chin landmark and feeds explicitly chin-relative station floors; this helper does not validate the remaining XYZ coordinates.
 * @evidence {@link Human.resolvePortraitCraniumShape} Resolves copied cranial defaults and admits complete caller-owned sagittal sections.
 * @evidenceReview {@link Human.resolvePortraitCraniumShape} #2d15bd1 Read seven default stations, chin-relative floor resolution, owned frame/defaults, finite checks, positive width/height, descending z and crownZ admission. The result strips chinRelative after applying it, preventing repeated chin offsets when a resolved recipe is used by construction.
 * @evidence {@link Human.resolvePortraitEarSampling} Validates pinna dimensions separately from bounded mesh sampling.
 * @evidenceReview {@link Human.resolvePortraitEarSampling} #a73096d Read all finite dimensions, positive outline scales/projection and nonnegative embedding, then integral angular and front/back row bounds. Returned defaults or explicit sampling are copied; reducing rows does not redefine anatomical dimensions.
 * @evidence {@link Human.resolvePortraitFacialFrameShape} Supplies owned neutral frame dimensions and refuses unsupported numerical combinations.
 * @evidenceReview {@link Human.resolvePortraitFacialFrameShape} #886533e Read every scale and displacement default and the finite per-key envelopes. browProjection joins the zero-valued [-8,8] mm displacements without changing one-valued width/length scales. This numeric resolver does not inspect eye bindings or geometry; the frame constructor owns those coupled failures and document schema admission owns unknown keys.
 * @evidence {@link Human.sealPortraitContactSeams} Closes only declared coincident free-boundary tissue contacts after refinement.
 * @evidenceReview {@link Human.sealPortraitContactSeams} #02fd206 Read free-edge selection, contact representatives, duplicate-fold removal and incidence checks. Original corner RGB follows each surviving triangle through welding. Removed triangles discard matching colours. The contact unit retains different tissue colours at coincident copies with identical common normals.
 * @evidence {@link Human.reservePortraitSkin} Selects a connected host-skin reservation that contains a component's proposed outer seam before the component removes its original faces.
 * @evidenceReview {@link Human.reservePortraitSkin} #bec1190 Read the target/loop cardinality guard, connected face-ring growth, simple-boundary test and finite termination before the shared annulus is attached. The host remains immutable and the reservation returns original face ordinals plus its outer boundary; this topology operation does not claim a 3D collision certificate.
 * @evidence {@link Human.portraitSkinAnnulus} Bridges a reserved outer host boundary to the component's inner boundary with the existing planar region triangulator.
 * @evidenceReview {@link Human.portraitSkinAnnulus} #346bf5e Read both loop winding checks, complete finite coordinate conversion, planar-region rejection and the returned oriented triangle order. The bridge preserves the two boundary identities for the eye attachment; it does not alter the component's optical or lower-lid dimensions.
 * @evidence {@link Human.portraitNeckShape} Selects the active cranial/neck section dimensions and crop.
 * @evidenceReview {@link Human.portraitNeckShape} #f3f6e13 Read the upper, lower and crop sections against the cervical appender. Their Y/width/front/centre/back values are provisional continuation defaults; a face document may replace them. The first study's capped identity is stored separately.
 * @evidence {@link Human.createPortraitMaterials} Produces owned reusable skin, dental and optical material defaults for a caller's face.
 * @evidenceReview {@link Human.createPortraitMaterials} #3ec8686 Read every generated material record, independent arrays, colour, roughness and optical defaults against the model palette composition. This reusable palette contains no person's photo samples. A face document may replace the full appearance; the frozen first-fit palette is a separate study input.
 * @evidence {@link Human.IPortraitEarShape} Groups the resident ear datum, scale, projection and embedding controls.
 * @evidenceReview {@link Human.IPortraitEarShape} #64ebbf0 Read the complete placement, independent scales, projection/embedding and optional angular/front/back sampling group beside resolution and construction. Anatomical dimensions and tessellation have separate ownership; hidden pinna anatomy is provisional.
 * @evidence {@link Human.IPortraitEarShape.centerY} Locates the ear datum along the construction Y axis.
 * @evidenceReview {@link Human.IPortraitEarShape.centerY} #fe0ab55 Read centerY into the sampled ear frame and its finite coordinate admission.
 * @evidence {@link Human.IPortraitEarShape.centerZ} Locates the ear datum along the construction Z axis.
 * @evidenceReview {@link Human.IPortraitEarShape.centerZ} #0cc974c Read centerZ into the sampled ear frame; it remains separate from the ear's anterior projection scale.
 * @evidence {@link Human.IPortraitEarShape.heightScale} Scales the ear's vertical extent around its resident datum.
 * @evidenceReview {@link Human.IPortraitEarShape.heightScale} #5beb13f Traced heightScale into the outer and inner ear sample rows beside positive finite scale checks.
 * @evidence {@link Human.IPortraitEarShape.depthScale} Scales the ear's depth extent around its resident datum.
 * @evidenceReview {@link Human.IPortraitEarShape.depthScale} #9e9dac6 Read depthScale into the ear shell's depth coordinates beside its positive finite admission.
 * @evidence {@link Human.IPortraitEarShape.projection} Controls the ear's anterior placement relative to the sampled head surface.
 * @evidenceReview {@link Human.IPortraitEarShape.projection} #cd9ec32 Read projection into the final ear frame beside the head-surface attachment; it does not move the shared facial sockets.
 * @evidence {@link Human.IPortraitEarShape.embedding} Controls lateral embedding of the ear shell into its host surface.
 * @evidenceReview {@link Human.IPortraitEarShape.embedding} #5a7d808 Traced embedding into the ear attachment frame and its bounded admission; the shell remains a separate component group.
 * @evidence {@link Human.buildPortraitEars} Samples and attaches both authored ear shells to the final cranial surface.
 * @evidenceReview {@link Human.buildPortraitEars} #f63278e Read side mirroring, copied shape inputs, live head-surface depth sampling and separate ear material groups beside ear attachment tests. This external shell does not claim detailed helix anatomy or likeness acceptance.
 * @evidence {@link Human.portraitEarShape} Supplies the default authored ear profile when no replacement is selected.
 * @evidenceReview {@link Human.portraitEarShape} #e2cf74e Read the default datum, scales, projection and embedding beside both ear consumers. These values are procedural defaults rather than measured subject anatomy.
 * @evidence {@link Human.IPortraitNeckSection} Describes one cross-section of the authored neck continuation.
 * @evidenceReview {@link Human.IPortraitNeckSection} #9f21ae5 Read the section's Y coordinate, width, front, centre and back depths beside appendPortraitNeck. These values define one closed continuation sample and do not claim measured cervical anatomy.
 * @evidence {@link Human.IPortraitNeckSection.y} Locates a neck section along the construction Y axis.
 * @evidenceReview {@link Human.IPortraitNeckSection.y} #988de89 Read the ordered section Y samples and their positive spacing admission beside neck loft construction.
 * @evidence {@link Human.IPortraitNeckSection.width} Sets the lateral half-width of one neck section.
 * @evidenceReview {@link Human.IPortraitNeckSection.width} #efb1575 Traced width into the section's paired lateral points and finite positive admission; it does not alter the facial component sockets.
 * @evidence {@link Human.IPortraitNeckSection.front} Sets the anterior depth of one neck section.
 * @evidenceReview {@link Human.IPortraitNeckSection.front} #3d71dce Read front depth beside the section loft's anterior boundary and its finite-domain checks.
 * @evidence {@link Human.IPortraitNeckSection.centre} Sets the central depth of one neck section.
 * @evidenceReview {@link Human.IPortraitNeckSection.centre} #e8cc6cf Read centre depth beside the neck surface sample; this is a construction datum, not a facial soft-tissue measurement.
 * @evidence {@link Human.IPortraitNeckSection.back} Sets the posterior depth of one neck section.
 * @evidenceReview {@link Human.IPortraitNeckSection.back} #36fc572 Read back depth beside the posterior closure and section admission; it remains separate from the visible jawline controls.
 * @evidence {@link Human.IPortraitNeckShape} Groups upper/lower neck sections and the crop policy for the cranial continuation.
 * @evidenceReview {@link Human.IPortraitNeckShape} #1c12991 Read the three section groups and optional anterior projection with its builder. The frozen study omits the new field, selecting the exact earlier arithmetic; its face and neck are not refitted. The optional envelope is not a measured anatomical property of this subject.
 * @evidence {@link Human.IPortraitNeckShape.upper} Supplies the upper neck section at the cranial attachment.
 * @evidenceReview {@link Human.IPortraitNeckShape.upper} #b8b35ad Read the upper section's shared neck datum beside the head/neck join.
 * @evidence {@link Human.IPortraitNeckShape.lower} Supplies the lower neck section at the crop boundary.
 * @evidenceReview {@link Human.IPortraitNeckShape.lower} #24a6126 Read the lower section's crop-side datum beside the closed neck continuation.
 * @evidence {@link Human.IPortraitNeckShape.crop} Selects the authored lower crop applied during neck construction.
 * @evidenceReview {@link Human.IPortraitNeckShape.crop} #c9c248d Read crop admission and its branch in appendPortraitNeck; it limits the authored continuation rather than moving face component anchors.
 * @evidence {@link Human.IPortraitHairCard} Names a caller-authored numerical surface lock.
 * @evidenceReview {@link Human.IPortraitHairCard} #16495c6 Read 2..32 root-to-tip XYZ stations, paired transverse directions and positive width. Head-millimetre attachment guides are authored rather than recovered from a photograph; the consumer refuses incomplete and collapsed frames.
 * @evidence {@link Human.assertPortraitHairFibreCurl} Inspects shared finite inclusive curl admission used by empty-groom geometry and both texture constructors.
 * @evidenceReview {@link Human.assertPortraitHairFibreCurl} #75f0069 Re-read the formatted null/nonobject guard and every finite inclusive comparison beside the empty-card and texture callers. The multiline Error has the same refusal and no clamping or defaults were introduced. These normalized pattern bounds are authoring limits, not measured anatomy; the first-hour face remains frozen.
 * @evidence {@link Human.IPortraitHairShape} Separates card geometry, painted fibres and material ownership.
 * @evidenceReview {@link Human.IPortraitHairShape} #e3f572a Read the complete shape and its geometry/material consumers. Optional fibreShadeStrength controls encoded RGB modulation independently of coverage, normal relief and card sampling; omission or one retains the original texture. It is not a biological pigment concentration. The first-hour facial basis remains frozen.
 * @evidence {@link Human.IPortraitHairLayer} Owns an additional named static guide and finish profile without changing the frozen face.
 * @evidenceReview {@link Human.IPortraitHairLayer} #e02466d Read the complete type and groom consumer. Each layer owns a complete shape, not a photo or hairstyle lookup. Names are checked across empty and populated layers; this study has not adopted a new layered groom.
 * @evidence {@link Human.buildPortraitHairGroom} Assembles independent additional card populations while retaining legacy hair output.
 * @evidenceReview {@link Human.buildPortraitHairGroom} #04b7bd1 Read the complete assembler and full-face call. Resident-only base lookup prevents order-dependent finish borrowing; every populated layer owns a distinct generated id and empty profiles still pass shape admission. This does not refit the frozen first-hour facial basis.
 * @evidence {@link Human.buildPortraitHairCards} Emits merged UV-bearing hair strips from numerical guides.
 * @evidenceReview {@link Human.buildPortraitHairCards} #797ec77 Read all shape/station checks, cubic guides and frames, taper, UVs and nondegenerate normals. Shade admission precedes the empty population; finite endpoints zero and one do not enter geometry arithmetic. Invalid shade cannot be concealed by an empty groom. The first-hour facial basis remains frozen.
 * @evidence {@link Human.createPortraitHairTexture} Builds a resident deterministic fibre mask without external images.
 * @evidence {@link Human.createPortraitHairMaterial} Derives the builder's independent masked hair finish without replacing its base.
 * @evidenceReview {@link Human.createPortraitHairMaterial} #c07ed28 Read the owned finish copy and actual texture consumers. Shade strength is forwarded only to base-colour generation; normals receive the unchanged curl profile. Independent identity, mask cutoff and base finish ownership remain intact. The first-hour facial basis remains frozen.
 * @evidenceReview {@link Human.createPortraitHairTexture} #753c843 Read the public wrapper and complete PNG encoder. Shade defaults to one and bypasses the new interpolation to retain prior arithmetic. Other valid strengths interpolate pre-quantized encoded RGB towards white; alpha and normal branches do not use this strength. No photograph or physical scattering is introduced. The first-hour facial basis remains frozen.
 * @evidence {@link Human.createPortraitHairNormalTexture} Supplies the independently selected card material's resident fibre shading capability without reauthoring the first study.
 * @evidenceReview {@link Human.createPortraitHairNormalTexture} #c83b8ed Read the shared winning-density wave and true-mode encoder. The transverse normal rotates perpendicular to the nominal metric wave slope; empty samples remain flat and Z stays nonnegative. Alpha remains the occupancy authority. Aspect is an authored approximation, not a recovered card metric. The first-hour facial basis remains frozen.
 * @evidence {@link Human.refinePortraitSkinBridge} Retains original-surface interior witnesses inside the attachment boundary.
 * @evidenceReview {@link Human.refinePortraitSkinBridge} #3b0ad1b Read finite/index/chart admission, centroid depth sampling, boundary-preserving Lawson flips and fixed-point termination. A 1e150 coordinate test checks normalized arithmetic. The rectangle requires its two interior witnesses to share an edge: disabling flips failed this assertion and restoration passed. The caller admits annulus manifold topology. Unrepresentable subnormal interior coordinates refuse rather than returning collapsed triangles.
 * @evidence {@link Human.appendPortraitCranium} Appends the cranial continuation to the shared control cage.
 * @evidenceReview {@link Human.appendPortraitCranium} #19719dd Read copied control positions, cranium section sampling and shared face boundary handoff before component refinement. The operation preserves the host's resident identities.
 * @evidence {@link Human.appendPortraitNeck} Appends the authored neck continuation and its crop to the cranial cage.
 * @evidenceReview {@link Human.appendPortraitNeck} #712cf4c Re-read the section/attachment guards, tangent handles and all ring sampling. The new optional projection is admitted before mutation and adds an anterior-only quartic between fixed joins. Zero skips that addition, preserving the frozen document path. Crop remains open; this reading is not visual acceptance or an intersection certificate.
 * @evidence {@link Human.portraitDirectionalSurfaceTargets} Converts complete engine face-clearance deficits into shared metric vertex targets.
 * @evidence {@link Human.portraitMinimumDirectionalSurfaceTargets} Read the shared frame projection, engine-owned bounded contact solve and copied target reconstruction. The ocular consumer keeps subsequent skin propagation and closed-rim correspondence. This source review neither changes the frozen first-girl document nor claims a renewed whole-face render or likeness assessment.
 * @evidenceReview {@link Human.portraitMinimumDirectionalSurfaceTargets} #eec6cdd Read frame admission, projection of both resident inputs, original vertex mapping and forward-only target reconstruction against the existing conservative function. The new function delegates clipping and optimization to the engine; final skin propagation remains in the ocular consumer. No first-girl fitting value or historical artifact is replaced, and current whole-face visual acceptance remains unpaid.
 * @evidenceReview {@link Human.portraitDirectionalSurfaceTargets} #be04133 Read frame projection, retained front triangle ordinals and maximum travel per shared vertex. Every corner of an offending face receives at least that face's deficit, so its interpolated interior cannot retain the original directional penetration. The small enclosed-support oracle moves all three otherwise clear corners; clear/empty support, shared maxima and unrepresentable output are exercised. The host still owns skin adaptation and normals.
 * @evidence {@link Human.IPortraitCheekSocket} Names the live skin attachments for one side's four cheek envelopes and fold path.
 * @evidenceReview {@link Human.IPortraitCheekSocket} #25f27ab Read the six bindings with constructor and fields(host) admission. The layer copies the socket but resolves positions on each supplied refined host, so a changed mouth or nose can move an attachment without an independently frozen cheek origin.
 * @evidence {@link Human.IPortraitCheekSocket.side} Selects the anatomical instance name and outward-offset handedness.
 * @evidenceReview {@link Human.IPortraitCheekSocket.side} #8d28ba6 Traced left/right validation into the layer ID and the sign of only offset[0]. Projection and lift keep the shared Z/Y directions; the offset test moves both inward controls toward the midline at mirrored centres +/-13mm.
 * @evidence {@link Human.IPortraitCheekSocket.malar} Binds upper-cheek support beneath the lateral orbit.
 * @evidenceReview {@link Human.IPortraitCheekSocket.malar} #1318e64 Located its retained vertex in the named-envelope loop and its matching shape.malar dimensions. The volume scenario moves the current host centre while preserving field radius and displacement, showing that the attachment is an identity rather than stored XYZ.
 * @evidence {@link Human.IPortraitCheekSocket.medial} Binds the medial cheek envelope beside the nasal region.
 * @evidenceReview {@link Human.IPortraitCheekSocket.medial} #55e0015 Read lookup of host.positions[socket.medial] before the optional local offset. The hand-defined offset scenario starts at [-20,-10,3]mm and obtains [-13,-4,7]mm on the right; it does not move the underlying datum itself.
 * @evidence {@link Human.IPortraitCheekSocket.buccal} Supplies the lower/lateral cheek's own retained support datum.
 * @evidenceReview {@link Human.IPortraitCheekSocket.buccal} #7c71d02 Compared the buccal binding with the separately indexed malar and medial fields. It is checked for a finite resident position before field construction; sharing dimensions with another envelope does not silently replace this identity.
 * @evidence {@link Human.IPortraitCheekSocket.modiolus} Binds local support outside the oral commissure.
 * @evidenceReview {@link Human.IPortraitCheekSocket.modiolus} #57fb297 Followed its named lookup into the fourth envelope. This datum belongs to neighbouring skin rather than an independent lip endpoint, and its support is evaluated on the same refined host as the other cheek regions.
 * @evidence {@link Human.IPortraitCheekSocket.nasolabial} Supplies the ordered retained skin path used by the fold integration.
 * @evidenceReview {@link Human.IPortraitCheekSocket.nasolabial} #e444486 Read minimum-two/distinct-ID admission, live point resolution and spline sampling. Active folds require nonzero finite path travel; the disabled-fold scenario allows coincident positions without running that integration, while still requiring valid bindings.
 * @evidence {@link Human.IPortraitCheekVolume} Separates support placement and extent from signed surface movement.
 * @evidenceReview {@link Human.IPortraitCheekVolume} #6152713 Compared offset and three radii with projection/lift in the field emitter. Both amplitudes zero omit the envelope, but the constructor still validates its declared dimensions. The type describes one axis-aligned deformation envelope, not a reconstructed fat compartment.
 * @evidence {@link Human.IPortraitCheekVolume.offset} Positions an envelope relative to its current skin anchor.
 * @evidenceReview {@link Human.IPortraitCheekVolume.offset} #df1c92b Checked owned finite triples, zero/omitted equivalence and right-side reversal of the outward component. Later caller mutation cannot alter the existing layer, and adding an unrepresentable offset to the host refuses before emitting a centre.
 * @evidence {@link Human.IPortraitCheekVolume.width} Sets the field's horizontal support radius in millimetres.
 * @evidenceReview {@link Human.IPortraitCheekVolume.width} #17c02c1 Read positive finite admission and conversion to radius.x/1000 in engine metres. The volume test gives 27/64 of central displacement halfway across the radius and zero at its boundary; this value is a support radius, not the complete cheek width.
 * @evidence {@link Human.IPortraitCheekVolume.height} Sets vertical support independently of horizontal spread.
 * @evidenceReview {@link Human.IPortraitCheekVolume.height} #023da86 Traced this positive finite dimension into the engine field's Y radius. It changes where a displacement decays vertically without itself lifting the centre or prescribing upward skin movement.
 * @evidence {@link Human.IPortraitCheekVolume.reach} Limits the envelope through the depth of the head.
 * @evidenceReview {@link Human.IPortraitCheekVolume.reach} #3583a6b Located conversion into radius.z beside independent X/Y radii. This is ellipsoidal depth support; unlike a fitting constraint's reach, it is not a distance propagated along mesh edges.
 * @evidence {@link Human.IPortraitCheekVolume.projection} Supplies signed anterior displacement at the envelope centre.
 * @evidenceReview {@link Human.IPortraitCheekVolume.projection} #518bac6 Read finite signed admission and displacement.z=projection/1000. The two-millimetre centre oracle produces 0.002m through the actual engine deformer, while support dimensions and the optional centre shift retain separate roles.
 * @evidence {@link Human.IPortraitCheekVolume.lift} Supplies signed vertical movement independently of anterior projection.
 * @evidenceReview {@link Human.IPortraitCheekVolume.lift} #129bebb Followed displacement.y=lift/1000 and the active-envelope condition using projection OR lift. The lift-only scenario emits [0,0.003,0]m, so a zero projection does not suppress an independently requested lift.
 * @evidence {@link Human.IPortraitCheekShape} Groups four support envelopes and a separately controlled nasolabial fold.
 * @evidenceReview {@link Human.IPortraitCheekShape} #9111264 Read the four named support volumes and independent fold radius/projection/depth against the copied layer factory. Their summed surface envelopes remain separate controls; their anatomical names do not imply recovered fat-compartment volume.
 * @evidence {@link Human.IPortraitCheekShape.malar} Supplies the upper-cheek envelope's own dimensions and motion.
 * @evidenceReview {@link Human.IPortraitCheekShape.malar} #5226350 Traced it to socket.malar and the first named field. The paired-layer test retains distinct 1mm and 4mm malar projections on the two anatomical sides rather than sharing one mutable setting.
 * @evidence {@link Human.IPortraitCheekShape.medial} Supplies independent medial fullness and centre placement.
 * @evidenceReview {@link Human.IPortraitCheekShape.medial} #661b9bc Read its independent projection/lift and offset alongside the malar entry. The offset and lift-only tests exercise this specific envelope; changing it does not rename the fold path or introduce a nasal attachment.
 * @evidence {@link Human.IPortraitCheekShape.buccal} Supplies the lower/lateral support envelope separately from the high cheek.
 * @evidenceReview {@link Human.IPortraitCheekShape.buccal} #adda9e3 Followed its own radius/amplitude values through the named field loop. The four-envelope scenario retains one field for each active name, including buccal; the current basic shape still lacks freely authored directional sections.
 * @evidence {@link Human.IPortraitCheekShape.modiolus} Controls the local cheek-side support around the mouth corner.
 * @evidenceReview {@link Human.IPortraitCheekShape.modiolus} #b424ecc Compared its independent volume record with the negative fold fields generated later. The local envelope can add support without requiring a groove, but it does not itself define the lip's commissural section.
 * @evidence {@link Human.IPortraitCheekShape.foldWidth} Sets the fold's planar support and sampling density.
 * @evidenceReview {@link Human.IPortraitCheekShape.foldWidth} #6ca3e9f Read division of X/Y path increments by this radius, its use as both emitted planar radii and the resulting sample-count admission. The refusal scenario admits 256 samples at width0.625mm and rejects the adjacent narrower0.624mm request.
 * @evidence {@link Human.IPortraitCheekShape.foldDepth} Controls nonnegative groove magnitude before the negative-Z field sign.
 * @evidenceReview {@link Human.IPortraitCheekShape.foldDepth} #4b2fb19 Traced zero to the early return and positive values through physical-distance sine-squared fading and normalized quadrature weight. The field emitter receives negative depth, so this control recesses the groove without supplying the raised cheek beside it.
 * @evidence {@link Human.IPortraitCheekShape.foldReach} Sets the fold's depth support and its normalized path metric.
 * @evidenceReview {@link Human.IPortraitCheekShape.foldReach} #58f9f23 Located it in the Z increment normalization and emitted radius.z. It therefore affects both field placement density on a depth-varying path and spatial influence through the head; positive finite admission is independent of foldWidth.
 * @evidence {@link Human.createPortraitCheekLayer} Derives owned cheek and fold fields from live refined skin attachments.
 * @evidenceReview {@link Human.createPortraitCheekLayer} #7f94a2f Read copied input/resident checks, side-mirrored offsets, metric field emission, bounded two-stage fold sampling and overflow refusals. The volume/offset tests cover neutral supports and moving anchors. The nineteen observed render sets retain broad perioral transitions; field correctness does not accept cheek likeness.
 * @evidence {@link Human.portraitCutBoundary} Orders the exposed edges of a selected triangle patch.
 * @evidenceReview {@link Human.portraitCutBoundary} #9dbf719 Read undirected incidence counting, retained directed edges, unique outgoing-edge admission and complete-loop traversal. Internal diagonals are excluded; empty, unclosed and disconnected boundary populations refuse. Its ordinals and winding are reused by nasal lining and deferred-region replacement.
 * @evidence {@link Human.IPortraitSkinConstraint} Carries one exact resident skin target and its surrounding adaptation reach.
 * @evidenceReview {@link Human.IPortraitSkinConstraint} #4f67019 Read vertex, XYZ target and reach together in blendPortraitSkin. The fixed map retains requested coordinates while the graph field affects only reachable neighbours; duplicate contradictory targets refuse rather than selecting a component by order.
 * @evidence {@link Human.IPortraitSkinConstraint.vertex} Identifies the existing attachment point rather than appending another seam sample.
 * @evidenceReview {@link Human.IPortraitSkinConstraint.vertex} #f36c397 Checked integral resident-index admission before the fixed target map is updated. The same identity is later retained through subdivision, while inserted vertices receive new indices; negative, fractional and out-of-range IDs are exercised by the attachment scenario.
 * @evidence {@link Human.IPortraitSkinConstraint.target} Supplies absolute construction-space XYZ for the pinned skin sample.
 * @evidenceReview {@link Human.IPortraitSkinConstraint.target} #aa4cac1 Followed length-three finite validation, owned target copying and subtraction of the original point to obtain displacement. The four-corner fan keeps its 4mm lifted corner exact; treating target as a delta would move an already translated attachment twice.
 * @evidence {@link Human.IPortraitSkinConstraint.reach} Limits adaptation by distance travelled along connected skin edges.
 * @evidenceReview {@link Human.IPortraitSkinConstraint.reach} #bd8d49c Read nonnegative finite admission and maximum-remaining-distance propagation. Zero retains the exact pin without freeing neighbours, and the attachment test leaves a nearby disconnected marker unchanged; Euclidean proximity alone does not establish influence.
 * @evidence {@link Human.portraitFacesInsideLoop} Delegates anatomical-loop face selection to the engine's connectivity owner.
 * @evidenceReview {@link Human.portraitFacesInsideLoop} #4b1ed25 Read the complete wrapper: it passes original host indices and the supplied boundary to selectAutoMovieTriangleRegion. No coordinate projection or new face-centroid classifier is introduced, and returned ordinals belong to that original topology.
 * @evidence {@link Human.IPortraitRegionReplacement} Describes a reserved group and its later appender against the refined socket.
 * @evidenceReview {@link Human.IPortraitRegionReplacement} #1b53951 Read region identity and append callback against direct and paired consumers. Appenders extend resident attributes in position order; reference assembly is not a nearest-surface lookup. The protocol does not authorize moving unrelated host vertices.
 * @evidence {@link Human.IPortraitRegionReplacement.group} Names the reserved face population inherited through subdivision.
 * @evidenceReview {@link Human.IPortraitRegionReplacement.group} #a229933 Traced the group label into selection of current refined faces and one-time removal. Duplicate, negative and fractional labels refuse before appenders run, and an absent label fails boundary extraction; this value is not an original face ordinal.
 * @evidence {@link Human.IPortraitRegionReplacement.append} Installs a sampled source after the shared host has refined its socket.
 * @evidenceReview {@link Human.IPortraitRegionReplacement.append} #c9ecd98 Read the callback handoff after all replacement boundaries have been resolved. The actual head scenario receives six boundary segments from one subdivided triangular reservation, so it cannot accidentally construct against the original three-edge cage.
 * @evidence {@link Human.applyPortraitRegionReplacements} Collects reserved boundaries before mutating an owned replacement mesh.
 * @evidenceReview {@link Human.applyPortraitRegionReplacements} #12c591e Read precomputed boundaries, owned geometry/attribute copies and appenders. Both optional reference and RGB must end aligned with positions. The head pairs appenders, while direct clients extend attributes themselves. Units exercise preserved alignment and rejection of either missing entry.
 * @evidence {@link Human.IPortraitFinalSurfaceHost} Exposes the common post-layer geometry seen by final component proposals.
 * @evidenceReview {@link Human.IPortraitFinalSurfaceHost} #07f757b Read its four readonly buffers beside the assembler's deeply frozen snapshot. Providers share one object before any result is applied; the final-surface scenario verifies identity and failed writes to positions, indices, groups and normals.
 * @evidence {@link Human.IPortraitFinalSurfaceHost.positions} Supplies immutable construction-millimetre coordinates to final shaping.
 * @evidenceReview {@link Human.IPortraitFinalSurfaceHost.positions} #7623632 Checked the outer array and every copied coordinate row are frozen. A later proposal still observes the original first vertex after an earlier provider requests its movement, preventing order-dependent fitting against partially applied positions.
 * @evidence {@link Human.IPortraitFinalSurfaceHost.indices} Retains shared triangle identities during positional proposals.
 * @evidenceReview {@link Human.IPortraitFinalSurfaceHost.indices} #3f4f549 Followed the copied frozen index buffer into the observer and the unchanged original indices in the returned mesh. This stage can prescribe existing vertex positions but does not accept replacement topology in its proposal type.
 * @evidence {@link Human.IPortraitFinalSurfaceHost.groups} Preserves per-triangle anatomical/material-region labels for target selection.
 * @evidenceReview {@link Human.IPortraitFinalSurfaceHost.groups} #df64e52 Read frozen label copying and the nasal/eyelid providers' group-based vertex selection. Labels remain triangle-local even when neighbouring regions share a vertex; they do not permit contradictory owners to overwrite each other.
 * @evidence {@link Human.IPortraitFinalSurfaceHost.normals} Supplies directions computed on the common unmodified proposal basis.
 * @evidenceReview {@link Human.IPortraitFinalSurfaceHost.normals} #ee4186a Traced the single portraitNormals call before provider execution. The buffer is not recomputed after each proposal; the head assembler performs the final common recomputation after positions are accepted and before material extraction.
 * @evidence {@link Human.IPortraitFinalSurface} Specifies a callback returning resident vertex targets rather than a detached mesh.
 * @evidenceReview {@link Human.IPortraitFinalSurface} #1ac9fbd Compared its readonly proposal array with output copying and finite XYZ/resident-index admission. Identical shared requests are compatible; different coordinates at one identity refuse even when both individual requests are finite.
 * @evidence {@link Human.applyPortraitFinalSurfaces} Applies compatible final positions after every provider has observed the same basis.
 * @evidenceReview {@link Human.applyPortraitFinalSurfaces} #afd198d Read immutable snapshots, copied proposals, ownership checks and final mesh spread. Only positions change; reference/RGB and topology survive. Empty providers or targets retain the input. The reference-coordinate unit pins attribute preservation; compatible geometry still requires visual review.
 * @evidence {@link Human.IControlMesh.positions} Preserves construction-space vertex identities during shared refinement.
 * @evidenceReview {@link Human.IControlMesh.positions} #c782da5 Read XYZ arrays in the Loop masks and the host's final metric packing. Original indices survive as moved samples, while inserted edge positions are appended once per shared edge.
 * @evidence {@link Human.IControlMesh.indices} Carries oriented triangles over the common vertex population.
 * @evidenceReview {@link Human.IControlMesh.indices} #6a94ca6 Followed edge adjacency and four child triples per face. The array is topology, not an anatomical boundary label; the optional curves must name actual resident edges.
 * @evidence {@link Human.IControlMesh.groups} Retains each triangle's material-region ownership through subdivision.
 * @evidenceReview {@link Human.IControlMesh.groups} #bcbcae3 Read four copies per parent face and the head's later region extraction. Shared edge vertices are refined once even when adjacent labels differ; colour separation happens only after shared normals.
 * @evidence {@link Human.createPortraitDirectionalIntersection} Intersects the foremost resident triangle from either side while preserving the original transverse projection; the canthal consumer uses its actual emitted surface.
 * @evidenceReview {@link Human.createPortraitDirectionalIntersection} #4832c15 Read the entire query with contactFrame, project and advance. A direct projection into one orthonormal frame avoids shifting an apex before its footprint query. The independent z=2 and x=2 triangle scenarios check forward/backward travel, boundary hits, misses, normalized direction, caller ownership and invalid inputs. The translated/oblique canthal scenario reaches the actual emitted apices using identical metric scaling. This directional hit alone does not establish skin thickness or global collision freedom.
 * @evidence {@link Human.createPortraitDirectionalContact} Resolves a contact target from resident triangles along a declared projection direction.
 * @evidenceReview {@link Human.createPortraitDirectionalContact} #5776a66 Read the shared contactFrame/project/advance path and the closure's foremost resident depth query. Independent frontal, diagonal, reversed and Y-normal plane oracles preserve the projected point and exact identity on clear or missed rays; invalid inputs and overflow refuse. The separate surface-target consumer now handles triangle interiors, which this point query alone cannot constrain.
 * @evidence {@link Human.IPortraitSurfaceControl} Describes a named requested movement on the common refined surface.
 * @evidenceReview {@link Human.IPortraitSurfaceControl} #2d5e07e Read all four fields with the coupled solver and nasal consumer. The displacement is a target right-hand side, while coefficients are solved from the whole population; treating it as an independent bump amplitude would miss neighbouring zero constraints.
 * @evidence {@link Human.IPortraitSurfaceControl.name} Names each anatomical handle and fixes deterministic elimination order.
 * @evidenceReview {@link Human.IPortraitSurfaceControl.name} #3008690 Traced copied controls through compareCodeUnits sorting and nonempty/duplicate-name refusal. Reversing the two-point input reproduces the same emitted fields without changing an anchor's physical target.
 * @evidence {@link Human.IPortraitSurfaceControl.anchor} Supplies the retained host vertex from which a control is located.
 * @evidenceReview {@link Human.IPortraitSurfaceControl.anchor} #c9d8e8d Read integer/nonnegative admission and resident finite-datum lookup in fields(host). A changed host relocates the handle; a missing resident point refuses before interpolation rather than defaulting to the origin.
 * @evidence {@link Human.IPortraitSurfaceControl.offset} Places an intermediate control relative to its live anatomical datum.
 * @evidenceReview {@link Human.IPortraitSurfaceControl.offset} #66e0dfd Compared the copied three-number offset and finite sum with the translated-frame test. The offset locates the kernel centre in millimetres and is not part of its requested movement.
 * @evidence {@link Human.IPortraitSurfaceControl.displacement} Prescribes the combined XYZ movement at one control position.
 * @evidenceReview {@link Human.IPortraitSurfaceControl.displacement} #a867909 Followed all three right-hand sides through common elimination and final metre conversion. The independent two-point inverse reproduces a nonzero first target and a zero neighbour; coefficient overflow refuses before any final field is emitted.
 * @evidence {@link Human.createPortraitControlLayer} Solves coupled anatomical targets into fields consumed by the shared surface assembler.
 * @evidenceReview {@link Human.createPortraitControlLayer} #3be53ee Read normalized engine probes, pivot selection, singular refusal and the three-axis output against actual assembly tests. A 0.2 mm nasal target reaches its refined control and moves resident lining while the remote chin remains fixed. The engine checks the final field and triangles; neither those checks nor interpolation prove global nonintersection or likeness.
 * @evidence {@link Human.IPortraitComponent} Separates an anatomical instance's identity, finishes and host-fitting operation.
 * @evidenceReview {@link Human.IPortraitComponent} #a0abcb5 Read all three members with head assembly and model material collection. The assembler calls fit on one unchanged host; the interface does not itself promise a correct external shape.
 * @evidence {@link Human.IPortraitComponent.id} Names the fitting owner used to reject duplicate component instances.
 * @evidenceReview {@link Human.IPortraitComponent.id} #759c65d Traced the head's unique-id check and its final-surface provider names. Separate eyes supply side-qualified identities, while nose and mouth each retain one owner.
 * @evidence {@link Human.IPortraitComponent.fit} Produces original-host constraints, cuts and the later attachment procedure.
 * @evidenceReview {@link Human.IPortraitComponent.fit} #9df446b Compared the head's complete plans map with subsequent blending. No component receives a predecessor's displaced host, so fit order cannot silently redefine its input surface.
 * @evidence {@link Human.IPortraitComponent.materials} Carries optional instance-owned finishes into the assembled palette.
 * @evidenceReview {@link Human.IPortraitComponent.materials} #71f2a1d Read the model's flatMap with an empty omission case and the eye factory's side-specific corneal materials. Optical thickness is captured with its eye rather than copied to a shared palette entry.
 * @evidence {@link Human.IPortraitComponentHost} Carries the original geometry and recorded view ray into every fitted part.
 * @evidenceReview {@link Human.IPortraitComponentHost} #5b3fb54 Read positions, indices and viewRay against eye, nose and mouth fitting. Construction coordinates use millimetres and the ray preserves the declared observation direction; the data is a caller-owned basis, not anatomical ground truth.
 * @evidence {@link Human.IPortraitComponentHost.positions} Retains original skin identities and the non-skin gaze markers.
 * @evidenceReview {@link Human.IPortraitComponentHost.positions} #e5848ff Followed socket-index lookup and the eye's copied aperture array. Gaze markers remain addressable although they need not occur in a triangle, which differs from the compacted material meshes.
 * @evidence {@link Human.IPortraitComponentHost.indices} Establishes original triangle ordinals for component cuts.
 * @evidenceReview {@link Human.IPortraitComponentHost.indices} #000a7cf Traced cut validation against indices.length/3 and the later traversal of original triples. Removing a patch does not renumber another component's requested cut before collection.
 * @evidence {@link Human.IPortraitComponentHost.viewRay} Supplies the measured projection direction for ocular placement and optional nasal body depth.
 * @evidenceReview {@link Human.IPortraitComponentHost.viewRay} #ae05916 Read sphere intersection, socket translation and the final nasal adapter. Consumers use a direction, not a point; its recorded pose remains a monocular estimate.
 * @evidence {@link Human.IPortraitComponentPlan} Splits a fitted part into exact host requests and shared-topology attachment.
 * @evidenceReview {@link Human.IPortraitComponentPlan} #12939dc Read constraints, original cut ordinals and the complete attach protocol beside preparePortraitHead and buildPortraitHead. The optional native provider reads sealed skin before packing; its empty result is authoritative and its presence suppresses compatibility finish. Existing openings, closures, curves, replacements and final proposals retain their owners.
 * @evidence {@link Human.IPortraitComponentPlan.constraints} Defines the complete exact attachment requests collected before skin blending.
 * @evidenceReview {@link Human.IPortraitComponentPlan.constraints} #dd57864 Followed plans.flatMap into blendPortraitSkin. Each request retains its vertex, target and reach; contradictory exact targets are the blend owner's refusal rather than a last-writer policy.
 * @evidence {@link Human.IPortraitComponentPlan.cutFaces} Identifies original faces replaced by component topology.
 * @evidenceReview {@link Human.IPortraitComponentPlan.cutFaces} #bf95039 Checked integral resident-ordinal and duplicate-cut refusal in buildPortraitHead. The list is not a set of post-subdivision material triangles.
 * @evidence {@link Human.IPortraitComponentPlan.attach} Appends shared geometry and returns the actual final-surface consumers.
 * @evidenceReview {@link Human.IPortraitComponentPlan.attach} #7117ddd Read cage/adapted/region inputs and every returned field, including additive native preparation. Contact sealing precedes provider calls; native and compatibility paths read the same final skin without mutation. The consumer invokes only one path for each component and retains component output order.
 * @evidence {@link Human.portraitPoint} Supplies the common XYZ value used by the study's construction-space curves and component frames.
 * @evidenceReview {@link Human.portraitPoint} #81b044d Read the direct x/y/z object construction: it retains millimetre coordinates without a hidden scale or axis swap, so the later portraitPart conversion remains the unit boundary.
 * @evidence {@link Human.portraitMix} Interpolates scalar coordinates and dimensions within the authored surface sections.
 * @evidenceReview {@link Human.portraitMix} #7097558 Compared a+(b-a)*t with its callers' local curve progress. It preserves endpoints and permits extrapolation; callers, rather than this scalar helper, own admissible parameter intervals.
 * @evidence {@link Human.portraitRayIntersection} Provides a bracketed camera-ray intersection for a caller-owned finite height surface.
 * @evidenceReview {@link Human.portraitRayIntersection} #7dc08cf Traced origin+t*direction and the signed height residual through forty bisections. Endpoint finiteness and sign bracketing are enforced; continuity and finiteness of the supplied surface remain caller preconditions, and the helper is not a general visibility query.
 * @evidence {@link Human.portraitNormals} Computes the shared skin/lining normal field before material regions are separated.
 * @evidenceReview {@link Human.portraitNormals} #a98ab37 Read area-weighted accumulation and the finite-sum guard before normalization. The normal-admission test refuses each overflowing coordinate sum and nonfinite cross product, while its adjacent representable planar input retains +Z. The hair-card consumer test reaches the same overflow boundary; the frozen portrait GLB remains byte-identical. Unused vertices retain zero, and shared normals alone do not establish the intended tangent.
 * @evidence {@link Human.portraitRegion} Extracts named material geometry while preserving the common field and original vertex identity.
 * @evidenceReview {@link Human.portraitRegion} #531cf29 Read first-use remapping and corner-colour admission. Keys combine old vertex identity with exact RGB only when supplied, splitting buffer vertices without splitting parent normals. Other coincident coordinates are not welded. Invalid count, triples, finite values or range refuse.
 * @evidence {@link Human.portraitPart} Converts completed construction meshes into static metre-space AutoMovie parts.
 * @evidenceReview {@link Human.portraitPart} #262ffdc Checked the engine transform's uniform 0.001 scale and null part transform/bone binding. Positions cross from millimetres to metres once while the engine preserves normal direction; the exported capture uses these resident buffers.
 * @evidence {@link Human.portraitPatch} Produces the shared rectangular sampling lattice used by authored parametric surfaces.
 * @evidenceReview {@link Human.portraitPatch} #e8578a7 Read both triangle triples per cell and their du-cross-dv orientation. Sampling includes both parameter endpoints without pole welding or caps. Its area normals therefore cannot supply a direction at an entirely collapsed pole; spherical owners now provide that derivative explicitly.
 * @evidence {@link Human.portraitSpline} Interpolates ordered spatial landmarks for lid, dental and other study curves.
 * @evidenceReview {@link Human.portraitSpline} #6e41fe7 Compared the uniform Catmull-Rom polynomial, repeated endpoint neighbours and clamped progress. The parameter is not physical arc length, so dental spacing is delegated to its separate arc-distance sampler.
 * @evidence {@link Human.portraitTube} Sweeps the coarse lash/brow strands in their construction frame.
 * @evidenceReview {@link Human.portraitTube} #e948aad Read tangent sampling and the fixed-Z cross-section guide, eight-sided rings and normal construction. Zero/nonfinite or Z-parallel tangents refuse; the tube is open-ended unless its owner closes it. Brow and lash consumers retain coarse authored fibres rather than a detailed hair system.
 * @evidence {@link Human.placePortraitMesh} Protects each part's actual placement before its final precision conversion.
 * @evidenceReview {@link Human.placePortraitMesh} #eb3a18c Read the translation-free (0,b-a,c-a) reference transformed by the same engine operation. Redundancy is classified after linear scale, so an enlarged tiny source face cannot borrow a pole exemption when a large translation erases it; supported rotations and baked mirrors retain their intended winding.
 * @evidence {@link Human.portraitMeshBuffers} Materializes and validates the actual Float32/Uint32 geometry delivered to glTF.
 * @evidenceReview {@link Human.portraitMeshBuffers} #1a04698 Read exact aligned Float32/Uint32 conversion, redundant-face ordinal retention, nonredundant orientation and unit-NORMAL tolerance. Collapse/inversion, changed redundant ordinals and zero normals refuse. All nineteen current exports traversed this actual conversion; byte parity and finite geometry remain separate from likeness.
 * @evidence {@link Human.portraitGltfExtensions} Declares the optical extension classes registered on this study's GLTF readers and writers.
 * @evidenceReview {@link Human.portraitGltfExtensions} #6fffc2a Compared the four registered classes with the exporter: clearcoat, IOR, transmission and volume are preserved by the actual SDK round trip. An unregistered reader/writer would be a different delivery path and is not covered by the captures.
 * @evidence {@link Human.portraitDocument} Converts the complete static study into resident GLTF material groups and attributes.
 * @evidenceReview {@link Human.portraitDocument} #cb42450 Reread the complete exporter after optional RGB was added. Placement and material merging now carry resident colours to a COLOR_0 VEC3 Float32 accessor; absent colours skip allocation. The final model validator rejects incomplete, nonfinite and out-of-range source RGB. Existing topology, optical closure, PNG deduplication, UV admission and unsupported-resource refusals remain in place. This source inspection does not certify expression-attached pigmentation or a new frozen-study replay; the earlier 11,177,028-byte replay predates this attribute change.
 * @evidence {@link Human.IControlMesh} Carries the shared triangular control positions, connectivity and one material label per face.
 * @evidenceReview {@link Human.IControlMesh} #56fc2e5 Read positions, face indices/groups and optional aligned reference XYZ/RGB beside all refinement consumers. Reference is a material coordinate chart, not final rest-state anatomy. Omission stays absent; the type itself does not admit topology or cardinality.
 * @evidence {@link Human.subdivideControlMesh} Refines the connected triangular cage before its shared normals and interiors are finalized.
 * @evidenceReview {@link Human.subdivideControlMesh} #2bc2ab2 Read every Loop and curve branch after sharing the refinement mask for positions, optional reference XYZ and RGB. Edge identities and face groups propagate each round; omitted attributes stay absent. The narrow-field unit demonstrates why product pigment is evaluated after reference refinement instead of interpolating only control RGB.
 * @evidence {@link Human.assertPortraitSkinTopology} Audits the declared openings and stitches of the complete control cage before refinement.
 * @evidenceReview {@link Human.assertPortraitSkinTopology} #dcbad64 Read the exact expected-edge set, duplicate opening refusal and two opposite incident directions for internal edges. Missing or undeclared openings fail independently of vertex position, so this verifies connectivity rather than anatomical shape or global self-intersection.
 * @evidence {@link Human.blendPortraitSkin} Adapts neighbouring skin to exact component attachments on one unchanged host.
 * @evidenceReview {@link Human.blendPortraitSkin} #70dbb80 Read the host assembly call through all simultaneous part constraints, unchanged reach propagation and the new free-vertex Dirichlet operator. Pins and unreachable positions remain exact; self edges contribute zero. The separate solvePortraitSkinSystem owner uses Jacobi-preconditioned conjugate gradients, checks the original equation residual and refuses breakdown or iteration exhaustion without caller mutation. The independent 101-ring cylinder reduces maximum displacement error from 0.6010787634mm to 3.22e-15mm. This verifies interpolation on an analytic case, not tissue physics or likeness. All 114 paired model/GLB comparisons and hardware captures are complete. Fourteen states change adaptive eyelid triangulation; corresponding vertices move at most 0.003411805mm, excluding changed topology. Directly inspected Alan and Yoo in all six states plus Daniel observed (13 paired sheets) show no discernible broad form change at their sheet scale. Remaining sheets await direct inspection. This is no whole-face likeness approval; representative-first experiments now precede the final population regression. Historical inspection retained: Read exact hard constraints and contradictory-target refusal beside the active-frontier distance propagation. Positive remaining reach enters the frontier, settled vertices are not reopened, and equal priorities retain ascending vertex identity. The sorted free vertices and weighted displacement sweeps are unchanged. Omitted, zero and infraorbital-pad complete unit faces reproduce the previous source exactly; this numerical comparison does not establish anatomical tangent, volume or likeness.
 * @evidence {@link Human.IPortraitReliefRegion} Separates each support's live vertex binding and offset from its metric support radii and signed displacement.
 * @evidenceReview {@link Human.IPortraitReliefRegion} #9908253 Read the named anchor, XYZ offset, three positive radii and displacement fields against the layer adapter. All use head-space millimetres; the anchor follows replacement, while these envelopes remain visible-surface controls rather than reconstructed internal tissue.
 * @evidence {@link Human.createPortraitReliefLayer} Converts owned anatomical support settings into engine deformation fields on the live skin.
 * @evidenceReview {@link Human.createPortraitReliefLayer} #6a87ee4 Traced copied regions, unique names, resident-anchor checks and the millimetre-to-metre conversion of centre/radius/displacement. Zero displacement emits no field and stretch stays zero; the final surface assembler supplies aperture protection and common normals.
 * @evidence {@link Human.IPortraitReliefCurvePoint} Declares one resident attachment, offset, support and displacement control for a continuous anatomical surface curve.
 * @evidenceReview {@link Human.IPortraitReliefCurvePoint} #886f2fe Read the four finite millimetre fields and resident anchor contract beside the curve layer; each control follows the live skin without creating a detached section.
 * @evidence {@link Human.IPortraitReliefCurve} Groups ordered curve controls under one named surface responsibility.
 * @evidenceReview {@link Human.IPortraitReliefCurve} #77e3c95 Read the unique name and bounded ordered control population beside the curve factory; the group is independently optional and shares the existing host.
 * @evidence {@link Human.createPortraitReliefCurveLayer} Samples adjacent controls into overlapping metric fields while preserving live endpoints and boundary ownership.
 * @evidenceReview {@link Human.createPortraitReliefCurveLayer} #30aae88 Read copied ordered curve controls, resident attachments, segment-start and two interior-third samples, one retained final endpoint, interpolated supports and millimetre conversion. The earlier wording of three interior samples was incorrect; the actual loop uses t=0, 1/3 and 2/3 on each segment.
 * @evidence {@link Human.IPortraitSurfaceHost} Gives anatomical layers the shared post-subdivision coordinates, topology and normal field.
 * @evidenceReview {@link Human.IPortraitSurfaceHost} #423655e Read the readonly millimetre position arrays, triangle identities and dimensionless flat normals against the layer consumers. This is a declared read-only view, not an assertion that an arbitrary callback is physically incapable of mutation.
 * @evidence {@link Human.IPortraitSurfaceLayer} Separates a surface layer's identity from its derivation of metric engine fields on live attachments.
 * @evidenceReview {@link Human.IPortraitSurfaceLayer} #c97a8b8 Re-read optional sampleSpacing beside stable identity and fields(host). Spacing is a millimetre request around this layer's own metric fields; omission or no fields leaves sampling unchanged. Every factory still observes the same original host, and the caller owns geometry and material extraction.
 * @evidence {@link Human.applyPortraitSurfaceLayers} Applies the composed surface displacement with open-rim protection before common normals and material extraction.
 * @evidenceReview {@link Human.applyPortraitSurfaceLayers} #51e2124 Re-read the complete composition and geodesic-mask path. Fields are admitted before optional local refinement, each sampling request uses only its own fields, and all factories observe the same host. Refined shared topology supplies distances and mask gradients before the one compiled deformer runs. Raw square tests give the inserted centre 0.1 mm movement, retain all open-rim points and leave a foreign layer unrefined when the requesting layer is empty. Final normals remain the assembler's responsibility.
 * @evidence {@link Human.IPortraitHeadFormation} Carries the shared cranial, cervical, performance and colour preparation input.
 * @evidenceReview {@link Human.IPortraitHeadFormation} #bcc0744 Read all four optional fields and both assembly consumers. The extracted input retains existing defaults; its appearance basis is material coordinates rather than physical rest geometry.
 * @evidence {@link Human.IPortraitHeadFormation.cranium} Selects the reference cranial continuation during shared preparation.
 * @evidenceReview {@link Human.IPortraitHeadFormation.cranium} #484d37f Traced the unchanged optional profile to appendPortraitCranium for current and paired-reference cages before refinement.
 * @evidence {@link Human.IPortraitHeadFormation.neck} Selects the cervical continuation before final materialization.
 * @evidenceReview {@link Human.IPortraitHeadFormation.neck} #c427894 Traced the same optional neck profile to both paired assemblies; its existing ordering and finite-value admission remain in appendPortraitNeck.
 * @evidence {@link Human.IPortraitHeadFormation.performance} Separates current facial vertices from newly performed continuation tissue.
 * @evidenceReview {@link Human.IPortraitHeadFormation.performance} #959d621 Read copied reference construction and the appended-only pose loop. Existing component IDs retain their performed positions and invalid callback coordinates still refuse.
 * @evidence {@link Human.IPortraitHeadFormation.appearance} Pairs observed colour coordinates with current component geometry.
 * @evidenceReview {@link Human.IPortraitHeadFormation.appearance} #255115d Read component order, topology, region, curve and replacement correspondence checks plus finite linear RGB admission. Current final proposals do not replace reference coordinates.
 * @evidence {@link Human.preparePortraitHead} Prepares shared skin and retains component finishers for the actual head consumer.
 * @evidenceReview {@link Human.preparePortraitHead} #f317855 Read the complete extracted fit, blend, cut, attach, continuation, reference, refinement, replacement, final-proposal and RGB path. It returns an unsealed surface without invoking interiors; buildPortraitHead consumes it before common normals and finishing. This is no global collision guarantee.
 * @evidence {@link Human.buildPortraitHead} Consumes prepared shared skin before contact sealing, common normals, material separation and attached interiors.
 * @evidenceReview {@link Human.buildPortraitHead} #dcca9a7 Read the complete consumer: unchanged preparation, explicit contact sealing, all native providers, common normals and colour-bearing skin regions, then ordered native packing or legacy finish. Empty native arrays do not fall back. No joint solve is invoked. Reference/current identities and retained colour corners remain owned by preparation and sealing; earlier multi-view limitations and unaccepted likeness remain.
 */
export const portraitSurfaceReview = {
  scope: "surface construction inspection",
};
