import type * as Human from "@automovie/human";

/**
 * Inspection of the connected-prior schema, evaluator and compact document IO.
 * Read the implementation owners and their actual worker/panel consumers.
 * The CC0 study's endpoint export and GPU observations live beside its payload;
 * this source inspection does not accept individual anatomy or photo likeness.
 *
 * @evidence requirements/actors/facial-authoring/contract.md#actor-face-connected-basis The connected study supplies a licensed neutral prior and independent compact edits to the real browser consumer.
 * @evidence specifications/asset-and-representation/facial-authoring/contract.md#face-spec-connected-basis The selected six-surface asset and worker exercise immutable basis compilation, common normals and revision-bound edits.
 * @evidence {@link Human.IAutoMovieHumanFaceControlMap} Read the basis-bound coordinate map and its disjoint shape membership; labels describe authored effects rather than measured age or anatomy.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceControlMap} #0c4334f Read the complete map declaration against compilation and the Simple/Fine consumer. Only fine weights enter documents and geometry; the map stores no person-specific displacement.
 * @evidence {@link Human.IAutoMovieHumanFaceControlMap.basis} Read exact basis matching before compiling any group.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceControlMap.basis} #f5049fe The map's exact identity is checked against the supplied basis; no inferred migration is accepted.
 * @evidence {@link Human.IAutoMovieHumanFaceControlMap.groups} Read distinct group identities and disjoint shape members against projection, labels and descriptions.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceControlMap.groups} #5e6f21b Read blank metadata, empty membership, unknown or expression members and duplicate membership refusals. Unlisted fine coordinates survive resolution.
 * @evidence {@link Human.createHumanFaceControlMap} Read signed endpoint normalization, mean/residual projection, feasible intervals and origin-based resolution against independent unequal-unit examples and the panel consumer.
 * @evidenceReview {@link Human.createHumanFaceControlMap} #1cbca1c Reread normalization, mean/residual projection, domain intersection and origin-based resolution with the unequal-unit, refusal and boundary scenarios. The three-member endpoint case reproduced an origin outside its own displayed interval due to subtraction rounding. The interval now explicitly contains that already admitted origin; outward edits still refuse and no-op restores exact omitted fields. Map ownership protects prototype-named coordinates and repeated replay from caller mutation. This is numerical authoring, not anatomical or demographic calibration.
 * @evidence {@link Human.IAutoMovieHumanFaceBasis} Read the schema and admission against the selected CC0 asset, including sparse endpoints, shared topology, complete material partitions and owned compilation.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasis} #03f15cb Read the schema and admission against the selected CC0 asset, including sparse endpoints, shared topology, complete material partitions and owned compilation. Reread after the optional corrective population was added: a corrective is admitted against the channels it drives, so a driver that is not a channel and a side a channel does not have both refuse rather than evaluating to a silent zero, its identity shares the channels' uniqueness, and its endpoint is resolved like any other. Omission is the purely linear prior this basis was. Reread after the schema version was removed: the immutable revision ID the contract asks for is the `id`, which the builder still matches exactly against the document that names it. Reread after a corrective input gained an optional peak: an in-between is a driver whose factor is a tent rather than a clamp, one at the named weight and zero again at full, so a corrective solved at half weight hands over to the full-weight one instead of stacking on it; omission is the plain clamp, and a peak outside (0,1] refuses. Reread after the optional span: an input may name the driver weights on either side of its peak where the tent fades to nothing, because two in-betweens on one driver spanning the whole envelope fire into each other's poses, and a tongue solved at three quarters was measured to re-cross at a half; omission is the whole envelope, and a span whose lower end is not below the peak, whose upper end is below it, or that leaves [0,1] refuses.
 * @evidence {@link Human.IAutoMovieHumanFaceBasis.id} Read nonblank identity admission and the builder's exact document-to-basis binding.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasis.id} #5362f20 Read nonblank identity admission and the builder's exact document-to-basis binding.
 * @evidence {@link Human.IAutoMovieHumanFaceBasis.channels} Read finite neutral-containing ranges, distinct signed endpoint selection, ordered accumulation and fixed surfaces when an endpoint is absent locally.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasis.channels} #8b34e29 Read finite neutral-containing ranges, distinct signed endpoint selection, ordered accumulation and fixed surfaces when an endpoint is absent locally.
 * @evidence {@link Human.IAutoMovieHumanFaceBasis.surfaces} Read topology admission, sparse vertex ordering, nonzero differences, oriented triangle partition and common-normal construction before UV separation.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasis.surfaces} #933f340 Read topology admission, sparse vertex ordering, nonzero differences, oriented triangle partition and common-normal construction before UV separation.
 * @evidence {@link Human.IAutoMovieHumanFaceBasis.materials} Read unique resident identities, copied overrides and final model/export material admission.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasis.materials} #20d5ec5 Read unique resident identities, copied overrides and final model/export material admission.
 * @evidence {@link Human.IAutoMovieHumanFaceBasisDocument} Read exact compact schema admission and independent shape, performance and appearance ownership against the generic transaction consumer.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasisDocument} #0fdf835 Read the compact schema after removing identity and document correctives. Shape/expression values, material overrides and hair/skin resource identities remain; exact schema admission refuses legacy geometry instead of silently discarding it. The compact-boundary scenario reproduces the old acceptance and checks load, save and direct build refusal.
 * @evidence {@link Human.IAutoMovieHumanFaceBasisDocument.id} Read nonblank identity admission and preservation into the resident model and downloaded filename.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasisDocument.id} #d5d2223 Read nonblank identity admission and preservation into the resident model and downloaded filename.
 * @evidence {@link Human.IAutoMovieHumanFaceBasisDocument.name} Read nonblank display identity admission and preservation into model and editor status.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasisDocument.name} #44def0f Read nonblank display identity admission and preservation into model and editor status.
 * @evidence {@link Human.IAutoMovieHumanFaceBasisDocument.basis} Read exact compiled-basis matching without implicit conversion or external URL resolution.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasisDocument.basis} #47fd14e Read exact compiled-basis matching without implicit conversion or external URL resolution.
 * @evidence {@link Human.IAutoMovieHumanFaceBasisDocument.shape} Read explicit shape-group validation, neutral omission and signed endpoint weights without clamping.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasisDocument.shape} #0c878d7 Read explicit shape-group validation, neutral omission and signed endpoint weights without clamping.
 * @evidence {@link Human.IAutoMovieHumanFaceBasisDocument.expression} Read expression-group validation and independent transient state; the source endpoint model does not guarantee physiological interpolation.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasisDocument.expression} #5422939 Read expression-group validation and independent transient state; the source endpoint model does not guarantee physiological interpolation.
 * @evidence {@link Human.IAutoMovieHumanFaceBasisDocument.materials} Read resident-ID validation, optional RGB/roughness boundaries, material copying and preservation of resident texture bytes.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasisDocument.materials} #28eb2fc Read resident-ID validation, optional RGB/roughness boundaries, material copying and preservation of resident texture bytes.
 * @evidence {@link Human.createHumanFaceBasisRegion} Read source/UV identity compilation and owned position/normal gathers against hand-permuted seam, null UV and empty examples.
 * @evidenceReview {@link Human.createHumanFaceBasisRegion} #dc7571e Read every compilation and gather branch against the region-compilation scenario's explicit source permutation, UV seam, null UV, empty region and independent mutation cases. The connected builder compiles each region once; the one-shot API delegates to the same owner.
 * @evidence {@link Human.createHumanFaceBasisBuilder} Read schema admission, immutable compilation, range checks, ordered signed sparse sums, common normal reconstruction, UV/material separation and final model validation. The actual worker consumes the builder and the existing exporter emits its result.
 * @evidenceReview {@link Human.createHumanFaceBasisBuilder} #8464235 Reread the prepared neutral admission and its complete validateModel/validateMesh consequence surface. Static references, indices, UVs and source materials are owned and admitted before the builder returns; document domains and finite normal construction remain per evaluation. Equal welded vertex classes preserve edge incidence under fixed indices. A changed partition still takes the full gate, and neither a valid fallback nor a refusal replaces the neutral expectation. The two-triangle scenario exercises valid merging, invalid same-winding superposition, returned-array mutation and invalid source roughness. Ordered channel/corrective arithmetic remains unchanged. This structural reuse establishes neither collision freedom nor anatomical validity.
 * @evidence {@link Human.parseHumanFaceBasisDocument} Read the shared UTF-16 text budget, JSON and exact-schema admission, finite numbers and nonblank identities. Basis-specific channel validation remains with the compiled builder.
 * @evidenceReview {@link Human.parseHumanFaceBasisDocument} #04edd49 Read the shared UTF-16 text budget, JSON and exact-schema admission, finite numbers and nonblank identities. Basis-specific channel validation remains with the compiled builder.
 * @evidence {@link Human.serializeHumanFaceBasisDocument} Read finite admission before JSON serialization and the shared size check after escaping and formatting, so a successful save fits the loader envelope; geometry remains separately versioned.
 * @evidenceReview {@link Human.serializeHumanFaceBasisDocument} #9d35caa Read finite admission before JSON serialization and the shared size check after escaping and formatting, so a successful save fits the loader envelope; geometry remains separately versioned.
 * @evidence {@link Human.measureHumanFaceBasisChannels} Read the whole-basis accumulation: every surface's sparse rows for one endpoint are summed before dividing by the shared resident vertex count, the empty-population refusal that keeps NaN out of a published measurement, and that an absent endpoint measures zero because admission already refuses that basis. The connected panel prints its result and the whole-face study fit prices shape weights with the same figures.
 * @evidenceReview {@link Human.measureHumanFaceBasisChannels} #bbc046d Read the whole-basis accumulation: every surface's sparse rows for one endpoint are summed before dividing by the shared resident vertex count, the empty-population refusal that keeps NaN out of a published measurement, and that an absent endpoint measures zero because admission already refuses that basis. The connected panel prints its result and the whole-face study fit prices shape weights with the same figures.
 * @evidence {@link Human.IAutoMovieHumanFaceSkin} Read the appearance schema against what the basis cannot carry: one flat colour per material and no map for skin, so a subject's pores, static creases and discolouration have no home in any shape weight.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceSkin} #a101358 Read the appearance schema against what the basis cannot carry: one flat colour per material and no map for skin, so a subject's pores, static creases and discolouration have no home in any shape weight. Reread with its documented members separated: the appearance still replaces maps on material identities the basis already declares and introduces none, so a map for a surface this face does not have cannot silently do nothing.
 * @evidence {@link Human.IAutoMovieHumanFaceSkin.id} Read the stable appearance identity carried independently of the face it is worn on.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceSkin.id} #7fdde28 Read the stable appearance identity carried independently of the face it is worn on.
 * @evidence {@link Human.IAutoMovieHumanFaceSkin.basis} Read the basis identity whose UV layout the maps are painted in, which is what makes an appearance meaningless on another prior.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceSkin.basis} #d378629 Read the basis identity whose UV layout the maps are painted in, which is what makes an appearance meaningless on another prior.
 * @evidence {@link Human.IAutoMovieHumanFaceSkin.maps} Read the replacement maps keyed by resident material identity, each a complete self-describing image so no second resolution can fail after the face is built.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceSkin.maps} #c4a10c4 Read the replacement maps keyed by resident material identity, each a complete self-describing image so no second resolution can fail after the face is built.
 * @evidence {@link Human.applyHumanFaceSkin} Read the replacement against a built face: named materials gain their maps while every other field and every unnamed material is untouched, an unknown material refuses rather than silently doing nothing, and neither input is mutated.
 * @evidenceReview {@link Human.applyHumanFaceSkin} #393fb8f Read the replacement against a built face: named materials gain their maps, every unnamed material and every other coefficient is untouched, an unknown material refuses rather than silently doing nothing, and neither input is mutated. Reread after the base colour of a mapped material was neutralised: the rendered colour is the factor times the map, and the first render of the real study showed what leaving an estimated skin colour in place does, so the factor becomes white while opacity survives.
 * @evidence {@link Human.IAutoMovieHumanFaceGroom} Read the seated groom schema against the surface it names: the basis identity, the travelling finish a bald connected basis cannot supply, and the profile that carries every procedural groom control except the locks.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceGroom} #a476636 Read the seated groom schema against the surface it names: the basis identity, the travelling finish a bald connected basis cannot supply, and the profile that carries every procedural groom control except the locks. Reread with its documented members separated: identity, basis, finish, profile and the zero-to-1024 seated locks are as they were, and the finish still travels with the groom because a connected basis names no hair material.
 * @evidence {@link Human.IAutoMovieHumanFaceGroom.id} Read the stable groom identity carried independently of the face it is seated on.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceGroom.id} #99c4877 Read the stable groom identity carried independently of the face it is seated on.
 * @evidence {@link Human.IAutoMovieHumanFaceGroom.basis} Read the basis identity the seats are expressed against, which is what makes a groom meaningless on another prior.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceGroom.basis} #069b3ab Read the basis identity the seats are expressed against, which is what makes a groom meaningless on another prior.
 * @evidence {@link Human.IAutoMovieHumanFaceGroom.finish} Read why the finish travels with the groom and the refusal when its identity is already resident on the face.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceGroom.finish} #03996e6 Read why the finish travels with the groom and the refusal when its identity is already resident on the face.
 * @evidence {@link Human.IAutoMovieHumanFaceGroom.profile} Read that every authored control except the locks passes through unchanged to the shared card tessellator.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceGroom.profile} #fdb0eec Read that every authored control except the locks passes through unchanged to the shared card tessellator.
 * @evidence {@link Human.IAutoMovieHumanFaceGroom.cards} Read the bounded seated lock population and that an empty population adds no geometry rather than refusing.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceGroom.cards} #926bca7 Read the bounded seated lock population and that an empty population adds no geometry rather than refusing.
 * @evidence {@link Human.IAutoMovieHumanFaceGroomCard} Read one lock as a property of a surface rather than of a position: the named part, the triangle ordinal, the barycentric seat and the stations written in that triangle's own frame.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceGroomCard} #f1f91b8 Read one lock as a property of a surface rather than of a position: the named part, the triangle ordinal, the barycentric seat and the stations written in that triangle's own frame.
 * @evidence {@link Human.IAutoMovieHumanFaceGroomCard.part} Read the resident part identity and the refusal when this face does not carry it.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceGroomCard.part} #b0fe477 Read the resident part identity and the refusal when this face does not carry it.
 * @evidence {@link Human.IAutoMovieHumanFaceGroomCard.triangle} Read the ordinal against that part's own index buffer, the unindexed consecutive-triple reading, and the refusal for a fractional or out-of-range ordinal.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceGroomCard.triangle} #c823f4f Read the ordinal against that part's own index buffer, the unindexed consecutive-triple reading, and the refusal for a fractional or out-of-range ordinal.
 * @evidence {@link Human.IAutoMovieHumanFaceGroomCard.weights} Read the barycentric seat inside the named triangle and its evaluation against the live corner positions.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceGroomCard.weights} #233090b Read the barycentric seat inside the named triangle and its evaluation against the live corner positions.
 * @evidence {@link Human.IAutoMovieHumanFaceGroomCard.guide} Read the root-to-tip stations in seat-frame metres and their conversion into the millimetres the card tessellator reads.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceGroomCard.guide} #17e81d1 Read the root-to-tip stations in seat-frame metres and their conversion into the millimetres the card tessellator reads.
 * @evidence {@link Human.IAutoMovieHumanFaceGroomCard.across} Read that width directions ride the frame's rotation without picking up the seat's translation.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceGroomCard.across} #561a82c Read that width directions ride the frame's rotation without picking up the seat's translation.
 * @evidence {@link Human.IAutoMovieHumanFaceGroomCard.width} Read the metre root width and its conversion for the shared tessellator.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceGroomCard.width} #42875e6 Read the metre root width and its conversion for the shared tessellator.
 * @evidence {@link Human.resolveHumanFaceGroom} Read the rebuild against the live surface: the seat and frame are taken from the triangle as it stands now, so a shape or expression edit carries the hair, and every unresolvable seat refuses instead of placing a lock at a silently wrong point.
 * @evidenceReview {@link Human.resolveHumanFaceGroom} #6d3a08e Read the rebuild against the live surface: the seat is the triangle's first corner offset along its two edges by the card's weights, the frame is `[edge, cross(normal, edge), normal]` so a station's third component is its height above the skin, both are taken from the triangle as it stands now so a shape or expression edit carries the hair, and every unresolvable seat refuses instead of placing a lock at a silently wrong point. The frame's axis order is now stated rather than implied, because a measurement written from the older phrasing put the normal on the second axis and reported a median 28% of every published groom as buried inside the head.
 * @evidence {@link Human.appendHumanFaceGroom} Read the composition against a built connected face: resident parts keep their order and identity, the generated card finish joins the base finish the groom brought, and neither input is mutated.
 * @evidenceReview {@link Human.appendHumanFaceGroom} #9f51386 Read the composition against a built connected face: resident parts keep their order and identity, the generated card finish joins the base finish the groom brought, and neither input is mutated.
 * @evidence {@link Human.IAutoMovieHumanFaceChannelScale} Read the per-channel record against the basis channel order and kind it copies, so a caller can index the two lists together.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceChannelScale} #935a1d9 Read the per-channel record against the basis channel order and kind it copies, so a caller can index the two lists together.
 * @evidence {@link Human.IAutoMovieHumanFaceChannelScale.id} Read the identity copied from the measured basis channel.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceChannelScale.id} #c08a6d2 Read the identity copied from the measured basis channel.
 * @evidence {@link Human.IAutoMovieHumanFaceChannelScale.kind} Read the shape/expression discriminator copied from the channel so grouping needs no second lookup.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceChannelScale.kind} #c2659af Read the shape/expression discriminator copied from the channel so grouping needs no second lookup.
 * @evidence {@link Human.IAutoMovieHumanFaceChannelScale.positive} Read the always-present positive endpoint measurement.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceChannelScale.positive} #a04a937 Read the always-present positive endpoint measurement.
 * @evidence {@link Human.IAutoMovieHumanFaceChannelScale.negative} Read the null result for a nonnegative control, distinguished from a measured zero.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceChannelScale.negative} #8eb0125 Read the null result for a nonnegative control, distinguished from a measured zero.
 * @evidence {@link Human.IAutoMovieHumanFaceEndpointScale} Read the endpoint record's metre units and its explicit limit: a large displacement states how far geometry moves, never that the result is anatomically valid or a likeness.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceEndpointScale} #bc6ba43 Read the endpoint record's metre units and its explicit limit: a large displacement states how far geometry moves, never that the result is anatomically valid or a likeness.
 * @evidence {@link Human.IAutoMovieHumanFaceEndpointScale.displacement} Read the root mean square over every resident vertex, including untouched ones, which is what makes a wide endpoint outrank a narrow one of equal distance.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceEndpointScale.displacement} #001a8a4 Read the root mean square over every resident vertex, including untouched ones, which is what makes a wide endpoint outrank a narrow one of equal distance.
 * @evidence {@link Human.IAutoMovieHumanFaceEndpointScale.peak} Read the largest single-vertex magnitude, taken as the square root of the largest squared row.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceEndpointScale.peak} #0d7529c Read the largest single-vertex magnitude, taken as the square root of the largest squared row.
 * @evidence {@link Human.IAutoMovieHumanFaceEndpointScale.vertices} Read the count of sparse rows the endpoint carries across all surfaces.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceEndpointScale.vertices} #89f1d76 Read the count of sparse rows the endpoint carries across all surfaces.
 */
export const humanFaceConnectedReview = true;
