import type * as Human from "@automovie/human";

/**
 * Inspection of the connected-prior schema, evaluator and compact document IO.
 * Read the implementation owners and their actual worker/panel consumers.
 * The CC0 study's endpoint export and GPU observations live beside its payload;
 * this source inspection does not accept individual anatomy or photo likeness.
 *
 * @evidence requirements/actors/facial-authoring/contract.md#actor-face-connected-basis The connected study supplies a licensed neutral prior and independent compact edits to the real browser consumer.
 * @evidence specifications/asset-and-representation/facial-authoring/contract.md#face-spec-connected-basis The selected six-surface asset and worker exercise immutable basis compilation, common normals and revision-bound edits.
 * @evidence requirements/actors/facial-authoring/contract.md#actor-face-articulation The articulated revision drives the mandible and globes from expression channels over source joint-cube landmarks and measured attachment weights, with the fits and retired rows recorded in its receipt.
 * @evidence specifications/asset-and-representation/facial-authoring/contract.md#face-spec-articulation The prepared basis carries landmarks, articulation and sparse attachments, and the real worker evaluates rest layer, landmarks, joint motion and attachment posing in the specified order.
 * @evidence requirements/actors/facial-authoring/contract.md#actor-face-contact The contact revision scales lip closure to the aperture it closes, refuses a tongue through closed teeth or sealed lips by name, and holds lining and lips outside the dental colliders within cited tissue budgets.
 * @evidence specifications/asset-and-representation/facial-authoring/contract.md#face-spec-contact The prepared basis publishes the vermilion and incisal vertex pairs, the closure channel decomposed at the reference opening, the passage slab, the sealed crown colliders with their reach and the soft budgets the builder evaluates in order.
 * @evidence {@link Human.IAutoMovieHumanFaceControlMap} Read the basis-bound coordinate map and its disjoint shape membership; labels describe authored effects rather than measured age or anatomy.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceControlMap} #0c4334f Read the complete map declaration against compilation and the Simple/Fine consumer. Only fine weights enter documents and geometry; the map stores no person-specific displacement.
 * @evidence {@link Human.IAutoMovieHumanFaceControlMap.basis} Read exact basis matching before compiling any group.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceControlMap.basis} #f5049fe The map's exact identity is checked against the supplied basis; no inferred migration is accepted.
 * @evidence {@link Human.IAutoMovieHumanFaceControlMap.groups} Read distinct group identities and disjoint shape members against projection, labels and descriptions.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceControlMap.groups} #5e6f21b Read blank metadata, empty membership, unknown or expression members and duplicate membership refusals. Unlisted fine coordinates survive resolution.
 * @evidence {@link Human.createHumanFaceControlMap} Read signed endpoint normalization, mean/residual projection, feasible intervals and origin-based resolution against independent unequal-unit examples and the panel consumer.
 * @evidenceReview {@link Human.createHumanFaceControlMap} #1cbca1c Reread normalization, mean/residual projection, domain intersection and origin-based resolution with the unequal-unit, refusal and boundary scenarios. The three-member endpoint case reproduced an origin outside its own displayed interval due to subtraction rounding. The interval now explicitly contains that already admitted origin; outward edits still refuse and no-op restores exact omitted fields. Map ownership protects prototype-named coordinates and repeated replay from caller mutation. This is numerical authoring, not anatomical or demographic calibration.
 * @evidence {@link Human.IAutoMovieHumanFaceBasis} Read the schema and admission against the selected CC0 asset, including sparse endpoints, shared topology, complete material partitions and owned compilation.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasis} #f9d1bbd Reread the complete schema with the articulated members: optional landmarks (source joint cubes with sparse shape rows), an optional articulation (one mandible with a condylar axis point, coupled opening translation, protrusion, laterotrusion and a sagittal budget; globes with authored gaze axes, degrees and the eccentric translation each gaze carries) and per-surface sparse attachments in place of the retired post-hoc rigid groups. Endpoints, hair domains, closure and material partitions keep their meaning. The schema names the joints; it proves no clinical trajectory. Reread with the optional contact block: aperture vertex pairs, closure coupling, passage, sealed colliders with reach, soft budgets and tolerance.
 * @evidence {@link Human.IAutoMovieHumanFaceBasis.id} Read nonblank identity admission and the builder's exact document-to-basis binding.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasis.id} #5362f20 Read nonblank identity admission and the builder's exact document-to-basis binding.
 * @evidence {@link Human.IAutoMovieHumanFaceBasis.channels} Read finite neutral-containing ranges, distinct signed endpoint selection, ordered accumulation and fixed surfaces when an endpoint is absent locally.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasis.channels} #24ac425 Reread the ordered channel declaration, finite neutral-containing envelopes, signed endpoint selection and local zero-field omission. Optional nonempty descriptions travel with the shared basis and render as literal text beside measured endpoint scales. They neither change weight evaluation nor add per-document fields.
 * @evidence {@link Human.IAutoMovieHumanFaceBasis.surfaces} Read topology admission, sparse vertex ordering, nonzero differences, oriented triangle partition and common-normal construction before UV separation.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasis.surfaces} #2783db9 Read source positions, sparse endpoints, growth-domain metadata, optional closure, material partitions and the sparse `[vertex, weight]` attachments that replace rigid membership. Attachments name only declared owners, weights lie in (0,1] and sum to at most one per vertex; the cranium is the complement. Admission checks structure, not the anatomy of a weight.
 * @evidence {@link Human.IAutoMovieHumanFaceBasis.materials} Read unique resident identities, copied overrides and final model/export material admission.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasis.materials} #20d5ec5 Read unique resident identities, copied overrides and final model/export material admission.
 * @evidence {@link Human.IAutoMovieHumanFaceBasisDocument} Read exact compact schema admission and independent shape, performance and appearance ownership against the generic transaction consumer.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasisDocument} #fe34839 Reread the complete compact schema, shared admission and worker. Hair now carries numerical layers and old resource strings refuse; pigmentation retains centre/radius/gain fields. The builder generates both from the same document. The published 18 inputs still require migration and current-population visual verification, so this source inspection does not declare the face editor complete.
 * @evidence {@link Human.IAutoMovieHumanFaceBasisDocument.id} Read nonblank identity admission and preservation into the resident model and downloaded filename.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasisDocument.id} #d5d2223 Read nonblank identity admission and preservation into the resident model and downloaded filename.
 * @evidence {@link Human.IAutoMovieHumanFaceBasisDocument.name} Read nonblank display identity admission and preservation into model and editor status.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasisDocument.name} #44def0f Read nonblank display identity admission and preservation into model and editor status.
 * @evidence {@link Human.IAutoMovieHumanFaceBasisDocument.basis} Read exact compiled-basis matching without implicit conversion or external URL resolution.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasisDocument.basis} #47fd14e Read exact compiled-basis matching without implicit conversion or external URL resolution.
 * @evidence {@link Human.IAutoMovieHumanFaceBasisDocument.shape} Read explicit shape-group validation, neutral omission and signed endpoint weights without clamping.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasisDocument.shape} #0c878d7 Read explicit shape-group validation, neutral omission and signed endpoint weights without clamping.
 * @evidence {@link Human.IAutoMovieHumanFaceBasisDocument.expression} Read expression-group validation and independent transient state; the source endpoint model does not guarantee physiological interpolation.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasisDocument.expression} #5422939 Read expression-group validation and independent transient state; the source endpoint model does not guarantee physiological interpolation.
 * @evidence {@link Human.IAutoMovieHumanFaceBasisDocument.materials} Read resident-ID validation, optional RGB/roughness boundaries, material copying and preservation of resident texture bytes.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasisDocument.materials} #28eb2fc Read resident-ID validation, optional RGB/roughness boundaries, material copying and preservation of resident texture bytes.
 * @evidence {@link Human.createHumanFaceBasisRegion} Read source/UV identity compilation and owned position/normal gathers against hand-permuted seam, null UV and empty examples.
 * @evidenceReview {@link Human.createHumanFaceBasisRegion} #c7d6a75 Reread source/UV identity compilation and all optional-colour gathers. The same source index gathers positions, normals and reference RGB into owned arrays. The square seam and shape/expression scenarios verify unchanged geometry and shared colour; no nearest-point transfer occurs.
 * @evidence {@link Human.createHumanFaceBasisBuilder} Read schema admission, immutable compilation, range checks, ordered signed sparse sums, common normal reconstruction, UV/material separation and final model validation. The actual worker consumes the builder and the existing exporter emits its result.
 * @evidenceReview {@link Human.createHumanFaceBasisBuilder} #c438239 Reread the reference rest layer evaluated with the reference channel alone for the aperture ratio, the fixed order: weights and activations, the rest layer on surfaces and landmarks, the articulation read off the shaped landmarks, sparse attachment posing, then common normals and regions; hair composes on the posed positions as before. A basis without articulation poses nothing and is the linear prior. The post-hoc rigid fit is gone; rigidity now follows from unit attachment. Neither step measures contact. Reread the contact order: rest without the closure channel, apertures from the posed pairs, closure rows scaled by weight and ratio, posing, passage, floor resolution, the lip seam reread after closure for passage and the summary, and the observe callback fed the summary or null. Reread the scalp tint gains multiplied into the resident surface's vertex colours under a hair document, after pigmentation and material overrides.
 * @evidence {@link Human.IAutoMovieHumanFaceBasis.landmarks} Read the joint-cube landmarks, their neutral XYZ and sparse shape rows, and that an expression carries no landmark row.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasis.landmarks} #7931f79 Read unique names, aligned finite positions and rows on declared endpoints only; the rest layer moves them by the same channel order as the surfaces, which is what makes a joint follow identity.
 * @evidence {@link Human.IAutoMovieHumanFaceBasis.articulation} Read the mandible (pivot landmark plus condylar offset, unit axis, opening degrees with coupled translation, protrusion, laterotrusion, translation limit) and the globes (centre landmark, gaze axes and degrees).
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasis.articulation} #6899c0a Read that every driving channel is one expression channel driving one joint, the limit admits the authored full opening, and each gaze entry names a unit axis, a nonzero angle and a finite translation. The values are measured from the source at preparation and cited there.
 * @evidence {@link Human.IAutoMovieHumanFaceRigidMotion} Read the pivot-relative rotation plus translation form every attached vertex receives.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceRigidMotion} #626925c Read `x' = R (x - pivot) + pivot + translation`; the pivot is the shaped landmark so a rotation turns about the joint.
 * @evidence {@link Human.assertHumanFaceArticulation} Read structural admission of landmarks, articulation and attachments after channels, correctives and surfaces.
 * @evidenceReview {@link Human.assertHumanFaceArticulation} #281185c Reread every refusal: landmark names, alignment, declared-endpoint rows; pivot and centre existence, unit axes, positive opening, limit against the authored opening, one expression channel per joint, nonzero gaze with a finite translation; attachment owners, ordering, weight range, per-vertex sum and the no-articulation rule. The admission unit scenarios exercise each branch on the analytic fixture.
 * @evidence {@link Human.humanFaceBasisWeights} Read the document-to-state boundary: envelope-checked weights and product corrective activations with the shape-only flag.
 * @evidenceReview {@link Human.humanFaceBasisWeights} #cec7867 Read the refusals (unknown channel, wrong kind, nonfinite, out of envelope) and the tent in-between factor lifted out of the builder unchanged; the rest scenario pins a quarter activation at two half drivers and the shape-only flag.
 * @evidence {@link Human.evaluateHumanFaceRest} Read the rest layer on surfaces and landmarks by endpoint name in channel order, then correctives.
 * @evidenceReview {@link Human.evaluateHumanFaceRest} #2ba7171 Read fresh copies, channel order, signed endpoint selection and that a landmark row moves only under its own endpoint; a basis without landmarks yields an empty record. Reread the `except` set that skips a channel's rows while its correctives still activate.
 * @evidence {@link Human.resolveHumanFaceArticulation} Read the jaw motion (angle and coupled translation from the opening weight, protrusion and laterotrusion added, the sagittal budget refusal) and each eye's composed gaze about its centre.
 * @evidenceReview {@link Human.resolveHumanFaceArticulation} #2bee18a Reread the budget check against the summed opening and protrusion translation with the figures in the refusal, the pivot taken from the shaped landmark plus offset, and gaze rotations composed in list order about the shaped centre with their eccentric translations summed. Blinks do not enter; no lid weight exists.
 * @evidence {@link Human.summarizeHumanFaceArticulation} Read the preview summary: opening degrees, mandibular translation against the budget, the shaped pivot and each eye's gaze angle, null without articulation.
 * @evidenceReview {@link Human.summarizeHumanFaceArticulation} #1f4c80d Read that it resolves through the same weights, rest layer and resolution the builder poses with, so the budget refusal is raised by name before geometry, and that a basis without articulation summarizes to null.
 * @evidence {@link Human.IAutoMovieHumanFaceBasis.contact} Read the aperture vertex pairs, closure coupling, passage, colliders with closure and reach, soft budgets and tolerance.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceBasis.contact} #bdb2cd7 Read that lips and incisors are vertex pairs of one surface, closure names a channel and its reference, passage names the tongue and its channel with a slab, colliders carry closure triangles and a reach, soft surfaces carry budgets, and a tolerance absorbs rounding.
 * @evidence {@link Human.IAutoMovieHumanFaceContactSummary} Read the apertures, closure ratio, passage measure and per-surface resolution counts a build reports.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceContactSummary} #004e82e Read the five members against the builder's assembly and the closure, passage and resolution scenarios that pin each one.
 * @evidence {@link Human.IAutoMovieHumanFaceContactSummary.interlabialMetres} Read the signed lip aperture along the opening direction.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceContactSummary.interlabialMetres} #35177e2 Read the signed projection; the closure scenario pins 0.1 at rest and 1.45 open.
 * @evidence {@link Human.IAutoMovieHumanFaceContactSummary.interincisalMetres} Read the signed incisal aperture along the opening direction.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceContactSummary.interincisalMetres} #bd1fc12 Read the signed projection; the closure scenario pins 0.2 at rest and 1.1 open.
 * @evidence {@link Human.IAutoMovieHumanFaceContactSummary.closureRatio} Read the nonnegative ratio the closure rows were scaled by.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceContactSummary.closureRatio} #cbe1f72 Read the clamp at zero; the closure scenario pins 0 closed, 1 at the reference and the measured fraction at half.
 * @evidence {@link Human.IAutoMovieHumanFaceContactSummary.passage} Read the tongue's protrusion and slab thickness, or null behind the plane.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceContactSummary.passage} #09911a1 Read null behind the plane and the two figures past it; the passage scenario pins 0.5 and 0.3.
 * @evidence {@link Human.IAutoMovieHumanFaceContactSummary.resolved} Read per soft surface the vertices returned to their floor and the deepest excess.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceContactSummary.resolved} #9048af8 Read one entry per soft surface in declaration order; the resolution scenario pins one vertex at the face-normal depth and zero on the tongue.
 * @evidence {@link Human.assertHumanFaceContact} Read the admission of names, vertex pairs, channels, colliders, soft budgets and the sealed collider's sheet query.
 * @evidenceReview {@link Human.assertHumanFaceContact} #a65b6ab Read every refusal message against the admission scenario's variants, the articulation prerequisite and the sheet query run on the neutral collider.
 * @evidence {@link Human.measureHumanFaceAperture} Read the opening frame from the lower incisor's reference drop, the posed vertex pairs and the closure ratio.
 * @evidenceReview {@link Human.measureHumanFaceAperture} #216d63b Read that only the four vertices are posed, that the reference aperture comes from the reference channel's own rest layer with its residual rows, up is the basis vertical made perpendicular to the mandibular axis, forward is axis cross up, gaps are signed projections, the ratio subtracts the shape-only rest aperture, and the refusals name a vertical axis and lips the reference does not part.
 * @evidence {@link Human.evaluateHumanFacePassage} Read the incisal plane, protrusion, slab thickness and the refusal against both apertures.
 * @evidenceReview {@link Human.evaluateHumanFacePassage} #c6a2f6b Read that the plane passes through the posed lower incisal edge so a sliding jaw protrudes nothing, that a tongue behind it returns null, that thickness is the slab's extent along up, and that the refusal names the protrusion channel, the short gap, the measured and needed millimetres.
 * @evidence {@link Human.resolveHumanFaceContact} Read the rest floor rule over sheet colliders within reach and the budget refusal.
 * @evidenceReview {@link Human.resolveHumanFaceContact} #d862ba3 Read the posed and rest compilations, the seam copies grouped by exact position and moved together, the floor `min(d0, 0)`, the rim skip at rest and posed, the excess against tolerance, the push along the nearest normal, the budget refusal by surface, vertex and depth, and the half push spread to one ring.
 * @evidence {@link Human.poseHumanFaceSurface} Read the sparse linear blend: each attached vertex moves by the weighted sum of its owners' rigid displacements.
 * @evidenceReview {@link Human.poseHumanFaceSurface} #037f9fa Read `p + sum w (M(p) - p)`, the throw for an owner without motion, and fresh output; the blend scenario pins a half-attached vertex at the midpoint and a unit vertex on the rigid image.
 * @evidence {@link Human.unposeHumanFaceSurface} Read the exact per-vertex affine inverse the preparation carries source poses through.
 * @evidenceReview {@link Human.unposeHumanFaceSurface} #7dac858 Read the accumulated `L` and `c` per vertex, Cramer's rule, the singular-blend refusal and unattached vertices passing through; the blend scenario round-trips a posed square.
 * @evidence {@link Human.parseHumanFaceBasisDocument} Read the shared UTF-16 text budget, JSON and exact-schema admission, finite numbers and nonblank identities. Basis-specific channel validation remains with the compiled builder.
 * @evidenceReview {@link Human.parseHumanFaceBasisDocument} #04edd49 Read the shared UTF-16 text budget, JSON and exact-schema admission, finite numbers and nonblank identities. Basis-specific channel validation remains with the compiled builder.
 * @evidence {@link Human.serializeHumanFaceBasisDocument} Read finite admission before JSON serialization and the shared size check after escaping and formatting, so a successful save fits the loader envelope; geometry remains separately versioned.
 * @evidenceReview {@link Human.serializeHumanFaceBasisDocument} #9d35caa Read finite admission before JSON serialization and the shared size check after escaping and formatting, so a successful save fits the loader envelope; geometry remains separately versioned.
 * @evidence {@link Human.measureHumanFaceBasisChannels} Read the whole-basis accumulation: every surface's sparse rows for one endpoint are summed before dividing by the shared resident vertex count, the empty-population refusal that keeps NaN out of a published measurement, and that an absent endpoint measures zero because admission already refuses that basis. The connected panel prints its result and the whole-face study fit prices shape weights with the same figures.
 * @evidenceReview {@link Human.measureHumanFaceBasisChannels} #2b64c3f Reread the whole-basis accumulation and its two lanes: an ordinary endpoint sums its sparse rows over every surface before dividing by the shared resident vertex count; a channel that drives a joint is posed through the same attachment blend the builder runs, at weight one on the neutral landmarks, and measured vertex by vertex against the neutral, so the printed millimetres are the render's rather than the residual's. The empty-population refusal and the absent-endpoint zero are unchanged. The connected panel prints the result and the articulated scale scenario pins the posed figures by hand.
 * @evidence {@link Human.IAutoMovieHumanFaceGroom} Read the seated groom schema against the surface it names: the basis identity, the travelling finish a bald connected basis cannot supply, and the profile that carries every procedural groom control except the locks.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceGroom} #a476636 Read the seated groom schema against the surface it names: the basis identity, the travelling finish a bald connected basis cannot supply, and the profile that carries every procedural groom control except the locks. Reread with its documented members separated: identity, basis, finish, profile and the zero-to-1024 seated locks are as they were, and the finish still travels with the groom because a connected basis names no hair material.
 * @evidence {@link Human.IAutoMovieHumanFaceGroom.id} Read the stable groom identity carried independently of the face it is seated on.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceGroom.id} #99c4877 Read the stable groom identity carried independently of the face it is seated on.
 * @evidence {@link Human.IAutoMovieHumanFaceGroom.basis} Read the basis identity the seats are expressed against, which is what makes a groom meaningless on another prior.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceGroom.basis} #069b3ab Read the basis identity the seats are expressed against, which is what makes a groom meaningless on another prior.
 * @evidence {@link Human.IAutoMovieHumanFaceGroom.finish} Read why the finish travels with the groom and the refusal when its identity is already resident on the face.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceGroom.finish} #03996e6 Read why the finish travels with the groom and the refusal when its identity is already resident on the face.
 * @evidence {@link Human.IAutoMovieHumanFaceGroom.profile} Read that every authored control except the locks passes through unchanged to the shared card tessellator.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceGroom.profile} #fdb0eec Read that every authored control except the locks passes through unchanged to the shared card tessellator.
 * @evidence {@link Human.IAutoMovieHumanFaceGroom.cards} Read the bounded seated lock population and that an empty population adds no geometry rather than refusing.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceGroom.cards} #926bca7 Read the bounded seated lock population and that an empty population adds no geometry rather than refusing.
 * @evidence {@link Human.IAutoMovieHumanFaceGroomCard} Read one lock as a property of a surface rather than of a position: the named part, the triangle ordinal, the barycentric seat and the stations written in that triangle's own frame.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceGroomCard} #f1f91b8 Read one lock as a property of a surface rather than of a position: the named part, the triangle ordinal, the barycentric seat and the stations written in that triangle's own frame.
 * @evidence {@link Human.IAutoMovieHumanFaceGroomCard.part} Read the resident part identity and the refusal when this face does not carry it.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceGroomCard.part} #b0fe477 Read the resident part identity and the refusal when this face does not carry it.
 * @evidence {@link Human.IAutoMovieHumanFaceGroomCard.triangle} Read the ordinal against that part's own index buffer, the unindexed consecutive-triple reading, and the refusal for a fractional or out-of-range ordinal.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceGroomCard.triangle} #c823f4f Read the ordinal against that part's own index buffer, the unindexed consecutive-triple reading, and the refusal for a fractional or out-of-range ordinal.
 * @evidence {@link Human.IAutoMovieHumanFaceGroomCard.weights} Read the barycentric seat inside the named triangle and its evaluation against the live corner positions.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceGroomCard.weights} #233090b Read the barycentric seat inside the named triangle and its evaluation against the live corner positions.
 * @evidence {@link Human.IAutoMovieHumanFaceGroomCard.guide} Read the root-to-tip stations in seat-frame metres and their conversion into the millimetres the card tessellator reads.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceGroomCard.guide} #17e81d1 Read the root-to-tip stations in seat-frame metres and their conversion into the millimetres the card tessellator reads.
 * @evidence {@link Human.IAutoMovieHumanFaceGroomCard.across} Read that width directions ride the frame's rotation without picking up the seat's translation.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceGroomCard.across} #561a82c Read that width directions ride the frame's rotation without picking up the seat's translation.
 * @evidence {@link Human.IAutoMovieHumanFaceGroomCard.width} Read the metre root width and its conversion for the shared tessellator.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceGroomCard.width} #42875e6 Read the metre root width and its conversion for the shared tessellator.
 * @evidence {@link Human.resolveHumanFaceGroom} Read the rebuild against the live surface: the seat and frame are taken from the triangle as it stands now, so a shape or expression edit carries the hair, and every unresolvable seat refuses instead of placing a lock at a silently wrong point.
 * @evidenceReview {@link Human.resolveHumanFaceGroom} #6d3a08e Read the rebuild against the live surface: the seat is the triangle's first corner offset along its two edges by the card's weights, the frame is `[edge, cross(normal, edge), normal]` so a station's third component is its height above the skin, both are taken from the triangle as it stands now so a shape or expression edit carries the hair, and every unresolvable seat refuses instead of placing a lock at a silently wrong point. The frame's axis order is now stated rather than implied, because a measurement written from the older phrasing put the normal on the second axis and reported a median 28% of every published groom as buried inside the head.
 * @evidence {@link Human.appendHumanFaceGroom} Read the composition against a built connected face: resident parts keep their order and identity, the generated card finish joins the base finish the groom brought, and neither input is mutated.
 * @evidenceReview {@link Human.appendHumanFaceGroom} #9f51386 Read the composition against a built connected face: resident parts keep their order and identity, the generated card finish joins the base finish the groom brought, and neither input is mutated.
 * @evidence {@link Human.IAutoMovieHumanFaceChannelScale} Read the per-channel record against the basis channel order and kind it copies, so a caller can index the two lists together.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceChannelScale} #935a1d9 Read the per-channel record against the basis channel order and kind it copies, so a caller can index the two lists together.
 * @evidence {@link Human.IAutoMovieHumanFaceChannelScale.id} Read the identity copied from the measured basis channel.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceChannelScale.id} #c08a6d2 Read the identity copied from the measured basis channel.
 * @evidence {@link Human.IAutoMovieHumanFaceChannelScale.kind} Read the shape/expression discriminator copied from the channel so grouping needs no second lookup.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceChannelScale.kind} #c2659af Read the shape/expression discriminator copied from the channel so grouping needs no second lookup.
 * @evidence {@link Human.IAutoMovieHumanFaceChannelScale.positive} Read the always-present positive endpoint measurement.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceChannelScale.positive} #a04a937 Read the always-present positive endpoint measurement.
 * @evidence {@link Human.IAutoMovieHumanFaceChannelScale.negative} Read the null result for a nonnegative control, distinguished from a measured zero.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceChannelScale.negative} #8eb0125 Read the null result for a nonnegative control, distinguished from a measured zero.
 * @evidence {@link Human.IAutoMovieHumanFaceEndpointScale} Read the endpoint record's metre units and its explicit limit: a large displacement states how far geometry moves, never that the result is anatomically valid or a likeness.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceEndpointScale} #bc6ba43 Read the endpoint record's metre units and its explicit limit: a large displacement states how far geometry moves, never that the result is anatomically valid or a likeness.
 * @evidence {@link Human.IAutoMovieHumanFaceEndpointScale.displacement} Read the root mean square over every resident vertex, including untouched ones, which is what makes a wide endpoint outrank a narrow one of equal distance.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceEndpointScale.displacement} #001a8a4 Read the root mean square over every resident vertex, including untouched ones, which is what makes a wide endpoint outrank a narrow one of equal distance.
 * @evidence {@link Human.IAutoMovieHumanFaceEndpointScale.peak} Read the largest single-vertex magnitude, taken as the square root of the largest squared row.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceEndpointScale.peak} #0d7529c Read the largest single-vertex magnitude, taken as the square root of the largest squared row.
 * @evidence {@link Human.IAutoMovieHumanFaceEndpointScale.vertices} Read the count of sparse rows the endpoint carries across all surfaces.
 * @evidenceReview {@link Human.IAutoMovieHumanFaceEndpointScale.vertices} #89f1d76 Read the count of sparse rows the endpoint carries across all surfaces.
 */
export const humanFaceConnectedReview = true;
