import type {
  IAutoMovieHumanFaceHair,
  assertHumanFaceHair,
  buildHumanFaceHairMesh,
  createHumanFaceHairBuilder,
  createHumanFaceHairGatherField,
  createHumanFaceHairRoots,
  createHumanFaceHairTailSpread,
  createHumanFaceScalpTint,
  evaluateHumanFaceHairDirection,
  growHumanFaceHairStrand,
  humanFaceHairContact,
  humanFaceHairDensity,
  humanFaceHairEmergence,
  humanFaceHairFrame,
  humanFaceHairLength,
  humanFaceHairSequence,
  humanFaceHairlineBoundary,
  humanFaceHairlineCoverage,
  integrateHumanFaceHairCurve,
  interpolateHumanFaceHairStrands,
  resolveHumanFaceHairGatherAnchor,
} from "@automovie/human";

/**
 * Numerical scalp-hair source inspection for the shared 18-document study.
 * The documents were migrated and GPU-reviewed, but source observations do not
 * accept photographic likeness or arbitrary parameter combinations. Source
 * fingerprints are obtained only after inspection.
 *
 * @evidence {@link IAutoMovieHumanFaceHair} Read the numerical layer document and its admission. Generated station arrays, photos and personal resource keys have no field in this schema.
 * @evidenceReview {@link IAutoMovieHumanFaceHair} #a10ddd4 Read the complete numerical document after adding a six-coefficient root envelope. The same canonical layers still contain no generated coordinates, photographs or private resource keys; the 18 published documents now use numerical layers. Reread with layers that may declare a guide hierarchy. Reread with no authored ribbon width in the document.
 * @evidence {@link IAutoMovieHumanFaceHair.layers} Read the eight-layer admission and empty-list behavior. The limit bounds construction cost, not biological hair populations.
 * @evidenceReview {@link IAutoMovieHumanFaceHair.layers} #5d32414 Read the eight-layer admission and empty-list behavior. The limit bounds construction cost, not biological hair populations.
 * @evidence {@link IAutoMovieHumanFaceHair.Layer} Read every root, length, direction, sampling and finish field beside the compiled builder. Coordinates use neutral head metres; physical rod dynamics and follicle density are not claimed.
 * @evidenceReview {@link IAutoMovieHumanFaceHair.Layer} #487684a Read rootRegion beside area sampling, independent part.region, per-layer fields and editor transactions. Local root preference preserves the requested count and is explicitly not biological density. Reread with the optional `guides` hierarchy (a fraction of roots integrated as guides, the rest interpolated from one to eight neighbours). Reread the optional clump inside the guide hierarchy. Reread with `width` removed: a ribbon stands for the scalp its root is responsible for, thinner hair is a smaller count or a lower finish coverage, and `clearance` is the fibre path's. Reread the optional gather block: a shared polar scalp tie, all-root integration, a tail axis and optional disk-filled radius/reach, with no saved strand coordinates.
 * @evidence {@link IAutoMovieHumanFaceHair.Layer.gather} Read the polar scalp tie, its radius and strength, and the axial tail with optional numeric cross-section radius/reach. No personal curve is stored.
 * @evidenceReview {@link IAutoMovieHumanFaceHair.Layer.gather} #3cb52da Reread the two neutral polar coordinates, current barycentric attachment, positive tie radius and strength, the finite tail direction and optional nonnegative tube radius with positive reach. A gathered layer integrates every root; the complete numerical document contains no personal guide.
 * @evidence {@link IAutoMovieHumanFaceHair.Layer.id} Read nonblank/unique admission and generated part/material naming. No person-dependent dispatch uses this name.
 * @evidenceReview {@link IAutoMovieHumanFaceHair.Layer.id} #994b721 Read nonblank/unique admission and generated part/material naming. No person-dependent dispatch uses this name.
 * @evidence {@link IAutoMovieHumanFaceHair.Layer.surface} Read exact lookup against shared source surfaces and current complete position buffers.
 * @evidenceReview {@link IAutoMovieHumanFaceHair.Layer.surface} #743f9bd Read exact lookup against shared source surfaces and current complete position buffers.
 * @evidence {@link IAutoMovieHumanFaceHair.Layer.domain} Read exact lookup of an anatomical triangle subset belonging to the selected shared surface. It cannot name a private groom.
 * @evidenceReview {@link IAutoMovieHumanFaceHair.Layer.domain} #7826069 Read exact lookup of an anatomical triangle subset belonging to the selected shared surface. It cannot name a private groom.
 * @evidence {@link IAutoMovieHumanFaceHair.Layer.count} Read inclusive integer 0..1024 admission, empty construction and retained-prefix area sampling. This is strip count, not biological density.
 * @evidenceReview {@link IAutoMovieHumanFaceHair.Layer.count} #ab4c708 Read inclusive integer 0..1024 admission, empty construction and retained-prefix area sampling. This is strip count, not biological density.
 * @evidence {@link IAutoMovieHumanFaceHair.Layer.seed} Read unsigned integer admission and retained candidate sequence offsets. Rejected candidates do not renumber surviving phase or variation.
 * @evidenceReview {@link IAutoMovieHumanFaceHair.Layer.seed} #fcf8bd8 Read unsigned integer admission and retained candidate sequence offsets. Rejected candidates do not renumber surviving phase or variation.
 * @evidence {@link IAutoMovieHumanFaceHair.Layer.hairline} Read the four polar boundaries, squared azimuth blending and rejection-only mask over the shared domain. This does not classify scalp anatomy from a photograph.
 * @evidenceReview {@link IAutoMovieHumanFaceHair.Layer.hairline} #c32e2eb Read the four polar boundaries, squared azimuth blending and rejection-only mask over the shared domain. This does not classify scalp anatomy from a photograph.
 * @evidence {@link IAutoMovieHumanFaceHair.Layer.lengthAxes} Read six positive metric values blended by absolute neutral radial components. Emergence belongs to the resulting centreline length; the axes are a field, not measured landmarks.
 * @evidenceReview {@link IAutoMovieHumanFaceHair.Layer.lengthAxes} #1546c2e Read six positive metric values blended by absolute neutral radial components. Emergence belongs to the resulting centreline length; the axes are a field, not measured landmarks.
 * @evidence {@link IAutoMovieHumanFaceHair.Layer.lengthVariation} Read deterministic base-seven fractional modulation and the worst-case interval admission. It stores amplitude, never per-root offsets.
 * @evidenceReview {@link IAutoMovieHumanFaceHair.Layer.lengthVariation} #e758db3 Read deterministic base-seven fractional modulation and the worst-case interval admission. It stores amplitude, never per-root offsets.
 * @evidence {@link IAutoMovieHumanFaceHair.Layer.samplingStep} Read the metric chord bound, curl sampling comparison and aggregate interval budget. This is numerical resolution, not a saved guide count.
 * @evidenceReview {@link IAutoMovieHumanFaceHair.Layer.samplingStep} #2d622f2 Read the metric chord bound, curl sampling comparison and aggregate interval budget. This is numerical resolution, not a saved guide count.
 * @evidence {@link IAutoMovieHumanFaceHair.Layer.clearance} Read its nonnegative addition to the free-strip contact margin. The root fan is explicitly outside that distance proof.
 * @evidenceReview {@link IAutoMovieHumanFaceHair.Layer.clearance} #8b1de0d Read its nonnegative addition to the free-strip contact margin. The root fan is explicitly outside that distance proof. Reread as the fibre path's clearance rather than the ribbon's; the ribbon's corners are kept out by the mesh owner instead.
 * @evidence {@link IAutoMovieHumanFaceHair.Layer.flow} Read finite nonzero admission and inward-component removal before lift/curl. Cancellation refuses instead of introducing a random replacement direction.
 * @evidenceReview {@link IAutoMovieHumanFaceHair.Layer.flow} #09d39b5 Read finite nonzero admission and inward-component removal before lift/curl. Cancellation refuses instead of introducing a random replacement direction.
 * @evidence {@link IAutoMovieHumanFaceHair.Layer.lift} Read nonnegative direction bias and exponential decay with positive metric reach. It is static styling, not measured material stiffness.
 * @evidenceReview {@link IAutoMovieHumanFaceHair.Layer.lift} #65383f5 Read nonnegative direction bias and exponential decay with positive metric reach. It is static styling, not measured material stiffness.
 * @evidence {@link IAutoMovieHumanFaceHair.Layer.part} Read normalized plane coordinates, tanh transition, tangent projection, optional Gaussian root envelope and arc-length decay. The envelope does not store per-root guides.
 * @evidenceReview {@link IAutoMovieHumanFaceHair.Layer.part} #3425558 Read the shared Region type and the same Gaussian arithmetic in parting. Root sampling and parting have independent values; extracting the formula preserves the previous directional calculation.
 * @evidence {@link IAutoMovieHumanFaceHair.Layer.curl} Read wave/helix branches, angular modulation and eight-interval wavelength admission. Contact may modify the desired curl and no stress-free rod solution is claimed.
 * @evidenceReview {@link IAutoMovieHumanFaceHair.Layer.curl} #af8e7f9 Read wave/helix branches, angular modulation and eight-interval wavelength admission. Contact may modify the desired curl and no stress-free rod solution is claimed.
 * @evidence {@link IAutoMovieHumanFaceHair.Layer.taper} Read the tip ratio and start fraction applied to measured arc-length UV. Generated strips do not receive a second curve fit.
 * @evidenceReview {@link IAutoMovieHumanFaceHair.Layer.taper} #b3959ea Read the tip ratio and start fraction applied to measured arc-length UV. Generated strips do not receive a second curve fit.
 * @evidence {@link IAutoMovieHumanFaceHair.Layer.finish} Read linear RGB, roughness and procedural fibre texture inputs. The common PNG formula produces derived pixels without personal bitmap authoring.
 * @evidenceReview {@link IAutoMovieHumanFaceHair.Layer.finish} #88e19fd Read linear RGB, roughness and procedural fibre texture inputs. The common PNG formula produces derived pixels without personal bitmap authoring.
 * @evidence {@link assertHumanFaceHair} Read structural equality, finite/range checks, optional fields, unique identities and joint allocation refusal. Domain/contact feasibility is deferred to the compiled builder, including empty-layer domain lookup.
 * @evidenceReview {@link assertHumanFaceHair} #f7e988c Read structural admission and both optional envelope paths. Finite centres and strictly positive finite spreads are required even at zero count; source-domain lookup and feasibility remain builder obligations. Reread the guide admission: fraction in (0,1], integral neighbours in [1,8]. Reread the optional clump admitted in [0,1]. Reread the admission without a width field; count, step, clearance and the interval budget are unchanged. Reread the optional greying proportion admitted in [0,1]. Reread polar and azimuth bounds, positive tie radius/strength, nonzero tail direction, optional tube radius/reach, and the explicit refusal of a partial guide hierarchy under gathering.
 * @evidence {@link createHumanFaceHairRoots} Read owned neutral triangle points, area CDF, square-root barycentric coordinates, polar rejection and preserved sequence identities. Sampling exhaustion is a refusal, not an anatomical result.
 * @evidenceReview {@link createHumanFaceHairRoots} #697f900 Read neutral area sampling followed by polar and base-13 Gaussian rejection. Sequence identities and barycentric seats are retained, omitted regions admit every candidate, and exhausted local populations explicitly refuse. Reread the hairline boundary now read through `humanFaceHairlineBoundary`, unchanged. Reread the area the sampler reports: candidates are uniform over the domain, so the share the masks admit times the domain area is the area the population grows on. Reread the acceptance share the sampler now reports, of the neutral domain rather than an area, so the caller takes it on the current shape.  * @evidence {@link humanFaceHairDensity} Read the ribbon width taken from the population's own local density: the k-nearest-neighbour estimator over the seated roots, the side of the scalp area one root is responsible for, and the measured-area fallback for a population too small to have neighbours.
 * @evidence {@link humanFaceHairDensity} Read the ribbon width taken from the population's own local density: the k-nearest-neighbour estimator over the seated roots, the side of the scalp area one root is responsible for, and the measured-area fallback for a population too small to have neighbours.
 * @evidenceReview {@link humanFaceHairDensity} #0dd7094 Read the four-neighbour estimator, its unbiased (k-1) divisor and the fallback to the sampler's own accepted area; widths are the current shape's, so identity widens them. This states coverage only: the fibre's diameter is not claimed and keeping a ribbon outside the skin belongs to the mesh owner.
 * @evidence {@link humanFaceHairSequence} Read the radical-inverse loop and its admitted caller indices. Prime bases select repeatable coordinates with no global random state.
 * @evidenceReview {@link humanFaceHairSequence} #7f7fc99 Read the radical-inverse loop and its admitted caller indices. Prime bases select repeatable coordinates with no global random state.
 * @evidence {@link humanFaceHairFrame} Read finite nonzero direction admission and least-aligned-axis transverse conditioning. The alternate axis defines a frame only and never replaces a cancelled comb direction.
 * @evidenceReview {@link humanFaceHairFrame} #03ce90a Read finite nonzero direction admission and least-aligned-axis transverse conditioning. The alternate axis defines a frame only and never replaces a cancelled comb direction.
 * @evidence {@link evaluateHumanFaceHairDirection} Read parting, lift and both curl branches in their declared order. The field remains kinematic and root-space regional influence is independent of deformed surface coordinates.
 * @evidenceReview {@link evaluateHumanFaceHairDirection} #bb25244 Read the extracted envelope call against its former expression: optional uniform weight, independent-axis squared distance and exponential weight are unchanged. Parting, lift and wave/helix order remain kinematic; no new visual acceptance is claimed.
 * @evidence {@link humanFaceHairEmergence} Read the exit angle from the scalp: the surface normal tilted toward the field's tangential part, by the hairline's own ramp between the mid-scalp and hairline figures.
 * @evidenceReview {@link humanFaceHairEmergence} #35009bd Read the lower end of each published range taken deliberately, the hairline ramp shared with the scalp colour, the normal kept when the field has no tangential part, and the temporal figure left unmodelled rather than invented.
 * @evidence {@link humanFaceHairContact} Read the clearance (half width, half step, requested clearance and a scale-derived allowance) and the nearest-feature projection shared by guides and interpolated strands.
 * @evidenceReview {@link humanFaceHairContact} #c92db58 Read the allowance and projection lifted out of the integrator unchanged, the 64-step refusal, and that interpolated strands call the same projection on every station after the root. Reread with the ribbon width taken out of the clearance: a fibre path now keeps half a step plus the requested clearance, so a strand is no longer lifted by half a ribbon. Reread the step the rule now carries, which is the chord a curve may span and still keep the clearance by the 1-Lipschitz bound.
 * @evidence {@link humanFaceHairLength} Read the six axial lengths combined by absolute chart components and the seeded variation, shared by guides and strands.
 * @evidenceReview {@link humanFaceHairLength} #ba22710 Read the length lifted out of the integrator unchanged and its singular-chart refusal; a strand takes its own regional length rather than its guides'.
 * @evidence {@link resolveHumanFaceHairGatherAnchor} Read the shared domain ray hit and its current-surface barycentric replay; a missing direction refuses.
 * @evidenceReview {@link resolveHumanFaceHairGatherAnchor} #184379f Reread the polar ray from the neutral domain origin, nearest positive triangle hit with roundoff admission, retained barycentric weights, and recomposition from current triangle vertices. The attached point belongs to the common scalp, not a personal guide.
 * @evidence {@link createHumanFaceHairGatherField} Read the current scalp graph distance and tangent descent used before the tie.
 * @evidenceReview {@link createHumanFaceHairGatherField} #ca60522 Reread exact-coordinate welding beside the engine sheet query, current edge-length propagation from the tie triangle, connected-domain refusal, triangle gradients and direct tangent descent inside the tie triangle. It approximates a surface geodesic and does not replace contact.
 * @evidence {@link createHumanFaceHairTailSpread} Read the deterministic filled cross-section after the tie.
 * @evidenceReview {@link createHumanFaceHairTailSpread} #3ac7b32 Reread the entry/root/conditioned-frame radial fallback, fixed sample-derived angle and square-root area radius, cubic transition derivative, and zero radial velocity at both ends. The integrator still bounds turns and surface clearance.
 * @evidence {@link interpolateHumanFaceHairStrands} Read the guide interpolation: nearest same-side guides by scalp distance, exponential weights against the guides' mean spacing, equal arc-length blending and scaling to the strand's own length.
 * @evidenceReview {@link interpolateHumanFaceHairStrands} #6b7f88a Read the part gate, the cut-off at twice the spacing with the nearest-guide fallback, the single-guide case, and the refusals for no guide, a zero-length guide and a collapsed blend; no contact query is made here, the builder projects the result. Reread the optional clump: each station pulled toward the nearest guide's station at the same arc fraction by clump times that fraction, and the reported length taken from the clumped curve.
 * @evidence {@link createHumanFaceScalpTint} Read the scalp tint: coverage from the hairline transition ramp and the root region envelope on the neutral, the densest layer's colour, and the clamped gain toward the hair colour over the skin finish.
 * @evidenceReview {@link createHumanFaceScalpTint} #68fa143 Read the 20 mm transition converted to a polar angle per vertex, the smoothstep ramp, the root-region product, empty layers skipped, the per-vertex region material read after document overrides, and gains clamped to [0,1] so a lighter hair leaves the skin. Reread the greying mixture the scalp sees, the layer's colour lifted toward white by its unpigmented proportion. Reread the ramp taken from the shared hairline owner rather than computed here.
 * @evidence {@link humanFaceHairlineCoverage} Read the hairline transition: the zone's depth read as the polar angle it subtends at a direction's own distance, and the smoothstep both the population and the scalp colour take from it.
 * @evidenceReview {@link humanFaceHairlineCoverage} #2efa6c9 Read the ramp lifted out of the scalp tint unchanged, the refusal on a singular direction, and that root sampling and the tint now read the one function. The depth stays the shallow end of the literature's 2 to 3 cm. The depth is the transition zone's own 0.5 to 1.0 cm, not the 2 to 3 cm of the whole hairline region an earlier reading took.
 * @evidence {@link humanFaceHairlineBoundary} Read the hairline boundary blended from the four authored angles by the squared horizontal chart components, shared by root sampling and scalp coverage.
 * @evidenceReview {@link humanFaceHairlineBoundary} #1fab004 Read the blend lifted out of root sampling unchanged and the polar-axis minimum.
 * @evidence {@link growHumanFaceHairStrand} Read the placement of one interpolated strand: every station after the root projected by the guides' contact rule, and the strand grown by the integrator when that projection refuses.
 * @evidenceReview {@link growHumanFaceHairStrand} #e97b11f Read that the root is kept, the projected stations sit at the contact clearance, the reported clearance is the contact's less its allowance, and a refusing projection falls back to the integrator; the analytic scenario drives both branches and the narrow interior that makes the contact refuse. Reread the chord test after placement: a blend scaled until its stations outrun that step is grown instead, since the segments between them have no clearance argument. The segment out of the root is the emergence and is exempt, as it is in the integrator.
 * @evidence {@link integrateHumanFaceHairCurve} Read neutral regional length, seeded phase, signed-distance contact, chord bisection and final metric truncation. Arithmetic allowance is explicit; root-fan and hair-to-hair clearance remain unproved.
 * @evidenceReview {@link integrateHumanFaceHairCurve} #457b552 Read the shared scale-derived contact allowance and h + epsilon chord admission, including final extension by at most epsilon. The nearest-endpoint bound pays for both from the remaining contact allowance. Same-input Float32 GLB bytes remained exact in the 1,024-root probe; root-fan and hair-to-hair clearance remain unproved. Reread the clearance without the ribbon width; the free-path argument now covers the fibre only, and the ribbon's own corners belong to the mesh owner. Reread the emergence taken from `humanFaceHairEmergence` rather than the surface normal. Reread the turn held to the tightest natural curl, the step's projection and bisection lifted into one advance rule, and that the blocked-step slide was measured on the population and removed. Reread root-inside and first segment-sphere entry as two tie paths, exact remaining metric length, the current-surface descent before tie, the post-tie direction and area-sampled tube fill, and a named refusal if length ends before tie.
 * @evidence {@link buildHumanFaceHairMesh} Read single-root fan, paired metric rows, minimal frame transport, measured UV/taper and nondegenerate triangle refusal. It meshes the integrator's stations without Catmull-Rom interpolation.
 * @evidenceReview {@link buildHumanFaceHairMesh} #3c056d6 Read the first nonparallel tangent's emergence plane, straight-curve normal fallback and subsequent minimal transport. The analytic planar-width scenario failed before this correction. This inspection does not accept root-fan contact or current population appearance; the integrator's stations and measured UV/taper remain the geometry owners. Reread the per-curve widths and the corner fitting: a half width within the station's own free distance less the requested clearance is taken unqueried, a wider one is measured and solved back by a safeguarded Newton step onto that provable bound, and both sides take the tighter half width so the ribbon stays centred on its fibre. A station the caller left on the surface, with no room for any ribbon, refuses.
 * @evidence {@link createHumanFaceHairBuilder} Read shared domain/closure admission, neutral/current correspondence, owned construction and procedural finishes. The actual connected builder now calls this function; the 18 published numerical documents are migrated; photographic likeness is still pending.
 * @evidenceReview {@link createHumanFaceHairBuilder} #4049ed5 Read shared domain/closure admission, neutral/current correspondence, owned construction and procedural finishes. The actual connected builder now calls this function; the 18 published numerical documents are migrated; photographic likeness is still pending. Reread the guide selection by the root's own Halton identity, integration of guides only, same-side interpolation of the rest, projection of every strand station by the guides' contact rule, and the station budget over both. Reread the strand placement delegated to `growHumanFaceHairStrand`, with the station budget counting whichever curve comes back. Reread the widths measured from the seated roots and the sampler's accepted area, passed with the surface query to the mesh owner. Reread the growth area taken as that share of the same domain triangles as they stand on this face, so identity scales the widths. Reread the greying proportion handed to the material. Reread one polar ray hit on the neutral growth domain, barycentric current attachment and one current-surface distance field per gathered layer. It passes the same field to all roots and requires full integration rather than mixing guide intervals across the tie.
 * @evidence specifications/asset-and-representation/facial-authoring/contract.md#face-spec-parametric-hair Records source inspection and remaining root-fan, hair-to-hair contact and photographic likeness verification gaps for the shared numerical path. It does not accept the current rendered population.
 */
export const humanFaceNumericalHairReview =
  "Numerical hair source inspection; photographic likeness pending" as const;
