import type * as Human from "@automovie/human";

/**
 * Ocular construction inspections retained from the portable face review.
 * Each original reason and fingerprint stays attached to the same declaration.
 * The parent review retains this domain and the native graph still requires
 * coverage of the complete human source population across both carriers.
 * This record does not decide likeness or revise any photographed identity.
 *
 * @evidence requirements/actors/facial-authoring/contract.md#actor-face-review Keeps ocular construction inspection separate from each subject's visual observations.
 * @evidence specifications/asset-and-representation/facial-authoring/contract.md#face-spec-review Retains exact source targets, review reasons and fingerprints as part of the portable study's complete construction evidence.
 *
 * @evidence {@link Human.createPortraitOpticalFrame} Inspects the centred spherical support and engine shortest-arc placement shared by the real iris and cornea consumers, including finite/noncentral admission and owned frame values.
 * @evidenceReview {@link Human.createPortraitOpticalFrame} #952ce58 Read all finite/radius/noncentral refusals, owned local sphere and translation, normalized axial direction and the shared engine rotation. The ten-mm quarter-turn cornea test checks pole sag and axial shell thickness against hand arithmetic; the old off-axis height field refuses beside the radial construction. Parallel, antiparallel and extreme finite witnesses are exercised. The helper neither fits the globe nor guarantees cranial containment.
 * @evidence {@link Human.appendPortraitEyeMargins} Attaches the section rings to retained outer skin identities and returns the new inner boundary mapping.
 * @evidenceReview {@link Human.appendPortraitEyeMargins} #db275b5 Read the extracted eyeMargins and eyeLidRows owners. The outer ring reuses fitted host IDs; seven appended rings retain one group per triangle and return the inner IDs consumed after common subdivision. Both fitting and attachment use the same row calculation and supplied profile samplers. The independent four-point test pins XYZ, guide transport and caller preservation. This source inspection does not accept the final eyelid shape or contact residual.
 * @evidence {@link Human.assertPortraitEyebrowProfile} Admits bounded strand populations and finite profile arithmetic before allocation.
 * @evidenceReview {@link Human.assertPortraitEyebrowProfile} #045012e Read optional seed admission before allocation beside flow, root/span and dimension checks. Zero and uint32 maximum seeds are exercised, with negative, fractional, excessive and nonfinite values rejected. JSON shape admission remains separate; the actual eye component calls this numeric guard.
 * @evidence {@link Human.assertPortraitEyePerformance} Rejects nonfinite or unsupported eye-performance inputs before posing geometry.
 * @evidenceReview {@link Human.assertPortraitEyePerformance} #c200f11 Read all four finite checks and inclusive closure/gaze bounds, including the 0.95 observed-blink maximum. This standalone guard is also called by the public optical and lid helpers rather than relying only on UI input validation.
 * @evidence {@link Human.buildPortraitCornea} Constructs the joined anterior/posterior shell delivered with optical volume materials.
 * @evidenceReview {@link Human.buildPortraitCornea} #ae6b51a Traced corneal sag minus globe sag, one axial vertex per pole, reversed back winding and shared outer-ring closure. Clipping changes radial reach without refitting curvature per column. The actual export's volume topology gate checks closure; opaque clay display does not judge refraction.
 * @evidence {@link Human.buildPortraitEye} Builds resident ocular surfaces, pigment, lashes and brows from the final shared lid boundary.
 * @evidenceReview {@link Human.buildPortraitEye} #91c8a85 Read the complete final-rim, optical, tissue, lash and brow finisher with eyeOpticalSurface, geometry scaling and the canthal hull. Exposed sphere faces and connective faces partition one boundary, with shared normals and the same triangles for contact. Exact lid interpolation endpoints prevent an endpoint X from being paired with an interior Y/Z outside a canthal apex; interior samples retain bisection. Wet support queries use the same millimetre-to-metre multiplication as portraitPart. Static, half-closed/gazing and closed analytic components exercise actual finishers. Remaining eyelid protrusion requires rendered anatomy review; this source inspection is not likeness acceptance.
 * @evidence {@link Human.buildPortraitEyebrow} Samples the final skin beneath each independently named strand.
 * @evidenceReview {@link Human.buildPortraitEyebrow} #f2a65c8 Read the optional seeded independent sequence and the omitted-seed legacy path through actual fibre emission. Seeded planar coverage preserves every root-height band and each retained mesh; no fades preserve all meshes regardless of seed. The frozen legacy GLB and model digests replay exactly. Flow endpoint and side tests also pass; these checks do not accept a likeness.
 * @evidence {@link Human.buildPortraitPerformanceGlobe} Keeps a complete globe underneath the changing aperture.
 * @evidenceReview {@link Human.buildPortraitPerformanceGlobe} #b9f6a59 Read bounded integer tessellation, single north/south poles, wrapped rings, outward triangle winding, radius/centre placement and overflow refusal. Visibility belongs to surrounding opaque tissue, not a changing sphere radius.
 * @evidence {@link Human.createPortraitEyeComponent} Fits one owned eye configuration into shared skin and supplies its optical and tissue finishers.
 * @evidenceReview {@link Human.createPortraitEyeComponent} #a785772 Read the complete factory and fitting/attachment/finishing closures with eyeComponentInputs, eyeSupport, eyeLidRows, eyeMargins, eyeOpticalSurface and eyeSurfaceContact. Copied input admission precedes the identity fit. Tangent mode retains observed canthal guides and uses its fixed hull for performed intersections, initial contact, final contact and drawing; gaze cannot choose the fitted centre. Omitted mode keeps the old sphere and unshifted guide arithmetic. Static, observed, half-closed/gazing and closed independent-host cases check fixed outer targets and optical identity while actual rim positions move. Geometric feasibility does not settle the observed tissue shape.
 * @evidence {@link Human.createPortraitIrisMaterials} Produces independently named, owned opaque pigment finishes from those admitted endpoints.
 * @evidenceReview {@link Human.createPortraitIrisMaterials} #0a2093f Read prefix admission, all array/domain failures and eight linear interpolations into fresh material records. Roughness is 0.65 and no texture is attached; the eye owns radial membership and chooses these IDs without moving a vertex. Palette names and scalar finishes do not establish optical or subject likeness.
 * @evidence {@link Human.IPortraitUpperLidPoint} Names positive outward offsets and signed anterior relief over the actual ocular-to-skin bridge.
 * @evidenceReview {@link Human.IPortraitUpperLidPoint} #6a7002f Read the outward-offset/signed-relief pair against the upper row mapper. They use construction mm over a contact-to-host support bridge, not measured internal tissue thickness.
 * @evidence {@link Human.IPortraitUpperLidPoint.offset} Places each dry upper-tissue witness outward from the wet aperture in millimetres.
 * @evidenceReview {@link Human.IPortraitUpperLidPoint.offset} #a6724b2 Traced the positive offset through strict ordering and the planar rim normal. The central tarsal witness reaches y=3 from aperture y=2 with authored offset 1.
 * @evidence {@link Human.IPortraitUpperLidPoint.projection} Supplies signed upper-tissue relief independently of transverse placement.
 * @evidenceReview {@link Human.IPortraitUpperLidPoint.projection} #399d2a6 Read signed projection validation and replacement of the basic depth term. Negative crease values survive JSON; the independent quarter oracle retains each role's sign.
 * @evidence {@link Human.IPortraitUpperLidSection} Separates the six ordered upper tissue roles and farther host-skin attachment.
 * @evidenceReview {@link Human.IPortraitUpperLidSection} #5f0f4d7 Read all six named rows in order and their correspondence to shared lid rings. Tests retain separate upper/lower geometry and reject crossing crease offsets.
 * @evidence {@link Human.IPortraitUpperLidSection.margin} Owns the dry tissue row outside the unchanged wet contact rim.
 * @evidenceReview {@link Human.IPortraitUpperLidSection.margin} #bfb68f8 Traced margin to the ridge ring rather than the wet rim. The row test retains every wet point while detailed tissue changes outside it.
 * @evidence {@link Human.IPortraitUpperLidSection.tarsal} Controls the exposed body below the upper crease without adding basic tarsal volume twice.
 * @evidenceReview {@link Human.IPortraitUpperLidSection.tarsal} #f48fa03 Read the dedicated body point below the crease. The hand-known central point is (0,3,2); changing basic fold/volume controls leaves that fully selected detailed point unchanged.
 * @evidence {@link Human.IPortraitUpperLidSection.creaseInner} Sets the lower crease bank independently of its tarsal neighbour.
 * @evidenceReview {@link Human.IPortraitUpperLidSection.creaseInner} #0ee2eca Followed the lower crease bank into creaseInner, independently of tarsal and upper-bank depths. Crossing its predecessor or giving it NaN relief refuses in the profile test.
 * @evidence {@link Human.IPortraitUpperLidSection.creaseOuter} Sets the distinct upper crease bank before the overlying hood.
 * @evidenceReview {@link Human.IPortraitUpperLidSection.creaseOuter} #4d19ef9 Read the separate upper crease bank and strict successor order. Removing this required point from a serialized eye profile refuses at document admission.
 * @evidence {@link Human.IPortraitUpperLidSection.hood} Controls the hood edge independently of the two recessed crease banks.
 * @evidenceReview {@link Human.IPortraitUpperLidSection.hood} #3b88642 Traced the hood point to hoodEdge rather than to a second volume overlay. Input/result mutation of its relief and offset leaves the sampler's owned section unchanged.
 * @evidence {@link Human.IPortraitUpperLidSection.preseptal} Connects the upper fold into a broader outer tissue transition.
 * @evidenceReview {@link Human.IPortraitUpperLidSection.preseptal} #38de0d4 Read the last internal tissue point before the live attachment. Its depth participates in the same convex sampler, while the outer rim remains the host query's result.
 * @evidence {@link Human.IPortraitUpperLidSection.attachment} Places the live host-skin query beyond every internal tissue offset.
 * @evidenceReview {@link Human.IPortraitUpperLidSection.attachment} #a35f9a0 Read strict placement beyond all six points and its consumption by both fitting and rows. Real-socket edits move upper targets without moving lower targets; attachment at the last offset refuses.
 * @evidence {@link Human.IPortraitUpperLidProfile} Owns complete medial-to-lateral upper section witnesses independently on each eye.
 * @evidenceReview {@link Human.IPortraitUpperLidProfile} #5109c82 Read both complete populations: optional closedSections preserves witness coordinates and attachment distances while admitting an observed hood return. Without it all six offsets retain the prior strict order. The observed and closed arrays remain ordinary region data; no named-person or frozen first-face document is changed by this type extension.
 * @evidence {@link Human.IPortraitUpperLidProfile.sections} Replaces two through 32 ordered complete sections spanning zero to one.
 * @evidenceReview {@link Human.IPortraitUpperLidProfile.sections} #8012510 Read the complete two-to-32 population, required endpoints and whole-array replacement. Tests include a later interval, exact upper population bound, empty/duplicate/end omissions and a left three-to-two replacement.
 * @evidence {@link Human.createPortraitUpperLidProfile} Copies and admits upper role witnesses through the shared order-preserving sampler.
 * @evidenceReview {@link Human.createPortraitUpperLidProfile} #c973603 Read the ordered fallback, copied folded and closed samplers, matched witness/attachment check and observed-relative closure. The same stations reach the real eye rows. Hand arithmetic gives hood offset 2.25 and relief 0.6 halfway from observed 0.2 to current 0.6; crossing interior interpolation is refused despite valid ends. This is transverse-section admission, not final-surface collision or likeness approval.
 * @evidence {@link Human.createPortraitLowerLidProfile} Resolves ordered anatomical section witnesses for the actual eye consumer.
 * @evidenceReview {@link Human.createPortraitLowerLidProfile} #c8f314a Read delegation of the six existing lower roles into the common lid sampler. Copied admission, endpoint/order checks and convex operation order are retained. Quarter-oracle, population boundary, refusal and paired component tests pass. This adds no lower tissue or likeness verdict.
 * @evidence {@link Human.createPortraitOcularTissues} Builds owned medial conjunctiva and wet lower-margin profiles against supplied live ocular support.
 * @evidenceReview {@link Human.createPortraitOcularTissues} #4f9129f Read the complete factory, interval/sample admission, mirrored medial section, separate mound/ridge terms and clipped lower strip. Shape ownership, mirrored and translated frames, independent disabling and invalid dimensions/samples are covered by the tissue scenarios. The assembled eye additionally fits these meshes against its resident optical shell; the factory alone neither solves full triangle contact nor accepts the still-synthetic lower-lid form.
 * @evidence {@link Human.fitPortraitEyeSphere} Fits the globe from the lid plane independently of the gaze marker.
 * @evidenceReview {@link Human.fitPortraitEyeSphere} #205917a Read both fitting directions and their shared mean-rim residual. The default canthal-plane arithmetic is retained; observation-ray mode fixes the reference rim mean projection, rejects degenerate or undersized inputs and does not read current gaze. The tilted unit-circle oracle and rigid-frame test distinguish the modes. This is an authored surface basis, not recovered globe anatomy.
 * @evidence {@link Human.IPortraitCornea} Defines the closed optical shell's aperture, curvature, axial thickness and live globe support.
 * @evidenceReview {@link Human.IPortraitCornea} #c5a8df5 Read every field in the millimetre frame: unclipped radius bounds the angular extents, curvature exceeds that radius, globeRadius bounds curvature, and rimLift clears thickness. The surface callback supplies fitted depth; these controls are a rendering model, not measured physiology.
 * @evidence {@link Human.IPortraitEyebrowFlowDirection} Defines a tip on the supporting brow and one signed anatomical sweep, independently of fibre radius or density.
 * @evidence {@link Human.IPortraitEyebrowFlowDirection.tip} Places a strand endpoint between the lower zero and upper one boundaries so upper roots can descend.
 * @evidence {@link Human.IPortraitEyebrowFlowDirection.outwardBend} Carries millimetre lateral displacement whose sign is applied by the existing anatomical-side owner.
 * @evidence {@link Human.IPortraitEyebrowFlowProfile} Supplies complete medial-to-lateral and lower-to-upper root-band flow instead of one global rise.
 * @evidence {@link Human.IPortraitEyebrowFlowProfile.sections} Replaces the whole ordered witness population with two through 32 stations spanning zero to one.
 * @evidence {@link Human.createPortraitEyebrowFlow} Provides the actual brow builder with owned convex longitudinal and root-band direction samples.
 * @evidenceReview {@link Human.IPortraitEyebrowFlowDirection} #aaa6ebc Read the bounded tip and signed millimetre sweep against interpolation and both strand builders. The planar geometry scenario checks actual root and tip vertices without changing fibre count.
 * @evidenceReview {@link Human.IPortraitEyebrowFlowDirection.tip} #54e856b Read zero as the lower and one as the upper supporting boundary. Independent endpoint and out-of-range tests pass; actual upper and lower roots converge to the same authored tip in ribbon and tube geometry.
 * @evidenceReview {@link Human.IPortraitEyebrowFlowDirection.outwardBend} #fc0ca68 Read the signed millimetre displacement through anatomical-side application. The planar consumer test verifies mirrored lateral endpoint offsets and the profile test retains negative sweeps.
 * @evidenceReview {@link Human.IPortraitEyebrowFlowProfile} #9445f66 Read complete lower and upper root-band directions rather than whole-brow root coordinates. Tests cover cloned ownership, a collapsed band sampled at one half and independent side document replacement.
 * @evidenceReview {@link Human.IPortraitEyebrowFlowProfile.sections} #8df5b6a Read ordered complete witnesses at both endpoints. Tests admit two and 32, reject missing endpoints, duplicate or invalid stations and 33 witnesses, and replace the whole document population.
 * @evidenceReview {@link Human.createPortraitEyebrowFlow} #0651332 Read the copied witnesses, bounded query admission and convex cubic then linear interpolation. Independent arithmetic and actual tube/ribbon endpoint tests pass; temporarily disconnecting the builder made the endpoint test fail before restoration.
 * @evidence {@link Human.IPortraitEyebrowProfile} Separates strand dimensions and local support clearance from the brow's boundary binding.
 * @evidenceReview {@link Human.IPortraitEyebrowProfile} #d3ee760 Read optional flow and uint32 densitySeed beside the inherited dimensions. Flow replaces direction; a supplied seed selects independent thinning, while omission preserves the original population for replay. Tests cover side-specific seed inheritance and complete direction arrays without changing the host boundary.
 * @evidence {@link Human.IPortraitEyePerformance} Separates observed closure, current blink and gaze differences from eye identity.
 * @evidenceReview {@link Human.IPortraitEyePerformance} #1322e5a Read closure bounds, the invertible observed maximum and gaze-difference units against admission and component construction. The fields change actual tissue/optical geometry rather than scaling a whole eye to simulate a blink.
 * @evidence {@link Human.IPortraitEyeShape} Groups aperture, surrounding tissue, optical and sampling inputs for one eye instance.
 * @evidenceReview {@link Human.IPortraitEyeShape} #d664de1 Read the complete aperture, upper/lower tissue, optical, lash and sampling contract with input admission. Tangent support couples observation-ray fitting and radial optics, fixes the canthal midpoint, and shares one sampled support through expression. The optical radius no longer has to span exterior canthi in that mode; omission retains the all-rim fit. Tissue sections and contact remain separate owners, and no field infers clinical anatomy or accepts likeness.
 * @evidence {@link Human.IPortraitEyeSocket} Assigns caller-owned anatomical boundary identities to one replaceable eye.
 * @evidenceReview {@link Human.IPortraitEyeSocket} #042d18d Read the six members beside loopOf, fitting and brow construction. Both aperture paths share canthi and run in head-X order; the instance's anatomical side is separate from that order.
 * @evidence {@link Human.IPortraitEyeSphere} States the common centre and radius of the fitted optical surface in millimetres.
 * @evidenceReview {@link Human.IPortraitEyeSphere} #ef3af5e Read centre and radius against fitting, intersection and height consumers. Radius is a positive authored optical curvature control and centre lies behind the fitted aperture; neither is inferred from an emotion or asserted as a physiological measurement.
 * @evidence {@link Human.IPortraitIrisPigment} Defines two linear-RGB endpoints for the eight-band iris palette.
 * @evidenceReview {@link Human.IPortraitIrisPigment} #0f525ea Read base and signed variation together with exact-three-element, finite and unit-range endpoint admission. Every intermediate band is a convex combination of the admitted endpoints. This data describes authored reflectance controls and contains no sampled photograph or geometry.
 * @evidence {@link Human.IPortraitLowerLidPoint} Gives a named lower-tissue sample its planar offset and anterior section projection.
 * @evidenceReview {@link Human.IPortraitLowerLidPoint} #2e8e170 Read both millimetre fields through the eye's local outward-normal construction and support-depth bridge. Projection is not muscle thickness or a contact clearance; the two coordinates have separate geometric effects.
 * @evidence {@link Human.IPortraitLowerLidProfile} Carries the complete optional medial-to-lateral section population for one eye.
 * @evidenceReview {@link Human.IPortraitLowerLidProfile} #fad1313 Read the two-to-32 section population, required zero/one endpoints and strict finite progress against the copied resolver. Eye construction chooses the basic path when the optional profile is absent and uses the owned resolver when present; a supplied empty list refuses rather than meaning omission.
 * @evidence {@link Human.IPortraitLowerLidSection} Separates margin, pretarsal body, subtarsal boundary and preseptal transition in one shared section.
 * @evidenceReview {@link Human.IPortraitLowerLidSection} #1234883 Read all six points and outer attachment beside the explicit eye-row mapping. The ordering validator refuses crossed rows; all points still feed the same shared topology. This defines numerical shape freedom, not an accepted anatomical fit.
 * @evidence {@link Human.IPortraitOcularTissueBoundary} Supplies the live eye frame consumed by both tissue surfaces.
 * @evidenceReview {@link Human.IPortraitOcularTissueBoundary} #1eb1b53 Read side, ordered X endpoints, upper/lower callbacks and support height together with the consuming section and globe closures. The current eye supplies refined lids and an engine-sampled support including cornea. No independent aperture or frozen tissue origin is created here.
 * @evidence {@link Human.IPortraitOcularTissueShape} Separates the medial conjunctival profile from the narrow lower ocular margin.
 * @evidenceReview {@link Human.IPortraitOcularTissueShape} #e9c3846 Read the five scalar dimensions and the factory's owned copy. All are finite and nonnegative; zero corner length or margin width disables its corresponding surface, while zero relief retains that surface's underlying support. This type does not describe the external lower-lid body.
 * @evidence {@link Human.portraitEyebrowProfile} Supplies the authored basic strand dimensions when a caller omits detail.
 * @evidenceReview {@link Human.portraitEyebrowProfile} #099d6ad Read the default radius 0.05, step 0.0075, taper 0.58, clearance 0.03, arch 0.1, outward bend 1.2 and five segments against both consumers. Optional distribution fields remain omitted. The values are provisional fibre dimensions, not measured hair or accepted grooming.
 * @evidence {@link Human.portraitEyeSphereHeight} Supplies the anterior spherical height shared by sclera and pigment surfaces.
 * @evidenceReview {@link Human.portraitEyeSphereHeight} #e553bae Compared radius squared minus transverse squared distance with the positive square root. Tangency is finite, samples outside the disk refuse, and the same radius gives equal horizontal/vertical curvature.
 * @evidence {@link Human.portraitEyeSphereIntersection} Places gaze/lid samples on the fitted globe along the supplied viewing ray.
 * @evidenceReview {@link Human.portraitEyeSphereIntersection} #6e879fb Read the normalized-ray quadratic and camera-facing root. The slanted radius-two oracle retains collinearity, while a missed sphere or zero ray refuses. This preserves projection only for the declared viewing direction.
 * @evidence {@link Human.posePortraitLidCurves} Moves paired eyelid margins to a common seam while preserving the fixed optical sphere.
 * @evidenceReview {@link Human.posePortraitLidCurves} #ba4f505 Read finite paired-sample admission, exact copied identity at unchanged closure, observed-relative opening ratio and the three-to-one upper/lower travel. Complete closure gives coincident corresponding points; overflow refuses. Actual wink and clay-oblique frames show closure, but regular lid shape remains a likeness limitation.
 * @evidence {@link Human.posePortraitOpticalMesh} Rotates resident optics and normals around one fixed globe centre.
 * @evidenceReview {@link Human.posePortraitOpticalMesh} #de0614f Read aligned finite position/normal admission, copied zero-gaze identity, yaw then negative-pitch quaternion composition, translated positions and rotation-only normals. Post-transform nonfinite values refuse; mesh dimensions and unrelated UV/index data are retained.
 * @evidence {@link Human.createPortraitLidSectionSampler} Supplies both named lid profiles with owned, ordered tissue interpolation.
 * @evidenceReview {@link Human.createPortraitLidSectionSampler} #84d8c89 Read the full sampler and both anatomical callers. Finite positive tissue dimensions and attachment beyond every row are mandatory; the default enforces strict order, while an explicit anatomical callback checks authored and interpolated sections. All fields use the existing copied smoothstep witnesses. The folded upper consumer exercises the callback and interior crossing refusal; ordinary upper and lower callers retain their numerical path.
 * @evidence {@link Human.IPortraitEyelashProfile} Defines the optional seven-field upper-lash shape separately from lid aperture and optical size.
 * @evidenceReview {@link Human.IPortraitEyelashProfile} #8079554 Read the seven required values and observed head-frame angle convention. The eye's omitted-profile branch retains the old geometry; selecting this profile supports rigid lid-relative radial transport, but adds neither lower lashes nor hair dynamics.
 * @evidence {@link Human.IPortraitEyelashProfile.length} Sets a maximum centreline arc length, not a projected height.
 * @evidenceReview {@link Human.IPortraitEyelashProfile.length} #9a2cb40 Read the two shortening factors at construction: the canthal envelope and deterministic growth weight both stay at or below one. Curl uses the arc integral and does not rescale this length.
 * @evidence {@link Human.IPortraitEyelashProfile.elevation} Sets the root tangent relative to anterior head Z.
 * @evidenceReview {@link Human.IPortraitEyelashProfile.elevation} #c9a8685 Read the degree-to-radian conversion and the later root-centred transport separately. This launch angle describes the observed head frame; a change in lid closure carries it with the globe-relative direction, while gaze alone adds no turn.
 * @evidence {@link Human.IPortraitEyelashProfile.curl} Controls signed root-to-tip tangent rotation.
 * @evidenceReview {@link Human.IPortraitEyelashProfile.curl} #2868d4e Read the stable sinc integral and the straight zero-turn branch. Radius times absolute turn must remain below the effective arc length to avoid an inner sweep singularity.
 * @evidence {@link Human.IPortraitEyelashProfile.fan} Mirrors the medial-to-lateral strand fan between eyes.
 * @evidenceReview {@link Human.IPortraitEyelashProfile.fan} #56a0c9f Read anatomical progress from the eye caller and the side sign in the builder. The constant horizontal frame stays orthogonal to the turning tangent, including a straight anterior strand.
 * @evidence {@link Human.IPortraitEyelashProfile.radius} Defines the root cross-section radius.
 * @evidenceReview {@link Human.IPortraitEyelashProfile.radius} #4fa5f7f Read its shared scalar bounds and its separate use in the ring offsets. It changes thickness, not the centreline or aperture.
 * @evidence {@link Human.IPortraitEyelashProfile.taper} Reduces the radius along the strand without collapsing its tip.
 * @evidenceReview {@link Human.IPortraitEyelashProfile.taper} #2a079b1 Read radius times one minus taper times progress. The inclusive 0.98 maximum retains a positive end ring rather than a repeated pole.
 * @evidence {@link Human.IPortraitEyelashProfile.variation} Selects deterministic per-strand shortening.
 * @evidenceReview {@link Human.IPortraitEyelashProfile.variation} #28e0ab8 Read the cosine-squared index sequence and the half-scale maximum. There is no random state, scene time or person name in this variation.
 * @evidence {@link Human.portraitEyelashParameters} Shares seven scalar envelopes between lash admission and eye detail sliders.
 * @evidenceReview {@link Human.portraitEyelashParameters} #a48d39b Read every bound, unit, step and effect against the profile and construction. These are authoring envelopes, not population-derived anatomical limits or proof that all combinations clear skin.
 * @evidence {@link Human.assertPortraitEyelashProfile} Rejects incomplete and out-of-envelope profiles before eye fitting.
 * @evidenceReview {@link Human.assertPortraitEyelashProfile} #e2fdc10 Read the finite and inclusive-bound checks over every required field. The coupled curvature-radius refusal belongs to the strand builder after its per-strand length is known.
 * @evidence {@link Human.buildPortraitEyelash} Builds the optional curved strand rooted on the current upper margin.
 * @evidenceReview {@link Human.buildPortraitEyelash} #fe7dd98 Read the full sweep and optional radial motion admission. Normalized observed/current directions define the shortest rigid turn about the current root; parallel inputs keep the unrotated arithmetic and antipodes refuse. Circle, normal and downward-turn unit tests pass. Length, radius and the eye's metre conversion remain independent of this turn; torsion and collisions are not modeled.
 * @evidence {@link Human.IPortraitEyeShape.upperLashProfile} Opts into the new shape while omission retains the original upper-lash formula.
 * @evidenceReview {@link Human.IPortraitEyeShape.upperLashProfile} #455a4b8 Read the optional admission and the finisher's two branches. Existing documents without this field keep their original tube formula; selecting it does not change the eye's aperture or its skin fitting inputs.
 */
export const humanFaceOcularReview = {
  scope: "ocular construction",
};
