import alanRickman from "./alan-rickman.json";
import danielRadcliffe from "./daniel-radcliffe.json";
import emmaWatson from "./emma-watson.json";
import generatedBlackBoy01 from "./generated-black-boy-01.json";
import generatedBlackGirl01 from "./generated-black-girl-01.json";
import generatedKoreanBoy01 from "./generated-korean-boy-01.json";
import generatedKoreanGirl01 from "./generated-korean-girl-01.json";
import generatedWhiteBoy01 from "./generated-white-boy-01.json";
import generatedWhiteGirl01 from "./generated-white-girl-01.json";
import jangSuHye from "./jang-su-hye.json";
import kimMinJung from "./kim-min-jung.json";
import leeTaeRi from "./lee-tae-ri.json";
import maggieSmith from "./maggie-smith.json";
import michaelGambon from "./michael-gambon.json";
import miriamMargolyes from "./miriam-margolyes.json";
import ohSeungYoon from "./oh-seung-yoon.json";
import parkEunBin from "./park-eun-bin.json";
import type { humanFaceStudyReview } from "./review";
import rupertGrint from "./rupert-grint.json";
import yooSeungHo from "./yoo-seung-ho.json";

/**
 * Selected numerical face documents used by the actual playground editor.
 * The package contains no named people; this study owns their input choices
 * and keeps the documents portable. The editor admits each document when read.
 * Source images, input quality and per-view observations remain separate.
 *
 * @evidence requirements/actors/facial-authoring/contract.md#actor-face-review Binds the editor's actual nineteen saved inputs to their separate source inventories, capture observations and unaccepted likeness verdicts.
 * @evidence specifications/asset-and-representation/facial-authoring/contract.md#face-spec-review Keeps the imported document identity attached to each artifact-specific review rather than treating successful construction as visual acceptance.
 * @evidence requirements/actors/facial-authoring/contract.md#actor-face-skin-condition Supplies separate resting-fold and tissue-descent settings for four older-person studies without assigning age morphology to every input.
 * @evidence specifications/asset-and-representation/facial-authoring/contract.md#face-spec-skin-condition Loads the same bounded skin documents in the editor, with explicit regional amounts and independent current-expression creasing.
 *
 * @evidence studies/human-face/review.md#oral-joint-space-2026-09-16 Retains the four named parent studies used by the joint oral investigation; replacement cavity meshes, numerical improvements and remaining render/tissue limitations are separately identified experiments rather than outputs replayed by these documents.
 * @evidenceReview studies/human-face/review.md#oral-joint-space-2026-09-16 #4d79467 Read the complete chronology against the nineteen-document registry. The older coarse/enriched self-crossings remain recorded; the later eight complete outputs clear exact all-AABB contact checks and retain the incisal improvements. All 72 later views were read, exposing Oh's residual dark marks and near-coincident inner/outer surfaces. Six directly read controls distinguish those marks from simple shadow changes; the two CPU clip controls remain uninspected. The parent documents do not replay cached cavities. The user's whole-feature face-editor priority and required low-quality inputs do not convert geometric feasibility into anatomical recovery or accepted likeness.
 *
 * @evidence studies/human-face/review.md#alan-rickman Connects the current aperture override removal to its measured boundary, thirteen-view comparison and separately audited built-in editor, while retaining the earlier face-only record.
 * @evidenceReview studies/human-face/review.md#alan-rickman #de2edd4 Read the complete current candidate and historical artifact records. The fitted incisal-column metric improves, but final Float32 contact checks expose the shared oral-backdrop defect; Alan and Oh also have lip intersections and the missed Oh neutral exposure is corrected. All 216 comparative views, model identities, counterexamples and actual-editor limitations remain preserved. This is joint-repair research, not oral completion or new likeness acceptance. Earlier inspection retained: Re-read this observation after relocation and verified its document and both Markdown inventories are byte-identical to the preceding paths. The following inspection remains the retained historical assessment, not a new capture or likeness approval: Read the projected aperture ratios and fresh baseline/candidate comparison beside all thirteen observed views and three views of each neutral/blink state. Removing the override reduces compression but leaves deep orbital shadows, young smooth skin, nasal/oral simplification and striped hair. The actual editor's three inspected fronts and independent same-browser replays preserve state; cross-runtime GLBs differ in one measured normal step, not positions or other bytes, so byte identity remains explicitly false. Neither the aperture improvement nor the separate numerical audit accepts likeness.
 * @evidence studies/human-face/review.md#daniel-radcliffe Supplies the daniel-radcliffe replay document whose selected source, rendered artifact and nine inspected views are recorded here.
 * @evidenceReview studies/human-face/review.md#daniel-radcliffe #93b6b2b Re-read this observation after relocation and verified its document and both Markdown inventories are byte-identical to the preceding paths. The following inspection remains the retained historical assessment, not a new capture or likeness approval: Read the source's visible lower incisors and the independently authored mandibular row in the nine-view result. Only a thin lower enamel sliver is visible, while the dark gap, regular crowns and angular nasal/lid support remain. No obvious protrusion in these views is not an interarch collision certificate; likeness is unaccepted.
 * @evidence studies/human-face/review.md#emma-watson Connects the current RGB-only study to its held-out comparison, thirteen-view inspection and separate built-in editor export, while retaining the earlier face-only record.
 * @evidenceReview studies/human-face/review.md#emma-watson #34a880e Re-read this observation after relocation and verified its document and both Markdown inventories are byte-identical to the preceding paths. The following inspection remains the retained historical assessment, not a new capture or likeness approval: Read the measured skin mask, fixed-geometry RGB adjustment and separate held-out result beside all thirteen current views. The dark cast is reduced but pale uniform skin, orbital planes, nasal/lip form and ribbon hair remain. The rebuilt native selection and JSON/GLB match independent source; three of six editor views were directly read. Neither partial colour improvement nor exact export accepts likeness or the inferred rear anatomy.
 * @evidence studies/human-face/review.md#generated-black-boy-01 Connects the current upper-crown and mandibular-row update to its source replay, ten inspected views and separately retained historical hair and face records.
 * @evidenceReview studies/human-face/review.md#generated-black-boy-01 #733f06e Re-read this observation after relocation and verified its document and both Markdown inventories are byte-identical to the preceding paths. The following inspection remains the retained historical assessment, not a new capture or likeness approval: Read the retained dental record and subsequent reference-continuation evidence. The historical twenty-five-degree refusal is now separated from the new midpoint/endpoint source replay, twenty inspected views and actual editor export. Lips stay connected and the original neck remains unchanged, but the endpoint submental fold, missing oral tissue and existing facial discrepancies remain. Finite clearance samples and construction tests do not establish physiological motion or likeness.
 * @evidence studies/human-face/review.md#generated-black-girl-01 Connects this study's partial optical adoption to the four changed construction controls, exact replay, 27 directly inspected views, retained limitations and preceding artifact-specific observations.
 * @evidenceReview studies/human-face/review.md#generated-black-girl-01 #463e31a Read the complete current optical adoption and preceding artifact records. The four numerical eye controls alone change; two independent builds reproduce the inspected candidate. Directly read all 27 current observed/blink/oral-gaze views for this person, including both profiles, back and clay. Curved optical reflection improves while the lower-lid band, orbital hollow, regular enamel and rear-hair separation remain unresolved. The 12-mm sphere and canthal hull are authored geometric approximations, not measured individual anatomy. Optical partial adoption does not accept whole-face likeness. Historical inspection retained: Re-read this observation after relocation and verified its document and both Markdown inventories are byte-identical to the preceding paths. The following inspection remains the retained historical assessment, not a new capture or likeness approval: Read the nine-view record and matched its final document/model identity to the current replay. The dark optical palette and smile remain, but lower-lid/lip bands and the tooth row are too uniform; profiles/back show inferred posterior lobes. Source hair is not reproduced and likeness remains unaccepted.
 * @evidence studies/human-face/review.md#generated-korean-boy-01 Connects this study's partial optical adoption to the four changed construction controls, exact replay, 27 directly inspected views, retained limitations and preceding artifact-specific observations.
 * @evidenceReview studies/human-face/review.md#generated-korean-boy-01 #ded1bb0 Read the complete current optical adoption and preceding artifact records. The four numerical eye controls alone change; two independent builds reproduce the inspected candidate. Directly read all 27 current observed/blink/oral-gaze views for this person, including both profiles, back and clay. The curved reflective optics improve while the lower-lid band, broad upper lid, medial depth, block-like crowns and inferred neck remain unresolved. The 12-mm sphere and canthal hull are authored geometric approximations, not measured individual anatomy. Optical partial adoption does not accept whole-face likeness. Historical inspection retained: Re-read this observation after relocation and verified its document and both Markdown inventories are byte-identical to the preceding paths. The following inspection remains the retained historical assessment, not a new capture or likeness approval: Read the selected original, nine capture identities and final observations. The smile is present but incisal form, brows and inferior-lid roll are regular. The refused smaller-opening proposal was withdrawn without weakening orientation admission. Replay passes and likeness remains unaccepted.
 * @evidence studies/human-face/review.md#generated-korean-girl-01 Supplies the generated-korean-girl-01 replay document whose selected source, rendered artifact and nine inspected views are recorded here.
 * @evidenceReview studies/human-face/review.md#generated-korean-girl-01 #401269d Re-read this observation after relocation and verified its document and both Markdown inventories are byte-identical to the preceding paths. The following inspection remains the retained historical assessment, not a new capture or likeness approval: Read the frozen first-hour boundary and the separately identified hair-free human artifact. All nine listed images, neutral and performance diagnostics were directly inspected; synthetic lid, nasal, lip and crown form remains. Current replay retains model 9d0c26d8 and GLB 112cc109. No identity fitting was resumed and likeness is unaccepted.
 * @evidence studies/human-face/review.md#generated-white-boy-01 Supplies the generated-white-boy-01 replay document whose selected source, rendered artifact and nine inspected views are recorded here.
 * @evidenceReview studies/human-face/review.md#generated-white-boy-01 #1a68bad Re-read this observation after relocation and verified its document and both Markdown inventories are byte-identical to the preceding paths. The following inspection remains the retained historical assessment, not a new capture or likeness approval: Read the source-pigment correction and nine-view account. The narrow-eyed smile and upper row remain, but block-like crowns, strip brows and angular nasal base do not reproduce the original. Reduced lower-lid relief does not resolve generic smiling tissue; likeness is unaccepted.
 * @evidence studies/human-face/review.md#generated-white-girl-01 Supplies the generated-white-girl-01 replay document whose selected source, rendered artifact and nine inspected views are recorded here.
 * @evidenceReview studies/human-face/review.md#generated-white-girl-01 #a01bf05 Re-read this observation after relocation and verified its document and both Markdown inventories are byte-identical to the preceding paths. The following inspection remains the retained historical assessment, not a new capture or likeness approval: Read the oblique original's observed/hidden-side distinction and all nine output views. Lateral gaze and smile remain, while the inferred opposite side, uniform enamel and simple lid rolls are not independently observed. Replay passes without accepting likeness or rear anatomy.
 * @evidence studies/human-face/review.md#jang-su-hye Supplies the jang-su-hye replay document whose selected source, rendered artifact and nine inspected views are recorded here.
 * @evidenceReview studies/human-face/review.md#jang-su-hye #d2bb046 Re-read this observation after relocation and verified its document and both Markdown inventories are byte-identical to the preceding paths. The following inspection remains the retained historical assessment, not a new capture or likeness approval: Read why the adult symposium portrait was selected over small childhood group frames. Its nine views retain closed lips without visible enamel, but nasal shape and orbital bands are simplified; hidden head/neck is inferred. The settings do not purport to reproduce other ages, and likeness is unaccepted.
 * @evidence studies/human-face/review.md#kim-min-jung Supplies the kim-min-jung replay document whose selected source, rendered artifact and nine inspected views are recorded here.
 * @evidenceReview studies/human-face/review.md#kim-min-jung #841502e Re-read this observation after relocation and verified its document and both Markdown inventories are byte-identical to the preceding paths. The following inspection remains the retained historical assessment, not a new capture or likeness approval: Read the closed-smile source and nine-view output record. Explicit lip closure removed the inappropriate dental strip, while heavy vermilion, pinched inner under-eye wedges and angular nasal base remain visible in obliques/clay. Event lighting does not supply measured albedo; likeness is unaccepted.
 * @evidence studies/human-face/review.md#lee-tae-ri Connects the measured opening override removal to current multi-angle and expression inspection while retaining the historical chin-frame record.
 * @evidenceReview studies/human-face/review.md#lee-tae-ri #17d9a24 Re-read this observation after relocation and verified its document and both Markdown inventories are byte-identical to the preceding paths. The following inspection remains the retained historical assessment, not a new capture or likeness approval: Read the measured boundary ratios, thirteen observed views, fresh baseline comparison and three views per neutral/half-blink/blink state. The aperture is less compressed, but the superior hood, nasal base, lip contour, uniform skin and centre-part hair remain unlike the source. Four actual editor fronts and byte-identical JSON/GLB exports support state replay; undo restores the closed-smile document without assuming positive lip separation. The record distinguishes twenty-four captures from inherited eighteen-capture prose. Neither numerical agreement nor closed lids accepts likeness.
 * @evidence studies/human-face/review.md#maggie-smith Supplies the maggie-smith replay document whose selected source, rendered artifact and nine inspected views are recorded here.
 * @evidenceReview studies/human-face/review.md#maggie-smith #eab8f4a Read the complete current candidate and historical artifact records. The fitted incisal-column metric improves, but final Float32 contact checks expose the shared oral-backdrop defect; Alan and Oh also have lip intersections and the missed Oh neutral exposure is corrected. All 216 comparative views, model identities, counterexamples and actual-editor limitations remain preserved. This is joint-repair research, not oral completion or new likeness acceptance. Earlier inspection retained: Re-read this observation after relocation and verified its document and both Markdown inventories are byte-identical to the preceding paths. The following inspection remains the retained historical assessment, not a new capture or likeness approval: Read the full-body source's small face and scarf-covered neck limitations. All nine outputs were inspected; the face looks substantially younger, with insufficient wrinkles, orbital bags and aged tissue. Uniform enamel and generic neck remain defects, and low source resolution does not make likeness accepted.
 * @evidence studies/human-face/review.md#michael-gambon Supplies the michael-gambon replay document whose selected source, rendered artifact and nine inspected views are recorded here.
 * @evidenceReview studies/human-face/review.md#michael-gambon #155575d Re-read this observation after relocation and verified its document and both Markdown inventories are byte-identical to the preceding paths. The following inspection remains the retained historical assessment, not a new capture or likeness approval: Read the monochrome provenance and nine-view record with separate one-ULP browser/Node GLBs. The wider jaw and narrowed eyes survive, but smooth young tissue and simplified orbital/nasolabial form remain. Skin and iris colours are explicitly unobserved authored values; likeness is unaccepted.
 * @evidence studies/human-face/review.md#miriam-margolyes Connects this study's partial optical adoption to the four changed construction controls, exact replay, 27 directly inspected views, retained limitations and preceding artifact-specific observations.
 * @evidenceReview studies/human-face/review.md#miriam-margolyes #5195e49 Read the complete current optical adoption and preceding artifact records. The four numerical eye controls alone change; two independent builds reproduce the inspected candidate. Directly read all 27 current observed/blink/oral-gaze views for this person, including both profiles, back and clay. The visible optical reflection and canthal transition improve while the hood, aged tissue, cap-like hair, neck and oral-state dental visibility remain unresolved. The 12-mm sphere and canthal hull are authored geometric approximations, not measured individual anatomy. Optical partial adoption does not accept whole-face likeness. Historical inspection retained: Re-read this observation after relocation and verified its document and both Markdown inventories are byte-identical to the preceding paths. The following inspection remains the retained historical assessment, not a new capture or likeness approval: Read the thirteen-view layered-hair adoption beside the earlier colour/brow and face-only records. The two numerical layers preserve all non-hair parts/materials and replace broad grey coils with fine white coverage, but the uniform cap, fringe and patterned shadows differ from the source. The separately rebuilt editor verifies current built-in selection, neutral, undo and blink with exact independent-source exports; three inspected editor fronts show closure and surviving fine coverage. Facial planes, aged tissue, oral contents and neck remain unresolved. Neither construction nor the fixed-light skin error accepts likeness.
 * @evidence studies/human-face/review.md#oh-seung-yoon Supplies the oh-seung-yoon replay document whose selected source, rendered artifact and nine inspected views are recorded here.
 * @evidenceReview studies/human-face/review.md#oh-seung-yoon #7b0e298 Read the complete current candidate and historical artifact records. The fitted incisal-column metric improves, but final Float32 contact checks expose the shared oral-backdrop defect; Alan and Oh also have lip intersections and the missed Oh neutral exposure is corrected. All 216 comparative views, model identities, counterexamples and actual-editor limitations remain preserved. This is joint-repair research, not oral completion or new likeness acceptance. Earlier inspection retained: Re-read this observation after relocation and verified its document and both Markdown inventories are byte-identical to the preceding paths. The following inspection remains the retained historical assessment, not a new capture or likeness approval: Read the small source's pixel/fringe limitations and nine directly inspected output views. The wide regular upper row, dark oral gap and heavy lid/lip bodies remain. The orientation-refused opening reduction was not committed; no guard was weakened and likeness is unaccepted.
 * @evidence studies/human-face/review.md#park-eun-bin Supplies the park-eun-bin replay document whose selected source, rendered artifact and nine inspected views are recorded here.
 * @evidenceReview studies/human-face/review.md#park-eun-bin #5509128 Re-read this observation after relocation and verified its document and both Markdown inventories are byte-identical to the preceding paths. The following inspection remains the retained historical assessment, not a new capture or likeness approval: Read the nine-view record and its separate browser and Node GLB digests. Closed lips hide enamel, but lid rolls and narrow nasal form remain simplified. The cross-runtime difference is one normal ULP, not a position or topology change; inferred rear anatomy and likeness remain unaccepted.
 * @evidence studies/human-face/review.md#rupert-grint Supplies the rupert-grint replay document whose selected source, rendered artifact and nine inspected views are recorded here.
 * @evidenceReview studies/human-face/review.md#rupert-grint #e91f10a Re-read this observation after relocation and verified its document and both Markdown inventories are byte-identical to the preceding paths. The following inspection remains the retained historical assessment, not a new capture or likeness approval: Read the premiere original and nine-view result. The thin closed lip band remains, but regular lid shelves, simplified nasal base and weak individualized soft tissue differ; freckles are unsupported. Source pose and successful replay do not accept likeness.
 * @evidence studies/human-face/review.md#yoo-seung-ho Connects this study's partial optical adoption to the four changed construction controls, exact replay, 27 directly inspected views, retained limitations and preceding artifact-specific observations.
 * @evidenceReview studies/human-face/review.md#yoo-seung-ho #d081ab2 Read the complete current candidate and historical artifact records. The fitted incisal-column metric improves, but final Float32 contact checks expose the shared oral-backdrop defect; Alan and Oh also have lip intersections and the missed Oh neutral exposure is corrected. All 216 comparative views, model identities, counterexamples and actual-editor limitations remain preserved. This is joint-repair research, not oral completion or new likeness acceptance. Earlier inspection retained: Read the complete current optical adoption and preceding artifact records. The four numerical eye controls alone change; two independent builds reproduce the inspected candidate. Directly read all 27 current observed/blink/oral-gaze views for this person, including both profiles, back and clay. The rounded optical reflection improves while the lower-lid protrusion, superior orbital volume, angular nasal/jaw/cervical planes and regular dental row remain unresolved. The 12-mm sphere and canthal hull are authored geometric approximations, not measured individual anatomy. Optical partial adoption does not accept whole-face likeness. Historical inspection retained: Re-read this observation after relocation and verified its document and both Markdown inventories are byte-identical to the preceding paths. The following inspection remains the retained historical assessment, not a new capture or likeness approval: Read the complete current and historical record. Ninety-six fringe paths change while the other cards, non-hair geometry and all materials stay exact. All thirteen observed views, the baseline comparisons and three views per expression support the lateral-flow improvement, but uniform clumps, crown strips and gaps, patterned shadows and facial likeness defects remain. The fragment-boundary residual is not subpixel accuracy: its fractional-shift probe varies by up to 2.10 pixels. The separate occupancy boundary records its definition and observed 0.43-pixel shift error without claiming a universal bound. Four actual editor fronts, strict JSON/GLB identity and undo support the four authored states. Neither sparse boundary measurements nor replay accepts likeness.
 * @evidence {@link humanFaceStudyReview} Retains the shared construction-source inspection for these independent numerical face documents.
 */
export const humanFaceStudyDocuments: Readonly<Record<string, unknown>> = {
  "alan-rickman": alanRickman,
  "daniel-radcliffe": danielRadcliffe,
  "emma-watson": emmaWatson,
  "generated-black-boy-01": generatedBlackBoy01,
  "generated-black-girl-01": generatedBlackGirl01,
  "generated-korean-boy-01": generatedKoreanBoy01,
  "generated-korean-girl-01": generatedKoreanGirl01,
  "generated-white-boy-01": generatedWhiteBoy01,
  "generated-white-girl-01": generatedWhiteGirl01,
  "jang-su-hye": jangSuHye,
  "kim-min-jung": kimMinJung,
  "lee-tae-ri": leeTaeRi,
  "maggie-smith": maggieSmith,
  "michael-gambon": michaelGambon,
  "miriam-margolyes": miriamMargolyes,
  "oh-seung-yoon": ohSeungYoon,
  "park-eun-bin": parkEunBin,
  "rupert-grint": rupertGrint,
  "yoo-seung-ho": yooSeungHo,
};
