import type { IPortraitHairShape } from "./IPortraitHairShape";
import { createTexture } from "./createTexture";

/**
 * Generate an RGB tangent-space normal PNG from the same fibre coverage that
 * owns the colour mask. Across each winning fibre a circular cross-section
 * supplies X and Z; Y is neutral in the legacy pattern. A curl profile rotates
 * that transverse normal perpendicular to its wave tangent using the authored
 * nominal aspect ratio. Empty samples retain the flat card normal.
 * This shading detail adds no vertices and does not model hair scattering.
 * The fibres are the mask's own, generated by the one shared owner, so an
 * optional greying mixture has to reach both: an unpigmented fibre is painted
 * thicker and the relief must describe the same fibre the colour does.
 * @evidence requirements/actors/facial-authoring/contract.md#actor-face-anatomical-components Supplies fibre relief on surface locks without constructing individual hair meshes.
 * @evidence specifications/asset-and-representation/facial-authoring/contract.md#face-spec-components Encodes the mask's shared fibre centres and radii as linear tangent-space normals.
 */
export function createPortraitHairNormalTexture(
  seed: number,
  fibres: number,
  coverage: number,
  curl?: IPortraitHairShape["fibreCurl"],
  mixture?: { pigment: readonly number[]; grey: number },
): string {
  return createTexture(seed, fibres, coverage, true, curl, 1, mixture);
}
