import type { IPortraitHairShape } from "./IPortraitHairShape";
import { createPortraitHairFibreTexture } from "./createPortraitHairFibreTexture";

/**
 * Generate an RGB tangent-space normal PNG from the same fibre coverage that
 * owns the colour mask. Across each winning fibre a circular cross-section
 * supplies X and Z; Y is neutral in the legacy pattern. A curl profile rotates
 * that transverse normal perpendicular to its wave tangent using the authored
 * nominal aspect ratio. Empty samples retain the flat card normal.
 * This shading detail adds no vertices and does not model hair scattering.
 * The fibres are the mask's own, generated by the one shared owner, so an
 * optional greying mixture has to reach both: an unpigmented fibre is painted
 * thicker and the relief must describe the same fibre the colour does.
 */
export function createPortraitHairNormalTexture(
  seed: number,
  fibres: number,
  coverage: number,
  curl?: IPortraitHairShape["fibreCurl"],
  mixture?: { pigment: readonly number[]; grey: number },
): string {
  return createPortraitHairFibreTexture(seed, fibres, coverage, true, curl, 1, mixture);
}
