#!/usr/bin/env node
import { AutoMovieLegacyImporter } from "@automovie/mcp";
import { spawnSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";

import { renderScaffold } from "./renderScaffold";
import { writeFiles } from "./writeFiles";

const USAGE = `automovie: scaffold an automovie project

Usage:
  npx create-automovie <directory> [--force]
  npx automovie start <directory> [--force]
  npx automovie verify
  npx automovie migrate <directory> [--dry-run | --rollback]
  npx automovie render <all|plan|run|status|verify|finalize|gc> [options]

Commands:
  start <directory>   Create <directory> and lay down the starter template:
                      production MCP config, typed shot source, deterministic
                      compiler, local viewer, capture, tests, and review gates.
  verify              Reopen generated bytes, reviews, render receipts, and
                      delivery media without modifying project state.
  migrate <directory> Plan or apply a non-destructive legacy v1 import.
  render <action>     Run the current project's resumable render job.

Options:
  --force             Scaffold into a non-empty directory.
  --dry-run           Print the immutable legacy import plan without writing.
  --rollback          Remove one still-untouched applied legacy import.
  -h, --help          Show this help.
  -v, --version       Print the version.
`;

/**
 * This package's version, read at runtime from the sibling `package.json`
 * (`require`, not an `import`, so it stays outside `rootDir`). `__dirname`
 * resolves to `src` under ttsx and `lib` when published; the file sits one
 * level up in both.
 */
const packageVersion = (): string =>
  (require(path.join(__dirname, "..", "package.json")) as { version: string })
    .version;

/** Derive a valid npm package name from the target directory's basename. */
const projectNameOf = (targetDir: string): string =>
  path
    .basename(targetDir)
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^[-.]+|[-.]+$/g, "") || "automovie-project";

/**
 * The `automovie` CLI entry: parse argv, render the starter, and write it to
 * the target directory. Returns the process exit code (0 success, 1 on a usage
 * or scaffold error) rather than exiting, so the logic stays unit-testable.
 *
 * @author Samchon
 */
export const run = (argv: readonly string[]): number => {
  const args = argv.slice(2);
  if (args.length === 0 || args.includes("-h") || args.includes("--help")) {
    process.stdout.write(USAGE);
    return 0;
  }
  if (args.includes("-v") || args.includes("--version")) {
    process.stdout.write(`${packageVersion()}\n`);
    return 0;
  }

  const [command, ...rest] = args;
  if (command === "render") return runProjectRender(rest);
  if (command === "verify") {
    if (rest.length !== 0) {
      process.stderr.write("verify takes no arguments.\n");
      return 1;
    }
    return runProjectScript("verify.ts", []);
  }
  if (command !== "start" && command !== "migrate") {
    process.stderr.write(`unknown command "${command}"\n\n${USAGE}`);
    return 1;
  }

  const dir = rest.find((arg) => !arg.startsWith("-"));
  if (dir === undefined) {
    process.stderr.write(`${command} needs a target directory\n\n${USAGE}`);
    return 1;
  }

  const targetDir = path.resolve(process.cwd(), dir);
  try {
    if (command === "migrate") {
      if (rest.includes("--dry-run") && rest.includes("--rollback"))
        throw new Error("migrate accepts only one of --dry-run or --rollback.");
      const importer = new AutoMovieLegacyImporter(targetDir);
      const output = rest.includes("--rollback")
        ? importer.rollback()
        : rest.includes("--dry-run")
          ? importer.plan()
          : importer.apply();
      process.stdout.write(`${JSON.stringify(output, null, 2)}\n`);
      return 0;
    }
    const files = renderScaffold({ name: projectNameOf(targetDir) });
    const written = writeFiles(targetDir, files, {
      force: rest.includes("--force"),
    });
    process.stdout.write(
      `Scaffolded ${written.length} files into ${targetDir}\n\n` +
        written
          .map((file) => `  ${path.relative(targetDir, file) || "."}`)
          .join("\n") +
        `\n\nNext:\n  cd ${dir}\n  npm install\n  npm run capture:install\n  npm run capture:doctor\n  npm run build\n  npm run lint\n  npm run render -- all --tier proxy\n  npm run viewer\n\n` +
        `Open http://127.0.0.1:5173 after the viewer starts.\n\n` +
        `README.md explains source ownership, MCP review gates, and the local viewer.\n`,
    );
    return 0;
  } catch (error) {
    process.stderr.write(
      `${error instanceof Error ? error.message : String(error)}\n`,
    );
    return 1;
  }
};

const runProjectRender = (args: readonly string[]): number => {
  const action = args[0];
  if (
    action !== "plan" &&
    action !== "run" &&
    action !== "status" &&
    action !== "verify" &&
    action !== "finalize" &&
    action !== "all" &&
    action !== "gc"
  ) {
    process.stderr.write(
      `render needs one of all, plan, run, status, verify, finalize, or gc\n\n${USAGE}`,
    );
    return 1;
  }
  return runProjectScript("render.ts", args);
};

const runProjectScript = (
  scriptName: string,
  args: readonly string[],
): number => {
  const root = process.cwd();
  const script = path.join(root, "scripts", scriptName);
  const tsx = path.join(root, "node_modules", "tsx", "dist", "cli.mjs");
  if (fs.existsSync(script) === false || fs.existsSync(tsx) === false) {
    process.stderr.write(
      `The current project has no installed scripts/${scriptName} + tsx runtime. Run this command from a scaffolded project after npm install.\n`,
    );
    return 1;
  }
  const child = spawnSync(process.execPath, [tsx, script, ...args], {
    cwd: root,
    stdio: "inherit",
  });
  return child.status ?? 1;
};

if (require.main === module) process.exitCode = run(process.argv);
