import type {
  AutoMovieContentDigest,
  IAutoMovieBuildProjectOutput,
  IAutoMovieDiagnostic,
  IAutoMovieGeneratedManifest,
} from "@automovie/interface";
import type { IAutoMovieProductionDesignGraph } from "@automovie/production";

import type {
  IAutoMovieProjectStateFreshness,
  IAutoMovieProjectStateProblem,
} from "./loadAutoMovieProjectState";

/**
 * Close a loaded snapshot with two source verdicts around the final design read.
 *
 * Every observed compile failure refuses current use, even when input identity
 * stays unchanged. Diagnostics retain first-observed order across the initial
 * and closing checks, collapsing only identical records. The readers preserve
 * the loader's read order while making failures observable without filesystem
 * fixtures. Generated bytes remain the snapshot the caller already verified.
 *
 * @evidence requirements/evidence-and-provenance/completeness-freshness-and-refusal.md#evidence-honest-refusal Refuses current state if any source verdict fails or closing identity cannot be confirmed.
 * @evidence specifications/evidence-and-provenance/completeness-freshness-and-refusal.md#evp-fail-closed-decision-gate Requires both closing verdicts and stable revision, manifest, and input identities before current-only use.
 */
export const closeAutoMovieProjectState = (input: {
  revision: number;
  manifest: IAutoMovieGeneratedManifest | null;
  manifestReadFailed: boolean;
  buildStatus: IAutoMovieBuildProjectOutput | null;
  problems: readonly IAutoMovieProjectStateProblem[];
  design: IAutoMovieProductionDesignGraph;
  read: {
    revision: () => number;
    compile: () => IAutoMovieBuildProjectOutput;
    design: () => IAutoMovieProductionDesignGraph;
    manifest: () => IAutoMovieGeneratedManifest | null;
  };
}): {
  freshness: IAutoMovieProjectStateFreshness;
  design: IAutoMovieProductionDesignGraph;
} => {
  const problems = [...input.problems];
  const diagnostics: IAutoMovieDiagnostic[] = [];
  const seenDiagnostics = new Set<string>();
  const initialFingerprint = input.buildStatus?.builder.inputFingerprint;
  const manifestFingerprint = input.manifest?.inputFingerprint ?? null;
  const manifestJson = JSON.stringify(input.manifest);
  let currentFingerprint: AutoMovieContentDigest | null = null;
  let compileInvalid = false;
  let design = input.design;
  const includeCompile = (
    result: IAutoMovieBuildProjectOutput,
  ): AutoMovieContentDigest => {
    currentFingerprint = result.builder.inputFingerprint;
    if (result.success === false) compileInvalid = true;
    for (const diagnostic of result.diagnostics) {
      const key = JSON.stringify([
        diagnostic.code,
        diagnostic.category,
        diagnostic.phase,
        diagnostic.target,
        diagnostic.path,
        diagnostic.message,
      ]);
      if (seenDiagnostics.has(key)) continue;
      seenDiagnostics.add(key);
      diagnostics.push({ ...diagnostic });
    }
    return currentFingerprint;
  };
  if (input.buildStatus !== null) includeCompile(input.buildStatus);
  if (
    manifestFingerprint !== null &&
    initialFingerprint !== undefined &&
    manifestFingerprint !== initialFingerprint
  )
    problems.push({
      code: "compile-fingerprint-stale",
      path: null,
      message: `Loaded compile fingerprint ${manifestFingerprint} is stale against current fingerprint ${initialFingerprint}.`,
    });

  try {
    const endingRevisionBefore = input.read.revision();
    const endingFingerprintBefore = includeCompile(input.read.compile());
    design = input.read.design();
    const endingFingerprintAfter = includeCompile(input.read.compile());
    const endingManifest = input.read.manifest();
    const endingRevisionAfter = input.read.revision();
    if (
      endingRevisionBefore !== input.revision ||
      endingRevisionAfter !== input.revision ||
      JSON.stringify(endingManifest) !== manifestJson ||
      endingFingerprintBefore !== endingFingerprintAfter ||
      endingFingerprintAfter !== initialFingerprint
    )
      problems.push({
        code: "project-state-changed",
        path: null,
        message:
          "Project revision, generated ownership, or builder input changed while state was loading. Retry against one stable repository snapshot.",
      });
  } catch (error) {
    problems.push({
      code: "project-state-changed",
      path: null,
      message: error instanceof Error ? error.message : String(error),
    });
  }
  if (compileInvalid)
    problems.push({
      code: "current-compile-invalid",
      path: null,
      message:
        "Current design, source, declared content, or generated ownership does not pass read-only source compilation. Inspect freshness.diagnostics and run the scaffold compile command after correction.",
    });

  return {
    freshness: {
      status:
        input.manifest === null && input.manifestReadFailed === false
          ? "missing"
          : problems.length === 0
            ? "current"
            : "stale",
      compileFingerprint: manifestFingerprint,
      currentFingerprint,
      diagnostics,
      problems,
    },
    design,
  };
};
