// GENERATED by build/sync-versions.mjs from the workspace. Do not edit by hand.
// Bump the package versions / catalog and re-run `pnpm run build:versions`.

/** Dependency versions baked into the scaffold, kept in sync with this repo. */
export const AUTOMOVIE_TEMPLATE_VERSIONS: Record<string, string> = {
  engine: "^0.1.0",
  interface: "^0.1.0",
  mcp: "^0.1.0",
  nodeTypes: "^22.19.17",
  ttsc: "^0.19.2",
  ttscLint: "^0.19.2",
  typescript: "^7.0.2",
};
