import { type ITtscEvidenceGraphConfig, evidence } from "@ttsc/evidence";
import type { ITtscLintConfig } from "@ttsc/lint";

const SYMBOLS: Array<"type" | "function" | "property"> = [
  "type",
  "function",
  "property",
];

interface IEvidenceGroup {
  name: string;
  sources: string[];
  requirements: string[];
  specifications: string[];
}

/**
 * Each claim is limited to an engine computation or invariant boundary. The
 * exact document lists deliberately leave user choice, provider adoption, and
 * publication authority with their owning packages.
 */
const groups: IEvidenceGroup[] = [
  {
    name: "building and interior physical invariants",
    sources: [
      "src/analysis/hygrothermalAnalysis.ts",
      "src/architecture/builtEnvironment.ts",
      "src/architecture/materialAssembly.ts",
      "src/architecture/planarGeometry.ts",
      "src/architecture/surfacePattern.ts",
      "src/service/**/*.ts",
      "src/validation/validateSceneEnvironment.ts",
    ],
    requirements: [
      "requirements/building-exterior/README.md",
      "requirements/building-exterior/coordinates-and-shared-boundaries.md",
      "requirements/building-exterior/external-circulation-and-attached-elements.md",
      "requirements/building-exterior/facades-and-walls.md",
      "requirements/building-exterior/massing-area-and-height.md",
      "requirements/building-exterior/materials-and-assemblies.md",
      "requirements/building-exterior/openings-and-fenestration.md",
      "requirements/building-exterior/patterns-and-instances.md",
      "requirements/building-exterior/representations-lod-and-fidelity.md",
      "requirements/building-exterior/roofs-and-rooftops.md",
      "requirements/building-exterior/services-and-envelope-interfaces.md",
      "requirements/building-exterior/storeys-levels-and-heights.md",
      "requirements/building-exterior/structure-and-envelope.md",
      "requirements/building-exterior/validation-and-interior-consistency.md",
      "requirements/building-exterior/weather-drainage-and-temporal-state.md",
      "requirements/interior/README.md",
      "requirements/interior/ceilings-and-overhead-zones.md",
      "requirements/interior/columns-beams-and-architectural-elements.md",
      "requirements/interior/connections-and-circulation.md",
      "requirements/interior/doors-windows-and-openings.md",
      "requirements/interior/floors-and-raised-floors.md",
      "requirements/interior/grain-seams-and-continuity.md",
      "requirements/interior/groups-instances-and-repetition.md",
      "requirements/interior/joints-edges-and-transitions.md",
      "requirements/interior/materials-and-physical-properties.md",
      "requirements/interior/services-and-environment.md",
      "requirements/interior/spaces-and-occupancy.md",
      "requirements/interior/spatial-hierarchy-and-zones.md",
      "requirements/interior/surface-assemblies.md",
      "requirements/interior/textures-patterns-and-variation.md",
      "requirements/interior/tolerances-and-imperfections.md",
      "requirements/interior/validation-and-iteration.md",
      "requirements/interior/walls-partitions-and-linings.md",
      "requirements/interior/wet-areas-and-waterproofing.md",
    ],
    specifications: [
      "specifications/building-envelope/README.md",
      "specifications/building-envelope/exterior-spaces-circulation-and-optics.md",
      "specifications/building-envelope/facade-roof-and-openings.md",
      "specifications/building-envelope/linked-interior-coordination.md",
      "specifications/building-envelope/massing-area-and-storeys.md",
      "specifications/building-envelope/representation-lod-and-fidelity.md",
      "specifications/building-envelope/services-water-weather-and-site.md",
      "specifications/building-envelope/structure-envelope-and-materials.md",
      "specifications/interior-space/README.md",
      "specifications/interior-space/boundaries-openings-and-circulation.md",
      "specifications/interior-space/materials-style-and-art.md",
      "specifications/interior-space/patterns-tolerances-and-aging.md",
      "specifications/interior-space/services-wet-and-fluid.md",
      "specifications/interior-space/space-level-zone-topology.md",
      "specifications/interior-space/surface-assemblies.md",
    ],
  },
  {
    name: "selected design identity and lineage",
    sources: [
      "src/architecture/designLineage.ts",
      "src/architecture/designReference.ts",
    ],
    requirements: [
      "requirements/asset-authoring/README.md",
      "requirements/asset-authoring/external-assets.md",
      "requirements/asset-authoring/identity-and-instances.md",
      "requirements/building-exterior/README.md",
      "requirements/building-exterior/existing-phases-and-alternatives.md",
      "requirements/building-exterior/external-assets-and-placement.md",
      "requirements/interior/README.md",
      "requirements/interior/existing-conditions-phases-and-alternatives.md",
      "requirements/interior/external-assets-and-placement.md",
    ],
    specifications: [
      "specifications/asset-and-representation/README.md",
      "specifications/asset-and-representation/identity-resources-and-lifecycle.md",
      "specifications/building-envelope/README.md",
      "specifications/building-envelope/external-assets-patterns-and-instances.md",
      "specifications/building-envelope/phases-deliverables-and-validation.md",
      "specifications/interior-space/README.md",
      "specifications/interior-space/construction-phases-and-alternatives.md",
      "specifications/interior-space/external-assets-and-groups.md",
    ],
  },
  {
    name: "analysis result and diagnostic computation",
    sources: ["src/analysis/analysisRun.ts", "src/validation/violation.ts"],
    requirements: [
      "requirements/diagnostics/README.md",
      "requirements/diagnostics/budgets-and-limits.md",
      "requirements/diagnostics/collection-fail-fast-and-determinism.md",
      "requirements/diagnostics/input-and-result-classification.md",
      "requirements/diagnostics/partial-artifacts-and-recovery.md",
    ],
    specifications: [
      "specifications/validation-and-diagnostics/README.md",
      "specifications/validation-and-diagnostics/budget-and-truncation.md",
      "specifications/validation-and-diagnostics/classification-and-causality.md",
      "specifications/validation-and-diagnostics/collection-order-and-termination.md",
      "specifications/validation-and-diagnostics/partial-artifacts-and-refusal.md",
    ],
  },
  {
    name: "actor pose and face compatibility",
    sources: [
      "src/face/**/*.ts",
      "src/validation/validateFace.ts",
      "src/validation/validateExpression.ts",
    ],
    requirements: [
      "requirements/actors/README.md",
      "requirements/actors/pose-expression-and-gaze.md",
      "requirements/actors/representation-tiers-and-fidelity-boundary.md",
      "requirements/actors/validation.md",
    ],
    specifications: [
      "specifications/asset-and-representation/README.md",
      "specifications/asset-and-representation/fidelity-and-validation.md",
      "specifications/performance-motion-and-staging/README.md",
      "specifications/performance-motion-and-staging/actor-identity-state-and-fidelity.md",
    ],
  },
  {
    name: "world geometry and traversal computation",
    sources: ["src/worldKit.ts"],
    requirements: [
      "requirements/map/README.md",
      "requirements/map/geology-and-ground-surfaces.md",
      "requirements/map/movement-and-visibility.md",
      "requirements/map/roads-and-paths.md",
      "requirements/map/scope-and-coordinates.md",
      "requirements/map/terrain-and-landforms.md",
    ],
    specifications: [
      "specifications/world-and-site/README.md",
      "specifications/world-and-site/spatial-reference-and-identity.md",
      "specifications/world-and-site/terrain-ground-and-geology.md",
      "specifications/world-and-site/traversal-and-visibility.md",
    ],
  },
  {
    name: "asset geometry and numeric invariants",
    sources: [
      "src/drawing/**/*.ts",
      "src/geometry/**/*.ts",
      "src/space/**/*.ts",
      "src/validation/artifactShape.ts",
      "src/validation/capsuleProxy.ts",
      "src/validation/readImageFacts.ts",
      "src/validation/validateMaterialParity.ts",
      "src/validation/validateMeshTopology.ts",
      "src/validation/validateModel.ts",
      "src/validation/validateProfileCapabilities.ts",
      "src/validation/validateSelfIntersection.ts",
      "src/validation/validateTextureAssets.ts",
      "src/validation/validateTransformScalars.ts",
    ],
    requirements: [
      "requirements/asset-authoring/README.md",
      "requirements/asset-authoring/geometry.md",
      "requirements/asset-authoring/representations-bounds-and-lod.md",
      "requirements/asset-authoring/validation.md",
    ],
    specifications: [
      "specifications/asset-and-representation/README.md",
      "specifications/asset-and-representation/bounds-proxies-and-lod.md",
      "specifications/asset-and-representation/fidelity-and-validation.md",
      "specifications/asset-and-representation/model-geometry-and-surface-facts.md",
    ],
  },
  {
    name: "camera and lighting computation",
    sources: [
      "src/analysis/daylightAnalysis.ts",
      "src/analysis/environmentContext.ts",
      "src/film/cameraMove.ts",
      "src/film/cameraProjection.ts",
      "src/film/productionLighting.ts",
      "src/resolve/lightChannel.ts",
      "src/resolve/resolveShotLighting.ts",
    ],
    requirements: [
      "requirements/camera/README.md",
      "requirements/camera/axis-eyeline-and-screen-direction.md",
      "requirements/camera/clipping-occlusion-and-spatial-constraints.md",
      "requirements/camera/continuity-and-intentional-violations.md",
      "requirements/camera/framing-and-shot-size.md",
      "requirements/camera/position-and-movement.md",
      "requirements/camera/projection-lens-and-sensor.md",
      "requirements/camera/scope-and-identity.md",
      "requirements/camera/targets-focus-and-depth-boundary.md",
      "requirements/camera/validation.md",
      "requirements/lighting/README.md",
      "requirements/lighting/analysis-and-visual-validation.md",
      "requirements/lighting/budgets-and-representation.md",
      "requirements/lighting/practicals-and-local-lights.md",
      "requirements/lighting/scope-and-identity.md",
      "requirements/lighting/shadows-reflections-and-transmission.md",
      "requirements/lighting/shape-filters-and-linking.md",
      "requirements/lighting/sources-and-photometry.md",
      "requirements/lighting/sun-sky-and-environment.md",
      "requirements/lighting/temporal-state-and-continuity.md",
    ],
    specifications: [
      "specifications/camera-light-and-visibility/README.md",
      "specifications/camera-light-and-visibility/camera-state-projection-and-gate.md",
      "specifications/camera-light-and-visibility/framing-axis-and-camera-path.md",
      "specifications/camera-light-and-visibility/light-source-photometry-and-environment.md",
      "specifications/camera-light-and-visibility/light-transport-color-and-budget.md",
      "specifications/camera-light-and-visibility/practical-shaping-and-linking.md",
      "specifications/camera-light-and-visibility/target-focus-exposure-and-sampling.md",
      "specifications/camera-light-and-visibility/temporal-state-and-continuity.md",
      "specifications/camera-light-and-visibility/visibility-and-image-space-observation.md",
    ],
  },
  {
    name: "formation layout and resolution",
    sources: [
      "src/formation.ts",
      "src/formationCadence.ts",
      "src/formationSlot.ts",
    ],
    requirements: [
      "requirements/formations/README.md",
      "requirements/formations/budgets-and-validation.md",
      "requirements/formations/heroes-variation-and-state.md",
      "requirements/formations/hierarchies-and-units.md",
      "requirements/formations/layouts-and-slots.md",
      "requirements/formations/reform-and-group-motion.md",
      "requirements/formations/resolution-culling-and-evidence.md",
      "requirements/formations/scope-and-identity.md",
      "requirements/formations/terrain-and-routes.md",
    ],
    specifications: [
      "specifications/performance-motion-and-staging/README.md",
      "specifications/performance-motion-and-staging/formation-identity-layout-and-terrain.md",
      "specifications/performance-motion-and-staging/formation-motion-resolution-and-budgets.md",
    ],
  },
  {
    name: "motion kinematics and pose resolution",
    sources: [
      "src/kinematics/**/*.ts",
      "src/math/Matrix4.ts",
      "src/math/Quaternion.ts",
      "src/math/Vector3.ts",
      "src/math/bisect.ts",
      "src/math/hull.ts",
      "src/math/random.ts",
      "src/math/rotationBetween.ts",
      "src/math/segments.ts",
      "src/motion/**/*.ts",
      "src/perform/**/*.ts",
      "src/resolve/**/*.ts",
      "src/rom/**/*.ts",
      "src/text/compareCodeUnits.ts",
      "src/validation/clipTrackShape.ts",
      "src/validation/fkReachableBones.ts",
      "src/validation/validateBalanceSupport.ts",
      "src/validation/validateBodyCollision.ts",
      "src/validation/validateExpression.ts",
      "src/validation/validateFootSkate.ts",
      "src/validation/validateFreeFall.ts",
      "src/validation/validateGroundContact.ts",
      "src/validation/validateMotion.ts",
      "src/validation/validatePose.ts",
      "src/validation/validateSupport.ts",
    ],
    requirements: [
      "requirements/motion/README.md",
      "requirements/motion/channels-controls-and-drivers.md",
      "requirements/motion/clips-keyframes-and-interpolation.md",
      "requirements/motion/constraints-and-inverse-kinematics.md",
      "requirements/motion/contact-weight-and-support.md",
      "requirements/motion/layers-blends-and-transitions.md",
      "requirements/motion/object-motion-and-interaction.md",
      "requirements/motion/procedural-motion-and-gaits.md",
      "requirements/motion/retargeting-and-scale.md",
      "requirements/motion/root-motion-and-trajectories.md",
      "requirements/motion/scope-and-identity.md",
      "requirements/motion/secondary-motion.md",
      "requirements/motion/timing-and-semantic-events.md",
      "requirements/motion/validation-and-determinism.md",
    ],
    specifications: [
      "specifications/performance-motion-and-staging/README.md",
      "specifications/performance-motion-and-staging/kinematics-contact-and-interaction.md",
      "specifications/performance-motion-and-staging/motion-sampling-and-composition.md",
      "specifications/performance-motion-and-staging/rig-deformation-and-retargeting.md",
    ],
  },
  {
    name: "staging state and deterministic playback",
    sources: [
      "src/film/beatEndSim.ts",
      "src/film/blockBeat.ts",
      "src/film/compileAttach.ts",
      "src/film/compileLaunch.ts",
      "src/film/coupleObjects.ts",
      "src/film/cutSequence.ts",
      "src/film/defineShot.ts",
      "src/film/filmGrammar.ts",
      "src/film/followClip.ts",
      "src/film/forgeCast.ts",
      "src/film/forgeProp.ts",
      "src/film/handoffEvents.ts",
      "src/film/objectMotionGate.ts",
      "src/film/performShot.ts",
      "src/film/playback.ts",
      "src/film/propPlacement.ts",
      "src/film/readSlateContext.ts",
      "src/film/realizeShotContract.ts",
      "src/film/resolveBeatEnd.ts",
      "src/film/resolvePoseKeypoints.ts",
      "src/film/reviewShot.ts",
      "src/film/reviewVisualRead.ts",
      "src/film/scriptGraph.ts",
      "src/film/stageScene.ts",
      "src/film/storyClock.ts",
      "src/film/subjectExtent.ts",
      "src/subject.ts",
      "src/validation/validateContinuity.ts",
      "src/validation/validateScriptTree.ts",
      "src/validation/validateShotArtifact.ts",
      "src/validation/validateSpace.ts",
    ],
    requirements: [
      "requirements/staging/README.md",
      "requirements/staging/budgets-safety-and-validation.md",
      "requirements/staging/coverage-and-alternative-takes.md",
      "requirements/staging/events-and-timing.md",
      "requirements/staging/interactions-and-choreography.md",
      "requirements/staging/marks-zones-and-blocking.md",
      "requirements/staging/scope-and-source-of-truth.md",
      "requirements/staging/shot-contracts-and-deliveries.md",
      "requirements/staging/state-handoff-and-continuity.md",
      "requirements/staging/subjects-and-object-staging.md",
      "requirements/staging/visibility-and-readability.md",
    ],
    specifications: [
      "specifications/performance-motion-and-staging/README.md",
      "specifications/performance-motion-and-staging/staging-events-coverage-and-validation.md",
      "specifications/performance-motion-and-staging/staging-space-state-and-choreography.md",
    ],
  },
  {
    name: "bounded simulation solvers",
    sources: [
      "src/effect.ts",
      "src/fluid/**/*.ts",
      "src/physics/**/*.ts",
      "src/scene/atmosphere.ts",
      "src/soft/**/*.ts",
    ],
    requirements: [
      "requirements/effects-and-simulation/README.md",
      "requirements/effects-and-simulation/budgets-and-bounded-work.md",
      "requirements/effects-and-simulation/clock-seek-and-determinism.md",
      "requirements/effects-and-simulation/damage-and-destruction-boundary.md",
      "requirements/effects-and-simulation/environment-coupling.md",
      "requirements/effects-and-simulation/fire-smoke-and-atmosphere.md",
      "requirements/effects-and-simulation/fluids-and-water.md",
      "requirements/effects-and-simulation/particles-and-emission.md",
      "requirements/effects-and-simulation/rigid-motion-ballistics-and-collision.md",
      "requirements/effects-and-simulation/scope-and-simulation-tiers.md",
      "requirements/effects-and-simulation/soft-bodies-and-deformation.md",
      "requirements/effects-and-simulation/validation-and-evidence.md",
    ],
    specifications: [
      "specifications/simulation-effects-and-sound/README.md",
      "specifications/simulation-effects-and-sound/budget-admission.md",
      "specifications/simulation-effects-and-sound/clocks-ordering-seek-and-checkpoints.md",
      "specifications/simulation-effects-and-sound/fluids-water-and-world-coupling.md",
      "specifications/simulation-effects-and-sound/particles-fire-and-atmosphere.md",
      "specifications/simulation-effects-and-sound/rigid-collision-and-damage.md",
      "specifications/simulation-effects-and-sound/scope-tiers-and-identities.md",
      "specifications/simulation-effects-and-sound/soft-bodies-and-deformation.md",
      "specifications/simulation-effects-and-sound/validation-evidence-and-compatibility.md",
    ],
  },
  {
    name: "sound timing spatialization and mix computation",
    sources: ["src/analysis/acousticAnalysis.ts", "src/sound/**/*.ts"],
    requirements: [
      "requirements/sound/README.md",
      "requirements/sound/ambience-and-sustained-sources.md",
      "requirements/sound/dialogue-voice-and-visemes.md",
      "requirements/sound/editing-synchronization-and-continuity.md",
      "requirements/sound/event-cues-and-timing.md",
      "requirements/sound/foley-and-sound-effects.md",
      "requirements/sound/interior-acoustics.md",
      "requirements/sound/mix-hierarchy-and-loudness.md",
      "requirements/sound/music-and-silence.md",
      "requirements/sound/scope-and-identity.md",
      "requirements/sound/spatialization-and-propagation.md",
      "requirements/sound/validation-and-delivery.md",
    ],
    specifications: [
      "specifications/simulation-effects-and-sound/README.md",
      "specifications/simulation-effects-and-sound/ambience-music-spatial-and-acoustics.md",
      "specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md",
      "specifications/simulation-effects-and-sound/sound-sources-events-dialogue-and-foley.md",
      "specifications/simulation-effects-and-sound/validation-evidence-and-compatibility.md",
    ],
  },
  {
    name: "render lowering identity and budget computation",
    sources: ["src/productionIdentity.ts", "src/render/**/*.ts"],
    requirements: [
      "requirements/rendering/README.md",
      "requirements/rendering/budgets.md",
      "requirements/rendering/frame-identity-and-content-addressing.md",
      "requirements/rendering/geometry-visibility-and-culling.md",
      "requirements/rendering/materials-lighting-and-color.md",
      "requirements/rendering/passes-channels-and-products.md",
      "requirements/rendering/scene-lowering-and-runtime-state.md",
      "requirements/rendering/scope-and-artifact-identity.md",
      "requirements/rendering/validation.md",
    ],
    specifications: [
      "specifications/editorial-render-and-delivery/README.md",
      "specifications/editorial-render-and-delivery/render-budget-identity-and-recovery.md",
      "specifications/editorial-render-and-delivery/render-products-visibility-and-color.md",
      "specifications/editorial-render-and-delivery/render-schedule-state-and-headless.md",
    ],
  },
];

const graph: ITtscEvidenceGraphConfig = {
  claims: groups.flatMap((group) => [
    {
      name: `${group.name} exports implement requirements`,
      type: "typescript" as const,
      files: group.sources,
      symbol: SYMBOLS,
      reference: {
        type: "markdown" as const,
        root: "../../docs",
        files: group.requirements,
        symbol: ["h2", "h3"],
      },
    },
    {
      name: `${group.name} exports implement specifications`,
      type: "typescript" as const,
      files: group.sources,
      symbol: SYMBOLS,
      reference: {
        type: "markdown" as const,
        root: "../../docs",
        files: group.specifications,
        symbol: ["h2", "h3"],
      },
    },
  ]),
};

export default {
  extends: "../../config/lint.config.ts",
  plugins: { evidence },
  rules: {
    "evidence/documented": ["error", { symbol: SYMBOLS }],
    "evidence/graph": ["error", graph],
    "evidence/todo": "error",
  },
} satisfies ITtscLintConfig;
