import { IAutoMovieProfile } from "../core/IAutoMovieProfile";
import { IAutoMovieMaterial } from "../material/IAutoMovieMaterial";
import { AutoMovieHumanoidBone } from "../skeleton/AutoMovieHumanoidBone";
import { IAutoMovieSkeleton } from "../skeleton/IAutoMovieSkeleton";
import { AutoMovieAssetOrigin } from "./AutoMovieAssetOrigin";
import { IAutoMovieAffordance } from "./IAutoMovieAffordance";
import { IAutoMovieBody } from "./IAutoMovieBody";
import { IAutoMovieModelPart } from "./IAutoMovieModelPart";

/**
 * A 3D model: the riggable subject that poses, motions, and expressions drive.
 *
 * This is automovie's central geometry container, and it deliberately unifies
 * the two things the project animates:
 *
 * - A **character** is a model _with_ a humanoid `skeleton`: poses and motions
 *   articulate its bones;
 * - An **object / prop** is a model with `skeleton: null`; it has geometry and
 *   materials but no joints, and is moved as a whole (placed in a scene, or
 *   parented to a character's bone as a held item).
 *
 * A model bundles its geometry (`parts`), its rig (`skeleton`, optional), and
 * its `materials` behind one id; downstream layers cite it by `id` and never
 * need to know whether it was generated from primitives or imported as a mesh
 * (that is `origin`). The LLM authors parts, materials, and the skeleton's ROM
 * (never raw vertex arrays, which arrive only via import).
 *
 * @evidence requirements/asset-authoring/identity-and-instances.md#asset-prototype-instance Exposes `IAutoMovieModel` as the portable data boundary for the asset prototype instance requirement.
 * @evidence specifications/asset-and-representation/alternatives-instances-and-groups.md#asset-spec-prototype-instance Types `IAutoMovieModel` for the asset prototype instance system contract.
 * @author Samchon
 */
export interface IAutoMovieModel {
  /**
   * Stable id; poses, motions, and scene nodes cite the model by this.
   *
   * @evidence requirements/asset-authoring/identity-and-instances.md#asset-prototype-instance Exposes `id` as the portable data boundary for the asset prototype instance requirement.
   * @evidence specifications/asset-and-representation/alternatives-instances-and-groups.md#asset-spec-prototype-instance Types `id` for the asset prototype instance system contract.
   */
  id: string;

  /**
   * Human / LLM readable name. Null if unnamed.
   *
   * @evidence requirements/asset-authoring/identity-and-instances.md#asset-prototype-instance Exposes `name` as the portable data boundary for the asset prototype instance requirement.
   * @evidence specifications/asset-and-representation/alternatives-instances-and-groups.md#asset-spec-prototype-instance Types `name` for the asset prototype instance system contract.
   */
  name: string | null;

  /**
   * Whether the geometry was generated by automovie or imported by the user.
   *
   * @evidence requirements/asset-authoring/external-assets.md#asset-external-gltf-scene Exposes `origin` as the explicit distinction between generated and adopted 3D assets.
   * @evidence specifications/asset-and-representation/alternatives-instances-and-groups.md#asset-spec-external-adoption-alternatives Types `origin` as the selected external-adoption mode.
   */
  origin: AutoMovieAssetOrigin;

  /**
   * The geometry pieces and their material/rig bindings. At least one.
   *
   * @evidence requirements/asset-authoring/geometry.md#asset-primitive-freeform-geometry Exposes `parts` as the model's composition of authored geometry pieces.
   * @evidence specifications/asset-and-representation/model-geometry-and-surface-facts.md#asset-spec-geometry-inputs Types `parts` as explicit model geometry inputs.
   */
  parts: IAutoMovieModelPart[];

  /**
   * The humanoid rig: bones, hierarchy, rest pose, and anatomical ROM. `null`
   * for a non-articulated object/prop. A model with a skeleton is a character;
   * one without is an object.
   *
   * @evidence requirements/actors/skeleton-rig-and-retargeting.md#actor-rest-bind-deformation Exposes `skeleton` as the model's declared rest and deformation rig.
   * @evidence specifications/performance-motion-and-staging/rig-deformation-and-retargeting.md#performance-rig-skin-rigid-morph-deformation Types `skeleton` as the deformation binding basis.
   */
  skeleton: IAutoMovieSkeleton | null;

  /**
   * The physical body: mass, center of mass, friction, restitution. `null` when
   * the model has no declared physics (a static prop or set piece);
   * physical-plausibility feedback is only computed for models with a body.
   *
   * @evidence requirements/effects-and-simulation/rigid-motion-ballistics-and-collision.md#effects-rigid-linear-angular-state Exposes `body` as the model's declared rigid-state parameters.
   * @evidence specifications/simulation-effects-and-sound/rigid-collision-and-damage.md#rigid-trajectory-tier-contract Types `body` as the rigid trajectory input body.
   */
  body: IAutoMovieBody | null;

  /**
   * Semantic contact points the object declares: stackable tops, handles,
   * sockets, hooks ({@link IAutoMovieAffordance}). Optional evolving-schema
   * field (the `space?` / `events?` pattern): absent or `null` means the model
   * declares no affordances, and nothing downstream changes.
   *
   * @evidence requirements/motion/object-motion-and-interaction.md#motion-object-authored-vocabulary Exposes `affordances` as the object's authored interaction vocabulary.
   * @evidence specifications/performance-motion-and-staging/kinematics-contact-and-interaction.md#performance-interaction-attachment-object-handoff Types `affordances` as explicit attachment and interaction handles.
   */
  affordances?: IAutoMovieAffordance[] | null;

  /**
   * Materials referenced by the parts.
   *
   * @evidence requirements/asset-authoring/materials-and-textures.md#asset-material-composition Exposes `materials` as the model's authored material composition.
   * @evidence specifications/asset-and-representation/model-geometry-and-surface-facts.md#asset-spec-material-texture-relations Types `materials` as explicit material and texture relations.
   */
  materials: IAutoMovieMaterial[];

  /**
   * Id of an engine-resolved binary payload (the imported glTF/VRM file backing
   * an `imported` model), or `null` when the geometry is fully described by
   * `parts` (a generated model).
   *
   * @evidence requirements/asset-authoring/external-assets.md#asset-external-resource-closure Exposes `asset` as the identity of the adopted binary resource.
   * @evidence specifications/asset-and-representation/model-geometry-and-surface-facts.md#asset-spec-surface-resource-closure Types `asset` as a member of the model's closed resource set.
   */
  asset: string | null;

  /**
   * Compiler-sealed execution facts for an imported appearance.
   *
   * The viewer loads only this digest closure. Humanoid node indices come from
   * ingest or authoritative VRM metadata, never a runtime name guess.
   *
   * @evidence requirements/asset-authoring/external-assets.md#asset-external-resource-closure Exposes `imported` as the sealed closure of adopted model resources and mappings.
   * @evidence specifications/asset-and-representation/model-geometry-and-surface-facts.md#asset-spec-surface-resource-closure Types `imported` as the model revision's complete imported resource closure.
   */
  imported?: {
    /** Fixed normalization profile proved from the resident model bytes. */
    profile: "gltf-static-v1" | "gltf-humanoid-v1" | "vrm-humanoid-v1";

    /** Exact manifest-owned LOD members in near-to-far order. */
    lod: Array<{
      /** Closed LOD identity. */
      level: "hero" | "near" | "far";

      /** Manifest-owned model path. */
      asset: string;

      /** SHA-256 of the model bytes compiled for this level. */
      digest: `sha256:${string}`;

      /** Fixed normalization profile proved for this level. */
      profile: "gltf-static-v1" | "gltf-humanoid-v1" | "vrm-humanoid-v1";

      /** Level-local authoritative humanoid mapping. */
      humanoidBones: Array<{
        /** Normalized automovie/VRM humanoid slot. */
        bone: AutoMovieHumanoidBone;

        /** Non-negative glTF node index. */
        node: number;

        /** Whether resident skin weights prove visible influence for this bone. */
        weighted: boolean;
      }>;
    }>;

    /** Every model, sidecar and proxy byte identity this binding may request. */
    assets: Array<{
      /** Canonical project-relative path. */
      path: string;

      /** SHA-256 sealed by the builder. */
      digest: `sha256:${string}`;
    }>;

    /** Authoritative normalized humanoid slot to glTF node index mapping. */
    humanoidBones: Array<{
      /** Normalized automovie/VRM humanoid slot. */
      bone: AutoMovieHumanoidBone;

      /** Non-negative glTF node index. */
      node: number;

      /** Whether resident skin weights prove visible influence for this bone. */
      weighted: boolean;
    }>;
  };

  /**
   * Declarative profiles bound to this runtime model.
   *
   * Omitted means the model proves no semantic engine capability. Imported
   * appearance does not inherit traits unless its registered deterministic
   * proxy supplies them.
   *
   * @evidence requirements/agent-authoring/capability-discovery.md#agent-capability-gap-discovery Exposes `profiles` as the model's explicit implemented capabilities.
   * @evidence specifications/authoring-and-authority/capability-and-content-boundary.md#spec-authoring-capability-state Types `profiles` as declared capability state rather than inferred content.
   */
  profiles?: IAutoMovieProfile[];
}
