import { IAutoMovieMeshGeometry } from "./IAutoMovieMeshGeometry";
import { IAutoMoviePrimitiveGeometry } from "./IAutoMoviePrimitiveGeometry";

/**
 * The geometry of one model part: either a compact parametric primitive or
 * explicit triangle data.
 *
 * Discriminated on `type` so the two paths the project cares about are
 * explicit: `primitive` is a bounded recipe with named dimensions, while
 * `mesh` is explicit data that may be imported, baked, or generated by a
 * deterministic named function. Both render to triangles downstream.
 * Provenance belongs to {@link AutoMovieAssetOrigin} at the model level, not
 * to this representation discriminator.
 *
 * @evidence requirements/asset-authoring/geometry.md#asset-primitive-freeform-geometry Exposes `IAutoMovieGeometry` as the portable data boundary for the asset primitive freeform geometry requirement.
 * @evidence specifications/asset-and-representation/model-geometry-and-surface-facts.md#asset-spec-geometry-inputs Types `IAutoMovieGeometry` for the asset spec geometry inputs system contract.
 * @author Samchon
 */
export type IAutoMovieGeometry =
  | IAutoMoviePrimitiveGeometry
  | IAutoMovieMeshGeometry;
