import { IautomovieMaterial } from "../material/IautomovieMaterial";
import { IautomovieSkeleton } from "../skeleton/IautomovieSkeleton";
import { automovieAssetOrigin } from "./AutomovieAssetOrigin";
import { IautomovieModelPart } from "./IautomovieModelPart";

/**
 * A 3D model ??the riggable subject that poses, motions, and expressions drive.
 *
 * This is automovie's central geometry container, and it deliberately unifies
 * the two things the project animates:
 *
 * - A **character** is a model _with_ a humanoid `skeleton` ??poses and motions
 *   articulate its bones;
 * - An **object / prop** is a model with `skeleton: null` ??it has geometry and
 *   materials but no joints, and is moved as a whole (placed in a scene, or
 *   parented to a character's bone as a held item).
 *
 * A model bundles its geometry (`parts`), its rig (`skeleton`, optional), and
 * its `materials` behind one id; downstream layers cite it by `id` and never
 * need to know whether it was generated from primitives or imported as a mesh
 * (that is `origin`). The LLM authors parts, materials, and the skeleton's ROM
 * ??never raw vertex arrays, which arrive only via import.
 *
 * @author Samchon
 */
export interface IautomovieModel {
  /** Stable id; poses, motions, and scene nodes cite the model by this. */
  id: string;

  /** Human / LLM readable name. Null if unnamed. */
  name: string | null;

  /** Whether the geometry was generated by automovie or imported by the user. */
  origin: automovieAssetOrigin;

  /** The geometry pieces and their material/rig bindings. At least one. */
  parts: IautomovieModelPart[];

  /**
   * The humanoid rig: bones, hierarchy, rest pose, and anatomical ROM. `null`
   * for a non-articulated object/prop. A model with a skeleton is a character;
   * one without is an object.
   */
  skeleton: IautomovieSkeleton | null;

  /** Materials referenced by the parts. */
  materials: IautomovieMaterial[];

  /**
   * Id of an engine-resolved binary payload (the imported glTF/VRM file backing
   * an `imported` model), or `null` when the geometry is fully described by
   * `parts` (a generated model).
   */
  asset: string | null;
}
