import type * as Human from "@automovie/human";

/**
 * Current construction-source inspection for the portable body studies.
 *
 * Every public declaration of the body folder was read against the basis it
 * evaluates (`connected-basis/basis.json.gz`), the analytic scenarios under
 * `test/src/features/human-body`, and its consumers. Deterministic replay and
 * source correctness do not accept a body's physiological range or likeness;
 * the census and render observations live beside the payload. Native-issued
 * fingerprints are added only after those inspections.
 *
 * @evidence requirements/actors/body-authoring/contract.md#actor-body-connected-basis The study supplies a licensed neutral body prior and independent compact edits to the evaluator this review reads.
 * @evidence requirements/actors/body-authoring/contract.md#actor-body-joints The study's joints, landmarks and skin weights are what the inspected skeleton and skinning code evaluate.
 * @evidence requirements/actors/body-authoring/contract.md#actor-body-measurements The study's measure channels are the ones the inspected rules price in metres.
 * @evidence requirements/actors/body-authoring/contract.md#actor-body-document The study's documents are loaded and saved through the inspected boundary.
 * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-basis The selected single-surface asset exercises immutable basis compilation, common normals and revision-bound edits.
 * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-joints The selected fifty-two joints exercise the frame rule, sign frames, pose validation and rigid skinning.
 * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-measurements The selected twenty measure channels exercise the girth, distance, height and breadth rules.
 * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-document The study documents exercise the parse and serialize admission and envelope.
 * @evidence requirements/actors/body-authoring/contract.md#actor-body-export The study's built body is what the inspected exporter writes to GLB and glTF.
 * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-export The exported study body exercises the shared Float32 writer without a rig.
 * @evidence requirements/actors/body-authoring/contract.md#actor-body-simple-shape The study's basis is what the simple tier's stature and body mass index are solved against.
 * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-simple-shape The study's ring and skin volume are the measurements the expansion's inversions read.
 * @evidenceExclude requirements/actors/body-authoring/contract.md#actor-body-editor The browser editor is the playground's; the study review inspects the package sources it calls, not the screen.
 * @evidenceExclude specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor-view The study review owns no inputs, presets or display state.
 * @evidenceExclude specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor The study review owns no transaction history or worker.
 * @evidenceExclude requirements/actors/body-authoring/README.md#body-requirements This index spans the editing screen and census review as well; the study review records source inspection, not the complete workflow.
 * @evidenceExclude specifications/asset-and-representation/body-authoring/README.md#body-specifications This index joins evaluation, measurement, document and later editor boundaries; the study review does not own the browser adapter.
 *
 * @evidence {@link Human.IAutoMovieHumanBodyBasis} Read the schema and admission against the shipped CC0 asset: sparse endpoints, shared topology, one exact material partition, landmarks, joints and four-influence skin, and the frame shared with the face at the neck ring.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyBasis} #95d2b2c Read the full schema and admission against the shipped connected asset: collar correspondence, endpoints, material partition, landmarks, skin, the shoulder contract with its joint-sinus envelope, the declared pelvifemoral rhythm and the joints that spread their twist, and the optional per-surface soft-tissue sag. Reread after the skin relief: surfaces may carry an anatomical relief map.
 * @evidence {@link Human.IAutoMovieHumanBodyBasis.id} Read nonblank identity admission and the builder's exact document-to-basis binding.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyBasis.id} #b74616d Read nonblank identity admission and the builder's exact document-to-basis binding.
 * @evidence {@link Human.IAutoMovieHumanBodyBasis.channels} Read finite neutral-containing ranges, reciprocal same-group mirrors, distinct signed endpoint selection and ordered accumulation.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyBasis.channels} #f250ee5 Read finite neutral-containing ranges, reciprocal same-group mirrors, distinct signed endpoint selection and ordered accumulation.
 * @evidence {@link Human.IAutoMovieHumanBodyBasis.correctives} Read driver-side admission, the (0,1] gain and the product activation the shipped macro pair residuals fire under.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyBasis.correctives} #6d51fa8 Read the channel, generic joint and shoulder-orientation kernel drivers, including the total elevation ramp and SO(3) angular window whose activity is invariant under equivalent TT pole coordinates.
 * @evidence {@link Human.IAutoMovieHumanBodyBasis.landmarks} Read the named point set, its finite positions and the sparse rows that move a joint with the shape it sits in.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyBasis.landmarks} #1043e03 Read the named point set, its finite positions and the sparse rows that move a joint with the shape it sits in.
 * @evidence {@link Human.IAutoMovieHumanBodyBasis.joints} Read the rooted parent-first tree, landmark ends, unit flexion reference, measured signs on exactly the mobile axes and rest-containing ranges.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyBasis.joints} #e6d3787 Read the rooted tree, landmark pivots, held generic upper-arm axes, measured bilateral thorax-TT rest, elevation and axial ranges, the periodic plane envelope, the optional twist spread along a bone to its one child, and four-influence skin binding.
 * @evidence {@link Human.IAutoMovieHumanBodyBasis.surfaces} Read topology admission, sparse vertex ordering, nonzero differences, oriented triangle partition, unit-sum skin and common normals before UV separation.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyBasis.surfaces} #c7e01f3 Read topology admission, sparse vertex ordering, nonzero differences, oriented triangle partition, unit-sum skin and common normals before UV separation; the optional sag's lean channel weights, gain, sweeps and softness. Reread after the skin relief: a surface's optional anatomical relief, a tangent-space PNG data URI normal map over its UV layout for a material's regions.
 * @evidence {@link Human.IAutoMovieHumanBodyBasis.materials} Read unique resident identities, copied overrides and final model admission.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyBasis.materials} #fe91223 Read unique resident identities, copied overrides and final model admission.
 * @evidence {@link Human.IAutoMovieHumanBodyBasisDocument} Read the compact schema admission for named shape, pose and material edits over one exact basis revision, with omissions meaning neutral or rest.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyBasisDocument} #dee66d4 Read exact compact schema admission for named shape, non-humeral clinical pose, separate thorax-relative shoulder goals, the optional cheek albedo the skin is coloured by site from, and materials under one basis revision, and the optional skin detail strength. Reread after the skin tone: the optional `skinTone` strength in [0,1], the chromophore tone map about the site colour with the base colour compensated.
 * @evidence {@link Human.IAutoMovieHumanBodyShoulderPose} Read the complete thorax-relative humeral goal, its plane period, total elevation, independent axial rotation and the two non-unique poles.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyShoulderPose} #f9193d6 Read its four exact fields, the builder's separate shoulder admission and the analytic left/right pole tests; the published r4 basis remains deliberately incompatible.
 * @evidence {@link Human.IAutoMovieHumanBodyShoulderPose.bone} Read explicit left/right humerus ownership rather than inferring a side from an angle sign.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyShoulderPose.bone} #9f44a49 Read the two allowed upper-arm names and the document's duplicate-bone refusal.
 * @evidence {@link Human.IAutoMovieHumanBodyShoulderPose.plane} Read the side-relative lateral zero, anterior positive plane and [-180,180) period.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyShoulderPose.plane} #c8da648 Read the side-relative sign in the TT quaternion and the parse boundary's excluded 180 endpoint against bilateral direction tests.
 * @evidence {@link Human.IAutoMovieHumanBodyShoulderPose.elevation} Read total humerothoracic elevation from the anatomical hanging zero, independent of the coupled girdle.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyShoulderPose.elevation} #5128dd2 Read the direct 0/90/180 direction oracles and the goal test where the girdle moves but the authored overhead direction remains overhead.
 * @evidence {@link Human.IAutoMovieHumanBodyShoulderPose.axialRotation} Read positive external rotation about the final humeral axis and its distinction from the plane choice.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyShoulderPose.axialRotation} #2bac298 Read the final-axis torsion in both arms, the hanging-pole orientation test and the equivalent 180-pole coordinates.
 * @evidence {@link Human.IAutoMovieHumanBodyBasisDocument.id} Read nonblank identity admission and preservation into the resident model.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyBasisDocument.id} #0c127d8 Read nonblank identity admission and preservation into the resident model.
 * @evidence {@link Human.IAutoMovieHumanBodyBasisDocument.name} Read nonblank display identity admission and preservation into the model.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyBasisDocument.name} #fa29c9c Read nonblank display identity admission and preservation into the model.
 * @evidence {@link Human.IAutoMovieHumanBodyBasisDocument.basis} Read exact compiled-basis matching without implicit conversion or migration.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyBasisDocument.basis} #774c47e Read exact compiled-basis matching without implicit conversion or migration.
 * @evidence {@link Human.IAutoMovieHumanBodyBasisDocument.shape} Read channel-membership and envelope validation, neutral omission and signed endpoint weights without clamping.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyBasisDocument.shape} #5bb3094 Read channel-membership and envelope validation, neutral omission and signed endpoint weights without clamping.
 * @evidence {@link Human.IAutoMovieHumanBodyBasisDocument.pose} Read the sparse unique-bone clinical pose, its validation against each joint's range and rest as omission.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyBasisDocument.pose} #17d7b3e Read the sparse unique-bone clinical pose, its validation against each joint's range and rest as omission.
 * @evidence {@link Human.IAutoMovieHumanBodyBasisDocument.materials} Read resident-ID validation, optional RGB/roughness boundaries and material copying.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyBasisDocument.materials} #8fd4fc3 Read resident-ID validation, optional RGB/roughness boundaries and material copying.
 * @evidence {@link Human.IAutoMovieHumanBodyBuild} Read the posed static model beside the rest skeleton, per-bone rest and posed transforms and shaped landmarks the verification tools consume.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyBuild} #c0b12c5 Read the posed static model beside the rest skeleton, per-bone rest and posed transforms and shaped landmarks the verification tools consume.
 * @evidence {@link Human.IAutoMovieHumanBodyBuild.model} Read the skinless, skeletonless posed model that the static exporter admits unchanged.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyBuild.model} #d02fb66 Read the skinless, skeletonless posed model that the static exporter admits unchanged.
 * @evidence {@link Human.IAutoMovieHumanBodyBuild.skeleton} Read the rest skeleton of the shaped body, before the document's pose.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyBuild.skeleton} #146537e Read the rest skeleton of the shaped body, before the document's pose.
 * @evidence {@link Human.IAutoMovieHumanBodyBuild.bones} Read the per-joint rest and posed world transforms in basis order, which the arc scenarios compare against hand rotations.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyBuild.bones} #5ebd862 Read the per-joint rest and posed world transforms in basis order, which the arc scenarios compare against hand rotations.
 * @evidence {@link Human.IAutoMovieHumanBodyBuild.landmarks} Read the shaped landmark positions after channels and correctives, before any pose.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyBuild.landmarks} #a046ade Read the shaped landmark positions after channels and correctives, before any pose.
 * @evidence {@link Human.IAutoMovieHumanBodyChannelScale} Read the per-endpoint RMS, peak and count beside the optional measurement record and its null-valued unmeasurable case.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyChannelScale} #e14f3ad Read the per-endpoint RMS, peak and count beside the optional measurement record and its null-valued unmeasurable case.
 * @evidence {@link Human.IAutoMovieHumanBodyChannelScale.id} Read the channel identity the scale reports for.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyChannelScale.id} #1edafd4 Read the channel identity the scale reports for.
 * @evidence {@link Human.IAutoMovieHumanBodyChannelScale.group} Read the source group copied for grouping without a second lookup.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyChannelScale.group} #28e2634 Read the source group copied for grouping without a second lookup.
 * @evidence {@link Human.IAutoMovieHumanBodyChannelScale.positive} Read the positive endpoint's whole-surface RMS, peak and moved count.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyChannelScale.positive} #90c399f Read the positive endpoint's whole-surface RMS, peak and moved count.
 * @evidence {@link Human.IAutoMovieHumanBodyChannelScale.negative} Read the negative endpoint's figures or null for a nonnegative control.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyChannelScale.negative} #2a8fe79 Read the negative endpoint's figures or null for a nonnegative control.
 * @evidence {@link Human.IAutoMovieHumanBodyChannelScale.measurement} Read the rule identity, kind and neutral, positive and negative metre values, null when no rule is bound or the surface cannot answer.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyChannelScale.measurement} #c91b7c5 Read the rule identity, kind and neutral, positive and negative metre values, null when no rule is bound or the surface cannot answer.
 * @evidence {@link Human.IAutoMovieHumanBodyMeasurement} Read the three rule kinds and the landmark, plane, sampling and extremum parameters each carries.
 * @evidenceReview {@link Human.IAutoMovieHumanBodyMeasurement} #0adc6f6 Read the three rule kinds and the landmark, plane, sampling and extremum parameters each carries, and the girth placed at a skin landmark instead: one plane through a vertex of a named basis surface, with no sampled fractions or extremum. Reread after the hip level: a band may also pick the station whose loop reaches furthest back.
 * @evidence {@link Human.HUMAN_BODY_MEASUREMENTS} Read each rule against the shipped landmarks and the public measurement definition it approximates, and the neck channels left without a rule.
 * @evidenceReview {@link Human.HUMAN_BODY_MEASUREMENTS} #2ad7ed4 Read each rule against the shipped landmarks and the public measurement definition it approximates, and the neck channels left without a rule. Reread after the limb tapes: the upper arm girth is taken from the midpoint toward the elbow (ISO 8559-1, ANSUR), since nearer the shoulder a heavy or muscular arm's plane cut the arm and trunk as one loop (1.27 to 1.90 m read on 70 to 130 kg bodies). Reread after the bust level: the bust is the horizontal girth through the left nipple-areola fill's centre (basis vertex 21898), where ISO 8559-1 and ANSUR take it; the band it replaced stopped at three fifths of the mid-to-upper thoracic span and read a lean man's chest 5 to 11 cm small, his nipple standing at 0.87 to 0.92 of it. Reread after the hip level: the hip girth is taken on the station whose loop reaches furthest back, where ANSUR takes the buttock circumference; the largest girth stood 4 cm low on a woman in the rest pose, around the spread tops of both thighs.
 * @evidence {@link Human.assertHumanBodyBasis} Read identity, envelope, mirror, corrective, topology, sparse-row, partition and endpoint-population admission, then the rig hand-off.
 * @evidenceReview {@link Human.assertHumanBodyBasis} #1eb8cfb Read identity/envelope/corrective admission, oriented surface and endpoint population, independent boundary caps and disjoint capped interiors, then the rig hand-off; the sag's lean channels declared and in range, a finite nonnegative gain, whole sweeps and a finite softness over declared channels. Reread after the skin relief: a relief must be a PNG data URI over a textured region of its material.
 * @evidence {@link Human.assertHumanBodyRig} Read landmark, tree-order, reference, sign-versus-constraint, range and skin admission against the shipped rig and the analytic negatives.
 * @evidenceReview {@link Human.assertHumanBodyRig} #5a38b66 Read tree, a twist spread only as a boolean on a bone with one child joint, measured bilateral thorax-TT rest, envelope knot order, canonical planes, positive in-range maxima and a rest inside the region, held old upper-arm axes, source-relative corrective ramps and orientation kernels whose centres lie in the reach, coupling limits, the pelvifemoral hand-off, and unit-sum skin.
 * @evidence {@link Human.assertSparseRows} Read the one row format every endpoint and landmark payload shares and the labelled refusals.
 * @evidenceReview {@link Human.assertSparseRows} #13a6ac2 Read the one row format every endpoint and landmark payload shares and the labelled refusals.
 * @evidence {@link Human.createHumanBodyBasisBuilder} Read schema admission, immutable compilation, the fixed evaluation order, pose validation through the engine, rigid skinning, normal reconstruction and final model validation.
 * @evidenceReview {@link Human.createHumanBodyBasisBuilder} #5e3d93d Read schema/revision admission, named shape and corrective evaluation, the coupled pose judged together with its pelvic-relative rhythm reading, shoulder goals refused outside the joint-sinus reach and resolved after girdle motion, the pelvis turned about the hip centres, skinning with the basis joint order, the skin coloured by site from a cheek (refused beside a skin colour override, without a skin material or outside (0,1], the sites read once on first use), and final model validation; the skin detail's normal map on the skin material, source UVs repeated at the layout's median scale over the tile, its scale the strength times the age curve, refused outside [0,1], without UVs or without the skin material; the declared sag over the document's rest and lean shapes, with gravity's change read by skinning a point a centimetre below each vertex, skipped at the rest pose. Reread after the skin tone: a `skinTone` strength, refused outside [0,1], without the skin material or on untextured skin regions, attaches the chromophore tone map as the skin's sRGB base-colour texture over the source UVs at the layout scale, at the strength times the age curve taken to a twentieth and cached by it, and multiplies the base colour by the map's compensation. Reread after the skin scattering: the skin material, where the basis has it, carries the measured subsurface radius on every build. Reread after the skin relief: with a surface relief for the skin, the skin detail binds it as the normal map, once over the UVs and clamped, and moves the tiled micro-relief to the detail normal map, both at the strength times the age curve; without one the micro-relief stays the normal map.
 * @evidence {@link Human.evaluateHumanBodyShape} Read `|weight| x endpoint`, then activation-scaled correctives, applied to surfaces and landmarks by endpoint name on fresh copies.
 * @evidenceReview {@link Human.evaluateHumanBodyShape} #a72f452 Read named `|weight| x endpoint` rows then activation-scaled correctives on fresh surface and landmark copies; the independent per-vertex document displacement is gone.
 * @evidence {@link Human.humanBodyBasisWeights} Read envelope and membership refusals and the product corrective activation shared by builder and measurement.
 * @evidenceReview {@link Human.humanBodyBasisWeights} #5fc7596 Read channel envelopes, coupled generic pose, total TT elevation ramp, the SO(3) geodesic shoulder kernel that agrees for equivalent 0/180 pole triples, the division of one family's kernels by their sum where it exceeds one, and the same division of one pose's shape examples (the channel sets its shape-and-pose correctives read, each at its largest channel-ramp product).
 * @evidence {@link Human.resolveHumanBodySkeleton} Read the `Y x F` frame, the Shepperd quaternion, the parent-relative rest transform and the sign rest frames, against the analytic frame scenarios.
 * @evidenceReview {@link Human.resolveHumanBodySkeleton} #44d21bf Read the `Y x F` frame, the Shepperd quaternion, the parent-relative rest transform and the sign rest frames, against the analytic frame scenarios. Reread after the rest angle: every axis frame now carries `{sign, neutral}` so the engine turns the rig by `(clinical - neutral) / sign`, checked by the offset scenario (a spine resting at 30 degrees stays put at 30 and swings back at 0).
 * @evidence {@link Human.createHumanBodySkinColour} Read the site weights off the skin (hand bones split by the normal along their flexion reference, feet by the normal against up, forearm, shank, neck and the protected rest), their diffusion, the clamped fits, the collar smoothstep from the open ring, and the base-and-multiplier split.
 * @evidenceReview {@link Human.createHumanBodySkinColour} #9d5f1ab Read the site weights off the skin (hand bones split by the normal along their skin-weighted flexion reference, feet by the normal against up and half exposed on top, forearm exposed, shank by its share, neck and head, the protected rest), the half-step diffusion, the power fits capped at 1, the collar smoothstep in the neutral distance to the open ring, and the base of each channel's largest albedo with multipliers in (0, 1]; ran the site, clamp, diffusion, collar, builder and refusal scenarios.
 * @evidence {@link Human.HUMAN_BODY_SKIN_SITES} Read each site's power fits against the skin-sites receipt's group-mean fits of the archive and the site assignment's weights.
 * @evidenceReview {@link Human.HUMAN_BODY_SKIN_SITES} #0037bed Read each site's power fits `exp(a) · cheek^b` against the skin-sites receipt's log-log fits over the International Skin Spectra Archive's group-and-sex means (inner arm, outer arm, neck, back of hand, palm; 12 to 16 means), the individual-level fit's regression toward the mean it avoids, the shank exposure, the palm and sole facing ramps, the twelve sweeps and the four-centimetre collar.
 * @evidence {@link Human.IAutoMovieHumanBodySkinSites} Read the table form: the coloured material, per-site channel power fits, facing ramps, exposure, sweeps and collar.
 * @evidenceReview {@link Human.IAutoMovieHumanBodySkinSites} #2290c97 Read the table form: the coloured material, per-site `[a, b]` power fits, the palm and sole facing ramps, the shank exposure, the diffusion sweeps and the collar band in metres.
 * @evidence {@link Human.createHumanBodySkinDetailTexture} Read the tileable height field (line families with integer directions and periodic warps, pores on a wrapped jittered grid), the normal from wrapped differences and the linear encoding.
 * @evidenceReview {@link Human.createHumanBodySkinDetailTexture} #78cfbcb Read the tileable height field (Gaussian grooves along integer directions, their phase warped and depth varied by integer-frequency sinusoid fields, Gaussian pores on a seeded jittered grid that wraps), the normal from wrapped central differences in micrometres and its linear 8-bit encoding, and ran the determinism, flat, groove period and pore dimple scenarios.
 * @evidence {@link Human.humanBodySkinMetresPerUv} Read the per-triangle square root of surface over UV area and its median over the material's textured regions, and the refusal of a layout without area.
 * @evidenceReview {@link Human.humanBodySkinMetresPerUv} #04546a4 Read the per-triangle square root of surface over UV area, the median over the material's textured regions and the refusal of a layout without area, and ran the half-scale box.
 * @evidence {@link Human.HUMAN_BODY_SKIN_DETAIL} Read the tile, line families, pores and age curve against their sources.
 * @evidenceReview {@link Human.HUMAN_BODY_SKIN_DETAIL} #2fc2e04 Read the tile, line families, pores and age curve against their sources.
 * @evidence {@link Human.IAutoMovieHumanBodySkinDetail} Read the table form: seed, tile resolution and size, line families, pores and the age curve.
 * @evidenceReview {@link Human.IAutoMovieHumanBodySkinDetail} #cbfd811 Read the table form: seed, tile resolution and size, line families with direction, depth, width, wander and depth variation, pores with density, radius and depth, and the age curve over `macroAge`.
 * @evidence {@link Human.createHumanBodySkinToneTexture} Read the two chromophore fields (integer-frequency sinusoids drawn log-uniformly in each band, amplitude one over frequency, unit variance), the optical density per primary, the exp(-density) multiplier over its largest, the sRGB encoding and the mean compensation.
 * @evidenceReview {@link Human.createHumanBodySkinToneTexture} #015db26 Read the two chromophore fields (integer-frequency sinusoids drawn log-uniformly in each band, amplitude one over frequency, unit variance, computed once per table and cached), the optical density per primary, the exp(-density) multiplier over its largest, the sRGB encoding through a 4096-step table and the mean compensation.
 * @evidence {@link Human.HUMAN_BODY_SKIN_TONE} Read the tile, each chromophore's band, spread and absorbance at the sRGB primaries' dominant wavelengths against Jacques 2013 and Prahl's haemoglobin tabulation, and the authored spread and age curve.
 * @evidenceReview {@link Human.HUMAN_BODY_SKIN_TONE} #69f71ce Read the tile (384 texels over 160 mm), each chromophore's band, spread and absorbance at the sRGB primaries' dominant wavelengths against Jacques 2013 and Prahl's haemoglobin tabulation, and the authored spread and age curve.
 * @evidence {@link Human.IAutoMovieHumanBodySkinTone} Read the table form: seed, tile resolution and size, the two chromophores and the age curve.
 * @evidenceReview {@link Human.IAutoMovieHumanBodySkinTone} #9f8d4b1 Read the table form: seed, tile resolution and size, the melanin and haemoglobin chromophores and the age curve over macroAge.
 * @evidence {@link Human.IAutoMovieHumanBodySkinTone.IChromophore} Read one chromophore's band of wavelengths, its number of waves, its spread and its absorbance at the three primaries.
 * @evidenceReview {@link Human.IAutoMovieHumanBodySkinTone.IChromophore} #5a6d340 Read one chromophore's band of wavelengths, its number of waves, its spread at green and its absorbance at the three primaries relative to green.
 * @evidence {@link Human.HUMAN_BODY_SKIN_SCATTERING} Read the skin's diffuse mean free path per primary against Jensen et al. 2001's measured skin.
 * @evidenceReview {@link Human.HUMAN_BODY_SKIN_SCATTERING} #8dae26b Read the skin's diffuse mean free path per primary, red 3.67 mm, green 1.37 mm and blue 0.68 mm, against Jensen et al. 2001's "skin1" (index of refraction 1.3), in metres.
 * @evidence {@link Human.createHumanBodySurfaceSag} Read the tissue thickness against the lean body along the rest normal, the compliance with gain and softness, gravity's change in the skin's frame, the smoothing with the open boundary held, and zero at an unturned skin.
 * @evidenceReview {@link Human.createHumanBodySurfaceSag} #c7a81b4 Read the tissue thickness against the lean body along the rest normal (outward part only), the compliance with the declared gain and the document's softness, gravity's change `down − R · down` in the skin's frame, the half-step smoothing with the open boundary held at zero, and ran the unturned, turned, inverted-lean, fading boundary, builder softness and clamp, and admission scenarios.
 * @evidence {@link Human.skinHumanBodySurface} Read the per-bone unit dual quaternion of `posed ∘ rest⁻¹`, the hemisphere alignment to the first influence, the normalization by the real part's norm, the exact rigidity of unit-weight vertices and the missing-transform refusal.
 * @evidenceReview {@link Human.skinHumanBodySurface} #40db3de Read the per-bone unit dual quaternion of `posed ∘ rest⁻¹`, its sign aligned parent to child once for the skin, the blend without per-vertex flipping, the normalization by the real part's norm and both refusals, the swing-twist split of a spreading bone's parent-relative rotation about its rest axis with the twist taken in proportion along it, and ran the skinning, hemisphere and twist scenarios (the head keeps its place, the middle half the twist, the child's head all of it): a half-weighted vertex on the half-angle arc, a blend invariant to influence order at a 182 degree turn, and exact rigidity of unit-weight vertices.
 * @evidence {@link Human.resolveHumanBodyCouplings} Read the clinical-angle swing-cone elevation (rest angles standing in for absent ones), the piecewise-linear curve that is zero at and below its first knot within a nanodegree, the addition onto the document's or rest angle, and the unjudged sum left to the pose validator.
 * @evidenceReview {@link Human.resolveHumanBodyCouplings} #69aa037 Read TT total elevation for a shoulder input, swing-cone elevation for other inputs, zero-at-rest bounded curves, coupled joints left trunk-relative for the legs, and the rhythm additions appended to the contribution list.
 * @evidence {@link Human.humanBodyShoulderTtRotation} Read direct plane tilt and final-axis torsion against hand-derived left/right quaternion and direction oracles at the hanging, forward, lateral and overhead poles.
 * @evidenceReview {@link Human.humanBodyShoulderTtRotation} #f43f791 Read its tilt-axis and torsion order against independent half-angle quaternions for bilateral lateral, forward, posterior and mixed directions and both poles.
 * @evidence {@link Human.humanBodyShoulderOrientationDistance} Read the shortest SO(3) distance of TT poses using the absolute quaternion dot so equivalent pole triples share a corrective activation.
 * @evidenceReview {@link Human.humanBodyShoulderOrientationDistance} #e333fcc Read the absolute dot, same-bone refusal, clamp and near-identity tolerance against the orientation-distance and corrective activation scenarios.
 * @evidence {@link Human.humanBodyShoulderElevationLimit} Read the periodic piecewise-linear plane envelope, including the seam segment before the first knot, against hand-interpolated knot, mid-segment and wrapped-plane oracles.
 * @evidenceReview {@link Human.humanBodyShoulderElevationLimit} #806fb11 Read the period normalization, the segment walk and the seam segment from the last knot to the first one period on, and ran the reach scenario's knot, mid-segment, seam, wrapped-plane and later-first-knot oracles.
 * @evidence {@link Human.humanBodyShoulderReaches} Read the elevation and axial ranges, the plane maximum and the direction-based overhead pole against extension, cross-body and functional-position oracles.
 * @evidenceReview {@link Human.humanBodyShoulderReaches} #e16e8d7 Read the finite, elevation and axial checks, the overhead pole judged by any knot reaching 180 and the plane maximum, and ran the reach scenario's extension, cross-body, functional-position, pole and axial cases.
 * @evidence {@link Human.assertHumanBodyPelvifemoral} Read the root-child chain, open flexion, second-driver refusal and zero-at-rest nondecreasing curve inside the lumbar range against the admission scenario's one-property negatives.
 * @evidenceReview {@link Human.assertHumanBodyPelvifemoral} #1a4a1e8 Read each refusal condition and ran the admission scenario, whose every negative refuses with the rhythm's own message and whose range-end curve and abduction coupling admit.
 * @evidence {@link Human.resolveHumanBodyPelvifemoralRhythm} Read the shared tilt from the larger trunk-relative leg flexion and its root, lumbar and hip additions against hand-derived one-fifth and bilateral oracles.
 * @evidenceReview {@link Human.resolveHumanBodyPelvifemoralRhythm} #8715710 Read the curve evaluation, the zero-tilt early return and the entry replacement, and ran the rhythm scenario's contributions, bilateral maximum, extension and rest cases.
 * @evidence {@link Human.solveHumanBodyArmsDown} Read the per-arm lateral-plane bisection against the chain-versus-body crossing reading charged only beyond the rest reading, with straight elbows and the document's other joints kept.
 * @evidenceReview {@link Human.solveHumanBodyArmsDown} #f5aa11c Read the synchronous run of every step of `stepHumanBodyArmsDown` to its returned joints, and ran the arms-down scenario against an independently walked first-contact elevation.
 * @evidence {@link Human.stepHumanBodyArmsDown} Read the chain walk, the rest baseline, the bottom check and the one-degree bisection with a pause after each build and crossing read, and the solved joints it returns.
 * @evidenceReview {@link Human.stepHumanBodyArmsDown} #0890565 Read the chain walk, the rest baseline, the bottom check and the one-degree bisection with a pause after each build and crossing read, and ran the resident worker's stepped solve against the synchronous one and against a superseding request.
 * @evidence {@link Human.resolveHumanBodyShoulders} Read the coupled girdle frame, measured A-pose subtraction, thorax-relative world goal and rigid transport of each humeral descendant about the moved joint centre.
 * @evidenceReview {@link Human.resolveHumanBodyShoulders} #904ec3d Read the thorax transform, A-pose relative quaternion and subtree pivot walk against analytic left/right humerus, elbow and coupled-girdle goal tests.
 * @evidence {@link Human.measureHumanBodySection} Read the plane cut, edge-keyed crossings, closed-loop chaining, open-chain discard and seed-nearest selection against the analytic box.
 * @evidenceReview {@link Human.measureHumanBodySection} #c01d71d Read the plane cut, edge-keyed crossings, closed-loop chaining, open-chain discard and seed-nearest selection against the analytic box. Reread after the tape girth: the loop is projected onto an orthonormal frame of the plane and its convex hull perimeter is reported beside the contour perimeter, equal on the convex box and shorter across the notch of the concave prism. Reread after the hip level: the chosen loop also reports its rearmost Z.
 * @evidence {@link Human.segmentHumanBodyModel} Read the dominant-bone partition against the census: one part per bone in joint order, majority and first-corner tie rules, the UV-seam vertex walk, and the population check that refuses a mismatched build.
 * @evidenceReview {@link Human.segmentHumanBodyModel} #96e3b95 Read every surface and material region in built order, preserving UV seam source walks, dominant-bone triangle assignment, region-qualified part IDs and global source ordinals.
 * @evidence {@link Human.exportHumanBody} Read the static export: the face's portrait document and writer applied to the built body model, no rig written.
 * @evidenceReview {@link Human.exportHumanBody} #804228c Read the static export: the face's portrait document and writer applied to the built body model, no rig written.
 * @evidence {@link Human.measureHumanBodyBasisChannels} Read the whole-surface RMS accumulation, the empty-population refusal and the rule evaluation through the same shape path the builder uses.
 * @evidenceReview {@link Human.measureHumanBodyBasisChannels} #36b752d Read the whole-surface RMS accumulation, the empty-population refusal and the rule evaluation through the same shape path the builder uses. Reread after the topological ring: the height rule now measures to the surface's open boundary rather than to a remembered clip plane, so the neck-complement revision measures to its own cut.
 * @evidence {@link Human.humanBodySurfaceBoundary} Read the directed-edge census: an edge whose reverse no triangle owns is a boundary edge, and its endpoints are the ring.
 * @evidenceReview {@link Human.humanBodySurfaceBoundary} #7a042ce Read directed boundary edges grouped into separate closed ordered loops, rejecting forks or open chains; the ordinary call still returns sorted boundary vertex IDs.
 * @evidence {@link Human.humanBodyClipRing} Read the boundary-first ring with the highest-vertex fallback the closed analytic box needs.
 * @evidenceReview {@link Human.humanBodyClipRing} #4445e43 Read the highest ordered open boundary loop in the shaped surface and the highest-vertex fallback for a closed analytic fixture.
 * @evidence {@link Human.measureHumanBodyVolume} Read the tetrahedron sum, the boundary cap fanned to the loop centroid with the reversed winding, and the absolute value, against the closed and the opened box.
 * @evidenceReview {@link Human.measureHumanBodyVolume} #8bd0f4c Read signed tetrahedral volume over the same independently capped loops validated by basis admission; the top-and-bottom-open box retains its analytical volume.
 * @evidence {@link Human.evaluateHumanBodyMeasurement} Read the one-rule evaluation: height to the clip ring, landmark distance, and the station walk that keeps the picked closed section, null where the surface cannot answer.
 * @evidenceReview {@link Human.evaluateHumanBodyMeasurement} #f054809 Read the height across all shaped surfaces using each upper clip ring, landmark distance, and nearest valid section chosen across all surfaces at each station; a skin-landmark girth's one station where the plane through the shaped vertex meets the segment, null for a vertex outside its surface, a missing surface or a plane parallel to the segment. Reread after the hip level: the rearmost pick keeps the value of the station whose loop reaches furthest back.
 * @evidence {@link Human.humanBodySimpleShapeDirection} Read the channel-alone and mass directions over their ranges, the envelope-holding wear, the five-fraction sampling that refuses an unmeasurable rule, and the linear solve that refuses beyond the reach it names.
 * @evidenceReview {@link Human.humanBodySimpleShapeDirection} #a7a2957 Read the channel-alone and mass directions over their ranges, the envelope-holding wear, the five-fraction sampling that refuses an unmeasurable rule, and the linear solve that refuses beyond the reach it names or, when asked to saturate, wears the nearer end for rising and falling readings.
 * @evidence {@link Human.humanBodySimpleShapeMath} Read the flat-ended curve, the refusing inversion, the clamped curve inverse, Deurenberg's fat and excess, the parameter record with the body mass index from mass and stature, the term product and Siri's density.
 * @evidenceReview {@link Human.humanBodySimpleShapeMath} #f679181 Read the flat-ended curve and inverse, the distinct Deurenberg child/adult fits and fractional-age bridge, the sex-specific maturity ramp and the developed muscle it scales, the visible fat the definition gates read (the regression's excess less 100 · Δ · developed muscle / BMI, floored at one point), Jensen's 1989 polynomial child head share and adult bridge, term product, and Siri density. Reread after the survey refit: the head-and-neck share less the kept neck, which falls inversely with the body mass index.
 * @evidence {@link Human.measureHumanBodySimpleShape} Read the stature (height rule plus head allowance, refused without a rule), the skin volume through the builder's shape path, the mass over the head-and-neck share and the channel rule reading.
 * @evidenceReview {@link Human.measureHumanBodySimpleShape} #8db6aa5 Read stature, every shaped surface's validated independent cap and nonoverlapping total volume, age-specific head/neck mass share, and named tape rules. Reread after the survey refit: the mass reads the share above the clip ring at the body's mass index.
 * @evidence {@link Human.projectHumanBodySimpleShape} Read the measured stature, the mass fixed point over the fat density, the inverse-first-row identity readings with the other muscle rows removed, and the named tape measurements read back.
 * @evidenceReview {@link Human.projectHumanBodySimpleShape} #8114e2a Read stature, the mass fixed point using the age-specific density and head share, inverse first-row demographic readings and tape measurements. Reread after the survey refit: the mass fixed point also updates the body mass index the share above the clip ring reads.
 * @evidence {@link Human.expandHumanBodySimpleShape} Read the envelope and missing-value refusals, the product-of-curves rows with envelope saturation and skipped channels, the three-sample inversions for stature, mass and each named tape measurement that refuse beyond their reach or on a channel that does not grow, and the residual composition over an existing shape.
 * @evidenceReview {@link Human.expandHumanBodySimpleShape} #f03718b Read age-specific fat parameters and mass inversion using the matching head and neck share, envelope saturation, the saturating tape-and-mass fixed point followed by one strict pass that refuses on the converged body, and residual composition; ran the coupled-reach scenario. Reread after the survey refit: the mass solve passes the requested body mass index to the share above the clip ring.
 * @evidence {@link Human.HUMAN_BODY_SIMPLE_SHAPE} Read every row against its pinned source: the age nodes, the sarcopenia gain, the ptosis, apron, android and gynoid curves, the definition gates over excess fat, and the firmness fall.
 * @evidenceReview {@link Human.HUMAN_BODY_SIMPLE_SHAPE} #fc8f05c Read the pinned table including separate Deurenberg child/adult regressions, the authored 15–16 continuity bridge, Jensen's 1989 boy-child polynomial head and neck share, adult share, the fat-free mass per unit of muscle by sex (Schutz 2002 medians, Kouri 1995 athletes), the maturity ramp from a year before to three years after peak height velocity by sex (Faigenbaum 2009, Lloyd 2014, Baxter-Jones 2008, Tanner 1981) that every row calibrated on adult training reads through developed muscle, the muscle envelope to 2, and the soft-tissue rows (gluteal mass and tone, breast descent, fill, projection and volume, adipose male chest, abdominal tone and navel, submental, arm and thigh fat, the trained V, musculature and chest definition, skeletal prominence under muscle) with the recalibrated definition bands, and the ANSUR II people rows (a woman's gluteal projection, hip breadth and depth, thigh and calf fat and breast position over body mass index knots 18, 22, 26, 30 and 35, fading to zero at 15 and 45 or 40, and her pelvis height at -0.6 from 18 to 35 with the same fade, fitted to reproduced survey women's unpinned buttock, waist, limb, bust point and crotch residuals; no men's rows), and the seven tape measurements' envelopes and channels: the waist, hip and bust girths and the shoulder breadth, and the thigh, upper arm and calf girths on their own measurement channels. Reread after the wrist and ankle rows: by sex over the same knots and fade, each the fitted residual of the reproduced people over the girth channel's response per unit (wrist 52 mm; ankle 56 mm for a woman, 54 for a man), a woman's positive throughout and a man's wrist turning negative past a body mass index of about 28. The mass they add is taken back by the mass solve, narrowing a surveyed woman's waist at the omphalion by 7.6 mm and a man's by 1.4. Reread after the survey refit: the kept neck (2.35 % at a body mass index of 24, inversely with it) taken out of the head-and-neck share; the ANSUR II people rows refitted twice on all 300 surveyed people under the rearmost hip rule and that mass model, with each candidate channel costing its measured ridge amplitude (the 1 to 4 cm heat-diffusion band of its field) above a plain scale field's, so neither sex keeps a gluteal projection or belly row; a woman's hip breadth, depth and height, thigh and calf fat and trunk breadth and depth, and a man's leg length (both segments), trunk breadth and depth and pelvis height (his thigh and calf fat rows folded a shorter man's pelvis at a body mass index of 30 and were dropped), the refitted and new rows rising from 11 to 17 and falling from 60 to 80, the new ones fading at a body mass index of 40.
 * @evidence {@link Human.IAutoMovieHumanBodySimpleShape} Read the five physical parameters and their units.
 * @evidenceReview {@link Human.IAutoMovieHumanBodySimpleShape} #2151743 Read the five physical parameters and their units, and the seven optional tape measurements: the waist, hip and bust girths, the shoulder breadth, and the thigh, upper arm and calf girths, each limb one moving both sides.
 * @evidence {@link Human.IAutoMovieHumanBodySimpleShapeTable} Read the table form: envelope, head allowance, mass model, fat estimate and product-of-curves rows.
 * @evidenceReview {@link Human.IAutoMovieHumanBodySimpleShapeTable} #5d9391d Read the age-specific fat coefficients, the muscle's fat-free mass index by sex, the maturity start and end ages by sex, and quadratic child head and neck mass-share form, both transition ages, the envelope with the seven tape measurements' bounds, the tape parameters a measurement entry may name, head allowance and product-of-curves rows. Reread after the survey refit: the kept neck's share at a body mass index, taken out of the head-and-neck share.
 * @evidence {@link Human.AutoMovieHumanBodySimpleParameter} Read the five parameters and the derived excess fat and developed muscle a curve may be read over.
 * @evidenceReview {@link Human.AutoMovieHumanBodySimpleParameter} #8575986 Read the five parameters and the derived excess fat and developed muscle a curve may be read over.
 * @evidence {@link Human.admitHumanBodyBasisDocument} Read exact schema admission, finiteness over named weights, angles and material scalars, nonblank identities and the duplicate-bone refusal.
 * @evidenceReview {@link Human.admitHumanBodyBasisDocument} #4fc05e2 Read exact schema and finite admission of weights, generic angles, complete TT shoulder triples, the skin's cheek albedo and materials, unique bones, and refusal of legacy identity and upper-arm Euler pose; the skin detail strength is among the finite numbers. Reread after the skin tone: the tone strength joins the finite numbers admission checks.
 * @evidence {@link Human.parseHumanBodyBasisDocument} Read the shared UTF-16 envelope, JSON parsing and the admission hand-off.
 * @evidenceReview {@link Human.parseHumanBodyBasisDocument} #b9f437d Read the shared UTF-16 envelope, JSON parsing and the admission hand-off.
 * @evidence {@link Human.serializeHumanBodyBasisDocument} Read admission before serialization and the envelope check on the escaped, formatted text.
 * @evidenceReview {@link Human.serializeHumanBodyBasisDocument} #e13d2dc Read admission before serialization and the envelope check on the escaped, formatted text.
 */
export const humanBodyStudyReview = {
  basis: "connected-basis/README.md",
  receipt: "connected-basis/extraction-receipt.json",
  likeness: "unaccepted",
};
