import type { IHumanBodyStudyProvenance } from "./IHumanBodyStudyProvenance";

/**
 * Public carrier for inspected physical candidates and static interchange.
 * It records no anatomical or clinical acceptance of the complete body.
 *
 * @evidenceExclude requirements/actors/body-authoring/README.md#body-requirements This family index spans complete body authoring and browser workflow; this carrier records bounded source-rest exterior and static candidate interchange without accepting complete anatomy.
 * @evidence requirements/actors/body-authoring/contract.md#actor-body-export Carries inspected source identity and candidate-qualified static readback.
 * @evidenceExclude specifications/asset-and-representation/body-authoring/README.md#body-specifications The specification index groups complete generation, joints, documents and editing; this carrier inspects one source-rest physical candidate and candidate export, while full anatomy remains unavailable.
 * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-export Carries the inspected source-to-primitive identity boundary without claiming rig or clinical document reconstruction.
 * @author Samchon
 */
export interface humanBodyStudyReview {
  /**
   * Inspected candidate asset identity, independent of whole-body qualification.
   *
   * The real writer/readback scenarios and current numerical request export
   * carry source IDs and actual primitive intervals, with reference-only target
   * provenance. Clinical registration, complete bones and skin remain unavailable.
   *
   * @evidence ../../../packages/human/src/body/export/IAutoMovieHumanBodyArticularAssetCorrespondence.ts#IAutoMovieHumanBodyArticularAssetCorrespondence Read the separate source partition and candidate-only qualification through actual GLB/glTF readback; this describes a target sphere rather than a validated bone or person.
   * @evidence ../../../packages/human/src/body/export/IAutoMovieHumanBodyArticularAssetCorrespondence.ts#IAutoMovieHumanBodyArticularAssetCorrespondence.geometry Read the common constructor's actual prepared populations and the reader's accessor/index partition admission; source IDs are not material-derived anatomy.
   * @evidence ../../../packages/human/src/body/export/IAutoMovieHumanBodyArticularAssetCorrespondence.ts#IAutoMovieHumanBodyArticularAssetCorrespondence.qualification Read supported revision/reference, target/reference-rig-only and unavailable whole skin/parts, with no clinical certificate or editable document inferred.
   * @evidence ../../../packages/human/src/body/export/readHumanBodyArticularAssetCorrespondence.ts#readHumanBodyArticularAssetCorrespondence Read legacy absence, malformed/unsupported namespace refusal, common interval delegation and exact candidate-ID join, with owned output and recovery scenarios.
   * @evidence ../../../packages/human/src/body/export/IAutoMovieHumanBodyArticularQualification.ts#IAutoMovieHumanBodyArticularQualification Read the named qualification record the exporter writes beside the common source partition, adding no interval formula of its own.
   * @evidence ../../../packages/human/src/body/export/IAutoMovieHumanBodyArticularQualification.ts#IAutoMovieHumanBodyArticularQualification.version Read the literal body metadata version 1, kept distinct from the common partition's version.
   * @evidence ../../../packages/human/src/body/export/IAutoMovieHumanBodyArticularQualification.ts#IAutoMovieHumanBodyArticularQualification.generatorRevision Read the literal "articular-head-inspection/1" inspector revision, never a clinical validation revision.
   * @evidence ../../../packages/human/src/body/export/IAutoMovieHumanBodyArticularQualification.ts#IAutoMovieHumanBodyArticularQualification.reference Read the neutral reference basis copied from the inspection report, not a registered personal centre.
   * @evidence ../../../packages/human/src/body/export/IAutoMovieHumanBodyArticularQualification.ts#IAutoMovieHumanBodyArticularQualification.skin Read the unavailable whole skin the export repeats rather than certifies.
   * @evidence ../../../packages/human/src/body/export/IAutoMovieHumanBodyArticularQualification.ts#IAutoMovieHumanBodyArticularQualification.parts Read one qualification per carrying primitive source member, in that member order.
   * @evidence ../../../packages/human/src/body/export/IAutoMovieHumanBodyArticularPartQualification.ts#IAutoMovieHumanBodyArticularPartQualification Read the per-member qualification joined to exactly one source part by candidate ID.
   * @evidence ../../../packages/human/src/body/export/IAutoMovieHumanBodyArticularPartQualification.ts#IAutoMovieHumanBodyArticularPartQualification.id Read the `${part}/head-candidate` template that names the candidate, distinct from its complete bone.
   * @evidence ../../../packages/human/src/body/export/IAutoMovieHumanBodyArticularPartQualification.ts#IAutoMovieHumanBodyArticularPartQualification.source Read the literal "target" source copied from the candidate, never an imaging acquisition.
   * @evidence ../../../packages/human/src/body/export/IAutoMovieHumanBodyArticularPartQualification.ts#IAutoMovieHumanBodyArticularPartQualification.registration Read the literal "reference-rig-only" placement copied from the candidate, certifying no personal registration.
   * @evidence ../../../packages/human/src/body/export/IAutoMovieHumanBodyArticularPartQualification.ts#IAutoMovieHumanBodyArticularPartQualification.partResolution Read the exported unavailable complete-part resolution of each candidate sphere.
   * @evidence ../../../packages/human/src/body/anatomy/generated/IAutoMovieHumanBodyUnvalidatedGeometry.ts#IAutoMovieHumanBodyUnvalidatedGeometry Read the shared unavailable-geometry status that inspection skin, candidate parts and exported qualification all carry instead of a resolved surface.
   * @evidence ../../../packages/human/src/body/anatomy/generated/IAutoMovieHumanBodyUnvalidatedGeometry.ts#IAutoMovieHumanBodyUnvalidatedGeometry.status Read the literal "unavailable" status that keeps a candidate from standing in for generated anatomy.
   * @evidence ../../../packages/human/src/body/anatomy/generated/IAutoMovieHumanBodyUnvalidatedGeometry.ts#IAutoMovieHumanBodyUnvalidatedGeometry.reason Read the literal "geometry-not-validated" reason, one member of the anatomical resolution reason union.
   * @evidence ../../../packages/human/src/body/anatomy/generated/IAutoMovieHumanBodyAnatomicalReference.ts#IAutoMovieHumanBodyAnatomicalReference Read the inspection's reference provenance, copied verbatim into exported qualification.
   * @evidence ../../../packages/human/src/body/anatomy/generated/IAutoMovieHumanBodyAnatomicalReference.ts#IAutoMovieHumanBodyAnatomicalReference.basis Read the reference basis identity the exporter refuses when blank.
   * @evidence ../../../packages/human/src/body/anatomy/generated/IAutoMovieHumanBodyAnatomicalReference.ts#IAutoMovieHumanBodyAnatomicalReference.evaluation Read the literal "neutral-reference" evaluation, which is not the requested person's skin.
   * @evidence ../../../packages/human/src/body/anatomy/generated/IAutoMovieHumanBodyArticularCandidate.ts#IAutoMovieHumanBodyArticularCandidate Read the explicit target-radius sphere record: one per explicit target, at the carrying joint's reference rig centre.
   * @evidence ../../../packages/human/src/body/anatomy/generated/IAutoMovieHumanBodyArticularCandidate.ts#IAutoMovieHumanBodyArticularCandidate.part Read the humerus/femur name the candidate concerns and the export ID is built from.
   * @evidence ../../../packages/human/src/body/anatomy/generated/IAutoMovieHumanBodyArticularCandidate.ts#IAutoMovieHumanBodyArticularCandidate.bone Read the upper-arm/upper-leg rig joint whose reference centre carries the sphere.
   * @evidence ../../../packages/human/src/body/anatomy/generated/IAutoMovieHumanBodyArticularCandidate.ts#IAutoMovieHumanBodyArticularCandidate.center Read the sphere centre in reference-frame metres that the candidate model places once with null part transforms.
   * @evidence ../../../packages/human/src/body/anatomy/generated/IAutoMovieHumanBodyArticularCandidate.ts#IAutoMovieHumanBodyArticularCandidate.radiusMetres Read the requested sphere-fitted radius in metres that sets the tessellated sphere size.
   * @evidence ../../../packages/human/src/body/anatomy/generated/IAutoMovieHumanBodyArticularCandidate.ts#IAutoMovieHumanBodyArticularCandidate.source Read the literal "target" source the exporter copies into each part qualification.
   * @evidence ../../../packages/human/src/body/anatomy/generated/IAutoMovieHumanBodyArticularCandidate.ts#IAutoMovieHumanBodyArticularCandidate.registration Read the literal "reference-rig-only" registration the exporter copies into each part qualification.
   * @evidence ../../../packages/human/src/body/anatomy/generated/IAutoMovieHumanBodyArticularCandidate.ts#IAutoMovieHumanBodyArticularCandidate.partResolution Read the candidate's unavailable complete-bone resolution, copied rather than shared by the exporter.
   * @evidence ../../../packages/human/src/body/anatomy/articulation/IAutoMovieHumanBodyArticularCandidateModelProps.ts#IAutoMovieHumanBodyArticularCandidateModelProps Read the candidate model adapter's inputs: model labels plus the generated inspection report, with no skin or personal mesh accepted.
   * @evidence ../../../packages/human/src/body/anatomy/articulation/IAutoMovieHumanBodyArticularCandidateModelProps.ts#IAutoMovieHumanBodyArticularCandidateModelProps.id Read the static model identity the adapter writes to the produced model.
   * @evidence ../../../packages/human/src/body/anatomy/articulation/IAutoMovieHumanBodyArticularCandidateModelProps.ts#IAutoMovieHumanBodyArticularCandidateModelProps.name Read the static model display name the adapter writes to the produced model.
   * @evidence ../../../packages/human/src/body/anatomy/articulation/IAutoMovieHumanBodyArticularCandidateModelProps.ts#IAutoMovieHumanBodyArticularCandidateModelProps.inspection Read the report whose candidates the adapter tessellates as spheres, one mesh per candidate.
   * @evidence ../../../packages/human/src/body/export/exportHumanBody.ts#exportHumanBody Read optional same-Document qualification before the existing writer and metadata-free face/body/person defaults through actual byte and geometry comparisons.
   * @evidence requirements/actors/body-authoring/contract.md#actor-body-export Inspects static candidate identity at the actual exporter while preserving the numerical document and anatomical limitations.
   * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-export Inspects primitive source correspondence at Float32 output without claiming a rig or clinical edit roundtrip.
   */
  readonly articularAssetIdentity: "candidate-only";
  /**
   * Inspected fictional source-rest exterior, independent of clinical anatomy.
   * The tiny authored source and actual r16 producer use the same compiled
   * builder, final Float32 instrument and bounded inverse. Complete context
   * survives; unregistered observed girths refuse and every clinical part
   * remains unavailable. This records a physical candidate, not GeneratedSkin.
   *
   * @evidence ../../../packages/human/src/body/anatomy/surface/IAutoMovieHumanBodyExteriorReference.ts#IAutoMovieHumanBodyExteriorReference Read one constructor-owned source registration without adding morph controls to the body document.
   * @evidence ../../../packages/human/src/body/anatomy/surface/IAutoMovieHumanBodyExteriorReference.ts#IAutoMovieHumanBodyExteriorReference.basis Read exact source identity and mismatch refusal against immutable compiled geometry.
   * @evidence ../../../packages/human/src/body/anatomy/surface/IAutoMovieHumanBodyExteriorReference.ts#IAutoMovieHumanBodyExteriorReference.incidence Read explicit native indexed or actual canonical source registration while the ordinary body constructor retains absent metadata.
   * @evidence ../../../packages/human/src/body/anatomy/surface/IAutoMovieHumanBodyExteriorReference.ts#IAutoMovieHumanBodyExteriorReference.evaluation Read the explicit source-rest recipe rather than registered personal posture.
   * @evidence ../../../packages/human/src/body/anatomy/generated/IAutoMovieHumanBodyExteriorCandidateBuild.ts#IAutoMovieHumanBodyExteriorCandidateBuild Read the actual static exterior beside clinical unavailable output and preserved complete context.
   * @evidence ../../../packages/human/src/body/anatomy/generated/IAutoMovieHumanBodyExteriorCandidateBuild.ts#IAutoMovieHumanBodyExteriorCandidateBuild.model Read real resident admission, source partition and original writer/readback at Float32 precision.
   * @evidence ../../../packages/human/src/body/anatomy/generated/IAutoMovieHumanBodyExteriorCandidateBuild.ts#IAutoMovieHumanBodyExteriorCandidateBuild.exterior Read every fulfilled target's readings, residual and section with candidate-only anatomical availability.
   * @evidence ../../../packages/human/src/body/anatomy/surface/createHumanBodyExteriorTargetBuilder.ts#createHumanBodyExteriorTargetBuilder Read the body document's anatomy met on the actual compiled exterior and re-read on its Float32 skin, with refusal and recovery.
   * @evidence ../../../packages/human/src/body/measure/readHumanBodyShapedMeasurement.ts#readHumanBodyShapedMeasurement Read the cohesive legacy instrument extraction and its observed final Float32 plane/seed without a duplicated formula.
   * @evidence ../../../packages/human/src/body/basis/createHumanBodyBasisBuilder.ts#createHumanBodyBasisBuilder Read explicit physicalSource compilation from actual native content or canonical samples, preserving default body output and independent geometry admission.
   * @evidence ../../../packages/human/src/body/basis/createHumanBodySurfaceParts.ts#createHumanBodySurfaceParts Read preUV source identity and actual document instance through the sole domain helper without changing posed coordinates or normals.
   * @evidence ../../../packages/human/src/body/basis/createHumanBodySurfaceRegionParts.ts#createHumanBodySurfaceRegionParts Read the same authoritative UV gather for XYZ and physical samples, preserving source incidence across material/UV aliases.
   * @evidence ../../../packages/human/src/common/measure/measureHumanSection.ts#measureHumanSection Read optional engine-resolved source-pair/null edge incidence in the existing cut, retaining omitted-argument raw-index behavior and unchanged plane/hull/seed calculations.
   * @evidence requirements/actors/body-authoring/contract.md#actor-body-editor Inspects the first physical exterior request consumer while preserving unsupported context and unavailable anatomy.
   * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor Inspects exactly one candidate report with transactional request/frame history.
   */
  readonly sourceConditionedExterior: "candidate-only";
}

/**
 * Current construction-source inspection for the portable body studies.
 *
 * Every public declaration of the body folder was read against the basis it
 * evaluates (`connected-basis/basis.json.gz`), the analytic scenarios under
 * `test/src/features/human-body`, and its consumers. Deterministic replay and
 * source correctness do not accept a body's physiological range or likeness;
 * the census and render observations live beside the payload. Native-issued
 * fingerprints are added only after those inspections.
 *
 * @evidence requirements/actors/body-authoring/contract.md#actor-body-connected-basis The study supplies a licensed neutral body prior and independent compact edits to the evaluator this review reads.
 * @evidence requirements/actors/body-authoring/contract.md#actor-body-joints The study's joints, landmarks and skin weights are what the inspected skeleton and skinning code evaluate.
 * @evidence requirements/actors/body-authoring/contract.md#actor-body-measurements The study's measure channels are the ones the inspected rules price in metres.
 * @evidence requirements/actors/body-authoring/contract.md#actor-body-document The study's documents are loaded and saved through the inspected boundary.
 * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-basis The selected single-surface asset exercises immutable basis compilation, common normals and revision-bound edits.
 * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-joints The selected fifty-two joints exercise the frame rule, sign frames, pose validation and rigid skinning.
 * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-measurements The selected twenty measure channels exercise the girth, distance, height and breadth rules.
 * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-document The study documents exercise the parse and serialize admission and envelope.
 * @evidence requirements/actors/body-authoring/contract.md#actor-body-export The study's built body is what the inspected exporter writes to GLB and glTF.
 * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-export The exported study body exercises the shared Float32 writer without a rig.
 * @evidence requirements/actors/body-authoring/contract.md#actor-body-simple-shape The study's basis is what the simple tier's stature and body mass index are solved against.
 * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-simple-shape The study's ring and skin volume are the measurements the expansion's inversions read.
 * @evidence requirements/actors/body-authoring/contract.md#actor-body-underwear The study's landmarks, skin weights and nipple vertex are what the inspected underwear rules are read on.
 * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-underwear The study body exercises the underwear's landmark rules, the clip at their zero and the lift along the posed normals.
 * @evidenceExclude requirements/actors/body-authoring/contract.md#actor-body-editor The browser editor is the playground's; the study review inspects the package sources it calls, not the screen.
 * @evidenceExclude specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor-view The study review owns no inputs, presets or display state.
 * @evidenceExclude specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor The study review owns no transaction history or worker.
 * @evidenceExclude requirements/actors/body-authoring/README.md#body-requirements This index spans the editing screen and census review as well; the study review records source inspection, not the complete workflow.
 * @evidenceExclude specifications/asset-and-representation/body-authoring/README.md#body-specifications This index joins evaluation, measurement, document and later editor boundaries; the study review does not own the browser adapter.
 *
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyBasis.ts#IAutoMovieHumanBodyBasis Read the schema and admission against the shipped CC0 asset: sparse endpoints, shared topology, one exact material partition, landmarks, joints and four-influence skin, and the frame shared with the face at the neck ring.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyBasis.ts#IAutoMovieHumanBodyBasis.id Read nonblank identity admission and the builder's exact document-to-basis binding.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyBasis.ts#IAutoMovieHumanBodyBasis.channels Read finite neutral-containing ranges, reciprocal same-group mirrors, distinct signed endpoint selection and ordered accumulation.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyBasis.ts#IAutoMovieHumanBodyBasis.correctives Read driver-side admission, the (0,1] gain and the product activation the shipped macro pair residuals fire under.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyBasis.ts#IAutoMovieHumanBodyBasis.landmarks Read the named point set, its finite positions and the sparse rows that move a joint with the shape it sits in.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyBasis.ts#IAutoMovieHumanBodyBasis.joints Read the rooted parent-first tree, landmark ends, unit flexion reference, measured signs on exactly the mobile axes and rest-containing ranges.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyBasis.ts#IAutoMovieHumanBodyBasis.surfaces Read topology admission, sparse vertex ordering, nonzero differences, oriented triangle partition, unit-sum skin and common normals before UV separation.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyBasis.ts#IAutoMovieHumanBodyBasis.materials Read unique resident identities, copied overrides and final model admission.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyBasisDocument.ts#IAutoMovieHumanBodyBasisDocument Read the compact schema admission for named shape, pose and material edits over one exact basis revision, with omissions meaning neutral or rest.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyShoulderPose.ts#IAutoMovieHumanBodyShoulderPose Read the complete thorax-relative humeral goal, its plane period, total elevation, independent axial rotation and the two non-unique poles.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyShoulderPose.ts#IAutoMovieHumanBodyShoulderPose.bone Read explicit left/right humerus ownership rather than inferring a side from an angle sign.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyShoulderPose.ts#IAutoMovieHumanBodyShoulderPose.plane Read the side-relative lateral zero, anterior positive plane and [-180,180) period.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyShoulderPose.ts#IAutoMovieHumanBodyShoulderPose.elevation Read total humerothoracic elevation from the anatomical hanging zero, independent of the coupled girdle.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyShoulderPose.ts#IAutoMovieHumanBodyShoulderPose.axialRotation Read positive external rotation about the final humeral axis and its distinction from the plane choice.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyBasisDocument.ts#IAutoMovieHumanBodyBasisDocument.id Read nonblank identity admission and preservation into the resident model.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyBasisDocument.ts#IAutoMovieHumanBodyBasisDocument.name Read nonblank display identity admission and preservation into the model.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyBasisDocument.ts#IAutoMovieHumanBodyBasisDocument.basis Read exact compiled-basis matching without implicit conversion or migration.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyBasisDocument.ts#IAutoMovieHumanBodyBasisDocument.shape Read channel-membership and envelope validation, neutral omission and signed endpoint weights without clamping.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyBasisDocument.ts#IAutoMovieHumanBodyBasisDocument.pose Read the sparse unique-bone clinical pose, its validation against each joint's range and rest as omission.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyBasisDocument.ts#IAutoMovieHumanBodyBasisDocument.materials Read resident-ID validation, optional RGB/roughness boundaries and material copying.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyBuild.ts#IAutoMovieHumanBodyBuild Read the posed static model beside the rest skeleton, per-bone rest and posed transforms and shaped landmarks the verification tools consume.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyBuild.ts#IAutoMovieHumanBodyBuild.model Read the skinless, skeletonless posed model that the static exporter admits unchanged.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyBuild.ts#IAutoMovieHumanBodyBuild.skeleton Read the rest skeleton of the shaped body, before the document's pose.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyBuild.ts#IAutoMovieHumanBodyBuild.bones Read the per-joint rest and posed world transforms in basis order, which the arc scenarios compare against hand rotations.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyBuild.ts#IAutoMovieHumanBodyBuild.landmarks Read the shaped landmark positions after channels and correctives, before any pose.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyChannelScale.ts#IAutoMovieHumanBodyChannelScale Read the per-endpoint RMS, peak and count beside the optional measurement record and its null-valued unmeasurable case.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyChannelScale.ts#IAutoMovieHumanBodyChannelScale.id Read the channel identity the scale reports for.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyChannelScale.ts#IAutoMovieHumanBodyChannelScale.group Read the source group copied for grouping without a second lookup.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyChannelScale.ts#IAutoMovieHumanBodyChannelScale.positive Read the positive endpoint's whole-surface RMS, peak and moved count.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyChannelScale.ts#IAutoMovieHumanBodyChannelScale.negative Read the negative endpoint's figures or null for a nonnegative control.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyChannelScale.ts#IAutoMovieHumanBodyChannelScale.measurement Read the rule identity, kind and neutral, positive and negative metre values, null when no rule is bound or the surface cannot answer.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyMeasurement.ts#IAutoMovieHumanBodyMeasurement Read the three rule kinds and the landmark, plane, sampling and extremum parameters each carries.
 * @evidence ../../../packages/human/src/body/constants/HUMAN_BODY_MEASUREMENTS.ts#HUMAN_BODY_MEASUREMENTS Read each rule against the shipped landmarks and the public measurement definition it approximates, and the neck channels left without a rule.
 * @evidence ../../../packages/human/src/body/basis/assertHumanBodyBasis.ts#assertHumanBodyBasis Read identity, envelope, mirror, corrective, topology, sparse-row, partition and endpoint-population admission, then the rig hand-off.
 * @evidence ../../../packages/human/src/body/basis/assertHumanBodyRig.ts#assertHumanBodyRig Read landmark, tree-order, reference, sign-versus-constraint, range and skin admission against the shipped rig and the analytic negatives.
 * @evidence ../../../packages/human/src/body/basis/assertSparseRows.ts#assertSparseRows Read the one row format every endpoint and landmark payload shares and the labelled refusals.
 * @evidence ../../../packages/human/src/body/basis/createHumanBodyBasisBuilder.ts#createHumanBodyBasisBuilder Read schema admission, immutable compilation, the fixed evaluation order, pose validation through the engine, rigid skinning, normal reconstruction and final model validation.
 * @evidence ../../../packages/human/src/body/basis/evaluateHumanBodyShape.ts#evaluateHumanBodyShape Read `|weight| x endpoint`, then activation-scaled correctives, applied to surfaces and landmarks by endpoint name on fresh copies.
 * @evidence ../../../packages/human/src/body/basis/humanBodyBasisWeights.ts#humanBodyBasisWeights Read envelope and membership refusals and the product corrective activation shared by builder and measurement.
 * @evidence ../../../packages/human/src/body/basis/resolveHumanBodySkeleton.ts#resolveHumanBodySkeleton Read the `Y x F` frame, the Shepperd quaternion, the parent-relative rest transform and the sign rest frames, against the analytic frame scenarios.
 * @evidence ../../../packages/human/src/body/basis/appearance/createHumanBodySkinColour.ts#createHumanBodySkinColour Read the site weights off the skin (hand bones split by the normal along their flexion reference, feet by the normal against up, forearm, shank, neck and the protected rest), their diffusion, the clamped fits, the collar smoothstep from the open ring, and the base-and-multiplier split.
 * @evidence ../../../packages/human/src/body/constants/HUMAN_BODY_SKIN_SITES.ts#HUMAN_BODY_SKIN_SITES Read each site's power fits against the skin-sites receipt's group-mean fits of the archive and the site assignment's weights.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodySkinSites.ts#IAutoMovieHumanBodySkinSites Read the table form: the coloured material, per-site channel power fits, facing ramps, exposure, sweeps and collar.
 * @evidence ../../../packages/human/src/body/basis/appearance/createHumanBodySkinDetailTexture.ts#createHumanBodySkinDetailTexture Read the tileable height field (line families with integer directions and periodic warps, pores on a wrapped jittered grid), the normal from wrapped differences and the linear encoding.
 * @evidence ../../../packages/human/src/body/basis/appearance/humanBodySkinMetresPerUv.ts#humanBodySkinMetresPerUv Read the per-triangle square root of surface over UV area and its area-weighted median over the material's textured regions, and the refusal of a layout without area.
 * @evidence ../../../packages/human/src/body/constants/HUMAN_BODY_SKIN_DETAIL.ts#HUMAN_BODY_SKIN_DETAIL Read the tile, line families, pores and age curve against their sources.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodySkinDetail.ts#IAutoMovieHumanBodySkinDetail Read the table form: seed, tile resolution and size, line families, pores and the age curve.
 * @evidence ../../../packages/human/src/body/basis/appearance/createHumanBodySkinToneTexture.ts#createHumanBodySkinToneTexture Read the two chromophore fields (integer-frequency sinusoids drawn log-uniformly in each band, amplitude one over frequency, unit variance), the optical density per primary, the exp(-density) multiplier over its largest, the sRGB encoding and the mean compensation.
 * @evidence ../../../packages/human/src/body/constants/HUMAN_BODY_SKIN_TONE.ts#HUMAN_BODY_SKIN_TONE Read the tile, each chromophore's band, spread and absorbance at the sRGB primaries' dominant wavelengths against Jacques 2013 and Prahl's haemoglobin tabulation, and the authored spread and age curve.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodySkinTone.ts#IAutoMovieHumanBodySkinTone Read the table form: seed, tile resolution and size, the two chromophores and the age curve.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodySkinTone.ts#IAutoMovieHumanBodySkinTone.IChromophore Read one chromophore's band of wavelengths, its number of waves, its spread and its absorbance at the three primaries.
 * @evidence ../../../packages/human/src/index.ts#HUMAN_BODY_SKIN_SCATTERING Read the skin's diffuse mean free path per primary against Jensen et al. 2001's measured skin.
 * @evidence ../../../packages/human/src/body/basis/createHumanBodySurfaceSag.ts#createHumanBodySurfaceSag Read the tissue thickness against the lean body along the rest normal, the compliance with gain and softness, gravity's change in the skin's frame, the smoothing with the open boundary held, and zero at an unturned skin.
 * @evidence ../../../packages/human/src/body/basis/skinHumanBodySurface.ts#skinHumanBodySurface Read the per-bone unit dual quaternion of `posed ∘ rest⁻¹`, the hemisphere alignment to the first influence, the normalization by the real part's norm, the exact rigidity of unit-weight vertices and the missing-transform refusal.
 * @evidence ../../../packages/human/src/body/basis/resolveHumanBodyCouplings.ts#resolveHumanBodyCouplings Read the clinical-angle swing-cone elevation (rest angles standing in for absent ones), the piecewise-linear curve that is zero at and below its first knot within a nanodegree, the addition onto the document's or rest angle, and the unjudged sum left to the pose validator.
 * @evidence ../../../packages/human/src/body/basis/humanBodyShoulderTtRotation.ts#humanBodyShoulderTtRotation Read direct plane tilt and final-axis torsion against hand-derived left/right quaternion and direction oracles at the hanging, forward, lateral and overhead poles.
 * @evidence ../../../packages/human/src/body/basis/humanBodyShoulderOrientationDistance.ts#humanBodyShoulderOrientationDistance Read the shortest SO(3) distance of TT poses using the absolute quaternion dot so equivalent pole triples share a corrective activation.
 * @evidence ../../../packages/human/src/body/basis/humanBodyShoulderPoseFromDirection.ts#humanBodyShoulderPoseFromDirection Read the shared shaped-rest unit-direction readout used by the actual shoulder resolver and fractional corrective sampler: explicit humerus side, side-aware atan2 plane and clamped acos elevation in degrees. One direction cannot measure torsion, so zero axial rotation preserves the prior rest convention; this readout neither registers an anatomical humeral frame nor admits physiological reach. Source inspection does not stand for the pending sampler scenarios or actual body render acceptance.
 * @evidence ../../../packages/human/src/body/basis/humanBodyShoulderElevationLimit.ts#humanBodyShoulderElevationLimit Read the periodic piecewise-linear plane envelope, including the seam segment before the first knot, against hand-interpolated knot, mid-segment and wrapped-plane oracles.
 * @evidence ../../../packages/human/src/body/basis/humanBodyShoulderReaches.ts#humanBodyShoulderReaches Read the elevation and axial ranges, the plane maximum and the direction-based overhead pole against extension, cross-body and functional-position oracles.
 * @evidence ../../../packages/human/src/body/basis/admission/rig/assertHumanBodyPelvifemoral.ts#assertHumanBodyPelvifemoral Read the root-child chain, open flexion, second-driver refusal and zero-at-rest nondecreasing curve inside the lumbar range against the admission scenario's one-property negatives.
 * @evidence ../../../packages/human/src/body/basis/resolveHumanBodyPelvifemoralRhythm.ts#resolveHumanBodyPelvifemoralRhythm Read the shared tilt from the larger trunk-relative leg flexion and its root, lumbar and hip additions against hand-derived one-fifth and bilateral oracles.
 * @evidence ../../../packages/human/src/body/measure/solveHumanBodyArmsDown.ts#solveHumanBodyArmsDown Read the per-arm lateral-plane bisection against the chain-versus-body crossing reading charged only beyond the rest reading, with straight elbows and the document's other joints kept.
 * @evidence ../../../packages/human/src/body/measure/stepHumanBodyArmsDown.ts#stepHumanBodyArmsDown Read the chain walk, the rest baseline, the bottom check and the one-degree bisection with a pause after each build and crossing read, and the solved joints it returns.
 * @evidence ../../../packages/human/src/body/basis/resolveHumanBodyShoulders.ts#resolveHumanBodyShoulders Read the coupled girdle frame, measured A-pose subtraction, thorax-relative world goal and rigid transport of each humeral descendant about the moved joint centre.
 * @evidence ../../../packages/human/src/common/measure/measureHumanSection.ts#measureHumanSection Read the plane cut, edge-keyed crossings, closed-loop chaining, open-chain discard and seed-nearest selection against the analytic box.
 * @evidence ../../../packages/human/src/index.ts#IAutoMovieHumanBodySectionPlane Read the caller-chosen point-normal cutting plane whose positive side includes on-plane vertices.
 * @evidence ../../../packages/human/src/index.ts#IAutoMovieHumanBodySectionPlane.point Read the metre point the signed vertex distance is measured from.
 * @evidence ../../../packages/human/src/index.ts#IAutoMovieHumanBodySectionPlane.normal Read the direction that signs vertex distance and seeds the orthonormal hull frame.
 * @evidence ../../../packages/human/src/index.ts#IAutoMovieHumanBodySectionReading Read the seed-nearest closed loop's readings, or null when no closed loop exists.
 * @evidence ../../../packages/human/src/index.ts#IAutoMovieHumanBodySectionReading.perimeter Read the contour length summed through every concavity of the loop.
 * @evidence ../../../packages/human/src/index.ts#IAutoMovieHumanBodySectionReading.girth Read the convex-hull perimeter in the plane, the tape girth that bridges concavities.
 * @evidence ../../../packages/human/src/index.ts#IAutoMovieHumanBodySectionReading.breadth Read the loop's X extent, maximum minus minimum crossing X.
 * @evidence ../../../packages/human/src/index.ts#IAutoMovieHumanBodySectionReading.back Read the loop's minimum crossing Z, rearmost because the body faces +Z.
 * @evidence ../../../packages/human/src/index.ts#IAutoMovieHumanBodySectionReading.centroid Read the mean crossing point that ranks loops by distance to the seed.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyShapeRowState.ts#IAutoMovieHumanBodyShapeRowState Read the admitted weights and corrective activations the row sum reads in channel order, then activation order.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyShapeRowState.ts#IAutoMovieHumanBodyShapeRowState.weights Read the signed channel weight map whose sign selects the endpoint and whose magnitude is the gain.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyShapeRowState.ts#IAutoMovieHumanBodyShapeRowState.activations Read the ordered corrective list applied after every channel endpoint.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyCorrectiveActivation.ts#IAutoMovieHumanBodyCorrectiveActivation Read the corrective target and activation pair produced by the weight owner and skipped at zero.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyCorrectiveActivation.ts#IAutoMovieHumanBodyCorrectiveActivation.target Read the corrective row-target name looked up among the evaluated row targets.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyCorrectiveActivation.ts#IAutoMovieHumanBodyCorrectiveActivation.activation Read the multiplier applied to every offset of the target when positive.
 * @evidence ../../../packages/human/src/body/basis/createHumanBodyUnderwear.ts#createHumanBodyUnderwear Read the coverage field on the body at rest: the waistband height, the leg line from the crotch within the gusset out to the outer hip's depth blended from back to front, the bra band blended from back to front by depth with the straps, and the uncovered arm skin at a metre per unit of weight; the clip at the field's zero with crossings held 5% inside an edge and shared by its two triangles, the lift along the posed normals, the refusals, and the part and material it emits after the skin.
 * @evidence ../../../packages/human/src/body/basis/closeHumanBodyUnderwearCreases.ts#closeHumanBodyUnderwearCreases Read the closing of the skin by a ball of half the span against two blocks with a slit: the wall points of a narrow slit reach the ball's arc, a wider slit keeps its walls, a mid slit stays within the arc's sag, and a flat top, a hollow cell, an empty garment and an oversized grid behave as stated.
 * @evidence ../../../packages/human/src/body/basis/measureHumanBodyDistanceField.ts#measureHumanBodyDistanceField Read the exact squared distance and nearest site against a brute-force minimum on a scattered grid, the corner case, and the empty-site convention.
 * @evidence ../../../packages/human/src/body/basis/voxelizeHumanBodySkin.ts#voxelizeHumanBodySkin Read the distance to a flat sheet in cells, the centres of a ball only in the air side and only in the shell, the nearest sample, the clamped voxel of a point, the refusal of an oversized grid and the dense sampling that grows the buffers.
 * @evidence ../../../packages/human/src/body/basis/clusterHumanBodyPoints.ts#clusterHumanBodyPoints Read the chains, pairs, loner and diagonal pair against the cube binning counted by hand.
 * @evidence ../../../packages/human/src/body/basis/createHumanBodyUnderwearCoverage.ts#createHumanBodyUnderwearCoverage Read the field through the garment tests on flat panels: the boxer hem and waistband heights, the briefs' leg line at the crotch, a third out and at the outer hip, the bra band and straps, and the bare arm.
 * @evidence ../../../packages/human/src/body/basis/cutHumanBodyUnderwearSurface.ts#cutHumanBodyUnderwearSurface Read the kept band, the exact crossing heights, the shared crossings and the winding through the garment tests on flat panels.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodySkinVoxels.ts#IAutoMovieHumanBodySkinVoxels Read the voxel queries through the voxel test.
 * @evidence ../../../packages/human/src/body/constants/HUMAN_BODY_UNDERWEAR.ts#HUMAN_BODY_UNDERWEAR Read the landmark names against the basis's MPFB joint cubes and the nipple vertex the bust girth uses, and each fraction against the rendered neutral, female, male, child and heavy bodies at rest and in the editor's presets; a costume table, not a garment standard.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyUnderwear.ts#IAutoMovieHumanBodyUnderwear Read the two styles and the optional colour a document puts on the body.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyUnderwear.ts#IAutoMovieHumanBodyUnderwear.style Read the boxer briefs and the sports bra with briefs the style picks.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyUnderwear.ts#IAutoMovieHumanBodyUnderwear.color Read the optional linear RGB in [0,1] that replaces the table's colour.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyUnderwear.ts#IAutoMovieHumanBodyUnderwear.ITable Read the table form the rules are evaluated from, every height and width a fraction between shaped landmarks.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyUnderwear.ts#IAutoMovieHumanBodyUnderwear.ITable.material Read the garment's material id, refused when the basis uses it.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyUnderwear.ts#IAutoMovieHumanBodyUnderwear.ITable.color Read the default linear fabric colour.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyUnderwear.ts#IAutoMovieHumanBodyUnderwear.ITable.roughness Read the fabric roughness.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyUnderwear.ts#IAutoMovieHumanBodyUnderwear.ITable.offsetMetres Read the lift of the fabric along the posed normal in metres.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyUnderwear.ts#IAutoMovieHumanBodyUnderwear.ITable.uncovered Read the bones whose skin, with every bone below them, is never covered past half a vertex's weight.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyUnderwear.ts#IAutoMovieHumanBodyUnderwear.ITable.landmarks Read the landmark ids the waist, legs, bra band and straps are measured on.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyUnderwear.ts#IAutoMovieHumanBodyUnderwear.ITable.briefs Read each style's waist fraction, the leg line's crotch, front and back depths, and its gusset and outer distances.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodyUnderwear.ts#IAutoMovieHumanBodyUnderwear.ITable.bra Read the nipple skin landmark and the band's bottom, front and back fractions and the strap's centre and half width.
 * @evidence ../../../packages/human/src/body/measure/segmentHumanBodyModel.ts#segmentHumanBodyModel Read the dominant-bone partition against the census: one part per bone in joint order, majority and first-corner tie rules, the UV-seam vertex walk, and the population check that refuses a mismatched build.
 * @evidence ../../../packages/human/src/body/export/exportHumanBody.ts#exportHumanBody Read the static model-only writer and optional candidate-report qualification in the same constructed Document, preserving legacy bytes and unavailable whole anatomy without writing a rig or restoring clinical document controls.
 * @evidence ../../../packages/human/src/body/measure/measureHumanBodyBasisChannels.ts#measureHumanBodyBasisChannels Read the whole-surface RMS accumulation, the empty-population refusal and the rule evaluation through the same shape path the builder uses.
 * @evidence ../../../packages/human/src/body/simple/humanBodySurfaceBoundary.ts#humanBodySurfaceBoundary Read the directed-edge census: an edge whose reverse no triangle owns is a boundary edge, and its endpoints are the ring.
 * @evidence ../../../packages/human/src/body/simple/measureHumanBodyVolume.ts#measureHumanBodyVolume Read the tetrahedron sum, the boundary cap fanned to the loop centroid with the reversed winding, and the absolute value, against the closed and the opened box.
 * @evidence ../../../packages/human/src/body/measure/evaluateHumanBodyMeasurement.ts#evaluateHumanBodyMeasurement Read the one-rule evaluation: landmark distance, and the station walk that keeps the picked closed section, null where the surface cannot answer.
 * @evidence ../../../packages/human/src/body/simple/humanBodySimpleShapeDirection.ts#humanBodySimpleShapeDirection Read the channel-alone and mass directions over their ranges, the envelope-holding wear, the five-fraction sampling that refuses an unmeasurable rule, and the linear solve that refuses beyond the reach it names.
 * @evidence ../../../packages/human/src/body/simple/humanBodySimpleShapeMath.ts#humanBodySimpleShapeMath Read the flat-ended curve, the refusing inversion, the clamped curve inverse, Deurenberg's fat and excess, the parameter record with the body mass index from mass and stature, the term product and Siri's density.
 * @evidence ../../../packages/human/src/body/simple/measureHumanBodySimpleShape.ts#measureHumanBodySimpleShape Read the mass as the whole person's closed volume at a density and the channel rule reading.
 * @evidence ../../../packages/human/src/body/simple/projectHumanBodySimpleShape.ts#projectHumanBodySimpleShape Read the whole person's stature and volume, the mass fixed point over the fat density, the inverse-first-row identity readings with the other muscle rows removed, and the named tape measurements read back.
 * @evidence ../../../packages/human/src/body/simple/expandHumanBodySimpleShape.ts#expandHumanBodySimpleShape Read the envelope and missing-value refusals, the product-of-curves rows with envelope saturation and skipped channels, the three-sample inversions for stature, mass and each named tape measurement that refuse beyond their reach or on a channel that does not grow, and the residual composition over an existing shape.
 * @evidence ../../../packages/human/src/body/constants/HUMAN_BODY_SIMPLE_SHAPE.ts#HUMAN_BODY_SIMPLE_SHAPE Read every row against its pinned source: the age nodes, the sarcopenia gain, the ptosis, apron, android and gynoid curves, the definition gates over excess fat, and the firmness fall.
 * @evidence ../../../packages/human/src/body/constants/HUMAN_BODY_SIMPLE_POSTURE.ts#HUMAN_BODY_SIMPLE_POSTURE Read the kyphosis table against its sources.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodySimplePosture.ts#IAutoMovieHumanBodySimplePosture Read the posture table form.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodySimplePosture.ts#IAutoMovieHumanBodySimplePosture.kyphosis Read the kyphosis entry.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodySimplePosture.ts#IAutoMovieHumanBodySimplePosture.thoracic Read the thoracic shares.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodySimplePosture.ts#IAutoMovieHumanBodySimplePosture.compensation Read the compensating joint.
 * @evidence ../../../packages/human/src/body/simple/humanBodySimplePosture.ts#humanBodySimplePosture Read the posture rows a body's age and sex give.
 * @evidence ../../../packages/human/src/body/constants/HUMAN_BODY_SKIN_RELIEF_POSE.ts#HUMAN_BODY_SKIN_RELIEF_POSE Read the relief-pose table.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodySkinReliefPose.ts#IAutoMovieHumanBodySkinReliefPose Read the relief-pose table form.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodySkinReliefPose.ts#IAutoMovieHumanBodySkinReliefPose.IJoint Read one joint's reach.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodySkinReliefPose.ts#IAutoMovieHumanBodySkinReliefPose.IJoint.bone Read the bone name.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodySkinReliefPose.ts#IAutoMovieHumanBodySkinReliefPose.IJoint.sigmaMetres Read the axial width.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodySkinReliefPose.ts#IAutoMovieHumanBodySkinReliefPose.IJoint.reachMetres Read the reach.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodySkinReliefPose.ts#IAutoMovieHumanBodySkinReliefPose.deepen Read the deepening share.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodySkinReliefPose.ts#IAutoMovieHumanBodySkinReliefPose.flatten Read the flattening share.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodySkinReliefPose.ts#IAutoMovieHumanBodySkinReliefPose.joints Read the joints list.
 * @evidence ../../../packages/human/src/body/basis/humanBodyReliefWeights.ts#humanBodyReliefWeights Read the relief weights a pose gives.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodySimpleShape.ts#IAutoMovieHumanBodySimpleShape Read the five physical parameters and their units.
 * @evidence ../../../packages/human/src/body/structures/IAutoMovieHumanBodySimpleShapeTable.ts#IAutoMovieHumanBodySimpleShapeTable Read the table form: envelope, head allowance, mass model, fat estimate and product-of-curves rows.
 * @evidence ../../../packages/human/src/body/structures/AutoMovieHumanBodySimpleParameter.ts#AutoMovieHumanBodySimpleParameter Read the five parameters and the derived excess fat and developed muscle a curve may be read over.
 * @evidence ../../../packages/human/src/body/document/admitHumanBodyBasisDocument.ts#admitHumanBodyBasisDocument Read exact schema admission, finiteness over named weights, angles and material scalars, nonblank identities and the duplicate-bone refusal.
 * @evidence ../../../packages/human/src/body/document/parseHumanBodyBasisDocument.ts#parseHumanBodyBasisDocument Read the shared UTF-16 envelope, JSON parsing and the admission hand-off.
 * @evidence ../../../packages/human/src/body/document/serializeHumanBodyBasisDocument.ts#serializeHumanBodyBasisDocument Read admission before serialization and the envelope check on the escaped, formatted text.
 */
export const humanBodyStudyReview: humanBodyStudyReview &
  IHumanBodyStudyProvenance = {
  basis: "connected-basis/README.md",
  receipt: "connected-basis/extraction-receipt.json",
  likeness: "unaccepted",
  articularAssetIdentity: "candidate-only",
  sourceConditionedExterior: "candidate-only",
};
