import {
  IAutoMovieProductionRenderManifest,
  IAutoMovieProductionRenderReceipt,
} from "@automovie/interface";
import {
  AutoMovieProductionCompiler,
  AutoMovieProductionProject,
  AutoMovieProductionReviewService,
  canonicalizeAutoMovieJson,
  digestAutoMovieBytes,
  probeProductionMedia,
} from "@automovie/mcp";
import { TestValidator } from "@nestia/e2e";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { PNG } from "pngjs";

import {
  formationDesign,
  modelRecipe,
  productionDesign,
  productionFixture,
  shotContract,
  worldDesign,
} from "./productionFixtures";
import {
  productionAudioMp4,
  productionH264Mp4,
} from "./productionMediaFixtures";

const diagnosticCodes = (
  output: ReturnType<AutoMovieProductionCompiler["compile"]>,
): Set<string> => new Set(output.diagnostics.map((item) => item.code));

/** Source compilation is sandboxed, recoverable and stable after reopen. */
export const test_mcp_production_compiler = async (): Promise<void> => {
  const fixture = productionFixture();
  const sourcePath = path.join(fixture.root, "src/shots/opening.ts");
  const original = fs.readFileSync(sourcePath, "utf8");
  const mutateSourceOutput = (mutation: string): string =>
    original
      .replace(
        "  return {\n    eventSamples:",
        "  const output = {\n    eventSamples:",
      )
      .replace(
        "\n  };\n};\n\n/** Opening",
        `\n  };\n${mutation}\n  return output;\n};\n\n/** Opening`,
      );
  const injectBuildSignal = (...statements: string[]): string =>
    original.replace(
      "): IAutoMovieShotSourceOutput => {",
      ["): IAutoMovieShotSourceOutput => {", ...statements].join("\n"),
    );
  try {
    const project = AutoMovieProductionProject.open(fixture.root);
    const review = new AutoMovieProductionReviewService(project);
    const compiler = new AutoMovieProductionCompiler(project, () =>
      review.queue(),
    );

    const designOnly = compiler.lint({ scope: "design" });
    TestValidator.predicate(
      "read-only design lint does not materialize",
      designOnly.success && designOnly.materialized.length === 0,
    );
    const preexistingGenerated = path.join(
      fixture.root,
      "generated/intruder.txt",
    );
    fs.writeFileSync(preexistingGenerated, "unowned");
    TestValidator.predicate(
      "the first compile refuses preexisting unowned generated bytes",
      diagnosticCodes(compiler.compile({ scope: "source" })).has(
        "generated-unowned",
      ),
    );
    fs.rmSync(preexistingGenerated);
    const first = compiler.compile({ scope: "source" });
    TestValidator.predicate(
      "starter source compiles",
      first.success &&
        first.materialized.some(
          (file) =>
            file.path === "shots/opening.json" && file.status === "created",
        ) &&
        first.reviews.entries.every(
          (entry) => entry.currentFingerprint !== null,
        ),
    );
    const recipeFile = path.join(
      fixture.root,
      ".automovie/design/models/sentinel.json",
    );
    const recipeBytes = fs.readFileSync(recipeFile);
    const recipeWithoutMaterial = JSON.parse(recipeBytes.toString("utf8"));
    recipeWithoutMaterial.palette = {};
    fs.writeFileSync(recipeFile, JSON.stringify(recipeWithoutMaterial));
    const failedMaterialization = compiler.compile({ scope: "source" });
    fs.writeFileSync(recipeFile, recipeBytes);
    TestValidator.predicate(
      "invalid recipe bytes cannot crash compiler-owned model materialization",
      diagnosticCodes(failedMaterialization).has(
        "model-materialization-failed",
      ),
    );
    const generatedManifestPath = path.join(
      fixture.root,
      ".automovie/generated-manifest.json",
    );
    const generatedBeforeDesignGate = fs.readFileSync(
      generatedManifestPath,
      "utf8",
    );
    const compileDesignOnly = compiler.compile({ scope: "design" });
    TestValidator.predicate(
      "design scope never replaces current generated source output",
      compileDesignOnly.success &&
        compileDesignOnly.materialized.length === 0 &&
        fs.readFileSync(generatedManifestPath, "utf8") ===
          generatedBeforeDesignGate &&
        fs.existsSync(path.join(fixture.root, "generated/shots/opening.json")),
    );
    const reopened = new AutoMovieProductionCompiler(
      AutoMovieProductionProject.open(fixture.root),
    ).compile({ scope: "source" });
    TestValidator.predicate(
      "reopen preserves identity and unchanged status",
      reopened.compiler.inputFingerprint === first.compiler.inputFingerprint &&
        reopened.materialized.every((file) => file.status === "unchanged"),
    );
    const canonicalShotBytes = fs.readFileSync(
      path.join(fixture.root, "generated/shots/opening.json"),
      "utf8",
    );
    TestValidator.equals(
      "generated JSON bytes are canonical regardless of source insertion order",
      canonicalShotBytes,
      `${canonicalizeAutoMovieJson(JSON.parse(canonicalShotBytes))}\n`,
    );
    const statusReadGenerated = project.readGeneratedFile;
    project.readGeneratedFile = ((relativePath: string) => {
      if (new Error("status race").stack?.includes("statusesOf"))
        throw new Error("generated status read denied");
      return statusReadGenerated.call(project, relativePath);
    }) as typeof project.readGeneratedFile;
    let statusRaceSurfaced = false;
    try {
      compiler.compile({ scope: "source" });
    } catch (error) {
      statusRaceSurfaced =
        error instanceof Error &&
        error.message.includes("generated status read denied");
    } finally {
      project.readGeneratedFile = statusReadGenerated;
    }
    TestValidator.predicate(
      "non-missing materialization status races remain loud",
      statusRaceSurfaced,
    );
    const viewerInput = path.join(fixture.root, "viewer/src/main.ts");
    const viewerBytes = fs.readFileSync(viewerInput);
    fs.appendFileSync(viewerInput, "\n// content identity mutation\n");
    const changedContent = compiler.lint({ scope: "source" });
    fs.writeFileSync(viewerInput, viewerBytes);
    const restoredContent = compiler.compile({ scope: "source" });
    TestValidator.predicate(
      "declared viewer and runtime content participates in compile identity",
      changedContent.compiler.inputFingerprint !==
        first.compiler.inputFingerprint &&
        diagnosticCodes(changedContent).has("generated-stale") &&
        restoredContent.compiler.inputFingerprint ===
          first.compiler.inputFingerprint,
    );

    const generatedShot = path.join(
      fixture.root,
      "generated/shots/opening.json",
    );
    fs.writeFileSync(generatedShot, "{}\n");
    const tamperedLint = compiler.lint({ scope: "source" });
    TestValidator.predicate(
      "lint refuses direct generated edits",
      tamperedLint.success === false &&
        diagnosticCodes(tamperedLint).has("generated-tampered"),
    );
    const repaired = compiler.compile({ scope: "source" });
    TestValidator.predicate(
      "compile repairs a declared generated file",
      repaired.success &&
        repaired.materialized.some(
          (file) =>
            file.path === "shots/opening.json" && file.status === "updated",
        ) &&
        repaired.diagnostics.some(
          (item) =>
            item.code === "generated-tampered" && item.category === "warning",
        ) &&
        JSON.parse(fs.readFileSync(generatedShot, "utf8")).shot.id ===
          "opening",
    );
    fs.rmSync(generatedShot);
    const missingLint = compiler.lint({ scope: "source" });
    const recreated = compiler.compile({ scope: "source" });
    TestValidator.predicate(
      "lint rejects and compile recreates a missing declared generated file",
      missingLint.diagnostics.some(
        (item) =>
          item.code === "generated-tampered" && item.message.includes("null"),
      ) &&
        recreated.success &&
        recreated.materialized.some(
          (file) =>
            file.path === "shots/opening.json" && file.status === "created",
        ),
    );
    const unowned = path.join(fixture.root, "generated/hand-edited.json");
    fs.writeFileSync(unowned, "{}\n");
    TestValidator.predicate(
      "unowned generated output blocks compilation",
      diagnosticCodes(compiler.compile({ scope: "source" })).has(
        "generated-unowned",
      ),
    );
    fs.rmSync(unowned);
    const currentGeneratedManifest = JSON.parse(
      fs.readFileSync(generatedManifestPath, "utf8"),
    ) as {
      files: Array<{
        path: string;
        owner: "compiler";
        digest: `sha256:${string}`;
        sourceTargets: string[];
      }>;
    };
    const forgedBytes = Buffer.from("{}\n");
    fs.writeFileSync(generatedShot, forgedBytes);
    const forgedManifest = structuredClone(currentGeneratedManifest);
    forgedManifest.files.find(
      (entry) => entry.path === "shots/opening.json",
    )!.digest = digestAutoMovieBytes(forgedBytes);
    fs.writeFileSync(generatedManifestPath, JSON.stringify(forgedManifest));
    const forgedOwnership = compiler.lint({ scope: "source" });
    TestValidator.predicate(
      "a self-consistent forged generated manifest cannot redefine compiler truth",
      diagnosticCodes(forgedOwnership).has("generated-tampered") &&
        diagnosticCodes(forgedOwnership).has("generated-manifest-stale") &&
        compiler.compile({ scope: "source" }).success,
    );
    const stalePath = path.join(fixture.root, "generated/stale-output.json");
    const staleBytes = Buffer.from('{"stale":true}\n');
    const withStale = JSON.parse(
      fs.readFileSync(generatedManifestPath, "utf8"),
    ) as typeof currentGeneratedManifest;
    withStale.files.push({
      path: "stale-output.json",
      owner: "compiler",
      digest: digestAutoMovieBytes(staleBytes),
      sourceTargets: ["compiler"],
    });
    fs.writeFileSync(stalePath, staleBytes);
    fs.writeFileSync(generatedManifestPath, JSON.stringify(withStale));
    const staleDeclaredLint = compiler.lint({ scope: "source" });
    const staleDeclaredCompile = compiler.compile({ scope: "source" });
    TestValidator.predicate(
      "prior compiler-owned files are diagnosed then removed by materialization",
      diagnosticCodes(staleDeclaredLint).has("generated-stale-output") &&
        staleDeclaredCompile.diagnostics.some(
          (diagnostic) =>
            diagnostic.code === "generated-stale-output" &&
            diagnostic.category === "warning",
        ) &&
        fs.existsSync(stalePath) === false,
    );
    const unreadableManifest = JSON.parse(
      fs.readFileSync(generatedManifestPath, "utf8"),
    ) as typeof currentGeneratedManifest;
    unreadableManifest.files.push({
      path: "stale-output.json",
      owner: "compiler",
      digest: digestAutoMovieBytes(staleBytes),
      sourceTargets: ["compiler"],
    });
    fs.writeFileSync(stalePath, staleBytes);
    fs.writeFileSync(generatedManifestPath, JSON.stringify(unreadableManifest));
    const residentGeneratedRead = project.readGeneratedFile;
    project.readGeneratedFile = ((relativePath: string) => {
      if (relativePath === "stale-output.json")
        throw new Error("stale output became unreadable");
      return residentGeneratedRead.call(project, relativePath);
    }) as typeof project.readGeneratedFile;
    const unreadableStale = compiler.lint({ scope: "source" });
    project.readGeneratedFile = residentGeneratedRead;
    fs.rmSync(stalePath);
    compiler.compile({ scope: "source" });
    TestValidator.predicate(
      "unreadable formerly declared output loses compiler ownership",
      diagnosticCodes(unreadableStale).has("generated-unowned"),
    );

    fs.rmSync(sourcePath);
    TestValidator.predicate(
      "missing bound source is diagnosed",
      diagnosticCodes(compiler.compile({ scope: "source" })).has(
        "source-path-missing",
      ),
    );
    fs.writeFileSync(sourcePath, original);
    const outside = {
      ...shotContract(),
      source: { module: "../outside.ts", export: "opening" },
    };
    project.setShotContract(outside);
    TestValidator.predicate(
      "source traversal is diagnosed",
      diagnosticCodes(compiler.compile({ scope: "source" })).has(
        "source-path-outside-root",
      ),
    );
    project.setShotContract(shotContract());

    fs.writeFileSync(
      sourcePath,
      [
        'import "side-effect";',
        'import fs from "node:fs";',
        'import * as runtimeNamespace from "runtime-namespace";',
        'import { type TypeOnly, runtimeName } from "mixed-runtime";',
        "export const opening = { build() {",
        "async function delayed() { return 1; } void delayed;",
        'void import("node:path");',
        "Math.random(); Math.random(); Date.now(); performance.now(); crypto.randomUUID(); Intl.Collator();",
        '"a".localeCompare("b"); "a"["toLocaleUpperCase"]();',
        'process.cwd(); require("x"); fetch("x");',
        "({ process: 1 }).process;",
        "setTimeout(() => {}, 0); setInterval(() => {}, 0);",
        "return {};",
        "} };",
      ].join("\n"),
    );
    const capabilityOutput = compiler.compile({ scope: "source" });
    const capabilities = diagnosticCodes(capabilityOutput);
    TestValidator.predicate(
      "runtime imports, entropy and ambient capabilities are rejected",
      capabilities.has("source-import-unsupported") &&
        capabilities.has("source-nondeterministic") &&
        capabilities.has("source-capability-forbidden") &&
        capabilityOutput.diagnostics.some((diagnostic) =>
          diagnostic.message.includes("Intl"),
        ),
    );
    fs.writeFileSync(
      sourcePath,
      [
        'import type { IAutoMovieScene } from "@automovie/interface";',
        'import { type IAutoMovieShot } from "@automovie/interface";',
        original,
      ].join("\n"),
    );
    TestValidator.predicate(
      "pure type-only imports remain valid coding-agent source",
      compiler.compile({ scope: "source" }).success,
    );
    fs.writeFileSync(
      sourcePath,
      injectBuildSignal(
        '  context.engine.distance.constructor("return process")();',
      ),
    );
    TestValidator.predicate(
      "VM source cannot climb through an injected host function constructor",
      diagnosticCodes(compiler.compile({ scope: "source" })).has(
        "source-execution-failed",
      ),
    );

    fs.writeFileSync(sourcePath, "export const somethingElse = 1;\n");
    TestValidator.predicate(
      "missing named build export is rejected",
      diagnosticCodes(compiler.compile({ scope: "source" })).has(
        "source-export-missing",
      ),
    );
    fs.writeFileSync(
      sourcePath,
      "export const opening = { build() { return Promise.resolve({}); } };\n",
    );
    TestValidator.predicate(
      "async source is rejected",
      diagnosticCodes(compiler.compile({ scope: "source" })).has(
        "source-capability-forbidden",
      ),
    );
    fs.writeFileSync(
      sourcePath,
      "export const opening = { build() { return { then() {} }; } };\n",
    );
    TestValidator.predicate(
      "thenable source results are rejected even without the Promise global",
      diagnosticCodes(compiler.compile({ scope: "source" })).has(
        "source-export-invalid",
      ),
    );
    fs.writeFileSync(
      sourcePath,
      injectBuildSignal("  Promise.resolve().then(() => { while (true) {} });"),
    );
    TestValidator.predicate(
      "Promise microtasks are rejected before VM execution",
      diagnosticCodes(compiler.compile({ scope: "source" })).has(
        "source-capability-forbidden",
      ),
    );
    for (const expression of ["{}", "undefined"]) {
      fs.writeFileSync(
        sourcePath,
        `export const opening = { build() { return ${expression}; } };\n`,
      );
      TestValidator.predicate(
        `structurally invalid source result ${expression} is rejected`,
        diagnosticCodes(compiler.compile({ scope: "source" })).has(
          "source-export-invalid",
        ),
      );
    }
    fs.writeFileSync(
      sourcePath,
      'export const opening = { build() { throw "boom"; } };\n',
    );
    TestValidator.predicate(
      "source exceptions are isolated",
      diagnosticCodes(compiler.compile({ scope: "source" })).has(
        "source-execution-failed",
      ),
    );
    fs.writeFileSync(
      sourcePath,
      'export const opening = { build() { throw { message: "object boom" }; } };\n',
    );
    TestValidator.predicate(
      "object-shaped source exceptions retain their message",
      compiler
        .compile({ scope: "source" })
        .diagnostics.some((item) => item.message.includes("object boom")),
    );
    for (const expression of ["null", "{}"]) {
      fs.writeFileSync(
        sourcePath,
        `export const opening = { build() { throw ${expression}; } };\n`,
      );
      TestValidator.predicate(
        `source exception ${expression} is stringified`,
        diagnosticCodes(compiler.compile({ scope: "source" })).has(
          "source-execution-failed",
        ),
      );
    }
    fs.writeFileSync(
      sourcePath,
      "export const opening = { build() { while (true) {} } };\n",
    );
    TestValidator.predicate(
      "source execution has a hard timeout",
      diagnosticCodes(compiler.compile({ scope: "source" })).has(
        "source-execution-timeout",
      ),
    );
    const getterSource = mutateSourceOutput(
      [
        '  Object.defineProperty(output, "shot", {',
        "    get() { while (true) {} },",
        "  });",
      ].join("\n"),
    );
    fs.writeFileSync(sourcePath, getterSource);
    TestValidator.predicate(
      "returned getters are snapshotted inside the VM timeout",
      diagnosticCodes(compiler.compile({ scope: "source" })).has(
        "source-execution-timeout",
      ),
    );
    fs.writeFileSync(
      sourcePath,
      original.replace("model: model.id,", 'model: "absent-model",'),
    );
    TestValidator.predicate(
      "compiled scenes cannot reference an absent model",
      diagnosticCodes(compiler.compile({ scope: "source" })).has(
        "engine-validation-failed",
      ),
    );
    fs.writeFileSync(sourcePath, "export const opening = { build: ( => 1 };\n");
    TestValidator.predicate(
      "transpile failures are source diagnostics",
      diagnosticCodes(compiler.compile({ scope: "source" })).has(
        "source-transpile-failed",
      ),
    );

    const instrumented = injectBuildSignal(
      "  console.log(context.engine.distance(",
      "    { x: 0, y: 0, z: 0 },",
      "    { x: 3, y: 4, z: 0 },",
      "  ));",
      "  console.warn(context.engine.groundHeight({ x: 1, z: 1 }));",
      "  console.error(context.engine.groundHeight({ x: 99, z: 99 }));",
    );
    fs.writeFileSync(sourcePath, instrumented);
    TestValidator.predicate(
      "constant ground geometry is available in the source oracle",
      compiler.compile({ scope: "source" }).success,
    );
    project.setWorldDesign({
      ...worldDesign(),
      surfaces: [
        {
          ...worldDesign().surfaces[0]!,
          height: {
            kind: "plane",
            originHeight: 1,
            slopeX: 0.1,
            slopeZ: 0.2,
          },
        },
      ],
    });
    fs.writeFileSync(sourcePath, instrumented);
    TestValidator.predicate(
      "explicit geometry helpers run in the frozen sandbox",
      compiler.compile({ scope: "source" }).success,
    );
    project.setWorldDesign(worldDesign());
    fs.writeFileSync(sourcePath, original);

    fs.writeFileSync(
      sourcePath,
      original.replace(
        "    skeleton: model.skeleton.id,\n    duration:",
        '    skeleton: "missing-skeleton",\n    duration:',
      ),
    );
    TestValidator.predicate(
      "motion skeleton references are compiler gates",
      compiler
        .compile({ scope: "source" })
        .diagnostics.some(
          (item) =>
            item.code === "engine-validation-failed" &&
            item.message.includes("missing skeleton"),
        ),
    );
    fs.writeFileSync(sourcePath, original);

    const residentReadSource = project.readSource;
    project.readSource = (() => {
      const iterator = (function* (): Generator<void> {
        yield;
      })();
      iterator.next();
      return iterator.throw("non-error source failure") as never;
    }) as typeof project.readSource;
    TestValidator.predicate(
      "non-Error source failures remain actionable diagnostics",
      compiler
        .compile({ scope: "source" })
        .diagnostics.some((item) =>
          item.message.includes("non-error source failure"),
        ),
    );
    project.readSource = residentReadSource;
    const residentContentInputs = project.contentInputs;
    for (const failure of [
      new Error("declared content junction"),
      "non-error declared content failure",
    ]) {
      project.contentInputs = (() => {
        if (failure instanceof Error) throw failure;
        const iterator = (function* (): Generator<void> {
          yield;
        })();
        iterator.next();
        return iterator.throw(failure) as never;
      }) as typeof project.contentInputs;
      const unsafeContent = compiler.compile({ scope: "source" });
      TestValidator.predicate(
        "declared content inventory failures are compiler diagnostics",
        unsafeContent.diagnostics.some(
          (diagnostic) =>
            diagnostic.code === "content-input-unsafe" &&
            diagnostic.message.includes(
              String(failure instanceof Error ? failure.message : failure),
            ),
        ),
      );
    }
    project.contentInputs = residentContentInputs;
    const residentReadGenerated = project.readGeneratedFile;
    project.readGeneratedFile = (() => {
      const iterator = (function* (): Generator<void> {
        yield;
      })();
      iterator.next();
      return iterator.throw("non-error generated failure") as never;
    }) as typeof project.readGeneratedFile;
    TestValidator.predicate(
      "non-Error generated path failures remain actionable diagnostics",
      compiler
        .lint({ scope: "source" })
        .diagnostics.some(
          (item) =>
            item.code === "generated-path-outside" &&
            item.message.includes("unsafe"),
        ),
    );
    project.readGeneratedFile = residentReadGenerated;

    const durationNeedle = "duration: context.contract.durationSeconds,";
    const durationIndex = original.lastIndexOf(durationNeedle);
    const wrongIdentity = `${original
      .slice(0, durationIndex)
      .replace(
        "id: context.contract.id,",
        'id: "wrong-shot",',
      )}duration: context.contract.durationSeconds - 1,${original.slice(
      durationIndex + durationNeedle.length,
    )}`;
    fs.writeFileSync(sourcePath, wrongIdentity);
    TestValidator.predicate(
      "compiled shot identity and duration are engine gates",
      diagnosticCodes(compiler.compile({ scope: "source" })).has(
        "engine-validation-failed",
      ),
    );
    for (const [name, mutation] of [
      [
        "duplicate-invalid-event-sample",
        [
          "  output.eventSamples[0]!.time = 999;",
          "  output.eventSamples.push({ ...output.eventSamples[0]! });",
        ].join("\n"),
      ],
      ["missing-event-sample", "  output.eventSamples = [];"],
      [
        "false-opening-state",
        "  output.motions[0]!.keyframes[0]!.pose.joints[0]!.abduction = 50;",
      ],
      [
        "false-closing-state",
        "  output.motions[0]!.keyframes[output.motions[0]!.keyframes.length - 1]!.pose.joints[0]!.abduction = 0;",
      ],
      [
        "unreadable-camera",
        "  output.scene.cameras[0]!.transform.translation.x = 100;",
      ],
    ] as const) {
      fs.writeFileSync(sourcePath, mutateSourceOutput(mutation));
      const realizationOutput = compiler.compile({ scope: "source" });
      TestValidator.predicate(
        `compiler-derived contract realization rejects ${name}: ${realizationOutput.diagnostics
          .map((diagnostic) => diagnostic.code)
          .join(",")}`,
        diagnosticCodes(realizationOutput).has("contract-realization-failed"),
      );
    }
    fs.writeFileSync(sourcePath, original);

    TestValidator.predicate(
      "formation witness fixture mutation is accepted",
      project.setModelRecipe({
        ...modelRecipe(),
        id: "formation-sentinel",
        role: "prop",
        archetype: "primitive-prop",
        parameters: { shape: "sphere", radius: 0.25 },
        capabilities: [],
        attachments: [],
      }).accepted &&
        project.setFormationDesign({
          ...formationDesign(),
          modelRecipe: "formation-sentinel",
        }).accepted &&
        project.setShotContract({
          ...shotContract(),
          participants: [
            { kind: "actor", id: "sentinel" },
            { kind: "formation", id: "line" },
          ],
        }).accepted,
    );
    const materializedFormation = compiler.compile({ scope: "source" });
    const formationShot = JSON.parse(
      fs.readFileSync(
        path.join(fixture.root, "generated/shots/opening.json"),
        "utf8",
      ),
    ) as {
      scene: { nodes: Array<{ id: string }> };
    };
    const formationRealization = JSON.parse(
      fs.readFileSync(
        path.join(fixture.root, "generated/realizations/opening.json"),
        "utf8",
      ),
    ) as {
      formations: Array<{ id: string; count: number; passed: boolean }>;
    };
    TestValidator.predicate(
      "formation count, hero identity and realization come from compiler-owned slots",
      materializedFormation.success &&
        formationShot.scene.nodes.some((node) => node.id === "captain") &&
        formationShot.scene.nodes.filter(
          (node) =>
            node.id === "captain" || node.id.startsWith("formation:line:slot:"),
        ).length === 6 &&
        formationRealization.formations.some(
          (formation) =>
            formation.id === "line" &&
            formation.count === 6 &&
            formation.passed,
        ),
    );
    fs.writeFileSync(
      sourcePath,
      mutateSourceOutput(
        [
          "  output.scene.nodes.push({",
          "    ...output.scene.nodes[0]!,",
          '    id: "formation:line:slot:000001",',
          "  });",
        ].join("\n"),
      ),
    );
    TestValidator.predicate(
      "coding-agent source cannot replace an ordinary compiler-owned formation slot",
      diagnosticCodes(compiler.compile({ scope: "source" })).has(
        "contract-realization-failed",
      ),
    );
    fs.writeFileSync(sourcePath, original);
    fs.rmSync(
      path.join(fixture.root, ".automovie/design/formations/line.json"),
    );
    TestValidator.predicate(
      "a physically missing formation design is a reference-graph failure",
      diagnosticCodes(compiler.compile({ scope: "source" })).has(
        "design-reference-missing",
      ),
    );
    project.setFormationDesign({
      ...formationDesign(),
      modelRecipe: "formation-sentinel",
    });
    project.setShotContract(shotContract());
    project.eraseDesignArtifact(
      { kind: "formation", id: "line" },
      "restore the one-shot compiler fixture after formation witness coverage",
    );
    project.eraseDesignArtifact(
      { kind: "model", id: "formation-sentinel" },
      "remove the formation-only recipe after witness coverage",
    );

    const fingerprints = {
      currentFingerprint: null,
      storedFingerprint: null,
    } as const;
    const reviewGate = new AutoMovieProductionCompiler(project, () => ({
      entries: [
        {
          target: { kind: "source", path: "src/shots/opening.ts" },
          state: "missing",
          ...fingerprints,
        },
        {
          target: { kind: "shot", id: "opening" },
          state: "stale",
          ...fingerprints,
        },
        {
          target: { kind: "film", id: "fixture-film" },
          state: "revise",
          ...fingerprints,
        },
        {
          target: {
            kind: "design",
            design: { kind: "model", id: "sentinel" },
          },
          state: "incomplete",
          ...fingerprints,
        },
        {
          target: {
            kind: "design",
            design: { kind: "production" },
          },
          state: "complete",
          ...fingerprints,
        },
        {
          target: { kind: "design", design: { kind: "world" } },
          state: "complete",
          ...fingerprints,
        },
      ],
    }));
    const reviewCodes = diagnosticCodes(
      reviewGate.compile({ scope: "review" }),
    );
    TestValidator.predicate(
      "review compile maps every queue state to a hard gate",
      [
        "review-missing",
        "review-stale",
        "review-revise",
        "review-incomplete",
      ].every((code) => reviewCodes.has(code)),
    );

    const requiredProduction = {
      ...productionDesign(),
      deliverables: [
        {
          id: "required-feature" as const,
          kind: "feature" as const,
          required: true,
        },
      ],
    };
    project.setProductionDesign(requiredProduction);
    const finalCompiler = new AutoMovieProductionCompiler(project);
    const missingRender = finalCompiler.compile({ scope: "final" });
    const renderManifestPath = path.join(
      fixture.root,
      ".automovie/render-manifest.json",
    );
    const renderReceiptPath = path.join(
      fixture.root,
      ".automovie/render-manifest-receipt.json",
    );
    fs.writeFileSync(renderManifestPath, "{}");
    const unownedRender = finalCompiler.compile({ scope: "final" });
    fs.writeFileSync(
      renderReceiptPath,
      JSON.stringify({
        version: 2,
        manifestDigest: digestAutoMovieBytes(Buffer.from("{}")),
        files: [],
      }),
    );
    const invalidRender = finalCompiler.compile({ scope: "final" });
    fs.writeFileSync(renderManifestPath, "{bad");
    fs.writeFileSync(
      renderReceiptPath,
      JSON.stringify({
        version: 2,
        manifestDigest: digestAutoMovieBytes(Buffer.from("{bad")),
        files: [],
      }),
    );
    const malformedRender = finalCompiler.compile({ scope: "final" });
    fs.rmSync(renderManifestPath);
    fs.mkdirSync(renderManifestPath);
    const unsafeRender = finalCompiler.compile({ scope: "final" });
    fs.rmdirSync(renderManifestPath);
    const featurePath = "deliverables/required-feature.mp4";
    const featureFrameCount = Math.round(
      requiredProduction.targetRuntimeSeconds *
        requiredProduction.frameFormat.fps,
    );
    const featureBytes = await productionH264Mp4({
      width: requiredProduction.frameFormat.width,
      height: requiredProduction.frameFormat.height,
      fps: requiredProduction.frameFormat.fps,
      frameCount: featureFrameCount,
    });
    fs.mkdirSync(path.join(fixture.root, "renders/deliverables"), {
      recursive: true,
    });
    fs.writeFileSync(
      path.join(fixture.root, "renders", featurePath),
      featureBytes,
    );
    const fakeFeaturePath = "deliverables/fake-feature.mp4";
    const fakeFeatureBytes = Buffer.from("this is not an MP4 container");
    fs.writeFileSync(
      path.join(fixture.root, "renders", fakeFeaturePath),
      fakeFeatureBytes,
    );
    const currentFingerprint = unsafeRender.compiler.inputFingerprint;
    const completeRenderManifest = {
      version: 1 as const,
      compileFingerprint: currentFingerprint,
      deliverables: [
        {
          id: "required-feature",
          kind: "feature" as const,
          files: [
            {
              path: featurePath,
              digest: digestAutoMovieBytes(featureBytes),
              bytes: featureBytes.length,
              mediaType: "video/mp4",
            },
          ],
          runtimeSeconds: requiredProduction.targetRuntimeSeconds,
          frameCount: featureFrameCount,
          codec: "h264",
        },
      ],
    };
    const fakeMediaCommitRefused = (() => {
      try {
        project.commitProductionRenderManifest({
          ...completeRenderManifest,
          deliverables: completeRenderManifest.deliverables.map(
            (deliverable) => ({
              ...deliverable,
              files: [
                {
                  path: fakeFeaturePath,
                  digest: digestAutoMovieBytes(fakeFeatureBytes),
                  bytes: fakeFeatureBytes.length,
                  mediaType: "video/mp4",
                },
              ],
            }),
          ),
        });
        return false;
      } catch {
        return true;
      }
    })();
    project.commitProductionRenderManifest(completeRenderManifest);
    fs.writeFileSync(renderReceiptPath, "{bad");
    const malformedReceipt = finalCompiler.compile({ scope: "final" });
    project.commitProductionRenderManifest({
      ...completeRenderManifest,
      compileFingerprint:
        "sha256:ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
    });
    const staleRender = finalCompiler.compile({ scope: "final" });
    project.commitProductionRenderManifest({
      ...completeRenderManifest,
      deliverables: [],
    });
    const incompleteRender = finalCompiler.compile({ scope: "final" });
    const mismatchedCommitRefused = (() => {
      try {
        project.commitProductionRenderManifest({
          ...completeRenderManifest,
          deliverables: completeRenderManifest.deliverables.map(
            (deliverable) => ({
              ...deliverable,
              files: deliverable.files.map((file) => ({
                ...file,
                digest:
                  "sha256:eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
              })),
            }),
          ),
        });
        return false;
      } catch {
        return true;
      }
    })();
    project.commitProductionRenderManifest(completeRenderManifest);
    fs.appendFileSync(
      path.join(fixture.root, "renders", featurePath),
      Buffer.from([0]),
    );
    const mismatchedRender = finalCompiler.compile({ scope: "final" });
    fs.writeFileSync(
      path.join(fixture.root, "renders", featurePath),
      featureBytes,
    );
    project.commitProductionRenderManifest(completeRenderManifest);
    TestValidator.predicate(
      "final compile requires an aggregate deliverable manifest",
      diagnosticCodes(missingRender).has("render-deliverable-missing"),
    );
    TestValidator.predicate(
      "final compile rejects direct aggregate manifest edits",
      diagnosticCodes(unownedRender).has("render-deliverable-unowned"),
    );
    TestValidator.predicate(
      "final compile rejects malformed renderer receipts",
      diagnosticCodes(malformedReceipt).has("render-deliverable-unowned"),
    );
    TestValidator.predicate(
      "final compile rejects an invalid aggregate deliverable manifest",
      diagnosticCodes(invalidRender).has("render-deliverable-invalid"),
    );
    TestValidator.predicate(
      "final compile rejects malformed aggregate deliverable JSON",
      diagnosticCodes(malformedRender).has("render-deliverable-invalid"),
    );
    TestValidator.predicate(
      "final compile rejects unsafe aggregate deliverable paths",
      diagnosticCodes(unsafeRender).has("render-deliverable-unowned"),
    );
    TestValidator.predicate(
      "final compile rejects a stale aggregate compile fingerprint",
      diagnosticCodes(staleRender).has("render-deliverable-stale"),
    );
    TestValidator.predicate(
      "final compile requires every declared deliverable",
      diagnosticCodes(incompleteRender).has("render-deliverable-missing"),
    );
    TestValidator.predicate(
      "renderer commit and final compile both reject byte-mismatched deliverables",
      mismatchedCommitRefused &&
        diagnosticCodes(mismatchedRender).has("render-deliverable-stale"),
    );
    TestValidator.predicate(
      "final compile accepts complete byte-exact aggregate deliverables",
      fakeMediaCommitRefused &&
        finalCompiler.compile({ scope: "final" }).success,
    );
    const edgeAudioBytes = productionAudioMp4();
    const edgeAudioProbe = probeProductionMedia({
      kind: "audio-mix",
      mediaType: "audio/mp4",
      bytes: edgeAudioBytes,
    });
    if (edgeAudioProbe.kind !== "audio")
      throw new Error("The compiler edge fixture requires parsed AAC audio.");
    const edgeProduction = {
      ...productionDesign(),
      targetRuntimeSeconds: edgeAudioProbe.runtimeSeconds,
    };
    edgeProduction.deliverables = [
      { id: "feature-runtime", kind: "feature", required: true },
      { id: "preview-runtime", kind: "preview", required: false },
      { id: "feature-frame", kind: "feature", required: false },
      { id: "captions-frame", kind: "captions", required: false },
      { id: "captions-invalid", kind: "captions", required: false },
      { id: "feature-codec", kind: "feature", required: false },
      { id: "guide-codec", kind: "guide-pass", required: false },
      { id: "audio-codec", kind: "audio-mix", required: false },
      { id: "audio-runtime", kind: "audio-mix", required: false },
      { id: "audio-valid", kind: "audio-mix", required: false },
      { id: "audio-missing", kind: "audio-mix", required: false },
      { id: "preview-codec", kind: "preview", required: false },
      { id: "invalid-file", kind: "preview", required: false },
      { id: "empty-files", kind: "preview", required: false },
      { id: "duplicate-file-owner", kind: "preview", required: false },
      { id: "missing-file", kind: "preview", required: false },
      { id: "kind-mismatch", kind: "captions", required: false },
    ];
    TestValidator.predicate(
      "final semantic edge production compiles",
      project.setProductionDesign(edgeProduction).accepted &&
        finalCompiler.compile({ scope: "source" }).success,
    );
    const edgeFingerprint = finalCompiler.lint({ scope: "source" }).compiler
      .inputFingerprint;
    type RenderedDeliverable =
      IAutoMovieProductionRenderManifest["deliverables"][number];
    const previewImage = new PNG({
      width: edgeProduction.frameFormat.width,
      height: edgeProduction.frameFormat.height,
    });
    previewImage.data.fill(180);
    previewImage.data[0] = 0;
    const previewBytes = PNG.sync.write(previewImage);
    const captionBytes = Buffer.from(
      "WEBVTT\n\n00:00:00.000 --> 00:00:06.000\nSignal raised.\n",
      "utf8",
    );
    const edgeFile = (id: string, kind: RenderedDeliverable["kind"]) => {
      const medium =
        kind === "feature" || kind === "guide-pass"
          ? {
              extension: "mp4",
              bytes: featureBytes,
              mediaType: "video/mp4",
            }
          : kind === "audio-mix"
            ? {
                extension: "m4a",
                bytes: edgeAudioBytes,
                mediaType: "audio/mp4",
              }
            : kind === "captions"
              ? {
                  extension: "vtt",
                  bytes: captionBytes,
                  mediaType: "text/vtt",
                }
              : {
                  extension: "png",
                  bytes: previewBytes,
                  mediaType: "image/png",
                };
      const relative = `deliverables/final-edges/${id}.${medium.extension}`;
      const absolute = path.join(fixture.root, "renders", relative);
      fs.mkdirSync(path.dirname(absolute), { recursive: true });
      fs.writeFileSync(absolute, medium.bytes);
      return {
        path: relative,
        digest: digestAutoMovieBytes(medium.bytes),
        bytes: medium.bytes.length,
        mediaType: medium.mediaType,
      };
    };
    const validRendered = (
      id: string,
      kind: RenderedDeliverable["kind"],
    ): RenderedDeliverable => {
      const timed = ["feature", "guide-pass", "captions", "audio-mix"].includes(
        kind,
      );
      const framed = kind === "feature" || kind === "guide-pass";
      const encoded =
        kind === "feature" || kind === "guide-pass" || kind === "audio-mix";
      return {
        id,
        kind,
        files: [edgeFile(id, kind)],
        runtimeSeconds: timed ? edgeProduction.targetRuntimeSeconds : null,
        frameCount: framed
          ? Math.round(
              edgeProduction.targetRuntimeSeconds *
                edgeProduction.frameFormat.fps,
            )
          : null,
        codec:
          kind === "audio-mix"
            ? edgeAudioProbe.codec
            : encoded
              ? "edge-codec"
              : null,
      };
    };
    const invalidDeliverables = edgeProduction.deliverables.map((contract) =>
      validRendered(contract.id, contract.kind),
    );
    const edge = (id: string): RenderedDeliverable =>
      invalidDeliverables.find((deliverable) => deliverable.id === id)!;
    edge("feature-runtime").runtimeSeconds =
      edgeProduction.targetRuntimeSeconds / 2;
    edge("preview-runtime").runtimeSeconds = 0;
    edge("feature-frame").frameCount = 0;
    edge("captions-frame").frameCount = 0;
    edge("feature-codec").codec = null;
    edge("guide-codec").codec = null;
    edge("audio-codec").codec = null;
    edge("audio-runtime").runtimeSeconds =
      edgeProduction.targetRuntimeSeconds / 2;
    edge("audio-missing").files = [];
    edge("preview-codec").codec = "";
    edge("empty-files").files = [];
    edge("kind-mismatch").kind = "preview";
    edge("kind-mismatch").files = [];
    const duplicateFileManifest: IAutoMovieProductionRenderManifest = {
      version: 1,
      compileFingerprint: edgeFingerprint,
      deliverables: [
        structuredClone(edge("invalid-file")),
        {
          ...structuredClone(edge("duplicate-file-owner")),
          files: [
            {
              ...edge("invalid-file").files[0]!,
              path: edge("invalid-file").files[0]!.path.toUpperCase(),
            },
          ],
        },
      ],
    };
    const duplicateFileCommitRefused = (() => {
      try {
        project.commitProductionRenderManifest(duplicateFileManifest);
        return false;
      } catch {
        return true;
      }
    })();
    const invalidFileManifest: IAutoMovieProductionRenderManifest = {
      version: 1,
      compileFingerprint: edgeFingerprint,
      deliverables: [
        {
          ...structuredClone(edge("invalid-file")),
          files: [
            {
              ...edge("invalid-file").files[0]!,
              bytes: 0,
              mediaType: "",
            },
          ],
        },
      ],
    };
    const invalidFileCommitRefused = (() => {
      try {
        project.commitProductionRenderManifest(invalidFileManifest);
        return false;
      } catch {
        return true;
      }
    })();
    const duplicateDeliverable = {
      ...structuredClone(edge("feature-runtime")),
      files: [],
    };
    const edgeManifest: IAutoMovieProductionRenderManifest = {
      version: 1,
      compileFingerprint: edgeFingerprint,
      deliverables: [
        ...invalidDeliverables,
        duplicateDeliverable,
        validRendered("undeclared", "preview"),
      ],
    };
    project.commitProductionRenderManifest(edgeManifest);
    const edgeReceipt = JSON.parse(
      fs.readFileSync(renderReceiptPath, "utf8"),
    ) as IAutoMovieProductionRenderReceipt;
    const writeReceipt = (receipt: IAutoMovieProductionRenderReceipt): void => {
      fs.writeFileSync(renderReceiptPath, JSON.stringify(receipt));
    };
    const restoreEdgeLedger = (): void => {
      project.commitProductionRenderManifest(edgeManifest);
    };
    writeReceipt({
      ...edgeReceipt,
      files: [...edgeReceipt.files, structuredClone(edgeReceipt.files[0]!)],
    });
    const duplicateReceiptRender = finalCompiler.compile({ scope: "final" });
    restoreEdgeLedger();
    writeReceipt({
      ...edgeReceipt,
      files: edgeReceipt.files.map((file, index) =>
        index === 0 ? { ...file, deliverable: "wrong-owner" } : file,
      ),
    });
    const mismatchedReceiptRender = finalCompiler.compile({ scope: "final" });
    restoreEdgeLedger();
    writeReceipt({
      ...edgeReceipt,
      files: edgeReceipt.files.map((file) => ({
        ...file,
        probe:
          file.probe.kind === "video" || file.probe.kind === "png"
            ? { ...file.probe, width: file.probe.width + 1 }
            : file.probe,
      })),
    });
    const staleProbeRender = finalCompiler.compile({ scope: "final" });
    restoreEdgeLedger();
    writeReceipt({
      ...edgeReceipt,
      files: [
        ...edgeReceipt.files,
        {
          ...structuredClone(edgeReceipt.files[0]!),
          path: "deliverables/final-edges/receipt-only.png",
        },
      ],
    });
    const receiptOnlyRender = finalCompiler.compile({ scope: "final" });
    restoreEdgeLedger();
    const probeFailureFile = edge("invalid-file").files[0]!;
    const probeFailurePath = path.join(
      fixture.root,
      "renders",
      probeFailureFile.path,
    );
    const probeFailureBytes = fs.readFileSync(probeFailurePath);
    fs.writeFileSync(probeFailurePath, "not a PNG");
    const currentProbeFailure = finalCompiler.compile({ scope: "final" });
    fs.writeFileSync(probeFailurePath, probeFailureBytes);
    restoreEdgeLedger();
    const captionFailureFile = edge("captions-invalid").files[0]!;
    const captionFailurePath = path.join(
      fixture.root,
      "renders",
      captionFailureFile.path,
    );
    const captionFailureBytes = fs.readFileSync(captionFailurePath);
    fs.writeFileSync(captionFailurePath, "not WebVTT");
    const currentCaptionFailure = finalCompiler.compile({ scope: "final" });
    fs.writeFileSync(captionFailurePath, captionFailureBytes);
    restoreEdgeLedger();
    const writeDirectLedger = (
      manifest: IAutoMovieProductionRenderManifest,
    ): void => {
      const manifestBytes = Buffer.from(`${JSON.stringify(manifest)}\n`);
      fs.writeFileSync(renderManifestPath, manifestBytes);
      writeReceipt({
        ...edgeReceipt,
        manifestDigest: digestAutoMovieBytes(manifestBytes),
      });
    };
    const duplicateOwnedManifest = structuredClone(edgeManifest);
    const duplicateOwner = duplicateOwnedManifest.deliverables.find(
      (deliverable) => deliverable.id === "duplicate-file-owner",
    )!;
    duplicateOwner.files = [
      {
        ...edge("invalid-file").files[0]!,
        path: edge("invalid-file").files[0]!.path.toUpperCase(),
      },
    ];
    writeDirectLedger(duplicateOwnedManifest);
    const duplicateOwnedRender = finalCompiler.compile({ scope: "final" });
    restoreEdgeLedger();
    const invalidEntryManifest = structuredClone(edgeManifest);
    const invalidEntry = invalidEntryManifest.deliverables.find(
      (deliverable) => deliverable.id === "invalid-file",
    )!.files[0]!;
    invalidEntry.bytes = 0;
    invalidEntry.mediaType = "";
    writeDirectLedger(invalidEntryManifest);
    const invalidEntryRender = finalCompiler.compile({ scope: "final" });
    restoreEdgeLedger();
    fs.rmSync(
      path.join(fixture.root, "renders", edge("missing-file").files[0]!.path),
    );
    const semanticRender = finalCompiler.compile({ scope: "final" });
    const residentRenderRead = project.readRenderFile;
    project.readRenderFile = ((relativePath: string) => {
      if (relativePath.endsWith("/missing-file.png")) {
        const iterator = (function* (): Generator<void> {
          yield;
        })();
        iterator.next();
        return iterator.throw("non-error render read failure") as never;
      }
      return residentRenderRead.call(project, relativePath);
    }) as typeof project.readRenderFile;
    const nonErrorRenderRead = finalCompiler.compile({ scope: "final" });
    project.readRenderFile = residentRenderRead;
    TestValidator.predicate(
      `final ledger rejects duplicate, undeclared, incomplete and unreadable outputs: duplicate=${duplicateFileCommitRefused}, invalid=${invalidFileCommitRefused}, duplicateReceipt=${[...diagnosticCodes(duplicateReceiptRender)]}, mismatchedReceipt=${[...diagnosticCodes(mismatchedReceiptRender)]}, staleProbe=${[...diagnosticCodes(staleProbeRender)]}, receiptOnly=${[...diagnosticCodes(receiptOnlyRender)]}, probeFailure=${[...diagnosticCodes(currentProbeFailure)]}, duplicateOwned=${[...diagnosticCodes(duplicateOwnedRender)]}, invalidEntry=${[...diagnosticCodes(invalidEntryRender)]}, semantic=${semanticRender.diagnostics
        .map((diagnostic) => diagnostic.code)
        .join(",")}, nonError=${nonErrorRenderRead.diagnostics
        .map((diagnostic) => `${diagnostic.code}:${diagnostic.message}`)
        .join("|")}`,
      duplicateFileCommitRefused &&
        invalidFileCommitRefused &&
        diagnosticCodes(duplicateReceiptRender).has(
          "render-deliverable-unowned",
        ) &&
        diagnosticCodes(mismatchedReceiptRender).has(
          "render-deliverable-unowned",
        ) &&
        diagnosticCodes(staleProbeRender).has("render-deliverable-unowned") &&
        diagnosticCodes(receiptOnlyRender).has("render-deliverable-unowned") &&
        diagnosticCodes(currentProbeFailure).has(
          "render-deliverable-invalid",
        ) &&
        currentCaptionFailure.diagnostics.some(
          (diagnostic) =>
            diagnostic.code === "render-deliverable-media-mismatch" &&
            diagnostic.message.includes(
              'Caption deliverable "captions-invalid"',
            ),
        ) &&
        diagnosticCodes(duplicateOwnedRender).has(
          "render-deliverable-invalid",
        ) &&
        diagnosticCodes(invalidEntryRender).has("render-deliverable-invalid") &&
        [
          "render-deliverable-invalid",
          "render-deliverable-incomplete",
          "render-deliverable-missing",
        ].every((code) => diagnosticCodes(semanticRender).has(code)) &&
        nonErrorRenderRead.diagnostics.some(
          (diagnostic) =>
            diagnostic.code === "render-deliverable-missing" &&
            diagnostic.message.includes("non-error render read failure"),
        ),
    );
    project.eraseDesignArtifact({ kind: "production" });
    TestValidator.predicate(
      "final diagnostics tolerate an absent production while design owns error",
      diagnosticCodes(finalCompiler.compile({ scope: "final" })).has(
        "design-missing",
      ),
    );
    TestValidator.predicate(
      "mutation consequences retain a film target without production metadata",
      project
        .setWorldDesign(worldDesign())
        .consequences.staleReviews.some(
          (target) => target.kind === "film" && target.id === "film",
        ),
    );
    project.setProductionDesign(productionDesign());

    project.eraseDesignArtifact({ kind: "world" });
    fs.writeFileSync(sourcePath, instrumented);
    TestValidator.predicate(
      "missing world uses the bounded empty source context before design refusal",
      diagnosticCodes(compiler.compile({ scope: "source" })).has(
        "design-missing",
      ),
    );
    fs.writeFileSync(sourcePath, original);
    project.setWorldDesign(worldDesign());

    const noDesignRoot = fs.mkdtempSync(
      path.join(os.tmpdir(), "automovie-production-empty-"),
    );
    try {
      const empty = new AutoMovieProductionCompiler(
        AutoMovieProductionProject.open(noDesignRoot),
      ).compile({ scope: "design" });
      TestValidator.predicate(
        "empty repository reports all required design classes",
        empty.success === false &&
          empty.diagnostics.filter((item) => item.code === "design-missing")
            .length === 3,
      );
    } finally {
      fs.rmSync(noDesignRoot, { force: true, recursive: true });
    }
  } finally {
    fixture.dispose();
  }
};
