/**
 * Package-local ledger for delivery contract units the render media surface does
 * not implement.
 *
 * This surface owns four things: the output profiles that say what a delivered
 * picture, video and audio stream must be, the parsers that read those facts back
 * out of bytes, the writers that assemble and splice containers without decoding
 * them, and the occurrence key that joins a repaint lane to a timeline. It owns
 * no mixer, no project store, no provider transaction and no human judgment, so
 * every unit below names the owner that does.
 *
 * @evidenceExclude requirements/delivery-and-accessibility/audio-streams-and-channels.md#delivery-audio-downmix The ordered downmix coefficients and resample stages are recorded by the audio decode that reads the source bytes; these profiles receive an already mixed stream and never see a source channel.
 * @evidenceExclude requirements/delivery-and-accessibility/audio-streams-and-channels.md#delivery-audio-mix-versions Full mix, dialogue, music-and-effects, clean audio, description and alternate-language products are a delivery set the blocking prototype does not produce; this surface judges the one deterministic master it does.
 * @evidenceExclude requirements/delivery-and-accessibility/audio-streams-and-channels.md#delivery-audio-refusal Refusing a stream whose duration, digest or plan binding contradicts the current sound plan is production's sound-evidence verifier, which holds both sides of that comparison; a sample-entry profile cannot see a plan.
 * @evidenceExclude requirements/delivery-and-accessibility/audio-streams-and-channels.md#delivery-audio-sample-boundary The first and last audible sample indices come from the render job plan's conversion of cue film time onto the fixed audio clock; this surface reads the timebase an encoded stream already carries.
 * @evidenceExclude requirements/delivery-and-accessibility/audio-streams-and-channels.md#delivery-audio-silence Separating authored silence, a missing source, a failed decode and not-run is production's sound-evidence verifier; an Opus sample entry carries no state that distinguishes them.
 * @evidenceExclude requirements/delivery-and-accessibility/audio-streams-and-channels.md#delivery-loudness-profile Integrated loudness, range, peak and tolerance are a destination policy the prototype does not model, and no measurement of them exists in this surface to compare against one.
 * @evidenceExclude requirements/delivery-and-accessibility/containers-codecs-and-media-facts.md#delivery-encoding-tool-identity The encoder package, version, closure digest and argument set are fenced into the render job plan's runtime identity; a container profile reads what was written, never which tool wrote it.
 * @evidenceExclude requirements/delivery-and-accessibility/containers-codecs-and-media-facts.md#delivery-media-fact-refusal Refusing a planned-versus-actual media fact mismatch by row and field is production's render-manifest row check, which is the only place that holds a manifest row beside a probe record.
 * @evidenceExclude requirements/delivery-and-accessibility/containers-codecs-and-media-facts.md#delivery-stream-duration-interleave Comparing each delivered row's duration and timebase against the plan is that same production manifest row check; this surface reports a stream's own presentation extent without a plan to check it against.
 * @evidenceExclude requirements/sound/validation-and-delivery.md#sound-evidence-identity-freshness Binding sound evidence to the compile, plan and stream identities it was measured from, and staling it when one changes, is production's sound-evidence verifier and its publication currentness.
 * @evidenceExclude requirements/sound/validation-and-delivery.md#sound-evidence-status Reporting planned, rendered, probed and not-run as distinct sound states is that verifier's result shape; this surface either returns container facts or throws.
 * @evidenceExclude requirements/sound/validation-and-delivery.md#sound-delivery-inventory The inventory that closes every required sound product for a delivery is assembled by production's publication join from the plan and the manifest, not from one stream's sample entry.
 * @evidenceExclude requirements/sound/validation-and-delivery.md#sound-picture-delivery-join Joining the audible master to the picture it ships with is production's non-video deliverable verifier, which reads both deliverables; this surface probes one byte stream at a time.
 * @evidenceExclude requirements/sound/validation-and-delivery.md#sound-numeric-verification Hand-computed fixture verification and negative twins are the repository test corpus and its review procedure, not a runtime export of this package.
 * @evidenceExclude requirements/sound/validation-and-delivery.md#sound-budget-evidence Per-tier audio budget accounting is not computed anywhere in the prototype; the profiles here record sample facts without a cost bound to charge them against.
 * @evidenceExclude requirements/sound/validation-and-delivery.md#sound-audible-review Whether a mix sounds right is settled by listening, which is a human review step the shipped review procedure owns; no profile comparison can answer it.
 * @evidenceExclude requirements/sound/validation-and-delivery.md#sound-seek-chunk-equivalence Proving a seek and a chunked render produce the same sound is the engine sound runtime's sampling equivalence together with the render job plan's chunk partition; container profiles see neither a seek nor a chunk.
 * @evidenceExclude specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-sync-refusal-contract Refusing an audio-visual duration mismatch by row, rather than trimming or padding a stream into agreement, is production's render-manifest row check, which is the only holder of both streams' planned facts.
 * @evidenceExclude specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-processing-chain-and-stable-summation The ordered processing chain and its stable summation are the engine sound mixer's; this surface admits the mixed result and reads its encoded identity.
 * @evidenceExclude specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-mix-automation-sample-clock Automation evaluated on the sample clock belongs to that same engine mixer, which is the only component that holds per-sample gain state.
 * @evidenceExclude specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-stem-master-relation-contract The stem-to-master relation is declared where the stems are produced, in the engine mixer and the project's sound runtime; a delivered master carries no stem lineage for a profile to check.
 * @evidenceExclude specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-loudness-peak-and-mix-failure Loudness and peak measurement, and the mix failures they raise, require the decoded programme the engine mixer produced; this surface never decodes audio samples.
 * @evidenceExclude specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-event-sync-and-boundary-continuity Event sync and boundary continuity across cues are resolved on the film clock by the render job plan and the engine sound runtime before any container exists.
 * @evidenceExclude specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#sound-conform-dependency-invalidation Invalidating a conformed mix when a dependency changes is production's publication currentness, which is the only holder of the previous generation's identity.
 * @evidenceExclude specifications/simulation-effects-and-sound/mix-stems-loudness-and-av-join.md#audio-visual-duration-and-timebase-join The exact rational duration join between picture and sound is asserted by production's render-manifest row check; the mux proves its two inputs share a runtime, which is the narrower fact claimed under chunk assembly.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-generation-provider-choice Choosing a generator and its model is the generated project's repaint configuration; this surface conforms bytes that an already selected provider returned.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-generation-credential-boundary Credential separation and the external transfer boundary live in production's repaint service and the project configuration that holds the secret; no credential reaches a container writer.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-generation-attempt-identity Request, attempt and result identities are minted and stored by production's repaint attempt records; a splice reads clip bytes and knows nothing of the attempt that produced them.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-generation-reproducibility Seed semantics and the determinism claim of a generator are recorded in production's repaint provenance, which is where a nondeterministic result must be declared as such.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-generation-adoption-output Adopting a generated result into the project store is production's repaint adoption; this surface answers only whether the adopted bytes can be spliced losslessly.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-generation-adoption-failures Classifying an adoption failure and preserving the failed attempt is that same production adoption path, which owns the records a failure has to survive in.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-repaint-eligibility-source-lock Repaint eligibility and the source lock it depends on are decided by production against the current compile and render receipts, before any clip exists to conform.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-repaint-manual-routing Routing a shot to repaint is an explicit user choice the generated project's configuration carries; nothing in this surface selects a lane, it only refuses one it cannot splice.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-repaint-execution-eligibility Execution eligibility and input binding are checked by production's repaint service at request time; the conform writer sees only the bytes that execution returned.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-repaint-controls-references Appearance requests, reference roles and their bounds are authored in the project's repaint configuration and validated by production; they leave no trace in a conformed container.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-repaint-attempt-selection Attempt, retry and adoption lineage are production's repaint records; a splice is handed one selected clip per occurrence and cannot see the candidates it beat.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-repaint-structure-continuity Structural comparison between a source render and a repainted result is production's visual change and repaint observation surface, which holds both revisions; this one holds one clip's samples.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-repaint-output-provenance Rendition output provenance is written into production's repaint receipt beside the adopted bytes; the conform writer preserves those bytes and records nothing about where they came from.
 * @evidenceExclude specifications/asset-and-representation/generated-assets-and-repaint-handoff.md#asset-spec-repaint-derivation-validation Validating a derivation chain and refusing a broken one needs the parent records production keeps; a container writer can only refuse bytes it cannot splice without decoding.
 */
export const AUTOMOVIE_RENDER_MEDIA_EVIDENCE_EXCLUSIONS =
  "render-media-evidence-exclusions" as const;
