import type {
  IAutoMovieCompileProjectOutput,
  IAutoMovieDiagnostic,
  IAutoMovieGeneratedManifest,
} from "@automovie/interface";
import type { IAutoMovieProductionDesignGraph } from "@automovie/production";
import type {
  IAutoMovieProjectState,
  IAutoMovieProjectStateFreshness,
  closeAutoMovieProjectState,
} from "automovie";

/** Compile observations and read order for an already loaded in-memory snapshot. */
export const createProjectStateClosureFixture = () => {
  const manifest: IAutoMovieGeneratedManifest = {
    version: 1,
    compiler: { packageVersion: "1", protocolVersion: "1" },
    inputFingerprint: `sha256:${"a".repeat(64)}`,
    files: [],
  };
  const initial: IAutoMovieCompileProjectOutput = {
    success: true,
    revision: 7,
    compiler: { version: "1", inputFingerprint: manifest.inputFingerprint },
    diagnostics: [],
    materialized: [],
  };
  const first = structuredClone(initial);
  const second = structuredClone(initial);
  const design: IAutoMovieProductionDesignGraph = {
    production: null,
    models: new Map(),
    world: null,
    formations: new Map(),
    shots: new Map(),
    acceptance: new Map(),
  };
  const endingDesign = structuredClone(design);
  const events: string[] = [];
  const revisions = [7, 7];
  const compilations = [first, second];
  let revisionIndex = 0;
  let compileIndex = 0;
  const input: Parameters<typeof closeAutoMovieProjectState>[0] = {
    revision: 7,
    manifest,
    manifestReadFailed: false,
    compileStatus: initial,
    problems: [],
    design,
    read: {
      revision: () => {
        events.push("revision");
        return revisions[revisionIndex++]!;
      },
      compile: () => {
        events.push("compile");
        return compilations[compileIndex++]!;
      },
      design: () => {
        events.push("design");
        return endingDesign;
      },
      manifest: () => {
        events.push("manifest");
        return structuredClone(manifest);
      },
    },
  };
  return {
    input,
    initial,
    first,
    second,
    manifest,
    endingDesign,
    events,
    revisions,
  };
};

/** A compiler-owned file failure whose identity is independent of source input. */
export const projectStateClosureTamperDiagnostic =
  (): IAutoMovieDiagnostic => ({
    code: "generated-tampered",
    category: "error",
    phase: "compile",
    target: "generated",
    path: "models/subject.json",
    message: "Generated bytes changed after the snapshot read. Recompile them.",
  });

/** Inject one failure into the ordered closing reads without an operating system. */
export const projectStateClosureReadFailure = (
  read: Parameters<typeof closeAutoMovieProjectState>[0]["read"],
  failure: number,
) => {
  let readIndex = 0;
  const reached: string[] = [];
  const wrap =
    <T>(name: string, next: () => T): (() => T) =>
    () => {
      reached.push(name);
      if (readIndex++ === failure)
        throw failure % 2 === 0
          ? new Error(`read ${failure} failed`)
          : `read ${failure} failed`;
      return next();
    };
  return {
    reached,
    read: {
      revision: wrap("revision", read.revision),
      compile: wrap("compile", read.compile),
      design: wrap("design", read.design),
      manifest: wrap("manifest", read.manifest),
    },
  };
};

/** Incomplete loaded evidence supplied to the unchanged current-only refusal. */
export const projectStateWithClosureFailure = (
  freshness: IAutoMovieProjectStateFreshness,
): IAutoMovieProjectState => {
  const fixture = createProjectStateClosureFixture();
  return {
    root: "project",
    productionId: "production",
    revision: 7,
    freshness,
    design: fixture.input.design,
    generated: {
      kind: "film",
      manifest: fixture.manifest,
      library: null,
      libraryEnvironments: new Map(),
      libraryContexts: new Map(),
      registry: null,
      design: fixture.input.design,
      models: new Map(),
      shots: new Map(),
      film: null,
    },
  };
};
