/**
 * The person editor's static markup: one canvas, one status line, one
 * history toolbar and file actions for the whole person, then a body section
 * and a face section (the body section fills its own group select). Each
 * section carries its own `basis-controls`,
 * `control-kind` and help elements as `data-role` attributes, not ids, so
 * the reused body and face control owners query their own section root and
 * the page keeps unique ids. The status line and the admission report sit
 * outside the editing fieldset, so they are readable in every state; the
 * panel enables the fieldset when its controls are mounted and decides each
 * button from its session state.
 *
 * @evidence requirements/actors/body-authoring/contract.md#actor-body-editor Lays out the body section with its history, file and export actions for the whole person.
 * @evidence requirements/actors/facial-authoring/contract.md#actor-face-editor Lays out the face section beside the body section on the same screen.
 * @evidence specifications/asset-and-representation/body-authoring/contract.md#body-spec-editor-view Provides the body section's group select and control containers.
 * @evidence specifications/asset-and-representation/facial-authoring/contract.md#face-spec-editor-view Provides the face section's control containers.
 * @author Samchon
 */
export function connectedPersonPanelMarkup(): string {
  return `
<style>
*{box-sizing:border-box}body{margin:0;background:#161c23;color:#e4eaf0;font:13px/1.5 system-ui}main{display:grid;grid-template-columns:minmax(300px,1fr) 450px;height:100vh}section{position:relative;min-width:0}canvas{width:100%;height:100%;display:block}aside{overflow:auto;padding:20px;background:#10161d}h1{font-size:20px;margin:0}h2{font-size:14px;margin:20px 0 8px}p,small{color:#a9b7c8}button,input,select,textarea{font:inherit;color:inherit;background:#202b37;border:1px solid #405063;border-radius:4px}button{padding:5px 8px;cursor:pointer}button:disabled{opacity:.4}a{color:#a7d1f0}.toolbar{display:flex;gap:6px;flex-wrap:wrap;margin:10px 0}.views{position:absolute;top:10px;left:10px;right:10px}fieldset{border:0;padding:0;margin:0}.row{margin:12px 0}.row label{display:block}.row div{display:flex;gap:10px}.row small{display:block;font-size:11px}.row input[type=range]{flex:1;min-width:0}.row input[type=number]{width:85px;padding:3px}textarea{width:100%;height:230px;font:11px monospace;padding:8px}select{width:100%;padding:6px}#person-status{white-space:pre-wrap;background:#1c2834;padding:10px;border-radius:5px;margin:12px 0}#person-status[data-state=error]{background:#422127;color:#ffd2d2}#person-status[data-state=draft]{background:#3d3320;color:#ffe6b0}#admission-report pre{white-space:pre-wrap;max-height:320px;overflow:auto;background:#1c2834;padding:10px;border-radius:5px;font:11px monospace}@media(max-width:780px){main{grid-template-columns:1fr;height:auto}section{height:60vh}}
</style>
<main><section><canvas id="person-canvas"></canvas><div class="toolbar views"><button data-view="0">Front</button><button data-view="45">Left ¾</button><button data-view="-45">Right ¾</button><button data-view="90">Left</button><button data-view="-90">Right</button><button data-view="180">Back</button><button id="fit-view">Fit</button><label><input id="clay" type="checkbox"> Clay</label><label><input id="shadows" type="checkbox" checked> Shadows</label></div></section>
<aside><h1>Connected person editor</h1><p>One person on one connected skin: the face owns the head, the body owns the rest, and one document records both.</p><p><a href="connected-body.html">Body editor</a> · <a href="connected-face.html">Face editor</a></p><div id="person-status" role="status">Loading the person generation…</div>
<fieldset id="editing" disabled><div class="toolbar"><button id="person-undo">Undo</button><button id="person-redo">Redo</button><button id="person-reset">Reset</button><button id="person-discard">Return to accepted person</button></div><div class="toolbar"><button id="person-save">Save document</button><button id="person-load">Load document</button><button id="person-glb">Export GLB</button><input id="person-file" type="file" accept=".json,application/json" hidden></div>
<details id="catalogue-section" open><summary>Numerical input catalogue</summary><p>Every input whose owner publishes a descriptor, with that owner's unit and range. A range the owner has not published is shown as not supplied.</p><div data-role="input-catalogue"></div></details>
<div id="body-section"><h2>Body</h2><p>Age, sex, weight and muscle are the body's macros and shape the head too. Measurements in millimetres, joints in clinical degrees.</p><details><summary>Simple body measurements</summary><p>Read on this person's current rest skin. Sex and muscle are legacy appearance coordinates; inferred mass is the source owner's volume-density estimate. These values establish no personal tissue or clinical forecast. Applying changes shape and keeps the current pose.</p><div data-role="person-simple-controls"></div></details><h2>Person measurements</h2><div data-role="person-measurements"></div><h2>Humeral heads</h2><div data-role="humeral-heads"></div><div class="toolbar"><button id="person-anatomy">Check skin contacts and humeral heads</button></div><h2>Pose presets</h2><div id="pose-presets" class="toolbar"></div><select data-role="control-kind" aria-label="Body control group"></select><div data-role="basis-controls"></div></div>
<div id="face-section"><h2>Face</h2><h2>Head measurements</h2><div data-role="head-measurements"></div><h2>Eyes, lashes and optics</h2><div data-role="eye-controls"></div><h2>Skin relief</h2><div data-role="skin-relief-controls"></div><h2>Oral assembly</h2><div data-role="oral-controls"></div><h2>Face anatomy</h2><div data-role="face-anatomy"></div><h2>Expression presets</h2><div id="expression-presets" class="toolbar"></div><select data-role="control-kind" aria-label="Face control group"><option value="shape">Face shape</option><option value="expression">Expression</option></select><p data-role="control-help"></p><div data-role="basis-controls"></div></div>
<details><summary>Document JSON · save and inspect</summary><p>The named measurement and choice controls author the supported traits. JSON preserves the complete saved document, including legacy styling fields; it supplies no additional supported shaping capability. Applying a file or this text uses the same admission and keeps the displayed person if refused.</p><textarea id="document-json" aria-label="Complete person document"></textarea><button id="document-apply">Apply document</button><small id="document-unapplied"></small></details></fieldset><div id="admission-report"></div></aside></main>`;
}
