import type { IAutoMovieModelPart } from "@automovie/interface";

import { areaWeightedNormals } from "../../../common/mesh/areaWeightedNormals";
import { createMetricMeshPart } from "../../mesh/createMetricMeshPart";
import { extractTriangleRegion } from "../../mesh/extractTriangleRegion";
import { assertPortraitInteriorBindings } from "../../surface/assertPortraitInteriorBindings";
import { sealPortraitContactSeams } from "../../surface/sealPortraitContactSeams";
import type { IPortraitComponent } from "../../surface/structures/IPortraitComponent";
import type { IPortraitComponentHost } from "../../surface/structures/IPortraitComponentHost";
import type { IPortraitSurfaceLayer } from "../../surface/structures/IPortraitSurfaceLayer";
import { preparePortraitHead } from "./preparePortraitHead";
import { type IPortraitHeadFormation } from "./structures/IPortraitHeadFormation";

export type { IPortraitHeadPerformance } from "./structures/IPortraitHeadPerformance";

/**
 * Materialize a connected head and its dependent anatomical interiors.
 * preparePortraitHead owns unchanged-host fitting, attachment, continuation,
 * refinement, layers, replacements and final proposals. This consumer seals
 * declared contacts, prepares native interiors, then computes one shared normal
 * field and packs each material region. Native providers and legacy finishers
 * read that same final surface; each component is generated by only one path.
 * Native bindings are admitted together before packing: declared joins require
 * exact resident coordinates and named cycles must follow directed mesh edges.
 *
 * Host, source and refined positions use millimetres. Part packing converts
 * geometry to model units through createMetricMeshPart. Resident vertex IDs survive
 * sealing even when its index equivalence removes coincident seam faces.
 * Linear skin colours use per-corner values when contact welding preserved
 * distinct material samples. Independent interiors receive no stale normals.
 * The caller's host is retained and each call constructs new output arrays.
 *
 * @evidence contracts/common.md#principled-implementation After preparation the declared contacts are sealed, interiors are prepared against the sealed skin and admitted together, and one shared normal field is computed by area weighting before each material region is packed, so every finisher reads the same final surface and each component is generated by only one path.
 * @evidence contracts/common.md#clear-and-simple-design Prepare, seal, stage interiors, compute normals, pack regions; each step has a named owner.
 * @evidence contracts/common.md#prohibited-implementation-shortcuts No provider is special-cased and no interior is generated twice.
 * @evidence contracts/common.md#meaningful-documentation States the phase order, the units (millimetres until createMetricMeshPart converts to model metres) and the colour rule at welded seams.
 * @evidence contracts/modeling.md#spatial-conventions Head millimetres until the single createMetricMeshPart conversion to model metres.
 * @evidence contracts/modeling.md#shared-boundaries Declared joins require exact resident coordinates before packing and the sealed skin is what every native interior reads.
 * @evidenceExclude contracts/anatomy.md#anatomical-source buildPortraitHead carries no anatomical value, range, proportion, landmark or tissue behaviour.
 * @evidenceExclude contracts/anatomy.md#permitted-range buildPortraitHead admits, bounds and combines no anatomical value.
 * @evidenceExclude contracts/anatomy.md#parametric-authority buildPortraitHead defines no input through which a caller shapes a human form.
 */
export function buildPortraitHead(
  host: IPortraitComponentHost,
  components: IPortraitComponent[],
  rounds: number,
  surfaceLayers: readonly IPortraitSurfaceLayer[] = [],
  anatomy: IPortraitHeadFormation = {},
) {
  const { surface, regions, finishers, source } = preparePortraitHead(
    host,
    components,
    rounds,
    surfaceLayers,
    anatomy,
  );
  const refined = sealPortraitContactSeams(
    surface,
    finishers.flatMap((attached) => attached.closures ?? []),
  );
  // Preserve each producer's native units and indices until every selected
  // interior is available. This is a preparation boundary, not a joint solve;
  // providers read the sealed skin and must not modify it or one another.
  const interiors = finishers.map((attached) =>
    attached.prepareInteriors?.(refined),
  );
  assertPortraitInteriorBindings(
    refined,
    interiors.flatMap((parts) => parts ?? []),
  );
  const packed = refined.positions.flat(),
    normals = areaWeightedNormals(packed, refined.indices);
  const parts: IAutoMovieModelPart[] = [];
  for (let group = 0; group < regions.length; group++) {
    const selected: number[] = [];
    const colors: number[][] | undefined =
      refined.colors === undefined || regions[group].material !== "skin"
        ? undefined
        : [];
    for (let i = 0; i < refined.groups.length; i++)
      if (refined.groups[i] === group) {
        selected.push(...refined.indices.slice(i * 3, i * 3 + 3));
        if (colors !== undefined)
          colors.push(
            ...(refined.cornerColors === undefined
              ? refined.indices
                  .slice(i * 3, i * 3 + 3)
                  .map((id) => refined.colors![id])
              : refined.cornerColors.slice(i * 3, i * 3 + 3)),
          );
      }
    if (selected.length !== 0)
      parts.push(
        createMetricMeshPart(
          regions[group].id,
          extractTriangleRegion(packed, normals, selected, colors),
          regions[group].material,
        ),
      );
  }
  for (let i = 0; i < finishers.length; ++i) {
    const native = interiors[i];
    parts.push(
      ...(native === undefined
        ? finishers[i].finish(refined)
        : native.map(({ id, mesh, material }) =>
            createMetricMeshPart(id, mesh, material),
          )),
    );
  }
  return { parts, refined, source };
}
