import {
  type ITtscEvidenceGraphConfig,
  type ITtscEvidenceGraphReference,
  evidence,
} from "@ttsc/evidence";
import type { ITtscLintConfig } from "@ttsc/lint";

const contractReferences = (files: string[]): ITtscEvidenceGraphReference[] => [
  {
    type: "markdown" as const,
    root: "../../docs",
    files: files.filter((file) => file.endsWith("/README.md")),
    symbol: ["h2", "h3"],
  },
  {
    type: "markdown" as const,
    root: "../../docs",
    files: files.filter((file) => !file.endsWith("/README.md")),
    symbol: ["h3"],
  },
];

/**
 * Public MCP contracts are grouped by the product boundary they implement.
 *
 * Exact document files keep each population honest: a storage primitive does
 * not inherit every review promise, and the guide-delivery surface does not
 * become the implementation owner for compiler or publication behavior.
 */
const graph: ITtscEvidenceGraphConfig = {
  claims: [
    {
      name: "mcp knowledge and external-service requirements",
      type: "typescript",
      files: [
        "src/AutoMovieApplication.ts",
        "src/createAutoMovieMcpServer.ts",
        "src/production/AutoMovieProductionContext.ts",
        "src/production/AutoMovieProductionGuideService.ts",
        "src/production/AutoMovieProductionRepaintService.ts",
      ],
      symbol: ["type", "function", "property"],
      reference: contractReferences([
        "requirements/agent-authoring/README.md",
        "requirements/agent-authoring/capability-discovery.md",
        "requirements/agent-authoring/mcp-boundary.md",
        "requirements/product/README.md",
        "requirements/product/capability-and-content.md",
        "requirements/product/charter.md",
        "requirements/product/choice-and-external-services.md",
        "requirements/product/scope-and-exclusions.md",
        "requirements/repaint/README.md",
        "requirements/repaint/identity-and-provenance.md",
        "requirements/repaint/prompts-controls-and-constraints.md",
        "requirements/repaint/providers-models-and-credentials.md",
        "requirements/repaint/scope-and-user-choice.md",
        "requirements/repaint/source-frames-and-reference-locking.md",
        "requirements/repaint/structural-comparison-and-review.md",
      ]),
    },
    {
      name: "mcp knowledge and external-service specifications",
      type: "typescript",
      files: [
        "src/AutoMovieApplication.ts",
        "src/createAutoMovieMcpServer.ts",
        "src/production/AutoMovieProductionContext.ts",
        "src/production/AutoMovieProductionGuideService.ts",
        "src/production/AutoMovieProductionRepaintService.ts",
      ],
      symbol: ["type", "function", "property"],
      reference: contractReferences([
        "specifications/asset-and-representation/README.md",
        "specifications/asset-and-representation/generated-assets-and-repaint-handoff.md",
        "specifications/authoring-and-authority/README.md",
        "specifications/authoring-and-authority/capability-and-content-boundary.md",
        "specifications/authoring-and-authority/delegation-and-decision-authority.md",
        "specifications/authoring-and-authority/external-execution-and-provider-neutrality.md",
        "specifications/authoring-and-authority/knowledge-evidence-and-tool-boundary.md",
        "specifications/authoring-and-authority/prototype-determinism-and-fidelity.md",
      ]),
    },
    {
      name: "mcp review and acceptance requirements",
      type: "typescript",
      files: [
        "src/production/acceptanceScope.ts",
        "src/production/AutoMovieProductionOracleService.ts",
        "src/production/AutoMovieProductionReviewService.ts",
      ],
      symbol: ["type", "function", "property"],
      reference: contractReferences([
        "requirements/acceptance/README.md",
        "requirements/acceptance/approval-exceptions-and-publication.md",
        "requirements/acceptance/criteria-and-observables.md",
        "requirements/acceptance/evidence-and-freshness.md",
        "requirements/acceptance/profiles-and-aggregation.md",
        "requirements/acceptance/scope-targets-and-authority.md",
        "requirements/acceptance/uncertainty-and-partial-success.md",
        "requirements/review/README.md",
        "requirements/review/annotations-findings-and-verdicts.md",
        "requirements/review/approval-rejection-and-waivers.md",
        "requirements/review/criteria-and-comparison.md",
        "requirements/review/defect-classification.md",
        "requirements/review/records-and-completeness.md",
        "requirements/review/reproducible-context.md",
        "requirements/review/scope-and-authority.md",
      ]),
    },
    {
      name: "mcp review and acceptance specifications",
      type: "typescript",
      files: [
        "src/production/acceptanceScope.ts",
        "src/production/AutoMovieProductionOracleService.ts",
        "src/production/AutoMovieProductionReviewService.ts",
      ],
      symbol: ["type", "function", "property"],
      reference: contractReferences([
        "specifications/review-and-acceptance/README.md",
        "specifications/review-and-acceptance/approval-waiver-and-publication.md",
        "specifications/review-and-acceptance/criteria-tolerance-and-comparison.md",
        "specifications/review-and-acceptance/evidence-freshness-and-completeness.md",
        "specifications/review-and-acceptance/observations-findings-and-defects.md",
        "specifications/review-and-acceptance/profiles-aggregation-and-partial-results.md",
        "specifications/review-and-acceptance/target-scope-and-context.md",
        "specifications/review-and-acceptance/verdict-authority-and-dissent.md",
      ]),
    },
    {
      name: "mcp compiler and authored-source requirements",
      type: "typescript",
      files: [
        "src/convert.ts",
        "src/dto.ts",
        "src/production/AutoMovieProductionCompiler.ts",
        "src/production/filmTimeline.ts",
        "src/production/linkProductionSource.ts",
        "src/production/materializeProduction.ts",
        "src/production/productionArchetypes.ts",
        "src/production/sandboxEngineBridge.ts",
        "src/production/sandboxEngineSurface.ts",
        "src/production/validateProductionDesign.ts",
      ],
      symbol: ["type", "function", "property"],
      reference: contractReferences([
        "requirements/agent-authoring/README.md",
        "requirements/agent-authoring/partial-work.md",
        "requirements/agent-authoring/project-ownership.md",
        "requirements/agent-authoring/source-owned-loop.md",
        "requirements/production-design/README.md",
        "requirements/production-design/continuity-change-and-deliverables.md",
        "requirements/production-design/scope-and-source-of-truth.md",
      ]),
    },
    {
      name: "mcp compiler and authored-source specifications",
      type: "typescript",
      files: [
        "src/convert.ts",
        "src/dto.ts",
        "src/production/AutoMovieProductionCompiler.ts",
        "src/production/filmTimeline.ts",
        "src/production/linkProductionSource.ts",
        "src/production/materializeProduction.ts",
        "src/production/productionArchetypes.ts",
        "src/production/sandboxEngineBridge.ts",
        "src/production/sandboxEngineSurface.ts",
        "src/production/validateProductionDesign.ts",
      ],
      symbol: ["type", "function", "property"],
      reference: contractReferences([
        "specifications/authoring-and-authority/README.md",
        "specifications/authoring-and-authority/partial-targets-and-atomic-results.md",
        "specifications/authoring-and-authority/source-authority-and-derivation.md",
      ]),
    },
    {
      name: "mcp building-interior scope requirements",
      type: "typescript",
      files: [
        "src/production/AutoMovieProductionCompiler.ts",
        "src/production/AutoMovieProductionGuideService.ts",
      ],
      symbol: ["type", "function", "property"],
      reference: contractReferences([
        "requirements/interior/README.md",
        "requirements/interior/scope-and-host-boundary.md",
      ]),
    },
    {
      name: "mcp building-interior scope specifications",
      type: "typescript",
      files: [
        "src/production/AutoMovieProductionCompiler.ts",
        "src/production/AutoMovieProductionGuideService.ts",
      ],
      symbol: ["type", "function", "property"],
      reference: contractReferences([
        "specifications/interior-space/README.md",
        "specifications/interior-space/scope-and-host.md",
      ]),
    },
    {
      name: "mcp diagnostic requirements",
      type: "typescript",
      files: [
        "src/production/AutoMovieProductionCompiler.ts",
        "src/production/diagnosticCatalog.ts",
        "src/production/designReferenceDiagnostics.ts",
        "src/production/filmGrammarDiagnostics.ts",
        "src/production/screenplayLedgerDiagnostics.ts",
        "src/production/screenplayProseDiagnostics.ts",
        "src/production/storySyncDiagnostics.ts",
        "src/production/validateProductionDesign.ts",
        "src/validators/**/*.ts",
      ],
      symbol: ["type", "function", "property"],
      reference: contractReferences([
        "requirements/diagnostics/README.md",
        "requirements/diagnostics/budgets-and-limits.md",
        "requirements/diagnostics/collection-fail-fast-and-determinism.md",
        "requirements/diagnostics/identity-path-and-context.md",
        "requirements/diagnostics/input-and-result-classification.md",
        "requirements/diagnostics/localization-and-machine-results.md",
        "requirements/diagnostics/partial-artifacts-and-recovery.md",
      ]),
    },
    {
      name: "mcp diagnostic specifications",
      type: "typescript",
      files: [
        "src/production/AutoMovieProductionCompiler.ts",
        "src/production/diagnosticCatalog.ts",
        "src/production/designReferenceDiagnostics.ts",
        "src/production/filmGrammarDiagnostics.ts",
        "src/production/screenplayLedgerDiagnostics.ts",
        "src/production/screenplayProseDiagnostics.ts",
        "src/production/storySyncDiagnostics.ts",
        "src/production/validateProductionDesign.ts",
        "src/validators/**/*.ts",
      ],
      symbol: ["type", "function", "property"],
      reference: contractReferences([
        "specifications/validation-and-diagnostics/README.md",
        "specifications/validation-and-diagnostics/budget-and-truncation.md",
        "specifications/validation-and-diagnostics/classification-and-causality.md",
        "specifications/validation-and-diagnostics/collection-order-and-termination.md",
        "specifications/validation-and-diagnostics/diagnostic-identity-location-and-severity.md",
        "specifications/validation-and-diagnostics/localization-and-machine-results.md",
        "specifications/validation-and-diagnostics/partial-artifacts-and-refusal.md",
      ]),
    },
    {
      name: "mcp external identity and adoption requirements",
      type: "typescript",
      files: [
        "src/production/assetAcquisition.ts",
        "src/production/AutoMovieLegacyImporter.ts",
        "src/production/contentIdentity.ts",
        "src/production/decodeProductionAudioAsset.ts",
        "src/production/inspectDesignReferenceAsset.ts",
        "src/production/trimProductionAudioPresentation.ts",
      ],
      symbol: ["type", "function", "property"],
      reference: contractReferences([
        "requirements/evidence-and-provenance/README.md",
        "requirements/evidence-and-provenance/canonical-digests-and-content-identity.md",
        "requirements/evidence-and-provenance/generation-transformation-and-derivation.md",
        "requirements/evidence-and-provenance/third-party-sources-rights-and-attribution.md",
        "requirements/external-inputs/README.md",
        "requirements/external-inputs/adoption-modes-and-composition.md",
        "requirements/external-inputs/conversion-receipts-and-determinism.md",
        "requirements/external-inputs/credentials-rights-and-provenance.md",
        "requirements/external-inputs/identity-coordinates-and-units.md",
        "requirements/external-inputs/source-selection-and-provider-neutrality.md",
        "requirements/external-inputs/validation-and-quarantine.md",
      ]),
    },
    {
      name: "mcp external identity and adoption specifications",
      type: "typescript",
      files: [
        "src/production/assetAcquisition.ts",
        "src/production/AutoMovieLegacyImporter.ts",
        "src/production/contentIdentity.ts",
        "src/production/decodeProductionAudioAsset.ts",
        "src/production/inspectDesignReferenceAsset.ts",
        "src/production/trimProductionAudioPresentation.ts",
      ],
      symbol: ["type", "function", "property"],
      reference: contractReferences([
        "specifications/evidence-and-provenance/README.md",
        "specifications/evidence-and-provenance/canonical-digests-and-content-identity.md",
        "specifications/evidence-and-provenance/generation-transformation-and-derivation.md",
        "specifications/evidence-and-provenance/third-party-sources-rights-and-attribution.md",
        "specifications/interchange-and-adoption/README.md",
        "specifications/interchange-and-adoption/adoption-decisions-and-composition.md",
        "specifications/interchange-and-adoption/conversion-receipts-and-determinism.md",
        "specifications/interchange-and-adoption/identity-coordinates-and-units.md",
        "specifications/interchange-and-adoption/provenance-rights-and-secrets.md",
        "specifications/interchange-and-adoption/validation-and-quarantine.md",
      ]),
    },
    {
      name: "mcp project-state and recovery requirements",
      type: "typescript",
      files: [
        "src/project/**/*.ts",
        "src/production/AutoMovieLegacyImporter.ts",
        "src/production/AutoMovieProductionProject.ts",
        "src/production/openAutoMovieProduction.ts",
        "src/production/rootNamespaceLock.ts",
      ],
      symbol: ["type", "function", "property"],
      reference: contractReferences([
        "requirements/operations-and-recovery/README.md",
        "requirements/operations-and-recovery/concurrent-runs-and-locking.md",
        "requirements/operations-and-recovery/failure-modes-and-recovery.md",
        "requirements/operations-and-recovery/idempotency-and-side-effects.md",
        "requirements/operations-and-recovery/migration-and-compatibility.md",
        "requirements/operations-and-recovery/partial-artifacts-and-publication.md",
        "requirements/operations-and-recovery/scope-job-identity-and-state.md",
      ]),
    },
    {
      name: "mcp project-state and recovery specifications",
      type: "typescript",
      files: [
        "src/project/**/*.ts",
        "src/production/AutoMovieLegacyImporter.ts",
        "src/production/AutoMovieProductionProject.ts",
        "src/production/openAutoMovieProduction.ts",
        "src/production/rootNamespaceLock.ts",
      ],
      symbol: ["type", "function", "property"],
      reference: contractReferences([
        "specifications/execution-and-recovery/README.md",
        "specifications/execution-and-recovery/artifacts-and-atomic-publication.md",
        "specifications/execution-and-recovery/concurrent-ownership-and-locking.md",
        "specifications/execution-and-recovery/failure-reconciliation-and-disaster-recovery.md",
        "specifications/execution-and-recovery/portability-migration-and-compatibility.md",
        "specifications/execution-and-recovery/retry-backoff-and-idempotency.md",
        "specifications/execution-and-recovery/scope-and-execution-identities.md",
      ]),
    },
    {
      name: "mcp render and publication requirements",
      type: "typescript",
      files: [
        "src/production/captureRuntimeIdentity.ts",
        "src/production/muxProductionFeatureMp4.ts",
        "src/production/probeProductionMedia.ts",
        "src/production/productionPublicationSnapshot.ts",
        "src/production/productionRegistry.ts",
        "src/production/productionRenderGc.ts",
        "src/production/productionRenderJob.ts",
        "src/production/renderIdentity.ts",
        "src/production/renditionIdentity.ts",
      ],
      symbol: ["type", "function", "property"],
      reference: contractReferences([
        "requirements/delivery-and-accessibility/README.md",
        "requirements/delivery-and-accessibility/integrity-provenance-and-authenticity.md",
        "requirements/delivery-and-accessibility/packages-manifests-and-dependencies.md",
        "requirements/delivery-and-accessibility/publication-and-retention.md",
        "requirements/operations-and-recovery/README.md",
        "requirements/operations-and-recovery/partial-artifacts-and-publication.md",
        "requirements/operations-and-recovery/resource-budgets-and-backpressure.md",
        "requirements/operations-and-recovery/retention-and-cleanup.md",
        "requirements/operations-and-recovery/scope-job-identity-and-state.md",
        "requirements/repaint/README.md",
        "requirements/repaint/identity-and-provenance.md",
        "requirements/repaint/sequence-continuity-and-publication.md",
        "requirements/rendering/README.md",
        "requirements/rendering/budgets.md",
        "requirements/rendering/chunks-resume-and-recovery.md",
        "requirements/rendering/encoding-and-multiplexing.md",
        "requirements/rendering/frame-identity-and-content-addressing.md",
        "requirements/rendering/frame-schedules-and-sampling.md",
        "requirements/rendering/headless-and-platform-determinism.md",
        "requirements/rendering/scope-and-artifact-identity.md",
        "requirements/rendering/validation.md",
      ]),
    },
    {
      name: "mcp render and publication specifications",
      type: "typescript",
      files: [
        "src/production/captureRuntimeIdentity.ts",
        "src/production/muxProductionFeatureMp4.ts",
        "src/production/probeProductionMedia.ts",
        "src/production/productionPublicationSnapshot.ts",
        "src/production/productionRegistry.ts",
        "src/production/productionRenderGc.ts",
        "src/production/productionRenderJob.ts",
        "src/production/renderIdentity.ts",
        "src/production/renditionIdentity.ts",
      ],
      symbol: ["type", "function", "property"],
      reference: contractReferences([
        "specifications/editorial-render-and-delivery/README.md",
        "specifications/editorial-render-and-delivery/delivery-package-provenance-and-publication.md",
        "specifications/editorial-render-and-delivery/render-budget-identity-and-recovery.md",
        "specifications/editorial-render-and-delivery/render-encoding-and-validation.md",
        "specifications/editorial-render-and-delivery/render-schedule-state-and-headless.md",
        "specifications/execution-and-recovery/README.md",
        "specifications/execution-and-recovery/artifacts-and-atomic-publication.md",
        "specifications/execution-and-recovery/resource-budgets-and-backpressure.md",
        "specifications/execution-and-recovery/retention-cleanup-and-quarantine.md",
      ]),
    },
  ],
};

export default {
  extends: "../../config/lint.config.ts",
  plugins: { evidence },
  rules: {
    "evidence/documented": [
      "error",
      { symbol: ["type", "function", "property"] },
    ],
    "evidence/graph": ["error", graph],
    "evidence/todo": "error",
  },
} satisfies ITtscLintConfig;
