import { type ITtscEvidenceGraphConfig, evidence } from "@ttsc/evidence";
import type { ITtscLintConfig } from "@ttsc/lint";

const graph: ITtscEvidenceGraphConfig = {
  claims: [
    {
      name: "model serialization implements interchange requirements",
      type: "typescript",
      files: ["src/exportModel.ts"],
      symbol: ["type", "function", "property"],
      reference: {
        type: "markdown",
        root: "../../docs",
        files: [
          "requirements/external-inputs/README.md",
          "requirements/external-inputs/conversion-receipts-and-determinism.md",
        ],
        symbol: ["h2", "h3"],
      },
    },
    {
      name: "model serialization implements interchange specifications",
      type: "typescript",
      files: ["src/exportModel.ts"],
      symbol: ["type", "function", "property"],
      reference: {
        type: "markdown",
        root: "../../docs",
        files: [
          "specifications/interchange-and-adoption/README.md",
          "specifications/interchange-and-adoption/conversion-receipts-and-determinism.md",
        ],
        symbol: ["h2", "h3"],
      },
    },
    {
      name: "screenplay formatting implements editorial text requirements",
      type: "typescript",
      files: ["src/screenplay.ts"],
      symbol: ["type", "function", "property"],
      reference: {
        type: "markdown",
        root: "../../docs",
        files: [
          "requirements/delivery-and-accessibility/README.md",
          "requirements/delivery-and-accessibility/captions-subtitles-and-cues.md",
          "requirements/editorial/README.md",
          "requirements/editorial/markers-effects-and-metadata.md",
        ],
        symbol: ["h2", "h3"],
      },
    },
    {
      name: "screenplay formatting implements editorial text specifications",
      type: "typescript",
      files: ["src/screenplay.ts"],
      symbol: ["type", "function", "property"],
      reference: {
        type: "markdown",
        root: "../../docs",
        files: [
          "specifications/editorial-render-and-delivery/README.md",
          "specifications/editorial-render-and-delivery/delivery-audio-text-and-localization.md",
          "specifications/editorial-render-and-delivery/rational-timeline-and-composition.md",
        ],
        symbol: ["h2", "h3"],
      },
    },
    {
      name: "caption sidecars implement timed-text requirements",
      type: "typescript",
      files: ["src/caption*.ts"],
      symbol: ["type", "function", "property"],
      reference: {
        type: "markdown",
        root: "../../docs",
        files: [
          "requirements/delivery-and-accessibility/README.md",
          "requirements/delivery-and-accessibility/captions-subtitles-and-cues.md",
          "requirements/delivery-and-accessibility/frame-rate-timebase-and-timecode.md",
          "requirements/rendering/README.md",
          "requirements/rendering/chunks-resume-and-recovery.md",
          "requirements/rendering/frame-schedules-and-sampling.md",
        ],
        symbol: ["h2", "h3"],
      },
    },
    {
      name: "caption sidecars implement delivery specifications",
      type: "typescript",
      files: ["src/caption*.ts"],
      symbol: ["type", "function", "property"],
      reference: {
        type: "markdown",
        root: "../../docs",
        files: [
          "specifications/editorial-render-and-delivery/README.md",
          "specifications/editorial-render-and-delivery/delivery-audio-text-and-localization.md",
          "specifications/editorial-render-and-delivery/rational-timeline-and-composition.md",
          "specifications/editorial-render-and-delivery/render-budget-identity-and-recovery.md",
          "specifications/editorial-render-and-delivery/render-schedule-state-and-headless.md",
        ],
        symbol: ["h2", "h3"],
      },
    },
    {
      name: "pose sidecars implement control-pass requirements",
      type: "typescript",
      files: ["src/poseKeypoint*.ts"],
      symbol: ["type", "function", "property"],
      reference: {
        type: "markdown",
        root: "../../docs",
        files: [
          "requirements/camera/README.md",
          "requirements/camera/validation.md",
          "requirements/lighting/README.md",
          "requirements/lighting/analysis-and-visual-validation.md",
          "requirements/rendering/README.md",
          "requirements/rendering/passes-channels-and-products.md",
          "requirements/repaint/README.md",
          "requirements/repaint/source-frames-and-reference-locking.md",
        ],
        symbol: ["h2", "h3"],
      },
    },
    {
      name: "pose sidecars implement control-pass specifications",
      type: "typescript",
      files: ["src/poseKeypoint*.ts"],
      symbol: ["type", "function", "property"],
      reference: {
        type: "markdown",
        root: "../../docs",
        files: [
          "specifications/camera-light-and-visibility/README.md",
          "specifications/camera-light-and-visibility/visibility-and-image-space-observation.md",
          "specifications/editorial-render-and-delivery/README.md",
          "specifications/editorial-render-and-delivery/render-products-visibility-and-color.md",
        ],
        symbol: ["h2", "h3"],
      },
    },
    {
      name: "render planning implements schedule and pass requirements",
      type: "typescript",
      files: ["src/guidePasses.ts", "src/plan.ts", "src/sequenceRenderPlan.ts"],
      symbol: ["type", "function", "property"],
      reference: {
        type: "markdown",
        root: "../../docs",
        files: [
          "requirements/editorial/README.md",
          "requirements/editorial/rational-time-and-ranges.md",
          "requirements/rendering/README.md",
          "requirements/rendering/encoding-and-multiplexing.md",
          "requirements/rendering/frame-schedules-and-sampling.md",
          "requirements/rendering/passes-channels-and-products.md",
          "requirements/rendering/scope-and-artifact-identity.md",
        ],
        symbol: ["h2", "h3"],
      },
    },
    {
      name: "render planning implements schedule and pass specifications",
      type: "typescript",
      files: ["src/guidePasses.ts", "src/plan.ts", "src/sequenceRenderPlan.ts"],
      symbol: ["type", "function", "property"],
      reference: {
        type: "markdown",
        root: "../../docs",
        files: [
          "specifications/editorial-render-and-delivery/README.md",
          "specifications/editorial-render-and-delivery/rational-timeline-and-composition.md",
          "specifications/editorial-render-and-delivery/render-encoding-and-validation.md",
          "specifications/editorial-render-and-delivery/render-products-visibility-and-color.md",
          "specifications/editorial-render-and-delivery/render-schedule-state-and-headless.md",
        ],
        symbol: ["h2", "h3"],
      },
    },
    {
      name: "render execution implements capture and encode requirements",
      type: "typescript",
      files: [
        "src/renderAndSee.ts",
        "src/renderVideo.ts",
        "src/sequenceRenderVideo.ts",
      ],
      symbol: ["type", "function", "property"],
      reference: {
        type: "markdown",
        root: "../../docs",
        files: [
          "requirements/rendering/README.md",
          "requirements/rendering/encoding-and-multiplexing.md",
          "requirements/rendering/frame-schedules-and-sampling.md",
          "requirements/rendering/scope-and-artifact-identity.md",
          "requirements/rendering/validation.md",
        ],
        symbol: ["h2", "h3"],
      },
    },
    {
      name: "render execution implements capture and encode specifications",
      type: "typescript",
      files: [
        "src/renderAndSee.ts",
        "src/renderVideo.ts",
        "src/sequenceRenderVideo.ts",
      ],
      symbol: ["type", "function", "property"],
      reference: {
        type: "markdown",
        root: "../../docs",
        files: [
          "specifications/editorial-render-and-delivery/README.md",
          "specifications/editorial-render-and-delivery/render-encoding-and-validation.md",
          "specifications/editorial-render-and-delivery/render-schedule-state-and-headless.md",
        ],
        symbol: ["h2", "h3"],
      },
    },
    {
      name: "chunk planning implements bounded render requirements",
      type: "typescript",
      files: ["src/chunkSequenceRender.ts"],
      symbol: ["type", "function", "property"],
      reference: {
        type: "markdown",
        root: "../../docs",
        files: [
          "requirements/rendering/README.md",
          "requirements/rendering/budgets.md",
          "requirements/rendering/chunks-resume-and-recovery.md",
          "requirements/rendering/passes-channels-and-products.md",
        ],
        symbol: ["h2", "h3"],
      },
    },
    {
      name: "chunk planning implements bounded render specifications",
      type: "typescript",
      files: ["src/chunkSequenceRender.ts"],
      symbol: ["type", "function", "property"],
      reference: {
        type: "markdown",
        root: "../../docs",
        files: [
          "specifications/editorial-render-and-delivery/README.md",
          "specifications/editorial-render-and-delivery/render-budget-identity-and-recovery.md",
          "specifications/editorial-render-and-delivery/render-products-visibility-and-color.md",
        ],
        symbol: ["h2", "h3"],
      },
    },
    {
      name: "headless capture implements platform and pass requirements",
      type: "typescript",
      files: ["src/headlessCapture.ts"],
      symbol: ["type", "function", "property"],
      reference: {
        type: "markdown",
        root: "../../docs",
        files: [
          "requirements/rendering/README.md",
          "requirements/rendering/headless-and-platform-determinism.md",
          "requirements/rendering/passes-channels-and-products.md",
          "requirements/rendering/validation.md",
        ],
        symbol: ["h2", "h3"],
      },
    },
    {
      name: "headless capture implements platform and pass specifications",
      type: "typescript",
      files: ["src/headlessCapture.ts"],
      symbol: ["type", "function", "property"],
      reference: {
        type: "markdown",
        root: "../../docs",
        files: [
          "specifications/editorial-render-and-delivery/README.md",
          "specifications/editorial-render-and-delivery/render-encoding-and-validation.md",
          "specifications/editorial-render-and-delivery/render-products-visibility-and-color.md",
          "specifications/editorial-render-and-delivery/render-schedule-state-and-headless.md",
        ],
        symbol: ["h2", "h3"],
      },
    },
    {
      name: "render budget evidence implements measurement requirements",
      type: "typescript",
      files: ["src/renderBudgetPreflight.ts", "src/renderObservationAudit.ts"],
      symbol: ["type", "function", "property"],
      reference: {
        type: "markdown",
        root: "../../docs",
        files: [
          "requirements/rendering/README.md",
          "requirements/rendering/budgets.md",
          "requirements/rendering/frame-identity-and-content-addressing.md",
          "requirements/rendering/passes-channels-and-products.md",
          "requirements/rendering/validation.md",
        ],
        symbol: ["h2", "h3"],
      },
    },
    {
      name: "render budget evidence implements measurement specifications",
      type: "typescript",
      files: ["src/renderBudgetPreflight.ts", "src/renderObservationAudit.ts"],
      symbol: ["type", "function", "property"],
      reference: {
        type: "markdown",
        root: "../../docs",
        files: [
          "specifications/editorial-render-and-delivery/README.md",
          "specifications/editorial-render-and-delivery/render-budget-identity-and-recovery.md",
          "specifications/editorial-render-and-delivery/render-encoding-and-validation.md",
          "specifications/editorial-render-and-delivery/render-products-visibility-and-color.md",
        ],
        symbol: ["h2", "h3"],
      },
    },
  ],
};

export default {
  extends: "../../config/lint.config.ts",
  plugins: { evidence },
  rules: {
    "evidence/documented": [
      "error",
      { symbol: ["type", "function", "property"] },
    ],
    "evidence/graph": ["error", graph],
    "evidence/todo": "error",
  },
} satisfies ITtscLintConfig;
